### ISSUE TITLE
impossible to take the title off the chart

### ISSUE THREAD

**Issue by Goodnato** [PHPOffice/PhpSpreadsheet#1000]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Take title

### What is the current behavior?
The title is null

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$title = new Title(null);

$chart = new Chart(
            'chart1', // name
            $title, // title
            null, // legend
            $plotArea, // plotArea
            true, // plotVisibleOnly
            0, // displayBlanksAs
            null, // xAxisLabel
            null,  // yAxisLabel
            $xAxis,  //xAxis
            $yAxis //yAxis
        );
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.2
PhpSpreadsheet master

It is like this: [Error](https://imgur.com/CxvZgY6)
As i want: [Success](https://imgur.com/mpT9WjD)

**Comment by oleibman** [comment]
`new Title(null)` was never really supported, but this had not been enforced in Release 1. Starting with Release 2, and, in particular PR #3793 in Jan. 2024, it became enforced through the use of native typing in the Title constructor.

Removing stale label, leaving issue closed.
