### ISSUE TITLE
Formula getCalculatedValue error with more than two INDIRECT

### ISSUE THREAD

**Issue by st875427** [PHPOffice/PhpSpreadsheet#1006]
This is:

```
- [O] a bug report
- [x] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When we want to use getCalculated on the formula which have more than two `INDIRECT` it should return a value.
For example: 
A1: `3`
B1: `4`
C1: `=INDIRECT("A1")+INDIRECT("B1")` 
getCalculatedValue C1 should be 7

### What is the current behavior?
When the formula had more than two INDIRECT, it will got error
```
PHP Fatal error:  Uncaught Error: Call to a member function getParent() on null in /home/yunjusu/report-renderer-library/vendor/phpoffice/phpspreadsheet/src/P
hpSpreadsheet/Cell/Cell.php:492
```

### My workaround solution
I add `$pCell->attach($pCellParent);` after line 3961 like this and it works.
```
$pCell->attach($pCellParent);
$result = call_user_func_array($functionCall, $args);
```
https://github.com/PHPOffice/PhpSpreadsheet/blob/1.7.0/src/PhpSpreadsheet/Calculation/Calculation.php#L3961

**Comment by oleibman** [comment]
Supplied code now generates correct result, even when I extend it to more than 2 INDIRECT's. Removing stale label, leaving issue closed.
