### ISSUE TITLE
CSV export of fomatted negative number

### ISSUE THREAD

**Issue by ShrekNZ** [PHPOffice/PhpSpreadsheet#1009]
This is: a bug report.
```
- [x] a bug report
```
### What is the expected behavior?
CSV export of the displayed negative number, even when formatted with a custom format code.

e.g. Number = -70
Format code is: #,##0;[Red]-#,##0

Should export as: "-70"

Old PHPExcel exported these numbers correctly.

### What is the current behavior?
Export as a mangled date and format code combination. For example, the above number and format code exports as: "[Sat, 10 Mar 1900 00:00:00 +0000190010]-#,##0"

### What are the steps to reproduce?

Create an Excel spreadsheet containing negative numbers formatted with the custom format code shown above. Use attached file: xx1.txt to do this.

Export created spreadsheet as CSV. Use attached file xx2.txt to do this.

### Which versions of PhpSpreadsheet and PHP are affected?

PHP 7.3.4
PhpSpreadsheet 1.7.0  (also affected 1.6.0)

[xx1.txt](https://github.com/PHPOffice/PhpSpreadsheet/files/3289077/xx1.txt)
[xx2.txt](https://github.com/PHPOffice/PhpSpreadsheet/files/3289078/xx2.txt)

**Comment by MarkBaker** [comment]
resolved in master
