### ISSUE TITLE
large excel file export issue

### ISSUE THREAD

**Issue by keval45** [PHPOffice/PhpSpreadsheet#1011]
I am trying to create an xlsx with 25000 rows and apprx. 75 columns with old phpexcel 1.7.8 ,1.8 and spreadsheet but not be able to generate xlsx file, it goes out of memory. i think capacity of writing an xlsx is much more than that. 
my default memory in php.ini is 1024M and is there any solution other than memory limit '-1'?
my execution time is 900s set in php.ini.
any other information is required from my side?

sample code is with phpexcel1.8
require_once 'Classes/1.8/PHPExcel.php';
require_once 'Classes/1.8/PHPExcel/IOFactory.php';
ini_set("display_errors","on");
error_reporting(-1);
$objPHPExcel = new PHPExcel();
 
for($i=0;$i<25000;$i++){
for($j=0;$j<76;$j++){
 $objPHPExcel->getActiveSheet()->setCellValueExplicitByColumnAndRow($j,$i,$j ,PHPExcel_Cell_DataType::TYPE_STRING);}
}
$objPHPExcel->setActiveSheetIndex(0);
$fileName="test".time()."_.xlsx";
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007'); 
$objWriter->save($fileName);

**Comment by MarkBaker** [comment]
Have you tried using cell caching? https://phpspreadsheet.readthedocs.io/en/latest/topics/memory_saving/ That was the approach that we took to try and reduce the memory footprint for larger workbooks.... but there are limits to reducing the memory requirements when we maintain the spreadsheet data as an in-memory model

**Comment by MarkBaker** [comment]
Also not that this is not a PHPExcel support forum; PHPExcel was deprecated in favour of PHPSpreadsheet which uses more modern features of PHP, and is more memory efficient

**Comment by keval45** [comment]
Hi Support,

Thanks for responding.
Yes, we read about PHPSpreadsheet is updated over PHPExcel. We had checked with PHPSpreadsheet for 25k rows having 75 columns with normal numeric values of column, but still it is not working, it throw some inner memory error.
Moreover, I read on stackoverflow that it is supporting large number of data but not sure either it require any caching mechanism or not.
Further, PHPSpreadSheet having functiaonality that  it writes all data together at the end of script. So, is there any way that it write data row by row instead of managing whole data together, that could be helpful to manage small memory chunks.

Also, Can you please assist me if any other way to manage large worksheet?

Thanks,

[cid:image001.png@01D52C33.82D132C0]<http://www.flydocs.aero/>
Keval Arora
Team Leader - PHP Development, FLYdocs
Intivia Tower, Plot No.117, Behind Prayosha Complex, Chhani Jakat Naka, Vadodara-390024, Gujarat, India
Office: +91 265 2761119/ M: +91 7043317171
keval.arora@flydocs.aero<mailto:keval.arora@flydocs.aero> | www.flydocs.aero<http://www.flydocs.aero/>

[cid:image002.png@01D52C33.82D132C0]<https://www.linkedin.com/company/flydocs>

[cid:image003.png@01D52C33.82D132C0]<https://vimeo.com/flydocs>
This email is confidential and may contain legally privileged information; it is intended for the use of the addressee only. If you are not the addressee you must not read, use, distribute, copy or rely on this email. If you have received this communication in error please notify us immediately by email or by telephone (+44 (0) 1827 289 186). The contents of this email do not constitute a commitment by FLYdocs Systems Ltd (FLYdocs), unless separately endorsed by an authorised representative of FLYdocs. Any views or opinions expressed are solely those of the author and do not necessarily represent those of the company. FLYdocs believes that this email and any attachments are free of viruses. However, it is the responsibility of the recipient to ensure it is virus free and FLYdocs does not accept any responsibility for any loss or damage that may arise from the use of this email or its contents.
