### ISSUE TITLE
How to use time value on Chart ?

### ISSUE THREAD

**Issue by jerikothomas** [PHPOffice/PhpSpreadsheet#1012]
I'm not able to use time values (hh:mm:ss) for charts there are only two `DATASERIES_TYPE` string and number, file output showing the render has failed
PHPspreadsheet: v1.6.0
PHP version: 7.2
[laporan_lost_time_2019 (21).xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3294030/laporan_lost_time_2019.21.xlsx)

**Comment by jerikothomas** [comment]
https://stackoverflow.com/questions/55935783/dataseriesvalues-for-time-values-in-chars

**Comment by MarkBaker** [comment]
Well a time value in MS Excel is a number; and you can apply a number format mask to chart values to display them as dates/times

**Comment by jerikothomas** [comment]
How to do that ?

**Comment by jerikothomas** [comment]
[laporan_lost_time_2019 (2).xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3299499/laporan_lost_time_2019.2.xlsx)

**Comment by jerikothomas** [comment]
yey I fixed it, thanks to @MarkBaker for the hint, my problems were the wrong sheet name
