### ISSUE TITLE
[Ticket#2019052701000038] security vulnerability in PhpSpreadsheet

### ISSUE THREAD

**Issue by usdResponsibleDisclosure** [PHPOffice/PhpSpreadsheet#1014]
Dear Sir or Madam,

In the course of a penetration test performed by our security analysts, we have noticed some security vulnerabilities in your software.

We would like to send you the findings in an encrypted manner to enable you to mitigate them. For encrypted communication, we can offer you a web-based platform hosted by us, or we can offer you to encrypt our e-mails via  S/MIME or PGP. Please let us know which method fits you best. In order to transmit our findings via email, we will need either your public S/MIME certificate or your public PGP key.

As stated in our Responsible Disclosure Guideline (see https://www.usd.de/wp-content/uploads/2017/10/usd-Responsible-Disclosure-EN.pdf), we will treat the vulnerabilities as confidential. We will grant you a time frame of 60 days to release a patch. After that deadline, we will reserve the right to publish the vulnerabilities. Since we already tried to contact you on 27 May via [redacted], the deadline ends on 26 July.

Sincerely,
usd responsible disclosure team

________________________________________

About usd AG

usd AG protects companies from hackers and criminals. As an accredited auditor, we consult and certify companies worldwide. Our work is as dynamic and diverse as current threats. We review IT systems, applications and processes for security vulnerabilities and help with their mitigation. With our Security Trainings, we raise security awareness; the CST Academy promotes an active dialogue and a transfer of knowledge.

www.usd.de
more security. usd

..........................................................................

Registered office: 63263 Neu-Isenburg
Local court of Offenbach: HRB 34667
Board of directors: Manfred Tubach
Chairman supervisory board: Dr. Dietmar Kirchner
VAT ID: DE 163774242
..........................................................................

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Mit freundlichen Grüßen
usd Responsible Disclosure Team

________________________________________

Über die usd AG

Die usd AG schützt Unternehmen vor Hackern und Kriminellen. Als akkreditierter Auditor beraten und zertifizieren wir Unternehmen weltweit. So dynamisch und vielfältig wie die Bedrohung ist unsere Arbeit. Wir prüfen IT-Systeme, Applikationen und Prozesse auf sicherheitsrelevante Schwachstellen und helfen bei deren Beseitigung. Mit unseren Security Awareness Trainings schaffen wir Sicherheitsbewusstsein, die CST Academy fördert Austausch und Wissenstransfer.

www.usd.de
more security. usd

.............................................................................

Sitz der Gesellschaft: 63263 Neu-Isenburg
Amtsgericht Offenbach: HRB 34667
Vorstand: Manfred Tubach
Aufsichtsratsvorsitzender: Dr. Dietmar Kirchner
USt-ID-Nr.: DE 163774242

.............................................................................

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sind nicht gestattet.

**Comment by MarkBaker** [comment]
On 17/06/2019 10:54, usdResponsibleDisclosure wrote:

In the course of a penetration test performed by our security analysts, we have noticed some security vulnerabilities in your software.

We would like to send you the findings in an encrypted manner to enable you to mitigate them. For encrypted communication, we can offer you a web-based platform hosted by us, or we can offer you to encrypt our e-mails via S/MIME or PGP. Please let us know which method fits you best. In order to transmit our findings via email, we will need either your public S/MIME certificate or your public PGP key.


As the main developer/administrator of the PHPSpreadsheet project, I am the person to contact; but I don't have secured email, so any communication would need to be through your web-based platform.


--
Mark Baker

 _________
|.  \     \-3
|_J_/ PHP |
|| |  __  |
|| |m|  |m|

 I LOVE PHP

**Comment by usdResponsibleDisclosure** [comment]
Dear Mr. Mark Baker,

As previously agreed, we are sending you a list of the security vulnerabilities we found in your software to the Email address listed in your Github profile: mark@lange.demon.co.uk. We provide our reports via our web-based platform FTAPI. You should have received an Email with further instruction by now.

Sincerely,
usd responsible disclosure team
responsible-disclosure@usd.de

________________________________________

About usd AG

usd AG protects companies from hackers and criminals. As an accredited auditor, we consult and certify companies worldwide. Our work is as dynamic and diverse as current threats. We review IT systems, applications and processes for security vulnerabilities and help with their mitigation. With our Security Trainings, we raise security awareness; the CST Academy promotes an active dialogue and a transfer of knowledge.

www.usd.de
more security. usd

..........................................................................

Registered office: 63263 Neu-Isenburg
Local court of Offenbach: HRB 34667
Board of directors: Manfred Tubach
Chairman supervisory board: Dr. Dietmar Kirchner
VAT ID: DE 163774242
..........................................................................

**Comment by MarkBaker** [comment]
Resolved in release 1.8.0
