### ISSUE TITLE
How can I make default page number to every sheet? 

### ISSUE THREAD

**Issue by moschel26** [PHPOffice/PhpSpreadsheet#1015]
My script to display page number like this :

    $sheet->getHeaderFooter()->setOddFooter('&R&P');

It works. But my problem is I have 3 sheet. On the every sheet display page number start of 1

I want in the sheet 1, it display page number 1-3. In the sheet 2, it will display page number 4-6. And the sheet 3, it display page number 7-9

I want like that. I had searching reference, but I don't find it

Please help me to solve this problem

**Comment by oleibman** [comment]
Suggested code now works correctly. Perhaps there problem has been fixed since 2019. Removing stale label, leaving issue closed.
