### ISSUE TITLE
How do I make automatic height row based on content

### ISSUE THREAD

**Issue by moschel26** [PHPOffice/PhpSpreadsheet#1016]
I had search reference and the reference say to try like this :

$objPHPExcel->getActiveSheet()->getRowDimension(37)->setRowHeight(-1);
$objPHPExcel->getActiveSheet()->getStyle('R37:Z37')->getAlignment()->setWrapText(true);

I try like that, but the result like this :

[![enter image description here][1]][1]

Should the height of row automatic added based content/text. But it does not added

How can I solve this problem?

  [1]: https://i.stack.imgur.com/LENys.png

**Comment by MarkBaker** [comment]
You also need to make the cell wrappable

**Comment by MarkBaker** [comment]
What writer are you using? xls?xlsx?

**Comment by moschel26** [comment]
xls
