### ISSUE TITLE
Cell types get lost when using removeColumnByIndex

### ISSUE THREAD

**Issue by jurgenhaas** [PHPOffice/PhpSpreadsheet#1034]
We do have spreadsheets with data like `12345.67890` formatted as a string in the xslx. Loading the data works just fine, the cell value is still a string and when we e.g. output to csv, we also get the full string as displayed above.

However, if we use `removeColumnByIndex` to remove a couple of columns from the spreadsheet, those string values get converted to floats and then the trailing zero gets lost. The value is then `12345.6789`

When avoiding to use `removeColumnByIndex`, everything is OK. I wasn't able to find out yet where and when the cast happens, but it is this single command.

Anyone an idea for this?

**Comment by MarkBaker** [comment]
My guess would be in the ReferenceHelper, that is executed whenever rows/columns are inserted/deleted to update any references that might require changes as a result; but until I investigate more deeply, that is just a guess

**Comment by czukowski** [comment]
I think this is where the data type gets lost:

https://github.com/PHPOffice/PhpSpreadsheet/blob/b2070fd18178af574bb6e0904b732d24875f4824/src/PhpSpreadsheet/ReferenceHelper.php#L438

It uses `setValue($cell->getValue())`, but perhaps it should rather use `setValueExplicit($cell->getValue(), $cell->getDataType())`.

**Comment by oleibman** [comment]
This is now working correctly. Leaving closed, removing stale label.
