### ISSUE TITLE
Warning: sqrt() expects parameter 1 to be float, string given

### ISSUE THREAD

**Issue by Arifi** [PHPOffice/PhpSpreadsheet#1035]
Hello,

Sorry but i got this error after parsing my Excel, all cells are dislayed well, except two warnings
`Warning: sqrt() expects parameter 1 to be float, string given in D:\projectfolder\wp-content\plugins\<plugin>\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Calculation\Calculation.php on line 3961
`
Any idea ?

**Comment by oleibman** [comment]
SQRT should now return Excel error if presented with non-numeric data. Removing stale label, leaving issue closed.
