### ISSUE TITLE
HtmlWriter comments are not html encoded

### ISSUE THREAD

**Issue by dstoever** [PHPOffice/PhpSpreadsheet#1038]
This is:

```
- [* ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Characters like < has to changed to &lt; in the cell comments

### What is the current behavior?
Characters like < are not html encoded

### What are the steps to reproduce?
Save a spreadsheet with characters like < in a cell comment

// add code that show the issue here...

The error is in Html.php line 1662
Now:
$result .= '<div class="comment">' . nl2br($pSheet->getComment($coordinate)->getText()->getPlainText()) . '</div>';

Should be:
$result .= '<div class="comment">' . nl2br(htmlspecialchars($pSheet->getComment($coordinate)->getText()->getPlainText())) . '</div>';

### Which versions of PhpSpreadsheet and PHP are affected?
1.7.0

**Comment by oleibman** [comment]
Fixed by PR #3957 in April 2024.
