### ISSUE TITLE
Splitting large CSV file into multiple worksheet not work properly

### ISSUE THREAD

**Issue by PhongNguyen512** [PHPOffice/PhpSpreadsheet#1039]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I expect when set `$spreadsheet->setActiveSheetIndexByName('name_here');` it return different set of data

### What is the current behavior?
I followed this example: https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Reader/14_Reading_a_large_CSV_file_in_chunks_to_split_across_multiple_worksheets.php

The system just return the 1st set of data of worksheet. I got a multiple sheet names after looping to split data into multiple worksheet

### What are the steps to reproduce?
```

```php
                $inputFileType = 'Csv';
                $inputFileName = '../web/opp1only.csv';
                $reader = IOFactory::createReader($inputFileType);

                $chunkSize = 1500;

                $chunkFilter = new ChunkReadFilter();
                $reader->setReadFilter($chunkFilter)->setContiguous(true);

                $spreadsheet = new Spreadsheet();
                $sheet = 0;

                for ($startRow = 0; $startRow <= 1500; $startRow += $chunkSize) {
                    $chunkFilter->setRows($startRow, $chunkSize);
                    $reader->setSheetIndex($sheet);
                    $reader->loadIntoExisting($inputFileName, $spreadsheet);
                    $spreadsheet->getActiveSheet()->setTitle('Data #' . (++$sheet));
                }
                $loadedSheetNames = $spreadsheet->getSheetNames();
                
                //This will return all of sheet name in a spreassheet
                foreach ($loadedSheetNames as $sheetIndex => $loadedSheetName) {
                    var_dump($loadedSheetName);
                }

                //I just only get the 1st 500 items from the  Data #1
                //If I change manually to 'Data #2' or #3. The data will be empty
                $spreadsheet->setActiveSheetIndexByName('Data #1');
                $sheetData = $spreadsheet->getActiveSheet()->toArray(null, false, false, true);
                var_dump($sheetData);
```

### Which versions of PhpSpreadsheet and PHP are affected?
phpoffice/phpspreadsheet: "^1.7"
php: ">=5.4.0"

**Comment by DhirajMaurya** [comment]
$inputFileType = 'xlsx';
$inputFileName = '**../web/opp1only.csv**';
$reader = IOFactory::createReader($inputFileType);

can we get dynamic  inputfilename file.
we try get dynamic but it generate error.
like this


Type: InvalidArgumentException

Message: File "employee_list_23_07_2019.xlsx" does not exist.

Filename: C:\xampp\htdocs\dhiraj\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Shared\File.php

Line Number: 137

Backtrace:

File: C:\xampp\htdocs\dhiraj\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\IOFactory.php
Line: 128
Function: assertFile

File: C:\xampp\htdocs\dhiraj\application\controllers\EmployeeController.php
Line: 343
Function: createReaderForFile

File: C:\xampp\htdocs\dhiraj\index.php
Line: 315
Function: require_once

**Comment by PhongNguyen512** [comment]
I already with my project, it work with dynamic file name. I think in your error that it said the file does not exist. Check the file path. I think the file path is wrong. The system could not reach the file, then it return that error to you.

**Comment by oleibman** [comment]
Supplied code seems to work correctly now (although I would change the starting value for `$startRow` to 2 rather than 0. For ease of testing, I did use much smaller chunks than 1500, but I don't think that should matter. Leaving issue closed, removing stale label.
