### ISSUE TITLE
Change return date format

### ISSUE THREAD

**Issue by phict** [PHPOffice/PhpSpreadsheet#1042]
This is:
- [x ] a feature request

### What is the expected behavior?
Possibility to set default format returned for date fields.

### What is the current behavior?
Always return m/d/yyyy

### What are the steps to reproduce?
using rangeToArray with formated returns always return in m/d/yyyy.
should be possible to set date return values similar to StringHelper::setDecimalSeparator

setting the below line to yyyy-mm-dd works but cannot find a way of changing this outside the source.
NumberFormat.php
self::$builtInFormats[14] = 'm/d/yyyy';

**Comment by oleibman** [comment]
Addressed by PR #3939, merged in March 2024.
