### ISSUE TITLE
1.8 fix breaks xmlreader when opening multiple files

### ISSUE THREAD

**Issue by rtek** [PHPOffice/PhpSpreadsheet#1045]
This is a bug report.

```
<?php

use PhpOffice\PhpSpreadsheet\Reader\Xlsx;
use PHPUnit\Framework\TestCase;

class BugTest extends TestCase
{
    public function testDev(): void
    {
        $reader = new Xlsx();
        $reader->load('tests/test1.xlsx');
        unset($reader);

        $reader = new \XmlReader();
        $reader->open('tests/test2.xlsx');
    }
}
```

```
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 462 ms, Memory: 10.00MB

There was 1 error:

1) BugTest::testDev
XMLReader::open(): Unable to open source data

tests\BugTest.php:20
```

### Which versions of PhpSpreadsheet and PHP are affected?
`1.8, 7.2`

### Cause

XmlScanner will not leave scope until the script terminates since its reference is stored in the shutdown handler callback. Resetting of the xml entity loader setting has to be done in a function and not in a method. 

https://github.com/PHPOffice/PhpSpreadsheet/commit/0e6238c69e863b58aeece61e48ea032696c6dccd#diff-5c5eea600b92ba6e320a104de4fbb16eR35

**Comment by rtek** [comment]
This also impacts `\DOMDocument` due to its use of libxml.

**Comment by MarkBaker** [comment]
I'm open to suggestions on how to fix this.... I just don't know how I can do so, other than reverting to the previous approach where it wasn't being used correctly when the xml was being parsed, which made it insecure. How can I practically restore the xml entity loader setting to its previous value?

Please somebody, before y development laptop goes flying through my 4th floor window.

I do not want to leave a security issue, and an open CVE.

**Comment by MarkBaker** [comment]
Remembering that it especially needs to be reset to its original value with PHP 7.2.0, 7.1 <= 7.1.12, 7.0 <= 7.0.26 and PHP 5.6, where it isn't thread-safe, even in the event of a fatal error
