### ISSUE TITLE
COUNTIF() doesn't count properly when use expression in criteria

### ISSUE THREAD

**Issue by joachimstalder** [PHPOffice/PhpSpreadsheet#1046]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
`COUNTIF(A1:A5, "<4")` formula in `C1` must return correct count (1) for values (6, 3, 4, X, '') in range `A1:A5` when evaluated with `$excelWorksheet->getCell('C1')->getCalculatedValue()` and as well when opening Excel file, in cell `C1`, it must be 1.

### What is the current behavior?
The formula return 3, which is not correct. It evaluate X and '' as smaller than 4.
When I open the Excel file and edit the formula in `C1` with F2 then Enter, the formula is now correctly evaluated.
Still in Excel, if I use the "refresh all" button, nothing change, formula return still a wrong value.

### What are the steps to reproduce?
```
$excelFile = new Spreadsheet();
$excelWorksheet = $excelFile->getActiveSheet();
$excelWorksheet->setCellValue('A1', 6);
$excelWorksheet->setCellValue('A2', 3);
$excelWorksheet->setCellValue('A3', 4);
$excelWorksheet->setCellValue('A4', 'X');
$excelWorksheet->setCellValue('A5', '');
$excelWorksheet->setCellValue('C1', '=COUNTIF(A1:A5,"<4")');
$excelWorksheet->setCellValue('C2', 'Formula in C1: =COUNTIF(A1:A5,"<4")');
$excelWorksheet->setCellValue('C3', 'Expected in C1: 1 not 3 because X and \'\' are not smaller than 4, only 3 is smaller');
$test2 = $excelWorksheet->getCell('C1')->getCalculatedValue();
// Generate the Excel file
$excelFileWriter = new Xlsx($excelFile);
$excelFileWriter->save('php://output');
```
### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.7.0
PHP 7.1.19

**Comment by PhongNguyenSandbox** [comment]
For some unknown reasons, I can't use the COUNTIF, but the SUMPRODUCT can be useful in here. I'm using SUMPRODUCT in my backend right now to solve that problem. The SUM or SUMPRODUCT can be an alternative way of COUNTIF. You can google it.

Also, some formulas won't work if you use in PhpSpreadSheet, but when you test those formulas in the real excel, it will work perfectly.

**Comment by joachimstalder** [comment]
@PhongNguyenSandbox, thanks for your comment and idea for `SUMPRODUCT`.
`COUNTIF` works in some way but not completly. When criteria is only a value or a cell, it works. For example, according to my case above, `=COUNTIF(A1:A5, 4)` will return 1 and it's correct

**Comment by joachimstalder** [comment]
In fact COUNTIF works well when we don't use an expression ("<4" in my case) but a value (4). When I set 4 in my exemple, it works and will return 1

**Comment by MarkBaker** [comment]
Fixed in master

**Comment by datasofi** [comment]
I am finding the same issue with this formula =COUNTIF(Sheet2!D9:I9;">0,80") 
Is it a bug with the ">0,80" part?
I am using a Spain locale, so decimals are split by comma instead of a dot

**Comment by MarkBaker** [comment]
If you were setting PhpSpreadsheet's Calculation Engine locale to Spanish, then you should be using `CONTAR.SI` instead of `COUNTIF`, though I suspect that the use of the comma decimal separator would still be a problem in this case.

If you're not setting PhpSpreadsheet's Calculation Engine locale to Spanish, then use the `,` argument separator, and `0.80` for the decimal value. Language/Locale settings are not 100%

**Comment by datasofi** [comment]
Thanks for the comment! 
I did change the locale:
$locale = 'es';
$validLocale = \PhpOffice\PhpSpreadsheet\Settings::setLocale($locale);

Funny thing is that next to it, I have another cell with this formula =COUNTIF(Sheet2!L9;"<4") which works fine. It's really puzzling. I am not playing with changing the formula to see if the problem goes away. Will keep in touch.

**Comment by datasofi** [comment]
In the end I assumed it is a bug in PhpSpreadsheet and changed the formula to:
=SUM(IF(D9>0,8;1;0);IF(E9>0,8;1;0);IF(F9>0,8;1;0);IF(G9>0,8;1;0);IF(H9>0,8;1;0);IF(I9>0,8;1;0))
and it works fine now. I am guessing there are issues with the COUNTIF implementation somewhere. Maybe the "0,8" was the issue, as the COUNTIF with "4" in the greather than rule worked.
