### ISSUE TITLE
Uncaught error when opening ods file in 1.8.1

### ISSUE THREAD

**Issue by franksl** [PHPOffice/PhpSpreadsheet#1047]
Hello,
When trying to open an ods file downloaded from google drive I receive this exception:

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PhpOffice\PhpSpreadsheet\Reader\Ods\Properties::setCoreProperties() must be an instance of SimpleXMLElement, array given, called in /my/path/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods/Properties.php on line 27 and defined in /my/path/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods/Properties.php:39

Thanks,
Frank

**Comment by MarkBaker** [comment]
Fixed in 1.8.2 release

**Comment by AdamReece-WebBox** [comment]
Hello,

This still seems to happen in 1.8.2:

> In Properties.php line 39:
> 
>   [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Type error: Argument 2 passed to PhpOffice\PhpSpreadsheet\Reader\Ods\Properties::setCoreProperties() must be an instance of Sim
>   pleXMLElement, instance of stdClass given, called in /var/www/intranet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reade
>   r/Ods/Properties.php on line 27
> 
> 
> Exception trace:
>  () at /var/www/intranet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods/Properties.php:39
>  PhpOffice\PhpSpreadsheet\Reader\Ods\Properties->setCoreProperties() at /var/www/intranet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods/Properties.php:27
>  PhpOffice\PhpSpreadsheet\Reader\Ods\Properties->load() at /var/www/intranet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods.php:284
>  PhpOffice\PhpSpreadsheet\Reader\Ods->loadIntoExisting() at /var/www/intranet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods.php:246
>  PhpOffice\PhpSpreadsheet\Reader\Ods->load() at /var/www/intranet/src/WebBox/ClientBundle/Command/ImportLegacyIntranetCommand.php:123

**Comment by AdamReece-WebBox** [comment]
This happens in 1.9.0 too.
