### ISSUE TITLE
Wrong Implementation psr-16

### ISSUE THREAD

**Issue by dusta** [PHPOffice/PhpSpreadsheet#1049]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
Error:
`Fatal error: Uncaught TypeError: Argument 1 passed to Driver::deleteItems() must be of the type array, object given, called in Psr16Adapter.php on line 178 and defined in lib/Phpfastcache/Core/Pool/CacheItemPoolTrait.php:297
`

### What is the expected behavior?
must be of the type array,

### What is the current behavior?
Object given

### What are the steps to reproduce?
Set cache adapter

```php
<?php

\PhpOffice\PhpSpreadsheet\Settings::setCache($Psr16Adapter);
```

**Comment by PowerKiKi** [comment]
This is not PhpSpreadsheet code, you are referencing code from another library. File a bug with that other library.

**Comment by dusta** [comment]
@PowerKiKi I show example how to reproduce error. 

https://github.com/PHPOffice/PhpSpreadsheet/blob/master/docs/topics/memory_saving.md

```php
$cache = new MyCustomPsr16Implementation();
\PhpOffice\PhpSpreadsheet\Settings::setCache($cache);
```

This not compatible with PSR-16

**Comment by PowerKiKi** [comment]
Those two lines of code have nothing to do with PSR-16. And they tell me nothing useful for PhpSpreadsheet. The implementation of `MyCustomPsr16Implementation` is incorrect/buggy, not PhpSpreadsheet.

Your lib incorrectly type hint array:

https://github.com/PHPSocialNetwork/phpfastcache/blob/5f12dab09b888383db754d941f2953cb4c876011/lib/Phpfastcache/Core/Pool/CacheItemPoolTrait.php#L297

But the PSR-16 specification clearly allow an iterable, not only an array:

https://github.com/php-fig/simple-cache/blob/408d5eafb83c57f6365a3ca330ff23aa4a5fa39b/src/CacheInterface.php#L88

Again there is nothing wrong with PhpSpreadsheet
