### ISSUE TITLE
Ods writer: add support for basic text styling

### ISSUE THREAD

**Issue by agopaul** [PHPOffice/PhpSpreadsheet#105]
The Ods writer doesn't support font styles like color, size, bold, italic, single underline, cell background.

Of course, this is a feature rather than a bug, but since I already implemented this on PHPExcel (see PR pending for PHPExcel https://github.com/PHPOffice/PHPExcel/pull/785) I thought maybe I could port the PR here. 

Also, since PhpSpreadsheet now has a working testing/CI environment, I'm writing a few unit tests for the Ods writer too.

I will reference the PR to this issue when it's ready

**Comment by PowerKiKi** [comment]
Thanks, looking forward to it.

For unit tests, it would be great to limit the use of binary files in the repository, either by not using any at all or re-using the existing one. But I guess you won't need any of them to test writing things.

**Comment by agopaul** [comment]
I shouldn't need any binary file, but since some methods return XML strings I'm wondering which is the preferred method to test XML output. XML it's not binary per se, but it can increase the weight on the repository in the long term. On the other hand, XML is still plain text and it's easy to merge if that was your point.

I can see two solutions for these kinds of tests where the XML output needs to be tested:
- take the output and test it against an XML file inside the repository (using PHPUnit's assertXmlStringEqualsXmlFile(), which uses DOMDocument and makes a comparison at structure level, not simple string comparison)
- take the output and parse it with DOMDocument or SimpleXML, checking each attributes and values

Both solutions have pros and cons. Most notably, the second approach could result in more verbose unit tests (lots of assertions or data inside the tests).
On the other hand, the first approach puts a little more weight on the repository and it could theoretically result in less maintainable (but likely more precise) tests.

My choice between the two would be the first approach because is can be more precise and, of course, the tests are faster to write.

I looked in the test suite for tests which used one solution or the other but I couldn't find any.

What do you think should be the preferred solution? I guess this can become a guideline for future tests too.

**Comment by PowerKiKi** [comment]
I am OK with the first solution. Hopefully it does not becomes too huge too soon, but like you said it seems to be the easiest way for now.
