### ISSUE TITLE
Use of INDIRECT with range generates exception during range calculation

### ISSUE THREAD

**Issue by tominventisbe** [PHPOffice/PhpSpreadsheet#1051]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
PhpSpreadsheet correctly inserts the formula.

### What is the current behavior?
PhpSpreadsheet fails on trying to calculate the range.

### What are the steps to reproduce?
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(
    1,
    1,
    "=SUM(INDIRECT(ADDRESS(4,12,4)):INDIRECT(ADDRESS(4,15,4)))"
);

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save('php://output');
```

This generates the following warning:

```
Worksheet!K4 -> Warning: trim() expects parameter 1 to be string, array given

in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php (line 3688) 
...
```

This is the line that looks like:

```php
if ((trim($operand1Data['value']) != '') && (is_numeric($operand1Data['value']))) {
                                    $operand1Data['reference'] = $pCell->getColumn() . $operand1Data['value'];
                                }
```

I took the liberty of giving you the actual location of the problem instead of the one shown by the exception; since none of the rethrown exceptions pass any `previous` values, you only see the higher-level error that points to a mostly irrelevant location.

The same likely applies for the second operand.

This formula works fine in LibreOffice Calc, but the data here becomes an array, likely due to the use of `INDIRECT`, which the range calculation `:` does not check for (yet).

A workaround is to use commas instead of ranges, but you will need to manually specify all cells in the range, in that case.

### Which versions of PhpSpreadsheet and PHP are affected?
Tested on PhpSpreadsheet 1.7.0 and PHP 7.3.

**Comment by tominventisbe** [comment]
This is still an issue.

**Comment by tominventisbe** [comment]
Bot: this is still an issue.

**Comment by tominventisbe** [comment]
Bot: this is still an issue.

**Comment by tominventisbe** [comment]
Bot: this is still an issue.

**Comment by tominventisbe** [comment]
Bot: this is still an issue.

**Comment by tominventisbe** [comment]
Bot: this is still an issue.

**Comment by PieterCappelle** [comment]
Did you find any solution?

**Comment by oleibman** [comment]
Supplied code now works correctly (using `getCell('A1')->setValue(...)`). Leaving closed, removing stale label.
