### ISSUE TITLE
cannot get jump values

### ISSUE THREAD

**Issue by alucardwind** [PHPOffice/PhpSpreadsheet#1057]
i create a xlsx file in excel 2016 with two sheets. 
In the first sheet i input aa in A1 cell.
In the second sheet i input directing to sheet1 A1 cell in sheet2 A1 cell.
![sheet1](https://user-images.githubusercontent.com/51143541/60654654-f7161c00-9e7e-11e9-9b71-608efa1f3bf6.JPG)
![sheet2](https://user-images.githubusercontent.com/51143541/60654659-f9787600-9e7e-11e9-9e31-5908bd6de330.JPG)

then i use phpspreadsheet to read sheet2 A1 cell.
```
$spreadsheet = $reader->load($filename);
$activeSheet = $spreadsheet->getSheetByName('sheet2');
$value = $activeSheet->getCell('A1')->getValue();
```
i just need $value get "aa" which in sheet1 A1 cell.
but $value get "=Sheet1!A1",
what should i do?

**Comment by MarkBaker** [comment]
You need to load both sheets; PHPSpreadsheet cannot get the value from sheet 1 if you've only loaded sheet 2. PHPSpreadsheet cannot execute that calculation without access to the worksheet that is referenced.
You also need to get the calculated value (using the `getCalculatedValue()` method), not the value. There is a [section in the documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/accessing-cells/#retrieving-a-cell-value-by-coordinate) that explains this; and many of the examples demonstrate how to get calculated values
