### ISSUE TITLE
cannot get Excel conditional format background color

### ISSUE THREAD

**Issue by alucardwind** [PHPOffice/PhpSpreadsheet#1058]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
**first, i am sorry to ask usage question here, because stackoverflow did not work in my network.**

i set cell background color is null, then use conditional format. Build a ruler which change the cell background color to red.
`$value = $activeSheet2->getStyle('B1')->getFill()->getStartColor()->getRGB();`
i need to get the new background color "red" or red RGB CODE,
but only "000000"

**Comment by MarkBaker** [comment]
```
$spreadsheet->getActiveSheet()
    ->getCell('B1')
    ->getDataValidation();
```
Will get the data validation for a cell; but there is no method to identify which rule from that set of data validations is applied based on the cell value, or subsequently to determine which style will be applied for that rule

**Comment by oleibman** [comment]
This can now be done using the StyleMatcher and CellAssessor classes. This was done to great effect in PR #4412. However, it can get a little complicated. Reopening this ticket while I work on simplifying it.
