### ISSUE TITLE
Importing values with apostrophe prefix (Xlsx)

### ISSUE THREAD

**Issue by serverdevil** [PHPOffice/PhpSpreadsheet#1061]
When importing Xlsx files, a cell value preceded with apostrophe in Excel e.g. `'1234` is returned as plain `1234`.

I went about looking at the xlsx file (xl\worksheets\sheet1.xml) but couldn't find any reference to how excel determines if the value has a preceding apostrophe. No where in the cell's data or the associated styles. Tried digging up some OOXML schema files from Microsoft but no luck.

Could @MarkBaker or other maintainers suggest where could I go looking?

Usecase: A cell value with apostrophe prefixed suggests that the value should be rendered as is, regardless of the cell's formatting or datatype. I need to know if the cell has apostrophe when reading using PHPSpreadsheet.

**Comment by MarkBaker** [comment]
It's a cell style of quotePrefix
```
$spreadSheet->getActiveSheet()
    ->getCell('A2')
    ->getStyle()
    ->setQuotePrefix(true);
```

**Comment by serverdevil** [comment]
Guess I didn't look hard-enough at the styles. Thanks Mark!
Will keep my eyes peeled next time.
