### ISSUE TITLE
LGPL license version ?

### ISSUE THREAD

**Issue by adelambe** [PHPOffice/PhpSpreadsheet#1065]
This is:

```
- [ ] a information request

### What is the license version ?
LGPL 2.1 or LGPL 3

**Comment by MarkBaker** [comment]
As it says: LGPL-2.1-or-later: [![License](https://poser.pugx.org/phpoffice/phpspreadsheet/license.png)](https://packagist.org/packages/phpoffice/phpspreadsheet)
