### ISSUE TITLE
Drawing - Move and size with cells

### ISSUE THREAD

**Issue by cloelke** [PHPOffice/PhpSpreadsheet#1067]
This is:
- [x ] a feature request

### What is the expected behavior?
Drawing
Move and size with cells

### What is the current behavior?
Move but don't size with cells

### What are the steps to reproduce?

The following page has an example of a mod they did, but this does not make it an option.
https://stackoverflow.com/questions/50870112/phpspreadsheet-drawing-move-and-size-with-cells?rq=1

**Comment by mylawacad** [comment]
Also faced the same issue today. Much appreciated if there is a change that allows to filter rows with images

**Comment by oleibman** [comment]
Should be fixed by PR #2532 and PR #2674.
