### ISSUE TITLE
PHPUnit: Tests: 367, Assertions: 627, Errors: 218, Skipped: 1

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PhpSpreadsheet#107]
I have run `$ ./vendor/phpunit/phpunit/phpunit --verbose > phpunit.log` on latest `develop` code (no changes in my fork), the produced logfile is rather large, so I uploaded it on my server:

https://cloud.mxchange.org/index.php/s/149vSQYmDeENiuY/download?path=%2FPHPSpreadsheet&files=phpunit.log

**Comment by PowerKiKi** [comment]
Closing because it is not clear what you want, and [Travis is passing on all PHP versions on latest commit](https://travis-ci.org/PHPOffice/PhpSpreadsheet/builds/207072691).

Please dig deeper to understand why your results are so different from Travis'. And please try to explain better the situation, with a more precise title and more complete description.

**Comment by Quix0r** [comment]
Okay, I only wanted to report it. Nothing more. And I cannot belive that it is passed, my version is `PHP 7.0.16-1~dotdeb+8.1 (cli) ( NTS )` and sure has issues.

**Comment by Quix0r** [comment]
`PHP 7.0.17-1~dotdeb+8.1 (cli) ( NTS )` is still reporting a lot failing issues:

> Tests: 369, Assertions: 628, Errors: 218, Skipped: 1.

Maybe Travis is missconfigured?

**Comment by gmsantos** [comment]
`./vendor/bin/phpunit --verbose > phpunit.log` results on the same issue?

**Comment by Quix0r** [comment]
Updated logfile, no change, same issues found. Mostly first parameter in test methods seem not be set (which is what I would expect). Maybe update test units against latest stable version of PhpUnit?

**Comment by PowerKiKi** [comment]
Several contributors tested PhpSpreadsheet with success in a variety of environments. The chance that there is something so wrong with PhpSpreadsheet itself is extremely slim. Something in your environment must be different, but there not much we can do without an access to said environment.

I suggest you build a brand new virtual machine, see that it works and then change it to replicate your current environment. And see exactly what modification breaks the test suit.
