### ISSUE TITLE
Request chart secondary Y axis

### ISSUE THREAD

**Issue by ShintaroNitta** [PHPOffice/PhpSpreadsheet#1072]
This is:

```
- [ ] a bug report
- [*] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

I want to add secondary Y axis to a chart.

### What is the current behavior?

There is no feature to add the secondary Y axis for now.

### Which versions of PhpSpreadsheet and PHP are affected?

Current version (1.8.2)

**Comment by ShintaroNitta** [comment]
I have already tried to add this feature in this PR.
https://github.com/PHPOffice/PhpSpreadsheet/pull/1073/files

**Comment by oleibman** [comment]
I'm afraid so. I haven't made any headway in figuring out how to implement it.
