### ISSUE TITLE
export excel, cell is empty whith formula countifs

### ISSUE THREAD

**Issue by sbonoseyte** [PHPOffice/PhpSpreadsheet#1074]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
apply formula countifs in cell when I'm going to export excel from array.

### What is the current behavior?
When I write formula, excel result cell is blank. I test with countif and  It well works.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example]

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$formulaVtoBase = '=COUNTIFS(C1:C4, 0, D1:D4, 0)';

```

### Which versions of PhpSpreadsheet and PHP are affected?
last  1.8.2

**Comment by MarkBaker** [comment]
You are aware that the `COUNTIFS()` function isn't implemented yet in any released version of PHPSpreadsheet? And is documented as such: [Function List by Name](https://github.com/PHPOffice/PhpSpreadsheet/blob/1.8.2/docs/references/https://github.com/PHPOffice/PhpSpreadsheet/blob/1.8.2/docs/references/function-list-by-name.md)

Code to implement `COUNTIFS()` has literally just been merged into the master branch yesterday
