### ISSUE TITLE
Is it a bug when import xlsx file?

### ISSUE THREAD

**Issue by nilcay** [PHPOffice/PhpSpreadsheet#1083]
if i use "\PhpOffice\PhpSpreadsheet\Reader\Xlsx()" to load file, my system will not be able to load the Xml files of the website. This problem also arises in PHPExcel-1.8.1, I must kill the php-cji processes to restart my web system. But the old version of PHPExcel did not have this problem.

**Comment by MarkBaker** [comment]
Insufficient information; I can't even clearly understand the problem other than simply "it won't load a file"... the only thing that I can think of with your reference to xml files is that you're running a version of PHP with the non-thread safe version of `libxml_disable_entity_loader()`, which is set true by PHPSPreadsheet as a security measure.
If this is the case, upgrade your PHP to a version that supports the thread-safe function; or read the notes in the ChangeLog.
