### ISSUE TITLE
SUMIF not working with multiple lines

### ISSUE THREAD

**Issue by mcmacfitter** [PHPOffice/PhpSpreadsheet#1090]
This is:

```
- [ *] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I have a few SUMIF formulas which calculate the sum from another sheet. 
The first sheet (List) contains a list of about 500 entries with several columns, including a column "name" (column B) and a column with a price in euros (column L).
The second sheet contains the unique names from sheet 1 (column A) the formulas (column B):
$sheet->setCellValue('B2', "=SUMIF(List!C:C,A2,List!L:L)");
$sheet->setCellValue('B3', "=SUMIF(List!C:C,A3,List!L:L)");
$sheet->setCellValue('B4', "=SUMIF(List!C:C,A4,List!L:L)");
and so on.....

### What is the current behavior?
The formula is not applied to all lines. Only the first rows are calculated. So the sum is not correct. 
For example the correct sum is 1000 but it shows only 500. If I select the cell with the formula and press enter, the sum is calculated correctly. So the formula is correct.

I found out it works correctly if I use =SUMIF(List!C2:C500,A3,List!L2:L500) instead of =SUMIF(List!C:C,A3,List!L:L). So this is a workaround for me.
But because I want to be flexible and don't want to change the whole formula after adding or removing a line, I wanted to post this topic here. Do you have any idea?

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

//

// add code that show the issue here...
$sheet->setCellValue('B2'=SUMIF(List!C:C,A2,List!L:L)");
$sheet->getStyle('B2')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_CURRENCY_EUR_SIMPLE);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet Version: 1.6.0
PHP Version 5.6.40

**Comment by MarkBaker** [comment]
Please, please, please..... I've said this many, many times..... row and column ranges are NOT implemented in the PHPSpreadsheet calculation engine; cell ranges are implemented; so `C:C` or `1:1` will not work, `C1:C100` or `A1:IV1` will work

**Comment by mcmacfitter** [comment]
Okay, thanks for your feedback. I searched for that topic but found nothing.
Ticket can be closed.
