### ISSUE TITLE
Hyperlink as function bug

### ISSUE THREAD

**Issue by Adrianotiger** [PHPOffice/PhpSpreadsheet#1091]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Adding a Formula "HYPERLINK" the link should open this link even if it is in another sheet.

### What is the current behavior?
Adding the formula "HYPERLINK" I get a message "Reference isn't valid"

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$spreadsheet->createSheet();
$sheet = $spreadsheet->getActiveSheet();

$sheet->setCellValue('A1', 'Link');

$sheet = $spreadsheet->getSheet(1);
$sheet->setCellValue('A1', 'ID')
      ->setCellValue('B1', 'Name');
$sheet->setTitle("Sheet2");

$dataContacts = [];
for($k=0;$k<20;$k++)
  array_push($dataContacts, array($k+1, "Name " . chr(65+$k)));
$sheet->fromArray($dataContacts, NULL, 'A2');
$sheet->setAutoFilter($sheet->calculateWorksheetDimension());

$sheet = $spreadsheet->getSheet(0);
$sheet->setTitle("Sheet1");
for($j=2;$j<15;$j++)
  $sheet->getCell('A' . $j)->setValue('=HYPERLINK("#Sheet2!"&ADDRESS(MATCH(' . $j . ',Sheet2!A:A,0),1),"LINK TO ID ' . $j . '")');

header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
header("Content-Disposition: inline; filename='test.xlsx'");
$writer = new Xlsx($spreadsheet);  
$writer->save('php://output');
```

Every time a Hyperlink function is added, it seems that PhpSpreadsheet will add a *real* hyperlink to this cell. 
In this example, you can click every link up to the last one. If you want to click the last one, this message is shown: "Reference isn't valid".

If you click on this cell and remove the hyperlink, the formula is used again and it will work.

### Which versions of PhpSpreadsheet and PHP are affected?

Version 1.7 and PHP 7.3

Edit: Added autofilter to the second sheet. Now, if you order the data, the hyperlink is still linking the (wrong) cell and the function is not executed. Once you remove the link, from the cell, you can click on it and it will rediret you to the right cell.

**Comment by Adrianotiger** [comment]
If I change the Calculation.php file (row 1000) from:
```
'HYPERLINK' => [
            'category' => Category::CATEGORY_LOOKUP_AND_REFERENCE,
            'functionCall' => [LookupRef::class, 'HYPERLINK'],
            'argumentCount' => '1,2',
            'passCellReference' => true,
        ],
```

to 
```

'HYPERLINK' => [
            'category' => Category::CATEGORY_LOOKUP_AND_REFERENCE,
            'functionCall' => [LookupRef::class, 'HYPERLINK'],
            'argumentCount' => '1,2',
            //'passCellReference' => true,
        ],
```

it works like expected. Don't know if this is the solution as I don't know how it is calculated. But in this way I don't have the hyperlink as overlay over the formula.

**Comment by oleibman** [comment]
Supplied code seems to work as desired. Leaving issue closed, removing stale label.
