### ISSUE TITLE
A non-numeric value encountered getCalculatedValue

### ISSUE THREAD

**Issue by hungbu** [PHPOffice/PhpSpreadsheet#1092]
This is:

```
- [x] a bug report

```

### What is the expected behavior?
load and save file:  
https://drive.google.com/file/d/1iJY5_F0TNrVWQfkUxaAVj-XMquYfnMOO/view?usp=sharing
error: 
https://drive.google.com/file/d/1FfwjooMKOABZmuDfuCvfoBKUsrTcgFWd/view?usp=sharing
### What are the steps to reproduce?

load and save file:  
https://drive.google.com/file/d/1iJY5_F0TNrVWQfkUxaAVj-XMquYfnMOO/view?usp=sharing

I have asked the question on the link: 
https://stackoverflow.com/questions/57081089/a-non-numeric-value-encountered-getcalculatedvalue
[hinoez_en.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3403051/hinoez_en.xlsx)

```php
<?php

public function gen_file_download_tt(&$result) {

        $language = $this->getlocal();
        $excel_tempate = public_path(). "/excel/template/truyenthong_".$language.".xlsx";
        $ex = new Excel();
        $ex->load($excel_tempate);


        $file_name = 'BangTinh_TruyenThong_Thang_'.Date('YmdHis').'.xlsx';
        $excel_result = public_path(). "/excel/download/".$file_name;
        $ex->save($excel_result);

        $ex->free();
        return $file_name;
    }
```

### Which versions of PhpSpreadsheet and PHP are affected?
laravel 5.8
php 7.1
phpoffice/phpspreadsheet [1.7.0] - 2019-05-26

**Comment by hungbu** [comment]
I have found the cause of the error here

[E22] = PMT (D20 / 12, D19, -E23, D7.0)

error returned value: #VALUE

so open excel does not save.

**Comment by MarkBaker** [comment]
`[E22] = PMT (D20 / 12, D19, -E23, __D7.0__)`

What is `D7.0`? Because this is an invalid formula in MS Excel

**Comment by hungbu** [comment]
Yes, i know that.
Thanks for support.
