### ISSUE TITLE
Import WPS EXCEL, Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by ryvlon** [PHPOffice/PhpSpreadsheet#1094]
This is:

```
- [ ] a bug report
```

### What is the current behavior?
![图片](https://user-images.githubusercontent.com/16218491/61508380-1cc52880-aa1c-11e9-888e-a0eb07e36b2b.png)

### What are the steps to reproduce?
![图片](https://user-images.githubusercontent.com/16218491/61508559-066b9c80-aa1d-11e9-9464-e30ea8fa0fb7.png)

**Comment by MarkBaker** [comment]
Yes, I'm afraid that spreadsheets use memory when they are loaded into memory; and memory usage is generally limited by PHP. If the spreadsheet is too big, then it can exceed those memory limits

**Comment by ryvlon** [comment]
> 
> 
> Yes, I'm afraid that spreadsheets use memory when they are loaded into memory; and memory usage is generally limited by PHP. If the spreadsheet is too big, then it can exceed those memory limits

The spreadsheet I importted only has one sheet with 8 cols and 12 rows, but it exceeds memory limits. The spreadsheet be open WPS app below, then it comes the bug.
![图片](https://user-images.githubusercontent.com/16218491/61580524-c3f1af00-ab45-11e9-8465-3f94748878fe.png)

**Comment by MarkBaker** [comment]
Just because those are the only rows and columns that contain visible content, doesn't mean that they are the only rows and columns.... cells can easily contain null values or empty strings, and PHPSpreadsheet doesn't distinguish when it loads

**Comment by viest** [comment]
PECL has a high-performance Excel extension. If the performance of PhpSpreadsheet does not fit your business scenario, try extending the extension.

### Benchmark
Test environment: Macbook Pro 13 inch, Intel Core i5, 16GB 2133MHz LPDDR3 Memory, 128GB SSD Storage.

#### Export
Two memory modes export 1 million rows of data (27 columns, data is string):

* Normal mode: only 29S is needed, and the memory only needs 2083MB;
* Fixed memory mode: only need 52S, memory only needs <1MB;

#### Import
1 million rows of data (1 columns, data is inter):

* Full mode: Just 3S, the memory is only 558MB;
* Cursor mode: Just 2.8S, memory is only <1MB;

https://github.com/viest/php-ext-excel-export
