### ISSUE TITLE
how to identifying a variable tag

### ISSUE THREAD

**Issue by yoyomule** [PHPOffice/PhpSpreadsheet#1096]
This is:
- [ ] a feature request
### What is the expected behavior?

Hello, in phpspreadsheet, it seems that you can only write data by finding the cell coordinates. In some cases, we want it to be able to write like a word tag by identifying a variable tag (eg.$name). This reduces the need to check the cell position, I only need to care about the name of the variable. In addition to the way to traverse the entire file, is there a better way?

**Comment by fengjiayin123** [comment]
```
```
````
```
```

**Comment by MarkBaker** [comment]
I'm sorry, I just don't understand what you mean by a "variable tag"; could you perhaps provide an example of how you would use this?

**Comment by oleibman** [comment]
No idea what is being requested, no response to request for more information. Leaving closed, removing stale label.
