### ISSUE TITLE
Remove counter-productive parameter default values

### ISSUE THREAD

**Issue by PowerKiKi** [PHPOffice/PhpSpreadsheet#110]
Throughout the code there are several setter that use default value, even it doesn't really make sense. For instance `Worksheet::setShowGridlines($pValue = false)`.

I can't imagine the purpose of having a default value to a setter with a single parameter. Moreover those parameter default value are sometime not the same as their corresponding property default value, adding to the confusion.

So we should analyze carefully each cases and remove the default value at least for setter with a single parameter if they are not used in our own codebase.

Since this would be a BC, it must happen before 1.0.

**Comment by Quix0r** [comment]
Or, setters are strictly setters: only setting one class field. Same with getter, nothing to be "getted from database" or even a file. Yes, I have seen such bad code. No wonder, there are so many confusions.

If you set boolean fields in classes, use the prefix enable, if you get them, use some "half-English-sentence" scheme.

Example:
- field name: $cellCollectionIsSorted
- "setter" `enableCellCollectionIsSorted($pCellCollectionIsSorted = true)`
- "getter": `isCellCollectionSorted ()`

This makes your object-oriented code being almost readable as an English sentence which is (not always possible, I know) much lesser confusing what is really done there.
