### ISSUE TITLE
Calculation during Writer->save() fails with IF calculation statements corresponding SUM

### ISSUE THREAD

**Issue by calien666** [PHPOffice/PhpSpreadsheet#1108]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Writing a $spreadsheet should execute all calculations. Best way is in order of creating or following the involved cells, I think.

### What is the current behavior?
In case of setting an IF statement, the Writer doesn't execute the file and doesn't write to stdout.

I figured out, that the IF condition is the problem, SUM works as expected. Trying to execute the calculations first before writing the IF has the same behavior.

### What are the steps to reproduce?
This PHP script works out of the box and reproduces the Error as expected.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);

$cells = [
    'A1' => 2,
    'A2' => 4,
    'A3' => 12
];

$sheet = $spreadsheet->getActiveSheet();

foreach ($cells as $cell => $value) {
    $sheet->setCellValue($cell, $value);
}

$sheet->setCellValue('A4', '=SUM(A1:A3)');

for ($i=1; $i<4; $i++) {
    $sheet->setCellValue('B'.$i, '=IF(A4;A'.$i.';0)');
}

$sheet->setCellValue('B4', '=SUM(B1:B3)');

$filename = 'text';

header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="'. $filename .'.xlsx"');
header('Cache-Control: max-age=0');

$writer->save('php://output');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet v1.8.2
Tested with PHP 7.0.33, 7.2.20 and 7.3.7

**Comment by MarkBaker** [comment]
Could it be the use of the `;` argument separator in the IF() function that's the problem? The calculation engine expects US format (ie comma `,` separator for function arguments)

**Comment by calien666** [comment]
Yes, you are right. I looked up for this section, but didn't find it.
