### ISSUE TITLE
Support sorting data range?

### ISSUE THREAD

**Issue by pixelchutes** [PHPOffice/PhpSpreadsheet#111]
Are there currently any plans for introducing support for sorting a range of data? I've reviewed the documentation and browsed through the code, and it does not currently seem to be an existing feature:

e.g. List (with headers), like the **Data > Sort...** option within Excel

This would be very helpful when working with a table of data, and sorting an individual column is not enough. Sorted data ranges effectively ensure that the relative data points remain correctly associated to their original row when sorting by a given column.

**Comment by PowerKiKi** [comment]
No plan, according to https://github.com/PHPOffice/PHPExcel/issues/864#issuecomment-198146095. I'd tend to agree with Mark here, while it might be convenient for end-users, it would probably add much complexity.

However if you are willing to contribute the whole feature as a PR (or as a separate package maybe?), I guess it could be negotiated.

**Comment by pixelchutes** [comment]
Thanks for the heads up. Makes sense. Would be happy to contribute if I do attempt to solve for this, but the "workarounds" seems perfectly reasonable.

**Comment by mahdiMJ** [comment]
Depends how much memory you have - I'd use the Worksheet's toArray() method to copy the cells from the main sheet to a PHP array, then you can use usort() to sort that array however you like, then create a new worksheet and use fromArray() to populate it with the sorted data - but for 20,000 rows, you need enough memory to hold that data as an array in memory.
