### ISSUE TITLE
How to Retain Formulas in Turning HTML

### ISSUE THREAD

**Issue by Ranxiu** [PHPOffice/PhpSpreadsheet#1111]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
How to Retain Formulas in Turning HTML

### What is the current behavior?
Formula missing

### What are the steps to reproduce?
function saveHtml($childPath,$rootPath){
  global $templateFilePath;
  $temp = __DIR__ . '/temp/' . time() . '.xlsx';
  // echo $temp;exit;
  $path = $templateFilePath.$childPath;
  if(copy( $path, $temp)){
    $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
    $spreadsheet = $reader->load($temp);
    try {
    $writer = new \PhpOffice\PhpSpreadsheet\Writer\html($spreadsheet);
    $writer->save($templateFilePath. $rootPath.'.html');
      unsetData($spreadsheet, $temp);
      return $rootPath.'.html';
    }
    catch (\Exception $e){
    unsetData($spreadsheet, $temp);
    thowError ($e);
    } catch (\Error $e){
    unsetData($spreadsheet ,$temp);
    thowError($e);
    }
  }
}

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by MarkBaker** [comment]
For the HTML Writer, cells are displayed as the evaluated result of their formula calculation by default, but you can disable that behaviour using the `setPreCalculateFormulas()` method
```
$writer = new \PhpOffice\PhpSpreadsheet\Writer\html($spreadsheet);
$writer->setPreCalculateFormulas(false);
$writer->save($templateFilePath. $rootPath.'.html');
```
