### ISSUE TITLE
Fatal error when loading file

### ISSUE THREAD

**Issue by JulienChavee** [PHPOffice/PhpSpreadsheet#1114]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The file can be loaded correctly. 
If not, produce an elegant error instead an undefined index + fatal error.

### What is the current behavior?
The library produce a fatal error :

```
Undefined offset: 3 in phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php in readLabelSst at line 3810
```
followed by
```
__clone method called on non-object in phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php in readLabelSst at line 3810
```

### What are the steps to reproduce?
Just reading an XLS file (probably corrupted).
I can't provide this file as it contains sensible informations.

### Which versions of PhpSpreadsheet and PHP are affected?
We are actually using version 1.6.0 for PhpSpreadSheet 
I'll try a bit later on latest version.

PHP : 7.3.6

**Comment by stevemueller-dreamsoft** [comment]
I got the same problem ;) 
When I remove row 1 till 6 - it works.

![image](https://user-images.githubusercontent.com/37575071/64241203-841f3500-cf03-11e9-8380-f744733f082e.png)

**Comment by stevemueller-dreamsoft** [comment]
No ideas?

**Comment by JulienChavee** [comment]
This is still an issue.

**Comment by JulienChavee** [comment]
This is still an issue

**Comment by JulienChavee** [comment]
This is still an issue

**Comment by JulienChavee** [comment]
This is still an issue

**Comment by tezrik** [comment]
Can you give the file?

**Comment by JulienChavee** [comment]
Hello,

Here an example

[0000000000000000000870897 (1).xls.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/4908116/0000000000000000000870897.1.xls.zip)

**Comment by JulienChavee** [comment]
This is still an issue

**Comment by JulienChavee** [comment]
This is still an issue.
