### ISSUE TITLE
Incorrect evaluation of statistical formulae if one of arguments is an error

### ISSUE THREAD

**Issue by AndreiPotemkin** [PHPOffice/PhpSpreadsheet#1118]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When one of the arguments to statistical function is an error (#NULL!, #DIV/0!, #VALUE!, #REF!, #NAME?, #NUM!, #N/A, #GETTING_DATA) then value gets skipped and function gets evaluated based on remaining arguments

### What is the current behavior?
Function should return respective error, at least in Excel compatibility mode

### What are the steps to reproduce?
Create new Excel file
In cell A1 enter value 1
in cell A2 enter formula '=1/0' (generates #DIV/0!)
In cell A3 enter formula '=MIN(A1, A2) (observe value #DIV/0! in Excel)
Save file
Open spreadsheet with PHPSpreadsheet library
Execute statement print $spreadsheet->getActiveSheet()->getCell('A3')->getCalculatedValue() (observe value 1)

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load("Test.xlsx");
$spreadsheet->getActiveSheet()->getCell('A1')->setValue(1);
$spreadsheet->getActiveSheet()->getCell('A2')->setValue('=1/0');
$spreadsheet->getActiveSheet()->getCell('A3')->setValue('=MIN(A1,A2)');
print $spreadsheet->getActiveSheet()->getCell('A3')->getCalculatedValue() . "\n";

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.8.2
PHP 7.1.23

**Comment by oleibman** [comment]
Supplied code now results in `#DIV/0!`, as it should. Leaving closed, removing stale label.
