### ISSUE TITLE
Temporary Directory 

### ISSUE THREAD

**Issue by naknak987** [PHPOffice/PhpSpreadsheet#1123]
This is:
A bug report.

### What is the expected behavior?
When using Mpdf to generate a PDF from a spreadsheet, Mpdf clears out its temporary files from the temp folder. This is currently set on line 131 in the `phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Pdf.php` file. 

### What is the current behavior?
It tries to delete files that don't belong to it. (at least on Windows 10)

### What are the steps to reproduce?
Generate a PDF using mPDF on a windows 10 machine. (didn't test with other operating systems)

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf;
$writer->save($path);
```
The temporary directory should be set to a folder that is specific to PhpSpreadsheet instead of the systems main temporary directory. I already posted this as an issue in the Mpdf issue tracker but they provide methods to set the temporary directory already. Since that is being handled by your implementation I decided to post here.

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.3.2
PhpSpreadsheet 1.8.2

**Comment by PJGaetan** [comment]
Hi, 

I met the same issue, and similarly to mpdf you can set the temporary folder.
If you try that, it should work.

```php
        // Create new Spreadsheet object
        $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
   
        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf($spreadsheet);
        //Set temporary directory
        $writer->setTempDir('path/to/your/temp/directory');
        $writer->save($path);
```

It is working for me.
PHP 7.3.3
PhpSpreadsheet 1.8.2

**Comment by naknak987** [comment]
@PJGaetan Oh, I tried looking for that in the documentation prior to opening this issue but I didn't get any results. Guess I didn't look hard enough because I can find it now. Thanks.
