### ISSUE TITLE
Number Format is not applied while cell is not edited

### ISSUE THREAD

**Issue by andrhevictor** [PHPOffice/PhpSpreadsheet#1124]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question
```

### What is the expected behavior?
To format the cells without have to edit afterwards.

### What is the current behavior?
Some formats are only aplied after editing the cell, like double-clicking in it or selecting the value in the formula bar.

### What are the steps to reproduce?
Insert a value in the cell then format it with a format code. Open the spreadsheet and see the cell format.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadSheet->getActiveSheet();

$sheet
    ->setCellValue('A1', '00000000000000')
    ->setCellValue('A2', $dateTime)
    ->getStyle( 'A1')
    ->getNumberFormat()
    ->setFormatCode('[<=99999999999]000\.000\.000-00;00\.000\.000\/0000-00');
$sheet
    ->getStyle('A2')
    ->getNumberFormat()
    ->setFormatCode('d/m');

$writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx( $spreadsheet );

ob_end_clean();
$writer->save( '/tmp/test.xlsx' );
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.8.2  
1.5.2

**Comment by Collie-IT** [comment]
I have the same Issue wist following code.

`$sheet->getStyle("A1")->getNumberFormat()->setFormatCode("0.00");`

The interessting fact is that 
`$sheet->getStyle(chr($col) . ($rowcounter))->getNumberFormat()->getFormatCode() `

Gives back 0.00 but after save "General"  would readout from the cell, especially if you have a formular in the cell. In the excelsheet there is no format selected

**Comment by oleibman** [comment]
Supplied code, both from the original report and from the August 1 addition, seems to work correctly now. Leaving issue closed, removing stale label.
