### ISSUE TITLE
Data Validation extract cell range should not trust sqref fully

### ISSUE THREAD

**Issue by wuchengzu** [PHPOffice/PhpSpreadsheet#1126]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
hope to add the judgment of the actual valid range of the cell area

extract cell reference range for validate data in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:1275
that is extract range according to "<dataValidation> 's sqref", 
but the value may be huge not valid value

```xml
<dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" sqref="B$1:B$1048576">
            <formula1>&quot;xx,xx,xx&quot;</formula1>
        </dataValidation>
```
![4463B7CC-BE80-4819-B241-3C4498C8037E](https://user-images.githubusercontent.com/17583147/62438615-db05e300-b77a-11e9-86d4-9039fb566552.png)

### What is the current behavior?
traverse whole range of "B$1:B$1048576", from row 1 to row 1048576

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
 /** @var BaseReader $objReader */
 $objReader = IOFactory::createReader('Xlsx');
 $objReader->setReadDataOnly(true);
 $objPHPExcel = $objReader->load($file);
 $objWorksheet = $objPHPExcel->getSheet($pIndex);
 $highestRow = $objWorksheet->getHighestRow();
 $highestColumn = $objWorksheet->getHighestColumn();
 $highestColumnIndex = self::columnIndexFromString($highestColumn);
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.6.0This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
hope to add the judgment of the actual valid range of the cell area

extract cell reference range for validate data in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:1275
that is extract range according to "<dataValidation> 's sqref", 
but the value may be huge not valid value

```xml
<dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" sqref="B$1:B$1048576">
            <formula1>&quot;xx,xx,xx&quot;</formula1>
        </dataValidation>
```
![Uploading 4463B7CC-BE80-4819-B241-3C4498C8037E.png…]()

### What is the current behavior?
traverse whole range of "B$1:B$1048576", from row 1 to row 1048576

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
 /** @var BaseReader $objReader */
 $objReader = IOFactory::createReader('Xlsx');
 $objReader->setReadDataOnly(true);
 $objPHPExcel = $objReader->load($file);
 $objWorksheet = $objPHPExcel->getSheet($pIndex);
 $highestRow = $objWorksheet->getHighestRow();
 $highestColumn = $objWorksheet->getHighestColumn();
 $highestColumnIndex = self::columnIndexFromString($highestColumn);
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.6.0

![4463B7CC-BE80-4819-B241-3C4498C8037E](https://user-images.githubusercontent.com/17583147/62438615-db05e300-b77a-11e9-86d4-9039fb566552.png)

**Comment by dgalv** [comment]
Hello,

The quote is escaped by $ObjWriter->writeElement() method because \XmlWriter escapes " < > etc.

A fix is necessary in Xlsx/Worksheet.php

`if ($dv->getFormula1() !== '') {`
`    $objWriter->startElement('x14:formula1');`
`    $objWriter->startElement('xm:f');`
`    $objWriter->writeRaw($dv->getFormula1());`
`    $objWriter->endElement();`
`    $objWriter->endElement();`
`}`

**Comment by dgalv** [comment]
Can u fix the same file, Xlsx\Worksheet.php for a second issue ?

Comment the first line 
`$this->writeDataValidations($objWriter, $worksheet);`

Regards,

And thx for ur work !

**Comment by oleibman** [comment]
The two occurrences of writeDataValidations was an unfortunate accident. It is fixed in master.

I do not understand what you are trying to say about "XmlWriter escapes".

**Comment by dgalv** [comment]
In PHP doc, we can read

> The characters <, >, & and " are written as entity references (i.e. &lt;, &gt;, &amp; and &quot;, respectively). All other characters including ' are written literally. To write the special XML characters literally, or to write literal entity references, xmlwriter_write_raw() has to be used.

**Comment by oleibman** [comment]
I don't see a problem. With the following code:
```php
$validation->setFormula1('"Option 1, Option & 2"');
```
I see the following result in the output file:
``` xml
<formula1>&quot;Option 1, Option &amp; 2&quot;</formula1>
```
That seems right, and Excel has no problem opening the resulting file, and validating the cell with this formula correctly. Am I misinterpreting your concern? Do you have an example where things are going awry?

**Comment by oleibman** [comment]
Problem seems answered, no update in 4 years, removing stale label, leaving closed.
