### ISSUE TITLE
IReadFilter not being called on load().

### ISSUE THREAD

**Issue by alsaleem00** [PHPOffice/PhpSpreadsheet#1127]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
load() should not load whole file.

### What is the current behavior?
load() loads the whole file (xlsx) regardless if I use IReadFilter or not. With 70M xlsx it takes more than 10 minutes before I can start reading cells. I had to use PHP CLI as apache/php do not allow that time. 4CPU, 8G RAM, and consumes +4GB on swap. xlsx is 700K rows x  20 col.
*** note *** : could the file header be that large before reading cell data? I am not so experienced in xlsx file structure.

### What are the steps to reproduce?
I used the code of sample 09 and a large 70M xlsx file.
 
### Which versions of PhpSpreadsheet and PHP are affected?
(1.8.2)

**Comment by siarheipashkevich** [comment]
@alsaleem00 did you resolve your problem?

**Comment by alsaleem00** [comment]
You can not use web interface to process such large files.
The software still loads the whole file. but only processes what IReadfilter allows it to.
