### ISSUE TITLE
Reading CSV values as strings

### ISSUE THREAD

**Issue by ondrej-bouda** [PHPOffice/PhpSpreadsheet#1132]
This is:

```
- [X] a bug report
```

### What is the expected behavior?
When reading a CSV file containing, e.g., `165008E4` as a cell value, it shall be read as is, i.e., as a "165008E4" string.

### What is the current behavior?
The cell gets 1650080000 set as its value.

### What are the steps to reproduce?

Create a CSV file `input.csv` containing the following:
```
165008G4
165008E4
```

Then execute the following script:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$filePath = 'input.csv';
$ssReader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($filePath);
$spreadsheet = $ssReader->load($filePath);
$sheet = $spreadsheet->getSheet(0);

$firstCell = $sheet->getCell('A1');
var_dump($firstCell->getValue()); // string(8) "165008G4"

$secondCell = $sheet->getCell('A2');
var_dump($secondCell->getValue()); // double(1650080000)
```

The first cell gets read correctly as string. The second cell, however, gets interpreted as a number. IMHO there should be no difference - unless specified otherwise, the data type should be the same for both values.

### Which versions of PhpSpreadsheet and PHP are affected?
1.8.2

I suggest fixing the `PhpOffice\PhpSpreadsheet\Reader\Csv::loadIntoExisting()` to use `setValueExplicit($rowDatum, DataType::TYPE_STRING)` instead of `setValue($rowDatum)`. I am not aware of any consequences, however. If somebody relies on the type auto-detection, maybe the problem might be addressed by introducing a configuration flag?

**Comment by PowerKiKi** [comment]
See https://github.com/PHPOffice/PhpSpreadsheet/pull/1133#issuecomment-520285177 for a solution to this use-case.

**Comment by yasasn86** [comment]
use StringValueBinder
 
`\PhpOffice\PhpSpreadsheet\Cell\Cell::setValueBinder( new \PhpOffice\PhpSpreadsheet\Cell\StringValueBinder() );`
