### ISSUE TITLE
Reading big integers from csv cell is incorrect

### ISSUE THREAD

**Issue by KevinHN** [PHPOffice/PhpSpreadsheet#1135]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
### What is the expected behavior?
If the cell value is a big integer (example 1017073915858857984), read it as raw value.

### What is the current behavior?
If the cell value is a big integer (example 1017073915858857984), it will be rounded.

### What are the steps to reproduce?
Just create a simple csv file with big integers and get the value.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.8.2, PHP 7.2

**Comment by KevinHN** [comment]
@PowerKiKi 

An other problem with the values like these:
769174591994368000
896870721988608000

it's auto convert to float value if I set the cell as general format. (both csv and xlsx format)

**Comment by MarkBaker** [comment]
If these values are larger than PHP_INT_MAX, then they will be converted to floats by default; there is a stringValueBinder provided that will treat any value stored in a cell as a string, but you need to enable it

**Comment by KevinHN** [comment]
@MarkBaker, Thank you for supporting. 

stringValueBinder is Ok, but that is not convenient. I think that it will be more convenient if it has method such as $cell->getRawValue() and this return the raw value in string. What are you think?

For the issue in the comment:
769174591994368000 >= PHP_INT_MAX
Return false.

**Comment by MarkBaker** [comment]
That would require us to create a new binder and make that the default anyway, and that would break backward compatibility by changing the existing default behaviour.

A custom binder can be written for specific columns as well, testing the cell address and making any datatype conversion required or not, based on that address

**Comment by KevinHN** [comment]
You may doesn't get my point here. I think this fix will not break backward compatibility.
Just a small change on DefaultValueBinder, and Cell class.

Just a a property private $rawValue; to Cell class and update this value on IValueBinder::bindValue

Another point: In the Cell::setValueExplicit, the current code is:
```
case DataType::TYPE_NUMERIC:
                $this->value = (float) $pValue;
```

I think this should be 
```
case DataType::TYPE_NUMERIC:
                $this->value =  is_int($pValue) ? (int)$pValue : (float) $pValue;
```

What do you think about this?

**Comment by PowerKiKi** [comment]
I think PR #874 is exactly what you want, but is missing tests to be merged.
