### ISSUE TITLE
Trailing zeros

### ISSUE THREAD

**Issue by Benjact** [PHPOffice/PhpSpreadsheet#1139]
https://github.com/PHPOffice/PhpSpreadsheet/blob/34675bdf5d736ee796abf552e75a1660cfab4b66/src/PhpSpreadsheet/Reader/Csv.php#L383

Reading a csv with a cell with a number 2.000 where the point is not a decimal delimiter but a thousand is returned as 2 because the 0 are assumed as trailing zeros. The setValue can't assign the type as string

**Comment by MarkBaker** [comment]
There is no setting of locale for data values in PHPSpreadsheet, so any conversion like this would need to be handled with a custom binder that was locale-aware
