### ISSUE TITLE
Erm...where is the classes folder?

### ISSUE THREAD

**Issue by Bsidey** [PHPOffice/PhpSpreadsheet#114]
Get started documentation says to copy files from the classes folder, but I don't have a classes folder. Ran Composer but still nothing.

**Comment by PowerKiKi** [comment]
Docs were updated, please [have a look again](http://phpspreadsheet.readthedocs.io/en/develop/) and submit PR to improve them.

Also next time try [gitter](https://gitter.im/PHPOffice/PhpSpreadsheet) first for support question.
