### ISSUE TITLE
Use of Built-In PHP Function is_readable() Problematic With UNC Path

### ISSUE THREAD

**Issue by broberts-mrmc** [PHPOffice/PhpSpreadsheet#1144]
Use of PHP's built-in function `is_readable()` (https://www.php.net/manual/en/function.is-readable.php) can be problematic with UNC (network) file paths.

It appears `is_readable()` is used going back to PHPOffice/PhpSpreadsheet 1.6, at least.  Here's a link to one such instance in 1.8:

https://github.com/PHPOffice/PhpSpreadsheet/blob/48ccdc271674070528f7252bfbb9c32a58df2813/src/PhpSpreadsheet/Shared/File.php#L140

There are a number of related, open PHP bug reports pertaining to `is_readable()`:

- https://bugs.php.net/bug.php?id=69834
- https://bugs.php.net/bug.php?id=68926
- https://bugs.php.net/bug.php?id=73543

For the moment, our workaround involves copying the network file to a local directory and then providing the local file path (i.e. instead of the network/UNC path) to PHPOffice/PhpSpreadsheet.

**Comment by oleibman** [comment]
See further discussion in PR #1998. This seems to be a problem with Php, not PhpSpreadsheet. Leaving closed, removing stale label.
