### ISSUE TITLE
Load by string

### ISSUE THREAD

**Issue by simoheinonen** [PHPOffice/PhpSpreadsheet#1147]
Would be nice to be able to create the reader from string. Would be great for example when using a filesystem abstraction like flysystem. (Currently need to write to a temp file and then load that)

**Comment by 4n70w4** [comment]
The same problem!

**Comment by v20100v** [comment]
Arg...

no php stream

**Comment by npelov** [comment]
It seams an obvious requirement to be able to load spreadsheet from string/stream

**Comment by Perturbatio** [comment]
FYI, you can capture the file contents using output buffering:

```
use League\Flysystem\Filesystem;
use League\Flysystem\InMemory\InMemoryFilesystemAdapter;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Ods;

$adapter = new InMemoryFilesystemAdapter();
$filesystem = new Filesystem($adapter);

$writer = new Ods($spreadsheet);

ob_start();
$writer->save('php://output');
$content = ob_get_contents();
ob_end_clean();

$filesystem->write('test-memory.ods', $content);
if ($filesystem->has('test-memory.ods')){
    $doc = $filesystem->read('test-memory.ods');
    // do something with the document
} else {
    echo "File not found";
}
```

**Comment by npelov** [comment]
Yes, that's a nice workaround for a feature that should have been there.

**Comment by MarkBaker** [comment]
> Yes, that's a nice workaround for a feature that should have been there.

Should have been there! But simply not possible. Streams, by their nature are linear, read from start to finish; but aside from HTML and CSV, none of the spreadsheet file formats are linear. You can't start reading the file at the beginning and process it to the end. Those files have to be accessed in a way that allows you to jump backwards and forwards within the file, reading different bits of content from different parts of the file.

The only way that we could accept string or stream content would be to create a temporary file internally, and then process it; simply moving that "workround" from outside of the library to inside it.

**Comment by npelov** [comment]
Hmm. I see. I haven't looked in in details how save works. But there is one better workaround:
```
    $fd = fopen("php://memory", "w+b");
    $writer->save($fd);
    rewind($fd);
    $xlsx = stream_get_contents($fd);
    fclose($fd);
```
Using the output buffer is not ideal. I think php://memory (since php 5.1) stream is a bit better. You could include that in the library. It doesn't require writable space on disk and doesn't mess with output buffer. I'm not sure if having gzip filters for output buffer would affect the php://output solution...

**Comment by MarkBaker** [comment]
But that uses PHP assigned memory; and PhpSpreadsheet is already frequently criticised for being too memory hungry. After all the work that I did over the summer to reduce memory consumption, I'd hate to eliminate those reductions by using php://memory
