### ISSUE TITLE
Calculation Branch Pruning should be Off by default

### ISSUE THREAD

**Issue by rolandsusans** [PHPOffice/PhpSpreadsheet#1149]
This is:

- [x] a bug report

### What is the expected behavior?
Branch Pruning should not affect the result in calculations, it's just "performance booster"
### What is the current behavior?

"performance booster" has some side effects, for example, it modifies results for VLOOKUP

### What are the steps to reproduce?

check out https://github.com/PHPOffice/PhpSpreadsheet/pull/1148

### Which versions of PhpSpreadsheet and PHP are affected?
1.9.0

**Comment by rolandsusans** [comment]
This kinda reverts https://github.com/PHPOffice/PhpSpreadsheet/pull/844. @frantzmiccoli you were not sure of backwards compatibility & side effects of your PR - can you please check  #1148 and confirm changes?

**Comment by frantzmiccoli** [comment]
I will give a look

**Comment by PowerKiKi** [comment]
Branch pruning should be fixed in 1.10.0
