### ISSUE TITLE
Ability to add value to cell instead of just setting

### ISSUE THREAD

**Issue by murilozilli** [PHPOffice/PhpSpreadsheet#115]
Today I saw that the project only has setValue methods(or setCellValue for Worksheet class). I think it would help to have addValue methods as well, giving the chance for the user to break the line inside the cell if he wishes.

That would help users that want to put values inside the same cell on a loop for instance.

**Comment by PowerKiKi** [comment]
Closing for the reasons explained in https://github.com/PHPOffice/PhpSpreadsheet/pull/116#issuecomment-286624055
