### ISSUE TITLE
data incorrect on reading the file

### ISSUE THREAD

**Issue by igrib-eif** [PHPOffice/PhpSpreadsheet#1155]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on 
```

### What is the expected behavior?
the data should be shown in the correct cell

### What is the current behavior?
cells content are replaced

### What are the steps to reproduce?

[obfuscated.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3589697/obfuscated.xlsx)

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$filepath = '/tmp/result.xlsx';
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($filepath);
$spreadsheet = $reader->load($filepath);
$sheets = $reader->listWorksheetNames($filepath);
foreach ($sheets as $key => $sheet)
{
	$worksheet = $spreadsheet->setActiveSheetIndexByName($sheet);
	$data = $spreadsheet->getActiveSheet()->toArray();
	echo json_encode($data);
	echo "\n\n";
}
echo "\n\n";
```
this shows the results:
[["header1","header2","header3","header4","header5","header6","header7","action","error_message"],
["_BR_1","_BR_1","000000000001","Y","000000000000","000000000001","000000000001","Loan is not found in the database.","_BR_5"],
["_BR_8","_BR_8","000000000001","Y","000000000000","000000000001","000000000001","Loan is not found in the database.","_BR_5"],
["_BR_9","_BR_9","000000000001","Y","000000000000","000000000001","000000000001","Loan is not found in the database.","_BR_5"],
["_BR_10","_BR_10","000000000001","Y","000000000000","000000000001","000000000001","Loan is not found in the database.","_BR_5"],
["**3**","**3**","000000000001","Y","000000000000","000000000001","000000000001","Loan is not found in the database.","_BR_5"],
[null,null,null,null,null,null,null,null,null]]

[["header1","header2","header3","header4","header5","action","error_message"],
["_BR_10","_BR_10","01\/01\/2014","Loan is not found in A2 or in database.","000000000020","Loan is not found in the database.",""],
["**3**","**3**","01\/01\/2014","Loan is not found in A2 or in database.","000000000020","Loan is not found in the database.",""],
[null,null,null,null,null,null,null]]

[["header1","header2","header3","action","error_message"],
["_BR_10","_BR_10","01\/02\/2014","Loan is not found in the database.","_BR_5"],
["**3**","**3**","01\/02\/2014","Loan is not found in the database.","_BR_5"],
[null,null,null,null,null]]

[["header1","header2","header3","action","error_message"],
["_BR_10","_BR_10","01\/03\/2014","Loan is not found in the database.","_BR_5"],
["**3**","**3**","01\/03\/2014","Loan is not found in the database.","_BR_5"],
[null,null,null,null,null]]

some cell contents are replaced:
- in sheets C, I1 and I2, the content of cells A3 and B3 are replaced with '3'

the file is generated by SAS (https://www.sas.com) and it happens with XLS and XLSX files. the content is shown correctly in Excel.

### Which versions of PhpSpreadsheet and PHP are affected?
tested on [1.9.0] and [1.5.0]

**Comment by oleibman** [comment]
Supplied code with supplied spreadsheet currently return expected result.
