### ISSUE TITLE
invalid Suspicious Double-encoded XML

### ISSUE THREAD

**Issue by paveldvorak5** [PHPOffice/PhpSpreadsheet#1157]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
In this code
```php
 private function toUtf8($xml)
    {
        $pattern = '/encoding="(.*?)"/';
        $result = preg_match($pattern, $xml, $matches);
        $charset = strtoupper($result ? $matches[1] : 'UTF-8');
        if ($charset !== 'UTF-8') {
            $xml = mb_convert_encoding($xml, 'UTF-8', $charset);
            $result = preg_match($pattern, $xml, $matches);
            $charset = strtoupper($result ? $matches[1] : 'UTF-8');
            if ($charset !== 'UTF-8') {
                throw new Reader\Exception('Suspicious Double-encoded XML, spreadsheet file load() aborted to prevent XXE/XEE attacks');
            }
        }
        return $xml;
    }
```
there should be         
if ( str_to_upper($charset) !== 'UTF-8') {
My file has utf-8 in lowercase

### What is the expected behavior?
Load file

### What is the current behavior?
Load fails with error: 'Suspicious Double-encoded XML, spreadsheet file load() aborted

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$sheetData = \PhpOffice\PhpSpreadsheet\IOFactory::load( $filePath )->getActiveSheet()->toArray( null, true, true, true );
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.9

**Comment by paveldvorak5** [comment]
[CNG_2019_06.XLSX](https://github.com/PHPOffice/PhpSpreadsheet/files/3609741/CNG_2019_06.XLSX)

**Comment by storeman** [comment]
I found this is caused by a change in the XmlScanner class. The `toUtf8` function has an error:

```

    private function toUtf8($xml)
    {
        $pattern = '/encoding="(.*?)"/';
        $result = preg_match($pattern, $xml, $matches);
        $charset = strtoupper($result ? $matches[1] : 'UTF-8');

        if ($charset !== 'UTF-8') {
            $xml = mb_convert_encoding($xml, 'UTF-8', $charset);

            $result = preg_match($pattern, $xml, $matches);
            $charset = strtoupper($result ? $matches[1] : 'UTF-8');
            if ($charset !== 'UTF-8') {
                throw new Reader\Exception('Suspicious Double-encoded XML, spreadsheet file load() aborted to prevent XXE/XEE attacks');
            }
        }

        return $xml;
    }
```

The function assumes that `mb_convert_encoding` also changes the XML code, which is a wrong assumption. I think the code after the mb_convert_encoding can be deleted and it is safe to assume mb_convert_encoding does wat it promises.

**Comment by paveldvorak5** [comment]
> I found this is caused by a change in the XmlScanner class. The `toUtf8` function has an error:
> 
> ```
> 
>     private function toUtf8($xml)
>     {
>         $pattern = '/encoding="(.*?)"/';
>         $result = preg_match($pattern, $xml, $matches);
>         $charset = strtoupper($result ? $matches[1] : 'UTF-8');
> 
>         if ($charset !== 'UTF-8') {
>             $xml = mb_convert_encoding($xml, 'UTF-8', $charset);
> 
>             $result = preg_match($pattern, $xml, $matches);
>             $charset = strtoupper($result ? $matches[1] : 'UTF-8');
>             if ($charset !== 'UTF-8') {
>                 throw new Reader\Exception('Suspicious Double-encoded XML, spreadsheet file load() aborted to prevent XXE/XEE attacks');
>             }
>         }
> 
>         return $xml;
>     }
> ```
> 
> The function assumes that `mb_convert_encoding` also changes the XML code, which is a wrong assumption. I think the code after the mb_convert_encoding can be deleted and it is safe to assume mb_convert_encoding does wat it promises.

Seems OK to me

**Comment by paveldvorak5** [comment]
could you fix it?

**Comment by storeman** [comment]
I cannot. The method would look like this:

```
    private function toUtf8($xml)
    {
        $pattern = '/encoding="(.*?)"/';
        $result = preg_match($pattern, $xml, $matches);
        $charset = strtoupper($result ? $matches[1] : 'UTF-8');

        if ($charset !== 'UTF-8') {
            $xml = mb_convert_encoding($xml, 'UTF-8', $charset);
        }

        return $xml;
    }
```

**Comment by paveldvorak5** [comment]
it was already fixed
$charset = strtoupper($result ? $matches[1] : 'UTF-8');
