### ISSUE TITLE
RESOLVING + RESOLVING2 constants (Calculation/Calculation.php:4148)

### ISSUE THREAD

**Issue by otuhacek** [PHPOffice/PhpSpreadsheet#1161]
Hi,
I just went into some problem when exporting some content on AC99 field. It complains of redefining RESOLVING2 constant multiple times, which triggered PHP Notice. Is this piece of code meant to be there or is it just something from previous testing?

https://github.com/PHPOffice/PhpSpreadsheet/blob/a972943ac56895905d9cbaf103d17e9e25fb8b50/src/PhpSpreadsheet/Calculation/Calculation.php#L4148

Thanks

![resolving](https://user-images.githubusercontent.com/55390565/64955374-5da8b480-d888-11e9-88a4-4e8d13b515b9.png)

**Comment by pedrofsantoscom** [comment]
I also have the same notice. Besides the notice it runs without a problem.
This happens on a file created that has 22-29 sheets, and on each of those sheets column A has ~1000 rows and each row on col A has a very long expression (7000 characters long).

![image](https://user-images.githubusercontent.com/2325978/68167768-91d25480-ff5e-11e9-8f24-dcac66fcd9c1.png)

**Comment by jonnylink** [comment]
This is still an issue

**Comment by jonnylink** [comment]
This is from this commit: https://github.com/jonnylink/PhpSpreadsheet/commit/0b387e767e99a9042886ea673d9b9905c7951e87

It does in fact look like code that was simply there to test, since there are no other references to the constant RESOLVING or RESOLVING2 in the codebase. I'm going to make a PR to remove that broken code.

**Comment by Benjiiii** [comment]
Facing same issue

**Comment by woganmay** [comment]
Just had this come up in production now for the first time. Definitely still an issue.

**Comment by jonnylink** [comment]
Might want to comment or thumbs up the PR if you're having this issue. Not sure anyone is checking closed issues.

https://github.com/PHPOffice/PhpSpreadsheet/pull/1328

**Comment by oleibman** [comment]
Fixed by PR #1328 in February 2020.
