### ISSUE TITLE
TCPDF - PDF generation does not respect $isPDF

### ISSUE THREAD

**Issue by Collie-IT** [PHPOffice/PhpSpreadsheet#1163]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
If I use TCPDF as writer, the $isPDF in <Path>/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Html.php should interpreted as true.

### What is the current behavior?
If I use TCPDF as writer, the $isPDF is misinterpreted in<Path>/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Html.php as false.

### What are the steps to reproduce?
```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue("A1" , "Test");
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Tcpdf');
$writer->setEmbedImages(true) ;
$writer->generateHTMLHeader() ;
$writer->generateStyles(true) ;
$writer->generateHTMLFooter() ;
$writer->save($path2); 

```
### Which versions of PhpSpreadsheet and PHP are affected?
Tested with 1.8.2, 1.9.0.

**Comment by Collie-IT** [comment]
The dirty hot fix is set to $isPDF to public in html.php.

**Comment by PowerKiKi** [comment]
What is the consequences of having this flag to the wrong flag? Why do you think it needs to be changed?

**Comment by Collie-IT** [comment]
The Problem is that the pagebreaks will be doubled, if $isPDF is false, because `<path>vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Html.php` on Line 828 checks for if not PDF 

https://github.com/PHPOffice/PhpSpreadsheet/blob/9d6736d30366706f5a18f49d2974e7738ec535ea/src/PhpSpreadsheet/Writer/Html.php#L828-L830

**Comment by oleibman** [comment]
Setting isPdf was added to PDF constructor by PR #1464 in May 2020.
