### ISSUE TITLE
Excel (.xlsx) parsing fails with an NPE

### ISSUE THREAD

**Issue by serverdevil** [PHPOffice/PhpSpreadsheet#1172]
This is:

```
- [x] a bug report
- [ ] a feature request
```

### What is the expected behavior?
Workbook parsing should succeed

### What is the current behavior?
Workbook parsing fails with following error
```
<b>Fatal error</b>:  Uncaught Error: Call to a member function attributes() on null in /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:1234
Stack trace:
#0 /var/www/html/NBUIExcelReader.php(60): PhpOffice\PhpSpreadsheet\Reader\Xlsx-&gt;load('/var/www/html/u...')
...
#3 {main}
  thrown in <b>/var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php</b> on line <b>1234</b><br />
```

### What are the steps to reproduce?
Apologies for this but the issue is being noticed in a bunch of financial Excel files that I'm not at liberty to share. 
Changing the erring code at line 1234 in `Reader/Xlsx.php` to the following works. 
```
if (isset($clr->alpha)) {
     $shadow->setAlpha(self::getArrayItem($clr->alpha->attributes(), 'val') / 1000);
}
```
If it is acceptable to the team to address this based on this info, please do so. Otherwise, feel free to close the issue. 

### Which versions of PhpSpreadsheet and PHP are affected?
Reproducible in 1.9

**Comment by oleibman** [comment]
I believe this was fixed by PR #2173 in June 2021.
