### ISSUE TITLE
How to get offline documentation

### ISSUE THREAD

**Issue by abelardolg** [PHPOffice/PhpSpreadsheet#1175]
This is:

```
- [ ] a bug report
- [x ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet and PHP are affected?

I would like to download the documentation of this library to be offline viewed with no Internet connection, please.

Warmest regards.

**Comment by mlapan** [comment]
You could always download the docs and then opening them in Atom with a md plugin to render it.
Or just find any free program that can render md, theres quite a few out there.
Even some 100% portable ones

**Comment by abelardolg** [comment]
I didn't realize that the docs were available right here. 

Sorry and thanks! :)
