### ISSUE TITLE
Uncaught error when opening ods file in 1.9

### ISSUE THREAD

**Issue by franksl** [PHPOffice/PhpSpreadsheet#1176]
Hello,
Reopening issue #1047, sorry for reposting.

When trying to open an ods file downloaded from google drive I receive this exception:

PHP Fatal error: Uncaught TypeError: Argument 2 passed to PhpOffice\PhpSpreadsheet\Reader\Ods\Properties::setCoreProperties() must be an instance of SimpleXMLElement, array given, called in /my/path/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods/Properties.php on line 27 and defined in /my/path/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods/Properties.php:39

I'm actually stuck at v1.7.

Thanks,
Frank

**Comment by fjqtp** [comment]
Same bug for me, bugfix by @Jerome3 works
