### ISSUE TITLE
ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by yinwanjin** [PHPOffice/PhpSpreadsheet#1179]
ERR_INVALID_RESPONSE
Error de php7

**Comment by biscuit214** [comment]
ME2

php v7.3.8

no error message

**Comment by biscuit214** [comment]
ZipArchive issue

yum update -y php-pecl-zip

**Comment by oleibman** [comment]
No idea what this issue was about. Leaving closed, removing stale label.
