### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by filipemansano** [PHPOffice/PhpSpreadsheet#118]
![image](https://cloud.githubusercontent.com/assets/6247393/23968765/e31f5928-09a2-11e7-89b8-744b10f917e3.png)

in PhpOffice\PhpSpreadsheet\Calculation.php on line 3054 have 3 points before $args.. this cause a php syntax error...

https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Calculation.php#L3054

PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in \lib\PhpOffice\PhpSpreadsheet\Calculation.php on line 3054

**Comment by gmsantos** [comment]
Its not a syntax error. http://php.net/manual/pt_BR/migration56.new-features.php#migration56.new-features.splat

Please be aware of the minimum PHP version requirement for PhpSpreadsheet (5.6+) and upgrade your system to fulfill this requirement.

**Comment by filipemansano** [comment]
got it, I had no knowledge about this operator... thanks for the information I will update my php to new version
