### ISSUE TITLE
Parse error: syntax error, unexpected '=' in [ ... ] Calculation.php on line 2460

### ISSUE THREAD

**Issue by mdzoon** [PHPOffice/PhpSpreadsheet#1189]
This is:

```
- [*] a bug report
- [ ] a feature request
- [*] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
create a spreadsheet

### What is the current behavior?
Parse error: syntax error, unexpected '=' in /home/forteuk/public_html/.staging/forte-reports/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php on line 2460

### What are the steps to reproduce?

<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
require_once('vendor/autoload.php');

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Hello World !');

$writer = new Xlsx($spreadsheet);
$writer->save('hello world.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 5.6 (ea-php56)
phpoffice/phpspreadsheet 1.9

**Comment by MarkBaker** [comment]
You do realise that the mimimum PHP version for PHPSpreadsheet 1.9 is PHP 7.1?

https://github.com/PHPOffice/PhpSpreadsheet/blob/1.9.0/composer.json#L42

**Comment by mdzoon** [comment]
Indeed. I did pick it up later that day. Thank you for your prompt response Mark, and apologies for any inconvenience.
