### ISSUE TITLE
can't get make it to work for the life of me

### ISSUE THREAD

**Issue by goncaloproenca** [PHPOffice/PhpSpreadsheet#1194]
Hi there,

Can't get phpSpreadshhet to work for the life of me.

Will make a small donation who can help - seriously.

I installed composer, have php7.2 and Ubuntu 18.04 LTS running, everything updated.

Ran composer, Ran composer require on the root and everything fine.

Tried to run some examples that come with it and :

Warning: require(/var/www/html/../Header.php): failed to open stream: No such file or directory in /var/www/html/Custom_properties.php on line 9

Fatal error: require(): Failed opening required '/var/www/html/../Header.php' (include_path='.:/usr/share/php') in /var/www/html/Custom_properties.php on line 9

Have everything on root , with permissions ( its a test server ).

**Comment by sbreiler** [comment]
You should have a vendor folder (in your root folder).

Try the following from console (don't copy the samples!), presumably inside **/var/www/html**:
```console
php ./vendor/phpoffice/phpspreadsheet/samples/index.php
```
If everything is passed (see output of command), than try:
```console
php ./vendor/phpoffice/phpspreadsheet/samples/Reader/18_Reading_list_of_worksheets_without_loading_entire_file.php
```

If this works, phpspreadsheet is installed/working correctly.

**Comment by PowerKiKi** [comment]
> don't copy the samples

This is the solution.
