### ISSUE TITLE
is PhpSpreadsheet support show richtext/html/table in the cell Or in comment

### ISSUE THREAD

**Issue by zh7314** [PHPOffice/PhpSpreadsheet#1198]
i copy html table from web page into comment find out it can support show  html/table 

 `$sheet->getComment(Coordinate::stringFromColumnIndex('10') . $Row)->getText()->createTextRun(self::noteShow($a));`

i use  createTextRun method to write into comment but no work，i don‘t know how to support richtext

**Comment by oleibman** [comment]
Several sample files (e.g. templates/sampleSpreadsheet or 51_ProtectedSort) show how to use RichText in comments.

Leaving issue closed, removing stale label.
