### ISSUE TITLE
xlsm read and write with macros

### ISSUE THREAD

**Issue by uhlyarikp** [PHPOffice/PhpSpreadsheet#1201]
Dear Devs,

I have some problem with macros and i need your help. My newest task is, to have to create workbook from database and saving into a new xlsm file. My customer sent the temlpate file with 4 sheets, VB macros, formulars and so on.
I can read the template and inserting new datas thats a good news.
The bad news is i can't save the file into xlsm formag, just xlsx. I lose macros, but it's very important to my customer, so i hope you can help me, becuse i need find a solution for this problem.
Is there any way to create xlsm or i have to figure out some other solution? 

Here is the code :

use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\IOFactory;

$inputFileName = 'template.xlsm';
$inputFileType = IOFactory::identify($inputFileName);
$reader = IOFactory::createReader($inputFileType);
$spreadsheet = $reader->load($inputFileName);

$sheet = $spreadsheet->setActiveSheetIndex(0);
$sheet->setCellValue('A1', $someVal1);

/* nothing happen 
$writer = IOFactory::createWriter($spreadsheet,$inputFileType);
$writer->save("test.$inputFileType");
exit;
*/
/* save without macros */
$writer = IOFactory::createReader($spreadsheet,'xlsx');
$writer = new Xlsx($spreadsheet);
$writer->save("test.xlsx");
 exit;

**Comment by karan-chauhan** [comment]
Hi uhlyarikp,

Any update on your task. Are you able to achieve your requirement with this library?

**Comment by jvarugh** [comment]
@uhlyarikp I've run into the exact same issue. Ever find a workaround? 

Thanks,

**Comment by armcar** [comment]
Just can't find how to write into a cell (xlsm).
Using use PhpOffice\PhpSpreadsheet\IOFactory

**Comment by leanesanity** [comment]
Have any updates on this ?
I lost some micros when saving also (xlsm)

**Comment by bmtmadushanka** [comment]
any update? i have same situation?

**Comment by MarkBaker** [comment]
We do not support, nor have we any plans to support, xlsm files, or VB macros
This isn't simply a case of needing to read and write the macros; but would entail the capability to parse VBA code from within PHP, and that is a non-trivial task.

**Comment by bradsaavedra** [comment]
On an older project I had a version of PHPSpreadsheet that I got to work with xlsm files. The macros in the workbook were VERY simple and I never had the need to test complex spreadsheets, but I could open the xlsm template, write my data and save it with the older package.

Opening the composer.json file shows that it was "phpoffice/phpspreadsheet": "^1.1". I am working on a newer project and cannot get the xlsm functionality to work. The version I am using is "phpoffice/phpspreadsheet": "^1.17". I may try and find that older code and see if I can get it work right though because this limitation is a drag.

**Comment by jomocag** [comment]
My two cents:

Symfony 4.4 project using phpoffice/phpspreadsheet 1.18.0 and PHP 7.4. We have a xlsm file with 3 sheets, 2 of them protected against design changes. One of the protected sheets, the one users put data in, has a row header with several background colors; some of its columns have conditional formating; other columns have data validation and users can select their cells value from a list. The other one has a button to execute a macro; the code is also protected.

Reading a xlsm file with: 
```
$reader = IOFactory::createReaderForFile("<path-to-xlsm-file>");
$spreadsheet = $reader->load("<path-to-xlsm-file>");
```
We add data as normal and then save file with:
```
$xlsxWriter = new Xlsx($spreadsheet);
$xlsxWriter->save("<filename>.xlsm");
```
If file is saved as `xlsx` then MS Excel complains and says it is corrupted. The saved xlsm file opens as usual but with some quirks:

- The sheet with the row header lost all the background colors.
- All data validation and cell value selection has disappeared.
- The button that launches the macro when clicked has disappeared, although the macro is still there and it can be executed manually.
- There is no protected sheets, although the code is still protected.
- If one tries to reenable sheet protection, the protection options checked by default are different (literal translation of options names from Excel 2016 in Spanish): 
  - saved file has all options checked but "Modify objects" and "Modify scenarios"
  - original xlsm file has enabled only these options: "Protect sheet and content of blocked cells", "Select blocked cells", "Select unblocked cells", "Insert rows", "Delete rows", "Sort", "Use Autofilter"
  - blank new file has enabled only these options: "Protect sheet and content of blocked cells", "Select blocked cells", "Select unblocked cells"

These quirks are minor problems for us at this moment as resulting files are only used internally.

**Comment by mohamedevweb** [comment]
This repository works perfectly: https://github.com/ribojhin/excelmacro

Super easy to install and use — ideal for working with .xlsm files while preserving macros.

**Comment by oleibman** [comment]
Reading the files used for macro code, and passing them through on output, has been supported for some time. There is no way to manipulate those files. In the likely event that the macros are used with form controls, there is only limited support for those (PR #3130).

Leaving issue closed, removing stale label.
