### ISSUE TITLE
Table Concept Support for xlsx

### ISSUE THREAD

**Issue by landall** [PHPOffice/PhpSpreadsheet#1202]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
https://docs.microsoft.com/en-us/office/open-xml/working-with-tables
support Table Concept in modern office excel files.
By now, most of the office 365 based development only takes Table as a data source, not a Sheet.

**Comment by oleibman** [comment]
Support was added in Oct. 2022 PR #2829, with many enhancements since.
