### ISSUE TITLE
Get / set Xlsx phonetic guide data

### ISSUE THREAD

**Issue by sakinobashi** [PHPOffice/PhpSpreadsheet#1204]
From what I could gather, getting and setting phonetic guide data on Xlsx files is not yet supported by PhpSpreadsheet. I understand this is a niche feature, but it's essential for one of my current projects. Are there any plans to implement this in the near future?

**Comment by sakinobashi** [comment]
I've been looking into this, to see what could be done about it.
First of all, a disclaimer: I'm absolutely not an experienced programmer, and I don't know what are the best practices to be followed when contributing to open source projects. That's why I won't attempt to do this myself, but here's some information that might help whoever's available to do so.

Phonetic guides are saved in the sharedStrings.xml file along with the text. They follow this format:
```xml
    <si>
        <t>これは一つの例文です。</t>
        <rPh sb="3" eb="4">
            <t>ひと</t>
        </rPh>
        <rPh sb="6" eb="8">
            <t>れいぶん</t>
        </rPh>
        <phoneticPr fontId="1" type="Hiragana"/>
    </si>
```
So the text is `<t>` : これは一つの例文です。
Each phonetic guide is `<rPh>`, with the attributes *sb* and *se*, respectively the position of the beginning and end of the text the guide applies to.
There are two guides here: one is "ひと", for the character from 3 to 4 ("一"), and the other is "れいぶん", for the characters from 6 to 8 ("例文").

The text would, therefore, be displayed this way:
<span>これは<ruby><rb>一</rb><rt>ひと</rt></ruby>つの<ruby><rb>例文</rb><rt>れいぶん</rt></ruby>です。</span>

One of the question this issue raises is, what should the phonetic readings be translated to in PHP? Personally, I want to use them in HTML, so my suggestion would be returning a text value with phonetic guides as HTML; in this case:
- without phonetic guides
`これは一つの例文です。`
- with phonetic guides
 `これは<ruby><rb>一</rb><rt>ひと</rt></ruby>つの<ruby><rb>例文</rb><rt>れいぶん</rt></ruby>です。`.

This is as far as I've gotten. I can hack a way to make PhpSpreadsheet read phonetic guides, but it would hardly be code worthy of a pull request and I still haven't gotten around to figure out how to write them.

Anyway, if there's anyone considering implementing this, I hope this helps.

**Comment by sakinobashi** [comment]
*Help wanted!*

I've worked on actually writing phonetic guides, and got the basics working based on the RichText class:

1 - I created a PhoneticRichText class which extends RichText
````
    private $phoneticElements;

    public function __construct(Cell $pCell = null)
    {
        $this->phoneticElements = [];

        parent::__construct($pCell);
    }

    public function addPhoneticElement(int $start, int $end, string $text)
    {
        $this->phoneticElements[] = [
            'start' => $start,
            'end' => $end,
            'text' => $text
        ];
    }

    public function getPhoneticElements() : array
    {
        return $this->phoneticElements;
    }

    public function setPhoneticElements(array $elements) : void
    {
        $this->phoneticElements = $elements;
    }
````

On StringTable::writeRichText(), I added to the end of the foreach loop:
````
$phoneticElements =  $pRichText->getPhoneticElements();

if (!empty($phoneticElements)) {
    foreach ($phoneticElements as $phonetic) {
        $objWriter->startElement($prefix . 'rPh');
         $objWriter->writeAttribute('sb', $phonetic['start']);
         $objWriter->writeAttribute('eb', $phonetic['end']);

         $objWriter->startElement($prefix . 't');
         $objWriter->writeRawData(StringHelper::controlCharacterPHP2OOXML($phonetic['text']));
         $objWriter->endElement();

         $objWriter->endElement();
    }
    $objWriter->startElement($prefix . 'phoneticPr');
    $objWriter->writeAttribute('fontId', 1);
    $objWriter->endElement();
}
````

This is enough to make it work, with one reasonably big caveat: as you can see on `$objWriter->writeAttribute('fontId', 1);`, a font is associated to the phonetic guide. It's usually the same as the standard font, just with a smaller font size.
This is what I would like to have help with: I can't quite understand how to 1) create a font based on the default, and 2) get its index.

Any help in this regard would be greatly appreciated.

**Comment by oleibman** [comment]
Reopening. There is a lot of good work here. I also can't figure out at the moment how to link the proper font, so may not get to this for a while.

**Comment by oleibman** [comment]
I need to defer to you as we discuss this - it is difficult for me to evaluate what is "correct" if we implement this. And MS requires me to specify, say, Japanese as my *default* language for *all* Office applications before I can even see the results, which is very cumbersome; it handles this much more simply for Word than for Excel.

FontId - your `PhoneticRichText` class needs to add a font for the "upper" text. I don't know if it makes more sense for it to be a property of the class, or an additional entry in the `phoneticElements` array. Regardless, you need to add the font to both the class, and to the overall spreadsheet. It can be added to the spreadsheet multiple times, but once will suffice. Your code will resemble:
```php
$rubyStyle = new Style();
$rubyStyle->getFont()
    ->setName('MS Mincho')
    ->setSize(5); // you may need to specify other properties, e.g. alignment
$spreadsheet->addCellXf($rubyStyle);
/* also add $rubyStyle->getFont() to PhoneticRichText */
```

When it comes time to write it to Xlsx, you need to get the hash code of the font. You also need to find Xlsx Writer's `fontHashTable`. Run through that, starting with index 0 and incrementing by 1, until you find a font whose hash matches the desired hash. If you don't find a match, you just have to ignore the phonetic part of the rich text. But, if you do find a match, you now have the fontId which needs to be specified in the xml. A word of caution - I think, but am not certain, that the hash table is populated by the time we need it for this purpose. The problem becomes much more difficult if it isn't.

I think that's enough of a task for now. If we can get this part working, I think it will be time for you to open a PR. It will need more. Writing Html should be easier than writing Xlsx. I don't know how difficult reading Html will be. I am sure that reading Xlsx will be quite difficult.
