### ISSUE TITLE
insertNewRowBefore problem with worksheet references

### ISSUE THREAD

**Issue by sidoitsu48** [PHPOffice/PhpSpreadsheet#1205]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Example: 
Worksheet1 with cells in Column 'A'
Worksheet2 with cells: 
'A1': '=Worksheet1!A1'
'A2': '=Worksheet1!A2'
'A3': '=Worksheet1!A3'

insertNewRowBefore('A3',1) in Worksheet2

Worksheet2 with cells: 
'A1': '=Worksheet1!A1'
'A2': '=Worksheet1!A2'
'A3':
'A4': '=Worksheet1!A4'

### What is the current behavior?

insertNewRowBefore('A3',1) in Worksheet2

Worksheet2 with cells: 
'A1': '=Worksheet1!A1'
'A2': '=Worksheet1!A2'
'A3':
'A4': '=Worksheet1!A3'

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by oleibman** [comment]
PhpSpreadsheet's behavior seems to match Excel's. Leaving issue closed, removing stale label.
