### ISSUE TITLE
Load the proper classes

### ISSUE THREAD

**Issue by vaso123** [PHPOffice/PhpSpreadsheet#121]
I'd like to use your library, it could be great, but when I include the bootstrap file, it can not found the composer autoloader. 

Of course, becuase I have no composer installed on my host provider machine. 

I understand that the composer is a good thing, but something is really wrong with the code if can not be live without that. 

I am yawn, and go and write my autoloader but is it really my "job"?

Your code is not good becuase you are using composer, it is good becuase it works.

**Comment by vaso123** [comment]
And the download link offers me the developer version. Let's say that I am using composer:

`composer require phpoffice/phpspreadsheet


  [InvalidArgumentException]
  Could not find package phpoffice/phpspreadsheet at any version for your minimum-stability (stable). Check the packa
  ge spelling or your minimum-stability
`

**Comment by PowerKiKi** [comment]
composer is a hard requirement, you have to use it.

The [docs says](http://phpspreadsheet.readthedocs.io/en/develop/#installation) how to get dev version:
```
composer require phpoffice/phpspreadsheet:dev-develop
```

**Comment by vaso123** [comment]
The docs say 

`composer require phpoffice/phpspreadsheet`

I do not want the development version. What is not works anyway...

I just want to load a simple file (1.4Mb with 30 sheets with pure data, no shapes, no picture, no formulas), and it lost somewhere in a really "nice and tight" method in the Reader\Xlsx line 415. Sorry to say that, I can not debug exactly for you, where is it, because  first you should learn SOLID, first of all the "S" letter.

1516 lines for one mehod.

**Comment by ankitm123** [comment]
@vaso123, PHPSpreadsheet is still in development. Please take a look at this section in the  [readme file](https://github.com/PHPOffice/PhpSpreadsheet#phpexcel-vs-phpspreadsheet-)
As mentioned in the link, you can take a look at PHPExcel, if you do not want the development version of PHPSpreadSheet. (The issues that need to be resolved before  PHPSpreadSheet v1.0 can be released are listed [here](https://github.com/PHPOffice/PhpSpreadsheet/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0) )

**Comment by twose** [comment]
how about modifying content about composer in  /docs/index.md?

**Comment by PowerKiKi** [comment]
@twose I don't see how the doc could be more clear. I don't want to promote `dev-develop` as the standard way of doing things, because it is a bad habit and it should be kept as a "last resort". But if you see something else to be improved, please suggest via a PR.
