### ISSUE TITLE
Number Formatting Regression

### ISSUE THREAD

**Issue by natewiebe13** [PHPOffice/PhpSpreadsheet#1217]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When using format `#\ ##0.00`, `1234567.00` should be formatted to `1234 567.00`

### What is the current behavior?
`12 345.67` is the result, which is `expected / 100`.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/PhpSpreadsheet/vendor/autoload.php';

echo \PhpOffice\PhpSpreadsheet\Style\NumberFormat::toFormattedString(1234567.00, '#\ ##0.00') . PHP_EOL;
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.9.0

### Notes
A regression was introduced in https://github.com/PHPOffice/PhpSpreadsheet/commit/20f36ccd790ca556024c87a656de11c83df4c058 and released in 1.9.0 that outputs an incorrectly formatted number when using spaces as the thousands separator, and there are no decimal places in the number.

I have started a PR here: https://github.com/PHPOffice/PhpSpreadsheet/pull/1216 which currently just adds test cases for confirming the issue has been resolved. While attempting to fix the issue, I noticed that there's a couple of places a fix could be introduced, and that the previous version where this worked breaks other formatting options. Direction as to how the team would like this resolved would be great.

**Comment by MarkBaker** [comment]
resolved in master; I used your unit tests to confirm
