### ISSUE TITLE
Сondition without type checking

### ISSUE THREAD

**Issue by MrThompson96** [PHPOffice/PhpSpreadsheet#1219]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Get the value 0, when i export the table that contains the value (int) 0.

### What is the current behavior?

I get emptiness.

### What are the steps to reproduce?

I could not write code repeating this error.
But to repeat this you need to call a function fromArray of /phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php with parameters:
([
'0' => [
'parameter_1' => 2, 
'parameter_2' => 0, 
'parameter_3' => 1
]], 
null)

'parameter 2' = 0 will be interpreted as null

### Which versions of PhpSpreadsheet and PHP are affected?

1.9

### To fix it

need to add '=' in the file: /phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php 2512: 37

**Comment by sbreiler** [comment]
Link to function in question: [fromArray](https://github.com/PHPOffice/PhpSpreadsheet/blob/1.9.0/src/PhpSpreadsheet/Worksheet/Worksheet.php#L2492)

The function works as intended, but it should be called with
```php
$strictNullComparison = true
```
i think.

Are you using fromArray directly?

See also: #449

**Comment by MrThompson96** [comment]
No, I did`t use this function, but I will use this.
Thanks for the answer.
Thanks for the help.

**Comment by MrThompson96** [comment]
No, I did`t use this parameter, but I will use this.
Thanks for the answer.
Thanks for the help.
