### ISSUE TITLE
I want $writer->save() to download 

### ISSUE THREAD

**Issue by suleodu** [PHPOffice/PhpSpreadsheet#1225]
is there a way i can download the xlsx file to local system instead saving to server

**Comment by sbreiler** [comment]
Hello, please ask such questions on [StackOverflow](https://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet)

Have a look at the samples provided:
- [01_Simple_download_ods](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Basic/01_Simple_download_ods.php)
- [01_Simple_download_pdf](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Basic/01_Simple_download_pdf.php)
- [01_Simple_download_xls](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Basic/01_Simple_download_xlsx.php)
- [01_Simple_download_xls](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Basic/01_Simple_download_xls.php)

**Comment by MarkBaker** [comment]
Send the appropriate http response headers, and save to `php://output`
