### ISSUE TITLE
Chart Sheet Causing Error

### ISSUE THREAD

**Issue by LipatJob** [PHPOffice/PhpSpreadsheet#1231]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The excel file must be read without errors.

### What is the current behavior?
The file reader throws the error:
` Undefined index: rId1 in <project_directory>\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php on line 638`

### What are the steps to reproduce?
1. Create an excel file with a chart sheet
2. Load the excel file using PhpSpreadsheet

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$reader = IOFactory::createReader('Xlsx');
$spreadsheet = $reader->load('my-file.Xlsx');


```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet - 1.9.0
PHP - 7.3.9

**Comment by MarkBaker** [comment]
There is  PR for this [#1121](https://github.com/PHPOffice/PhpSpreadsheet/pull/1121), but it could use some unit tests

**Comment by oleibman** [comment]
Chart Sheets added by PR #2830 in May 2022.
