### ISSUE TITLE
Date::stringToExcel() unexpected behavior

### ISSUE THREAD

**Issue by mpryvkin** [PHPOffice/PhpSpreadsheet#1234]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
### What is the expected behavior?
Expect `\PhpOffice\PhpSpreadsheet\Shared\Date::stringToExcel('0.15')` to return `false` .

### What is the current behavior?
`\PhpOffice\PhpSpreadsheet\Shared\Date::stringToExcel('0.15')` detects `'0.15'` as date and returns `43784`

When used with `\PhpOffice\PhpSpreadsheet\Cell\AdvancedValueBinder` leads to conversion of all fixed precision numbers to Excel date.

### What are the steps to reproduce?

`\PhpOffice\PhpSpreadsheet\Shared\Date::stringToExcel('0.15')`

**Example**
```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

var_dump(\PhpOffice\PhpSpreadsheet\Shared\Date::stringToExcel('0.15'));
```
**Output**
```
double(43784)
```

### Which versions of PhpSpreadsheet and PHP are affected?
Tested with PhpSpreadsheet 1.9.0 and PHP 7.2

**Comment by oleibman** [comment]
The period in the string is being treated as a delimiter. So we have 2 fields, 0 and 15. Without going into all the gory details, this winds up being treated as year=current month=current day=15. This explains the unexpected behavior, and I don't think anything further need be done here - providing an ambiguous string will often not yield the expected result. I am more concerned about the AdvancedValueBinder comment, but I am unable to duplicate the symptom described. When it sees the string 0.15, or, for that matter, 43784, it treats them as numbers and does not attempt to treat them as dates.
