### ISSUE TITLE
Writer\Html output is much too large

### ISSUE THREAD

**Issue by werbfred** [PHPOffice/PhpSpreadsheet#1235]
This is:

```
- [ ] a bug report
- [x ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

When using the save method from **PhpOffice\PhpSpreadsheet\Writer\Html**, we could expect that only the usefull data is being outputed. This works fine for **PhpOffice\PhpSpreadsheet\Writer\Csv**.

### What is the current behavior?

Currently **PhpOffice\PhpSpreadsheet\Writer\Html** uses the method **_Worksheet::calculateWorksheetDimension()_** which is relying on **_Worksheet::getHighestColumn()_**.

In this case it could be better to rely on **_Worksheet::getHighestDataColumn()_**. This would avoid displaying a lot of empty cells on the right side of the html table. HTML file would also be much smaller.

### What are the steps to reproduce?

Call **_PhpOffice\PhpSpreadsheet\Writer\Html::save()_** and have the generated file rendered in your favortie web browser.

### Which versions of PhpSpreadsheet and PHP are affected?

Php version 7.3
PhpSpreadsheet version 1.9

**Comment by mathias-meyer** [comment]
Looking at the source code I would suggest that in **_Html::generateSheetData()_** the line 

```
$dimension = explode(':', $sheet->calculateWorksheetDimension());
```

should be replaced by

```
$dimension = explode(':', $sheet->calculateWorksheetDataDimension());
```
That would do the job I believe.

**Comment by mathias-meyer** [comment]
Any feedback if this feature makes sense ?

**Comment by adjenks** [comment]
Only the stale bot is responding to my tickets as well.

**Comment by mathias-meyer** [comment]
Up

**Comment by PowerKiKi** [comment]
I guess it makes sense. Have any of you had a look a git blame to see if there is a reason why we don't already do that?

**Comment by werbfred** [comment]
Should I make a Pull Request ?

**Comment by werbfred** [comment]
Pull Request raised : **Writer\Html output is much too large #1537**
