### ISSUE TITLE
syntax error  Calculation.php 

### ISSUE THREAD

**Issue by sevgicorumlu** [PHPOffice/PhpSpreadsheet#1241]
Parse error: syntax error, unexpected '=' in 
koolreport/excel/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php on line 2460
->   [$language] = explode('_', $locale);

**Comment by MAKS-dev** [comment]
Current online version code is only PHP 7.1 compatible:
```
            [$language] = explode('_', $locale);
```
Older version was (which is still supported in PHP):
```
            list($language) = explode('_', $locale);
```
https://www.php.net/manual/en/function.list.php
> **Symmetric array destructuring**
> The shorthand array syntax ([]) may now be used to destructure arrays for assignments (including within foreach), as an alternative to the existing list() syntax, which is still supported.

I don't like that this makes the code only support PHP7.1+ there is no actual need. Yes I know that support for older PHP versions are long dropped, but it is still wide spread.

Anyway @sevgicorumlu if this is the only error, you can change the line of code for now. But best is to upgrade to PHP7.3 all together ;-)

**Comment by sevgicorumlu** [comment]
thank you :)
