### ISSUE TITLE
Xls writer, on save, sets selected cell in sheet to last parsed cell with formula and cannot set active sheet (selects multiple sheets when available).

### ISSUE THREAD

**Issue by jimmy4o4** [PHPOffice/PhpSpreadsheet#1250]
Xls writer, on save, sets selected cell in sheet to last cell with formula and cannot set active sheet (selects multiple sheets when available).

This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
1. On save() with Xls writer, selected cell(s) should remain selected and selection should not change.
2. On save() with Xls writer, active sheet should remain active. Only one (active), not multiple sheets should be selected in output file.

### What is the current behavior?
1. On save() with Xls writer, cell(s) selection changes to last parsed sheet cell that contain formula;

This is caused by running \PhpOffice\PhpSpreadsheet\Cell\Cell::getStyle() method (in fact \PhpOffice\PhpSpreadsheet\Worksheet\Worksheet::getStyle()) in \PhpOffice\PhpSpreadsheet\Calculation\Calculation::_calculateFormulaValue() method.

2. On save() with Xls writer, output file has selected multiple sheets and active is not the one that was made active before save. Using LibreOffice Calc 6.3.2.2 x86 to open output file.

### What are the steps to reproduce?

```php
<?php

require_once 'vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet->setActiveSheetIndex(0)
    ->setTitle('Test1')
    ->setCellValue('D1', 1)
    ->setCellValue('D2', 2)
    ->setCellValue('D3', 3)
    ->setCellValue('D4', 4)
    ->setCellValue('D5', '=SUM(D1:D4)')
    ->setSelectedCell('A1');

$spreadsheet->createSheet(1);

$spreadsheet->setActiveSheetIndex(1)
    ->setTitle('Test2')
    ->setCellValue('D1', 4)
    ->setCellValue('E1', 3)
    ->setCellValue('F1', 2)
    ->setCellValue('G1', 1)
    ->setCellValue('H1', '=SUM(D1:G4)')
    ->setSelectedCell('A1');

$spreadsheet->setActiveSheetIndex(0);

echo $spreadsheet->getActiveSheetIndex() . PHP_EOL; // Prints 0
foreach ($spreadsheet->getAllSheets() as $sheet) {
    echo $sheet->getTitle() . ": " . $sheet->getActiveCell() . PHP_EOL;
    // Prints:
    // Test1: A1
    // Test2: A1
}

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xls');

$writer->save('Test.xls');

echo $spreadsheet->getActiveSheetIndex() . PHP_EOL; // Prints 1 (should be 0).
foreach ($spreadsheet->getAllSheets() as $sheet) {
    echo $sheet->getTitle() . ": " . $sheet->getActiveCell() . PHP_EOL;
    // Prints:
    // Test1: D5
    // Test2: H1
    // Should be:
    // Test1: A1
    // Test2: A1
}

// These changes (with wrong selected cells and sheets) has been saved to output file.
```

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet: since 1.7.0
PHP: 7.1.26 and 7.3.11 was used with the same result

**Comment by oleibman** [comment]
Fixed by PR #1256.
