### ISSUE TITLE
Implement date_default_timezone_set() function in Helper/Sample in log()

### ISSUE THREAD

**Issue by muniz034** [PHPOffice/PhpSpreadsheet#1251]
Implement date_default_timezone_set() function in Helper/Sample in log()
This is: 

```
- [ ] a bug report
- [X] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
To print the log with current timezone setted up by the server.

### What is the current behavior?
Probably printing the default time zone for Europe/London.

### What are the steps to reproduce?
- Use log() function from Helper/Sample object.

```php
<?php

require __DIR__ . '/vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Helper\Sample;

$helper = new Sample();

$helper->log('Some message');
```

```

- This will print H:i:s (from Europe/London) plus Some message

```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: 1.9.0
PHP: 7.3.1

**Comment by oleibman** [comment]
These messages currently use server timezone.
