### ISSUE TITLE
Workbook Calculation options

### ISSUE THREAD

**Issue by pedrofsantoscom** [PHPOffice/PhpSpreadsheet#1259]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
A function to set the `Workbook Calculation` options
![image](https://user-images.githubusercontent.com/2325978/69542306-13783980-0f83-11ea-9a5a-0b832808cec4.png)

### Which versions of PhpSpreadsheet and PHP are affected?
"phpoffice/phpspreadsheet": "^1.9"
php 7.3.1

**Comment by MarkBaker** [comment]
How does this differ from the Writer's option to `setPreCalculateFormulas(false)`?

**Comment by oleibman** [comment]
Question was answered. Removing stale label, leaving closed.
