### ISSUE TITLE
Support Shapes in twoCellAnchors

### ISSUE THREAD

**Issue by ntoniazzi** [PHPOffice/PhpSpreadsheet#126]
Are there plans to support [Shapes](http://www.officeopenxml.com/drwShape.php)? Currently, only [pictures](https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Reader/Xlsx.php#L1602) seems to be supported.
Thanks.

**Comment by PowerKiKi** [comment]
AFAIK there is no plan to work on that, but if you or somebody else is able to contribute a PR for that, it would be appreciated.
