### ISSUE TITLE
Readout only a distinct worksheet

### ISSUE THREAD

**Issue by Collie-IT** [PHPOffice/PhpSpreadsheet#1260]
This is:

```
- [ x] a feature request
```

### What is the expected behavior?
The readout process is sometimes very slow, Often only one sheet is of interested to read out. Other sheets can be scipt. To readout this unnecessary takes time and memory.  
I would like to have the possibility to readout only one distinct sheet from the workbook.

### What is the current behavior?
All sheets from workbook will be loaded.

### Which versions of PhpSpreadsheet and PHP are affected?
current

**Comment by MarkBaker** [comment]
So have you considered using the Reader's `setLoadSheetsOnly()` method to give the reader a sheet name or list of sheet names that it should read?
