### ISSUE TITLE
1.10  showing as 1.1  in text format .

### ISSUE THREAD

**Issue by jihadismail8** [PHPOffice/PhpSpreadsheet#1264]
$codeValue = "1.10";
$worksheet->getCell('A19')->getStyle('A19')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_TEXT);

 $worksheet->getCell('A19')->setValueExplicit($codeValue,\PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_INLINE);

in excel it shows as   "1.1"  , whats the problem ???

**Comment by MarkBaker** [comment]
You don't actually need the cell reference in the `getStyle()` call as you're explicitly getting the style for that cell already, and you shouldn't be calling `setValueExplicit()` with a datatype of `TYPE_INLINE` but of `TYPE_STRING` (INLINE is for rich text, and should only be use for rich text objects, not for simple string values.... that may be your problem

**Comment by jihadismail8** [comment]
Hi thanks for your answer  , but I did try without getting the cell and I tried data type  string   , but also no luck with them , any other ideas ?

**Comment by MarkBaker** [comment]
What format are you saving as?

**Comment by jihadismail8** [comment]
Standard   .xlsx

**Comment by MarkBaker** [comment]
I've just tried:
```
$spreadsheet = new Spreadsheet;

$worksheet = $spreadsheet->getActiveSheet();


$value = '1.10';
$cell = 'A1';

$worksheet
    ->getCell($cell)
    ->getStyle()
    ->getNumberFormat()
    ->setFormatCode(NumberFormat::FORMAT_TEXT);
;

$worksheet->getCell($cell)
    ->setValueExplicit($value, DataType::TYPE_STRING)
;


$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xls($spreadsheet);
$writer->save('formatTest.xls');
```
for both Xlsx and Xls Writers, and it works as expected
