### ISSUE TITLE
BUG. IF in XLSX not exists sharedStrings in the workbook.xml.rels

### ISSUE THREAD

**Issue by kozlikov** [PHPOffice/PhpSpreadsheet#1269]
```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
### Which versions of PhpSpreadsheet and PHP are affected?
php: 7.4
PHPOffice/PhpSpreadsheet: 1.10.0

This is:
`PHP Notice:  Trying to access array offset on value of type null in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 434
`
### File: .rels
```XML 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
     <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>
```
https://github.com/PHPOffice/PhpSpreadsheet/blob/f734783d826bd84c3d54fcf7b71c37ab9bac4b04/src/PhpSpreadsheet/Reader/Xlsx.php#L420

### File: workbook.xml.rels
```XML 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
   <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
   <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>
```

In the code below, we are trying to find a construct in the workbook.xml.rels file `http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings`
https://github.com/PHPOffice/PhpSpreadsheet/blob/f734783d826bd84c3d54fcf7b71c37ab9bac4b04/src/PhpSpreadsheet/Reader/Xlsx.php#L431

but in my xls file that I am trying to process, there are no `http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings` and in this case an error crashes, which leads to the script stopping.

Because when trying to get "http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings", variable $xpath to null `$xpath = self::getArrayItem($relsWorkbook->xpath("rel:Relationship[@Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings']"));`

This situation is very simple:
https://github.com/PHPOffice/PhpSpreadsheet/blob/f734783d826bd84c3d54fcf7b71c37ab9bac4b04/src/PhpSpreadsheet/Reader/Xlsx.php#L433

, please add to your additional check (`is_null($xpath) ?: simplexml_load_string`):
```php
                    $xpath = self::getArrayItem($relsWorkbook->xpath("rel:Relationship[@Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings']"));
                    //~ http://schemas.openxmlformats.org/spreadsheetml/2006/main"
                    $xmlStrings = is_null($xpath) ?: simplexml_load_string(
                        $this->securityScanner->scan($this->getFromZipArchive($zip, "$dir/$xpath[Target]")),
                        'SimpleXMLElement',
                        Settings::getLibXmlLoaderOptions()
                    );
```
And everything will work fine!
Thanks!

**Comment by PowerKiKi** [comment]
Fixed in 9fa45f7e4822da947d934369aac83d3b87303c80
