### ISSUE TITLE
How to get an array with merged cells?

### ISSUE THREAD

**Issue by dimmitri** [PHPOffice/PhpSpreadsheet#127]
A | B | C | D | E
--- | --- | --- | --- | ---
1 | 2 | 3 | 4 | 5

```php
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($file);
$reader->setReadDataOnly(true);
$spreadsheet = $reader->load($file);
$worksheet = $spreadsheet->getActiveSheet();
$worksheet->toArray(null, false);
```

```php
array(5) {
  [0]=>1
  [1]=>2
  [2]=>3
  [3]=>4
  [4]=>5
}
```

<table>
  <tr>
    <td>A</td>
    <td>B</td>
<td>C</td>
<td>D</td>
<td>E</td>
  </tr>
  <tr>
<td></td>
    <td colspan="3">2</td>
<td>5</td>
  </tr>
</table>

Now:
```php
array(5) {
  [0]=>NULL
  [1]=>2
  [2]=>NULL
  [3]=>NULL
  [4]=>5
}
```
Is it possible to get such result?
```php
array(3) {
  [0]=>NULL
  [1]=>2
  [2]=>5
}
```

**Comment by PowerKiKi** [comment]
AFAIK this is not possible.

Please next time keep questions on stackoverflow and only bug report on this issue tracker.
