### ISSUE TITLE
fromArray($data, NULL, 'A' . $sIndex);Unable to open file

### ISSUE THREAD

**Issue by jiechengyang** [PHPOffice/PhpSpreadsheet#1276]
This is:

```
use fromArray($data, NULL, 'A' . $sIndex);

It cannot be opened after more than 50 pieces of data have been written.But it can generate files normally.
```

**Comment by adjenks** [comment]
Unstale!

**Comment by MarkBaker** [comment]
Please explain the problem fully, with working example if necessary: because the examples provided with this library often use `toArray()` with more than 50 elements. Are there any errors?

**Comment by oleibman** [comment]
Requested information not supplied in over 4 years, removing stale label but keeping issue closed.
