### ISSUE TITLE
problems with formula

### ISSUE THREAD

**Issue by Bigmanni** [PHPOffice/PhpSpreadsheet#1279]
- [ x] a bug 
Using  lastest Release( composer install), with ubuntu16 PHP7, Office 2010

I open a existing xlsx file.
Some cells contain a formula like this
=WENN(ISTZAHL(A41);SVERWEIS(A41;'\\Hsnas\Vorlagen\EXCEL\[Rep2013.xls]deutsch'!$C$2:$E$101;3;FALSCH);" ")
These are apparently not read out correctly and removed by PHPSpreadsheet
If I try to rewrite the formula in PHP then this is also discarded.
also i try to set cell manuel  (with cast some chars)
$sheet->setCellValueExplicit(
        'D30','=WENN(ISTZAHL(A30);SVERWEIS(A30;\'\\\Hsnas\Vorlagen\EXCEL\[Rep2013.xls]deutsch\'!$C$2:$E$101;3;FALSCH);" ")',
\PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_FORMULA);
Not Work
If i set TYPE STRING  the Cell have the right  string  ( but  excel show it as string and i must set one time to formula.
It has the impression that it is related to the file path and or the formula analysis . ( slashes ....)
Now I am looking for a way to keep the formulas or rewrite in php in the cells.

**Comment by MarkBaker** [comment]
It's more likely the fact that `\Hsnas\Vorlagen\EXCEL[Rep2013.xls]` is referencing an external file, which PHPSpreadsheet can't verify in any way. but I'll run some tests to see if I can verify
