### ISSUE TITLE
I think that it must be replaced spaces without the Unicode option when outputting Excel.

### ISSUE THREAD

**Issue by tommykoko** [PHPOffice/PhpSpreadsheet#1284]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The processDomElement method dose not replace IDEOGRAPHIC SPACE(S) to a half-width space.

### What is the current behavior?
The processDomElement method replaces IDEOGRAPHIC SPACES to a half-width space.

### What are the steps to reproduce?
Outputting Excel with the text which has IDEOGRAPHIC SPACE(S) like below.
★
　★
　　★

The processDomElement method in PhpOffice\PhpSpreadsheet\Reader\Html treats and replaces IDEOGRAPHIC SPACE (Full-width space) as Unicode to a half-width space like below.
So IDEOGRAPHIC SPACES is replaced to a half-width space.

CODE as is
```php
$domText = preg_replace('/\s+/u', ' ', trim($child->nodeValue));
```

HTML does not replace IDEOGRAPHIC SPACES to a half-width space.

And many Japanese people use IDEOGRAPHIC SPACES as a formating text.
So please replace spaces without the Unicode Option when outputting Excel.

CODE to be
```php
$domText = preg_replace('/\s+/', ' ', trim($child->nodeValue));
```

### Which versions of PhpSpreadsheet and PHP are affected?
Ver 1.10.1

Best regards.

**Comment by oleibman** [comment]
This treatment dates back to PhpExcel. Like @tommykoko, I believe it is incorrect - Html's handling of whitespace corresponds to Php's *when the u modifier is not specified*, and it should be removed from Html Reader. This affects not only ideographic space but non-breaking space (and several other characters which I'm guessing aren't much used). I am reopening the issue. Expect a fix in a day or two.
