### ISSUE TITLE
Feature: functions to easy the creation process (functions inside)

### ISSUE THREAD

**Issue by knil-maloon** [PHPOffice/PhpSpreadsheet#1286]
Hi,

I was using PHPSpreadsheet and created some nice functions to easy the process of creating a new excel. I just though it could be useful to other developers.
It can be extended but in this example I just put the cases I used for my code.

/**
 * @param $sheet, excel sheet
 * @param $headers, array of column titles
 * @param $letters, array of letters
 * @param $width, array of width
 * @param $row_number, current row number
 *@param $backgroundcolor, hexadecimal color or background color
 * @return mixed, excel sheet
 */
function getExcelHeaders($sheet,$headers,$letters,$width,$row_number,$backgroundcolor){
    foreach ($headers as $index=>$header) {
        $sheet->setCellValue($letters[$index] . $row_number, $header);
        $sheet->getStyle($letters[$index] . $row_number)->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
        $sheet->getStyle($letters[$index].$row_number)->getFill()->getStartColor()->setARGB($backgroundcolor);
        $sheet->getStyle($letters[$index].$row_number)->getFont()->setBold( true );
        $sheet->getStyle($letters[$index].$row_number)->getBorders()->getAllBorders()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_MEDIUM);
        $sheet->getStyle($letters[$index].$row_number)->getAlignment()->setHorizontal('center');
        $sheet->getStyle($letters[$index].$row_number)->getAlignment()->setWrapText(true);

        $sheet->getColumnDimension($letters[$index])->setAutoSize(false);
        $sheet->getColumnDimension($letters[$index])->setWidth($width[$index]);
    }
    return $sheet;
}

/**
 * @param $sheet, excel sheet
 * @param $data_array, multidimensional array with the content
 * @param $headers, array of column titles
 * @param $letters, array of letters
 * @param $section_centered, array of 0 or 1 to center
 * @param $row_number, current row number
 * @para $section_background, array of 0 or 1 to add background color
 * @param $backgroundcolor, hexadecimal color or background color
 * @return mixed, excel sheet
 */
function getExcelData($sheet,$data_array,$headers,$letters,$section_centered,$row_number,$section_background,$backgroundcolor){
    foreach ($data_array as $row => $data) {
        foreach ($headers as $index => $header) {
            $sheet->setCellValue($letters[$index].$row_number, $data[$index]);
            $sheet->getStyle($letters[$index].$row_number)->getBorders()->getAllBorders()->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN);
            $sheet->getStyle($letters[$index].$row_number)->getAlignment()->setWrapText(true);
            if($section_centered[$index] == "1"){
                $sheet->getStyle($letters[$index].$row_number)->getAlignment()->setHorizontal('center');
            }
            if($section_background[$index] == "1"){
                 $sheet->getStyle($letters[$index].$row_number)->getFill()->getStartColor()->setARGB($backgroundcolor);
             }
        }
        $row_number++;
    }
    return $sheet;
}

**Comment by oleibman** [comment]
These functions seem too be much too specialized to be of general use.

Leaving issue closed, removing stale label.
