### ISSUE TITLE
2  bugs about chart

### ISSUE THREAD

**Issue by wuwenweichris** [PHPOffice/PhpSpreadsheet#1287]
This is:

```
- [* ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the current behavior?
1. Export the file with chart and the chart title is not empty character. After opening and modifying the excel content, there is an error in saving the file

2.Read the excel file with chart and the chart style is not the default. Generate a new EXCEL file without modifying the chart data. The new EXCEL file loses the original style

### What are the steps to reproduce?
question 2 code

```php
<?php

require __DIR__ . '/vendor/autoload.php';


$reader = IOFactory::createReader("Xlsx");
$reader->setIncludeCharts(true);

header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="new.xlsx"');
header('Cache-Control: max-age=0');

$writer = IOFactory::createWriter($spreadsheet,'Xlsx');
$writer->setIncludeCharts(true);
$writer->save('php://output');
die;

```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet : the newest version
PHP:7.1

**Comment by oleibman** [comment]
I believe that both these issues are long resolved. Reopen with a sample file if you feel this isn't the case. Removing stale label, leaving issue closed.
