### ISSUE TITLE
Any autoremove commands in project ?

### ISSUE THREAD

**Issue by ohmountain** [PHPOffice/PhpSpreadsheet#129]
When i require phpoffice/phpspreadsheet in my php project and try to read an xlsx file, the folder 'vendor/phpoffice/phpspreadsheet/' becomes empty, it happens many times. My enviroment : Ubuntu 16.04, php7.0, the project requires only phpoffice/phpspreadsheet and phpoffice/phpexcel.

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. And don't forget to mention what version of this project you are using. That way there will be more chance for the issue to be solved.
