### ISSUE TITLE
XLSM with autostart macro

### ISSUE THREAD

**Issue by HeinzWuert** [PHPOffice/PhpSpreadsheet#1290]
- [ ] a bug report
Excel macros with autostart (while opening or closing) are saved in the area "ThisWorkbook".
This macro calls other sheet oriented macros.
When filling such a template PhpSpreadsheet creates a new "ThisWorkbook1". Here are missing the macros of the origininal one and the autostart function does not work with this newly createtd file.

### What is the expected behavior?
copying macros out of "ThisWorkbook" into the newly created "ThisWorkbook1" or prevent the behaviour of creating this.

### Which versions of PhpSpreadsheet and PHP are affected?
actual

**Comment by oleibman** [comment]
Current version copies ThisWorkbook correctly.
