### ISSUE TITLE
Undefined offset in Xlsx reader

### ISSUE THREAD

**Issue by nick-lai** [PHPOffice/PhpSpreadsheet#1293]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### Which versions of PhpSpreadsheet and PHP are affected?

```
php: ^7.0

PHPOffice/PhpSpreadsheet: ^1.8.2
```

File: [Undefined offset in Xlsx reader(Cell B1 is an empty richtext).xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3999415/Undefined.offset.in.Xlsx.reader.Cell.B1.is.an.empty.richtext.xlsx)

https://github.com/PHPOffice/PhpSpreadsheet/blob/9fab8900ef9a4f5ba293e738b0350f7ffe6acead/src/PhpSpreadsheet/Reader/Xlsx.php#L439-L447

The processing of 441 to 445 lines causes the `$sharedStrings` array to skip the empty `SimpleXMLElement` object.

Example for `$xmlStrings`:

```php
SimpleXMLElement::__set_state(array(
    // '@attributes' => ...
    'si' =>
    array (
        0 => SimpleXMLElement::__set_state(array(
           't' => 'Name',
        )),
        1 => SimpleXMLElement::__set_state(array()), // will be skipped.
        // ...
    )
))
```

https://github.com/PHPOffice/PhpSpreadsheet/blob/9fab8900ef9a4f5ba293e738b0350f7ffe6acead/src/PhpSpreadsheet/Reader/Xlsx.php#L675-L688

In this case, a `undefined offset` error would occur on line 679.

Fix for empty SimpleXMLElement:

```php
foreach ($xmlStrings->si as $val) {
    if (isset($val->t)) {
        $sharedStrings[] = StringHelper::controlCharacterOOXML2PHP((string) $val->t);
    } elseif (isset($val->r)) {
        $sharedStrings[] = $this->parseRichText($val);
    } else {
        // When SimpleXMLElement is empty the `t` and `r` properties no exists.
        $sharedStrings[] = ''; 
    }
}
```

**Comment by nick-lai** [comment]
[Undefined offset in Xlsx reader(Cell B1 is an empty richtext).xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3999415/Undefined.offset.in.Xlsx.reader.Cell.B1.is.an.empty.richtext.xlsx)

**Comment by nick-lai** [comment]
@MarkBaker

**Comment by oleibman** [comment]
Reopening, (very late) fix is on the way.
