### ISSUE TITLE
Drawings get lost addExternalSheet

### ISSUE THREAD

**Issue by CiTRO33** [PHPOffice/PhpSpreadsheet#1294]
This is:

```
- [x] a bug report
```

### What is the expected behavior?

two xlsx-template files with one sheet and a image should combined into one xlsx with two sheets.

### What is the current behavior?

xlsx-files gets combined and corrupted, recovered xlsx removes the image on second sheet.

maybe its the same cause: see #1140, #927, #1022 https://github.com/PHPOffice/PhpSpreadsheet/issues/877#issuecomment-515455684 

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx ();
$spfirst = $reader->load ( "first.xlsx" );
$spsecond = $reader->load ( "second.xlsx" );
$pSheet = $spsecond->getActiveSheet ();
$spfirst->addExternalSheet ( $pSheet, 0 );

$objWriter = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx ( $spfirst );
$objWriter->setPreCalculateFormulas ( true );

$objWriter->save ( "result.xlsx" );


Example files:

[first.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3991477/first.xlsx)
[second.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3991479/second.xlsx)

[result.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3991478/result.xlsx)

### Which versions of PhpSpreadsheet and PHP are affected?

1.10.1 / 1.8.2

**Comment by hazem-kifah** [comment]
Did you try
```php
<?php

$reader->setIncludeCharts(true);
```

```php
<?php

$objWriter->setIncludeCharts(true);
```
before saving?

I have a problem even with include charts enabled that it always says the drawing is corrupted and deletes it from the result Excel.

**Comment by CiTRO33** [comment]
> 
> 
> Did you try
> 
> ```
> <?php
> 
> $reader->setIncludeCharts(true);
> ```
> 
> and
> 
> ```
> <?php
> 
> $objWriter->setIncludeCharts(true);
> ```
> 
> before saving?
> 
> I have a problem even with include charts enabled that it always says the drawing is corrupted and deletes it from the result Excel.

this didn't work either.
the second image is still removed

**Comment by YanSt** [comment]
I confirm that there is a problem. But, I  reproduced it only on version 1.10.1. As a temporary solution, I rolled back to 1.10.0.

I used these samples to test it:
vendor/phpoffice/phpspreadsheet/samples/Chart/33_Chart_create_area.php
vendor/phpoffice/phpspreadsheet/samples/Chart/33_Chart_create_bar.php

Besides. OpenOffice opens files correctly. And if you re-save them with OpenOffice, then the Excel opens without an error.

**Comment by CiTRO33** [comment]
I made some tests with  previous Versions.
with version 1.2.1 the "addExternalSheet" dont corrupt the drawings.
With Version 1.3.0  it gets broken.
I think the pull #435 broke this. 
maybe someone can investigate into.

@YanSt i only work with images not with charts.

**Comment by CiTRO33** [comment]
this problem still occurs.
Any investigation?

**Comment by parthkharecha** [comment]
**displayBlanksAs Repace 0 to gap**
 
```
   $chart = new Chart(
                    'PROCESSED LEADS BREAKDOWN', // name
                    $title, // title
                    $legend, // legend
                    $plotArea, // plotArea
                    true, // plotVisibleOnly
                    'gap', // displayBlanksAs //Repace 0 to gap
                    null, // xAxisLabel
                    null   // yAxisLabel- Like Pie charts, Donut charts don't have a Y-Axis
                );
```
https://github.com/PHPOffice/PhpSpreadsheet/issues/942#issuecomment-605392953

**Comment by CiTRO33** [comment]
@parthkharecha  this didn't solve my problem.
I don't include a Chart. I have only a image in two created excelsheet with MS Excel.
And i want to combine this two sheets with PHPSpreadsheet

**Comment by CarlosArango** [comment]
I have the same problem, please let me know  if  anyone resolve it ? 
I have a custom template with charts, and it`s working  good in  Google Sheet but in Excel the file is corrupted and just show the data not the charts
