### ISSUE TITLE
[Question] How to apply style to the whole column with an unknown amount of rows

### ISSUE THREAD

**Issue by milewski** [PHPOffice/PhpSpreadsheet#1295]
Hi is it possible to set style to the whole column without specifying a range `A1:A99999` for example,

```php
->getStyle('A1:A' . self::$count) // currently this work but it`s not ideal
->applyFromArray([....]);
```

what I was hoping to achieve would be as simple as just specifying the column without a row number and get the whole column style applied:

```php
->getStyle('A')->applyFromArray([...]);
```

or is there a method I can use to get the total of rows generated so far which I can use to feed on the range?

**Comment by MAKS-dev** [comment]
Please ask your support questions on StackOverflow, or have a quick chat on Gitter.

However, this should work: `getStyle('A:A')`
This is the same notation as is used in Excel.
