### ISSUE TITLE
How to add some margin between a cell and an image?

### ISSUE THREAD

**Issue by elieobeid7** [PHPOffice/PhpSpreadsheet#1297]
When inserting an image into a cell, it gets inserted to the very left of the cell, I'd like to add some margin, how to do so?

I tried many things, I'm not the first to ask this, it's being asked since the days of PHPexcel and there's no answer, I tried every solution to no avail, like this one, which should center whatever is in the cell

    function center(){
    $styleArray = [
        'alignment' => [
            'vertical' => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER,
            'horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER,
        ],
    ];
    return $styleArray;
    }
    $sheet->getStyle('B2')->applyFromArray(center()));

I'm not necessarily trying to center it, whatever works, all I need is some margin between the cell and the image.

**Comment by MarkBaker** [comment]
Images aren't inserted into cells; images are effectively in a "layer" over the cells, and aren't influenced by cells styles, alignments, etc.
When you position an image, and specify a cell, you aren't storing the image in that cell; you are simply specifying a position relative the the cell grid where the image will be overlaid.
By default, the image will be overlaid relative to the top left corner of the cell that you specify; but you can also specify X and Y offsets from that corner.
```
$drawing = new Drawing();
$drawing->setName('PhpSpreadsheet logo');
$drawing->setDescription('PhpSpreadsheet logo');
$drawing->setPath(__DIR__ . '/../images/PhpSpreadsheet_logo.png');
$drawing->setHeight(36);
$drawing->setCoordinates('B2');
$drawing->setOffsetX(10);    // top left corner of the image will be offset 10 units to the right the top left corner of the cell
$drawing->setOffsetY(5);     // top left corner of the image wil be offset 5 units below the top left corner of the cell
$drawing->setWorksheet($spreadsheet->getActiveSheet());
```

**Comment by elieobeid7** [comment]
Thank you so much!
