### ISSUE TITLE
Looping through cells

### ISSUE THREAD

**Issue by lifeismeme** [PHPOffice/PhpSpreadsheet#1298]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
The seek method is not working for the RowIterator:
\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet::getRowIterator
$RowIterator->seek(200);

### What is the expected behavior?
after calling $RowIterator->seek(200); looping through the row will now begin at row position 200

### What is the current behavior?
calling seek() does nothing, the row still start at row 1.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

sample code:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load('sample.xlsx');
$worksheet = $spreadsheet->getActiveSheet();

$list = [];
//problem is here, seek to row 200 is nothing working
$it = $worksheet->getRowIterator()->seek(200);
//it still start at row 1
foreach ($it as $row) {
    $cellIt = $row->getCellIterator();
    $r = [];
    foreach ($cellIt as $cell) {
        $r[] = $cell->getFormattedValue();
    }
    $list[] = $r;
}
//in the end the list contains all the row values, row 1 to row n
var_dump($list);



### Affected versions of PhpSpreadsheet and PHP ?
PhpSpreadsheet 1.10.1 
PHP 7.2

**Comment by CiTRO33** [comment]
Its the normal behavoir because foreach reset the seekposition
Use 
`$it = $worksheet->getRowIterator(200)`

to start at row 200
