### ISSUE TITLE
Spreadsheet changes values on writer save

### ISSUE THREAD

**Issue by uneasymusic** [PHPOffice/PhpSpreadsheet#1299]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I have spreadsheet open that I am working on, I don't change any values , just changing colors and then creating new writer and saving new spreadsheet to file.  

### What is the current behavior?
Some Values all values for IMEI number which is 11 digit numbers, are changed ( some added 1 some added 3 and some different) . It happens on writer save, I checked spreadsheet just before save and values remain as they should be. 

### What are the steps to reproduce?
so for e.g. in one column I have IMEI numbers e.g. 357818100172547 
but in output file it comes up as 3578181001725**50**

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$writer = new Writer($spreadsheet);
$writer->save($destinationFolder);
```

### Which versions of PhpSpreadsheet and PHP are affected?
 **1.10.1**

**Comment by elieobeid7** [comment]
Would you please provide some testable code? the snippet you pasted cannot be tested, anything that we could copy and paste into an editor and test.

**Comment by uneasymusic** [comment]
I did eventually found the cause. 
The spreadsheet I was opening, was in XLS format, and when I was saving it with writer I was using xlsx writer. Not sure why, but that was changing my values. When I saved it back to original format, it was fine.

**Comment by elieobeid7** [comment]
Could you please close this issue? So that we help the maintainers know that this issue is closed :)
