### ISSUE TITLE
lost conditions :(

### ISSUE THREAD

**Issue by CrazyBite** [PHPOffice/PhpSpreadsheet#130]
Hello, PhpSpreadsheet lost conditions on "read-write" file. 
Code:

```php
require_once '/vendor/autoload.php';
$objReader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader("Xlsx");
$objPHPExcel = $objReader->load("test1.xlsx");			
$objWriter = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($objPHPExcel, 'Xlsx');		
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="test1_after.xlsx"');
header('Cache-Control: max-age=0');
$objWriter->save('php://output');
exit;
```

xlsx file for example here : https://github.com/CrazyBite/temp/blob/master/test1.xlsx
Look on all conditions on sheet before and after "read-write" procedure.

**Comment by PowerKiKi** [comment]
Would you be able to modify your code not to use any external file ? So creating the file with PhpSpreadsheet, writing it, reading it, and confirm the absence of conditions all by code ?

**Comment by CrazyBite** [comment]
Lost only conditions created with the Microsoft Office Software :\

**Comment by ajaxovic** [comment]
Funny... My issue #117 is almost same, I provided lot of tests and is not accepted. 👍

**Comment by PowerKiKi** [comment]
@ajaxovic thanks for letting me know. You are right. I am closing this as duplicate of #117
