### ISSUE TITLE
loadFromString()

### ISSUE THREAD

**Issue by andreaquiles** [PHPOffice/PhpSpreadsheet#1308]
Call to undefined method PhpOffice\PhpSpreadsheet\Reader\Html:loadFromString()
already updated and nothing via composer.
What's happened ?

**Comment by Finicnl** [comment]
same here

**Comment by itgoldman** [comment]
indeed you should update version of PHPOffice to at least "phpoffice/phpspreadsheet": "^1.16"

**Comment by andreaquiles** [comment]
> 
> 
> indeed you should update version of PHPOffice to at least "phpoffice/phpspreadsheet": "^1.16"

thanks
