### ISSUE TITLE
Calculation.php Parse error 

### ISSUE THREAD

**Issue by alpchokmah** [PHPOffice/PhpSpreadsheet#1309]
Type: ParseError
Message: syntax error, unexpected '='
Filename: vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php
Line Number: 2460

I'm using PHP v7.3 and read in past issues that this line is compatible for v7.1 and need to upgrade it. Well, I have upgraded but still encountered issue. 

Anyone solved this?

**Comment by eduzetapy** [comment]
I have the same inconvenience :(

**Comment by eduzetapy** [comment]
@alpchokmah  do you have another version of php installed?

**Comment by oleibman** [comment]
Regrettably, there is just not enough information in this ticket to take any action. Leaving issue closed, removing stale label.
