### ISSUE TITLE
How to set text in two columns or more

### ISSUE THREAD

**Issue by uldcra** [PHPOffice/PhpSpreadsheet#1314]
Sorry my english is very poor.
How to put the text in multiple columns ('A1:B1', 'hello word')
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();

$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Hello World !');
$sheet->setCellValue('A2', 'Hola a todos !');

$writer = new Xlsx($spreadsheet);
$writer->save('excel/hello world.xlsx');

**Comment by elieobeid7** [comment]
I believe you are looking for merge

```
$sheet->setCellValue('A1', 'Hello World !');
$sheet->setCellValue('A2', 'Hola a todos !');
$sheet->mergeCells('A1:A2');
```

**Comment by uldcra** [comment]
Sorry my english.
A lot of thanks.

**Comment by elieobeid7** [comment]
Could you please close this issue? So that we help the maintainers know that this issue is closed :)
