### ISSUE TITLE
[Excel to HTML] rowspan is not shown up

### ISSUE THREAD

**Issue by dev-yakuza** [PHPOffice/PhpSpreadsheet#1319]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the current behavior?

this excel file([test_bug.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4057887/test_bug.xlsx)) has merged cell(A1:E3) like below.

![Screen Shot 2020-01-14 at 16 45 05](https://user-images.githubusercontent.com/42969906/72324092-84b7ab80-36ed-11ea-9c96-4849ffcdfdf7.png)

I generated HTML file from this file. and I expected first row(tr tag) has `rowspan="3"` but didn't has it like below.

<img width="1278" alt="Screen Shot 2020-01-14 at 16 45 53" src="https://user-images.githubusercontent.com/42969906/72324135-9600b800-36ed-11ea-848c-6979cccff092.png">

however, insert empty row and column to A1 like this file([test_ok.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4057895/test_ok.xlsx)) like below,

<img width="547" alt="Screen Shot 2020-01-14 at 16 45 14" src="https://user-images.githubusercontent.com/42969906/72324183-aca70f00-36ed-11ea-9fa6-76821a9fbc8e.png">

merged cell is generated with `rowspan="3"` like below.

<img width="1278" alt="Screen Shot 2020-01-14 at 16 46 19" src="https://user-images.githubusercontent.com/42969906/72324208-b9c3fe00-36ed-11ea-9d2e-2ec3f3662543.png">

### What are the steps to reproduce?

when I commented out a line of source code below, generated HTML file with rowspan from problem excel file.

```php
 $this->isSpannedRow[$sheetIndex][$rowIndex] = $rowIndex;
```
in

```php
// Identify which rows should be omitted in HTML. These are the rows where all the cells
            //   participate in a merge and the where base cells are somewhere above.
            $countColumns = Coordinate::columnIndexFromString($sheet->getHighestColumn());
            foreach ($candidateSpannedRow as $rowIndex) {
                if (isset($this->isSpannedCell[$sheetIndex][$rowIndex])) {
                    if (count($this->isSpannedCell[$sheetIndex][$rowIndex]) == $countColumns) {
                        $this->isSpannedRow[$sheetIndex][$rowIndex] = $rowIndex;
                    }
                }
            }

            // For each of the omitted rows we found above, the affected rowspans should be subtracted by 1
            if (isset($this->isSpannedRow[$sheetIndex])) {
                foreach ($this->isSpannedRow[$sheetIndex] as $rowIndex) {
                    $adjustedBaseCells = [];
                    $c = -1;
                    $e = $countColumns - 1;
                    while ($c++ < $e) {
                        $baseCell = $this->isSpannedCell[$sheetIndex][$rowIndex][$c]['baseCell'];

                        \Log::error('$baseCell: ');
                        \Log::error($baseCell);
                        \Log::error('$adjustedBaseCells: ');
                        \Log::error($adjustedBaseCells);
                        if (!in_array($baseCell, $adjustedBaseCells)) {
                            // subtract rowspan by 1
                            --$this->isBaseCell[$sheetIndex][$baseCell[0]][$baseCell[1]]['rowspan'];
                            $adjustedBaseCells[] = $baseCell;
                            \Log::error('$sheetIndex: ' . $sheetIndex);
                            \Log::error('$baseCell[0]: ' . $baseCell[0]);
                            \Log::error('$baseCell[1]: ' . $baseCell[1]);
                            \Log::error($this->isBaseCell);
                        }
                    }
                }
            }
```

### Which versions of PhpSpreadsheet and PHP are affected?

1.10

**Comment by dev-yakuza** [comment]
any news?

**Comment by oleibman** [comment]
Reopening. Expect a fix in a day or two.
