### ISSUE TITLE
1.0.0 Release?

### ISSUE THREAD

**Issue by HeathNaylor** [PHPOffice/PhpSpreadsheet#133]
Any plans to have a release and start giving us some semantic versioning? Right now breaking changes could be merged and our composer file would have little protection against it.

**Comment by ankitm123** [comment]
@HeathNaylor, I think once all the issues tagged with milestone 1.0 are done, it will be released.
Take a look at these issues:
https://github.com/PHPOffice/PhpSpreadsheet/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0

**Comment by PowerKiKi** [comment]
@ankitm123 is correct. When approaching completion of milestone a beta might be released, and then a final 1.0.0. From then on we'll stick to semver.

Next time time please use [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet) for discussion.
