### ISSUE TITLE
Support customHeight attribute on row

### ISSUE THREAD

**Issue by serverdevil** [PHPOffice/PhpSpreadsheet#1330]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When a row is manually resized in an Excel file, an attribute customHeight="1" is added to the row. This attribute should be available when reading an Excel file.

### What is the current behavior?
Said attribute is not considered during read operation. However, writer code has the attribute set, when applicable.

### What are the steps to reproduce?
File with 2 rows, 1st row has automatic height, 2nd was manually resized.
[customHeight.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4075002/customHeight.xlsx)
NOTE: This file was created using LibreOffice (I'm Linux only, right now) and hence attribute shows up as `customHeight="true"`. MS Excel generated files have `customHeight="1"`

### Which versions of PhpSpreadsheet and PHP are affected?
Latest

phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx/ColumnAndRowAttributes.php
`readRowAttributes()`?

**Comment by serverdevil** [comment]
Any comments on this, guys!?

**Comment by oleibman** [comment]
Heights are now processed correctly when loading and saving supplied spreadsheet.
