### ISSUE TITLE
Invalid cell coordinate - VLOOKUP

### ISSUE THREAD

**Issue by seltix5** [PHPOffice/PhpSpreadsheet#1331]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Get the calculated value ( "2" in the provided test.xlsx )

### What is the current behavior?
error : PhpOffice\PhpSpreadsheet\Calculation\Exception: b!A1 -> Invalid cell coordinate A1+1

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$xlsx = \PhpOffice\PhpSpreadsheet\IOFactory::load($testxlsx);
$xlsx->getSheetByName('b')->getCell('A1')->getCalculatedValue();
```
[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4079001/test.xlsx)

I did not find online how to add entry in the "Name Manager" with PhpSpreadsheet but the provided file is just :

- sheet "a" : A1 => "1"
- sheet "b" : A1 => "=vartest"

and in "Formulas > Name Manager" I created entry with :
- Name : vartest
- Refers to : =a!$A$1+1

### Which versions of PhpSpreadsheet and PHP are affected?
PHP : 7.2
PhpSpreadsheet : 1.10.1

**Comment by seltix5** [comment]
no reply?

**Comment by seltix5** [comment]
Bump

**Comment by seltix5** [comment]
No reply?

**Comment by MarkBaker** [comment]
Named formulae currently aren't supported, only named ranges; but I've recently been working on improvements to the handling of ranges and named ranges, so I'll take a look and see how easy it is to implement named formulae

**Comment by seltix5** [comment]
Any news?

**Comment by pich** [comment]
> Named formulae currently aren't supported, only named ranges; but I've recently been working on improvements to the handling of ranges and named ranges, so I'll take a look and see how easy it is to implement named formulae

Any update on Named formulas? @MarkBaker please provide me with some code references, I may be able to help.

**Comment by seltix5** [comment]
Any update on this?

**Comment by oleibman** [comment]
Named formulas were implemented in Release 1.15.0.

**Comment by pich** [comment]
Awesome, @oleibman Could you please point the specific commit that fixed this issue?

**Comment by oleibman** [comment]
PR #1535.
