### ISSUE TITLE
Cannot create spreadsheet with more than 26 columns

### ISSUE THREAD

**Issue by martinezjr231** [PHPOffice/PhpSpreadsheet#1335]
This is:

```
- [XX] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Create a spreadsheet with more than 26(A-Z) columns.

### What is the current behavior?
column AA is not a valid reference(coord

### What are the steps to reproduce?
create a spreadsheet with more than 26 columns

// add code that show the issue here...
columns = Array
(
    [0] = Line#
    [1] = Item Name
    [2] = Additional Info
    [3] = Qty Rqstd
    [4] = Lowest Price
    [5] = Vendor1
    [6] = Vendor2
    [7] = Notes
    [8] = -
    [9] = Vendor1 Item Number
    [10] = Vendor1 Unit Size
    [11] = Vendor1 Pack Price
    [12] = -
    [13] = Vendor2 Item Number
    [14] = Vendor2 Unit Size
    [15] = Vendor2 Pack Price
    [16] = -
    [17] = -
    [18] = -
    [19] = Vendor1 Won
    [20] = Vendor1 Order
    [21] = Vendor1 Total
    [22] = -
    [23] = Vendor2 Won
    [24] = Vendor2 Order
    [25] = Vendor2 Total
    [26] = -
)

```Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Exception: Invalid cell coordinate [12 in /var/www/html/classes/spreadsheet_v1/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php:41 Stack trace: #0 /var/www/html/classes/spreadsheet_v1/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(1267): PhpOffice\PhpSpreadsheet\Cell\Coordinate::coordinateFromString('[12') #1 /var/www/html/classes/spreadsheet_v1/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(1227): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->createNewCell('[12') #2 /var/www/html/classes/spreadsheet_v1/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(1126): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->getCell('[12') #3 /var/www/html/modules/inventory/makeTabulation.php(71): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->setCellValue('[12', '-') #4 /var/www/html/modules/inventory/tab.php(118): require_once('/var/www/html/m...') #5 /var/www/html/index.php(139): include('/var in /var/www/html/classes/spreadsheet_v1/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php on line 41


### Which versions of PhpSpreadsheet and PHP are affected?
phpoffice 1.8.1 php v7.2.20

**Comment by elieobeid7** [comment]
I have never tried to create an excel sheet with more than 26 columns but it should be feasable. After A-Z you get AA, AB, and so on

Actually you could do something like


```
$col ='A';
++$col; //in a loop;
$sheet->setCellValue($col . 'something');
```

or if you want to increment by more than one you could do

`$col = chr(ord($col) + 1);`

Again I never got to 26 columns but I don't believe this is a bug, have you tried doing `AA` and so on after `Z`?

**Comment by Goodnato** [comment]
Hello,

I tested and work normally.

I used this code:

`$col= 'A';`
`for ($i = 1; $i < 60; $i++) {`
`$row= 1;`
`$sheet->setCellValue(($col.$row), 'Hello World !');`
`$col++;`
`}`

The last column in Excel is BG.

**Comment by elieobeid7** [comment]
Agreed, the issue should be closed.

**Comment by MarkBaker** [comment]
PHPSpreadsheet is not limited to 2 columns, but can handle the full MS Excel column range up to 256 (IV) for xls and 16.384 (XFD) for xlsx

**Comment by martinezjr231** [comment]
While I would agree that it should handle more than 26 columns, it was in the code that I was using.  Instead of using similar to Goodnato's reply, I was using chr() function to reference the alphabetical part.  I have changed it to $colOffset = "A"; $colOffset++;
`

**Comment by DarwingRuiz** [comment]
Hello, I follow this way, how do I decrease the $col variable? if $col-- doesn't work

**Comment by MarkBaker** [comment]
One option you have is to use the Column Iterator, which has a `prev()` method.

As an alternative:
```php
$col = 'AA';
var_dump(decrementColumn($col));

function decrementColumn(string $column): string {
    $columnIndex = Coordinate::columnIndexFromString($column)
    return Coordinate::stringFromColumnIndex($this->columnIndex);
}
```
I've not shown any logic for error handling, e.g. what to do if you pass a value of `A` to the function; you can decide that for yourself.

**WARNING:** PHP Internals are looking at deprecating the increment operator for strings in the next release, although I'm hoping that they'll reconsider when it comes to the vote.
