### ISSUE TITLE
Excel file containing string which must be escaped cannot be correctly read.

### ISSUE THREAD

**Issue by vonobow** [PHPOffice/PhpSpreadsheet#1336]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Excel file which contains characters must be escaped should be correctly read.

### What is the current behavior?
Excel file which contains string like "_x0012_foo" cannot be correctly read.
I got the result like as: "_x005Ffoo"

### What are the steps to reproduce?
Execute following code by PHP interpreter.
This code expects the output

_x005F_x0020_foo
_x005F_x0012_foo

or 

_x0020_foo
_x0012_foo

but actual result is:

_x005F_x0020_foo
_x005Ffoo

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$sheet = $spreadsheet->getSheet(0);

// Put string value "_x0020_foo" and "_x0012_foo" into the cells,
// but should we escape "_" (U+005F) as "_x005F_" ?
$sheet->setCellValue("A1", "_x005F_x0020_foo");
$sheet->setCellValue("A2", "_x005F_x0012_foo");

// save as Excel file
$filename = "test-escape-php.xlsx";
$writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save($filename);
// This file is correctly read by Excel and Excel interprets these
// string as "_x0020_foo" and "_x0012_foo",
// xl/sharedStrings.xml in test-escape-php.xlsx holds
// these string as "_x005F_x0020_foo" and "_x005F_x0012_foo".

// read the file written above.
$reader = new PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$xlsx = $reader->load($filename);
foreach ($xlsx->getSheet(0)->toArray() as $v)
	fputcsv(STDOUT, $v);

// This produces following output:
// _x005F_x0020_foo
// _x005Ffoo
// The first line is acceptable result,
// although it's better that unescaped strings are returned.
// The second line is possibly incorrect.

```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadSheet 1.10.1, PHP 7.1.32

**Comment by oleibman** [comment]
Stumbled upon this while researching a different problem. I have an explanation, so will remove the stale label, but will leave the issue closed. The control characters are legal in xml. `_x0020` wasn't replaced when the spreadsheet was written out because it isn't in the control character range (hex 00-1f). But `_x0012` was replaced because it is in the control character range. You can even see it as follows:
```php
var_dump(bin2hex($xlsx->getSheet(0)->getCell('A2')->getValue()));
Result:
string(20) "5f783030354612666f6f"
```
So it is being correctly read after all.
