### ISSUE TITLE
Merging cell formatting with conditional formatting is broken (xlsx)

### ISSUE THREAD

**Issue by 3SCadmin** [PHPOffice/PhpSpreadsheet#1338]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
In Excel you can apply formatting directly to a cell, or via a conditional rule.

When the conditional rule is triggered, Excel will "merge" the formatting instructions from these 2 sources.   IF both sources contain formatting instructions for the same attribute (ex: Fill) then the conditional rule wins.

### What is the current behavior?

When the conditional rule is triggered, all formatting assigned directly to the cell is over-written by the rule.  **ALL formatting instructions** from rule are applied to the cell, not just the few that the user specified in the rule:  Everything the user did not specify is assumed to be system default, and these system default instructions over-write all the formatting  directly assigned to the cell

### What are the steps to reproduce?

1. Create a test file in Excel, place a date in a cell, write a conditional rule that changes the background color of that cell.
2. load the file with phpspreadsheet
3. save the file under a new name with phpspreadsheet.
4. examine the cell in Excel

You'll notice the cell value is no longer formatted as a date, but is displayed as a generic number!

### Which versions of PhpSpreadsheet and PHP are affected?

PHPSpreadsheet 1.10.1
PHP 7.2.24

**Comment by 3SCadmin** [comment]
Stale?   bad bot!

This is still very much an issue until someone fixes it.
To re-iterate:   PHPspreadsheets 1.10.1 will break any xlsx file that contains conditional formatting!
You don't even need to touch the cells which contain conditional formatting.
Just opening and saving the file is enough to break formatting as described above.

PHPspreadsheets 1.10.1 will turn this:
![image](https://user-images.githubusercontent.com/45569168/78015928-ffce4c80-7341-11ea-9456-7d2bcc0830f0.png)

into this:
![image](https://user-images.githubusercontent.com/45569168/78015951-0957b480-7342-11ea-9536-48364fef567d.png)

.. if the blue background came from conditional formatting.

**Comment by oleibman** [comment]
[issue.1338.xlsx](https://github.com/user-attachments/files/16739243/issue.1338.xlsx)
Attached file meets criteria stated in issue, and PhpSpreadsheet load/save preserves everything about it. Removing stale label, but leaving issue closed.
