### ISSUE TITLE
Make the Writer classes capable of appending lines to a file

### ISSUE THREAD

**Issue by Brandyparty** [PHPOffice/PhpSpreadsheet#1339]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Writers should have a mode in which they append data. 

### What is the current behavior?
Writers can only produce complete files which hinders their usage when dealing with larger files. Reading can be splitted to only read certain lines and therefore streamlined. However writing can not.

**Comment by MarkBaker** [comment]
Aside from CSV (and html), speadsheet file are not linear in structure, and cannot simply be appended to
