### ISSUE TITLE
clear README!!!  its unstalbe but are stable!

### ISSUE THREAD

**Issue by mckaygerhard** [PHPOffice/PhpSpreadsheet#134]
i quoted a interesting:
>Because all efforts have shifted to PhpSpreadsheet, PHPExcel will no longer be maintained. All contributions for PHPExcel, patches and new features, should target PhpSpreadsheet develop branch.

later said:
>However PhpSpreadsheet is still unstable and not yet released. So if you need stability stick to PHPExcel until this project is released. If you prefer to live on the edge you can try to install this project manually via composer, but there is no guarantee and it will likely break again before an official release.

so then:
1) PHPExcel will no longer be maintained
2) but.. " PhpSpreadsheet is still unstable and not yet released"

oh men! of course! I UNDERSTAND! ITS CLARELLY CLEAR!????

and takin in consideration the "php until next release" tha forces the admin mantainers constant builds.. wthf!

**Comment by PowerKiKi** [comment]
PHPExcel 1.8.1 is the latest stable and released version. If in doubt, use that.

**Comment by mckaygerhard** [comment]
okthanks for clarifycation but "the works goin with the wind".. so the issues now i'll send agains the phpexcel okey! code contribution? pstches, fixeds!?

i'm not so smart but the information in README are not so clear! around reports bug and feature request over STABLE releases...  still there some bugs in "stable" release unresolved i noted!

**Comment by f1rf1n** [comment]
@mckaygerhard I have always understood 'stable' to mean there will be no major breaking (api) changes.

**Comment by mckaygerhard** [comment]
@f1rf1n stable also means able to use in production and bug free, no random problems and knowed working! use dictionary
