### ISSUE TITLE
Auto-size notes box

### ISSUE THREAD

**Issue by denitsa-cm** [PHPOffice/PhpSpreadsheet#1341]
This is:

```
- [ ] a bug report
- [x] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

The note box should expand to fit the text.

### What is the current behavior?

The note box has a fixed size: 

![image](https://user-images.githubusercontent.com/21036599/73439726-5faf7380-4350-11ea-9112-5ed1e9d87c1d.png)

### What are the steps to reproduce?

Add a longer note to a cell.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet ->->getActiveSheet()->getComment('A1')->getText()->createTextRun('Test a longer note here and see how the box will not expand')
```

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet 1.10.1, PHP 7.4

**Comment by denitsa-cm** [comment]
This is still an issue. I don't know how to increase the note box size to fit the text.

**Comment by tbyte80** [comment]
It's also an issue for me. At least height shoud fit the text automatically.

This might not be a trivial issue though. Even in Excel you have to run a script to fit comment boxes afterwards. So I am guessing width and height of the box are calculated based on the amount of text and it's properties and then updated.
