### ISSUE TITLE
PHP Warnings on reader

### ISSUE THREAD

**Issue by albertocattan** [PHPOffice/PhpSpreadsheet#1342]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

Hi, I thought you might like to know I'm getting these PHP Warnings on my error log while reading an Excel workbook:

PHP Warning: Invalid argument supplied for foreach() in /home/blah/blahblah/blahblahblah/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line **349**

PHP Warning: Invalid argument supplied for foreach() in /home/blah/blahblah/blahblahblah/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line **398**

PHP version is 7.3.14 and PHPSpreadsheet is up to date.
Thanks in advance.

### What is the expected behavior?
Read Excel Workbook

### What is the current behavior?
Seems to be working OK (but these warnings appear on my error log)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by albertocattan** [comment]
Forgot to mention PHP version is 7.3.14 and PHP version and PHPSpreadsheet is up to date.

**Comment by oleibman** [comment]
Removing stale label, leaving closed. More than 5 years since last update. Issue can't be resolved without supplying the file.
