### ISSUE TITLE
Not parsed date before 1900

### ISSUE THREAD

**Issue by skortabeast** [PHPOffice/PhpSpreadsheet#1346]
This is:
Not parsed date from db before 1900 use method  Date::stringToExcel($date)
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Parsed date to excel format

### What is the current behavior?
empty value

### What are the steps to reproduce?
return any collection with map use method Date::stringToExcel($item)

**Comment by MarkBaker** [comment]
MS Excel doesn't recognise dates before 1-1-1900 (or 1-1-1904 if using the Mac calendar), so you'd need to take this one up with Microsoft
