### ISSUE TITLE
Excel with protection, black cells after edit

### ISSUE THREAD

**Issue by bbinotto** [PHPOffice/PhpSpreadsheet#1353]
This is:

```
- [X ] a bug report
- [ ] a feature request
- [x ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Open TestCaseAnonym.xlsx and write into unprotected cell should not change style of other cells.

### What is the current behavior?
Open 
[TestCaseAnonym.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4170321/TestCaseAnonym.xlsx)
, write into unprotected cell, save to TestCaseOutput.xlsx. 
Lots of cells (probalbly all protecte?) are now unreadable because they have a black background color.

### What are the steps to reproduce?
composer install
php -f TestCase.php
View TestCaseOutput.xlsx.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php
include_once "vendor/autoload.php";

use PhpOffice\PhpSpreadsheet\IOFactory;
class TestCase
{
    /**
     * @throws \PhpOffice\PhpSpreadsheet\Reader\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     */
    public static function Exec(){
            $objReader = IOFactory::createReader("Xlsx");
            $excel = $objReader->load("TestCaseAnonym.xlsx");
            $excel->setActiveSheetIndex(1);
            $activeSheet = $excel->getActiveSheet();
            $activeSheet->SetCellValue("J21", utf8_encode("2"));
            $objWriter = IOFactory::createWriter($excel,"Xlsx");
            $objWriter->save("TestCaseOutput.xlsx");
    }
}

TestCase::Exec();
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.10.1
I have the same issue with the old PhpExcel.
php 7.2

**Comment by bbinotto** [comment]
Complete example
[MinimalExcel.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/4170345/MinimalExcel.zip)

**Comment by bbinotto** [comment]
I found that Xlsx.php@1624 causes this:
//$docStyle->getFill()->getStartColor()->setARGB('FF000000');

**Comment by plagiatmakc** [comment]
> I found that Xlsx.php@1624 causes this:
> //$docStyle->getFill()->getStartColor()->setARGB('FF000000');
> 
> Anyone has an idea what the side effects are if we just remove this?

Xlsx.php@1624
I think that this is better way:
$docStyle->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_NONE);
instead
> //$docStyle->getFill()->getStartColor()->setARGB('FF000000');
because this way the background becomes transparent, and in your case it’s just white. 

Sorry for my english....
