### ISSUE TITLE
Excel sheet like view in broswer.

### ISSUE THREAD

**Issue by pranayteja2773** [PHPOffice/PhpSpreadsheet#1355]
### What is the expected behavior?
Excel sheet like view in browser.

### What is the current behavior?
I am converting the Excel sheet to HTML before saving it so that I can see my code is working or not. But some functionalities I can't see it in HTML unless I saved it to xlsx file like filters. Every time I change the code, I have to download the file to see changes are coming or not. This is an exhausting task. So I looked for an excel viewer in the browser. It is not supporting. I found google, Microsoft office and Zoho are providing excel viewer but they come with a price and my data is confidential so I can't use them.  Is there any to view my excel sheet? It is a community so I am hoping to find an answer here. 

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by oleibman** [comment]
No suggestions in 6 years. I don't see anything that meets the request criteria. Opening the spreadsheet in LibreOffice seems like it might be a better option than converting it to html.

Leaving issue closed, removing stale label.
