### ISSUE TITLE
Chunk big xlsx file

### ISSUE THREAD

**Issue by D0nVitalio** [PHPOffice/PhpSpreadsheet#1359]
Hi. You have ChunkReadFilter() example on https://phpspreadsheet.readthedocs.io/en/latest/topics/reading-files/ . You can find example "class ChunkReadFilter implements \PhpOffice\PhpSpreadsheet\Reader\IReadFilter"

When looping I need to provide total rows 65536 like in that example. 
I have an xlsx file where can be 100ooo or 2 mln rows and I want to read that file by chunks in order to keep memory usage low. In order to get total rows you have "getHighestRow()". Problem is that when I use "getHighestRow()" it takes to memory whole xlsx file.

Is there a way to read big xlsx files and use less memory?

**Comment by damijanc** [comment]
You could read the metadata but according to my experience it is unreliable. What could help a bit is to use only data option.

**Comment by MarkBaker** [comment]
This is why we provide a `listWorksheetInfo()` method for the Readers, that allows you to get details of worksheet dimensions without having to load the entire file into memory first. See [ReadTheDocs](https://phpspreadsheet.readthedocs.io/en/latest/topics/reading-files/) for more information, and `samples/Reader/19_Reading_worksheet_information_without_loading_entire_file.php` for an example of its use

**Comment by D0nVitalio** [comment]
> This is why we provide a `listWorksheetInfo()` method for the Readers, that allows you to get details of worksheet dimensions without having to load the entire file into memory first. See [ReadTheDocs](https://phpspreadsheet.readthedocs.io/en/latest/topics/reading-files/) for more information, and `samples/Reader/19_Reading_worksheet_information_without_loading_entire_file.php` for an example of its use

Thanks, 
I was able read file with 75k rows, but 1 million rows (160mb file) and memory limit to 3072M I've got this:
ErrorException: XMLReader::read(): Memory allocation failed : growing input buffer in file C:\xampp\htdocs\backend\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php on line 216
