### ISSUE TITLE
Calculate autowidth for all columns at once

### ISSUE THREAD

**Issue by carlos-mg89** [PHPOffice/PhpSpreadsheet#1386]
I've tried the following method with undesired behaviour:

`$spreadsheet->getActiveSheet()->calculateColumnWidths()`

By the name, and the code of the method, I thought it'd calculate the width of the columns from my sheet automatically (without having to iterate through them). However that doesn't seem to be the case.

So I had to iterate through all the columns and apply the `setAutoSize()`:
```
foreach ($spreadsheet->getActiveSheet()->getColumnIterator() as $column) {
    $spreadsheet->getActiveSheet()->getColumnDimension($column->getColumnIndex())->setAutoSize(true);
}
```

Perhaps there's a bug in the `calculateColumnWidths()` or maybe I'm getting things wrong and that method is intended to do another thing.

Thanks for this library by the way. Very happy with it!

**Comment by MAKS-dev** [comment]
As the doc states: "Calculate widths for auto-size columns"
So it works as expected when the columns are auto-size. Since this is not the default, you'll have to iterate once to change that.

**Comment by carlos-mg89** [comment]
I understand that the normal behaviour and the one you intended is to iterate through all the columns and manually apply the auto-size over there.

However, this issue is more like a proposal/suggestion to create a new method that would do this automatically for ALL columns. Simplifying the interaction with the sheet.

As I said, it's just a proposal. If you don't find the value in it, you can close this issue :)

**Comment by oleibman** [comment]
Removing stale label, leaving issue closed. Explanation from MAKS-dev is correct. I don't think there's a strong use case for this, and code provided by carlos-mg89 does not seem overly burdensome for those who want it.
