### ISSUE TITLE
dataTypeForValue() casting string ("1.100") to float (1.1)

### ISSUE THREAD

**Issue by rentalhost** [PHPOffice/PhpSpreadsheet#1387]
**This is:** a bug report;

### Description

I am using `$worksheet->fromArray()` method, that calls the `DefaultValueBinder::dataTypeForValue()` with my datas. Some of have values like `"1.100"` (as string, a street number, for instance) or `"1,100"` (as string too), but it is replaced by a float `1,1` (the "dot" or "comma" will depends of system locale).

### What is the expected behavior?

Cell should stores a string `"1.100"`.

### What is the current behavior?

Cell is storing a float `1,1`. Which is an invalid street number information (that should be exactly `"1.100"`).

### What are the steps to reproduce?

```php
<?php

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet;

$sheet = $spreadsheet->getActiveSheet();
$sheet->fromArray([
    [ '1.100' ]
]);

$writer = new Xlsx($spreadsheet);
$writer->save('issue-1387.xlsx');
```

[issue-1387.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4236980/issue-1387.xlsx)

### Debugging

I have debugged the `DefaultValueBinder::bindValue()` method, and checked the output from `$value` parameter and `static::dataTypeForValue($value)` return. It is what I received:

![image](https://user-images.githubusercontent.com/421851/75049741-722d5080-54a9-11ea-84ea-de04b1ccb768.png)

It is: `dataTypeForValue()` will return `"n"` (_number_) for `"1.100"` instead of `"s"` (_string_).

How the [`preg_match()` line](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Cell/DefaultValueBinder.php#L64) will handle this value (`"1.100"`), so I think that it should be improved to keep `"1.100"` as string, or create an alternative method to force string when using `$worksheet->fromArray()`.

For instance, we have the [`TextElement` class](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/RichText/TextElement.php), but it actually is not supported at this context.

Anyway, I think that `"1.100"` should not be treated as number, except if it `is_int()` or `is_float()`. Or if it have any `"0"` on right-side.

### Workaround

The current possible workaround is very ugly and will modify the cell data: `"1.100 "` (note the space after the number).

Other option is forcing via `$worksheet->setCellValueExplicit()`, but it is not viable when using `$worksheet->fromArray()`.

### Which versions of PhpSpreadsheet and PHP are affected?

- PhpSpreadsheet 1.10.1
- PHP 7.3.14

**Comment by rentalhost** [comment]
I'm working on a PR, but I'm in the middle of a dilemma:

For `"1.0"`, when it is `fromArray()`'ed, it should be keeped as string, else it will be displayed just as  `1` on Excel (once that zeroed decimal part will be hidden). So in my initial solution, the `dataTypeForValue()` should returns `"s"` for this value, which works fine. But when the file is readed again, real numeric values like `1.0` will be returned as string.

I still working on a definitive solution, but I accept suggestions of how I should proceed.

Check updates here: https://github.com/PHPOffice/PhpSpreadsheet/compare/master...rentalhost:issue-1387

**Comment by 4n70w4** [comment]
The same problem!


```
composer info | grep phpspreadsheet
```

```
phpoffice/phpspreadsheet                         1.18.0
```


```php
        $spreadsheet = new Spreadsheet;

        $sheet = $spreadsheet->getActiveSheet();
        $sheet->fromArray([
                              [ '1.100' ]
                          ]);

        $writer = new Csv($spreadsheet);
        $writer->save('issue-1387.csv');
        var_dump(file_get_contents('issue-1387.csv'));
        die();
```

Output:
```csv
string(6) ""1.1"
```

**Comment by MarkBaker** [comment]
If this is a problem, then you should use the `StringValueBinder`, or create your own custom binder. That's why we provide the binder mechanism

**Comment by 4n70w4** [comment]
just need to somehow guess that this mechanism exists.

**Comment by MarkBaker** [comment]
Perhaps [Reading the docs](https://phpspreadsheet.readthedocs.io/en/latest/topics/accessing-cells/#excel-datatypes) would help, together with the section on [Value Binders](https://phpspreadsheet.readthedocs.io/en/latest/topics/accessing-cells/#using-value-binders-to-facilitate-data-entry)
