### ISSUE TITLE
Notice of undefined index when opening file

### ISSUE THREAD

**Issue by tristanleboss** [PHPOffice/PhpSpreadsheet#1392]
This is:

```
- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

No notice. Even if chart sheet are not supported, there should be no notice. Index should be checked using `array_key_exists` or `isset` before access.

### What is the current behavior?

I get a notice: 

> Notice: Undefined index: rId14 in C:\Users\\Downloads\simujp\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php on line 624
> 
> Call Stack:
>     0.0013     529064   1. {main}() C:\Users\\Downloads\simujp\test.php:0
>     0.0345    1606576   2. PhpOffice\PhpSpreadsheet\Reader\Xlsx->load() C:\Users\\Downloads\simujp\test.php:12

### What are the steps to reproduce?

I cant' provide the file but searching in it for `rId14` using WinRAR gives 2 results:

![image](https://user-images.githubusercontent.com/1431508/75101858-c6d4e680-55e3-11ea-9171-0d1d597573b7.png)

xl/workbook.xml:
`<sheet name="7 Evolution fiscale " sheetId="35" r:id="rId14"/>`

xl/_rels/workbook.xml.rels
`<Relationship Id="rId14" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/chartsheet" Target="chartsheets/sheet1.xml"/>`

File `xl\chartsheets\sheet1.xml` does exists in the XLSX file.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load("BadFile.xlsx");

```

### Which versions of PhpSpreadsheet and PHP are affected?

Last version installed by Composer.

**Comment by perkthefox** [comment]
Same here

**Comment by tristanleboss** [comment]
Activity ;)

**Comment by tristanleboss** [comment]
Activity ;)

**Comment by tristanleboss** [comment]
This error is due to the fact chart sheet are not supported cf. #1564

**Comment by tristanleboss** [comment]
You're an annoying bot ;)

**Comment by jarrettj** [comment]
Hi,

Good day.

This happens if the image source is a link as well.

Regards.
JJ

**Comment by oleibman** [comment]
Chartsheets are supported since PR #2830 which was merged 2 years ago.
