### ISSUE TITLE
LookupRef function VLOOKUP is not datatype specific

### ISSUE THREAD

**Issue by ljcag** [PHPOffice/PhpSpreadsheet#1402]
This is:

```
- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I expect, that PhpSpreadsheets calculation engine calculates VLOOKUP to the same value as Excels calculation engine does.

### What is the current behavior?
When a VLOOKUP function is set to return an exact match using range_lookup = false, excel returns a match based on the lookup_value parameters value AND number format. PhpSpreadsheet seems to ignore the number format. This is a problem, if the lookup_array contains indexes with different formats.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();
$worksheet = $spreadsheet->getActiveSheet();

// First row
$worksheet->setCellValueExplicit("A1", 1, "s");
$worksheet->setCellValue("B1", "Text Nr 1");

// Second row
$worksheet->setCellValue("A2", 2);
$worksheet->setCellValue("B2", "Unwanted numeric result");

// Third row
$worksheet->setCellValueExplicit("A3", 2, "s");
$worksheet->setCellValue("B3", "Text Nr 2");

// Calculation row
$worksheet->setCellValueExplicit("A4", 2, "s");
$worksheet->setCellValue("B4", '=VLOOKUP(A4,$A$1:$B$3,2,0)');

// Will return "Unwanted numeric result"
echo $worksheet->getCell("B4")->getCalculatedValue();

$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save(__DIR__."/VLookupTest.xlsx");
?>
```

If you now open the created Excel-file, you will see that the value of Cell B4 is actually "Text Nr 2"

### Which versions of PhpSpreadsheet and PHP are affected?
Tested on PHP v. 7.4.1 and 7.0.33 with PhpSpreadsheet v. 1.10.1 and 1.8.2

**Comment by ljcag** [comment]
Upon further investigation I found out that LookupRef::VLOOKUP not datatype-specific is. This can easily be confirmed with the following example:
```php
<php
require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Calculation\LookupRef;

$array_mixed = array(
    1 => ["A" => 1, "B" => "Wrong"],
    2 => ["A" => "1", "B" => "Correct"],
    3 => ["A" => 2, "B" => "Wrong"]
);
// Will output Wrong
echo LookupRef::VLOOKUP("1", $array_mixed, 2, false)."<br/>";
?>
```

**Comment by oleibman** [comment]
Reopening, don't expect to get to this for a while.
