### ISSUE TITLE
GetCalculatedValue  with if statements returns incorrect result unless disableBranchPruning

### ISSUE THREAD

**Issue by snedabyte** [PHPOffice/PhpSpreadsheet#1405]
```
- [ x] a bug report
- [ ] a feature request
- [ x] **not** a usage question (ask them on 
```
### What is the expected behavior?
Branch pruning is not working as expected and returns incorrect results in some cases.
**Work around:**
 Calculation::getInstance($spreadsheet)->disableBranchPruning();

**Test Function**: 
 =IF(WEEKDAY(43886+2)=1,43886+2-13,IF(WEEKDAY(43886+2)=2,43886+2-7,IF(WEEKDAY(43886+2)=3,43886+2-8,IF(WEEKDAY(43886+2)=4,43886+2-9,IF(WEEKDAY(43886+2)=5,43886+2-10,IF(WEEKDAY(43886+2)=6,43886+2-11,IF(WEEKDAY(43886+2)=7,43886+2-12,)))))))+6

 Expect The test function above to evaluate to a floating point number with a value of 43884.
.... **Working Calculation stack track truncated to final lines**
[140] => Data!D1 -> Data!H1 => Evaluating Function IF() with 3 arguments
    [141] => Data!D1 -> Data!H1 => Evaluating IF( FALSE, 43875, 43878 )
    [142] => Data!D1 -> Data!H1 => Evaluation Result for IF() function call is a floating point number with a value of 43878
    [143] => Data!D1 -> Data!H1 => Evaluating 43878 + 6
    [144] => Data!D1 -> Data!H1 => Evaluation Result is a floating point number with a value of 43884
    [145] => Data!D1 => Evaluation Result for cell Data!H1 is a floating point number with a value of 43884

### What is the current behavior?
If you do not disable branch pruning the results can be incorrect as shown below.
**Current results of cell.getCalculatedValue results with Test Function**: Evaluation Result is an integer number with a value of 6.
  The calculation stack trace does not match versions without branchPruning feature, see below
... **Non working Calculation stack trace truncated to final lines**
Data!D1 -> Data!H1 => Evaluating Function IF() with 3 arguments
Data!D1 -> Data!H1 => Evaluating IF( "Pruned branch (only if storeKey-1) 0", FALSE, FALSE )
Data!D1 -> Data!H1 => Evaluation Result for IF() function call is a boolean with a value of FALSE
Data!D1 -> Data!H1 => Evaluating Function IF() with 3 arguments
Data!D1 -> Data!H1 => Evaluating IF( "Pruned branch (only if storeKey-0) 0", FALSE, FALSE )
Data!D1 -> Data!H1 => Evaluation Result for IF() function call is a boolean with a value of FALSE
Data!D1 -> Data!H1 => Evaluating FALSE + 6
Data!D1 -> Data!H1 => Evaluation Result is an integer number with a value of 6

### What are the steps to reproduce?
```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$cell = $spreadsheet->getActiveSheet()->getCell('A1');

 // Original formula has Today() replaced with 43886 to make repeatable
 $cell->setValue('=IF(WEEKDAY(43886+2)=1,43886+2-13,IF(WEEKDAY(43886+2)=2,43886+2-7,IF(WEEKDAY(43886+2)=3,43886+2-8,IF(WEEKDAY(43886+2)=4,43886+2-9,IF(WEEKDAY(43886+2)=5,43886+2-10,IF(WEEKDAY(43886+2)=6,43886+2-11,IF(WEEKDAY(43886+2)=7,43886+2-12,)))))))+6');
// work around /correct results uncomment next line.
//Calculation::getInstance($spreadsheet)->disableBranchPruning();

self::assertEquals('43884', $cell->getCalculatedValue());
    }
```
### Which versions of PhpSpreadsheet and PHP are affected?
1.10.11
All PHP versions

**Comment by oleibman** [comment]
We have several examples of this problem. However, this code now returns the correct answer. From my viewpoint, this is unfortunate because this example uses a much simpler formula than the others, offering a better chance to diagnose the problem if it still existed. Sigh. Removing stale label, leaving issue closed.
