### ISSUE TITLE
Custom properties are missing in xls but do exist in xlsx

### ISSUE THREAD

**Issue by codexp** [PHPOffice/PhpSpreadsheet#1410]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

After setting custom properties, I find them in file's custom properties.

### What is the current behavior?

This works for `xlsx` format, but doesn't for `xls`.

### What are the steps to reproduce?

- set custom properties
- save as xls
- open file in office
- open custom properties dialog

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet->getProperties()
    ->setCustomProperty('Exported', time(), \PhpOffice\PhpSpreadsheet\Document\Properties::PROPERTY_TYPE_DATE)
    ->setCustomProperty('Version', '1.0')
;

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xls($spreadsheet);
$writer->save('spreadsheet.xls');
```

### Which versions of PhpSpreadsheet and PHP are affected?

1.8.2

**Comment by IvanRibkov** [comment]
This bug is still present in PHP **7.4.33** + PhpSpreadsheet **1.28**. Custom properties work fine for **xlsx** and **ods** formats but don't work for **xls** format. Tested on LibreOffice **6.4.7.2** and Microsoft Office 2003.
