### ISSUE TITLE
Export to csv from excel including hyperlink

### ISSUE THREAD

**Issue by CmdrMahesh** [PHPOffice/PhpSpreadsheet#1412]
Hi PHPOffice,

I am looking for a way to export my XLSX file to CSV where some columns have a hyperlink and I could not figure out how to export the file with a hyperlink instead of the text on which hyperlink is applied.

here is my code to export to CSV:

```
require constant('EO_ECIE_DIR').'vendor/autoload.php';				
 $xl_reader = new Xlsx();
 $sheets = $xl_reader->load(self::$_file);

 $sheet_names = $sheets->getSheetNames();

 $csv_writer = new Csv($sheets);
 if(is_array($sheet_names) and !empty($sheet_names[0])){

	$csv_writer->setSheetIndex(0);					
       $csv_writer->save(self::$_file.'.csv');
       self::$_file = self::$_file.'.csv';
}

```
Help is appreciated as I have already googled a lot before writing a query here.

Thanks in advance.

**Comment by MarkBaker** [comment]
This isn't something that PHPSpreadsheet does; what wold you expect to see in the CSV file for a cell containing a hyperlink?

**Comment by CmdrMahesh** [comment]
I would like to extract those hyperlinks if they have any instead of the text label.
