### ISSUE TITLE
How to parse collapsed excel pivot table?

### ISSUE THREAD

**Issue by 1210mk2** [PHPOffice/PhpSpreadsheet#1413]
I tried to read pivot table with collapsed block (+/- buttons inside cell close to cell value) and got no result.

Is there any way to expand pivot table groups and get data?
Thank you.

**Comment by 1210mk2** [comment]
still actual.

**Comment by oleibman** [comment]
Just implemented with PR #4942. Leaving issue closed, removing stale label.
