### ISSUE TITLE
Native Excel dates that happen to be a round number getting mistyped

### ISSUE THREAD

**Issue by orcinus** [PHPOffice/PhpSpreadsheet#1416]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
All native Excel dates parsed from an Excel spreadsheet should be cast into a float.

### What is the current behavior?
Native Excel dates that just so happen to be a round number end up cast into an integer, while those that are not round are correctly cast as float.

### What are the steps to reproduce?
1) create a new spreadsheet
2) write "08/03/2020 00:00:00" into first cell
3) write "07/03/2020 07:00:00" into second cell
4) parse the spreadsheet
5) apply getCalculatedValue() on first and second cell
5) first cell's value gets typed as an integer
6) second cell's value gets typed as a float

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

Not possible, the problem occurs when reading/parsing a file.

### Which versions of PhpSpreadsheet and PHP are affected?
It started *after* 1.8.2. Sadly, i cannot be more precise than that. I was working on a stale branch with 1.8.2 when i got a ticket about an issue that ended up being caused by this bug in production. After hunting around for an hour trying to figure out what's going on, as i couldn't repro the case on my (stale) branch, i realized it might not be our code, updated my PhpSpreadsheet to 1.11.0 and the problem showed up.

We're running PHP 7.1.33

**Comment by orcinus** [comment]
Bump.

**Comment by orcinus** [comment]
Bump again.

**Comment by orcinus** [comment]
So, how's the weather up there?

**Comment by pittyplatsch** [comment]
Hi there! On my personal #hacktoberfest quest I came across this issue. Unfortunately couln't reproduce. Can you maybe provide the file you're trying to read?

**Comment by alexgunkel** [comment]
I could reproduce the behavior. Depending on your file you get a numeric value that either contains an integer or a floating point number. Therefor, it's interpreted as an integer if the string representation contains a dot, as float otherwise. This is expected behavior as far as I can see.

I recommend casting it after calling getCalculatedValue when you know that you got a date and time and you need a float.

**Comment by orcinus** [comment]
Exactly this. If it's a datetime field, it should always be (re)cast into a float, regardless of whether the representation ended up being an integer (by accident) or a float.

**Comment by orcinus** [comment]
🎄🎄🎄Merry Christmas, stale-bot!🎄🎄🎄

Ugh. Since there are no takers, i guess i'll try and whip up a PR myself one of these days.

**Comment by orcinus** [comment]
HUZZAH!
REJOICE!

Thank you :)

**Comment by oleibman** [comment]
You're welcome. Please note that you need to add an extra function call to activate the new behavior; it would otherwise have been a breaking change.

**Comment by orcinus** [comment]
Noted.
I hacked a fix in into our local fork in a similar way for similar reasons, actually.
