### ISSUE TITLE
Reader\Xslx.php $relsVML->Relationship can be NULL

### ISSUE THREAD

**Issue by Collie-IT** [PHPOffice/PhpSpreadsheet#1419]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Now Warning/Errow will be thrown.

### What is the current behavior?

> Warning: Invalid argument supplied for foreach() in ../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 1012 

would be thrown.

### What are the steps to reproduce?
If you not add a image to header.

### Which versions of PhpSpreadsheet and PHP are affected?
10.0.1

**Comment by oleibman** [comment]
Fixed by PR #1420.
