### ISSUE TITLE
The picture is not copied to a new sheet

### ISSUE THREAD

**Issue by pobornic** [PHPOffice/PhpSpreadsheet#1421]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [x ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
new sheet contains images

### What is the current behavior?
new sheet does not contain a images

### What are the steps to reproduce?

![xls](https://user-images.githubusercontent.com/39998941/77206552-47660480-6b08-11ea-9b67-e618b3e896dc.png)
[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4361824/test.xlsx)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
$outfile ='new_doc.xlsx';
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('test.xlsx');
$spreadsheet->setActiveSheetIndex(1);

$drawing = new \PhpOffice\PhpSpreadsheet\Worksheet\Drawing();
$drawing->setName('img');
$drawing->setDescription('img');
$drawing->setPath('xls.png');
$drawing->setCoordinates('B8');
$drawing->setWorksheet($spreadsheet->getActiveSheet());

$newSheet = $spreadsheet->getActiveSheet()->copy();
$newSheet->setTitle("new_sheet");
$spreadsheet->addSheet($newSheet, 2);
$spreadsheet->setActiveSheetIndex(2);

$writer = new Xlsx($spreadsheet);
$writer->save($outfile);
```

### Which versions of PhpSpreadsheet and PHP are affected?
php 7.3.1,  PhpSpreadsheet 1.11.0

**Comment by lihuizhang1** [comment]
I have this question too.Copy the entire sheet, including the pictures and formulas.
After copying the sheet page, the picture is not copied. If the file is opened, an error will be reported and the picture is lost.
