### ISSUE TITLE
=($A1=0;"true";"false")  if $A1 ='' result "false"

### ISSUE THREAD

**Issue by EugeneGeek** [PHPOffice/PhpSpreadsheet#1429]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
=($A1=0;"true";"false")  if $A1 ='' result "false"

### What is the expected behavior?
result "true"

### What is the current behavior?
result "false"

### What are the steps to reproduce?
$spreadsheet->getActiveSheet()->getCell('B1')->getCalculatedValue();

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by MarkBaker** [comment]
Assuming that the formula should be an IF test: `=IF($A1=0;"true";"false")`

**Comment by oleibman** [comment]
My testing indicates that if A1 is empty, formula returns true in Excel, LibreOffice, and PhpSpreadsheet. However, when it is null string, it returns false in all 3. So I will remove the stale label, but leave the issue closed.
