### ISSUE TITLE
Can I add digital signature to xls file?

### ISSUE THREAD

**Issue by sitte** [PHPOffice/PhpSpreadsheet#143]
I need to add digital signature to xls document to verify authenticity of document. Is it possible with Your library? If not, can anyone point me a direction how to do this?

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
