### ISSUE TITLE
cells not merged on copy row

### ISSUE THREAD

**Issue by cashalotkzn** [PHPOffice/PhpSpreadsheet#1438]
i have template, which generating rows from db data. This is template.
![image](https://user-images.githubusercontent.com/4135982/78620242-1d426f80-7888-11ea-8778-5ef5d7c3ce8b.png)

This is code
![image](https://user-images.githubusercontent.com/4135982/78619922-4e6e7000-7887-11ea-93da-dc8be2bf9103.png)

thats be correct
![image](https://user-images.githubusercontent.com/4135982/78620325-4f53d180-7888-11ea-9af7-c8b3c81fa782.png)

but merged cell not merging. all styles has been copied succesful, data too, but cells has not merged.
![image](https://user-images.githubusercontent.com/4135982/78620070-a9a06280-7887-11ea-90a6-b014ba38613c.png)

and that's interesting - i don't have new inserting rows and their cells in $worksheet->getMergeCells();
![image](https://user-images.githubusercontent.com/4135982/78620145-df454b80-7887-11ea-82df-ab92ffb328fc.png)

what i doing wrong?

**Comment by cashalotkzn** [comment]
@MarkBaker help me, pls

**Comment by amiretemad** [comment]
> @MarkBaker help me, pls

Hi,

I haven't used PHPSpreadsheet for a while but as I know you should merge cells programmatically

inside the loop , merge cells that you want to be merged something like below code ( I'm not sure about code as I said I haven't used it for a while )
 
$spreadsheet->getActiveSheet()->mergeCells("$range1:$range2");

**Comment by ivanaugustobd** [comment]
Any news?

**Comment by oleibman** [comment]
Removing stale label, leaving closed. Solution from amiretemad is correct.
