### ISSUE TITLE
DefaultValueBinder::bindValue - different rules for number format check

### ISSUE THREAD

**Issue by kuty** [PHPOffice/PhpSpreadsheet#1439]
This is:

```
- [ xx ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

static::dataTypeForValue($value) should identify value type and type is used as a param of $cell->setValueExplicit($value, static::dataTypeForValue($value));

### What is the current behavior?

static::dataTypeForValue($value) has own rules how to identify numeric value and check according regular expression etc. this will cause e.g. that numeric string with enter at the end: 

"0.0
"

will be identified as a numeric value.

But Cell::setValueExplicit($pValue, $pDataType) is not using the same format checks and  dataTypeForValue() and it will cause that 

case DataType::TYPE_NUMERIC:
                **if (is_string($pValue) && !is_numeric($pValue)) {**
                    throw new Exception('Invalid numeric value for datatype Numeric');
                }
                $this->value = 0 + $pValue;

                break;

will cause an exception.

**Comment by yamyoume** [comment]
I'm getting the same error when I'm trying to export a large table it gets to about 7200 rows then throws this error, with a limit or a small table it works! so what's up?

**Comment by sferragne** [comment]
Any news on this?

**Comment by juniorb2ss** [comment]
I'm facing the same issue.

**Comment by MchMichael** [comment]
In PhpOffice\PhpSpreadsheet\Cell\DefaultValueBinder uses
 `preg_match('/^[\+\-]?(\d+\\.?\d*|\d*\\.?\d+)([Ee][\-\+]?[0-2]?\d{1,3})?$/', $pValue)`

in PhpOffice\PhpSpreadsheet\Cell\Cell uses 
` if (is_string($pValue) && !is_numeric($pValue)) {
                    throw new Exception('Invalid numeric value for datatype Numeric');
                }`
This is the reason of problem. I faced this issue too.

**Comment by nomagick** [comment]
+1 on this.
