### ISSUE TITLE
isDateTime doesn't respect formula's

### ISSUE THREAD

**Issue by jverelst** [PHPOffice/PhpSpreadsheet#1441]
https://github.com/PHPOffice/PhpSpreadsheet/blob/87f71e1930b497b36e3b9b1522117dfa87096d2b/src/PhpSpreadsheet/Shared/Date.php#L328

When you have an excel file with a date-field which is also a formula, this method will return 'false', because it only checks 'getValue()' and not 'getCalculatedValue()'. I am not sure on how that could be fixed, I wrote a small helper function myself using this code as a baseline, but I think that PhpSpreadsheet should support this.

**Comment by PowerKiKi** [comment]
Fixed in #1480
