### ISSUE TITLE
Is it possible to open xlsx-file that protected with password?

### ISSUE THREAD

**Issue by vosaan** [PHPOffice/PhpSpreadsheet#1443]
My code:
```
...
        $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
        try {
            $spreadsheet = $reader->load($request->file('report_file'));
            dd($spreadsheet);
        } catch (\Exception $exception) {
            dd($exception->getMessage());
        }
...
```

My result:
`"ZipArchive::getFromName(): Invalid or uninitialized Zip object"`

What I have to do to open protected file?

**Comment by avambro** [comment]
@vosaan  Have you found any solution ?  
I've same issue

**Comment by vosaan** [comment]
> @vosaan Have you found any solution ?
> I've same issue

My question on StackOverflow: https://stackoverflow.com/questions/61210720/phpspreadsheet-is-it-possible-to-open-and-read-xlsx-file-that-protected-with-pa

If shortly: no.

**Comment by jonathanpmartins** [comment]
same problem here, no solution!
