### ISSUE TITLE
Add composer.lock to .gitignore

### ISSUE THREAD

**Issue by pwsdotru** [PHPOffice/PhpSpreadsheet#145]
Fork develop branch and clone it. After composer update file composer.lock showed in list of modified files.

I think is best way add this file to .gitignore and remove it repository

**Comment by pwsdotru** [comment]
I can make PR for this

**Comment by PatrickRose** [comment]
You shouldn't run composer update unless you're updating the dependencies. You should run composer install

**Comment by PowerKiKi** [comment]
Indeed you should not `composer update`. This will not be merged for the reasons explained in https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/
