### ISSUE TITLE
Get style as array

### ISSUE THREAD

**Issue by Erwane** [PHPOffice/PhpSpreadsheet#1451]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
Same as #580, with an use case.
Get Style as array, for unit testing.

Tests can be very simple with a `PhpOffice\PhpSpreadsheet\Style::toArray()` method

Maybe a method `getAsArray(string $styleType)` where styleType can be `borders` `fill` ...

Thanks

**Comment by PowerKiKi** [comment]
Duplicates #580
