### ISSUE TITLE
Format Data Series (ScatterChart)

### ISSUE THREAD

**Issue by cwolcott** [PHPOffice/PhpSpreadsheet#1452]
This is:

```
- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
To be able to provide attributes to format data series.  Specifically in a ScatterChart for now.

### What is the current behavior?
Currently can not provide line attributes to format a data series.
Only the marker style and fill.

### Which versions of PhpSpreadsheet and PHP are affected?
1.11.0

The chart below is a ScatterChart made up of 5 Data Series.  

- The 1st data series has 320 values from 1 to 320 and is represented by the blue, nofill, circles.

- The 2nd and 3rd data series has 2 values at 1 & 320.  It is represented by the green transparent dashed line with head/tail triangles and no markers.  It is showing the HIT boundaries above and below the lines.

- The 4th and 5th data series has 2 values at 1 & 320.  It is represented by the red transparent dashed line with head/tail triangles with no markers.  It is showing the EXCLUSION THRESHOLD boundaries above and below the lines.

![image](https://user-images.githubusercontent.com/3777526/80242757-e021ff80-8633-11ea-9d96-69f27031ed75.png)

After reviewing the Xlsx/Chart.php code, and reviewing what is stored in the xl/charts/chart1.xml archive file in the excel spreadsheet I have determine what the format is to correctly configure the chart.

I currently have this working now in the code (backward compatible), but am now trying to determine the most appropriate way to introduce this into the code baseline.

**Comment by oleibman** [comment]
Fixed by PR #2828.
