### ISSUE TITLE
Ignore empty rows when counting

### ISSUE THREAD

**Issue by DuaelFr** [PHPOffice/PhpSpreadsheet#1454]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

When we use `\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet::getHighestDataRow()` we expect to get the number of lines with content.

### What is the current behavior?

In some XSLX documents, the number returned by `getHighestDataRow` is way bigger than the actual number of lines.

### What are the steps to reproduce?

Use this file as an example (cannot reproduce by generating a spreadsheet from code):
[site_builder.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4552613/site_builder.xlsx)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Use the link above to get the file.
$file_path = '/path/to/site_builder.xlsx';

$type = \PhpOffice\PhpSpreadsheet\IOFactory::identify($file_path);
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($type);
$reader->setReadDataOnly(TRUE);
$reader->setLoadSheetsOnly('Fields');
$workbook = $reader->load($file_path);
$worksheet = $workbook->getSheet(0);

// Expected result: 2
// Current result: 1002
echo $worksheet->getHighestDataRow();
```

### Which versions of PhpSpreadsheet and PHP are affected?

Found on PhpSpreadsheet 1.12.0 and PHP 7.3.15

**Comment by Vagir-dev** [comment]
Hi!

This is **not** a PhpSpreadsheet's bug.

In the 2nd sheet of your file in columns E and F the style is defined for cells in rows 4 to 1003:

_xl\worksheets\sheet2.xml_
![image](https://user-images.githubusercontent.com/64550355/82155711-8eaa1080-987f-11ea-8d71-788a86678dfc.png)

_xl\styles.xml_
![image](https://user-images.githubusercontent.com/64550355/82155789-0bd58580-9880-11ea-9d8f-0c8798dd8fc0.png)

So such rows are treated as not empty.

Close #1454

**Comment by khayyak** [comment]
I have similar issue , and I have two solutions :
First : when you delete old rows from XLSX file you should not delete normally with delete button , you should delete it using delete option in the top right of excel file .
Second one : you can check if a required cell is null or whole row is null like that :

for($row = 2 ; $row <= $lastRow ; $row++)
{
if($page->getCell('A'.$row)->getValue() == NULL && $page->getCell('B'.$row)->getValue() == NULL)
{
break;
//or continue or anything you want;
}
else
{
// your logic
}
}

hope that helps you or help someone need it.

**Comment by oleibman** [comment]
`$reader->setReadEmptyCells(false);`
