### ISSUE TITLE
Borders are not complete on rowspanned columns using HTML reader

### ISSUE THREAD

**Issue by andrasf** [PHPOffice/PhpSpreadsheet#1455]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
<img width="69" alt="Képernyőfotó 2020-04-30 - 16 06 11" src="https://user-images.githubusercontent.com/288001/80720043-a3a34780-8afc-11ea-93c9-7afb88b918bf.png">

### What is the current behavior?
<img width="54" alt="Képernyőfotó 2020-04-30 - 16 06 15" src="https://user-images.githubusercontent.com/288001/80720061-aaca5580-8afc-11ea-93c8-1830cd8f38d5.png">

### What are the steps to reproduce?
<td style="border: 5px solid black;" rowspan="2"></td>

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Html();
$spreadsheet = $reader->loadFromString('<table><tr><td style="border: 1px solid black;">NOT SPANNED</td><td rowspan="2" style="border: 1px solid black;">SPANNED</td></tr><tr><td style="border: 1px solid black;">NOT SPANNED</td></tr></table>');
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xls');
$writer->save(__DIR__ . '/test.xls');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.11.0
PHP 7.3.13

**Comment by dhaval247** [comment]
I have created a pull request for resolving this border related issue.
