### ISSUE TITLE
Problem with uft-8

### ISSUE THREAD

**Issue by crisscott** [PHPOffice/PhpSpreadsheet#1459]
This is:

```
- [ X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When reading an excel file take the special characters

### What is the current behavior?
The result is empty

### What are the steps to reproduce?
1. Load File 
2. Sheet to array

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$file = $_FILES['file']['tmp_name'];
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($file);
$data = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);

print_r($data);

//Expect "INT DE BAÑOS"
//Result  ""

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.4.1
PhpSpreadSheet 1.12

**Comment by oleibman** [comment]
If this was a problem in 2020, it shouldn't be now. No sample file provided with this issue, so can't take it any further. Removing stale label, but leaving issue closed.
