### ISSUE TITLE
Memory limit ignored when ran by a cron

### ISSUE THREAD

**Issue by vicentor** [PHPOffice/PhpSpreadsheet#1463]
This is: a potential bug report

### What is the expected behavior?
For the file to be loaded in memory when calling $reader->load( $file_path ); considering the 4096M memory limit when using a cron job.

### What is the current behavior?
It crashes with the following error:

```
mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 217055232) (tried to allocate 4096 bytes) in /home/monkeystats/public_html/api/v1/includes/php/phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php on line 34

Fatal error: Out of memory (allocated 217055232) (tried to allocate 4096 bytes) in /home/monkeystats/public_html/api/v1/includes/php/phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php on line 34
```

### What are the steps to reproduce?
Load a large file that would exceed 1GB of memory (it'll work when manually ran) wtih 2GB+ on memory_limit. Run the same script using a cron job.

```
$memory_limit = ini_get('memory_limit'); // $memory_limit = 4096M here
$spreadsheet = $reader->load( $file_path ); // Overrides the memory limit to 218.628096MB and crashes with the provided error, nobody knows why
```

We are hosted at SG and they forced the memory limit globally and it still seems to be ignored. The script works perfectly when not run as a cron. It could still be a host-related issue (maybe...).

If nobody encountered this or has any idea, we'll go deeper and make a simple version of our script to see more information.

### Which versions of PhpSpreadsheet and PHP are affected?
1.11.0

Thank you for any insight!

**Comment by oleibman** [comment]
Removing stale label, leaving closed. This seems like an issue with the host, not with PhpSpreadsheet.
