### ISSUE TITLE
Rich text is not working with line breaks

### ISSUE THREAD

**Issue by skortabeast** [PHPOffice/PhpSpreadsheet#1467]
This is:

```
- [X] a bug report
```

### What is the expected behavior?
Text with style

### What is the current behavior?
When create rich text in merged columns and rows with line breaks use "\n" or PHP_EOL , style is not working
![image](https://user-images.githubusercontent.com/10978770/81546713-73bd3500-9383-11ea-88a5-038c9cf08ec0.png)

### What are the steps to reproduce?
Merge few columns and rows.
Create simple rich text

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$managementText = new RichText();
$payable = $managementText->createTextRun('test text');
$payable->getFont()->setBold(true);
$payable->getFont()->setItalic(true);
$payable->getFont()->setColor(new Color(Color::COLOR_YELLOW));

$monitoringText = new RichText();
$payable = $monitoringText->createTextRun('test text2');
$payable->getFont()->setBold(true);
$payable->getFont()->setItalic(true);
$payable->getFont()->setColor(new Color(Color::COLOR_BLACK));

$spreadsheet->getActiveSheet()->getCell('A1')->setValue($managementText  . "\n" . $monitoringText);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet - 1.10
PHP - 7.3

**Comment by Vagir-dev** [comment]
Hi!
Just do like this:

```
<?php
        $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

        $payable1 = new Run('test text' . chr(10));
        $payable1->getFont()->setBold(true)
            ->setItalic(true)
            ->setColor(new Color(Color::COLOR_YELLOW));

        $payable2 = new Run('test text2');
        $payable2->getFont()->setBold(true)
            ->setItalic(true)
            ->setColor(new Color(Color::COLOR_BLACK));

        $richText = new RichText();
        $richText->addText($payable1);
        $richText->addText($payable2);

        $spreadsheet->getActiveSheet()->getCell('A1')->setValue($richText);
        $spreadsheet->getActiveSheet()->getStyle('A1')->getAlignment()->setWrapText(true);
?>
```

Привет Минску! ;)

**Comment by smit-devdigital** [comment]
@Vagir-dev 

I am using your code added in the last comment but the setBold is not working. 

Below is my code:
`$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$run1 = new \PhpOffice\PhpSpreadsheet\RichText\Run('test text' . chr(10));
$run1->getFont()->setBold(true)
->setItalic(true)
->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK));

$run2 = new \PhpOffice\PhpSpreadsheet\RichText\Run('test text2');
$run2->getFont()->setBold(true)
	->setItalic(true)
	->setUnderline(true)
	->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK));

$richText = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
$richText->addText($run1);
$richText->addText($run2);

$sheet->getCell('A1')->setValue($richText);
$sheet->getStyle('A1')->getAlignment()->setWrapText(true);

$objWriter = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter("test.xlsx", 'Xlsx');`

PhpSpreadsheet - 1.12
PHP - 7.2

Thank You
![Annotation 2020-05-19 185230](https://user-images.githubusercontent.com/49265629/82331557-e96b7580-9a01-11ea-85f9-f5cc93251518.png)
