### ISSUE TITLE
Drawing() setPath does not work with special characters

### ISSUE THREAD

**Issue by duncanclaridgebg** [PHPOffice/PhpSpreadsheet#1470]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The .xlsx file should open normally and display any added images.

### What is the current behavior?
When attempting to open the file, you see an 'Alert' popup saying 'We found a problem with some content in MyFileName.xlsx'.

### What are the steps to reproduce?
Use an image file that has a '#' in the filename.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$spreadsheet->createSheet();
$spreadsheet->setActiveSheetIndex(0);

$drawing = new \PhpOffice\PhpSpreadsheet\Worksheet\Drawing();
$drawing->setName('test');
$drawing->setDescription('test');
$drawing->setPath('/var/www/various_folder_names/my_filename_#000000_700x400.png');
$drawing->setCoordinates('A1');
$drawing->setOffsetX(0);
$drawing->setRotation(0);
$drawing->setWorksheet( $spreadsheet->getActiveSheet() );

$objWriter = new Xlsx( $spreadsheet );
$objWriter->save('php://output');

```

### Which versions of PhpSpreadsheet and PHP are affected?
I'm using PHP 7.3 and the version of PhpSpreadsheet is 1.9.0 2019-08-17

**Comment by Vagir-dev** [comment]
Hi!

I checked the situation you've described out and I think it's not a PhpSpreadsheet's bug.
**MS Excel doesn't allow drawing's (and not only drawing's,  I suppose) filenames to include symbol '#'.**
So, when an opened XLSX-file contains an incorrect filename, Excel raises an error.

PhpSpreadsheet doesn't change such filenames in writing methods because it's your (as a programmer) responsibility to provide a correct filenames.

I think you could add a little code to bring the file names to an acceptable format.

**Comment by duncanclaridgebg** [comment]
That’s totally fine.

Thanks for clearing that up. It’s a great class by-the-way.

Actually… may I be cheeky (whilst you’re here). I have a question to do with very large datasets. We have one report that can be very big – and we constantly run into memory problems with it. Is there a way to save partial sheets and then stitch them together at the end?


Kind regards

Duncan Claridge
Web Developer

BIG GROUP Retail

Switch:  +44 (0) 1635 524055

The Big Barn, Hambridge Farm,
Hambridge Road, Newbury RG14 2QG

Registered in England: 2581201

www.biggroup-retail.co.uk<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.biggroup-retail.co.uk%2F&data=02%7C01%7Cduncan.claridge%40biggroup.co.uk%7C78cac0a6c57a412228a708d7c7392e4c%7Ce1bfdd245a6a4babb0cf3629b731cf05%7C0%7C0%7C637196920717052202&sdata=sL%2BcuINk4VWNTsCPfhEzD26oWJ1PjC0ygUpVI2LSFG4%3D&reserved=0>

**Comment by Vagir-dev** [comment]
> Thanks for clearing that up. It’s a great class by-the-way.

Thanks! I'm glad to help.


> I have a question to do with very large datasets. We have one report that can be very big – and we constantly run into memory problems with it. Is there a way to save partial sheets and then stitch them together at the end?

I think the solution of the memory problem depends very much on exactly where in the code it happens. Unfortunately, it's hard to say anything useful without analyzing your code.

But for now I don't see any reason why your large report cannnot be created step by step and then merged into a single document.

**Comment by norqf** [comment]
Dentro de la carpeta "vendor\PhpOffice\PhpSpreadsheet\Worksheet" modifica el archivo Drawing.php
  public function getIndexedFilename()
    {
        // $fileName = $this->getFilename();
        // $fileName = str_replace(' ', '_', $fileName);
        //return str_replace('.' . $this->getExtension(), '', $fileName) . $this->getImageIndex() . '.' . $this->getExtension();
        return "imagen".$this->getImageIndex() . '.' . $this->getExtension();
    }
![solucion temporal](https://user-images.githubusercontent.com/92640879/137594019-d6756a7a-3b54-4126-b183-a7c32a1f9467.png)

**Comment by norqf** [comment]
Dentro de la carpeta "vendor\PhpOffice\PhpSpreadsheet\Worksheet" modifica el archivo Drawing.php
  public function getIndexedFilename()
    {
        // $fileName = $this->getFilename();
        // $fileName = str_replace(' ', '_', $fileName);
        //return str_replace('.' . $this->getExtension(), '', $fileName) . $this->getImageIndex() . '.' . $this->getExtension();
        return "imagen".$this->getImageIndex() . '.' . $this->getExtension();
    }
![solucion temporal](https://user-images.githubusercontent.com/92640879/137594171-2d7ddd6b-40c7-4ca9-a16d-5678bb9a24fb.png)

**Comment by windmeup62** [comment]
If ththe problem with "#" in image filename ist still interesting here is a quick solution:
#norqf point me to the right direction.
1. Go to the file ../Worksheet/Drawing.php
2. Go to the function "getIndexedFilename()"
3. Add before or after $filename = str_replace(' ','_', $filename); a new line with:
4. $filename = str_replace('#','%23', $filename);

That's it. Now Excel find the image and open correctly without faults.
