### ISSUE TITLE
I know this won't be answered

### ISSUE THREAD

**Issue by stratboy** [PHPOffice/PhpSpreadsheet#1471]
Ok, I see you do not aswer on github. Well, I wrote on stackoverflow:

https://stackoverflow.com/questions/61757048/why-am-i-getting-encoding-problems-with-phpspreadsheet

Didn't get your answer, though.

**Comment by Vagir-dev** [comment]
Sorry, I don't see any problems in your code. When I run it I just get an empty worksheet with data that you set:
![image](https://user-images.githubusercontent.com/64550355/81943539-30252e00-9604-11ea-8e07-f5ebc79902f9.png)
And that's what have to be.

To get more cpecific diagnostic can you please attache file 01simple.xls which you've dounloaded when run your code?

**Comment by Vagir-dev** [comment]
> I know this won't be answered

@stratboy, now it's clear why your questions aren't answered - because it's just a waste of time.

**Comment by stratboy** [comment]
Sorry I already moved to another library that works. Anyway, if you answer 2 days after my question, since I have to work and finish the projects, chances are that I moved elsewhere or already found some kind of alternative or solution in the meantime.

That said, as I wrote on stackoverflow, the issue was quite strange since that very code do work if I run it from the PhpSpreadsheet examples. It doesn't when I move to another folder. Or more precisely, it does create the xls but with some econding issues (I guess).

Anyway, I solved the problem using another library, so this thread can be closed.

Thank you.

**Comment by Vagir-dev** [comment]
@stratboy, I am not a member of the PhpSpreadsheet development team.
So I answered your issue as soon as I saw it and when I had some free time. :)

**Comment by stratboy** [comment]
Ah, and before closing this issue, well, after 5 days there is no answer by the developer, nor the developer answered on stackoverflow. So, again, essentially the dev do not give tech support and won't answer any question. Therefore, go move to this, easier and better:

https://github.com/mk-j/PHP_XLSXWriter

Or, if you're a js coder, maybe even better:

https://sheetjs.com/
