### ISSUE TITLE
Excel is closing when i try to print

### ISSUE THREAD

**Issue by ShreeVas7989** [PHPOffice/PhpSpreadsheet#1474]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I want to print the excel i have downloaded

### What is the current behavior?
i can't print the excel that i downloaded

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
$spreadsheet = new Spreadsheet();

		$sheet = $spreadsheet->getActiveSheet();

		$spreadsheet->getActiveSheet()->mergeCells('A1:G1');
		$spreadsheet->getActiveSheet()->mergeCells('A2:G2');
		$spreadsheet->getActiveSheet()->mergeCells('A3:G3');

		$spreadsheet->getActiveSheet()->setCellValue('A1', 'PEOPLE CO-OP SOCIETY LTD');
		$spreadsheet->getActiveSheet()->setCellValue('A2', $agentbranch);
		$spreadsheet->getActiveSheet()->setCellValue('A3', $agentcodedetails);

		$spreadsheet->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
   		$spreadsheet->getActiveSheet()->getStyle('A2')->getFont()->setBold(true);
   		$spreadsheet->getActiveSheet()->getStyle('A3')->getFont()->setBold(true);

   		$sheet->getStyle('A1')->getAlignment()->setHorizontal('center');
   		$sheet->getStyle('A2')->getAlignment()->setHorizontal('center');
   		$sheet->getStyle('A3')->getAlignment()->setHorizontal('center');

   		$spreadsheet->getActiveSheet()->getStyle('D')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_NUMBER);
   		$spreadsheet->getActiveSheet()->getStyle('C')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_DATE_DMYSLASH);
		//First Converting Transaction rows to normal associative array

		//First Filtering the transactionrows
		//Setting Header for this excel
   		$headerarray = array(
   			'Serial Number',
   			'Transdate',
   			'Account Type',
   			'Account Number',
   			'Account Name',
   			'Closing Balance',
   			'Demand Amount',
   			'Recvd Amount',
   			'Member Number',
   		);

   		 $sheet->fromArray([$headerarray], NULL, 'A4');
   		 $spreadsheet->getActiveSheet()->getStyle('A4:I4')->getFont()->setBold(true);
   		 $spreadsheet->getActiveSheet()->getRowDimension('4')->setRowHeight(30);
   		 
		//
		$i = 5;
		$actyperows = $this->posdb->get('products')->result();
		$demandtotal = '';
		$receivedtotal = '';
		foreach ($transactionrows as $exportrow) {
		  $serialno = $exportrow->serialno;
          $transactiondate = $exportrow->transactiondate;
          $accounttype = $exportrow->accounttype;
          $acno = $exportrow->acno;
          $acname = $exportrow->acname;
          $closingbal = $exportrow->closingbal;
          $demandamount = $exportrow->demandamount;
          $amountpaid = $exportrow->amountpaid;
          $membershipno = $exportrow->membershipno;

          $demandtotal = $demandtotal + $demandamount;
          $receivedtotal = $receivedtotal + $amountpaid;

          //Changing Date FOmat
		  $transactiondate = date("d/m/Y", strtotime($transactiondate));

          foreach ($actyperows as $actyperow) {
          	if($accounttype == $actyperow->id){
          		$accounttype = $actyperow->code;
          		break;
          	}
          }
          //Getting Actypes form
          $array = array(
          	$serialno,
			$transactiondate,
			$accounttype,
			$acno,
			$acname,
			$closingbal,
			$demandamount,
			$amountpaid,
			$membershipno,
          );

          $sheet->fromArray([$array], NULL, 'A'.$i);
          $i++;
   		}

   		$cell = 'G'.$i++;
   		$spreadsheet->getActiveSheet()->setCellValue($cell, 'DEMAND GRAND TOTAL');
   		$cell = 'G'.$i++;
   		$spreadsheet->getActiveSheet()->setCellValue($cell, $demandtotal);
   		$cell = 'G'.$i++;
   		$spreadsheet->getActiveSheet()->setCellValue($cell, 'RECEIVED GRAND TOTAL');
   		$cell = 'G'.$i++;
   		$spreadsheet->getActiveSheet()->setCellValue($cell, $receivedtotal);

   		$spreadsheet->getActiveSheet()->getPageSetup()
    ->setOrientation(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_LANDSCAPE);
		$spreadsheet->getActiveSheet()->getPageSetup()
    ->setPaperSize(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_A4);

   		$writer = new Xlsx($spreadsheet);
		$writer->setOffice2003Compatibility(true);
		$path = "./assets/uploads/temp/".$filename;
		$writer->save($path);

**Comment by Vagir-dev** [comment]
> i can't print the excel that i downloaded

@ShreeVas7989, I'm afraid no one can help you because no one has your database from which you set data to a spreadsheet. Without this, it is impossible to analyze your problem.

Try to delete parts of the code one by one and open the resulting file each time. This way you will know which part is causing the problem.

**Comment by ShreeVas7989** [comment]
I am saying Excel is not printing . How can i upload sample excel

**Comment by Vagir-dev** [comment]
>How can i upload sample excel

Look at the bottom block of form, where you type your messages. There is a text "Attach files by dragging..." Just click on it :)

**Comment by ShreeVas7989** [comment]
[DS_2020-05-16_2020-05-16_189.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4639599/DS_2020-05-16_2020-05-16_189.xlsx)
This is the excel i am trying to print but it was closing when i try to print ....
But if i save as like a new file then it was opening

**Comment by ShreeVas7989** [comment]
Hey I found the solution ..... 
        $writer = new Xlsx($spreadsheet);
	"""$writer->setOffice2003Compatibility(true);""""
	$path = "./assets/uploads/temp/".$filename;
	$writer->save($path);

if i remove the  2nd line setOffice2003Compatibility(true)  .... it was workig
