### ISSUE TITLE
For Xlsx, setBold & setItalic is not working with Richtext

### ISSUE THREAD

**Issue by smit-devdigital** [PHPOffice/PhpSpreadsheet#1479]
This is:

```
- [ ] a bug report
```

### What is the expected behavior?
For Xlsx, setBold & setItalic should work with Richtext 

### What is the current behavior?
When creating a richtext & applying setBold & setItalic then it is not working for Xlsx. When we use Xls instead of Xlsx then it is working fine.

**Output with Xlsx:**
![Annotation 2020-05-19 195336](https://user-images.githubusercontent.com/49265629/82338380-75819b00-9a0a-11ea-9b74-1add53a645ba.png)

**Output with Xls:**
![Annotation 2020-05-19 200017](https://user-images.githubusercontent.com/49265629/82339191-651df000-9a0b-11ea-9eee-cce769d25cc5.png)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$line1 = new \PhpOffice\PhpSpreadsheet\RichText\Run('Line 1' . chr(10));
$line1->getFont()->setBold(true)->setUnderline(true);

$line2 = new \PhpOffice\PhpSpreadsheet\RichText\Run('Line 2' . chr(10));
$line2->getFont()->setBold(true);

$line3 = new \PhpOffice\PhpSpreadsheet\RichText\Run('Line 3');

$richText = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
$richText->addText($line1);
$richText->addText($line2);
$richText->addText($line3);

$sheet->getCell('A1')->setValue($richText);
$sheet->getStyle('A1')->getAlignment()->setWrapText(true);
$sheet->mergeCells("A1:A4");

\PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadSheet: 1.12
PHP: 7.214

**Comment by Vagir-dev** [comment]
Hi!

It is strange.

What I get after run exactly your code:

![image](https://user-images.githubusercontent.com/64550355/82340271-b7551600-99f7-11ea-9a31-0fe8aa692fbe.png)

So it's what have to be.

PHP: 7.2.22
PhpSpreadsheet: 1.12 + master last dev

Try to debug code on your local machine... Or wait for 1.13...
