### ISSUE TITLE
[BUG] number of days from 1900 calculated has 2 extra days

### ISSUE THREAD

**Issue by moiz-conceptlz** [PHPOffice/PhpSpreadsheet#1496]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When an excel file is imported, a date format returns the value as stored by excel - which is the number of days from 1900. However, 2 extra days get added while a sheet is imported. 

### What is the current behavior?
when a cell which has a date in the format of d/m/Y the return value in the array is the number of days from 1900 - but the value is wrong. 

### What are the steps to reproduce?
Create an excel file and in any column add a date in the format as 26/02/2019 ( this is essentially d/m/Y). When this file is imported using the package, the resulting data includes the value of excel with the number of days from 1990.

An example file is included which contains date values. Notice Column K has ETA which has dates in the format of d/m/Y.

[moon_report.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4695402/moon_report.xlsx)

**if the value of a date is 26/02/2019 - the resulting number of days should be 43520. However, the imported data has 43522**. This is consistent with any date, where 2 days are added. It can be confirmed by this - https://www.convertunits.com/dates/from/Jan+1,+1900/to/Feb+26,+2019

### Which versions of PhpSpreadsheet and PHP are affected?
1.10

**Comment by tezrik** [comment]
this bag in Microsoft Exel 
https://github.com/PHPOffice/PhpSpreadsheet/blob/5dd7e883c6bd409063882de2cde1a07a556f25be/src/PhpSpreadsheet/Shared/Date.php#L281-L284

According to estimates, really 43520 days. But Microsoft Exel itself calculates this date as 43522 days.
Checked through in Microsoft Exel 2010

**Comment by tezrik** [comment]
You can use 
```
$value = $worksheet->getCell('A1')->getValue();
$date = \PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($value);
```
