### ISSUE TITLE
Ubuntu 17.04 test failed.

### ISSUE THREAD

**Issue by titanrat** [PHPOffice/PhpSpreadsheet#150]
phpunit fails with

1) PhpOffice\PhpSpreadsheetTests\SampleTest::testSample with data set "27 Images Xls" ('/home/user/PhpstormProjects/P...ls.php')
PHPUnit_Framework_Exception: libpng warning: iCCP: known incorrect sRGB profile
libpng warning: Interlace handling should be turned on when using png_read_image

error.

**Comment by PowerKiKi** [comment]
According to [this](http://stackoverflow.com/questions/12990602/libpng-warning-interlace-handling-should-be-turned-on-when-using-png-read-image), it may be related to the image itself. Are you able to reproduce with a different image ?

**Comment by titanrat** [comment]
Changing images in template xls file solves problem.

**Comment by titanrat** [comment]
I'm preparing PR for solving this problem.
btw, tests fails on win 10 too. Is it normal behavior?

**Comment by PowerKiKi** [comment]
I don't use win10 and have no easy way to test it, but ideally it should not fail...

**Comment by titanrat** [comment]
I'll create another issue for Win10 when find problem.
