### ISSUE TITLE
[BUG] getFormattedValue method

### ISSUE THREAD

**Issue by 315933614** [PHPOffice/PhpSpreadsheet#1507]
This is:

- [x] a bug report

Excel cell value is in date format,but the result obtained by the ```getformattedvalue ```method is a number.

```Excel File```
[1.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4722638/1.xlsx)

### What is the expected behavior?

```python
import pandas as pd
print(pd.read_excel('1.xlsx'))
````
![1](https://user-images.githubusercontent.com/6285874/83624406-253b3900-a5c5-11ea-8199-d60eb2a9ff16.png)
![2](https://user-images.githubusercontent.com/6285874/83624413-28362980-a5c5-11ea-863d-a58979891b19.png)

### What is the current behavior?
```php
$reader = IOFactory::createReaderForFile('1.xlsx');
        $reader->setReadDataOnly(true);
        $spreadsheet = $reader->load($excel_path);
        $excel = $spreadsheet->getActiveSheet();
        $dates=$excel->getCell("A1")->getFormattedValue();
```
![3](https://user-images.githubusercontent.com/6285874/83625297-4bada400-a5c6-11ea-894e-46b091166e64.png)

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet  = 1.13.0

**Comment by MarkBaker** [comment]
If you use `$reader->setReadDataOnly(true);` then you're telling PHPSpreadsheet to load the data, but to ignore the formatting information. In MS Excel, a data is just a number with formatting information to tell Excel that it should be displayed as a date.
This is not a bug; this is how Excel works, and hence how PHPSpreadsheet works. Don't set read data only to true, and you will get the formatting information loaded, and PHPSpreadsheet will be able to recognise when numbers should be formatted as dates.
