### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by rajendrap123** [PHPOffice/PhpSpreadsheet#1508]
This is:
D:\xampp\htdocs\aayo\aayowebapp>composer require phpoffice/phpspreadsheet --update-no-dev
You are running Composer with SSL/TLS protection disabled.
Using version ^1.13 for phpoffice/phpspreadsheet
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package backpack/generators (locked at v2.0.7, required as ^3.0) is satisfiable by backpack/generators[v2.0.7] but these conflict with your requirements or minimum-stability.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

Installation failed, reverting ./composer.json to its original content.
```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?
I tried to install PHPspreadsheet and its giving me this error

### Which versions of PhpSpreadsheet and PHP are affected?
1.13

**Comment by PowerKiKi** [comment]
This is not related with PhpSpreadsheet. The package `backpack/generators` which is the source of your problem has no relation at all with PhpSpreadsheet.
