### ISSUE TITLE
 Define hyperlink for all rows in the column

### ISSUE THREAD

**Issue by jefersonroots** [PHPOffice/PhpSpreadsheet#1513]
I'm only managing to set it to 1 cell.
setToolTip is not work!!
there is some way to define setCellValue ('A', 'text').

to get all the rows? 

Here is the code:
    **$spreadsheet
    ->getActiveSheet()
    ->setCellValue('I2', $data->CORPRODUTO)
    ->getCell('I'.$row)
    ->getHyperlink ('I'.$row) 
    ->setUrl($data->FOTO )
    ->setTooltip('TESTE');**

**Comment by jefersonroots** [comment]
**i have this return**
![image](https://user-images.githubusercontent.com/64113091/83933080-e6031880-a77b-11ea-9560-9ea941f3f4f6.png)

**Comment by oleibman** [comment]
I do not think there is a good use case for this. Closing as "not planned" (won't fix), removing stale label.
