### ISSUE TITLE
Borders fill not working correctly

### ISSUE THREAD

**Issue by davidasrocha** [PHPOffice/PhpSpreadsheet#152]
Hello,

I'm attempting using borders feature, but not working correctly.
I create a square region and I applying borders, but borders at top, right and bottom not were applieds.

I do severals attempts, but result some were.
 
This is a bug?

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue without relying on an external Excel file.

And don't forget to mention what version of this project you are using.

**Comment by davidasrocha** [comment]
Hi @PowerKiKi 

I created a Gist with example https://gist.github.com/davidasrocha/bad22920ad7d00854853402f4a287840.
I'm use dev-master version with Composer and my PHP version is 7.0 .

**Comment by PowerKiKi** [comment]
Could you please try with develop branch latest commit ?

**Comment by davidasrocha** [comment]
I tested with develop branch latest commit, but I had same result.

**Comment by PowerKiKi** [comment]
Fixed by https://github.com/PHPOffice/PhpSpreadsheet/commit/1c5db4e17052f19cd8bbed00d20f9ee394d04cd5
