### ISSUE TITLE
only 2 row but \PhpOffice\PhpSpreadsheet\Reader\Xlsx::listWorksheetInfo.totalRows ===1048560

### ISSUE THREAD

**Issue by qidizi** [PHPOffice/PhpSpreadsheet#1529]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

`\PhpOffice\PhpSpreadsheet\Reader\Xlsx::listWorksheetInfo.totalRows === 2`   

### What is the current behavior?
` \PhpOffice\PhpSpreadsheet\Reader\Xlsx::listWorksheetInfo.totalRows ===1048560`   

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// create reader
            $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
// get info
        $names = $reader->listWorksheetInfo($excel_path);
        var_dump($names);exit;

/* 
output:  
array (size=1)
  0 => 
    array (size=5)
      'worksheetName' => string '1' (length=1)
      'lastColumnLetter' => string 'O' (length=1)
      'lastColumnIndex' => int 14
      'totalRows' => string '1048560' (length=7)
      'totalColumns' => int 15

*/
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.13.0
php72
docker desktop 2.3.0.3 + centos7
MacBook Pro (15-inch, 2017) osx-10.15.5 (19F101)  2.8 GHz 四核Intel Core i7  16 GB 2133 MHz LPDDR3

[qidizi.xlsx](https://code.aliyun.com/qidizi/public/raw/b0e3ee5f67cee2c0baaa1ce37659a74384cfab22/qidizi.xlsx)

**Comment by oleibman** [comment]
Rows 1 through 95, and row 1048560, all have a custom height in qidizi.xlsx. That last one is, of course, the source of the totalRows value above; the row is 21 pixels high, where everything around it is 20. But, even if you delete that row and save, you would still see a value of 95, not 2, for totalRows.

**Comment by khayyak** [comment]
I have similar issue , and I have two solutions :
First : when you delete old rows from XLSX file you should not delete normally with delete button , you should delete it using delete option in the top right of excel file .
Second one : you can check if a required cell is null or whole row is null like that :

for($row = 2 ; $row <= $lastRow ; $row++)
{
if($page->getCell('A'.$row)->getValue() == NULL && $page->getCell('B'.$row)->getValue() == NULL)
{
break;
//or continue or anything you want;
}
else
{
// your logic
}
}

hope that helps you or help someone need it.
