### ISSUE TITLE
libxml_disable_entity_loader causing problems with other libraries

### ISSUE THREAD

**Issue by franksl** [PHPOffice/PhpSpreadsheet#1539]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

Hi,
I have a big file that goes out of memory when reading with PhpSpreadsheet, so for that particular file I decided to use spout.
I still use the file format check in PhpSpreadsheet (Xlsx::canRead()) method, but I have a problem when passing from PhpSpreadheet to spout.
Basically, after some investigations, I found that the XmlScanner class calls libxml_disable_entity_loader(true), but does not set it to false properly, because the destructor of XmlScanner, wich calls libxml_disable_entity_loader(false) does not get called before it's needed.

Here's an example:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$path = 'path_to_spreadsheet.xlsx';
$ckrdr = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
if ($ckrdr->canRead($path)) {
    $wb = \Box\Spout\Reader\Common\Creator\ReaderEntityFactory::createXLSXReader();
    $wb->open($path); // here a "XMLReader::open(): Unable to open source data" appears 
}
```
To make it work I need to call libxml_disable_entity_loader(false) before the $wb->open($path) line

I think libxml_disable_entity_loader(false) should be called in a controllable point, maybe in the scan method.
Thanks,
Franco

**Comment by oleibman** [comment]
After dropping support for Php7.4, libxml_disable_entity_loader is no longer called by PhpSpreadsheet.
