### ISSUE TITLE
Exception: Sheet does not exist. Coping Worksheet from another Spreadsheet

### ISSUE THREAD

**Issue by diosby** [PHPOffice/PhpSpreadsheet#1542]
This is a bug report.

### What is the expected behavior?
The sheet must be copied and it must not be removed from original Spreadsheet.

### What is the current behavior?
**Sheet does not exist.**
vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Spreadsheet.php
728: throw new Exception('Sheet does not exist.');

### What are the steps to reproduce?
```php
$customEditionSizeSheet = clone $firstSpreadsheet->getSheetByName('Wide printed sheet');
$customEditionSizeSheet->setTitle('Example CustomEditionSize');
$spreadsheet->addExternalSheet($customEditionSizeSheet);
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.13.0

**Comment by diosby** [comment]
The addExternalSheet (https://github.com/PHPOffice/PhpSpreadsheet/blob/10a4a95d678d674a612c9126f912acab2013f294/src/PhpSpreadsheet/Spreadsheet.php#L840) function calls the rebindParent (https://github.com/PHPOffice/PhpSpreadsheet/blob/10a4a95d678d674a612c9126f912acab2013f294/src/PhpSpreadsheet/Worksheet/Worksheet.php#L803) function that removes the sheet from the parent Spreadsheet.

**Comment by MarkBaker** [comment]
Duplicate of Issue [#1483](https://github.com/PHPOffice/PhpSpreadsheet/issues/1483)

**Comment by oleibman** [comment]
The following code will work as desired, by temporarily adding the cloned sheet to the original, from which it will be removed by addExternalSheet:
```php
$customEditionSizeSheet = clone $firstSpreadsheet->getSheetByName('Wide printed sheet');
$customEditionSizeSheet->setTitle('Example CustomEditionSize');
$firstSpreadsheet->addSheet($copySheet);
$spreadsheet->addExternalSheet($customEditionSizeSheet);
```
It is possible that this solution should be officially documented, and/or that a new method to simplify this might be added. I will think about both.
