### ISSUE TITLE
Export in OpenDocument format err

### ISSUE THREAD

**Issue by autumnrustle** [PHPOffice/PhpSpreadsheet#155]
I use PhpSpreadsheet-master. Donload it. open examples and try to run `01_Simple_download_ods.php`. When I open generated file inside I see next:

`Fatal error: Uncaught Error: Class 'PhpOffice\PhpSpreadsheet\Writer\ReflectionObject' not found in C:\Users\autumn\Dropbox\xampp\htdocs\fish\PhpSpreadsheet-master\src\PhpSpreadsheet\Writer\OpenDocument.php:147 Stack trace: #0 C:\Users\autumn\Dropbox\xampp\htdocs\fish\PhpSpreadsheet-master\src\PhpSpreadsheet\Writer\OpenDocument.php(108): PhpOffice\PhpSpreadsheet\Writer\OpenDocument->createZip('C:\\Users\\autumn...') #1 C:\Users\autumn\Dropbox\xampp\htdocs\fish\PhpSpreadsheet-master\samples\01_Simple_download_ods.php(56): PhpOffice\PhpSpreadsheet\Writer\OpenDocument->save('C:\\Users\\autumn...') #2 {main} thrown in C:\Users\autumn\Dropbox\xampp\htdocs\fish\PhpSpreadsheet-master\src\PhpSpreadsheet\Writer\OpenDocument.php on line 147`

**Comment by PowerKiKi** [comment]
Master is broken, use develop branch.
