### ISSUE TITLE
Replace \n when insert array

### ISSUE THREAD

**Issue by autumnrustle** [PHPOffice/PhpSpreadsheet#156]
So, I have array with data and in some pleaces with prepeared \n
```
$dataArray = [
    ['2010', 'Q1', 'United\nStates', 790],
    ['2010', 'Q2', 'United States', 730],
    ['2010', 'Q3', 'United States', 860]
]
```
I insert tihis data using `fromArray()`

`$spreadsheet->getActiveSheet()->fromArray($dataArray, null, 'A1');`

After I try to replace \n and want see next:

```
2010 | Q1 | United           | 790
     |    | States           | 
2010 | Q2 | United States    | 730
```
I use this to do this

`$spreadsheet->getActiveSheet()->getStyle('C1')->getAlignment()->setWrapText(true);`

What can I do to this?

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!

**Comment by autumnrustle** [comment]
I think it is not a quastion. If read and insert info and after that try to wrap - no result.

**Comment by MarkBaker** [comment]
this is a problem with your understanding of PHP strings.

```
    $dataArray = [
        ['2010', 'Q1', 'United\nStates', 790],
        ['2010', 'Q2', 'United States', 730],
        ['2010', 'Q3', 'United States', 860]
    ]
```

A `'\n'` in single quotes is treated as a literal `\n`; a `"\n"` in double quotes is treated as a new line character.  So either build your array using double quotes:

```
    $dataArray = [
        ['2010', 'Q1', "United\nStates", 790],
        ['2010', 'Q2', "United States", 730],
        ['2010', 'Q3', "United States", 860]
    ]
```

or convert the literal `\n` to a new line using str_replace:

```
    $modified = str_replace('\n', "\n", $original);
```
