### ISSUE TITLE
Empty shared string breaks string references in Xlsx file

### ISSUE THREAD

**Issue by bianchim** [PHPOffice/PhpSpreadsheet#1560]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Using the Xlsx reader with empty shared strings should provide empty strings in the data.
This is represented by an empty '<si\><\/si>' in the shared strings file when unzipping the Xlsx file.

### What is the current behavior?
The strings gets ignored and skipped, throwing the whole share strings array indices off by 1.

### What are the steps to reproduce?

The bug is present exactly there : 
https://github.com/PHPOffice/PhpSpreadsheet/blob/1.14.0/src/PhpSpreadsheet/Reader/Xlsx.php#L434

You can either make a test file and empty a shared string in it manually (unzip, modify "xl/sharedStrings.xml" and rezip it), or force the "else" case on one string in the linked code above.
The result in both will be to throw an "undefined index" when simply opening and reading the file, since the last shared string will be out of bounds.

### Which versions of PhpSpreadsheet and PHP are affected?
Last stable ( 1.14.0 )

### Possible resolution
The simplest fix would be to add an else case and put an empty string in there. While this worked in my case, I don't have the time nor ressources to make extensives tests, and I fear this could break other things for other users.

**Comment by oleibman** [comment]
Reopening, will be fixed by solution for issue #4063.
