### ISSUE TITLE
Auto-Calculating problem with Excel

### ISSUE THREAD

**Issue by Leamo** [PHPOffice/PhpSpreadsheet#1563]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

File auto-calculate formulas as defined in the options. No "calculate" in status bar.

### What is the current behavior?

Sheets no longer calculates automatically. A "calculate" button appear in status bar. It affect all opened workbooks.

### What are the steps to reproduce?

- Using https://github.com/Maatwebsite/Laravel-Excel and download simple xlsx file with it. (following the 5 minutes quick start guide by example)
- Open it with Office 365 Excel with calculation option set to automatic (Tools-->Options-->Formulas-->Calculation options)
- Click 'Enable Editing' if requested.

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet Version : ^1.14
PHP Version : 7.2.27

I reported the bug to laravel plugin repo but it seems to be a PhpSpreadsheet internal behavior : https://github.com/Maatwebsite/Laravel-Excel/issues/2543

![pic1](https://user-images.githubusercontent.com/7149459/86221678-82ef8080-bb85-11ea-929e-c25c90e724c0.png)

![pic2](https://user-images.githubusercontent.com/7149459/86221700-88e56180-bb85-11ea-99cb-6afc6f461258.png)

**Comment by oleibman** [comment]
forceFullCalc option was added by PR #4271, and the default setting with Release 4.0 is that it not be used unless explicitly requested.
