### ISSUE TITLE
Support "chartsheet", a spreadsheet with only a chart in it

### ISSUE THREAD

**Issue by tristanleboss** [PHPOffice/PhpSpreadsheet#1564]
This is:

```
- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
`getChartCollection` on the worksheet object should return the chart.

### What is the current behavior?
`getChartCollection` returns an empty collection.

### What are the steps to reproduce?
Using Excel, create a chart. Then, right click on it and select "Move Chart...".
In the window, choose "New sheet".

![image](https://user-images.githubusercontent.com/1431508/86247082-42572d80-bbac-11ea-8361-b297531b1eb9.png)

![image](https://user-images.githubusercontent.com/1431508/86247060-3cf9e300-bbac-11ea-86c3-fa801f06f3c8.png)

### Which versions of PhpSpreadsheet and PHP are affected?
1.14.0

**Comment by oleibman** [comment]
Chartsheets are supported since PR #2830 which was merged 2 years ago. Support isn't perfect (handled as a worksheet with a chart rather than a chartsheet). If that is not sufficient, please open a new issue.
