### ISSUE TITLE
Problems with line-breaks and missing enclosure escaping in CSV file

### ISSUE THREAD

**Issue by Hativ** [PHPOffice/PhpSpreadsheet#1569]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

I expect the following output:

```
1
2
3
```

LibreOffice Calc opens the file correctly.

### What is the current behavior?

I get the following output:

```
1
2
Test"
3
```

### What are the steps to reproduce?

CSV file:
```
"1";"Test"
"2";"Test
Test "Test" Test
Test"
"3";"Test"
```

PHP code:
```php
<?php

require_once('vendor/autoload.php');

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Csv();
$reader->setInputEncoding('UTF-8');
$reader->setDelimiter(';');
$reader->setEnclosure('"');
$reader->setSheetIndex(0);

$spreadsheet = $reader->load('test.csv');
$worksheet = $spreadsheet->getActiveSheet();

$highestRow = $worksheet->getHighestRow();

for ($row = 1; $row <= $highestRow; ++$row) {
  $cellValue = $spreadsheet->getActiveSheet()->getCellByColumnAndRow(1, $row)->getValue();
  echo($cellValue . '<br>');
}
```

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet version: 1.14.0
PHP version: 7.4.7

**Comment by oleibman** [comment]
PhpSpreadsheet is behaving in exactly the same manner as Excel does when it loads this file.

**Comment by oleibman** [comment]
In addition, your data does not conform to the RFC 4180 https://tools.ietf.org/html/rfc4180, the standard for CSV files.
In particular:
Item 5: If fields are not enclosed with double quotes, then
       double quotes may not appear inside the fields.
Item 7: If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.
Your intended value for cell B2 starts with a double-quote, which is matched by the first unescaped double-quote;
however, there is no separator character following that, so the field continues. But it is no longer enclosed in
double quotes, so continues to end of line (including the other unescaped double-quote on that line);
the next line starts a new row. That is why you are seeing the result you are seeing. If you were to change line 3 to read:
Test ""Test"" Test, you would see the result you are expecting, in both PhpSpreadsheet and Excel.

**Comment by Hativ** [comment]
Thank you. Unfortunately the world out there is not perfect and CSV file creators don't stick to RFC's. But we have to deal with it. So it would be great if PhpSpreadsheet could also parse CSV files that are not that compliant. Like Libreoffice Calc does. So don't consider the issue as a bug, but as a feature request.

**Comment by oleibman** [comment]
LibreOffice seems to be the outlier here. I agree that it parses the file as you wish. On the other hand, Gnumeric parses it just as Excel does. Changing the behavior of PhpSpreadsheet here, even it were desirable, would require a change not to PhpSpreadsheet, but to PHP itself, since the data is parsed using the PHP function fgetcsv.

**Comment by Hativ** [comment]
I now solve this with a regex that edits the file before opening and escapes it. Maybe something like that would be an optional feature for PhpSpreadsheet.
