### ISSUE TITLE
php 7.4 support in 1.8.x

### ISSUE THREAD

**Issue by ArtemGoutsoul** [PHPOffice/PhpSpreadsheet#1575]
This is a bug report and a request

### What is the expected behavior?
1.8.x would work on php 7.4. We have a case when we want to run the same code in 7.0 and 7.4, so 1.9.x and newer are not suitable.

### What is the current behavior?
1.8.2 fails with php 7.4.

### What are the steps to reproduce?

\PhpOffice\PhpSpreadsheet\Reader\Xlsx\Styles::readAlignmentStyle fails with accessing array keys on null value.

### Which versions of PhpSpreadsheet and PHP are affected?
1.8.2

Proposed solution:
- pls make a branch 1.8.x from 1.8.2 release to continue making releases for 1.8.x
- I could try to fix php 7.4 related issues that we encounter: e.g. https://github.com/PHPOffice/PhpSpreadsheet/compare/master...Enkora:1.8.2-php74

**Comment by EduVillas** [comment]
Stil a problem here with php 7.4

**Comment by enter-rebel** [comment]
with 1.8.1 , i still got Array and string offset access syntax with curly braces is deprecated.

**Comment by enter-rebel** [comment]
but we already have many releases after 1.8

**Comment by jrmldesign-official** [comment]
Just delete the vendor then composer install then composer update. That'll do.
