### ISSUE TITLE
htmlspecialchars(): charset `0' not supported, assuming utf-8

### ISSUE THREAD

**Issue by ocyssau** [PHPOffice/PhpSpreadsheet#1577]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

error message :
    htmlspecialchars(): charset `0' not supported, assuming utf-8

in file :
    ..../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/XMLWriter.php:90

Trace :
#0 [internal function]: rbinit_exception_error_handler(2, 'htmlspecialchar...', '/usr/share/ranc...', 90, Array)
#1 vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/XMLWriter.php(89): htmlspecialchars('2009-04-02T16:2...')
#2 vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/DocProps.php(148): PhpOffice\PhpSpreadsheet\Shared\XMLWriter->writeRawData('2009-04-02T16:2...')
#3 vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(260): PhpOffice\PhpSpreadsheet\Writer\Xlsx\DocProps->writeDocPropsCore(Object(PhpOffice\PhpSpreadsheet\Spreadsheet))

### Solution

Can you try to change the line

return $this->writeRaw(htmlspecialchars($text));

to

return $this->writeRaw(htmlspecialchars($text, ENT_QUOTES, 'UTF-8'));

on line 90 of file phpspreadsheet/src/PhpSpreadsheet/Shared/XMLWriter.php

Thanks

### What are the steps to reproduce?
Only with specials xlsx workbooks

### Which versions of PhpSpreadsheet and PHP are affected?
All

**Comment by oleibman** [comment]
Probably resolved by Php fix https://bugs.php.net/bug.php?id=71876.
