### ISSUE TITLE
Paint full sheet Excel PhpSpreadsheet

### ISSUE THREAD

**Issue by jdavila2222** [PHPOffice/PhpSpreadsheet#1579]
Hello I am new to PhpSpreadsheet, I am trying to paint a whole sheet with a color, I would appreciate your help.

**Comment by jdavila2222** [comment]
![image](https://user-images.githubusercontent.com/68079552/87078886-44943a00-c1f3-11ea-8a42-49bc26da23c8.png)

**Comment by jdavila2222** [comment]
I need that

**Comment by MarkBaker** [comment]
From the "Styles" Section of the [PHSpreadsheet Documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#styles):

```
$spreadsheet->getActiveSheet()->getStyle('A1:E5')     // Choose your cell range here
    ->getFill()
    ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
    ->getStartColor()
    ->setARGB('FFFFFF00');    // Choose your colour here
```

Although setting a background colour for the entire worksheet is not a good idea; you would be better setting the colour for just a viewing area.
