### ISSUE TITLE
get styles from excel document

### ISSUE THREAD

**Issue by alsemyannikow** [PHPOffice/PhpSpreadsheet#1581]
Hello, I'm sorry I do not speak English well. My question is, I decided to draw an excel table on the screen based on your library, but I can’t get the styles that were previously saved in an excel document (.xlsx), how can I do this?

**Comment by MarkBaker** [comment]
Have you tried using the cell's `getStyle()` method? And there's a lot of information in the [Styles section](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#styles) or the [PHPSpreasheet documentation](https://phpspreadsheet.readthedocs.io/en/latest/), or looked at the [HTML Writer](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Writer/Html.php) to see how it's done there
