### ISSUE TITLE
It is recommended that you provide the option to ignore calculation errors.

### ISSUE THREAD

**Issue by qidizi** [PHPOffice/PhpSpreadsheet#1599]
This is a bug report    

### What is the expected behavior?

When the cell calculation is abnormal, the calculation ends and the user-defined value is returned, such as null; continue to read other cells.    

### What is the current behavior?

`rangeToArray($cut, null, 1, 1, 0)`     
The code execution is that when an exception occurs in a cell calculation, it throws an exception and returns null    

### What are the steps to reproduce?

`1.xlsx` and `3.xlsx` on same dir; then rename `3.xlsx` to `4.xlsx`, run the php code    
will get the exception    

```
Sheet2!A1 -> Formula Error: An unexpected error occurred

```    

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

 try {
            $sheet_index = 0;

        $reader->setLoadSheetsOnly('Sheet2');
        $reader->setReadDataOnly(1);// 是否考虑格式,经过测试,大概增加一半的时间;如果不考虑,日期像 2019-05-03 会变成 数字
        $spreadsheet = $reader->load('1.xlsx');// 
            $xy = $spreadsheet->getSheet($sheet_index)
                ->rangeToArray('A1:Z100', null, 1, 1, 0);
        }catch (Exception $e){
            echo $e->getMessage();
        }

```         

[3.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4985899/3.xlsx)        

[1.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4985901/1.xlsx)          

### Which versions of PhpSpreadsheet and PHP are affected?    

PhpSpreadsheet 1.14.1        
php 7.2   

### Temporary solution     

open `PhpSpreadsheet/Worksheet/Worksheet.php:2518` chang to    

```php
if ($calculateFormulas) {
                                try {
                                    $returnValue[$rRef][$cRef] = $cell->getCalculatedValue();
                                }catch (\Exception $e){
                                    $returnValue[$rRef][$cRef] = null;
                                }
                            }

```

**Comment by oleibman** [comment]
Addressed by PR #3092 in October 2022.
