### ISSUE TITLE
Fatal error: Class 'ZipArchive'

### ISSUE THREAD

**Issue by fastrer** [PHPOffice/PhpSpreadsheet#160]
This is:

- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
the code take a template and fill two cells

### What is the current behavior?
Fatal error: Class 'ZipArchive' not found

### What are the steps to reproduce?
on Ubuntu 16.04 install PHP 2.4.18 and apache 2.4.18

install extensions:
php-gd php-xml php-xsl php-zip

Download the repository and execute composer install on the directory, after create a test file, as next one

```php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require __DIR__.'/PhpSpreadsheet-develop/src/Bootstrap.php';
use PhpOffice\PhpSpreadsheet\IOFactory;

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$template = __DIR__."/templates/FLYAWAY_EN.xlsx";
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($template);
$worksheet = $spreadsheet->getActiveSheet();

$worksheet->getCell('B2')->setValue('John');
$worksheet->getCell('C2')->setValue('Smith');

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xls');
$writer->save('write.xls');

```

**Comment by PowerKiKi** [comment]
Do you have stacktrace that includes the file and line number ?

I suspect php-zip is installed but not enabled, can you double-check that by adding a line to your test file:

```php
var_dump(extension_loaded('zip'));
```

**Comment by fastrer** [comment]
```
var_dump of "var_dump(extension_loaded('zip'))":
/var/www/html/alchemy/calculadora/test2.php:10: bool(false)
end var_dump

Fatal error: Class 'ZipArchive' not found in /var/www/html/alchemy/calculadora/PhpSpreadsheet-develop/src/PhpSpreadsheet/Reader/Xlsx.php on line 87 Call Stack:

1. {main}() /var/www/html/alchemy/calculadora/test2.php:0 

2. PhpOffice\PhpSpreadsheet\IOFactory::load() /var/www/html/alchemy/calculadora/test2.php:17 

3. PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile() /var/www/html/alchemy/calculadora/PhpSpreadsheet-develop/src/PhpSpreadsheet/IOFactory.php:184

4. PhpOffice\PhpSpreadsheet\Reader\Xlsx->canRead() /var/www/html/alchemy/calculadora/PhpSpreadsheet-develop/src/PhpSpreadsheet/IOFactory.php:270 

```

**Comment by PowerKiKi** [comment]
Install and configure php-zip correctly to get rid the exception

**Comment by fastrer** [comment]
how can i do that?

**Comment by PowerKiKi** [comment]
On Ubuntu, try something like `sudo phpenmod zip`, or else google for how to configure PHP in general. The `var_dump()` mentioned earlier must return true.

**Comment by afilina** [comment]
`extension_loaded('zip')` should be checked by the library and a more appropriate error message should be sent to the user. Otherwise, I suspect that people will keep asking the same question. It's in the composer file, but for some reason I got zero warnings when adding this package.

**Comment by PowerKiKi** [comment]
It's not a warning but an error. And if you didn't get it, then it means that you run composer and your code with a different PHP environment. Typically you should double check that PHP for CLI has the same (or compatible) configuration as PHP for apache/nginx.

**Comment by afilina** [comment]
@PowerKiKi Good point. I may have made a mistake in that regard.

**Comment by ClarityMedia** [comment]
FWIW, in a "f***ing duh" moment, I got the same error and realized that I hadn't actually restarted Apache after installing the zip archive.  OP didn't note if they did that or not, but any installation of new PHP extensions will require an Apache restart to enable them.  Hope that helps someone else.

**Comment by dpchami** [comment]
@ClarityMedia you helped me sir

**Comment by roel018** [comment]
Hi! I'm getting the same **Class 'ZipStream\Option\Archive' not found** error, however, I have in fact installed the ZIP extension. This is actually working fine:

var_dump(extension_loaded('zip')); 

...this produces **bool(true)**

When I use ZipArchive in my extensions myself, however, I always need to use \ZipArchive (with the backslash). Otherwise, it won't find it. How can I solve this without needing to adjust all ZipArchive occurences in PhpSpreadSheet to \ZipArchive ? Thanks!
