### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 18874368 bytes) in PhpSpreadsheet/Collection/Memory.php on line 66

### ISSUE THREAD

**Issue by qidizi** [PHPOffice/PhpSpreadsheet#1600]
This is a bug report    

### What is the expected behavior?
load normal     

### What is the current behavior?
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 18874368 bytes) in PhpSpreadsheet/Collection/Memory.php on line 66    

![image](https://user-images.githubusercontent.com/3324382/88655639-9d276a80-d101-11ea-892d-38d36a21e48a.png)
    
### What are the steps to reproduce?

load [test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/4987679/test.xlsx)   
will trigger this error   with the code      

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...


if ('xlsx' === $ext) {
            $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
        } elseif ('xls' === $ext) {
            $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xls();
        } else
            throw new Exception('仅支持xls或xlsx文件');


        $reader->setReadDataOnly(1);// 是否考虑格式,经过测试,大概增加一半的时间;如果不考虑,日期像 2019-05-03 会变成 数字
        $spreadsheet = $reader->load($excel_path);
```

### Which versions of PhpSpreadsheet and PHP are affected?    

php7.2    
PhpSpreadsheet 1.4.1      

The cause of the problem may be similar to this one [#1529](1529).     
 If so, can add an option that, when enabled, can intelligently judge that after enough blanks are reached, larger columns or rows are no longer read?    
thank you.

**Comment by nvcken** [comment]
Hi @qidizi How can you capture memory usage as the screenshot? looks cool

**Comment by qidizi** [comment]
xdebug

**Comment by ajpgtech** [comment]
try this workaround

        $writer = new Xlsx($outputSpreadsheet);
        $writer->setPreCalculateFormulas(false);
        $writer->save($outFileName);

**Comment by oleibman** [comment]
File is huge (worksheet is 46MB packed to 6MB), consisting almost entirely of empty cells (style was applied to all which is why they all appear in worksheet Xml. It can be read without a memory problem using:
```php
$reader->setReadDataOnly(true);
$reader->setReadEmptyCells(false);
```
