### ISSUE TITLE
It seems not posible to see the data labels en each marker in a line chart

### ISSUE THREAD

**Issue by hguzmang** [PHPOffice/PhpSpreadsheet#1603]
This is a feature request
### What is the expected behavior?
To have an easy option to see the data labels en each marker in a line chart

### What is the current behavior?
It seems not posible to see the data labels en each marker in a line chart

### What are the steps to reproduce?
Use the sample 33 in this GitHub account

Piece of code:
$dataSeriesValues = [
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$B$2:$B$5', null, 4),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$C$2:$C$5', null, 4),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$D$2:$D$5', null, 4),
        ];
        $dataSeriesValues[2]->setLineWidth(60000);

        // Build the dataseries
        $series = new DataSeries(
            DataSeries::TYPE_LINECHART, // plotType
            DataSeries::GROUPING_STACKED, // plotGrouping
            range(0, count($dataSeriesValues) - 1), // plotOrder
            $dataSeriesLabels, // plotLabel
            $xAxisTickValues, // plotCategory
            $dataSeriesValues,        // plotValues
            null, //plotDirection
            false, //smoothLine
            DataSeries::STYLE_MARKER //plotStyle
        );

**Comment by oleibman** [comment]
Labels now seem visible when hovering over any marker for 33_chart_create_line.
