### ISSUE TITLE
setter method for potentialDelimiters

### ISSUE THREAD

**Issue by boiangeorgiev** [PHPOffice/PhpSpreadsheet#1604]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### New setter method for potentialDelimiters

Given the following (very awkwardly crafted text) file:
```
https://www.example1.com/ item:1
https://www.example2.com/ item:2
http://www.example3.com/blog/ item:3
http://example4.com/ item:4
https://example5.com/ item:5
https://www.example6.com/ item:6
https://example7.com/home item:7
https://www.example8.com item:8
https://www.example9.com/ item:9
http://example10.com/ item:10
http://www.example11.com/ item:11
https://www.example7.com/ item:12
```

The guessed delimiter is ":" (a colon), which is correct as per current code (it is most evenly distributed).
Unfortunately because of this, the entities are split to: "https", "//www.example1.com/ item" and "1" for row 1 and so on.

It would be very convenient to have a method to control the potential delimiters the same way we can set a specific delimiter.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: v1.14.1
PHP: v7.2.32

**Comment by MarkBaker** [comment]
Is there some problem with using the CSV Reader's `setDelimiter()` method?

**Comment by oleibman** [comment]
Reopening because I think this deserves an answer, but I am skeptical. The method would be easy to implement, but I don't understand the use case. Sure, the sample supplied makes it clear what shouldn't be used as a delimiter (colon); but it's equally clear what should be used (space). What is the use case for knowing what shouldn't be used without knowing what should be? I'll leave this open for a couple of months to give the opportunity to respond?

**Comment by boiangeorgiev** [comment]
I agree with you that already knowing that "it is not working out of the box for my file so I need to specify to skip the colon as a delimiter" really implies also "I already know the content of that particular file so I will just force it to use the space as delimiter". Perhaps I was just wanting it to still be generic and not specifically setting the delimiter just because, yet deliberately removing the colon from the optional ones. This was long ago and the real use case has faded away. Since nobody else is in need of such feature, I suppose it can be closed. Thank you for your collaboration! :)

**Comment by oleibman** [comment]
@boiangeorgiev Thank you for responding. Closing, as you recommended.
