### ISSUE TITLE
`formatAsDate` does not strip language metadata

### ISSUE THREAD

**Issue by SheetJSDev** [PHPOffice/PhpSpreadsheet#1616]
[`formatAsDate`](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Style/NumberFormat.php#L472) attempts to strip language metadata but has a few issues.

The attached [chinesedate.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/5081214/chinesedate.xlsx) uses the format code `[$-zh-CN]dddd`.  The current regular expression does not strip it (it only matches one hyphen)

[From the XLSX spec](https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oi29500/17d11129-219b-4e2c-88db-45844d21e528):

```
NFPartLocaleID =
    ASCII-LEFT-SQUARE-BRACKET
    ASCII-DOLLAR-SIGN
    1*UTF16-ANY
    [ASCII-HYPHEN-MINUS 3*8ASCII-DIGIT-HEXADECIMAL]
    ASCII-RIGHT-SQUARE-BRACKET
```

Ignoring the obvious issue (UTF16-ANY should be UTF16-ANY-WITHOUT-RIGHT-SQUARE-BRACKET), and noting that the `DBNum` specifier is of the form `\[DBNum\d\]`, the line probably should be something like:

```php
        $format = preg_replace('/^(\[DBNum\d\])*(\[\$[^\]]*\])/i', '', $format);
```

Note: This was originally left as a comment in [another issue](https://github.com/PHPOffice/PhpSpreadsheet/issues/140#issuecomment-554332866) since @cocowool 's contribution introduced the bug.

**Comment by oleibman** [comment]
Fixed by PR #1618.
