### ISSUE TITLE
Pie chart is not visible with MS Office but works with Apache and libreoffice

### ISSUE THREAD

**Issue by anurag-acco** [PHPOffice/PhpSpreadsheet#1621]
This is:

```
- [* ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
i was trying to generate a piechart and thus cloned the chart samples form the repo. The generated chart works fine with excel but when opening with MS Office it opens file in read only and does not show chart 
[spreadsheet_example.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/5107109/spreadsheet_example.xlsx)

the link i am using https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Chart/33_Chart_create_pie.php
### Which versions of PhpSpreadsheet and PHP are affected?
i am using latest version of PhpSpreadsheet with php 7.3

**Comment by tomours** [comment]
The charts also don't open correctly with Open Office (probably the same problem).
For example : 
- Libre Office (works fine) :
![Capture d’écran du 2020-08-26 10-24-31](https://user-images.githubusercontent.com/4772473/91291943-1ca66900-e796-11ea-8109-5f7b8663fdbb.png)

- Open Office (doesn't work but does not exactly shows the same output as with Microsoft Office) :
![image2](https://user-images.githubusercontent.com/4772473/91291674-b28dc400-e795-11ea-8329-74ff438dbb16.png)

**Comment by pratikus** [comment]
I have pre-formatted charts in an excel file (.xlsx) saved on the server. I used PHPSpreadsheet to read this file and then wrote data on teh file (that populates the pre-formatted charts). However, the charts work only on Libre Office and Open Office, they do not work on MS office.

**Comment by aymeric-gerip** [comment]
I had the same issue and just found how to resolved it.
If you take this exmaple https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Chart/33_Chart_create_pie.php
You need at one moment to configure $dataSeriesLabels, $xAxisTickValues, $dataSeriesValues as below

![image](https://user-images.githubusercontent.com/68116386/128333156-5cd75ca5-e1b2-4615-b87c-af9553aa407f.png)

And finally the extracttion is like this
![image](https://user-images.githubusercontent.com/68116386/128333467-0aae099c-39b8-4dea-b996-1a80506c6e9f.png)

So i watched in the generated excel what was the data and it's look like this:
![image](https://user-images.githubusercontent.com/68116386/128333599-8c935834-d00f-4323-ac3e-759eb277b4df.png)

Finally i understood, MS excel doesn't like Worksheet and work with the name of your page and finally it's work

![image](https://user-images.githubusercontent.com/68116386/128333885-1202cee2-c3e1-4103-b5bf-771166024bb7.png)

![image](https://user-images.githubusercontent.com/68116386/128333929-52b3379e-749b-449d-9193-968cec4cfda7.png)

**Comment by StevenRenaux** [comment]
I had the same issue with MS Excel. It's working on Libre Ofice.

If you follow the example code (https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Chart/33_Chart_create_pie.php) to configure your chart. At one moment you need to configure some plotLabel ($dataSeriesLabels), plotCategory ($xAxisTickValues) and plotValues ($dataSeriesValues)

![image](https://user-images.githubusercontent.com/59167761/128334626-74c21071-5a4b-4bbd-8644-b10c2b4848e6.png)

And it's not working. But if you go to this generated excel and have a look on the data selected to made the chart you can see this.

![image](https://user-images.githubusercontent.com/59167761/128334879-79000316-3f06-4bbf-9c7c-87b2dc7b56bb.png)

Unfortunately MS Excel doesn't understand the value Worsheet so i just changed it and he understand finally with the title/name of your page.

![image](https://user-images.githubusercontent.com/59167761/128335177-c3de06c9-fd5a-4759-bdb5-ae11c74db615.png)

![image](https://user-images.githubusercontent.com/59167761/128335279-d3e1866a-4361-4c4e-8d70-308ca0b9fc45.png)

**Comment by MarinaWagih** [comment]
Issue still happens charts are correctly show in Linux and charts are empty in Microsoft Office Excel
this file is example for the issue
[chart (61).xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8893021/chart.61.xlsx)
 this is an example of code used
 `

          use Maatwebsite\Excel\Concerns\FromView;
          use Maatwebsite\Excel\Concerns\WithCharts;
          use Maatwebsite\Excel\Concerns\WithTitle;
          use PhpOffice\PhpSpreadsheet\Chart\Axis;
          use PhpOffice\PhpSpreadsheet\Chart\Chart;
          use PhpOffice\PhpSpreadsheet\Chart\DataSeries;
          use PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues;
          use PhpOffice\PhpSpreadsheet\Chart\Legend;
          use PhpOffice\PhpSpreadsheet\Chart\PlotArea;
          use PhpOffice\PhpSpreadsheet\Chart\Title;
          use PhpOffice\PhpSpreadsheet\IOFactory;
          use PhpOffice\PhpSpreadsheet\Spreadsheet;

          class RearingChartExport implements WithCharts ,WithTitle ,FromView
          {
 
              public function charts(){
                  $spreadsheet = new Spreadsheet();
                  $worksheet=$spreadsheet->getActiveSheet();
                   //Our data here
                  $cycle_data=[......];
                  $chartData=[];
                  foreach($cycle_data as $weeklyData){
                              //chart data
                                $chartData[]=[ ];
                  }
                  $worksheet->fromArray($chartData);
                  $dataSeriesLabels = [
                      new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$B$1', null, 1), 
                      new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$C$1', null, 1),
                      new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$D$1', null, 1),
                      new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$E$1', null, 1),
                      new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$F$1', null, 1),
                      new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$G$1', null, 1),
                  ];

        $xAxisTickValues = [
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$A$2:$A$23', null, 4), 
        ];
        $dataSeriesValues = [
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$B$2:$B$23',  null, null,[],"none"),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$C$2:$C$23', null, null,[],"none"),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$D$2:$D$23',  null, null,[],"none"),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$E$2:$E$23', null, null,[],"none"),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$F$2:$F$23', null, null,[],"none"),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$G$2:$G$23', null, null,[],"none"),

        ];
        // Build the dataseries
        $series = new DataSeries(
            DataSeries::TYPE_LINECHART, // plotType
            null, // plotGrouping (Scatter charts don't have any grouping)
            range(0, count($dataSeriesValues) - 1), // plotOrder
            $dataSeriesLabels, // plotLabel
            $xAxisTickValues, // plotCategory
            $dataSeriesValues, // plotValues
            null, // plotDirection
            true, // smooth line
            DataSeries::STYLE_LINEMARKER  // plotStyle
        );
        // Set the series in the plot area
        $plotArea = new PlotArea(null, [$series]);
        // Set the chart legend
        $legend = new Legend(Legend::POSITION_BOTTOM, null, false);
        $title = new Title('Rearing');
        $yAxisLabel = new Title('weight (g)');
        $xAxisLabel = new Title('Weeks');
        $xAxis =  new Axis();
        $xAxis->setAxisOptionsProperties(
            Axis::AXIS_LABELS_NEXT_TO,
            null,
            null,
            null,
            Axis::TICK_MARK_CROSS,
            null,
            1,  // minimum
            22, // maximum
            1  // major unit
        );

        $yAxis = new Axis();
        $yAxis->setAxisOptionsProperties(
            Axis::AXIS_LABELS_NEXT_TO,
            null,
            null,
            null,
            null,
            null,
            0,  // minimum
            4000, // maximum
            200  // major unit
        );

        // Create the chart
        $chart = new Chart(
            'feed chart', // name
            $title, // title
            $legend, // legend
            $plotArea, // plotArea
            true, // plotVisibleOnly
            DataSeries::EMPTY_AS_GAP, // displayBlanksAs
            $xAxisLabel, // xAxisLabel
            $yAxisLabel,  // yAxisLabel
            $xAxis, //x axis
            $yAxis
        );

        $chart->setTopLeftPosition('A1');
        $chart->setBottomRightPosition('O20');

        // Add the chart to the worksheet

        $worksheet->addChart($chart);

        // feeding Chart
        $feeddataSeriesLabels = [
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$H$1', null, 1), // 2010
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$I$1', null, 1), // 2011
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$J$1', null, 1),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$K$1', null, 1),
        ];

        $feedxAxisTickValues = [
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$A$2:$A$23', null, 4), // Q1 to Q4
        ];
        $feeddataSeriesValues = [
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$H$2:$H$23', null, null,[],"none"),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$I$2:$I$23',  null, null,[],"none"),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$J$2:$J$23',  null, null,[],"none"),
            new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$K$2:$K$23',  null, null,[],"none"),
        ];

        $feedseries = new DataSeries(
            DataSeries::TYPE_LINECHART, // plotType
            null, // plotGrouping (Scatter charts don't have any grouping)
            range(0, count($feeddataSeriesValues) - 1), // plotOrder
            $feeddataSeriesLabels, // plotLabel
            $feedxAxisTickValues, // plotCategory
            $feeddataSeriesValues, // plotValues
            null, // plotDirection
            true, // smooth line
            DataSeries::STYLE_LINEMARKER  // plotStyle
        );
        // Set the series in the plot area
        $feedplotArea = new PlotArea(null, [$feedseries]);
        // Set the chart legend
        $feedlegend = new Legend(Legend::POSITION_BOTTOM, null, false);
        $feedtitle = new Title('Rearing (feed)');
        $feedingyAxis = new Axis();
        $feedingyAxis->setAxisOptionsProperties(
            Axis::AXIS_LABELS_NEXT_TO,
            null,
            null,
            null,
            null,
            null,
            20,  // minimum
            130, // maximum
            10  // major unit
        );
        // Create the chart
        $feeding_chart = new Chart(
            'feed chart', // name
            $feedtitle, // title
            $feedlegend, // legend
            $feedplotArea, // plotArea
            true, // plotVisibleOnly
            DataSeries::EMPTY_AS_GAP, // displayBlanksAs
            $xAxisLabel, // xAxisLabel
            $yAxisLabel,  // yAxisLabel
            $xAxis, //x axis
            $feedingyAxis
        );

        $feeding_chart->setTopLeftPosition('A33');
        $feeding_chart->setBottomRightPosition('O53');

        // Add the chart to the worksheet

        $worksheet->addChart($feeding_chart);


        // Save Excel 2007 file
        $filename = trans('base.inputs.chart');
        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        $writer->setIncludeCharts(true);
        $writer->save($filename);
        return [$chart,$feeding_chart];
    }

    public function view(): View
    {
      //return view
    }
    public function title(): string
    {
        return trans('base.sections.rearing_chart');
    }
    }`

**Comment by oleibman** [comment]
It is not a mystery to me that the charts don't work in Excel; what I don't understand is why they do work in LibreOffice. The data series all point to an invalid worksheet named `Worksheet`, which is not part of the file; that is why Excel doesn't display anything in the charts. If you change your code to use the correct worksheet name, what happens? For example,
```php
              $dataSeriesLabels = [
                  new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, '\'Production data\'!$B$1', null, 1), 
                 ...
              ];
```
This is essentially what @StevenRenaux suggested earlier in this thread. I assume there are some places where you should be using `Rearing data` rather than `Production data`, and possibly other sheet names are needed in places.

**Comment by MarinaWagih** [comment]
from previous comments I noticed that `$worksheet->fromArray(.....);` doesn't work as expected in excel the data should always be present in the sheets and that's why Libra office can view the data & excel

**Comment by MarkBaker** [comment]
> from previous comments I noticed that `$worksheet->fromArray(.....);` doesn't work as expected
>
Can you please explain? In what way doesn't `fromArray()` work? If there is an issue with `fromArray()` then it should be raised as such, not simply mentioned without any clarification or explanation in an issue related to charts.

**Comment by MarkBaker** [comment]
> from my understanding $worksheet->fromArray(.....); should allow me to add a chart data series without the need to actually add the data into a sheet .

The whole point of the `fromArray()` Worksheet method is that it's adding data from an array to a worksheet; it has no direct connection with a chart at all... a chart may retrieve data from that worksheet, but `fromArray()` simply populates a worksheet with data, and doesn't care what happens to the data after that.
And there's no such thing as "virtual sheets": a worksheet either exists or it doesn't

What I'm having problems understanding is "doesn't work as expected", so I'm trying to understand what your expectation of `fromArray()` is, and where you got that expectation.

**Comment by oleibman** [comment]
Closing, no update in 7 months, no reason to think suggestions don't solve problem.
