### ISSUE TITLE
getFormattedValue() returns 0 for spreadsheet with complicated calculations involving VLOOKUP

### ISSUE THREAD

**Issue by JeyjooMilano** [PHPOffice/PhpSpreadsheet#1624]
This is:

```
- [ ] a bug report
```

### What is the expected behavior?
getFormattedValue() and getCalculatedValue() should return a whole number

### What is the current behavior?
getCalculatedValue(), getFormattedValue() both return 0 for complicated excel calculations that use conditional lookups.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object

// add code that show the issue here...
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load("Lookup.xlsx"); // Simplified version of spreadsheet attached. Exhibits the problem
$sheet = $spreadsheet->getActiveSheet();

$v = $sheet->getCell('A5')->getValue();
$fv = $sheet->getCell('A5')->getFormattedValue();
$cv = $sheet->getCell('A5')->getCalculatedValue();

echo "getValue: ".$v;// =ROUND(VLOOKUP(A4,IF($A$2<55,$B$1:$I$4,$B$5:$I$8),$A$1+1,0)*$A$3/1000,2)
echo "<br>getFormattedValue: ".$fv;// 0
echo "<br>getCalculatedValue: ".$fv;// 0
```
[Lookup.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/5119380/Lookup.xlsx)

### Which versions of PhpSpreadsheet and PHP are affected?
Problem observed using PhpSpreadsheet 1.14.1 and PHP 7.3

**Comment by oleibman** [comment]
Code sample above now returns same result as Excel, 931.4. Closing ticket.
