### ISSUE TITLE
Error T_VARIABLE

### ISSUE THREAD

**Issue by azzahrah** [PHPOffice/PhpSpreadsheet#1633]
TParse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/xxx/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Spreadsheet.php on line 902

howto solve this problem?

**Comment by tristanleboss** [comment]
Update your PHP version to 7.1 minimum

**Comment by swat2702** [comment]
I'm already having php version 7.3 

Type: ParseError
Message: syntax error, unexpected '?', expecting variable (T_VARIABLE)
Filename: /home/xxx/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Html.php

please help to solve this

**Comment by MarkBaker** [comment]
If you're running your code from the CLI, then check our version.... CLI and Web could be running different versions of PHP
