### ISSUE TITLE
Saving XLSX unhides every row

### ISSUE THREAD

**Issue by wyattGTL** [PHPOffice/PhpSpreadsheet#1641]
```
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment;filename=$fileName");
header("Cache-Control: max-age=0");
$writer->save('php://output');
```

All of the rows get un-hidden when exporting like that. I've verified that the rows are in fact hidden in the original file. 
How can I fix this?

**Comment by wyattGTL** [comment]
I am using version 1.14

**Comment by wyattGTL** [comment]
Just realized it only happens with some files. Here is a file that is happens with.
[libre.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/5179675/libre.xlsx)

**Comment by wyattGTL** [comment]
Rows 2 and 5 will not be hidden after exporting the file with the above code.

**Comment by wyattGTL** [comment]
Before saving the file, I get the row dimensions and verify that the rows are in fact hidden. Something is going wrong in the saving with this specific file. I would appreciate any help, I'm in a bit of a time crunch unfortunately.

**Comment by oleibman** [comment]
The worksheet includes autofilters, and Excel autofilters will find *and display* previously hidden rows if they satisfy the filter. PhpSpreadsheet evaluates autofilters when writing, which is leading to your problem. I'm not sure that it's practical to change this behavior - it would represent a breaking change for many programs which currently execute as expected.
