### ISSUE TITLE
getValue() modifies numbers.

### ISSUE THREAD

**Issue by ceckobecko** [PHPOffice/PhpSpreadsheet#1644]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
We are hitting a nasty bug with the library.
It modifies number even when the format of the cell is a "string".

### What is the expected behavior?
I'm expecting the value of the cell to be the same when read. The example here is with "999999999999999".

### What is the current behavior?
The retrieved value is not equal to the value given in the spreadsheet - "1000000000000000"

### What are the steps to reproduce?
This is the minimum valuable script to reproduce the problem
```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$path = './excel-test.xlsx';
$objReader = PhpOffice\PhpSpreadsheet\IOFactory::createReader(PhpOffice\PhpSpreadsheet\IOFactory::identify($path));
$objPHPExcel = $objReader->load($path);
assert(999999999999999 === $objPHPExcel->getActiveSheet()->getCell('A1')->getValue());
```

[excel-test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/5195162/excel-test.xlsx)

### Which versions of PhpSpreadsheet and PHP are affected?
* PHP 7.4.9 (cli) (built: Aug  7 2020 19:23:06) ( NTS ).
* PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )
* Library Version - 1.14.1

**Comment by MarkBaker** [comment]
2,147,483,647 is the maximum value for a 32-bit signed integer; so if you're running PHPSpreadsheet using 32-bit PHP then the value 999,999,999,999,999 will be converted to a float; which can cause precision/rounding problems
