### ISSUE TITLE
Missing header image when opening an excel file an saving it

### ISSUE THREAD

**Issue by Raemy92** [PHPOffice/PhpSpreadsheet#1645]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

I'm using this library on a TYPO3 installation to create excel order sheets from some articles. Everything works like a charm but the image in the header disappears.

I'm using a tamplate .xlsx file with the headers (image and some text) included, insert the articles with this library and save it to another path.

When I'm opening the file the header text and the articles are correctly saved but no the header image.

### What is the expected behavior?
The same header as in the template file (image and text)

### What is the current behavior?
Only the header text appears. The image on the header left is missing.

### What are the steps to reproduce?
1. Load the Excel template
```php
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($this->pathToTemplate);
```

2. Make some changes (in my case add the articles). I used a loop with something similar to this:
```php
$spreadsheet->getActiveSheet()->setCellValue($cell, $text);
```

3. Save the File in another path because the template is used multiple times
```php
$writer = new Xlsx($spreadsheet);
$writer->save($savePath);
```

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

See code above.

I also tried to insert the image manually:

```php
$drawing = new HeaderFooterDrawing();
$drawing->setName('Logo');
$drawing->setPath($pathToImage);
$drawing->setHeight(90);
$spreadsheet->getActiveSheet()->getHeaderFooter()->addImage($drawing, \PhpOffice\PhpSpreadsheet\Worksheet\HeaderFooter::IMAGE_HEADER_LEFT);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHPSpreadSheet: 1.14
PHP: 7.2

**Comment by k7y6t5** [comment]
@Raemy92 I haven't tried working with a template that already contains a header image but I have tried to insert one manually. It's not working for me either.

https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#setting-the-print-header-and-footer-of-a-worksheet

PHPSpreadsheet 1.8
PHP 7.4.9

**Comment by oleibman** [comment]
Closing. I believe this issue is resolved. For example, if I load tests/data/Reader/XLSX/issue.3126.xlsx and save it elsewhere, the output file contains the same footer image as the input file. The same is true when I add a header image as well.
