### ISSUE TITLE
[BUG] Illegal character causing wrong rows count when Importing txt file

### ISSUE THREAD

**Issue by oseintow** [PHPOffice/PhpSpreadsheet#1648]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

So I’m trying to import a txt file. Sample content of the file below.

```
id|name|address|account_number
1|John|box 4|101
2|Doe|spring’s ave|104
3|Baz|spring”s quarters|105
4|Foo|‘box 4|102
5|Bar|“box 5|103
6|Baz|street 1|106
7|Baz|street 2|107
```

Now the issue I’m facing is when I have `'`  or `"` at the beginning of a cell’s/column’s value eg `'box 4` or  `"box 5` it causes the rows count to break.
What I realized is It merges the subsequent rows to that cell.

Using `'enclosure' => "'"`, or `'enclosure' => '"'`,  causes  `'box 4`  or `"box 5` to break respectively.

### What is the expected behavior?
Row count should be 7. $row[3]['address'] should be `'box 4`.

### What is the current behavior?
Row count is 4. And row[3]['addresss'] is `‘box 4|102
5|Bar|“box 5|103
6|Baz|street 1|106
7|Baz|street 2|107`

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

create a txt file with some of the fields having a single quote(') and/or double quote(") at the beginning of the values. eg `'John Doe` or `"John Doe` with `|` as the delimiter. 

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: `^1.11`
PHP: `7.2`

**Comment by oleibman** [comment]
The behavior you are describing is not a bug - it is how CSV's work. Excel will read the file exactly the same way. That being said, you have the option of setting the enclosure value to a character which you know will not be present in your file, e.g. a null character: `"\x00"`. This should produce the result you are looking for.
