### ISSUE TITLE
fail to set autoheight for merged cell.

### ISSUE THREAD

**Issue by LF00** [PHPOffice/PhpSpreadsheet#1651]
`setWrapText` not works for merged cell, have has no effect.

```
$sheet = $spreadsheet->getActiveSheet();
$sheet->fromArray([["1\n1\n2\n\n3\n"],range(1,3),['188196','test']]);
$sheet->mergeCells('A1:D1');
$sheet->getStyle("A1:D1")->getAlignment()->setWrapText(true);
```

And I have questioned on StackOverflow with more detail.
[SO: Phpspreadsheet how to set autoheight for merged cell?](https://stackoverflow.com/q/63858786/6521116)

**Comment by oleibman** [comment]
Excel does not allow autoheight or wraptext for a merged cell - see https://support.microsoft.com/en-us/topic/you-cannot-use-the-autofit-feature-for-rows-or-columns-that-contain-merged-cells-in-excel-34b54dd7-9bfc-6c8f-5ee3-2715d7db4353
