### ISSUE TITLE
MemoryDrawing pdf export failure

### ISSUE THREAD

**Issue by theplayer2k3** [PHPOffice/PhpSpreadsheet#1652]
This is:

```
- [ X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

This is my first report of a problem in an OpenSource project. I hope i do it right ;-)

### What is the expected behavior?
Image should be included as base64 png image in HTML redering for PDF export. The img tag renders src="data:image/png;base64,BASE64DATA"

### What is the current behavior?
The img tag renders src="data:image/jpeg;base64,BASE64DATA"

### What are the steps to reproduce?
create a Spreadsheet with an MemoryImage and safe as PDF

### Which versions of PhpSpreadsheet and PHP are affected?
I don't know it's still in the source of the actual version

I've already looked for the file where the failure happens and found a solution.

PhpSpreadsheet/Writer/Html.php:699
$dataUri = 'data:image/jpeg;base64,' . base64_encode($contents);

change to:
$dataUri = 'data:image/png;base64,' . base64_encode($contents);

line 695 you see that there is a png is generated
imagepng($drawing->getImageResource()); //  This will normally output the image, but because of ob_start(), it won't.

**Comment by oleibman** [comment]
The correction from image/jpeg to image/png was made in PR #2788. Closing this issue.
