### ISSUE TITLE
Contains pictures

### ISSUE THREAD

**Issue by zddapi** [PHPOffice/PhpSpreadsheet#1653]
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, "Xlsx");
$writer->save($inputFileName);

Anything that includes an image is an error!

![7){J)D$T_RXTNAX43RQLP7L](https://user-images.githubusercontent.com/29446786/93563844-44ff3d00-f9bb-11ea-85f4-2142d4808f69.png)

**Comment by oleibman** [comment]
Closing. No update in 3 years. The statement "anything that includes an image is an error" is not true; our unit test suite contains much image handling. Please open a new issue  if you still have a specific example of the problem reported in this issue.
