### ISSUE TITLE
Issue when saving xlsm, Macros gone

### ISSUE THREAD

**Issue by leanesanity** [PHPOffice/PhpSpreadsheet#1657]
Using this library I am able to read my xlsm file and update the file but in the saving of the file, I encounter an issue... It erases the macros on my file. Is there a way to retain the micros when saving ?

Code Below:

        $download_file_name = $data['file_name'];
        $file_path = storage_path("app/{$data['connection']}/bankexporttemplate.xlsm");
        $spreadsheet = IOFactory::load($file_path);
        $worksheet = $spreadsheet->getActiveSheet();
        $worksheet->setCellValue('D2', 'Company');
        $worksheet->setCellValue('D4', 'Ph');
        $writer = IOFactory::createWriter($spreadsheet, "Xlsx");
        $saveFile = (storage_path("app/{$data['connection']}/{$download_file_name}.xlsm"));
        $writer->save($saveFile);
        return Response::download($saveFile); // OUTPUT FILE HAVE NO MACROS

**Comment by Collie-IT** [comment]
Because of that macros are not supported the macros will not save while regenerating the file.

**Comment by leanesanity** [comment]
Is there any way to retain the macros by default ?

![image](https://user-images.githubusercontent.com/39898232/94232950-a97d4780-ff39-11ea-9083-30da8abb4684.png)

**Comment by jamesfraser** [comment]
@leanesanity I'm doing something quite similar, using version 1.14.1 and the macros are being retained in the output.
The only difference for my code is that I'm using `Reader\Xlsx->load()` instead of `IOFactory::load()`

```
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;
use PhpOffice\PhpSpreadsheet\IOFactory;

$spreadsheet = new Xlsx();
$spreadsheet->load( $xlsm_path );

// Modify sheets here

$writer = IOFactory::createWriter($spreadsheet, "Xlsx");
$update_file = "test.xlsm";
$writer->save( $updated_file );
```

**Comment by oleibman** [comment]
Closing. As noted above, macros are, for better or worse, saved. Tested in Writer/Xlsx/UnparsedDataTest.
