### ISSUE TITLE
Corrupted File when using hyperlinks for more than 32767 rows

### ISSUE THREAD

**Issue by Wazzledi** [PHPOffice/PhpSpreadsheet#1667]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When creating a Spreadsheet with Hyperlinks the Links should be inserted as a hypertext URL and the file should not be corrupt.

### What is the current behavior?
With more than 32766 Rows and 2 Columns the created File is corrupt and all Hyperlinks gets removed after repairing it in Excel.
For my tests the limit for the rows was 32767 where the error occured.

### What are the steps to reproduce?

1. Run the code below
2. Open Excel File and the error Message appears

```php
<?php
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Cell\DataType;

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$columns = array (
				"A",
				"B"
);

//Limit where error occurs is 32767. No error for 32766
for( $i = 1; $i < 32767; $i ++ )
{
	foreach ( $columns as $column )
	{
		$currentCell = $sheet->getCell( $column . $i );
		$currentCell->setValueExplicit( "http://google.de", DataType::TYPE_STRING );
		$sheet->getCell( $column . $i )->getHyperlink()->setUrl( "http://google.de" );
	}
}

//Write to file
//Occures also for XLS Files
$writer = new Xlsx($spreadsheet);
$writer->save("test.xlsx");
```

### Which versions of PhpSpreadsheet and PHP are affected?
Used PHP Version: 7.4.10 but tested also with 7.2.5 <br>
Used PhpSpreadsheet Version: 1.14.1

**Comment by ResetButton** [comment]
Same problem
File with hyperlinks is corrupted

**Comment by MarkBaker** [comment]
There is a limit to the number of hyperlinks you can have in one Excel Worksheet. It can be up to 66,530 hyperlinks in a file. This is not a PHPSpreadsheet limit (we don't check how man hyperlinks you create): this is an MS Excel limit.

[Reference](https://support.microsoft.com/en-gb/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3)

**Comment by Wazzledi** [comment]
Ok Thank you. 
Then this is not relevant anymore
