### ISSUE TITLE
IOFactory::load emits errors instead of throwing exceptions

### ISSUE THREAD

**Issue by FinesseRus** [PHPOffice/PhpSpreadsheet#167]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?

`PhpOffice\PhpSpreadsheet\IOFactory::load` throws an `PhpOffice\PhpSpreadsheet\Reader\Exception` exception when it gets a file which it can't read. According to [the documentation](https://phpspreadsheet.readthedocs.io/en/develop/topics/reading-files/#error-handling), exception must be thrown in case of problems.

Or at least I can suppress errors by placing the `@` operator before calling the `load` method.

### What is the current behavior?

When I run the script via a web server, the script just stops (browser says that the connection has been broken by the server).

When I run the script via a console, `IOFactory::load` emits errors which are not catchable by try-catch:

* PHP 7.0: `zend_mm_heap corrupted`
* PHP 7.1: `Segmentation fault: 11`

Placing the `@` operator before calling `IOFactory::load` changes nothing.

### What are the steps to reproduce?

1. Download this file ([file.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/1043743/file.zip)) and put it near the script below.
2. Run the script:
    ```php
    <?php
    
    require __DIR__ . '/vendor/autoload.php';
    
    try {
        $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load(__DIR__.'/file.zip');
        echo 'Your file is good.';
    } catch (\Exception $e) {
        echo 'Your file is wrong!';
    }
    ```

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet 1.0.0-beta1 – 1.1.0. PHP 7.0.15, 7.1.1 (didn't test it in other versions). I run it on macOS 10.13.3.

**Comment by FinesseRus** [comment]
I've found that the code on the line 363 in the file `src/PhpSpreadsheet/Shared/StringHelper.php` makes the script exit without a chance to handle error:

```php
$value = @iconv('UTF-8', 'UTF-8', $value);
```

**Comment by FinesseRus** [comment]
The problem can be solved by removing this block:

```php
if (self::getIsIconvEnabled()) {
    $value = @iconv('UTF-8', 'UTF-8', $value);

    return $value;
}
```

I don't know if it is a good solution.

**Comment by PowerKiKi** [comment]
Could you investigate whether one of [those answers](https://stackoverflow.com/questions/1307275/simplexml-error-handling-php) helped in your case ?

**Comment by FinesseRus** [comment]
@PowerKiKi, unfortunately I can't reproduce the `simplexml_load_string` errors. But I still face the problem below when I reproduce the «how to reproduce» example above:

> I've found that the code on the line 363 in the file src/PhpSpreadsheet/Shared/StringHelper.php makes the script exit without a chance to handle error:
> ```php
> $value = @iconv('UTF-8', 'UTF-8', $value);
> ```

**Update.** I've just succeed to reproduce the `simplexml_load_string ` errors by removing the `@` symbol from the `StringHelper::sanitizeUTF8` code. When I added `libxml_use_internal_errors(true);` to the code, and got the same error from which I started (the script just stops, browser says that the connection has been broken by the server).

**Comment by FinesseRus** [comment]
The issue is still actual for 1.0.0-beta2, but the error message changed.

**Comment by FinesseRus** [comment]
This issue is still actual for version 1.1.0 😕

**Comment by PowerKiKi** [comment]
I actually cannot reproduce the zend_mm_heap or Segmentation fault. This is most likely a bug in PHP itself or one of its extension. And there is not much we can do.

What could be done though, is to prevent the CSV reader to accept any file. We should ideally only accept CSV files. Maybe via mimetype detection if that proves to be reliable enough on CSV files. But that should be tested.

**Comment by FinesseRus** [comment]
@PowerKiKi I don't have any extension, I use pure PHPs from [MAMP](https://www.mamp.info). I will make a Travis CI demo soon.

**Comment by FinesseRus** [comment]
@PowerKiKi Unfortunately, Travis CI can't test PHP on macOS ([i tried](https://travis-ci.org/PHPOffice/PhpSpreadsheet/builds/353276366)).

I run the tests on my mac and got some errors:

* PhpOffice\PhpSpreadsheetTests\Calculation::testIMEXP#0:
    ```
    Mismatched Real part: 187004.112739 != 187004.112739
    Failed asserting that false is true.
     ~/tests/PhpSpreadsheetTests/Calculation/EngineeringTest.php:230
    ```
* PhpOffice\PhpSpreadsheetTests\Calculation::testIMSQRT#1:
    ```
    Mismatched Real part: 58223.706512 != 58223.706512
    Failed asserting that false is true.
     ~/tests/PhpSpreadsheetTests/Calculation/EngineeringTest.php:344
    ```
* PhpOffice\PhpSpreadsheetTests\Writer\Ods\Content::testWriteSpreadsheet:
    ```
    Failed asserting that two DOM documents are equal. <Click to see difference>
    
     ~/tests/PhpSpreadsheetTests/Writer/Ods/ContentTest.php:96
    ```
    The difference:
    ![2018-03-14 21 20 36](https://user-images.githubusercontent.com/9006227/37399524-97483868-27cd-11e8-9f3d-be888c43f479.png)

**Comment by FinesseRus** [comment]
Tested the issue in the version 1.2.0: it is fixed 🍻
