### ISSUE TITLE
MIT or lgpl? 

### ISSUE THREAD

**Issue by Inscure** [PHPOffice/PhpSpreadsheet#1670]
Hi,

You have two places with MIT License set, but there is also one telling about lgpl. 

![image](https://user-images.githubusercontent.com/1856485/95345200-c8c19080-08ba-11eb-95d8-c265e8d6b9ce.png)
![image](https://user-images.githubusercontent.com/1856485/95345402-f9092f00-08ba-11eb-9e58-a0583c912428.png)

![image](https://user-images.githubusercontent.com/1856485/95345303-e131ab00-08ba-11eb-91b3-cb6780d60d13.png)

What is the proper  license of this project?

**Comment by MarkBaker** [comment]
The correct license is the MIT license
