### ISSUE TITLE
[Feature proposal] new Writer for JSON files

### ISSUE THREAD

**Issue by schultz-it-solutions** [PHPOffice/PhpSpreadsheet#1673]
For our own usecase of PhpSpreadsheet (a JOOMLA! extension called **jDBexport** I developed an additional writer to create JSON documents from the spreadsheet object (it is based on the Csv writer).

As far as our usecase is concerned, this is fully working - and therefore I like to propose this to be included in PhpSpreadsheet.

kind regards
Ruediger Schultz
Schultz IT Solutions

**Comment by jihadismail8** [comment]
hi , could you please provide it ?? i am need it please )  i have some excel files i need to send by API as json from my laravel app

**Comment by schultz-it-solutions** [comment]
Hello,

here is the writer:
[Json.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/5627873/Json.zip)

you need to unzip it and put the **Json.php** into your  **PhpOffice/PhpSpreadsheet/Writer** directory

Then call the writer like this:

			$objWriterType = 'Json';
			$objWriter = new \PhpOffice\PhpSpreadsheet\Writer\Json($objDocument);
			$objWriter->setInsertLineEndings(FALSE);

If you want linebreaks after each JSON record, you can **setInsertLineEndings** to TRUE.

Let me know if this works for you. you can reach me by email: it-solutions@schultz.ch

kind regards
Ruediger Schultz
Schultz IT Solutions

**Comment by jihadismail8** [comment]
thank you very much )

**Comment by PowerKiKi** [comment]
Thanks for the suggestion, but I don't think we would add new writers for the time being, especially for something without a clear format (the JSON structure you chose may or may not fit other users). However I encourage you to publish, and maintain, a separate package if you feel like this would benefit the community.
