### ISSUE TITLE
Class 'Mpdf\Mpdf' not found in ..\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Pdf\Mpdf.php

### ISSUE THREAD

**Issue by jmechevarria** [PHPOffice/PhpSpreadsheet#1677]
This is:

```
- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
`\Mpdf\Mpdf` to be defined and its constructor's signature to comply with the parent class' (`PhpOffice\PhpSpreadsheet\Writer\Pdf`)

### What is the current behavior?
`\Mpdf\Mpdf` is not defined

### What are the steps to reproduce?
1. install via `composer require phpoffice/phpspreadsheet`
2. Follow the example in [the docs](https://phpspreadsheet.readthedocs.io/en/latest/topics/reading-and-writing-to-file/#pdf) to write a spreadsheet into pdf format.

Errors screens
![Screenshot (576)](https://user-images.githubusercontent.com/31573181/95668249-f155be80-0b36-11eb-818a-9d2371e3697e.png)
:
![Screenshot (577)](https://user-images.githubusercontent.com/31573181/95668213-64ab0080-0b36-11eb-9698-48fe34d57539.png)

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Hello World !');

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf($spreadsheet); //tried the three variants in the example for instantiating

$writer->save("05featuredemo.pdf"); //<----- triggers the error

```

First time using this tool, but the only `Mpdf` class I can find in the whole codebase is the same in which the error is occurring, there's no **Mpdf** folder at all, hence there can't be an `\Mpdf\Mpdf` class. So I tried to change:

        `return new \Mpdf\Mpdf($config);`

with

        `return new Mpdf($config);`

since it did make more sense to me and, yes, the error went away, but then this happened:

![Screenshot (580)](https://user-images.githubusercontent.com/31573181/95668311-f7986a80-0b37-11eb-8a73-14d9e2040e4a.png)

![Screenshot (579)](https://user-images.githubusercontent.com/31573181/95668312-f8c99780-0b37-11eb-8bf6-36302f15efb1.png)

So I switched it back and posted this here.

Thanks

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.4.11
PhpSpreadsheet 1.14.1 - 2020-07-19

-------------------------------------------------------------------------------------------
**PS**
there's also a typo in the docs (same link), in section _Or you can instantiate directly the writer of your choice like so:_
`$writer = \PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf($spreadsheet);` throws error  **Call to undefined function PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf()**, it seems to be missing the keyword **new** after **=** sign.

**Comment by MarkBaker** [comment]
Have you actually compose installed mPDF? This is an option, not installed as part of PHPSpreadsheet itself


```composer require mpdf/mpdf```

**Comment by jmechevarria** [comment]
> Have you actually composer installed mPDF? This is an option, not installed as part of PHPSpreadsheet itself
> 
> `composer require mpdf/mpdf`

I had not. I really missed this: _You must now install a PDF rendering library yourself_. I guess I scanned the docs instead of reading the docs, and skipped that bit.

Thanks a lot
