### ISSUE TITLE
Precision loss with large integers with 64 bit PHP

### ISSUE THREAD

**Issue by JanTvrdik** [PHPOffice/PhpSpreadsheet#168]
This is:

- [x] a bug report yes
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
No precision loss when using large integers (such as `9810000041216737`). DefaultValueBinder MUST NOT detect numeric type for large integers which cannot be represented as 64bit float.

### What is the current behavior?
[DefaultValueBinder](https://github.com/PHPOffice/PhpSpreadsheet/blob/6e4e0a65f5d28b95b63d645eb2c1389ab25653e4/src/PhpSpreadsheet/Cell/DefaultValueBinder.php#L85-L93) auto detect type numeric for large integers stored in string even though [casting such integers](https://github.com/PHPOffice/PhpSpreadsheet/blob/6e4e0a65f5d28b95b63d645eb2c1389ab25653e4/src/PhpSpreadsheet/Cell.php#L240-L242) to float may result in precision loss.

**Comment by PowerKiKi** [comment]
Would you like to provide a PR to fix that ?

**Comment by PowerKiKi** [comment]
Also what would you expect to happen when those big numbers would be used in calculation ? Wouldn't it break everything anyway ?

**Comment by JanTvrdik** [comment]
> Wouldn't it break everything anyway ?

Yes, probably. But that's another problem. I'm mostly interested in not casting strings which cannot be safely represented as 64 float to integers. Changing [this condition](https://github.com/PHPOffice/PhpSpreadsheet/blob/2e59885895a7e3e78bb76b0f97d35888c8823a3d/src/PhpSpreadsheet/Cell/DefaultValueBinder.php#L89) to sth. like

~~~php
} elseif ((strpos($pValue, '.') === false) && ($pValue > PHP_INT_MAX || $pValue > 9007199254740992)) {
    return DataType::TYPE_STRING;
}
~~~

should be enough.

**Comment by PowerKiKi** [comment]
Unfortunately I don't think the suggested patch will work, because it will cast to int, thus overflowing, and then trying to compare that overflown thing to the highest number possible.

Come to think of it, I don't think it is wise to "pretend" to support 64 bits overflowing numbers in reading process if we can't do any calculation with them. This will come back to bite us later on.

To solve your specific use-case though, I suggest you read about custom value binder: https://phpspreadsheet.readthedocs.io/en/develop/topics/reading-files/#a-brief-word-about-the-advanced-value-binder.

**Comment by PowerKiKi** [comment]
Looking at it even further and https://github.com/PHPOffice/PhpSpreadsheet/commit/d44aebc is actually already what you suggest and has been implemented 2 years ago.

And max int on 64 bits is not 9007199254740992, but actually 3 more digits longer:

```sh
$ php -r 'var_dump([PHP_INT_MAX, PHP_VERSION]);'
Command line code:1:
array(2) {
  [0] =>
  int(9223372036854775807)
  [1] =>
  string(36) "7.1.7-1+ubuntu16.04.1+deb.sury.org+1"
}
```

Maybe the diagnosis is not entirely correct ?

**Comment by JanTvrdik** [comment]
@PowerKiKi Once again, I'm not interested in supporting large numbers. I'm interested in supporting large strings which looks like numbers and are destroyed by PhpSpreadsheet.

**Comment by JanTvrdik** [comment]
> And max int on 64 bits is not 9007199254740992

Yes, I'm well aware. Please read the issue once more, you're missing the point. Also read // https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e which has been mentioned.

**Comment by PowerKiKi** [comment]
I see I mixed up `int` and `float` max values. Can you please provide a  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that shows exactly what you are trying to do, and what you expect to happen ?

**Comment by JanTvrdik** [comment]
> Can you please provide a Minimal, Complete, and Verifiable example of code that shows exactly what you are trying to do, and what you expect to happen ?

Yes, I can do it. No, I will not do it.
