### ISSUE TITLE
PHP 7.4 excel with macrosTrying to access array offset on value of type bool

### ISSUE THREAD

**Issue by ribehbl** [PHPOffice/PhpSpreadsheet#1685]
hello,

In a _symfony4_ project, I generate an **excel** file with **macros** with spreadsheet.
with **php7.2** it 's work fine. but when I try with a **7.4** php version I get this: 
**_Notice: Trying to access array offset on value of type_** bool

my pfile is :  "zip:///home/..../test.xlsm#xl/media/image62.wmf" & xl/media/image62.wmf is added automatically 
`getimagesize($pfile); `==> return false so `return image_type_to_mime_type($image[2]);` return this Notice
any help plz?

**Comment by nbulinski** [comment]
I'm having a similar issue. No macros but if there is an image in the spreadsheet it will throw this error. I have no idea what is wrong or how to fix it, please help.
