### ISSUE TITLE
Missing Bubble Chart example

### ISSUE THREAD

**Issue by Co0olCat** [PHPOffice/PhpSpreadsheet#169]
First of all -> Great product. We love.

Now, we cannot find example for bubble chart. 

Please advise.

Thank you.

TY

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
