### ISSUE TITLE
PdfWriter Mpdf orientation bug

### ISSUE THREAD

**Issue by sirion89** [PHPOffice/PhpSpreadsheet#1691]
I have already found the solution i think, but i'm not practical with pull request. I'm not used to it :( sorry
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The orientation to be what i've set when i created the pdf writer

### What is the current behavior?
The orientation get overwritten mistakenly by the code

### What are the steps to reproduce?
Quite easy, 
```php
$writerPdf = IOFactory::createWriter( $spreadsheetPdf, 'Mpdf' );
$writerPdf->setOrientation( PageSetup::ORIENTATION_LANDSCAPE );
$writerPdf->writeAllSheets();
$writerPdf->save( $path );
```

The fix should also be easy i guess. File is: src/PhpSpreadsheet/Writer/Pdf/Mpdf.php
This is an extract of the save function:

```php
  //  Check for paper size and page orientation
        if (null === $this->getSheetIndex()) {
            $orientation = ($this->spreadsheet->getSheet(0)->getPageSetup()->getOrientation()
                == PageSetup::ORIENTATION_LANDSCAPE) ? 'L' : 'P';
            $printPaperSize = $this->spreadsheet->getSheet(0)->getPageSetup()->getPaperSize();
        } else {
            $orientation = ($this->spreadsheet->getSheet($this->getSheetIndex())->getPageSetup()->getOrientation()
                == PageSetup::ORIENTATION_LANDSCAPE) ? 'L' : 'P';
            $printPaperSize = $this->spreadsheet->getSheet($this->getSheetIndex())->getPageSetup()->getPaperSize();
        }
        $this->setOrientation($orientation); //<------- this kill what we set with $writerPdf->setOrientation...
        //  Override Page Orientation
        if (null !== $this->getOrientation()) { // At this point $this->getOrientation() will ALWAYS have $orientation value
            $orientation = ($this->getOrientation() == PageSetup::ORIENTATION_DEFAULT)
                ? PageSetup::ORIENTATION_PORTRAIT
                : $this->getOrientation();
        }
        $orientation = strtoupper($orientation);
```

### Which versions of PhpSpreadsheet and PHP are affected?
composer.json:
"phpoffice/phpspreadsheet": "^1.10",
PHP version: 7.3.21

**Comment by oleibman** [comment]
PhpSpreadsheet allows the setting of different page size and orientation on each sheet. So, instead of setting the orientation on the PDF writer, you could instead do something like the following before doing your write:
```php
foreach ($spreadsheetPDF->getAllSheets() as $worksheet) {
    $worksheet->getPageSetup()->setOrientation(PageSetup::ORIENTATION_LANDSCAPE);
}
```
I agree that this is not quite so convenient as your existing code, but it should produce the result you want.

I will look into what is needed to make the writer override the orientation for a sheet only when the sheet hasn't explicitly specified a non-default orientation. The same should probably happen for paper size, which is slightly more difficult.
