### ISSUE TITLE
Invalid content in VML comments

### ISSUE THREAD

**Issue by emeraldjava** [PHPOffice/PhpSpreadsheet#170]
### What are the steps to reproduce?

Hi,

I'm trying to load a excel file using the load function via the code below. I want to be able to write data to the workbook

```php
$spreadsheet = PhpOffice\PhpSpreadsheet\IOFactory::load("BHAA.Race.Master.xlsm");
```

see https://github.com/emeraldjava/bhaa-racemaster/blob/master/BHAA.Race.Master.xlsm for the target file.

### What is the current behavior?

I get this error when loading, which indicated there are invalid XML details in the VML comments

```
[12-Jun-2017 09:14:36 UTC] PHP Warning:  simplexml_load_string():  &lt;/v:shape&gt;&lt;/xml&gt; in /home/pauloconnell/projects/github/bhaawp/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php on line 1354
[12-Jun-2017 09:14:36 UTC] PHP Warning:  simplexml_load_string():                  ^ in /home/pauloconnell/projects/github/bhaawp/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php on line 1354
[12-Jun-2017 09:14:36 UTC] PHP Fatal error:  Call to a member function registerXPathNamespace() on boolean in /home/pauloconnell/projects/github/bhaawp/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php on line 1355
```

Looking at the code in the Excel2007 file

```
// Loop through VML comments
foreach ($vmlComments as $relName => $relPath) {
    // Load VML comments file
    $relPath = \PhpOffice\PhpSpreadsheet\Shared\File::realpath(dirname("$dir/$fileWorksheet") . '/' . $relPath);
    $vmlCommentsFile = simplexml_load_string(
        $this->securityScan($this->getFromZipArchive($zip, $relPath)),
        'SimpleXMLElement',
        \PhpOffice\PhpSpreadsheet\Settings::getLibXmlLoaderOptions()
    );
    $vmlCommentsFile->registerXPathNamespace('v', 'urn:schemas-microsoft-com:vml');
```

because the 'simplexml_load_string' fails, the subsequent '$vmlCommentsFile->registerXPathNamespace()' is not a valid reference.

### Which versions of PhpSpreadsheet and PHP are affected?
 
I'm using php 5.6.30. 

My composer config has

```
"require": {
  "phpoffice/phpspreadsheet": "dev-master"
}
```

Has anybody seen this issue before or perhaps can suggest a fix. I'm happy to create a push request but am unsure how to best handle this situation.

**Comment by PowerKiKi** [comment]
You are using an old version of PhpSpreadsheet, start by upgrading and see if it still happens.

**Comment by emeraldjava** [comment]
@PowerKiKi - I updated the version to 'phpoffice/phpspreadsheet-->dev-develop' but the issue remains. 

Having investigated the vmlDrawing.xml files of the workbook, we have a number of macro buttons where the text message is being formatted with html '<br>' elements. These formatting statements are not contained in CDDATA blocks, so the php 'simplexml_load_string()' fails. I wondering is there an alternative xml processing method which is more flexible in terms of the xml structure which control the button formatting.

**Comment by PowerKiKi** [comment]
It sounds like your file is incorrectly written. Are you able to reproduce the bug with a minimal file that is written with Excel 2016 ?
