### ISSUE TITLE
Uncaught TypeError: Argument 2 passed to PhpOffice\PhpSpreadsheet\Calculation\LookupRef::INDIRECT() must be an instance of PhpOffice\PhpSpreadsheet\Cell\Cell or null, bool given

### ISSUE THREAD

**Issue by fami-64** [PHPOffice/PhpSpreadsheet#1704]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
No error when reading a cell with $cell->getCalculatedValue() (from a XLSX file)

### What is the current behavior?
Fatal error: Uncaught TypeError: Argument 2 passed to PhpOffice\PhpSpreadsheet\Calculation\LookupRef::INDIRECT() must be an instance of PhpOffice\PhpSpreadsheet\Cell\Cell or null, bool given in .../phplib/PhpOffice/PhpSpreadsheet/Calculation/LookupRef.php:276 Stack trace: #0 [internal function]: PhpOffice\PhpSpreadsheet\Calculation\LookupRef::INDIRECT('L1C2', false, Object(PhpOffice\PhpSpreadsheet\Cell\Cell)) #1 .../phplib/PhpOffice/PhpSpreadsheet/Calculation/Calculation.php(4714): call_user_func_array(Array, Array) #2 .../phplib/PhpOffice/PhpSpreadsheet/Calculation/Calculation.php(3442): PhpOffice\PhpSpreadsheet\Calculation\Calculation->processTokenStack(Array, 'A1', Object(PhpOffice\PhpSpreadsheet\Cell\Cell)) #3 .../phplib/PhpOffice/PhpSpreadsheet/Calculation/Calculation.php(3233): PhpOffice\PhpSpreadsheet\Calculation\Calculation->_calculateFormulaValue('INDIRECT("L1C2"...', 'A1', Object(PhpOffice\PhpSprea in .../phplib/PhpOffice/PhpSpreadsheet/Calculation/LookupRef.php on line 276

### What are the steps to reproduce?
Create a xlsx file with a formula like "=indirect('L1C2', FAUX)" in the first cell
Nota : I use a French version of Excel

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require '../phplib/autoload.php';
use PhpOffice\PhpSpreadsheet\IOFactory;

$inputFileName = 'a/valid/xlsx/file';
$reader = IOFactory::createReader('Xlsx');
$spreadsheet = $reader->load($inputFileName);
$worksheet = $spreadsheet->getSheet(0);

// add code that show the issue here...
foreach ($worksheet->getRowIterator() as $row) {
	$cellIterator = $row->getCellIterator();
	$cellIterator->setIterateOnlyExistingCells(FALSE);
	foreach ($cellIterator as $cell) echo '<br/>' . $cell->getCalculatedValue();
}
```
When I use "getValue()" rather than "getCalculatedValue", it works and returns "=INDIRECT("L1C2",FALSE)"
[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/5501597/test.xlsx)
[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/5501601/test.xlsx)

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.15.0
PHP v7.4.3

**Comment by oleibman** [comment]
It still produces an error, though it is now easier to understand:
```
Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Feuil1!A1
-> Invalid R1C1-format Cell Reference in C:\git\dateax\src\PhpSpreadsheet\Cell\Cell.php on line 298
```
It is worth noting that on my (US English) version of Excel, the cell in question displays `#REF!`, so your spreadsheet isn't portable even in Excel. This makes it difficult to decide what the best way for PhpSpreadsheet to handle it would be.
