### ISSUE TITLE
XLSX -> CSV, Escapped special characters in free text cell

### ISSUE THREAD

**Issue by Deck8** [PHPOffice/PhpSpreadsheet#1708]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

To keep an escaped special character, in this instance `\"` as `\"`

### What is the current behavior?

Special character is duplicated becoming `\""`

### What are the steps to reproduce?

In an excel document which is exported from a company application it has a column from a freetext box. Special characters are automatically escaped. In one entry the column contains the following (censored for privacy):

```
Address: Xxxxxxxx/ Xxxxxxx, ul.\"Xxxxxx\" nr.99
Germany/ Berlin, Hermannplatz
```

After converting from xlsx to csv it becomes:
```
"Address: Xxxxxxxx/ Xxxxxxx, ul.\""Xxxxxx\"" nr.99
Germany/ Berlin, Hermannplatz"
```

Reading this file using php fgetcsv breaks on this entry splitting the line having a new entry with  `Germany/ Berlin` as first and `Hermannplatz"` as second index.

Other lines with linebreaks in this column but without `\""` process as expected.

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\IOFactory;

$original = pathinfo($filename);
$outfile = $original['dirname']."/".$original['filename'].".csv";

$reader = IOFactory::createReaderForFile($filename);
$spreadsheet = $reader->load($filename);

$writer = IOFactory::createWriter($spreadsheet, "Csv");
$writer->setSheetIndex(0);   // Select which sheet to export.
$writer->setDelimiter(',');  // Set delimiter.
$writer->save($outfile);

```

### Which versions of PhpSpreadsheet and PHP are affected? 
PHP 7.2.24-0ubuntu0.18.04.7 /  PhpSpreadsheet 1.15

**Comment by oleibman** [comment]
The fgetcsv function by default uses '\' as its escape character, but you do not want to be using that for your file. The following code reads it as you wish:

```php
$escape = "\x0"; // can be null string for PHP7.4+
$arr = fgetcsv($handle, 0, ',', '"', $escape);
```

**Comment by oleibman** [comment]
... markup error above - "by default uses backslash as its escape character"

**Comment by oleibman** [comment]
No update in a year; believe suggested code addresses the problem.
