### ISSUE TITLE
Error integrating PhpSpreadsheet in codeigniter

### ISSUE THREAD

**Issue by techmind86** [PHPOffice/PhpSpreadsheet#171]
Hi,

I am just trying to integrate it in codeigniter but it gives me following error:

An uncaught Exception was encountered

Type: Error

Message: Class 'PhpOffice\PhpSpreadsheet\CachedObjectStorageFactory' not found

Filename: 
public_html/application/third_party/Phpexcel/PhpSpreadsheet/Worksheet.php

Line Number: 341

Backtrace:

File: public_html/application/third_party/Phpexcel/PhpSpreadsheet/Spreadsheet.php
Line: 363
Function: __construct

File: public_html/application/controllers/Dashboard.php
Line: 139
Function: __construct

File: public_html/index.php
Line: 315
Function: require_once

anyone there can help me to resolve this error.

Thanks

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
