### ISSUE TITLE
Xls file can't be read, Notice: String offset cast occurred

### ISSUE THREAD

**Issue by rpg600** [PHPOffice/PhpSpreadsheet#1714]
This is:

```
- [ X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the current behavior?
Some of my xls files can't be read, I got a hundred of notice until it stop. 
If I save my file with Excel for example, it solves the problem.
I don't know what Excel do in order to fix my file (encoding ?).

here is the stack trace if I convert the error to exception with an error handler :
```
  #message: "Notice: String offset cast occurred"
  #code: 0
  #file: "/home/adminweb/bo/current/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php"
  #line: 7902
  #severity: E_NOTICE
  trace: {
    /home/adminweb/bo/current/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php:7902 { …}
    /home/adminweb/bo/current/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php:2990 { …}
    /home/adminweb/bo/current/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php:736 { …}
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$reader = IOFactory::createReaderForFile($fileName);
$spreadsheet = $reader->load($fileName); // it crash here
```

### Which versions of PhpSpreadsheet and PHP are affected?
phpoffice/phpspreadsheet: 1.14.1
php 7.1.33

**Comment by oleibman** [comment]
Closing. No update in over 3.5 years. If this is still a problem, please open a new issue, preferably providing a file which demonstrates the problem.
