### ISSUE TITLE
Memory leak with Huge Files

### ISSUE THREAD

**Issue by IanStratico** [PHPOffice/PhpSpreadsheet#1726]
### What is the expected behavior?
to read the hole file

### What is the current behavior?
it sends a FATAL ERROR that says: "Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 167772160 bytes)"

### What are the steps to reproduce?
only run the code

// add code that show the issue here...
require __DIR__ . '/phpSpreadSheet/vendor/autoload.php'; 
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\IOFactory;

$inputFileName = "prueba.xlsx";
$numeroRollo = 20224662;
$reader = new PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$reader->setReadDataOnly(true);
$spreadsheet = $reader->load($inputFileName);
$worksheet = $spreadsheet->getActiveSheet();
$lastRow = $worksheet->getHighestRow();
echo $lastRow;

### Which versions of PhpSpreadsheet and PHP are affected?
the last one

**Comment by MarkBaker** [comment]
PHPSpreadsheet is an "in memory" model, which means that it uses PHP's memory to store the spreadsheet data when you load a spreadsheet, and for larger spreadsheets that can be a large amount of memory, and that may be more memory than is available for PHP to use.

Various methods are available to reduce that memory footprint. Setting read data only to true is one of those methods; another is cell caching (described in the [documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/memory_saving/), loading only specific worksheets, or even specific cells, or "chunk" loading the spreadsheet to process it in smaller segments). However, while this methods can help reduce memory requirements for a large spreadsheet file, memory usage cannot be eliminated.
