### ISSUE TITLE
Incorrect activeSheetIndex after removeSheetByIndex() call

### ISSUE THREAD

**Issue by sad-spirit** [PHPOffice/PhpSpreadsheet#1735]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
$sheet variable containing the remaining sheet.

### What is the current behavior?
Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Exception: Your requested sheet index: 1 is out of bounds. The actual number of sheets is 1.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$spreadsheet->createSheet();
$spreadsheet->setActiveSheetIndex(1);
$spreadsheet->removeSheetByIndex(0);
$sheet = $spreadsheet->getActiveSheet();
```

### Which versions of PhpSpreadsheet and PHP are affected?

All versions, I suspect. The bug is caused by the following code in `removeSheetByIndex()`:
```php
        // Adjust active sheet index if necessary
        if (
            ($this->activeSheetIndex >= $pIndex) &&
            ($pIndex > count($this->workSheetCollection) - 1)
        ) {
            --$this->activeSheetIndex;
        }
```
where `$pIndex > count($this->workSheetCollection) - 1` condition is only true when the last sheet is removed. The code looked this way from the very beginning.

**Comment by oleibman** [comment]
Fixed by PR 1743.
