### ISSUE TITLE
Date is incorrectly formatted

### ISSUE THREAD

**Issue by szymonczembor** [PHPOffice/PhpSpreadsheet#1740]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

I have a simple Excel sheet with only one cell holding the following date: `03.12.2020` (third of December). I expect that metod `getFormattedValue` on a cell object will return value `03.12.2020`.

### What is the current behavior?

I get `12/3/2020` value which is an incorrect date. I was debugging it for a long time but I wasn't able to find a solution how to read the cell's value with a proper format. In the file NumberFormat.php line 168 the static method `builtInFormatCode` gets value `14` as an argument so it returns format  `m/d/yyyy`. That's why I assume that it can be some bug.

### What are the steps to reproduce?

Below is my code.

```php
<?php

require_once '../vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load('test.xlsx');
$worksheet = $spreadsheet->getActiveSheet();
$cell = $worksheet->getCell('A1');

echo $cell->getFormattedValue(); // outputs 12/3/2020
```

### Which versions of PhpSpreadsheet and PHP are affected?

I use PhpSpreadsheet 1.12.0 and PHP 7.1.33.

**Comment by gvnt** [comment]
Hey, i have exactly the same problem, after long research i found this : https://stackoverflow.com/questions/34900605/excel-cell-style-issue .

It seems Excel interprets code 14 depending of Windows Language.

**Comment by szymonczembor** [comment]
@gvnt Thank you for your message. Stackoverflow's question you shared helped me to understand how date is stored in an Excel's file and why I am experiencing this problem with date format. I thought that this is a bug in the PhpSpreadsheet library but I was wrong. When `numFmtId ` is equal to 14 then formatting need to be provided.

Thanks to what I've read I've found a solution. My code now looks like this:

```
<?php

require_once '../vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load('test.xlsx');
$worksheet = $spreadsheet->getActiveSheet();

$worksheetCellValues = [];

foreach ($worksheet->getRowIterator() as $row) {
    $cellIterator = $row->getCellIterator();
    $cellIterator->setIterateOnlyExistingCells(false);

    $rowCellValues = [];

    foreach ($cellIterator as $cell) {
        $cellValue = $cell->getFormattedValue();

        if (PhpOffice\PhpSpreadsheet\Shared\Date::isDateTime($cell)) {
            $dateTime = PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($cell->getValue());
            $cellValue = $dateTime->format('d.m.Y');
        }

        $rowCellValues[] = $cellValue;
    }

    $worksheetCellValues[] = $rowCellValues;
}
```
