### ISSUE TITLE
Problem with the c:crossBetween element

### ISSUE THREAD

**Issue by vasilyevmichail** [PHPOffice/PhpSpreadsheet#1748]
Problem with the c:crossBetween element. If it is set to "midCat" then the values will be shifted to the left, leaving a bar-chart with more than one value-set so far left-shifted that the first value will disappear.

/Writer/Xslx/Chart.php

$objWriter->startElement('c:crossBetween');
$objWriter->writeAttribute('val', 'midCat');   // here change to 'between'
$objWriter->endElement();

![file](https://user-images.githubusercontent.com/14147113/101499877-d2c94380-397e-11eb-9aa3-f003f12df9b4.png)

**Comment by oleibman** [comment]
PR #2881, part of just released 1.24, permits specification of crossBetween value.
