### ISSUE TITLE
API Documentation Not Working

### ISSUE THREAD

**Issue by natatkinson** [PHPOffice/PhpSpreadsheet#1750]
This is:
https://phpoffice.github.io/PhpSpreadsheet/, whenever clicking a link to a method, 404 github error.
This link, for example: https://phpoffice.github.io/classes/PhpOffice-PhpSpreadsheet-Style-Style.html#property_conditionalStyles

```
- [X] a bug report
- [ ] a feature request
```

### What is the expected behavior?
page should load

### What is the current behavior?
404

**Comment by PowerKiKi** [comment]
Hopefully this will be fixed in the next release via https://github.com/PHPOffice/PhpSpreadsheet/commit/e8ebf117078d481b455b566eca760fa3c7c82cc7.

Meanwhile you can generate the doc locally via:

```sh
curl -LO https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.0.0/phpDocumentor.phar
php phpDocumentor.phar --directory src/ --target docs/api
```
