### ISSUE TITLE
[InvalidArgumentException] Could not find package phpoffice/phpspreadsheet.

### ISSUE THREAD

**Issue by dginanjar13** [PHPOffice/PhpSpreadsheet#1758]
**[InvalidArgumentException]**
  Could not find package phpoffice/phpspreadsheet.

  **Did you mean one of these?**
      phpoffice/phpspreadsheet
      mulgor/phpspreadsheet
      marble-d/phpspreadsheet
      nnchutchikov/spreadsheet
      remember/laravel-spreadsheet

**Any somebody help me?**
_composer.json_ code was same with : https://github.com/PHPOffice/PhpSpreadsheet/blob/master/composer.json

**Comment by LRJoker** [comment]
Try to check your composer repositories？

**Comment by oleibman** [comment]
Closing. No update in 21 months, similar reported problems have all been due to errors in reporter's composer environment.
