### ISSUE TITLE
Unnecessarily enforces maximum of 31 characters in sheet titles

### ISSUE THREAD

**Issue by MikkelPaulson** [PHPOffice/PhpSpreadsheet#176]
This is:

- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### Summary

XLSX files (at the very least) support sheet titles over 31 characters, but PhpSpreadsheet enforces a 31-character limit regardless of file format. This would be annoying if it only affected sheet creation, but the validation code is also run on load. This means that PhpSpreadsheet is unable to load any valid XLSX file (or file of any other format) containing a sheet with a name over 32 characters.

### What is the expected behavior?

A worksheet title containing 32 characters is set correctly. An exception should only be thrown when saving to a format that doesn't support longer titles.

### What is the current behavior?

An exception is thrown with the message "Maximum 31 characters allowed in sheet code name.".

### What are the steps to reproduce?

(Shows creating a new file, but the same behaviour is encountered when loading an existing file with a sheet title over 31 chars.)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getSheet();
$sheet->setTitle('ten chars ten chars ten chars +2');
```

### Which versions of PhpSpreadsheet and PHP are affected?

PHPExcel 1.8, PhpSpreadsheet develop

**Comment by PowerKiKi** [comment]
Thanks for this contribution of quality. Would you be able to find official specs for a few formats about sheet title length ? I'd say at least XLSX and ODS would be nice

**Comment by MikkelPaulson** [comment]
Reviewing the ODS spec, the relevant XML property is [table:name](https://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#attribute-table_name). It specifies the data type as "string" without additional constraints. Obviously applications will impose their own limits in terms of what they'll render, but LibreOffice happily opened a file containing an entire paragraph of lorem ipsum.

<img width="1061" alt="screen shot 2017-06-14 at 20 33 46" src="https://user-images.githubusercontent.com/585944/27160265-e643d29c-5140-11e7-991f-11b53e6b9f1c.png">

**Comment by PowerKiKi** [comment]
See https://github.com/PHPOffice/PhpSpreadsheet/pull/177#issuecomment-309699114
