### ISSUE TITLE
PHPWord maintainers

### ISSUE THREAD

**Issue by stephanvierkant** [PHPOffice/PhpSpreadsheet#1765]
Sorry for creating this issue here, but it's my last option to get in contact with anyone from PHPOffice.

It looks like PHPWord isn't maintained anymore. https://github.com/PHPOffice/PHPWord/pull/1946 is open for a couple of months, without any reaction from the maintainers. @troosan doesn't look active here and I haven't found any contact details (apart from connecting via LinkedIn).

Does anyone know how we get in contact with the maintainer(s)?

**Comment by MrElLeRm** [comment]
> Sorry for creating this issue here, but it's my last option to get in contact with anyone from PHPOffice.
> 
> 
> 
> It looks like PHPWord isn't maintained anymore. https://github.com/PHPOffice/PHPWord/pull/1946 is open for a couple of months, without any reaction from the maintainers. @troosan doesn't look active here and I haven't found any contact details (apart from connecting via LinkedIn).
> 
> 
> 
> Does anyone know how we get in contact with the maintainer(s)?

**Comment by MrElLeRm** [comment]
> Sorry for creating this issue here, but it's my last option to get in contact with anyone from PHPOffice.
> 
> 
> 
> It looks like PHPWord isn't maintained anymore. https://github.com/PHPOffice/PHPWord/pull/1946 is open for a couple of months, without any reaction from the maintainers. @troosan doesn't look active here and I haven't found any contact details (apart from connecting via LinkedIn).
> 
> 
> 
> Does anyone know how we get in contact with the maintainer(s)?

Why anyone from "super" devs doesn't fork this and make a new version with needle support yet ?

**Comment by stephanvierkant** [comment]
While this is a possible work-around, I think it's the responsibility for open source projects to transfer 'ownership' if they stop to maintain it. It's in nobody's interest to have multiple forks of the same project just because the maintainers stopped working with PHP.

The original packages should have a clear warning (on Github and packagist) that the project is unmaintained and that even security issue won't be fixed.

But I really hope we can get this project maintained again.

**Comment by oleibman** [comment]
It appears that a number of PR's were merged yesterday, including the one you explicitly mentioned (1946).

**Comment by stephanvierkant** [comment]
But without tagging a release: https://github.com/PHPOffice/PHPWord/issues/1979.

**Comment by stephanvierkant** [comment]
I give up.
