### ISSUE TITLE
Ods: Call to a member function getAttributeNS() on null

### ISSUE THREAD

**Issue by eigan** [PHPOffice/PhpSpreadsheet#1772]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Can load this ods file. Worked in 1.14.

### What is the current behavior?
Crashes. See below.

### What are the steps to reproduce?
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$readerType = IOFactory::identify('file.ods');
$reader = IOFactory::createReader($readerType);
$reader->load('file.ods')
```
See attached file (had to zip it because GitHub did not allow .ods file).

[testcase.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/5764502/testcase.zip)

### Which versions of PhpSpreadsheet and PHP are affected?
PHP Spreadsheet 1.15+
PHP 7.4 (probably earlier versions too)

### Error
```
Error: Call to a member function getAttributeNS() on null

vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods/PageSettings.php:57
vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods/PageSettings.php:26
vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods.php:289
vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods.php:244
```

**Comment by TonisOrmisson** [comment]
Im also experiencing this issue

**Comment by oleibman** [comment]
Fixed by PR 1776.
