### ISSUE TITLE
replace Logic

### ISSUE THREAD

**Issue by MouseZver** [PHPOffice/PhpSpreadsheet#1779]
https://github.com/PHPOffice/PhpSpreadsheet/blob/76d4323b85129d0c368149c831a07a3e258b2b50/src/PhpSpreadsheet/Calculation/Calculation.php#L2776

in_array ( $returnType, [ self::RETURN_ARRAY_AS_VALUE, self::RETURN_ARRAY_AS_ERROR, self::RETURN_ARRAY_AS_ARRAY ], true )

**Comment by MarkBaker** [comment]
We do accept Pull Requests
