### ISSUE TITLE
NumberFormat.php Parse error:syntax error, unexpected '='

### ISSUE THREAD

**Issue by silencefent** [PHPOffice/PhpSpreadsheet#1787]
This is: Syntax error, file is vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Style\NumberFormat.php, at line 720
```
[$currencyCode] = explode('-', $currencyCode);
```
suggestion to fix this bug:
```
$currencyCode = explode('-', $currencyCode)[0];
```
thank you

**Comment by silencefent** [comment]
at file last line 
```
 [$writerInstance, $function] = $callBack;
```
```
$writerInstance = callBack[0];
$function = callBack[1];
```

**Comment by michaljusiega** [comment]
Which version PHP do you have ? Short syntax list was introduced in `PHP 7.1` (https://wiki.php.net/rfc/short_list_syntax) and PHPSpreadsheet needs `>= PHP 7.2`
