### ISSUE TITLE
Comment box text alignment

### ISSUE THREAD

**Issue by prfardin** [PHPOffice/PhpSpreadsheet#1788]
how i can set alignment for comment box text!
im using laravel https://github.com/maatwebsite/Laravel-Excel and here's my code :
` $row = $failuresRow['row'];
$commentRichText = $event->sheet->getDelegate()
   ->getComment($key.$row)
   ->getText()
   ->createTextRun('PhpSpreadsheet:');
$commentRichText->getFont()->setBold(true);
$event->sheet->getDelegate()
   ->getComment($key.$row)
   ->getText()->createTextRun("\r\n");
$event->sheet->getDelegate()
   ->getComment($key.$row)
   ->getText()->createTextRun($columnError['errors']);

$event->sheet->getDelegate()->getComment($key.$row)
   ->setAlignment(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER_CONTINUOUS);
$event->sheet->getDelegate()->getComment($key.$row)->setWidth("200px");
$event->sheet->getDelegate()->getComment($key.$row)->getFillColor()->setARGB('FFFFFFFF'); `

**Comment by oleibman** [comment]
Functionality added by PR #4006. Closing issue.
