### ISSUE TITLE
Exception when rounding #VALUE! Cell with PHP 8

### ISSUE THREAD

**Issue by davidlienhard** [PHPOffice/PhpSpreadsheet#1789]
Hi
I stumbled uppon this issue with **PHP 8** when rounding a cell. I'm not sure if PhpSpreadsheet already supports PHP 8, but according to `composer.json` it does.

This is:
```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
An array with the contents of the Excel-Sheet when using `$worksheet->toArray()`

### What is the current behavior?
An exception is thrown:
```
PHP Fatal error:  Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /srv/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php:4714
Stack trace:
#0 [internal function]: round()
#1 /srv/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php(4714): call_user_func_array()
#2 /srv/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php(3442): PhpOffice\PhpSpreadsheet\Calculation\Calculation->processTokenStack()
#3 /srv/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php(3233): PhpOffice\PhpSpreadsheet\Calculation\Calculation->_calculateFormulaValue()
#4 /srv/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php(257): PhpOffice\PhpSpreadsheet\Calculation\Calculation->calculateCellValue()
#5 /srv/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(2525): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()
#6 /srv/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(2599): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->rangeToArray()
#7 /srv/app/xls.php(13): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->toArray()
#8 {main}
  thrown in /srv/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php on line 4714
```

### What are the steps to reproduce?
This seems to happen when trying to `round` a cell with a value that cannot be calculated.
Use this example Excel-Sheet:  [test.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/5809677/test.zip)
In the first cell there is some text. In the second we try to multiply the text with 5 which is not possible of course. The Exception then is happening in **Cell C** when trying to `round` the second cell.

|                   | A     | B            | C                        |
|-------------|------|----------| ------------------|
| RAW          | text | =A1*5    | =ROUND(B1;0) |
| Calculated | text | #VALUE! | #VALUE!           |

You can use this code to reproduce:
```php
<?php

declare(strict_types=1);

use \PhpOffice\PhpSpreadsheet\IOFactory;

require_once __DIR__."/vendor/autoload.php";

$file = __DIR__."/test.xlsx";

$spreadsheet = IOFactory::load($file);
$worksheet = $spreadsheet->getActiveSheet();
print_r($worksheet->toArray());

```

### Which versions of PhpSpreadsheet and PHP are affected?
I'm using PhpSpreadsheet 1.16.1 from Composer. This only happens with **PHP 8** due to the more strict type-checks.

**Comment by oleibman** [comment]
When PhpSpreadsheet encounters a function call in a cell, it invokes either a PhpSpreadsheet method or a built-in PHP function. I believe that this problem is possible for any of the built-in PHP functions. Aside from ROUND, these are:
ABS, ACOS, ACOSH, ASIN, ASINH, ATAN, ATANH, COS, COSH, DEGREES (rad2deg), EXP,  LN (log), LOG10, RADIANS (deg2rad), REPT (str_repeat), SIN, SINH, SQRT, TAN, TANH.

**Comment by oleibman** [comment]
It is also worth noting that, although PHP7 doesn't throw an exception for these situations, its results are nevertheless wrong. For example, ROUND('text') will result in 0 for PHP7 PhpSpreadsheet, but should result in a VALUE error. So the solution to this problem will not necessarily be as simple as wrapping the offending statement within try/catch.

**Comment by oleibman** [comment]
Result is also currently wrong, regardless of PHP version, whenever one of the builtin functions returns NAN, e.g. acos(2).

**Comment by davidlienhard** [comment]
Hi @oleibman 
Thank you very much for looking into this and having a fix for this. Very much appreciated :)
I just did some tests with PHP 8.0.1 & PHPSpreadsheet from master branch and no exceptions were thrown. I get the result of `#VALUE!` as expected.
But I noticed another issue that seems to be caused by those changes. I'm not sure if I should create a new issue for that. Let me know if you prefer this.

The problem happens when rounding an empty cell. I'm using the following formula where `A1` is an empty cell: `=ROUND(A1;0)`
PHPSpreadsheet returns a result of `#VALUE!` but Excel returns `0`. Now we can argue which result is mathematically correct, but I think it would be correct if PHPSpreadsheet would return the same result as Excel does.

I'm using the same code as above, as mentioned with PHP 8.0.1 & PHPSpreadsheet from the current master branch.

**Comment by oleibman** [comment]
That is a surprising result. The Excel documentation is often sparse about weird situations like this. In addition to null, ROUND seems to accept booleans as arguments! I will look into changing PhpSpreadsheet's behavior to match Excel's in these situations some time this week.

**Comment by davidlienhard** [comment]
Yes, this is at least not what were used from php. 
Booleans indeed seem to work as well:
| Formula | Result
-----------------------|--
| `=ROUND(TRUE;0)` | 1
| `=ROUND(FALSE;0)` | 0
| `=ROUND("test";0)` | #VALUE!
| `=ROUND(;0)` | 0

Thank you very much for having a look into this!

**Comment by davidlienhard** [comment]
Hi @oleibman 
Thank you very much for your work on this. I just tried it with the latest code from master branch and my app is not working as with php 7.4 before!

**Comment by dleer** [comment]
I am new to PHPSpreadsheet and have run into this issue.  I put together a simple spreadsheet in OpenOffice, in their native ODS format, and used the round function.  The OpenOffice manual says "If Count is omitted or zero, the function rounds to the nearest integer" and this is what is desired so I did not specify Count.

The result is:
`[23-Feb-2023 17:30:51] PHP Fatal error:  Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Sheet1!E3 -> Formula Error: Wrong number of arguments for ROUND() function: 1 given, 2 expected in phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:390
Stack trace:
#0 phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(2990): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()
#1 phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(3102): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->rangeToArray('A1:E433', NULL, true, true, true)
#2 _import.php(70): PhpOffice\PhpSpreadsheet\Worksheet\Worksheet->toArray(NULL, true, true, true)
#3 {main}
  thrown in phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php on line 390
`


If I save the spreadsheet in XLS format there is no error and it imports fine.

**Comment by MarkBaker** [comment]
> I am new to PHPSpreadsheet and have run into this issue with a page I built to import a spreadsheet. I put together a simple spreadsheet in OpenOffice, in their native ODS format, and used the round function. The OpenOffice manual says "If Count is omitted or zero, the function rounds to the nearest integer" and this is what is desired so I did not specify Count.

I'm sure that you can appreciate the difficulties of different mandatory arguments for functions between different Spreadsheet applications

For MS Excel:
 > ROUND(number, num_digits)
 > The ROUND function syntax has the following arguments:
 > - number    Required. The number that you want to round.
 > - num_digits    **Required**. The number of digits to which you want to round the number argument.
(my emphasis)


And for OpenOffice:
 > ROUND(number; places)
 > returns number rounded to places decimal places. **If places is omitted** or zero, the function rounds to the nearest integer. If places is negative, the function rounds to the nearest 10, 100, 1000, etc.
(my emphasis)

If you have any suggestions on how we might be able to cater for these contradictory requirements, how the places argument can be both mandatory and optional at the same time, then I'm happy to listen

**Comment by dleer** [comment]
So PHPSpreadsheet is primarily targeting Excel rules?  Maybe just removing the ability to upload ODS sheets on my page would work for me.  When I save a spreadsheet in Excel format with OpenOffice, I see it adds the second argument to round.  

I suppose the solution on PHPSpreadsheet's side would be similar comprehensive sheet specification detection / management that it doesn't do right now.  I can certainly understand that would be quite the undertaking!



> > I am new to PHPSpreadsheet and have run into this issue with a page I built to import a spreadsheet. I put together a simple spreadsheet in OpenOffice, in their native ODS format, and used the round function. The OpenOffice manual says "If Count is omitted or zero, the function rounds to the nearest integer" and this is what is desired so I did not specify Count.
> 
> I'm sure that you can appreciate the difficulties of different mandatory arguments for functions between different Spreadsheet applications
> 
> For MS Excel:
> 
> > ROUND(number, num_digits)
> > The ROUND function syntax has the following arguments:
> > 
> > * number    Required. The number that you want to round.
> > * num_digits    **Required**. The number of digits to which you want to round the number argument.
> 
> (my emphasis)
> 
> And for OpenOffice:
> 
> > ROUND(number; places)
> > returns number rounded to places decimal places. **If places is omitted** or zero, the function rounds to the nearest integer. If places is negative, the function rounds to the nearest 10, 100, 1000, etc.
> 
> (my emphasis)
> 
> If you have any suggestions on how we might be able to cater for these contradictory requirements, how the places argument can be both mandatory and optional at the same time, then I'm happy to listen

**Comment by MarkBaker** [comment]
> So PHPSpreadsheet is primarily targeting Excel rules? Maybe just removing the ability to upload ODS sheets on my page would work for me. When I save a spreadsheet in Excel format with OpenOffice, I see it adds the second argument to round.
> 
> I suppose the solution on PHPSpreadsheet's side would be similar comprehensive sheet specification detection / management that it doesn't do right now. I can certainly understand that would be quite the undertaking!

I can see a couple of possible options; but I don't really like either.
 1. Modify the ODS Reader so that it checks every formula and adds/adjusts arguments if necessary; in this case, adding the missing places argument. It is already necessary to modify the loaded formula to match Excel syntax.
 2. Modifying the Calculation engine to handle the differences between Spreadsheets. We already have a Calculation Mode option that is used to manage the different handling within a function between Excel/ODS/Gnumeric.

Both are possible
BUT
 1. The Reader Option
   a. Would slow down the loading of ODS files, probably quite significantly for formula heavy spreadsheets.
   b. If the file was subsequently saved as ODS, the formula would now have the additional argument.
 2. The Calculation Engine Option.
   a. Requires the developer to do make an explicit call to set the Mode.
   b. Would require a reloading of the Calculation Engine's internal table of Function definitions on change of Mode.

And both options create a lot of extra work in keeping track of all the subtle differences between Functions in the different Spreadsheet apps, which can change for each new release of the app. It's difficult enough keeping up with new functions; but keeping up with the minutiae of function arguments and behaviours greatly increases that workload... especially as those details are often not documented in Change Logs
