### ISSUE TITLE
parseFormula(): exception on mbstring named range

### ISSUE THREAD

**Issue by Dfred** [PHPOffice/PhpSpreadsheet#179]
This is:

- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
whether or not a string is multi-byte should not make a difference for the calculation engine.

### What is the current behavior?
Throws a PHPExcel_Calculation_Exception with message

> Formula Error: An unexpected error occured

### What are the steps to reproduce?

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\NamedRange;
use PhpOffice\PhpSpreadsheet\Calculation;

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$spreadsheet->getActiveSheet()->setCellValue('A1', 'kiki');
$name = html_entity_decode('clich&eacute;');
$spreadsheet->addNamedRange(new NamedRange($name, $spreadsheet->getActiveSheet(), 'A1'));
$res = Calculation::getInstance($spreadsheet)->parseFormula('=' . $name);
var_dump($res);
```

### Which versions of PhpSpreadsheet and PHP are affected?
all

**Comment by Dfred** [comment]
somebody has taken charge of this.

**Comment by Dfred** [comment]
I have fixed the issue, but will need more time or help to create the PR with all required tests.

**Comment by oleibman** [comment]
Supplied code now works correctly.
