### ISSUE TITLE
Drop PclZip in favor of built-on ZipArchive

### ISSUE THREAD

**Issue by PowerKiKi** [PHPOffice/PhpSpreadsheet#18]
Since PHP 5.2 ZipArchive is always available, and PclZip is a cause of bug. This can be seen in sample `20_Read_OOCalc_with_PCLZip.php`, which gives the following output:

```
$ php samples/20_Read_OOCalc_with_PCLZip.php 
PHP Fatal error:  Uncaught Error: Call to undefined method PhpSpreadsheet\Shared\ZipArchive::statName() in /sites/PhpSpreadsheet/src/PhpSpreadsheet/Reader/OOCalc.php:73
Stack trace:
#0 /sites/PhpSpreadsheet/src/PhpSpreadsheet/IOFactory.php(251): PhpSpreadsheet\Reader\OOCalc->canRead('/sites/PhpSprea...')
#1 /sites/PhpSpreadsheet/src/PhpSpreadsheet/IOFactory.php(173): PhpSpreadsheet\IOFactory::createReaderForFile('/sites/PhpSprea...')
#2 /sites/PhpSpreadsheet/samples/20_Read_OOCalc_with_PCLZip.php(10): PhpSpreadsheet\IOFactory::load('/sites/PhpSprea...')
#3 {main}
  thrown in /sites/PhpSpreadsheet/src/PhpSpreadsheet/Reader/OOCalc.php on line 73

Fatal error: Uncaught Error: Call to undefined method PhpSpreadsheet\Shared\ZipArchive::statName() in /sites/PhpSpreadsheet/src/PhpSpreadsheet/Reader/OOCalc.php on line 73

Error: Call to undefined method PhpSpreadsheet\Shared\ZipArchive::statName() in /sites/PhpSpreadsheet/src/PhpSpreadsheet/Reader/OOCalc.php on line 73

Call Stack:
    0.0001     362960   1. {main}() /sites/PhpSpreadsheet/samples/20_Read_OOCalc_with_PCLZip.php:0
    0.0013     464544   2. PhpSpreadsheet\IOFactory::load() /sites/PhpSpreadsheet/samples/20_Read_OOCalc_with_PCLZip.php:10
    0.0013     464544   3. PhpSpreadsheet\IOFactory::createReaderForFile() /sites/PhpSpreadsheet/src/PhpSpreadsheet/IOFactory.php:173
    0.0034     603008   4. PhpSpreadsheet\Reader\OOCalc->canRead() /sites/PhpSpreadsheet/src/PhpSpreadsheet/IOFactory.php:251
```

So instead of debugging an obsolete, duplicated library, I suggest we drop it entirely. @MarkBaker @Progi1984 what do you think ?

**Comment by Progi1984** [comment]
The solution that I use in PhpPresentation is the Zip Adapter of PHPOffice\Common :
* Common : https://github.com/PHPOffice/Common/tree/develop/src/Common/Adapter/Zip
* Use in PhpPresentation : https://github.com/PHPOffice/PHPPresentation/blob/develop/src/PhpPresentation/Writer/ODPresentation/Pictures.php#L24

**Comment by Quix0r** [comment]
That what @Progi1984 recommends is are more flexible solution, rather than hard-coded ZipArchive code.

**Comment by PowerKiKi** [comment]
I tend to agree, but that implies that composer becomes mandatory. While I don't think it matters, since composer is so common nowaday, I believe @MarkBaker wanted to keep a version without composer (hence the custom autoloader).

**Comment by PowerKiKi** [comment]
composer is now mandatory since 035281f04cc05f33919da8c0ac230de69cd7a675, so we can go ahead with this feature too.

**Comment by PowerKiKi** [comment]
@Progi1984, @Quix0r, I had a look at Common's `ZipInterface` and even though I did prepare a PR to complete the features needed for PhpSpreadsheet, I must say that I am a bit unsure whether this is the right way do to it.

First of all, I noticed that PhpPresentation has a hard dependency on `ZipArchive` via composer (`"ext-zip": "*"`). And this is very clearly the case since all readers use `new ZipArchive()` instead of the `ZipInterface`. That explains why `ZipInterface` has no methods to read anything (but only write). So why is done that way in PhpPresentation ?

Secondly, using `ZipInterface` instead of `ZipArchive` is a slight overhead in complexity of code and reduce the features we can use since PclZip cannot (easily) replicate everything that `ZipArchive` does. So the question here is why should we do more work to be more limited ? what is the added value of using `ZipInterface` ?

Finally PclZip seems to be a dying project. It is only available via an [**unofficial** fork](https://github.com/ivanlanin/pclzip), which was [never updated since the first commit 3 years ago](https://github.com/ivanlanin/pclzip/graphs/contributors), who is [possibly out of sync for the last 2 years](https://github.com/ivanlanin/pclzip/issues/2), whose [PR were never addressed at all](https://github.com/ivanlanin/pclzip/pulls), and who happen to be [incompatible with PHP 7.1](https://travis-ci.org/PHPOffice/Common/jobs/205237664#L313-L319). Oh, and the [latest official news is from 7 years ago.](http://www.phpconcept.net/pclzip/news) So I am really wondering why should we keep supporting this old tech ?

**Comment by Quix0r** [comment]
I found this here:
http://phpzip.cvs.sourceforge.net/viewvc/phpzip/pclzip/

Even more older, sad to see that so much progress is dying because of lack of interest/time/what ever. Yeah, same with my projects like `mailer`. :-(

**Comment by agopaul** [comment]
At this point, I think the question is how much the library (PhpSpreadsheet) should be portable.

On Ubuntu the zip extension in not bundled with the PHP package but, like most extensions, it has its own package. So a "stock" LAMP installation doesn't have the zip extension installed, but when working on PHP projects, using extensions is almost inevitable. I don't know if the extension is bundled with PHP in other Linux distros and on other OSes.

Shared hosting is the only context where PHP extensions are tricky because, of course, you can't install them if they're missing. But shared hosts usually come with all the most common extensions already installed (eg: gd2, soap, zip, etc.)

I think that support for PclZip should probably be dropped otherwise the only solution would be to create and support a fork of it, but that would require additional resources and energy to maintain a library which apparently throws notice errors with the latest PHP version.

**Comment by PowerKiKi** [comment]
Thanks all for offering your opinions. In the past 6 months, nobody offered strong argument to keep PclZip. It seems dropping it is acceptable and so it was done.

**Comment by andyinabox** [comment]
So just to clarify — does this mean that if I don't have the zip extension installed (and can't install it) I'm out of luck?

**Comment by PowerKiKi** [comment]
yes, this is [enforced by composer](https://github.com/PHPOffice/PhpSpreadsheet/blob/49775bd9721fd31b162a7840514bd69902eff77c/composer.json#L35-L49). You won't be able to install PhpSpreadsheet if you don't have all required extensions.

**Comment by andyinabox** [comment]
Oh I see  -- guess I unintentionally found a loophole; I'm serving the site from a VM using vagrant but did the composer install on the host machine. :/

**Comment by andyinabox** [comment]
Maybe it would be a good idea to list dependencies on the main README file?

**Comment by PowerKiKi** [comment]
The README will stay as concise as possible, to avoid duplication of information. This particular requirement is already listed in the install instructions. So there is nothing to do.
