### ISSUE TITLE
Only variables can be passed by reference

### ISSUE THREAD

**Issue by applibs** [PHPOffice/PhpSpreadsheet#1801]
Please fix this line:
return array_pop(array_slice($dataValues, 0, $ruleValue));

into:
$array = array_slice($dataValues, 0, $ruleValue);
return array_pop($array);

same here:
$instanceId = end(array_keys($GLOBALS['_OLE_INSTANCES']));
and
$cellAddress = array_pop(array_keys($this->phpSheet->getComments()));

**Comment by oleibman** [comment]
Closing. No indication where suggested changes were supposed to be made, but:
`array_pop(array_slice` might refer to Worksheet/AutoFilter, where the suggested change is already made.
`array_keys($GLOBALS` might refer to Shared/Ole, where the suggested change is already made.
`phpSheet->getComments` might have referred to Reader/Xls, where the suggested change is already made.
