### ISSUE TITLE
 Formula Error: Wrong number of arguments for COUNTIFS() function: 4 given, 2

### ISSUE THREAD

**Issue by wolly66** [PHPOffice/PhpSpreadsheet#181]
[tabellaperassociazioni.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1094740/tabellaperassociazioni.xlsx)
This is:

- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
I load an xlsx template
I put some test data in cells
Write the new file

### What is the current behavior?
When reading, get:  Formula Error: Wrong number of arguments for COUNTIFS() function: 4 given, 2

### Solution
in Calculation.php modify line 404
from 'argumentCount' => '2',
to 'argumentCount' => '2,4',

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

To test you need an external excel file, that i attach

```php
<?php
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
//Load the file template
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('tabellaperassociazioni.xlsx');

$worksheet = $spreadsheet->getActiveSheet();
//insert test data in some cells
$worksheet->getCell('C3')->setValue('API GENOVA');
$worksheet->getCell('C5')->setValue('22/06/2017');
$worksheet->getCell('A11')->setValue('Messina');
$worksheet->getCell('B12')->setValue('Dario');
$worksheet->getCell('C11')->setValue('Italiano');
$worksheet->getCell('H11')->setValue('ARENZANO');

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xls');
//write the file
$writer->save('comunicazione.xls');

```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet = develop
PHP 7.0

**Comment by PowerKiKi** [comment]
[`COUNTIFS`](https://support.office.com/en-us/article/COUNTIFS-function-dda3dc6e-f74e-4aee-88bc-aa8c2a866842) function takes an infinite even number of arguments, not only 4. Would you want to create a PR that contains unit tests for that ?

**Comment by wolly66** [comment]
I'd really like to, but I never created a unit test.

I'm so sorry, I swear that I'll study how to do it.

**Comment by PowerKiKi** [comment]
Have a look at [LogicalTest::testAnd()](https://github.com/PHPOffice/PhpSpreadsheet/blob/07455d24f644ea1ebd8efafbc8bcc711d0cbf6b3/tests/PhpSpreadsheetTests/Calculation/LogicalTest.php#L28-L42) and [tests/data/Calculation/Logical/AND.php](https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/tests/data/Calculation/Logical/AND.php) for examples on what it could look like.
