### ISSUE TITLE
Can I do ignore Formula Error: An unexpected error occurred?

### ISSUE THREAD

**Issue by balex777** [PHPOffice/PhpSpreadsheet#1811]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
I have a lot of xlsx files, and when reading their sometime my sheets has Formula Error: An unexpected error occurred, this makes a fatal error and stops all work php, can I do ignore that erros? 
Thanks

```php
<?php

require __DIR__ . '/vendor/autoload.php';

       $reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');

        $spreadsheet = $reader->load('/file.xlsx');
        $sheet = $spreadsheet->getSheet(6);
        $sheetData = $sheet->toArray(null, true, true, true);

### Which versions of PhpSpreadsheet and PHP are affected?

**Comment by davidlienhard** [comment]
How about wrapping the `toArray()` call or the whole code into a try/catch block?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');

try {
    $spreadsheet = $reader->load('/file.xlsx');
    $sheet = $spreadsheet->getSheet(6);
    $sheetData = $sheet->toArray(null, true, true, true);
} catch (\Exception $e) {
    echo "an error occured: ".$e->getMessage();
}

// more code

**Comment by balex777** [comment]
> 
> 
> How about wrapping the `toArray()` call or the whole code into a try/catch block?
> 
> ```
> <?php
> 
> require __DIR__ . '/vendor/autoload.php';
> 
> $reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
> 
> try {
>     $spreadsheet = $reader->load('/file.xlsx');
>     $sheet = $spreadsheet->getSheet(6);
>     $sheetData = $sheet->toArray(null, true, true, true);
> } catch (\Exception $e) {
>     echo "an error occured: ".$e->getMessage();
> }
> 
> // more code
> ```

I have error php, not exeption.  I try this but it is not help I have fatal error php

`                catch (\Error $er)     {

                    Yii::log(CVarDumper::dumpAsString($er->getMessage()), CLogger::LEVEL_ERROR, self::logFileName .'.Error');
                
                }`

**Comment by davidlienhard** [comment]
what error are you getting? do you have an example excel file?

**Comment by oleibman** [comment]
Closing. No update in almost 3 years. Insufficient information in ticket to diagnose problem.
