### ISSUE TITLE
Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Riepilogo!B2 -> Riepilogo!B4 -> Formula Error: An unexpected error occured

### ISSUE THREAD

**Issue by wolly66** [PHPOffice/PhpSpreadsheet#182]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
I load an xlsx template
I put some test data in cells
Write the new file

### What is the current behavior?

When reading, get: Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Riepilogo!B2 -> Riepilogo!B4 -> Formula Error: An unexpected error occured

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

To reproduce this bug, first you need to solve the ISSUE #181 as I suggested.

The excel formula is: =SE(SOMMA(B4:B80)='Liste presenze'!K8;"  ";"ERRORE") in english =IF(SUM(B4:B80)='Liste presenze'!K8;"  ";"ERRORE")
To test you need an external excel file, that i attach

```php
<?php
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
//Load the file template
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('tabellaperassociazioni.xlsx');

$worksheet = $spreadsheet->getActiveSheet();
//insert test data in some cells
$worksheet->getCell('C3')->setValue('API GENOVA');
$worksheet->getCell('C5')->setValue('22/06/2017');
$worksheet->getCell('A11')->setValue('Messina');
$worksheet->getCell('B12')->setValue('Dario');
$worksheet->getCell('C11')->setValue('Italiano');
$worksheet->getCell('H11')->setValue('ARENZANO');

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xls');
//write the file
$writer->save('comunicazione.xls');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet = develop
PHP 7.0
[tabellaperassociazioni.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1094761/tabellaperassociazioni.xlsx)

**Comment by JosHonig** [comment]
Hi there, I think i have the same issue. 
when i use a formula with a reference to another sheet, it fails.

after i change the formula to a reference on the same sheet, it will pass... I think you are using different sheets also?

**Comment by wolly66** [comment]
Yes, in the template there are 2 sheets.

I solved, deleting the second sheet :-) and copying and pasting the first sheet, the one dinamically generated :-)

I know, it's not a solution, but it works :-)

**Comment by PowerKiKi** [comment]
@JosHonig if you are able to pinpoint exactly what goes wrong and find a fix, that would be very appreciated. Maybe the first step for that would be to reproduce the issue without external file, by creating a spreadsheet by code only.

**Comment by wolly66** [comment]
@PowerKiKi Ok, I'll do

**Comment by JosHonig** [comment]
the line below gives an error
=vlookup(A1,Sheet1!A:B,2,false)

and this one is working
=vlookup(A1,Sheet1!A1:B99999,2,false)

so refering to columns on another sheet is not working for me... (both creating from scratch and creating new)

**Comment by PieterCappelle** [comment]
Any update on this? Having the same problem with vlookup.

**Comment by PowerKiKi** [comment]
Nothing new from me unfortunately. I'm afraid my last comment still stands and one of you will have to debug it further to find a fix

**Comment by adriencohen** [comment]
I have the same exception, I'm not sure it's the same issue but I'll post what I founded so far:

I load this file : [dede.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/1264841/dede.zip)
And then I try to save it and then I get basically the same error.

I'm maybe completely wrong but something looks odd to me when I try to debug it. I found that the formula that I get with 
`$pCell->getValue()` line 2556 in Calculation.php is different from what is really shown in excel

EXCEL:
`=IF(AND(BC3>50,OR(HM3>12,GY3>90)),"CPC",IF(AND(BC3<50,AND(HM3<12,GY3<90)),"GC","PAC"))
`
PhpSpreadsheet:
`=IF(AND(BC3>50,OR(3>12,3>90)),"CPC",IF(AND(BC3<50,AND(3<12,3<90)),"GC","PAC"))`

As you can see "HM" and "GY" are gone and an ascii character appeared (0x1D). I don't really understand what _parseFormula in Calucation.php but from what I tried to debug I would say it blocks on this character.

**Comment by enoola** [comment]
same issue here, when we are refering to another sheet in a formula =COUNTIF(Data!K:K;">=30"),
we get the issue reported :/

**Comment by dwainscheeren** [comment]
I also still got this error when refering to another sheet in the same file

**Comment by Peterbins** [comment]
Still Same here : 

works:
 $sheet->setCellValue('D15', "=SUM('name sheet!AL1:AL99999)");

error : 
 $sheet->setCellValue('D15', "=SUM('name sheet!AL:AL)");

**Comment by janchimugica** [comment]
Any updates on this? :)

**Comment by MarkBaker** [comment]
Most of the examples here are using column or row ranges, which are not cleanly supported by PHPSpreadsheet's calculation engine; references to other sheets in formulae should work, unsupported column or row ranges do not, whether in the same sheet or another sheet

**Comment by arimourao** [comment]
Unfortunately this is still a living issue. Reference to other sheet in the same file crashes. It is not out of column or row ranges. Any workaround this?

**Comment by arimourao** [comment]
The error seems to be when saving the file, the PHPSpreadsheet tries to read the formulae. I saw that on PHPExcel, lots of people had this problem but were able to solve it calling the method `$objWriter->setPreCalculateFormulas(false);`

Is there anything like this for PhpSpreadsheet? Couldn't find in the docs.

**Comment by kashifumar** [comment]
ok, found the issue, this happens when the formula in some cell is invalid, that would in normal excel case give an error or in some case excel auto-corrects it so you cant re-produce the issue in excel in some case. in my case, some cells contained values like
=CONCATENATE("+", "2.")
which evaluates to +2. and there cant be a decimal at the end of the value in the cell

So debug your data

**Comment by luckdragon** [comment]
so, why is it on the OLD PHPExcel I was able to read the formula: =VLOOKUP(A3,'Current Inventory'!A:B,2,FALSE)
but on PhpOffice (which is supposed to be better), I get an exception and have to change my formula to look like:
=VLOOKUP(A3,'Current Inventory'!A1:B9999,2,FALSE).. this becomes a real pain for an existing spreadsheet with 5 worksheets and at least 5000 lines on each sheet..  

isn't there a simple way to edit the code to say something like..

      explode on ":" 
         if there's no cell # on the first result then make it minRow, 
         if there's no result on the 2nd result then make it maxRow?

**Comment by allenc71** [comment]
I had a similar error message showing "Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception:". 
The field that was in question was having issue saving into Excel cell, and after testing, I found not all values fetched cause error.
The values were fetched from database using while loop. Excel must have had pre-determined the type of the cell after fetching multiple values, then decided to throw error on a value that it thinks it doesn't match the type. I think this was the cause because after I setCellValueExplicit to TYPE_STRING for that cell, the error had disappeared.

**Comment by maximnl** [comment]
excel by default (an option) stores all the data from the cells as you see it. if you turn of evaluation engine off on open, you still get your data in cells on open as you left it. so is there a way to turn of evaluation and just load the data?
i tried $reader->setReadDataOnly(true);
did not notice any effect, the sheet with vlookup formulas not loading.

**Comment by MagicStino** [comment]
To save people time: I tested your code on the latest composer version and it works flawless.

**Comment by oleibman** [comment]
@MagicStino Thank you for confirming this and the other issue where you posted a similar comment.

**Comment by stikendra07** [comment]
Remove the Extra Worksheet from their and convert the file into CSV Formate it works
