### ISSUE TITLE
function namedRangeToArray cause crash

### ISSUE THREAD

**Issue by lxjillusion** [PHPOffice/PhpSpreadsheet#1821]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
1. Defined a cell range values in one sheet
2. Return the cell values in array

### What is the current behavior?
1. Crashed while call this function.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
    public function namedRangeToArray($pNamedRange, $nullValue = null, $calculateFormulas = true, $formatData = true, $returnCellRef = false)
    {
        $namedRange = NamedRange::resolveRange($pNamedRange, $this);
        if ($namedRange !== null) {
            $pWorkSheet = $namedRange->getWorksheet();
            **$pCellRange = $namedRange->getValue();**
            _**// Upper line may return $pCellRange as format "SheetName!$B$1:$B$5", this cause function Coordinate::rangeBoundaries($pCellRange) parsed the the range as ["SheetName!$B$1", "$B$5"], then function coordinateFromString("SheetName!$B$1") cause crash**_

            return $pWorkSheet->rangeToArray($pCellRange, $nullValue, $calculateFormulas, $formatData, $returnCellRef);
        }

        throw new Exception('Named Range ' . $pNamedRange . ' does not exist.');
    }

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet Ver : V1.16.0
PHP Ver: 7.4.10

**Comment by lxjillusion** [comment]
PhpSpreadSheet V1.14.1 is ok on namedRangeToArray, since the range resolved as "B1:B5", no sheet name.
For V1.16.0, the range resolved as "SheetName!$B$1:$B$5", the "SheetName" cause crash

**Comment by oleibman** [comment]
Closing. Function namedRangeToArray seems to work correctly since at least 1.17.1.
