### ISSUE TITLE
Number Format GBP Formats

### ISSUE THREAD

**Issue by philipdarlo** [PHPOffice/PhpSpreadsheet#1824]
This is:

```
- [x] a feature request
```

### What is the expected behavior?
Number formats file should store currency for GBP £

### What is the current behavior?
Only formats for USD and EUR are stored.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

$spreadsheet->getActiveSheet()->getStyle("A1")->->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_ACCOUNTING_GBP);

### Which versions of PhpSpreadsheet and PHP are affected?
"phpoffice/phpspreadsheet": "1.16",
"php": 7.3.26

**Comment by MarkBaker** [comment]
The pre-defined formats are those generally supported within MS Excel's set of predefined formats, which does not include UK/GBP. These are simply a set of pre-defined constants; but there is nothing to prevent you creating your own constant in your own scripts.

I am currently working on a set of Wizards/Helpers for building Number, Currency and Accounting format masks, that you might find helpful.

**Comment by philipdarlo** [comment]
Ah must be because I am a UK excel user which is why I thought it was predefined. I did add it as a feature request incase.  I actually did my own constant and worked around it that way, I was thinking about future users was all. 

Your new feature sounds really cool! I will mark this as closed.
