### ISSUE TITLE
setValueExplicit(true, DataType::TYPE_BOOL) results in a cell with =TRUE() function

### ISSUE THREAD

**Issue by ZaneCEO** [PHPOffice/PhpSpreadsheet#1833]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

Also reported here: https://stackoverflow.com/questions/66121500/how-can-i-set-a-cell-to-truefalse-with-phpspreadsheet

### What is the expected behavior?

Given this code:

```
$sheet->getCell('A1')
        ->setValueExplicit(true, DataType::TYPE_BOOL);
```

I expect the cell to contain a `TRUE` value, type: Boolean.

### What is the current behavior?

I get a cell with a function  `=TRUE()`

![](https://i.stack.imgur.com/kFlab.png)

The cell is type: Number:

![](https://i.stack.imgur.com/IYNsk.png)

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Import the core class of PhpSpreadsheet
use PhpOffice\PhpSpreadsheet\Spreadsheet;

// Import the Xlsx writer class
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Create a new Spreadsheet object
$spreadsheet = new Spreadsheet();

// Retrieve the current active worksheet
$sheet = $spreadsheet->getActiveSheet();

// Set cell AA with a "True" boolean value
$sheet->getCell('A1')->setValueExplicit(
    true,
    \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_BOOL
);

// Write a new .xlsx file
$writer = new Xlsx($spreadsheet);

// Save the new .xlsx file
$writer->save('create-xlsx-files-with-explicit-cell-datatype.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?

 1.16.0, I'm opening the generated XLSX file with LibreOffice Calc 7.1 (I also tried with 7.0).

**Comment by MarkBaker** [comment]
Opening either a saved xlsx or xls file using MS Excel, the value is a boolean; Opening a saved ods file with LibreOffice, the value is a boolean. This all suggests that there is no issue in PHPSpreadsheet.

The only way I am able to recreate this is by saving an xlsx file which I then open using LibreOffice, which suggests that the problem is a bug in the LibreOffice import of xlsx files.

**Comment by ZaneCEO** [comment]
Hi @MarkBaker ! Thanks for you reply.

I had the chance to open the generated file with Excel 2019 and you're right: the TRUE/FALSE are handled correctly

![zShot_1613057497](https://user-images.githubusercontent.com/5873880/107658894-e480dd00-6c86-11eb-8ce5-5430bbadba86.png)

So, yeah, this is probaly a bug in LibreOffice.

Thanks for checking this out with me.
