### ISSUE TITLE
$autoFilter->showHideRows(); will not work

### ISSUE THREAD

**Issue by fglueck** [PHPOffice/PhpSpreadsheet#1835]
Filter definition working well, if I open the Excel-File. The Filter-Column is defined, the value I set to the filter is active. 
But the Excelfile shows all rows, the filter is not active.
I try to activate the filter with:
$autoFilter->showHideRows();

But it does not work. If I click "Filter erneut anwenden" in Excel, the filter will work fine.

`
      $autoFilter = $this->sheet->setAutoFilter("A{$this->filter_row}:{$this->column_count_char}{$this->filter_row}")->getAutoFilter();
      # Filter aus den Parametern auf Excel übertragen
      if(isset($this->params['xls_filter']) and is_array($this->params['xls_filter'])) {
          foreach($this->params['xls_filter'] as $key => $value) {
            if(!empty($value)) {
              $value = str_replace(['--'], '', $value);
              $filter = $autoFilter->getColumn(Coordinate::stringFromColumnIndex((int)$key+1));
              $rule = $filter->setFilterType(\PhpOffice\PhpSpreadsheet\Worksheet\AutoFilter\Column::AUTOFILTER_FILTERTYPE_FILTER)->createRule();
             $rule->setRule(\PhpOffice\PhpSpreadsheet\Worksheet\AutoFilter\Column\Rule::AUTOFILTER_COLUMN_RULE_EQUAL, $value);

          }
        }
     }
    $autoFilter->showHideRows();
`
I try this befor filling the xlsx with data and after, with the same behaviour.

Thanks
Frank

**Comment by stdrew** [comment]
Experiencing same issue.  Seems like no matter how or where I set up the autofilter and the filter rules, "appying" them (hiding affected rows) does not work via $autoFilter->showHideRows()

like original poster, I can see the filter rules (checked boxes) are working in Excel, just not applying. Thanks.

**Comment by oleibman** [comment]
There were some autofilter PRs applied after the last official release (18.0). If you run against master, do you still see the same problem?

**Comment by stdrew** [comment]
Thx for suggestion.  Tried on master but still a problem.

Anyone else experiencing this with $autoFilter->showHideRows() not hiding filtered rows?

Any suggested workaround to simulate opening an autofilter dropdown in Excel and clicking "ok" to apply it?

**Comment by oleibman** [comment]
Glad it's resolved now. Thank you for the confirmation.

**Comment by oleibman** [comment]
Should be resolved in Release 19.
