### ISSUE TITLE
Can't insert Rows

### ISSUE THREAD

**Issue by Shane-Gastmans** [PHPOffice/PhpSpreadsheet#1836]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Rows get added

### What is the current behavior?
 Uncaught Error: Call to a member function getHashCode() on null in /home/USER/php/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/ReferenceHelper.php:611

### What are the steps to reproduce?
        $spreads = IOFactory::load("excelfile.xlsx");
        $sheet = $spreads->getActiveSheet();
        $sheet->insertNewRowBefore(6);

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php

<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
        $spreads = IOFactory::load("excelfile.xlsx");
        $sheet = $spreads->getActiveSheet();
        $sheet->insertNewRowBefore(6);
```

### Which versions of PhpSpreadsheet and PHP are affected?
7.4.3
^1.16

**Comment by MarkBaker** [comment]
Unable to replicate
