### ISSUE TITLE
Undefined index in cell formula

### ISSUE THREAD

**Issue by ToleubekRauan** [PHPOffice/PhpSpreadsheet#1841]
This is:

```
- [ ] a bug report
```

Exception while calculating value
`
 PhpOffice\PhpSpreadsheet\Calculation\Exception:  sheetName !V32 -> sheetName ·!V30 -> sheetName ·!V27 -> Undefined index: G 
`
where G is range in formula 
`=ЕСЛИ($G$3/30>=I$3;0;ИНДЕКС('График проект'**!$G:$G;**ПОИСКПОЗ(I1;'График проект'!$D:$D;0);1))
`

Stack trace 
`
#0 /usr/share/nginx/html/blitz/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php(165): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()
#1 /usr/share/nginx/html/blitz/app/Helpers/ImportFiles.php(306): PhpOffice\PhpSpreadsheet\Cell\Cell->getFormattedValue()
#2 /usr/share/nginx/html/blitz/app/Helpers/ImportFiles.php(28): App\Helpers\ImportFiles->importOpiuSTB()
#3 /usr/share/nginx/html/blitz/app/Http/Controllers/ProjectsController.php(760): App\Helpers\ImportFiles->importFromFile()
#4 [internal function]: App\Http\Controllers\ProjectsController->tempCreate(Object(Illuminate\Http\Request))
#5 /usr/share/nginx/html/blitz/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
`

**Comment by MarkBaker** [comment]
PHPSpreadsheet doesn't always resolve column ranges (e.g. `$G:$G`) or row ranges (e.g. `$3:$3`) with a worksheet reference; but it can always resolve cell ranges if it's possible to modify our spreadsheet to use those instead (e.g. `$G1:$G1024`)
