### ISSUE TITLE
Problem with set border on merged cells

### ISSUE THREAD

**Issue by solinskip** [PHPOffice/PhpSpreadsheet#1845]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Expected behavior is to set border on all of merged cells from A1 to T1.

### What is the current behavior?
Border is set only on one cell A1. 

### What are the steps to reproduce?
Create new spreadsheet, merge cells A1:T1, set border bottom. 

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet->getActiveSheet()->mergeCells('A1:T1');

$spreadsheet->getActiveSheet()->getStyle('A1')->applyFromArray([
    'borders' => [
        'bottom' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => 'bfbfbf']
        ]
    ]
]);

$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save("file.xlsx");

### Which versions of PhpSpreadsheet and PHP are affected?
PHPSpreadsheet 1.16.0
PHP 7.3

**Comment by Trkzi-Omar** [comment]
**PhpSpreadsheet is doing exactly what you are asking it to do:**
This "merges" the cell, but it doesn't mean at all that they are combined/reduced to one cell (A1):

> ```php
> $spreadsheet->getActiveSheet()->mergeCells('A1:T1');
> ```

Now this sets the style for the A1 cell:

> ```php
> $spreadsheet->getActiveSheet()->getStyle('A1')->applyFromArray([
>     'borders' => [
>         'bottom' => [
>             'borderStyle' => Border::BORDER_THIN,
>             'color' => ['rgb' => 'bfbfbf']
>         ]
>     ]
> ]);
> ```

This is however how to edit the style for all the merged cell:
```php
$spreadsheet->getActiveSheet()->getStyle('A1:T1')->applyFromArray([
    'borders' => [
        'bottom' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => 'bfbfbf']
        ]
    ]
]);
```

**Comment by oleibman** [comment]
No update in 4 months. Suggested solution seems to answer question. Closing.
