### ISSUE TITLE
Opening an Excel2007 file throws a PHP Fatal Error

### ISSUE THREAD

**Issue by kanduvisla** [PHPOffice/PhpSpreadsheet#185]
This is a bug report.

### What is the expected behavior?

Opening an Excel2007 file using the most basic approach should work out of the box.

### What is the current behavior?

Using the latest version, it throws the following error:

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PhpOffice\PhpSpreadsheet\Reader\Excel2007::readStyle() must be an instance of stdClass, instance of SimpleXMLElement given, called in /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php on line 630 and defined in /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php:1880
Stack trace:
#0 /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php(630): PhpOffice\PhpSpreadsheet\Reader\Excel2007::readStyle(Object(PhpOffice\PhpSpreadsheet\Style), Object(SimpleXMLElement))
#1 /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/IOFactory.php(175): PhpOffice\PhpSpreadsheet\Reader\Excel2007->load('/vagrant/var/Ar...')
#2 /vagrant/app/code/xxx/Import/Model/ExcelManagement.php(45): PhpOffice\PhpSpreadsheet\IOFactory::load('/vagrant/var/Ar...')
#3 /vagrant/app/code/xxx/Import/Console/ValidateExcel.php(68): xxx\Import\Model\ExcelManagement->loadExcelFile('/vagrant/var/Ar...')
#4  in /vagrant/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Excel2007.php on line 1880
```

### What are the steps to reproduce?

This is the code that I'm using:

```php
$spreadSheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('sheet.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?

- PHP Version 7.0.20
- PhpSpreadSheet latest version (master)
- Excel for Mac 15.35

I'll see if I can attach a spreadsheet that throws this error. I cannot upload the current sheet because it's private data.

### Attachment:

I am able to reproduce the error with the following spreadsheet. It's basically my clients spreadsheet, but with all data deleted. Given the error message I assume it has something to do with the styling:

[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1135252/test.xlsx)

**Comment by PowerKiKi** [comment]
Latest version is on develop branch, master is not expected to work at this time. Please upgrade and try again.

**Comment by kanduvisla** [comment]
But... why?

Why is master not stable? Isn't this the other way around? I'm not very comfortable on having my project rely on a develop-branch.

**Comment by PowerKiKi** [comment]
PhpSpreadsheet is still under development and has not release at all yet. As soon as we release something master will be the "stable" branch though.

**Comment by kanduvisla** [comment]
Could you at least provide a tag that is 'stable enough' (`0.0.1` or something) so I can at least lock my project on a specific version?

**Comment by PowerKiKi** [comment]
While agree that not having any release is sub-optimal, it is not required to lock on a specific version. You can do that with something along the line of:

```sh
composer require "phpoffice/phpspreadsheet:dev-develop#fb12e82d62df6adf8efb734e799a250c0aada70a"
```
