### ISSUE TITLE
How to insert a picture into a cell?

### ISSUE THREAD

**Issue by MuGongziya** [PHPOffice/PhpSpreadsheet#1860]
When I insert the picture, it's not embedded in the cell.

![QQ截图20210218162728](https://user-images.githubusercontent.com/66168501/108328219-4bfad780-7207-11eb-9081-c338f34d7fcb.png)

**Comment by MarkBaker** [comment]
No, because Excel doesn't embed pictures in cells; they're "overlaid" above the cells, but linked to the cells.

When you add an image, you link it to a cell address:
```
// Add a drawing to the worksheet
$drawing = new Drawing();
$drawing->setName('PhpSpreadsheet logo');
$drawing->setDescription('PhpSpreadsheet logo');
$drawing->setPath(__DIR__ . '/../images/PhpSpreadsheet_logo.png');
$drawing->setHeight(36);
$drawing->setCoordinates('D24');
$drawing->setOffsetX(10);
$drawing->setWorksheet($spreadsheet->getActiveSheet());
```

Links the added image to cell address `D24`

**Comment by MuGongziya** [comment]
> 不可以，因为Excel不会将图片嵌入单元格中。它们“重叠”在单元格上方，但链接到单元格。
> 
> 添加图像时，将其链接到单元地址：
> 
> ```
> // Add a drawing to the worksheet
> $drawing = new Drawing();
> $drawing->setName('PhpSpreadsheet logo');
> $drawing->setDescription('PhpSpreadsheet logo');
> $drawing->setPath(__DIR__ . '/../images/PhpSpreadsheet_logo.png');
> $drawing->setHeight(36);
> $drawing->setCoordinates('D24');
> $drawing->setOffsetX(10);
> $drawing->setWorksheet($spreadsheet->getActiveSheet());
> ```
> 
> 将添加的图像链接到单元格地址 `D24`

thanks

**Comment by MuGongziya** [comment]
Hello, I still have this situation after I use your code.
This is my code. Please help me to have a look.
![QQ截图20210219080701](https://user-images.githubusercontent.com/66168501/108438277-e996eb00-7289-11eb-9b4e-f7c20de16400.png)
![QQ截图20210219081128](https://user-images.githubusercontent.com/66168501/108438392-28c53c00-728a-11eb-92b0-269eccffd3bf.png)
I don't know what went wrong.
I tried wps2019 and wps2016, and the effect was the same.

**Comment by MuGongziya** [comment]
> No, because Excel doesn't embed pictures in cells; they're "overlaid" above the cells, but linked to the cells.
> 
> When you add an image, you link it to a cell address:
> 
> ```
> // Add a drawing to the worksheet
> $drawing = new Drawing();
> $drawing->setName('PhpSpreadsheet logo');
> $drawing->setDescription('PhpSpreadsheet logo');
> $drawing->setPath(__DIR__ . '/../images/PhpSpreadsheet_logo.png');
> $drawing->setHeight(36);
> $drawing->setCoordinates('D24');
> $drawing->setOffsetX(10);
> $drawing->setWorksheet($spreadsheet->getActiveSheet());
> ```
> 
> Links the added image to cell address `D24`

Hello, I still have this situation after I use your code.
This is my code. Please help me to have a look.
I don't know what went wrong.
I tried wps2019 and wps2016, and the effect was the same.
![QQ截图20210219080701](https://user-images.githubusercontent.com/66168501/108438597-8d809680-728a-11eb-913e-6ad35350329c.png)
![QQ截图20210219081128](https://user-images.githubusercontent.com/66168501/108438602-8f4a5a00-728a-11eb-9435-204b63cd74fd.png)

**Comment by MAKS-dev** [comment]
Please explain what you want to do and what you think is wrong.
It seems correct, the result is what your code should do.
Please note that this library still has a (very old) bug when using the same image multiple times, see #1153

**Comment by MuGongziya** [comment]
> 请说明您想做什么和您认为错了。
> 似乎正确，结果就是您的代码应该执行的操作。
> 请注意，当多次使用同一张图片时，该库仍存在一个（很旧的）错误，请参阅[＃1153](https://github.com/PHPOffice/PhpSpreadsheet/issues/1153)

I mean, after using the code you provided. This is still the case: the picture overlaps above the cell. I loop the contents of the database into the cells. The image is stored in the server.

**Comment by MarkBaker** [comment]
That's the point; Excel does not store its images in the cells, but in a layer on top of the cell; so yes, images can overlap unless you size them correctly so that they "fit" the cell dimensions

**Comment by MuGongziya** [comment]
Okay,&nbsp;I&nbsp;already&nbsp;know&nbsp;what&nbsp;to&nbsp;do.&nbsp;I&nbsp;will&nbsp;set&nbsp;the&nbsp;size&nbsp;of&nbsp;the&nbsp;cell&nbsp;to&nbsp;resize&nbsp;the&nbsp;inserted&nbsp;picture.&nbsp;But&nbsp;when&nbsp;I&nbsp;insert&nbsp;a&nbsp;picture,&nbsp;office&nbsp;retains&nbsp;the&nbsp;aspect&nbsp;ratio&nbsp;of&nbsp;the&nbsp;picture.&nbsp;Can&nbsp;PhpSpreadsheet&nbsp;resize&nbsp;the&nbsp;picture&nbsp;to&nbsp;insert&nbsp;it&nbsp;into&nbsp;the&nbsp;cell&nbsp;at&nbsp;will?


---Original---

**Comment by MuGongziya** [comment]
> 这才是重点; Excel不会将其图像存储在单元格中，而是存储在单元格顶部的一层中。所以是的，除非您正确调整尺寸，以使它们“适合”像元尺寸，否则图像可能会重叠

Okay, I already know what to do. I will set the size of the cell to resize the inserted picture. But when I insert a picture, office retains the aspect ratio of the picture. Can PhpSpreadsheet resize the picture to insert it into the cell at will?    
Thank you very much for your help. Thank you.
In fact, I am Chinese. I chat with you through translation software.

**Comment by Mymko** [comment]
The Drawing class has height and width attributes.
```
$drawing->setHeight($value);
$drawing->setWidth($value);
```

You might be helped by displaying a picture in a comment (when hovering over a cell), but this functionality is not implemented.

**Comment by oleibman** [comment]
Closing. No update since March, and the instructions already provided seem adequate. Also, PR #2422 now allows use of image with comments.

**Comment by ecns-bdavid** [comment]
Hi this isn't really resolved. In Excel you can in fact place an image inside of a cell. You can do this by right-clicking on an image in Excel and selecting "Place in cell". The image is treated like other in cell data and can be aligned etc at the cell level.

Is there a corresponding method to place an image in a cell like Excel?

**Comment by oleibman** [comment]
We are aware that Excel recently started to allow this. No, we have not yet caught up with it. A current open version of this issue is #4034.
