### ISSUE TITLE
I couldn't get the text data inside, please help.

### ISSUE THREAD

**Issue by BeycanDeveloper** [PHPOffice/PhpSpreadsheet#1861]
It always turns an object to me, but all I want is to get the text data inside, I examined the documentation, but I couldn't find what I was looking for. Please help.

For example, there is no method called getTextData () or something? It will print out the text to me inside.

**Comment by MarkBaker** [comment]
What always turns into an object for you? What type of object?

**Comment by BeycanDeveloper** [comment]
Hello, I could not find the necessary methods in the document, but I reached the result with a google search.

https://github.com/PHPOffice/PHPPresentation

now I'm trying to get texts in ppt files with this but I'm failing.

**Comment by MarkBaker** [comment]
Perhaps asking on the PHPPresentation repo would be better than asking against the PHPSpreadsheet repo

**Comment by BeycanDeveloper** [comment]
Okay thank you.
