### ISSUE TITLE
Error: Call to a member function getHashCode() on null

### ISSUE THREAD

**Issue by ivanstan** [PHPOffice/PhpSpreadsheet#1872]
Got error 
```
Error: Call to a member function getHashCode() on null
```
In following code there is no check if `$definedName->getWorksheet()` returns `null`

https://github.com/PHPOffice/PhpSpreadsheet/blob/1318b90330773d852ee15c8b432a7e7175c4bd55/src/PhpSpreadsheet/ReferenceHelper.php#L611

while in definition of the method `getWorksheet`, `null` is listed as a possible outcome. 

https://github.com/PHPOffice/PhpSpreadsheet/blob/1318b90330773d852ee15c8b432a7e7175c4bd55/src/PhpSpreadsheet/DefinedName.php#L162

**Comment by MarkBaker** [comment]
Fixed
