### ISSUE TITLE
reduce dependencies - just using the reader?

### ISSUE THREAD

**Issue by Rello** [PHPOffice/PhpSpreadsheet#1877]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
PhpSpreadsheet + its composer dependencies is 5.7MB
I am just using the reader so I wonder if the codebase can be reduced?
e.g. the `writer` & `chart` section seem not to be relevant (.9MB).
Is there a chance to derive, which parts of PhpSpreadsheet and which libraries are required for just the reader?

thank you very much

**Comment by MarkBaker** [comment]
Not easily, and certainly not in a way that's convenient for users to pull through composer.

But disk costs aren't that expensive, surely; and the autoloading ensures that only classes that are actually used are loaded into memory
