### ISSUE TITLE
Corrupt XLSX file

### ISSUE THREAD

**Issue by robregonm** [PHPOffice/PhpSpreadsheet#188]
When I export files and the generated files are more than 60kB I get corrupted files in prod but they export fine locally, after compared the exact same export script (even same data, but different environments), the correctly generated file starts like this (generated locally and open without issues):

<pre>
50 4B 03 04 14 00 00 00  08 00 <b><i>0F 62</i></b> F5 4A 19 39  PK...... ...b.J.9
E2 60 93 01 00 00 EF <b><i>0C</i></b>  00 00 13 00 00 00 5B 43  .`...... ......[C
6F 6E 74 65 6E 74 5F 54  79 70 65 73 5D 2E 78 6D  ontent_T ypes].xm
6C CD 97 5F 4F 83 30 14  C5 DF FD 14 A4 AF 06 4A  l.._O.0. .......J
A7 CE 69 C6 F6 E0 F4 51  97 A8 1F A0 B6 97 41 06  ..i....Q ......A.
6D D3 76 FF BE BD 17 B6  A9 31 19 71 D9 12 FB 02  m.v..... .1.q....
21 70 CE F9 71 68 6E CA  70 BC AE AB 68 <b><i>09</i></b> D6 95  !p..qhn. p...h...
5A 65 84 25 29 89 40 <b><i>09</i></b>  2D 4B 35 CB C8 FB DB 53  Ze.%).@. -K5....S</pre>

But the corrupted file starts like this:

<pre>
50 4B 03 04 14 00 00 00  08 00 <b><i>43 64</i></b> F5 4A 19 39  PK...... ..Cd.J.9
E2 60 93 01 00 00 EF <b><i>20</i></b>  00 00 13 00 00 00 5B 43  .`.....  ......[C
6F 6E 74 65 6E 74 5F 54  79 70 65 73 5D 2E 78 6D  ontent_T ypes].xm
6C CD 97 5F 4F 83 30 14  C5 DF FD 14 A4 AF 06 4A  l.._O.0. .......J
A7 CE 69 C6 F6 E0 F4 51  97 A8 1F A0 B6 97 41 06  ..i....Q ......A.
6D D3 76 FF BE BD 17 B6  A9 31 19 71 D9 12 FB 02  m.v..... .1.q....
21 70 CE F9 71 68 6E CA  70 BC AE AB 68 <b><i>20</i></b> D6 95  !p..qhn. p...h ..
5A 65 84 25 29 89 40 <b><i>20</i></b>  2D 4B 35 CB C8 FB DB 53  Ze.%).@  -K5....S</pre>

The differences are very subtle and are <b><i>highlighted like this</i></b>.

I'm using PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (local) and 7.1.7-1+ubuntu14.04.1+deb.sury.org+1 (production)
And the installed extensions look similar. The only noticeable differences are the running Ubuntu versions (16.04 in my local environment and 14.04 in production) and the available memory (16GB local env, 512 MB in production)

I'm using the last PhpSpreadsheet `dev-master` version

Thoughts? Ideas?

**Comment by robregonm** [comment]
This issue also happened when I used PHP 5.6, but since recently I'm exporting a lot I noticed that issue

**Comment by robregonm** [comment]
In fact, I just tested, updating to the very last version and happen all the times. Any ideas?

**Comment by robregonm** [comment]
Btw, the files are decompressed correctly (e.g. unzip)

**Comment by robregonm** [comment]
After many tests, combination of formats (it was happening with all formats) and debugging, I found that It was due to Cloudflare minification script, it seems that Cloudflare doesn't detect the content of the files based on MIME type headers, but it minifies all the files (it doesn't care the format)
So, I disabled HTML minification and everything is working back again.

**Comment by maerni** [comment]
Guten Tag

Ich bin bis zum 7. August 2017 abwesend.

Ihre Nachricht wird nicht weitergeleitet.

In dringenden Fällen füllen Sie bitte unser Supportformular aus:

https://support.yourchoice.ch/

Mit freundlichen Grüssen

Michael Aerni, Software Engineer
________________________________

YourChoice Informatik GmbH
Mattenweg 15
2557 Studen BE
m.aerni@yourchoice.ch
www.yourchoice.ch
