### ISSUE TITLE
Catastophic failure when reading xslx file with empty cell data type

### ISSUE THREAD

**Issue by keikland** [PHPOffice/PhpSpreadsheet#1883]
The latest version of PhpSpreadsheet bombed when loading an Excel workbook downloaded from the web.  I traced this to the xlsx reader failing to capture that the cell type (and cell value) was empty.  Presumably the workbook must have been written by some utility.  Strangely,  the problem only manifested itself on a latest-gen Intel i9 CPU under Win10. 

I added this at line xlxs.pho line 661:
              if(empty($cellDataType)) {   // KE FIX: Ignore empty data types
                  ++$rowIndex;
                  continue;
              }

Additionally, I noticed that the read filter below incremented the row counter, but did not test for the outer loop then going outside of bounds.  At line 663 I added 

               $n = count($xmlSheet->sheetData->row);  // KE FIX: For overrun test fix

and below in the test for cell read filter:   

              ++$rowIndex;
              if($rowindex >= $n) break;  // KE FIX: Overrun test!

These changes resolved the problem with the non-standard workbook.

**Comment by keikland** [comment]
Here is an example file that produces the problem btw. - Option to load the Indices sheet with data only.
[mibgas.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6044131/mibgas.xlsx)

**Comment by keikland** [comment]
Incorrectly closed the issue.

**Comment by oleibman** [comment]
Unable to duplicate your problem with your file using the following code as I believe you instructed:
```php
        $reader->setReadDataOnly(true);
        $reader->setLoadSheetsOnly(['Indices']);
        $robj = $reader->load($infil);
```
No problem with release 16, 17.1, 18.0, or master. I am on Win10 like you, although my hardware is older than yours (Intel i7).

**Comment by oleibman** [comment]
Unable to duplicate. No update to ticket since June. Closing.
