### ISSUE TITLE
Samples not fully showing example data

### ISSUE THREAD

**Issue by binyata** [PHPOffice/PhpSpreadsheet#190]
This is:

- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
Be able to use samples

### What is the current behavior?
I cannot fully generate the sample examples because I am seeing these errors:
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/ryanlee/src/ocr-engine/deckard/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Helper/Sample.php on line 154
22:48:45 Write Xls format to <code>/var/folders/5n/04h9cqw16yn110g0cqz1tcqwpm0k15/T/phpspreadsheet/01_Simple.xls</code>  in 0.0240 seconds

### What are the steps to reproduce?
Follow the documents and set up your sample localhost. Go to localhost and try looking up any of the samples. Notice this error.

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by PowerKiKi** [comment]
This is unrelated to PhpSpreadsheet: https://stackoverflow.com/a/16765214/37706

**Comment by emmjk** [comment]
Am having hard time trying to do anything with this one as It displays nothing after read result , No error , no nothing . Tried to go through samples folder and run them files normally as I run normal php but am getting some 403 error .
