### ISSUE TITLE
Number formatting results in CR LF characters at end

### ISSUE THREAD

**Issue by serverdevil** [PHPOffice/PhpSpreadsheet#1924]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

I narrowed down an issue with an excel file to this. The value 826 formatted with ```#,##0.00 _€``` is resulting in a bad formatted value.

### What is the expected behavior?
```826.00<space><space>```

### What is the current behavior?
```826.00<space><space><CR><LF>```
As is content (verified that the last 2 chars are actually CR and LF)
```826.00 ��```

### What are the steps to reproduce?
```php
<?php

require __DIR__ . '/vendor/autoload.php';

echo PhpOffice\PhpSpreadsheet\Style\NumberFormat::toFormattedString(826, "#,##0.00 _€");

?>
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.17.1

**Comment by serverdevil** [comment]
Ignore.

**Comment by serverdevil** [comment]
Closed by mistake.

**Comment by MarkBaker** [comment]
Expected output from a mask of `#,##0.00 _€` should have been `826.00<space><space>€`

Fix implemented and merged to the master branch
