### ISSUE TITLE
The 'getFormattedValue()' method return format pattern instead of number formatted according to accounting number format

### ISSUE THREAD

**Issue by merapidev** [PHPOffice/PhpSpreadsheet#1929]
This is:
```
- [x] a bug report
```

### What is the expected behavior?
The method `getFormattedValue` will return:
- (79.3%) for cell D2
- 383.7% for cell D3
- (0.79) for cell E2

### What is the current behavior?
The method `getFormattedValue` return:
- ("#,##0.0%") for cell D2
- 110.1f% for cell D3
- ("#,##0.00") for cell E2

### What are the steps to reproduce?
Use attached excel file: 
[spreadsheet_test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6149069/spreadsheet_test.xlsx)

OR

Prepare excel file as shown below:
![image](https://user-images.githubusercontent.com/15861673/111312284-6b96eb80-865f-11eb-8a35-5296db10056c.png)

Formula for D2 and E2: =(B2-C2)/C2
Formula for D3 and E3: =(B3-C3)/C3

Formatting for D2 and D3:
![image](https://user-images.githubusercontent.com/15861673/111312549-b153b400-865f-11eb-8d99-39521554f30d.png)

Formatting for E2 and E3:
![image](https://user-images.githubusercontent.com/15861673/111312626-c7617480-865f-11eb-91c8-ee873b581b61.png)

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('spreadsheet_test.xlsx');
$sheet = $spreadsheet->getSheet(0);

$d2 = $sheet->getCell('D2')->getFormattedValue();
$d3 = $sheet->getCell('D3')->getFormattedValue();
$e2 = $sheet->getCell('E2')->getFormattedValue();
$e3 = $sheet->getCell('E3')->getFormattedValue();

file_put_contents('D2.txt', $d2);
file_put_contents('D3.txt', $d3);
file_put_contents('E2.txt', $e2);
file_put_contents('E3.txt', $e3);
```

### Which versions of PhpSpreadsheet and PHP are affected?
Phpspreadsheet: 1.17.1
PHP: 7.4.15

**Comment by MarkBaker** [comment]
Using the current master branch, I'm seeing the expected values for the Delta (`(0.79)` and `3.84`); but can confirm that there is an issue with the percentage format masks.

I'm already doing some work on the formatting code after an unrelated bugfix last night (related to the `_` placeholder in format masks), so I'll have a closer look tonight and try to identify the problem.

**Comment by merapidev** [comment]
Hi, did you identify the problem?

When the next release is expected?

**Comment by merapidev** [comment]
Hi,

I checked the formatting with new version (1.18) and there is small issue.
Expected value is `(79.3%)` for cell D2 but it return `(  79.3%)`.
