### ISSUE TITLE
listWorksheetInfo is broken for xlsx reader

### ISSUE THREAD

**Issue by rychkov-evgeniy** [PHPOffice/PhpSpreadsheet#1939]
This is:

```
- [*] a bug report
```

### What is the expected behavior?
Method listWorksheetInfo in Xlsx reader should return array of worksheets with metadata

### What is the current behavior?
Method listWorksheetInfo in Xlsx reader return empty array

### What are the steps to reproduce?
Everything works before

This
```php
<?php
    foreach ($xmlWorkbook->sheets->sheet as $eleSheet) {
```
was replaced on 
```php
<?php
    foreach ($xmlWorkbook->sheets->sheet->children() as $eleSheet) {                   
```
 children() returns an empty array

version: 1.17.1

In master branch everything works

**Comment by MarkBaker** [comment]
The bug has been fixed in master, and will be part of the next release

**Comment by rychkov-evgeniy** [comment]
@MarkBaker Ok, thanks. Is there a date for the next release?

**Comment by MarkBaker** [comment]
Likely before the end of the month. There's a few small fixes ready for the next release, including the `listWorksheetInfo()`; but we're also doing a lot of refactoring work behind the scenes that I'd like to get through into the next release as well

**Comment by rychkov-evgeniy** [comment]
Thanks!
