### ISSUE TITLE
Support for Color Scale on conditional formatting

### ISSUE THREAD

**Issue by binyata** [PHPOffice/PhpSpreadsheet#195]
Mainly I am trying to figure out if there is code that behaves like the conditional formatting in excel where you use the color scale to display values from one end to another in a transparent manner.

Does this library support that?

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
