### ISSUE TITLE
[Bug] Formatting doesn't seem to be working in some cases.

### ISSUE THREAD

**Issue by JulioPablo** [PHPOffice/PhpSpreadsheet#1972]
This is:

```
- [X] a bug report
```

### What is the expected behavior?

Formats are kept.

### What is the current behavior?

For example, take a number with the following format string `"\$#,##0.00_);[RED]"($"#,##0.00\)"` used to represent a USD amount, if it is not a negative number it should be displayed as follows `$1.00` 
if it is a negative number `($1.00)` and in red.

Currently, this format gets interpreted as a Date, this happens because the code that processes the color portion of the format, expects the color to be capitalized, but not all in upper case meaning, `[Red]` works but `[RED]` does not.

My proposed fix for this would be replacing the following line 

https://github.com/PHPOffice/PhpSpreadsheet/blob/6490c3ff0ae10b0e2e7649c119c186dcb3df28bf/src/PhpSpreadsheet/Style/NumberFormat/Formatter.php#L46

with 

```
        $color_regex = '/\\[(' . implode('|', Color::NAMED_COLORS) . ')\\]/i';
```

Essentially only adding a `i` after the end delimiter and making the regex case insensitive.
Back to how this causes the format to be taken as date, since the color portion is not separated from the actual format portion, later on the format looks something like `[RED]"($"#,##0.00")"`

which matches the following regex

https://github.com/PHPOffice/PhpSpreadsheet/blob/6490c3ff0ae10b0e2e7649c119c186dcb3df28bf/src/PhpSpreadsheet/Style/NumberFormat/Formatter.php#L137-L140

that's how we end up with the date formatting.

We can also see here the list of colors and how only the capitalized variant of the names are included here:

https://github.com/PHPOffice/PhpSpreadsheet/blob/a24ca09bd442ca2011b0d620f292232182426863/src/PhpSpreadsheet/Style/Color.php#L7-L16

I tested my proposed fix for the case sensitivity, this seemed to work, but there's still a issue. After the format gets sectioned off, the second section, for the negative numbers, ends up like this ` "($"#,##0.00")"`

This code here 

https://github.com/PHPOffice/PhpSpreadsheet/blob/6490c3ff0ae10b0e2e7649c119c186dcb3df28bf/src/PhpSpreadsheet/Style/NumberFormat/Formatter.php#L124

Changes the escaped characters, using `\` to quoted characters `"` that's how we end up with ` "($"#,##0.00")"`

but later on here

https://github.com/PHPOffice/PhpSpreadsheet/blob/6490c3ff0ae10b0e2e7649c119c186dcb3df28bf/src/PhpSpreadsheet/Style/NumberFormat/Formatter.php#L142-L143

We have a `if` statement that checks if the format string starts and ends with `"`, it does not do any more further processing and sets the format string as the value, this `if` I do not understand, why is it there, what purpose does it serve? 

So, essentially I'm seeing two issues 

1. Colors in formats are tokenized/found in a case sensitive way
2. The current logic in which any format string starting and ending with quotes is used as the value, is wrong.

My proposed fixes are 

1. Updating the regex as previously specified
2. Removing that if statement with the quote-checking logic, but this is probably not the right solution, since I have no idea what that is there for.

for some clarity, with the processed format string for a negative number in this case being `""($"#,##0.00")""` the following is happening:
![image](https://user-images.githubusercontent.com/33587721/112897593-0e5a5b80-909d-11eb-984c-631d706e57f3.png)

### What are the steps to reproduce?

If you want to reproduce this, try to read the formatted values of the following spreadsheet 
[Test_Sheet.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6224424/Test_Sheet.xlsx)

If done with the current code, a combination of a date + a format string will be read instead of the negative number.
After the color comparison is made to be case insensitive, the format string alone is displayed instead of the negative number.

### Which versions of PhpSpreadsheet and PHP are affected?
I tested this on 1.16 (via Laravel Excel) but the problematic code, which I linked here is clearly still present on the latest version.

**Comment by JulioPablo** [comment]
@MarkBaker Hi! I just checked the blame and noticed you edited this file, was wondering if you could help me understand this if statement https://github.com/PHPOffice/PhpSpreadsheet/blob/6490c3ff0ae10b0e2e7649c119c186dcb3df28bf/src/PhpSpreadsheet/Style/NumberFormat/Formatter.php#L142-L143

:)

**Comment by MarkBaker** [comment]
I'm assuming that `"\$#,##0.00_);[RED]"($"#,##0.00\)"` should be `"\$#,##0.00_;[RED]\"(\$\"#,##0.00\")\""` in a PHP script

That test is there to handle masks like `[Green]"Positive";[Red]"Negative";[Blue]"Zero"`, where the numeric value is simply replaced by a quoted string, which as also perfectly valid in MS Excel.

It's an over-simplistic test, assuming that the leading and trailing quotes are simply wrapping a complete string; and doesn't check that the endquote for your leading quote is inside the string`"(\$\"#,##0.00\")\"`, and that the startquote for the ending quote is also inside the string.

The fix is probably over-simplistic as well, but a simple check to see if the quotes at the beginning and end are simply wrapping a single string:
```php
if (substr($format, 0, 1) === '"' && substr($format, -1, 1) === '"' && substr_count($format, '"') === 2) {
    $value = substr($format, 1, -1);
```
which wouldn't handle escaped quotes `""` inside a quoted string (though that is probably an edge case

`[Green]"I said ""Hello""";[Red]"You said ""Goodbye""";[Blue]"We all said ""quoted quotes inside quotes are a real pain, especially with regexp"""`

**Comment by JulioPablo** [comment]
> I'm assuming that `"\$#,##0.00_);[RED]"($"#,##0.00\)"` should be `"\$#,##0.00_;[RED]\"(\$\"#,##0.00\")\""` in a PHP script
> 

I don't think this is the correct format `"\$#,##0.00_;[RED]\"(\$\"#,##0.00\")\""`  because as I understand it the backslashes which are used to denote the escaped characters, in this case the `$` and the `(` & `)` are replaced by double quotes, so the conversion in this example goes like 

- `\$` -> `"$"`
- `\(` -> `"("`
- `\)` -> `")"`

So the unexpected behavior is because the negative section of the format ends up as a string that starts & ends with quotes, which are used to escape the characters, but they're not part of the actual format.

So **I think**, I might be wrong, that the actual correct format we should be getting after replacing the `\` is `"($"#,##0.00")"` which we **are** currently getting, so I would say this is not a issue.

>which wouldn't handle escaped quotes "" inside a quoted string (though that is probably an edge case
>
>[Green]"I said ""Hello""";[Red]"You said ""Goodbye""";[Blue]"We all said ""quoted quotes inside quotes are a real pain, especially >with regexp"""... although a quick experiment suggests that MS Excel strips quotes inside the mask, even if they're escaped as >double quotes (not documented behaviour)
> 

Which if I understand correctly, would mean your solution to the `if` statement would be sufficient as is, as it would be behaving just as excel? :)

**Comment by oleibman** [comment]
Sorry, did not see your message till just now. Seems like you already solved the problem without my involvement.

**Comment by oleibman** [comment]
Is it okay to close this issue?

**Comment by oleibman** [comment]
Fixed by PR 1978.
