### ISSUE TITLE
Fatal error: Uncaught exception 'PHPExcel_Exception' with message 'Invalid cell coordinate' related to Workbook name

### ISSUE THREAD

**Issue by BlackPage05** [PHPOffice/PhpSpreadsheet#198]
Hi there,
I'm encountering a problem I cannot seem to be able to resolve upon trying to save a xlsx file based on the attached xlsx source

Here is the stack trace of the error 

Fatal error: Uncaught exception 'PHPExcel_Exception' with message 'Invalid cell coordinate 'EAF-CLAN'' in /var/www/html/inc/lib/phpexcel/classes/PHPExcel/Cell.php:590
Stack trace:
#0 /var/www/html/inc/lib/phpexcel/classes/PHPExcel/Cell.php(643): PHPExcel_Cell::coordinateFromString(''EAF-CLAN'')
#1 /var/www/html/inc/lib/phpexcel/classes/PHPExcel/Cell.php(618): PHPExcel_Cell::absoluteCoordinate(''EAF-CLAN'')
#2 /var/www/html/inc/lib/phpexcel/classes/PHPExcel/Writer/Excel2007/Workbook.php(331): PHPExcel_Cell::absoluteReference(''EAF-CLAN'')
#3 /var/www/html/inc/lib/phpexcel/classes/PHPExcel/Writer/Excel2007/Workbook.php(308): PHPExcel_Writer_Excel2007_Workbook->_writeDefinedNameForNamedRange(Object(PHPExcel_Shared_XMLWriter), Object(PHPExcel_NamedRange))
#4 /var/www/html/inc/lib/phpexcel/classes/PHPExcel/Writer/Excel2007/Workbook.php(277): PHPExcel_Writer_Excel2007_Workbook->_writeNamedRanges(Object(PHPExcel_Shared_XMLWriter), Object(PHPExcel))
#5 /var/www/html/inc/lib/phpexcel/classes/PHPExcel/Writer/Excel2007/Workbook.php( in /var/www/html/inc/lib/phpexcel/classes/PHPExcel/Cell.php on line 590

And here is the xlsx source file

[bc_sfr_fibre.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1215666/bc_sfr_fibre.xlsx)

What the required php code does is : 

Open the source file
Update values in certain cells
Save the result as a new xlsx file

The problem il located when trying to save the result file : 

`$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
print "go";
$objWriter->save($C->path() . $Final_File);
print "done";
`
Go is displayed, done is never reached

I've been trying to find the error for weeks but can't seem to grasp it...

Thx in advance

**Comment by PowerKiKi** [comment]
Unfortunately this is the wrong project, you are using PHPExcel, not PhpSpreadsheet. Try to reproduce your issue without the need of your source xlsx file and re-submit over there: https://github.com/PHPOffice/PHPExcel
