### ISSUE TITLE
[bug] getPageMargins()->setTop,Right,Left,Bottom .nothing to do.

### ISSUE THREAD

**Issue by smallwl** [PHPOffice/PhpSpreadsheet#1991]
This is:

```
- [ ] a bug report
```

### What is the expected behavior?
the page margin will be set.

### What is the current behavior?
open the hello.xlsx file , nothing to do.

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$sheet = $spreadsheet->getActiveSheet();

$sheet->getPageMargins()->setTop(1);
$sheet->getPageMargins()->setRight(0.75);
$sheet->getPageMargins()->setLeft(0.75);
$sheet->getPageMargins()->setBottom(1);

$writer = new Xlsx($spreadsheet);
$writer->save('hello.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
php7.4.15 , office 2016 , PhpSpreadsheet 1.17

**Comment by oleibman** [comment]
Looks as expected to me. File, Print, shows Custom Margins, which further show:
![image](https://user-images.githubusercontent.com/10341515/113802146-08085700-970f-11eb-943b-6ccfacdceabf.png)
Do you see something different?
