### ISSUE TITLE
Error with embedded IF function in another IF when the returnIfTrue parameter is empty in the embedded IF. 

### ISSUE THREAD

**Issue by yowaiOtoko** [PHPOffice/PhpSpreadsheet#2002]
This is:

```
- [x] a bug report
```
Error with embedded IF function in another IF when the returnIfTrue parameter is empty in the embedded IF. 

### What is the expected behavior?
The following formula should work
=IF(5>4,4,IF(5=6,,6))

### What is the current behavior?

An exception with the following message is thrown
Sheet1!C6 -> internal error

### Which versions of PhpSpreadsheet and PHP are affected?
php 4.2
PhpSpreadsheet 1.17.1

**Comment by MarkBaker** [comment]
This issue is related to the code implemented for the "lazy" evaluation of `IF`s.

As a temporary measure, you can disable lazy evaluation before executing any calculation, or saving the spreadsheet using:
```php
    $calculationEngine = Calculation::getInstance($spreadSheet);
    $calculationEngine->disableBranchPruning();
```
where `$spreadSheet` is your Spreadsheet instance

**Comment by MarkBaker** [comment]
Note to self that this is still an issue when branch pruning is enabled

**Comment by nastasache** [comment]
I also have some formulas with lot of nested IFs falling on internal error. Thank you, this workaround works.
