### ISSUE TITLE
FreezePane not working in Ods documents

### ISSUE THREAD

**Issue by pszalko** [PHPOffice/PhpSpreadsheet#2013]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
This code should freeze row 1 in Ods document:
```
$sheet->freezePane('A2');
```

### What is the current behavior?
First row is not frozen.

### What are the steps to reproduce?
1. Select current sheet.
2. Freeze row as in code sample above.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'hello world!');
$sheet->freezePane('A2');

$filename = tempnam('/tmp', 'export_');
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Ods($spreadsheet);
$writer->save($filename);
```

### Which versions of PhpSpreadsheet and PHP are affected?
I'm using: 1.17, didn't test earlier versions.

**Comment by MarkBaker** [comment]
At the moment, FreezePane is only supported by the Xls and Xlsx Readers and Writers; Ods has rather a awkward data structure for frozen panes, I'll need to investigate further just how it's defined to see how practical it is to implement.
