### ISSUE TITLE
Unable to parse Excel SUMIFS formula and/or named ranges within formula

### ISSUE THREAD

**Issue by treadmillian** [PHPOffice/PhpSpreadsheet#203]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question

### What is the expected behavior?
Code should return an array of calculated values (decimals).  The spreadsheet is commercially sensitive and it's not possible to reduce or anonymise the data without breaking the spreadsheet.

Will be happy to supply spreadsheet directly to developer, when/if requested.

### What is the current behaviour?
PhpSpreadsheet seems to be unable to parse an Excel =SUMIFS() formula and perhaps unable to also resolve named ranges, for example:

`=SUMIFS(INDEX(a_InputData,MATCH($B12,l_InputDataTitles,0),),l_Years,C$9,l_Quarters,C$8)`

The spreadsheet does parse without any errors, however, all values are returned as an array of 0.00.

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;

$reader = IOFactory::createReaderForFile($filename);
$reader->setLoadAllSheets(true);
$reader->setIncludeCharts(false);
$spreadsheet = $reader->load('test.xlsx');

$spreadsheet->setActiveSheetIndexByName('#5 data');
$data = $spreadsheet->getActiveSheet()->rangeToArray('C12:AT12', true, true, true, false);
\var_dump(data);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: 1.0.0-beta

php --version
PHP 5.6.25 (cli) (built: Oct 21 2016 17:57:17)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by GreatHumorist** [comment]
Can you attach a test file so that we can see where the bug occurred, cause your formula has some unclear definition like 'a_InputData' and so on.

**Comment by treadmillian** [comment]
I cannot publicly supply the file due to commercial sensitivity, I can private supply the file to you if you let me know where I can send it to you in a secure/private means and if you agree to destroy it after you have resolved, or not, the issue.

The spreadsheet is very complicated and hence why I can't really give you a minimised version of it.

What I have managed to do in order to start resolving the issue is to deal with any `#DIV/0` errors in the spreadsheet.  This has been done, and I get this specific error hundered of times: 

`
Warning: array_keys() expects parameter 1 to be array, double given in /data/kevin.smith/crt/develop/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation.php on line 3416
PHP Warning:  array_keys() expects parameter 1 to be array, null given in /data/kevin.smith/crt/develop/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation.php on line 3416
`

`
Warning: array_keys() expects parameter 1 to be array, null given in /data/kevin.smith/crt/develop/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation.php on line 3416
PHP Warning:  array_shift() expects parameter 1 to be array, null given in /data/kevin.smith/crt/develop/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation.php on line 3417
`

This does manage to give me the following data, which is better than zeros I guess.
```json
"data":[7164.99,7164.99,7164.99,7164.99,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
```
However, the resolved formulas in the spreadsheet that gives the above numbers are completely wrong.  I also cannot find any number in the spreadhseet such as; `7164` or `7164.99`.

The data should be as shown below and as viewed in the spreadsheet.

```json
"data":[726.586, 660.403875, 632.604479, 536.608225, 451.598508, 384.720508, 389.8475, 351.25175, 236.52725, 168.2445, 164.681, 199.489, 168.9935, 115.556, 84.151, 53.925, 124.694, 96.558, 59.826, 50.515, 13.6355, 12.3141, 11.089, 10.6825, 12.567, 11.3079999999999, 11.1665, 11.1134999999999, 6.78999999999998, 5.41249999999999, 6.07749999999999, 6.301, 5.61899999999998, 7.08899999999998, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

**Comment by GreatHumorist** [comment]
You can send me a test file which is not include sensitive information to my email<GreatHumorist@gmail.com>.
And now I'm going bed because the time is 1.am where I live. Tomorrow I will help you to solve the problem.

**Comment by treadmillian** [comment]
@GreatHumorist Have sent you an email as requested, here's the content of that email for reference:
 
Attached are two of the same spreadsheets, one using the Excel function `SUMIFS()` and the other `SUMPRODUCT()`.  The tab the data is coming from is `#5 data` as you can see from the script.
 
The `SUMPRODUCT()` spreadsheet will produce the following errors and output data as reported previously, but the formulas resolve to the wrong numbers.

```
Warning: array_keys() expects parameter 1 to be array, double given in /data/kevin.smith/crt/develop/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation.php on line 3416 PHP Warning: array_keys() expects parameter 1 to be array, null given in /data/kevin.smith/crt/develop/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation.php on line 3416
Warning: array_keys() expects parameter 1 to be array, null given in /data/kevin.smith/crt/develop/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation.php on line 3416 PHP Warning: array_shift() expects parameter 1 to be array, null given in /data/kevin.smith/crt/develop/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation.php on line 3417
```
 
The `SUMIFS()` spreadsheet produces no errors, but all the data are zero’s.
 
```php
<?php

require \dirname(__DIR__) . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;

$filename=[];
$filename[] = __DIR__ . '/github_SUMPRODUCT.xlsx';
$filename[] = __DIR__ . '/github_SUMIFS.xlsx';

$reader = IOFactory::createReaderForFile($filename);
$reader->setLoadAllSheets(true);
$reader->setIncludeCharts(false);
$spreadsheet = $reader->load($filename[0]);

$spreadsheet->setActiveSheetIndexByName('#5 data');
$data = $spreadsheet->getActiveSheet()->rangeToArray('C12:AT12', true, true, true, false);
\var_dump($data);
```

**Comment by treadmillian** [comment]
@PowerKiKi Are you aware of this issue with `SUMIFS()` and `SUMPRODUCT()`?

**Comment by PowerKiKi** [comment]
@treadmillian I am not aware of anything about `SUMIFS` and `SUMPRODUCT`. But it might be easier for you to try to reproduce with unit tests to at least know if it is a calculation issue, or more a parsing issue. You'll find many example on how to structure tests in `tests/`.
