### ISSUE TITLE
The 'getFormattedValue()' doesn't format nubmers with space character modifier (underscore) in format code

### ISSUE THREAD

**Issue by merapidev** [PHPOffice/PhpSpreadsheet#2037]
I checked formatting of number cells that use standard currency format code. I spotted some issues. Some of them works properly on version `1.17.1` but non of them work properly on `dev-master`. I decided to report them to be sure that you are aware of them.

This is:

```
- [x] a bug report
```

NOTE: I will use " character to display white spaces.

### What is the expected behavior?

- `" € 11.70 "` for cell B2
- `"-€ 12.14 "` for cell B3
- `" € -   "` for cell B4
- `" test "` for cell B5

### What is the current behavior?

**Version 1.17.1**
- `" € 11.70 "` for cell B2 - **good**
- `"-€ 12.14 "` for cell B3 - **good**
- `"0"` for cell B4
- `"test"` for cell B5

**Version dev-master**
- `" -€ 11.70 -"` for cell B2
- `"-€ 12.14 -"` for cell B3
- `"0"` for cell B4
- `"test"` for cell B5

### What are the steps to reproduce?

Use attached excel file:
[currency_example.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6397556/currency_example.xlsx)

OR

Prepare excel file as shown below:
![image](https://user-images.githubusercontent.com/15861673/116530857-ca968400-a8de-11eb-8e42-2cc1079343e4.png)

Formatting for B2 and B3:
![image](https://user-images.githubusercontent.com/15861673/116531032-06314e00-a8df-11eb-9e6f-3e4622bb0fb7.png)

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('currency_example.xlsx');
$sheet = $spreadsheet->getSheet(0);

$b2 = $sheet->getCell('B2')->getFormattedValue();
$b3 = $sheet->getCell('B3')->getFormattedValue();
$b4 = $sheet->getCell('B4')->getFormattedValue();
$b5 = $sheet->getCell('b5')->getFormattedValue();

file_put_contents('B2.txt', sprintf('"%s"', $b2));
file_put_contents('B3.txt', sprintf('"%s"', $b3));
file_put_contents('B4.txt', sprintf('"%s"', $b4));
file_put_contents('B5.txt', sprintf('"%s"', $b5));
```

### Which versions of PhpSpreadsheet and PHP are affected?
Phpspreadsheet: 1.17.1 and dev-master
PHP: 7.4.15

**Comment by MarkBaker** [comment]
Thanks for drawing our attention to this. I'd done some fairly extensive refactoring of the number format masking code, and had managed to retain the sizing character to go with the `_` in the logic, rather than stripping it from the rendered result.

We'd never had any specific logic for handling a mask without digit placeholders for the zero value case, for the moment the logic I've put in for that is fairly hacky, but it will now handle it.

We've never had any special handling for text values, they're simply returned "as is" and that behaviour will remain for the moment.

**Comment by merapidev** [comment]
Epic! 

I tested in locally on all examples I've got and it works as expected.
Thanks for quick feedback.
