### ISSUE TITLE
Xlsx to PDF with barcode (using Mpdf) / or custom HTML tags

### ISSUE THREAD

**Issue by DPlachkov** [PHPOffice/PhpSpreadsheet#2043]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Transforming an excel document to pdf with a barcode by using text in a cell with specific font.

### What is the current behavior?
I have an xlsx document with a cell that is with a font code39 (free 3 of 9 extended) which is a barcode font. When trying to convert this to pdf using the Mpdf facade it does not work. 
For the MPDF library to work it needs a special barcode tag - https://mpdf.github.io/reference/html-control-tags/barcode.html
To do this we need to have a unique html tag inside of a cell - the only way to do this is to use RichText and the "HTML" helper, but it does not support custom tags as far as I can see
Is there a solution with which a PDF can be created with a Barcode using XLSX ( without including a barcode image as a drawing, but rather using the font and the field value)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load($templatePath);
$worksheet = $spreadsheet->getActiveSheet();
$worksheet->getCell('L11')->setValue($trackingCode);

 $writer = new Mpdf($spreadsheet);
$pdfName ='somename.pdf';
$writer->save($pdfName);
```

### Which versions of PhpSpreadsheet and PHP are affected?
"phpoffice/phpspreadsheet": 1.14.1
php 7.2.4 / +

**Comment by oleibman** [comment]
The Html (and therefore PDF) writer has a callback facility. You can call setEditHtmlCallback to set a callback which will edit the generated Html before it is output. So, if you can find the right place to insert your barcode tag, that could achieve your result. If you can't locate it by unique content, possibly you could add a comment to the cell you want to treat in this manner in order to be able to locate it.

**Comment by oleibman** [comment]
No update since April. Believe the suggestion addresses the issue.
