### ISSUE TITLE
getHighestRow() function returning 1048576 rows instead of 2, which leads to out of memory exception when using toArray()

### ISSUE THREAD

**Issue by awtyklo** [PHPOffice/PhpSpreadsheet#2051]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
$worksheet->getHighestRow() should return correct highest row = 2
(similar behaviour is with getHighestColumn() - example in steps to reproduce)

### What is the current behavior?
$worksheet->getHighestRow() returns highest row = 1048576

### What are the steps to reproduce?

You can use attached XLSX.
[import_test_example.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6407380/import_test_example.xlsx)

This is a 4 cell XLSX (2x2) saved by LibreOffice.

Just a few more notes about this file. This file has been initially created using phpspreadsheet writer and opened in LibreOffice, then removed couple of rows and saved again. When I'm saving this file as CSV or whatever other format using LibreOffice it works as expected (2 rows and 2 columns are present)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$filepath = "import_test_example.xlsx';
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($filepath);
$worksheet = $spreadsheet->getActiveSheet();
$highestRow = $worksheet->getHighestRow(); // 1048576, should be 2
$highestColumn = $worksheet->getHighestColumn(); // L, should be B
```

### Which versions of PhpSpreadsheet and PHP are affected?
Using 1.17.1
LibreOffice 6.4.7.2 (maybe it will help)

If you need more information just let me know. Thank you in advance.

**Comment by MarkBaker** [comment]
No!
The `getHighesRow()` (and corresponding `getHighestColumn()`) method will return the highest row number that contains "something", whether that something is an empty cell, a reference in print settings, a style, whatever.

The `getHighesDataRow()` will return the highest row with a cell that that contains actual data (although even then, a cell containing an empty string can cause problems)

**Comment by awtyklo** [comment]
Hi Mark,

Thank you for quick answer and a an explanation.

You are absolutely right. Example excel had formatting on all cells . I removed formatting using:
Clear all formatting button (I selected all cells beforehand)

and it worked as expected (2 rows, 2 columns).

For future reference. The elegant way of handling such case would be to use this solution:
https://phpspreadsheet.readthedocs.io/en/latest/topics/reading-and-writing-to-file/#excel-2007-spreadsheetml-file-format
(Section = Read data only)
```php
<?php
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xls();
$reader->setReadDataOnly(true);
$spreadsheet = $reader->load("05featuredemo.xls");
```

Is this correct?

The part I do not fully understand is that after using `setReadDataOnly`, the `getHighestRow()` had in fact expected value = 2, but `getHighestColumn()` still returned L (should be B).

I opened the file and deleted all values (not styles) from cells C2:L3 (including). No change. After removing styles (just from C2:L3) it showed B as expect.

Ps. Thank you for inormation about uploading files. I attached this Excel for future reference and edited the issue.

**Comment by MarkBaker** [comment]
`$reader->setReadDataOnly(true);` comes at a cost; styling information is lost, which also means that it is no longer possible to identify whether a numeric value in a cell is a genuine float/int, or whether it is a date value.

The fact it still returned L as the highest column does suggest that there is a cell in column L that does contain some value (and empty string or a null)... for whatever reason, the Reader identified that it did need to create a cell in column L based on the file content; but without examining the file itself I wouldn't be able to say for certain

**Comment by MarkBaker** [comment]
Looking at the file you've uploaded now, it has a `<dimension ref="A1:L1048576"/>` and the actual row/column information reads:
```
-<sheetData>
-<row r="1" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="13.8" customFormat="false">
-<c r="A1" t="s" s="1">
<v>0</v>
</c>
-<c r="B1" t="s" s="1">
<v>1</v>
</c>
<c r="C1" s="1"/>
<c r="D1" s="1"/>
<c r="E1" s="1"/>
<c r="F1" s="1"/>
<c r="G1" s="1"/>
<c r="H1" s="1"/>
<c r="I1" s="1"/>
<c r="J1" s="1"/>
<c r="K1" s="1"/>
</row>
-<row r="2" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="13.8" customFormat="false">
-<c r="A2" t="s" s="1">
<v>2</v>
</c>
-<c r="B2" t="s" s="1">
<v>3</v>
</c>
<c r="G2" s="1"/>
<c r="H2" s="1"/>
<c r="I2" s="1"/>
<c r="J2" s="1"/>
<c r="K2" s="1"/>
<c r="L2" s="1"/>
</row>
<row r="3" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="13.8" customFormat="false"/>
<row r="1048540" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048541" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048542" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048543" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048544" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048545" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048546" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048547" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048548" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048549" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048550" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048551" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048552" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048553" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048554" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048555" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048556" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048557" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048558" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048559" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048560" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048561" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048562" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048563" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048564" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048565" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048566" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048567" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048568" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048569" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048570" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048571" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048572" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048573" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048574" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048575" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
<row r="1048576" collapsed="false" outlineLevel="0" customHeight="false" hidden="false" ht="12.8" customFormat="false"/>
</sheetData>
```


Use of `getHighestRow()` is fast, because the value is calculated once on load of the file and then cached in the Worksheet object. This makes it quick to access the information, but it may not be completely accurate, partly because it is derived from all cell/row/column references anywhere in the spreadsheet file (which does include styles, print settings, image positioning, etc as well as actual cell data). Nor does the value get updated if you add new rows/columns to a worksheet, so it can get "out of date" if you're modifying the sheet.

`getHighestDataRow()` is slower because it reads the full cell collection every time it is called to determine its response based on actual cells containing data; but that call still include null values and empty strings. It can also be called passing in a column id, and will return the highest row containing a cell in that specified column. And if you add new rows of data, it will return the updated value when next called.

**Comment by awtyklo** [comment]
Thank you for detailed explaination - it was very helpful.
