### ISSUE TITLE
If xlsx has not style we got a crasgh

### ISSUE THREAD

**Issue by realtebo** [PHPOffice/PhpSpreadsheet#2064]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

importing a not-so-well formatted xlsx PHPExcel survive to small problems

OpenOffice opens it well
LibreOffice also.
Excel 2013 also
Excel 265 also.

### What is the current behavior?

See here:

https://github.com/PHPOffice/PhpSpreadsheet/blob/1.17.1/src/PhpSpreadsheet/Reader/Xlsx.php#L472

If $xpath is null here, PHP crashes because at L475 phpexcel tries to access `$dir/$xpath[Target]` 

But `$xpath` is not an array, it's null so ... crash !

### What are the steps to reproduce?

I cannot send you this specific .xlsx because it's coming from a 3rd party.

I choosen to point you at the exact problem in the code; I hope it is useful.
I have no idea on HOW to reproduce the file with the same formal error, if it's a formal error.

### Which versions of PhpSpreadsheet and PHP are affected?

1.17.1

**Comment by realtebo** [comment]
PLEASE NOTE !!

https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Reader/Xlsx.php#L424-L441

You have already fixed this.

Please, release a 1.17.2 asap !

**Comment by hrtrulz** [comment]
Looking at the code lines 424-441 are not the issue it is line 475 and using that file you linked to just moves the error to line 474.

**Comment by oleibman** [comment]
Problem reported fixed by originator last May. Closing.
