### ISSUE TITLE
Can't set password for document

### ISSUE THREAD

**Issue by vladyslavstartsev** [PHPOffice/PhpSpreadsheet#207]
This is:

- [x] a bug report
### What is the expected behavior?
File is locked with password.

### What is the current behavior?
File is unlocked

### What are the steps to reproduce?
Paste the code in the file and run on the web

```php
<?php

require __DIR__ . '/vendor/autoload.php';


$spreadsheet = new Spreadsheet();
$spreadsheet->setActiveSheetIndex(0)
    ->fromArray([array_keys($dbData[0])]) //setting first row of document
    ->fromArray($dbData->toArray(), null, 'A2');
$spreadsheet->getActiveSheet()->getProtection()->setSheet(true);
$spreadsheet->getSecurity()->setLockWindows(true);
$spreadsheet->getSecurity()->setLockStructure(true);
$spreadsheet->getSecurity()->setLockRevision(true);
$spreadsheet->getSecurity()->setWorkbookPassword('123');
$spreadsheet->getSecurity()->setRevisionsPassword('123');

header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="01simple.xls"');
header('Cache-Control: max-age=0');

$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save('php://output');
exit;

```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet - `dev-develop 7d4dc74`
PHP - `7.1.8`

**Comment by PowerKiKi** [comment]
Your code does work and prevent the data to be modified as expected, with the following message:

![image](https://user-images.githubusercontent.com/72603/30225464-e0a87c18-94d2-11e7-9036-39b817d9ee9b.png)

What you may have been expecting is to prevent viewing the data, but this is not supported.

**Comment by vladyslavstartsev** [comment]
@PowerKiKi oh, that's why. Yes, I'm expecting it. Any ideas how can I get this?

**Comment by PowerKiKi** [comment]
You can't, it is not supported. Unless you contribute this new feature.

**Comment by pcoughlin** [comment]
Is this part of #448 ?
