### ISSUE TITLE
reading xlsx with toArray() seems to return malformed array

### ISSUE THREAD

**Issue by ant-garz** [PHPOffice/PhpSpreadsheet#2070]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When using toArray(), I expect "Create array from worksheet."

### What is the current behavior?
When using this method, the array of data returns malformed, but only from 1 of 2 approaches, When run from the CLI, an external script that utilizes this method works as intended, and var_dumping the data in question returns an array such as 

```
array(8) {
  [0]=>
  string(11) "TEST DATA"
  [1]=>
  string(7) "TEST DATA"
  [2]=>
  string(17) "TEST DATA"
  [3]=>
  string(52) "TEST DATA"
  [4]=>
  string(11) "TEST DATA"
  [5]=>
  string(6) "TEST DATA"
  [6]=>
  string(2) "TEST DATA"
  [7]=>
  NULL
}
```
Which is good and what is expected, though when testing the functionality from the browser and having the script triggered from that route, the script will not work and fail out. When debugging from the file that triggers the exec() command to run the script with phpspreadsheet, the data will return to the browser like 

```
array(18) {
  [0]=>
  string(10) "array(8) {"
  [1]=>
  string(7) "  [0]=>"
  [2]=>
  string(26) "  string(11) "TEST DATA""
  [3]=>
  string(7) "  [1]=>"
  [4]=>
  string(21) "  string(7) "TEST DATA""
  [5]=>
  string(7) "  [2]=>"
  [6]=>
  string(32) "  string(17) "TEST DATA""
  [7]=>
  string(7) "  [3]=>"
  [8]=>
  string(67) "  string(52) "TEST DATA""
  [9]=>
  string(7) "  [4]=>"
  [10]=>
  string(26) "  string(11) "TEST DATA""
  [11]=>
  string(7) "  [5]=>"
  [12]=>
  string(20) "  string(6) "TEST DATA""
  [13]=>
  string(7) "  [6]=>"
  [14]=>
  string(16) "  string(2) "TEST DATA""
  [15]=>
  string(7) "  [7]=>"
  [16]=>
  string(6) "  NULL"
  [17]=>
  string(1) "}"
}
``` 
which is not expected and seems bugged. I have peered through documentation and tried to implement several different methods outlined there with no luck so far, so any help would be greatly appreciated.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

In separate file, the following code is used to trigger a php script that uses phpspreadsheet, this is that snippet below
```
$shCommand = 'php ' . __DIR__ . "/scripts/process-report.php -f='$newFilePath' -i='$newHighestUploadID'";
        //exec($shCommand);
        exec($shCommand, $test, $work);
        var_dump($test, $work);exit;
```

inside the script, I find the file and load the data as follows 

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// imports
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;

// add code that show the issue here...
// Read uploaded file

/**  Identify the type of $inputFileName  **/
$inputFileType = \PhpOffice\PhpSpreadsheet\IOFactory::identify($fullNewFilePath);
/**  Create a new Reader of the type that has been identified  **/
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($inputFileType);
/**  Load $inputFileName to a Spreadsheet Object  **/
$spreadsheet = $reader->load($fullNewFilePath);

/**  Convert Spreadsheet Object to an Array for ease of use  **/
$data = $spreadsheet->getActiveSheet()->toArray();

var_dump($data);
        die;

```

### Which versions of PhpSpreadsheet and PHP are affected?
Php version is 7.4 and PhpSpreadsheet  is ^1.17
[testxlsx.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6436733/testxlsx.xlsx)

Thank you !

**Comment by MarkBaker** [comment]
`toArray()` doesn't return a malformed array. The problem here lies in the fact that you are `var_dump`ing the output to return it from the `exec` call.... `exec` returns its result as an array of the lines of output, and `var_dump()` applies a formatting to its output that results in a broken rendering from exec.

Rather than var_dump the array to return it, try echoing it after serialising it.

**Comment by ant-garz** [comment]
That makes sense, I'll continue debugging with that in mind and hopefully be able to resolve from there , thank you again !

**Comment by MarkBaker** [comment]
Note that `toArray()` returns an array of arrays to reflect rows and columns, not a simple array as you have shown in your CLI output exmple

**Comment by ant-garz** [comment]
After further debugging , I confirmed the bug is not related to toArray as I thought, but I do want to thank you again for the tip for debugging, that was helpful in finding what I needed, I appreciate it ! Would it be best to close this issue then ?

**Comment by MarkBaker** [comment]
Yes! As it's not an issue with PHPSpreadheet, it should be closed.
