### ISSUE TITLE
Xlsx writer don't calculate correct boolean formulas in cells

### ISSUE THREAD

**Issue by xandros15** [PHPOffice/PhpSpreadsheet#2082]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?

Spreadsheet in application should show "False" values as result of formula

### What is the current behavior?

Spreadsheet in application shows empty cells

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

use PhpOffice\PhpSpreadsheet\Spreadsheet;

require_once __DIR__ . '/vendor/autoload.php';

$spreadsheet = new Spreadsheet();
$worksheet = $spreadsheet->getActiveSheet();
$worksheet->fromArray([
    'A',
    'B',
    'C',
    'D',
]);

$worksheet->getCell('A2')->setValue(
    '=A1<>"A"'
);

$xlsx = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
/** @var \PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet $xlsxWorksheet */
$xlsxWorksheet = $xlsx->getWriterPart('worksheet');
$data = $xlsxWorksheet->writeWorksheet($worksheet, [], []);
//what we expect
$expectXml = '<c r="A2" t="b"><f>A1&lt;&gt;&quot;A&quot;</f><v>0</v></c>';
echo strpos($data, $expectXml) !== false ? 'Correct format' : 'Incorrect format', PHP_EOL;
$xlsx->save(__DIR__ . '/test2.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?

PHP 7.4.8
phpspreadsheet: 1.17.1

**Comment by xandros15** [comment]
The problem is here: https://github.com/PHPOffice/PhpSpreadsheet/blob/a0719d8dd4e1766c67085a3b24a6573d5d83c4e1/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php#L1252-L1253

returning empty string instead of 0 in string

**Comment by oleibman** [comment]
Unable to duplicate - when I run your code, unchanged, against master or 17.1, cell A2 in the resulting file shows "FALSE". I tested using PHP7.4.14 (same result for 7.3.21 and 8.0.0).

**Comment by xandros15** [comment]
Updated code with check xml format.

Microsoft Office Excel 2007:
![image](https://user-images.githubusercontent.com/10834079/117678089-59dd4a80-b1af-11eb-8024-4deced9d702e.png)

I will post later results from newer version of Microsoft Office Excel.

**Comment by oleibman** [comment]
Let's see what my output file looks like on your system.
[issue2082.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6453018/issue2082.xlsx)

**Comment by oleibman** [comment]
That was kind of an interesting exercise. When I clicked on the link, I saw:
![image](https://user-images.githubusercontent.com/10341515/117680556-21fde500-b166-11eb-83b3-1290ae35bafb.png)
This matches your result. But, when I clicked on "enable editing":
![image](https://user-images.githubusercontent.com/10341515/117680701-43f76780-b166-11eb-8efa-7999d2f13e58.png)
That matches my result. Interesting.

**Comment by xandros15** [comment]
same:
![image](https://user-images.githubusercontent.com/10834079/117680670-ac1f6b00-b1b1-11eb-908d-38ad469bc99e.png)
maybe different language version?

**Comment by xandros15** [comment]
>This matches your result. But, when I clicked on "enable editing":
Maybe then spreadsheet recalculate all values and replacing them.

**Comment by oleibman** [comment]
I found a copy of Excel 2007. The cell in question is stored as
```
<c r="A2" t="str">
<f>A1&lt;&gt;"A"</f>
<v/>
```
It is possible that it should be stored as
```
<c r="A2" t="b">
<f>A1&lt;&gt;"A"</f>
<v/>
```
Further, it is possible that Excel 365 doesn't care about the difference, but Excel 2007 does. I'll look into it.

**Comment by oleibman** [comment]
No, I was mistaken. I don't know where 'str' came from above, but, when I repeated the exercise, it was 'b', as expected. So I have no idea what's going wrong here.

**Comment by xandros15** [comment]
Microsoft Excel 2016 MSO 16.0.13929.20222
![image](https://user-images.githubusercontent.com/10834079/117693073-ebec4f80-b1bd-11eb-8e85-982f2d743167.png)

**Comment by oleibman** [comment]
I believe the issue is the empty v tag. It appears that Excel 2007 explicitly expects ```<v>0<\v>```. I will work on a solution.

**Comment by oleibman** [comment]
Yes, explicitly casting a boolean formula result to int (before calling formatNumber) fixes this problem. I'll check if there are any possible consequences for empty string.
