### ISSUE TITLE
Could not find package phpoffice/phpspreadsheet

### ISSUE THREAD

**Issue by dmitry-kuchura** [PHPOffice/PhpSpreadsheet#209]
What i do wrong?

**composer require phpoffice/phpspreadsheet**

```php
[InvalidArgumentException]                                                                                                        
Could not find package phpoffice/phpspreadsheet at any version for your minimum-stability (stable). 
Check the package spelling or your minimum-stability

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
