### ISSUE TITLE
 Argument 1 passed to PhpOffice\PhpSpreadsheet\Writer\Xls::writeSummaryProp() must be of the type string, null given

### ISSUE THREAD

**Issue by ClCfe** [PHPOffice/PhpSpreadsheet#2090]
Hello

I am using v1.17.1, and I have the following error:

>  Argument 1 passed to PhpOffice\PhpSpreadsheet\Writer\Xls::writeSummaryProp() must be of the type string, null given, called in /opt/PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xls.php on line 829

If I look in the code,

https://github.com/PHPOffice/PhpSpreadsheet/blob/d08653433c39feb5337b1c0182fee7475fd7c643/src/PhpSpreadsheet/Writer/Xls.php#L769-L771

https://github.com/PHPOffice/PhpSpreadsheet/blob/d08653433c39feb5337b1c0182fee7475fd7c643/src/PhpSpreadsheet/Writer/Xls.php#L782-L784

I see that `$dataProp` may be null because you check it with `if ($dataProp) { `
So I think you have to use nullable type hint

```
diff --git a/src/PhpSpreadsheet/Writer/Xls.php b/src/PhpSpreadsheet/Writer/Xls.php
index c7c2e7d..5f2363a 100644
--- a/src/PhpSpreadsheet/Writer/Xls.php
+++ b/src/PhpSpreadsheet/Writer/Xls.php
@@ -759,7 +759,7 @@ class Xls extends BaseWriter
         return $data;
     }
 
-    private function writeSummaryPropOle(int $dataProp, int &$dataSection_NumProps, array &$dataSection, int $sumdata, int $typdata): void
+    private function writeSummaryPropOle(?int $dataProp, int &$dataSection_NumProps, array &$dataSection, int $sumdata, int $typdata): void
     {
         if ($dataProp) {
             $dataSection[] = [
@@ -772,7 +772,7 @@ class Xls extends BaseWriter
         }
     }
 
-    private function writeSummaryProp(string $dataProp, int &$dataSection_NumProps, array &$dataSection, int $sumdata, int $typdata): void
+    private function writeSummaryProp(?string $dataProp, int &$dataSection_NumProps, array &$dataSection, int $sumdata, int $typdata): void
     {
         if ($dataProp) {
             $dataSection[] = [
```

**Comment by oleibman** [comment]
Perhaps the code is not as tight it should be, but ... how did you arrive at this error? I can duplicate it by, for example, setting creator to null (because the set routines in Document/Properties use only doc-block typehints, not typehints in the function signature). Is that what you are doing, and, if so, why?

**Comment by oleibman** [comment]
PR #1932 moved typehints in Document/Properties from doc-block to function signature. If you run your test against master, do you see the same problem you are reporting?

**Comment by ClCfe** [comment]
I use the Reader on an existing file, and then, I append a new sheet using Xls Writer
I have no control on the files that I modify (user upload)

in this case, 
https://github.com/PHPOffice/PhpSpreadsheet/blob/c55269cb06911575a126dc225a05c0e4626e5fb4/src/PhpSpreadsheet/Writer/Xls.php#L829
did in fact return a null Title

**Comment by oleibman** [comment]
Is it possible for you to share the file that is giving you this problem?

**Comment by oleibman** [comment]
10 months, no update, closing.
