### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by momala454** [PHPOffice/PhpSpreadsheet#2092]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
No memory leak

### What is the current behavior?
Memory leak

### What are the steps to reproduce?

The memory doesn't stop growing. My files are xls and xlsx, varies from 30kB to 21MB

```php
<?php

require __DIR__ . '/vendor/autoload.php';

foreach (glob($this->filesFolder.'*') as $fileName) {
           echo number_format(memory_get_usage())."\n";
            $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($fileName);
           $spreadsheet->disconnectWorksheets();
           $spreadsheet->garbageCollect();
           unset($spreadsheet);
        }

### Which versions of PhpSpreadsheet and PHP are affected?
1.17.1

**Comment by MarkBaker** [comment]
A real memory leak would be a bug; but PHPSpreadsheet doesn't suffer from that. Rather, an "in memory" spreadsheet uses a lot of memory, and just because a file that you load is small, doesn't mean that its "in memory" representation is small..... it all depends on the number of worksheets/rows/columns

We provide a series of approaches for working with larger spreadsheets, from loading only specific worksheets, to loading only part of a worksheet; to loading only the raw data in the cells without formatting information; and also provide options to allow caching of cell data, reducing the memory requirements. These are all documented

**Comment by momala454** [comment]
the memory requirement is not a problem. What is a problem is that each opened excel file increase the memory usage without never releasing the memory

**Comment by MAKS-dev** [comment]
Looks to me your PHP garbage collection is not directly taking place. (Some details: https://stackoverflow.com/a/584982/4712173)
You can try to call `gc_collect_cycles();` after the unset (https://www.php.net/manual/en/function.gc-collect-cycles.php)
Or maybe an `usleep` to give the CPU some free cycles (depending also on other processes obviously).

Maybe it's something else, but worth a look.

**Comment by momala454** [comment]
i tried with that after unset, but it still use more and more memory, until reaching around 400mB. It must be the size necessary to load my biggest file. it reached 400mb when my xls file is 20mb

```php
gc_collect_cycles();
		sleep(1);```

**Comment by PowerKiKi** [comment]
Three things:

- PhpSpreadsheet uses internal cache (that can never be cleared) for some things, so it is expected that memory increase (a bit) and never decrease totally
- `Spreadsheet::garbageCollect()` is not useful here, it is not really meant to free memory. And more generally I'm not sure a user should ever call it manually
- However I did reproduce a few leaks, the most significant one when the spreadsheet contains images. They have been fixed via #2092

I used the following script to load pretty much all files existing in, or generated by the project. It read the file two times. First to warm up the cache, and second for real measurement. Before running the script, normal unit tests should be run once to generate all files in `/tmp/phpspreadsheet/`:

```php
<?php

use PhpOffice\PhpSpreadsheet\IOFactory;

require 'vendor/autoload.php';

function memory(): int
{
    gc_collect_cycles();

    return memory_get_usage();
}

function load(string $fileName): void
{
    $spreadsheet = IOFactory::load($fileName);
    $spreadsheet->disconnectWorksheets();
}

function monitorMemory(callable $callable): int
{
    $before = memory();
    $callable();
    $after = memory();

    $diff = $after - $before;

    echo number_format($before) . PHP_EOL;
    echo number_format($after) . PHP_EOL;
    echo '+ ' . number_format($diff) . PHP_EOL;
    echo PHP_EOL;

    return $diff;
}

$files = [
    ...glob('/tmp/phpspreadsheet/*.xls'),
    ...glob('/tmp/phpspreadsheet/*.xlsx'),
    ...glob('/tmp/phpspreadsheet/*.csv'),
    ...glob('tests/data/Reader/CSV/*'),
    ...glob('tests/data/Reader/Gnumeric/*'),
    ...glob('tests/data/Reader/Ods/*'),
    ...glob('tests/data/Reader/XLS/*'),
    ...glob('tests/data/Reader/XLSX/*'),
];

$except = [
    'tests/data/Reader/CSV/empty.csv',
    'tests/data/Reader/Ods/corruptMeta.ods',
    'tests/data/Reader/XLSX/double_attr_drawing.xlsx',
];

$files = array_diff($files, $except);

foreach ($files as $fileName) {
    $do = function () use ($fileName): void {
        load($fileName);
    };

    echo $fileName . PHP_EOL;

    // Warmup caches
    $do();

    // Do it for real while monitoring memory
    $diff = monitorMemory($do);

    if ($diff > 0) {
        throw new Exception('Memory leak found !');
    }
}

echo count($files) . ' files loaded' . PHP_EOL;
echo 'with a peak memory usage of : ' . number_format(memory_get_peak_usage()) . PHP_EOL;
echo 'with a final memory usage of: ' . number_format(memory()) . PHP_EOL;
```

This would end up with:

```
247 files loaded
with a peak memory usage of : 31,957,288
with a final memory usage of: 11,191,304
```

**Comment by momala454** [comment]
how to clear the internal caches ? I don't think any script is supposed to keep things in memory once everything have been unset

**Comment by PowerKiKi** [comment]
> PhpSpreadsheet uses internal cache (that can never be cleared)

**Comment by maximnl** [comment]
we use chunkreadfilter , this loads only the range of rows and lets u limit the arrays
however you need to take care of removing all leading NULL rows after the first chunk. 
i use a php array function , works ok. 

still , i am able to load about 1K rows per sec, so large files just time out after 40K+ rows. (few minutes)

**Comment by IronSean** [comment]
> PhpSpreadsheet uses internal cache (that can never be cleared)

This is a pretty frustrating behaviour if you're using PhpSpreadsheet in a webserver thread that gets reused to process excel file uploads. Users are unlikely to upload the same excel file as each other so the cache is useless, but the memory can't be cleared.

**Comment by smenzer** [comment]
I'm having similar problems...I'm using a chunkreadfilter to process a large (250k rows) spreadsheet in chunks. However, memory continues to grow even as I unset variables when I am done with them.  here's a code snippet:

```php
// self::$_CHUNK_SIZE = 25000;
for ($row = 2; $row <= $nb_rows; $row += self::$_CHUNK_SIZE) {
      $chunk_filter->setRows($row, self::$_CHUNK_SIZE);
      $reader->setReadFilter($chunk_filter);
      $sheet = $reader->load($filepath);

      $raw_data = $sheet->getActiveSheet()->toArray();
      unset($sheet);

      $upload_string = $this->prepareDataForBulkUpload($raw_data);
      unset($raw_data);

      // do something with $upload_string

      unset($upload_string);
}
```

I would expect that the `$sheet`, `$raw_data`, `$upload_string` variables to be quite large, but after `unset`ing them, the memory should be freed up. I have put several `memory_get_usage()` calls throughout the code, and I can see that `unset($raw_data)` and `unset($upload_string)` clears up 10's of MBs, but the `unset($sheet)` clears nothing. Because of this, the script's memory grows by 150MB on each loop, which is not sustainable.

@PowerKiKi - What can be done to free up the memory usage?

**Comment by MarkBaker** [comment]
Suggestion #1
From the [documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/creating-spreadsheet/#clearing-a-workbook-from-memory) you can't simply `unset` the file that you've loaded, because PHP can't clear cyclic references in the object tree. You need to explicitly break those references by calling the Spreadsheet's `disconnectWorksheets()` method first

Suggestion #2
Avoid using `toArray()` if you possibly can. PHP arrays are an incredible memory hog

**Comment by rasmuscnielsen** [comment]
I came across this problem in a Laravel Octane project today, where uploading a 1mb xlsx file would climb from 60mb --> 256mb in 3-4 attempts and then exceed memory limit. 

After a bunch of different failed attempts at garbage collection, I found that using Laravel's `Concurrency::run(...)` feature did the trick. This will do the import in a separate short-lived PHP process rather than bloating the Octane worker.

Example:

```php
[$result] = Concurrency::run(function () use ($file) {
    $type = IOFactory::identify($file);
    $reader = IOFactory::createReader($type);

    $sheet = $reader->load($file)->getActiveSheet();

    // do work and set some $result ...

    return $result;
});
```

**Comment by DavidPetrasek** [comment]
This issue should be reopened:
My XLSX file has over  27000 rows. I unset all variables everywhere. I use Symfony 7.2.
After few thousand rows I run out of memory.

This is my code:

```
class ChunkReadFilter implements IReadFilter
{
    private int $startRow = 0;
    private int $endRow = 0;
    
    public function __construct
    (
        private array $columns
    ){}

    /**
     * Set the list of rows that we want to read.
     */
    public function setRows(int $startRow, int $chunkSize): void
    {
        $this->startRow = $startRow;
        $this->endRow = $startRow + $chunkSize;
    }

    public function readCell(string $columnAddress, int $row, string $worksheetName = ''): bool
    {
        //  Only read rows and columns that were configured
        if ($row >= $this->startRow && $row < $this->endRow) 
        {
            if (in_array($columnAddress, $this->columns)) 
            {
                return true;
            }
        }

        return false;
    }
}
```


```
#[Route('/import')]
class ImportController extends AbstractController
{
    const PHPSPREADSHEET_CHUNK_SIZE = 500;
    const DOCTRINE_BATCH_SIZE = 20;
    private int $doctrineCurrInsertIt = 0;

    function __construct
    (
        private readonly EntityManagerInterface $entityManager,
        private readonly string $projectDir,
    )
    {}
    

    #[Route('/clients')]
    public function clients(): Response
    {
        ini_set('max_execution_time', 60*30);
        ini_set('memory_limit', '512M');
        
        $this->entityManager->getConnection()->getConfiguration()->setSQLLogger(null);
        $chunkFilter = new ChunkReadFilter(['B', 'AA', 'S', 'L', 'M', 'N', 'F', 'E', 'P', 'Q', 'O', 'J', 'V', 'U', 'W', 'X', 'A']);

        $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
        $reader->setReadDataOnly(true);
        $reader->setReadFilter($chunkFilter);

        $info = $reader->listWorksheetInfo($this->projectDir.'/var/data/import/file.xlsx');
        $totalRows = $info[0]['totalRows'];
        unset($info);

        for ($startRow = 2; $startRow < $totalRows; $startRow += self::PHPSPREADSHEET_CHUNK_SIZE)
        {
            $chunkFilter->setRows($startRow, self::PHPSPREADSHEET_CHUNK_SIZE);
            $spreadsheet = $reader->load($this->projectDir.'/var/data/import/file.xlsx');

            $endRow = $startRow + self::PHPSPREADSHEET_CHUNK_SIZE - 1;
            $chunkArray = $spreadsheet->getActiveSheet()->rangeToArray("A{$startRow}:AJ{$endRow}", null, false, false, true);
            $spreadsheet->disconnectWorksheets();
            unset($spreadsheet, $endRow);

            $this->proccessChunk($chunkArray);
            unset($chunkArray);
            gc_collect_cycles();
        }

        unset($reader, $chunkFilter);
      
        return new Response('finished');
    }

    private function proccessChunk(array $chunkArray): void
    {
        foreach ($chunkArray as $row) 
        {
            $this->registerClient($row, $this->entityManager); // This method processes row and persists doctrine entities
            unset($row);
            
            if (($this->doctrineCurrInsertIt % self::DOCTRINE_BATCH_SIZE) === 0) 
            {
                $this->entityManager->flush();
                $this->entityManager->clear(); // Detaches all objects from Doctrine!
            }
            $this->doctrineCurrInsertIt++;           
        }
        unset($chunkArray);

        $this->entityManager->flush(); // Persist objects that did not make up an entire batch
        $this->entityManager->clear();
    }
```

**Comment by oleibman** [comment]
Rather than using arrays, you are probably much better off using iterators if possible. Even if not possible, you needn't load a huge array all at once.
```php
    private function proccessChunk(Worksheet $sheet, int $startRow, int $endRow, string $startColumn, string $endColumn): void
    {
        for ($rowIndex = $startRow; $rowIndex <= $endRow; ++$rowIndex) 
        {
            $row = $sheet->getActiveSheet()->rangeToArray(
                "{$startColumn}{$rowIndex}:{$endColumn}{$rowIndex}",
                null,
                false,
                false,
                true
            )[0];
            $this->registerClient($row, $this->entityManager); // This method processes row and persists doctrine entities
            unset($row);
            
            if (($this->doctrineCurrInsertIt % self::DOCTRINE_BATCH_SIZE) === 0) 
            {
                $this->entityManager->flush();
                $this->entityManager->clear(); // Detaches all objects from Doctrine!
            }
            $this->doctrineCurrInsertIt++;           
        }

        $this->entityManager->flush(); // Persist objects that did not make up an entire batch
        $this->entityManager->clear();
    }

**Comment by DavidPetrasek** [comment]
@oleibman I found the bottleneck. It was doctrine. I had to disable all logging like this:

``` yaml
dbal:
            logging: false
            profiling: false
```

Now I don't even need to set the memory_limit to 512M anymore.  It took 10 Minutes and 28 Seconds with peak memory usage 99.1 MB

But I switched to https://github.com/openspout/openspout anyway, because it took only 6 Minutes 37 Seconds with peak memory usage 64.5 MB.

**Comment by DavidPetrasek** [comment]
@oleibman I also found there is no need to unset anything in my provided code.

Performance results with all unset calls removed:

- PhpSpreadsheet - 10 Minutes 40 Seconds with peak memory usage 103.1 MB

- Openspout -  6 Minutes 33 Seconds with peak memory usage 34.00 MB
