### ISSUE TITLE
Not allow create new sheet in csv files

### ISSUE THREAD

**Issue by HAL0594** [PHPOffice/PhpSpreadsheet#2094]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
create a new sheet in csv file

### What is the current behavior?

not allow change the sheet name always take the name of the file  and not add the new sheet 

### What are the steps to reproduce?

A few days ago I started using the package that I normally use with xls but I found myself having to create a csv with two sheets, when I try to add a new one with createSheet it only show one sheet and not allow renaming with setTitle.

```
        $spreadsheet = new Spreadsheet();
        $data = [];
        array_push($data, '#', 'cost');

        
        $spreadsheet->setActiveSheetIndex(0);
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Coverages');

        $sheet->fromArray($data, null, 'A1');

        $spreadsheet->createSheet();
        $spreadsheet->setActiveSheetIndex(1);
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Locations');
        $sheet->fromArray($data, null, 'A1');

        $writer = new Csv($spreadsheet);

        header('Content-Type: application/csv; charset=UTF-8');
        header('Content-Disposition: attachment; filename="report.csv"');
```
result
![image](https://user-images.githubusercontent.com/43229066/118156587-c2f2d700-b3d6-11eb-8349-7002a5bd704a.png)

### Which versions of PhpSpreadsheet and PHP are affected?
the last version of PhpSpreadsheet and php version is 7.3

**Comment by MarkBaker** [comment]
I'm not exactly sure what your problem is here? What exactly are you trying to do?
