### ISSUE TITLE
Fatal Allowed memory size of 2147483648 bytes exhausted ... PhpSpreadsheet/Cell/Coordinate.php .. line 395

### ISSUE THREAD

**Issue by nvcken** [PHPOffice/PhpSpreadsheet#2107]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Should not get fatal error

### What is the current behavior?
the file is 1.6M and has 1048576 rows data that created by Macro script, tried with empty rows data also 

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

$inputFileName =  '/test.xlsx';
$reader = IOFactory::createReader('Xlsx');
$reader->setLoadSheetsOnly($sheetNames);
$spreadsheet = $reader->load($inputFileName);
```

### Which versions of PhpSpreadsheet and PHP are affected?
Both 1.16.0 and 1.17.1

### Log trace

[17-May-2021 17:51:42 Asia/Singapore] [2021-05-17T17:51:41.997522+08:00] common.ALERT: Fatal Error (E_ERROR): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 528384 bytes) {"code":1,"message":"Allowed memory size of 2147483648 bytes exhausted (tried to allocate 528384 bytes)","file":"/var/www/repo/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php","line":395,"trace":null} []

Call Stack:
    ....
  505.7027   52479032  21. PhpOffice\PhpSpreadsheet\Reader\Xlsx\DataValidations->load() /var/www/repo/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:800
  601.6662   52561800  22. PhpOffice\PhpSpreadsheet\Reader\Xlsx\DataValidations->load() xdebug://debug-eval:1
  601.6662   52561800  23. PhpOffice\PhpSpreadsheet\Cell\Coordinate::extractAllCellReferencesInRange(???) xdebug://debug-eval(1) : eval()'d code:1
  870.5984 2139037424  24. sprintf(???, ???, ???) /var/www/repo/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php:344
  870.6617 2139037160  25. PhpOffice\PhpSpreadsheet\Cell\Coordinate::extractAllCellReferencesInRange(???) /var/www/repo/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx/DataValidations.php:30
  870.6680 2139037536  26. PhpOffice\PhpSpreadsheet\Cell\Coordinate::getReferencesForCellBlock(???) /var/www/repo/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php:334

**Comment by MarkBaker** [comment]
It's difficult to create a PHP script that loads data into memory while keeping the amount of memory used to a minimum.
Have you read the documentation on [memory saving](https://phpspreadsheet.readthedocs.io/en/latest/topics/memory_saving/)?

**Comment by nvcken** [comment]
yes @MarkBaker, I see that feature, but haven't tried yet, as actually I have know my issue is come from `extractAllCellReferencesInRange` but the range it tried to read is totally empty cell data as kind like the rest of empty cells, then I just try to find out the way to by pass this would be better  as I think my data is not that huge to need a cache yet

**Comment by nvcken** [comment]
ok I tried cache already, but issue still occurs as this is due to 
```
foreach ($cellList as $coord) {
   [$column, $row] = sscanf($coord, '%[A-Z]%d');
```
when $cellList count is huge, e.x 6272958

**Comment by MarkBaker** [comment]
Then I suggest you look to another project to work with your spreadsheets, one that works in a linear fashion... without a total rewrite, we cannot create a script that will maintain a spreadsheet of over 6 million cells in memory without using memory, We don't hold genuinely empty cells in memory, but a cell may contain a null value or an empty string, and in that case it is not an empty cell.

**Comment by nvcken** [comment]
Hi @MarkBaker does have anyway to this fatal exception? Could you help pls

**Comment by MarkBaker** [comment]
I don't know what I can do! PHPSpreadsheet: works the way it does, so without a complete rewrite, I don't know how I can change it.

From your original log, the Xlsx file loader is failing when it tries to load DataValidations; it shouldn't even be calling that method if you had readDataOnly set to true

**Comment by MarkBaker** [comment]
It might be possible to modify that method to make it a `generator`; but I would have to check everywhere that it's called in the code to be sure that could work with an `iterable` return, there's certainly some places (such as the calculation engine) that would require reworking to handle an `iterable` return.

**Comment by MarkBaker** [comment]
On closer inspection it doesn't look practical; that method needs to handle intersections and unions between multiple lists of cells

**Comment by jaytee117** [comment]
iv had a similair issue with a 5MB .xlsx file,  ended up converting it to a csv before processing
