### ISSUE TITLE
No sheets detected

### ISSUE THREAD

**Issue by kowach** [PHPOffice/PhpSpreadsheet#2109]
The `IOFactory::load()` loads file with no errors, but it can't detect any sheets.

PhpSpreadsheet v1.17.1
PHP 7.4.16
File type: XLSX
File size: 1.6MB
Rows in sheet1: 5214

Here is the problematic document (it opens fine in Libre office and if converted to .ods PhpSpreadsheet will load all data)

[Sample_large_excel_file.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6499675/Sample_large_excel_file.xlsx)

**Comment by MarkBaker** [comment]
This is a namespacing issue; and there is already a PR in progress to address it; but it's a significant code change and needs extensive testing, so won't be in the next release but hopefully the release after,

**Comment by MarkBaker** [comment]
If you want to test/experiment this is [PR #2088](https://github.com/PHPOffice/PhpSpreadsheet/pull/2088)... note that it's only Phase 1 of the steps to handle namespacing more cleanly, and support namespacing other than that used as standard in MS-Excel generated files

**Comment by blackwolf12333** [comment]
@MarkBaker I noticed an issue similar to this with an excel file from a customer, I've been able to confirm that the merged PR on master fixed the issue.

**Comment by oleibman** [comment]
Thank you for confirming.

**Comment by oleibman** [comment]
Fixed in [1.19.0](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.19.0)
