### ISSUE TITLE
Financial::COUPNCD and Google Tables different results

### ISSUE THREAD

**Issue by ElShapovalov** [PHPOffice/PhpSpreadsheet#2116]
cpnNextAt = 30.09.2021
maturityAt = 31.03.2022
cpnFreq = 2
dayCntDes = 0

Financial::COUPNCD = **30.09.2021**
Google Tables = **31.03.2022**

**Comment by oleibman** [comment]
Problem is caused because code subtracts 6 months from a PHP DateTime, say, 2022-03-31, which results in 2021-10-01 rather than 2021-09-30. Fixing that is a little messy, but doable, but then there are all sorts of regression possibilities. I am looking into it.
