### ISSUE TITLE
A non well formed numeric value encountered in src/PhpSpreadsheet/Worksheet/ColumnDimension.php on line 77

### ISSUE THREAD

**Issue by rsimonru** [PHPOffice/PhpSpreadsheet#2145]
This is:

```
- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
No error

### What is the current behavior?
An error for every <td> with "width" property in percent <td width="xx%">

### What are the steps to reproduce?
Generate Excel from HTML table with "width property" in <td> tags in percent.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// $vcTable is an string with a simple table in HTML with any <td width="xx%">
$vcTable='
<table>
<tr>
<td width="15%">A</td>
<td>B</td>
<td>C</td>
</tr>
</table>
';
$tmpfile = tempnam(sys_get_temp_dir(), 'html');
file_put_contents($tmpfile, $vcTable);

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$reader = new PhpOffice\PhpSpreadsheet\Reader\Html();


// add code that show the issue here...
$reader->loadIntoExisting($tmpfile, $spreadsheet);
```

### Which versions of PhpSpreadsheet and PHP are affected?
Checked in last version (1.18.0)

**Comment by oleibman** [comment]
Better support for units for column width and row height when reading html is probably doable. However, it is particularly difficult to figure out what should be done when the measurement is specified as a percentage. Would it be acceptable to you if PhpSpreadsheet merely ignored the width indication if it is specified as a percentage? That would satisfy your "no error" expected behavior. If not, what do you think it should be doing when it sees a percentage rather than a fixed unit?

**Comment by MarkBaker** [comment]
I have a half-written update to the column width management for the Html Reader, but it's pretty arbitrary with all the css "relative" UoMs - `em`, `ex`, `ch` and `rem` are all character-based, so it simply bases the width on the arbitrary default column width of 8.54 for 10 Calibri 11pt characters; `%` is the percentage of 8.54; and `vw`, `vh`, `vmin` and `vmax` all simply set the width to 8.54. "Absolute" units like `pt`, `px`, `pc`, `cm`, `mm` and `in` are more straightforward; based on 96dpi, and then adjusted to Microsoft's awkward values based on Calibri 11pt;

**Comment by rsimonru** [comment]
Lot of thanks for the response.

At this moment, for us, is enought if the library ignore the width configuration when is set in "%". When it write lots of messages, Excel sheet is not generated, and that is the real problem.

**Comment by MarkBaker** [comment]
[PR #2152](https://github.com/PHPOffice/PhpSpreadsheet/commit/05466e99ce2ec19750ba9373116bfbc07e69ae55) merged to master
