### ISSUE TITLE
Changing grey background to black in Excel template

### ISSUE THREAD

**Issue by keithslater** [PHPOffice/PhpSpreadsheet#2147]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Not change the cell background color

### What is the current behavior?
Grey background cells are changing to black

### What are the steps to reproduce?
Create spreadsheet with grey background cells
Use IOFactory::load to load the spreadsheet
Use the Xls writer to write a new spreadsheet

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = IOFactory::load('input.xls');

$writer = new Xls($spreadsheet);
	header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
	header('Content-Disposition: attachment; filename="output.xls"');
	$writer->save('php://output');
```

### Which versions of PhpSpreadsheet and PHP are affected?
Works fine in 1.16.0. I noticed it broke in 1.18.0. Didn't test 1.17.0.
I did look closer and 1.16.0 has a different shade of grey than what is originally there, but it's not doing what the latest version is doing which turns it to black.

**Comment by zagadum** [comment]
yes critical.
IOFactory load ->give black color

etalon xls file
![изображение](https://user-images.githubusercontent.com/965855/121344569-975b0200-c92c-11eb-96c5-943a95525d2b.png)

IOFactory::load('input.xls');
recive 

![изображение](https://user-images.githubusercontent.com/965855/121344878-e6089c00-c92c-11eb-9a1e-8fc76624f7c7.png)

**Comment by michaljusiega** [comment]
There is problem with XLS. Converted to XLSX will resolve the issue I think.

**Comment by zagadum** [comment]
**Converted to XLSX**  

original file
1. exel 95
2. exel 2016
[view.xls](https://github.com/PHPOffice/PhpSpreadsheet/files/6623540/view.xls)
[view.8b7ecd1391dead619fab9e3dd6bfab2a.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6623541/view.8b7ecd1391dead619fab9e3dd6bfab2a.xlsx)

reult from xlsx

![изображение](https://user-images.githubusercontent.com/965855/121350513-7518b280-c933-11eb-8762-fa102aa78416.png)

**Comment by MarkBaker** [comment]
Can you narrow this down for me: is this a Reader or a Writer issue? Load the spreadsheet, and var_dump the background colour of one of those cells, if it's black at that point, then the problem is in the Reader, if it's still grey and only turns the cell to black when you save, then the problem is in the Writer.... that simple test halves my investigation. 
If it works ok if you save as Xlsx, but is wrong when you save as Xls, then that suggests an error in the colour mapping tables for the Xls writer... but can you confirm with that simple diagnostic.
