### ISSUE TITLE
Templates with Check Boxes

### ISSUE THREAD

**Issue by 604media** [PHPOffice/PhpSpreadsheet#215]
I have created a template in Excel 2007 that contains check boxes. After I write data to the cells and open the file, the check boxes do not appear . The data appears in the cells I expect them to, just no check boxes. Am I missing something?

https://github.com/PHPOffice/PHPExcel/issues/181

Is this feature available in PhpSpreadsheet?

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
