### ISSUE TITLE
"Illegal offset type" when processing authorId in Xlsx.php - php8 compatibility issue?

### ISSUE THREAD

**Issue by fagzal** [PHPOffice/PhpSpreadsheet#2154]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Compatibility with PHP8 / reading xlsx file without errors.

### What is the current behavior?

After upgrading to PHP8.0.6, we started to get errors when reading xlsx files.
Error happens in master,phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php, line 883:

```php
$commentModel->setAuthor($authors[$comment['authorId']]);
```
Error reported is "Illegal offset type".

I have printed the value of $comment['authorId'], and it is:

```php
SimpleXMLElement Object
(
    [0] => 1
)
```

I could do a workaround by using:
```php
$commentModel->setAuthor($authors[(string)$comment['authorId']]);
```

I am not 100% sure this is PHP8 related, but it worked when we use PHP7.4.

### What are the steps to reproduce?

Will provide if you cannot reproduce.

### Which versions of PhpSpreadsheet and PHP are affected?

master

**Comment by MarkBaker** [comment]
Hmmm. which version of MS Excel was the file created with? Excel now has `Notes` (which used to be called `Comments`), and `Comments`, that are now threaded.

**Comment by micc83** [comment]
Same problem here with PHP 7.4.8. 
Exception:
```
  #message: "Illegal offset type"
  #code: 0
  #file: "./vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php"
  #line: 884
  #severity: E_WARNING
```
https://github.com/PHPOffice/PhpSpreadsheet/blob/418cd304e8e6b417ea79c3b29126a25dc4b1170c/src/PhpSpreadsheet/Reader/Xlsx.php#L879-L887
where:
```
$comment['authorId'] = SimpleXMLElement {#48722
  +"0": "1"
}
```
and
```
$authors = array:2 [
  0 => " "
  1 => "Owner"
]
``` 
I see however thats this is probably already fixed on master:
https://github.com/PHPOffice/PhpSpreadsheet/blob/eb0cda1d63149a97c8b150349f5d4a23d6c3d013/src/PhpSpreadsheet/Reader/Xlsx.php#L921-L930
Some clue on when it will be released? Thank you for the great job.

**Comment by BigOHenry** [comment]
Same problem here with PHP 7.4.8.

**Comment by tlokot** [comment]
Can I ask what the status on this is? Is this a simple fix that is pending release, or is this a rework of Comments & Notes handling? This is blocking a production issue for me where I simply want to read the contents of the spreadsheet and ignore the comments/notes entirely, but I can't even open the file in PHPSpreadsheet without it erroring.

**Comment by micc83** [comment]
@tlokot If you are in a urge I confirm that the issue has already been fixed in dev-master.

**Comment by tlokot** [comment]
Thank you for confirming that. I’ll test it out.

**Comment by BARNZ** [comment]
Just ran into this problem as well on php7.4. Fixed by doing a composer update to get the latest version - thanks for the heads up.

I guess this issue can be marked as resolved now.

**Comment by oleibman** [comment]
Several confirmations that this is now working correctly.
