### ISSUE TITLE
Return Value Error - DatabaseAbstruct::buildQuery() return null but must be string

### ISSUE THREAD

**Issue by CasheeeewNuts** [PHPOffice/PhpSpreadsheet#2158]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
DatabaseAbstruct::buildQuery() return string

### What is the current behavior?
DatabaseAbstruct::buildQuery() return null but it must be string, throwed Return Value Error

### What are the steps to reproduce?
An error occurs when I try to export a spreadsheet with the following formula,
```
=AVERAGEIF(A:A, "", B:B)
```
when a blank cell is specified in the search condition.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();

// Create new Spreadsheet object
$spreadSheet = $reader->load('example.xlsx');

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadSheet);
$writer->save('php://output'); // anywhere

// add code that show the issue here...
```

**Comment by PowerKiKi** [comment]
Fixed in [1.19.0](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.19.0)
