### ISSUE TITLE
documentation is out of sync

### ISSUE THREAD

**Issue by marcelloh** [PHPOffice/PhpSpreadsheet#216]
Go to
https://phpspreadsheet.readthedocs.io/en/develop/topics/reading-files/

read the paragraph:
Loading a Spreadsheet File

notice:
See Examples/Reader/exampleReader01.php for a working example of this code.

Where is this example?

**Comment by PowerKiKi** [comment]
Duplicate of #17

**Comment by marcelloh** [comment]
I would say, it is not a duplicate, because the other issue is about fixing the structure and mine is about fixing the documentation.
