### ISSUE TITLE
PPMT() function should not asserts that rate is a positive number

### ISSUE THREAD

**Issue by majermi4** [PHPOffice/PhpSpreadsheet#2163]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
In an native excel, the `=PPMT (rate, per, nper, pv, [fv], [type])` function allows `rate` parameter to be a negative value. 

![Screenshot 2021-06-15 at 18 34 17](https://user-images.githubusercontent.com/2118173/122090683-52d9d580-ce08-11eb-8637-40b81a904da5.png)

### What is the current behavior?
The changes added [in this commit/line](https://github.com/PHPOffice/PhpSpreadsheet/commit/a34695e0f9e7125e701b255f17f1436c2554eabe#diff-32ee98846269c57581fd0afba3bf0b9ed6c9e5fa4b69da56b41ee45ce4e29930R39) now trigger error when calculating value of the `PPMT` function when negative `rate` value is given to it.

I have to admit that I'm not an expert on what the `PPMT` function does and how it is meant to be used but we have a lot of excel files from experts in the financial industry and they seem to use a negative rate value in this function which now causes our app to crash. 

My proposed solution is to simply remove that one line of validation which will make PHPOffice/PhpSpreadsheet behave consistently with native excel.

### Which versions of PhpSpreadsheet and PHP are affected?

Effected PhpSpreadsheet version: 1.18.0 and higher

**Comment by MarkBaker** [comment]
There was a time when MS provided decent, consistent documentation on all of the Excel functions, not simply providing an example or two, but detailing all the validations, and the errors that would be returned. Sadly, that is no longer the case.

**Comment by PowerKiKi** [comment]
Fixed in [1.19.0](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.19.0)
