### ISSUE TITLE
setWrapText

### ISSUE THREAD

**Issue by rencarnation** [PHPOffice/PhpSpreadsheet#2175]
This is:

```
- [ ] a bug report
- [ ] a feature request

```
setWrapText is not working on merge cell

$sheet->setCellValue('A1', 'This is just a sample This is just a sample This is just a sample This is just a sample This is just a sample This is just a sample This is just a sample This is just a sample This is just a sample This is just a sample 123456');

$spreadsheet->getActiveSheet()->mergeCells('A1:C1'');
$spreadsheet->getActiveSheet()->getStyle('A1:C1')->getAlignment()->setWrapText(true);

**Comment by MarkBaker** [comment]
I've just tested this, and it works for Xls, Xls, Ods and Html Writers... what wrapText doesn't do is change the row height, you have to do that yourself
