### ISSUE TITLE
Do PhpSpreadsheet support form fields? If not, could you please add this feature.

### ISSUE THREAD

**Issue by justice93kg** [PHPOffice/PhpSpreadsheet#219]
Do PhpSpreadsheet support form fields? If not, could you please add this feature.

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
