### ISSUE TITLE
0.07 will change to 0.070000000001 when read xls file   

### ISSUE THREAD

**Issue by cxieqing** [PHPOffice/PhpSpreadsheet#220]
This is:

- [ ] a bug report
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
I expect 0.07 not 0.070000000001

### What is the current behavior?
0.07 will change to 0.070000000001 when read xls file   

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
	private static function _extractNumber($data)
	{
		$rknumhigh = self::_GetInt4d($data, 4);
		$rknumlow = self::_GetInt4d($data, 0);
		$sign = ($rknumhigh & 0x80000000) >> 31;
		$exp = (($rknumhigh & 0x7ff00000) >> 20) - 1023;
		$mantissa = (0x100000 | ($rknumhigh & 0x000fffff));
		$mantissalow1 = ($rknumlow & 0x80000000) >> 31;
		$mantissalow2 = ($rknumlow & 0x7fffffff);
		$value = $mantissa / pow( 2 , (20 - $exp));

		if ($mantissalow1 != 0) {
			$value += 1 / pow (2 , (21 - $exp));
		}

		$value += $mantissalow2 / pow (2 , (52 - $exp));
		if ($sign) {
			$value *= -1;
		}
		return $value;
	}


### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.1.7
Linux test 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux (windows is no problem.)

**Comment by PowerKiKi** [comment]
I believe this not a bug in PhpSpreadsheet, but rather a limitation of the language itself as explained there: http://php.net/manual/en/language.types.float.php

Unless you can prove that PhpSpreadsheet is doing something incorrectly, there is nothing we can do. Float cannot be guaranteed to be exact, by definition.
