### ISSUE TITLE
After reading the excel, how will the occupied memory be recovered?

### ISSUE THREAD

**Issue by zouhuigang** [PHPOffice/PhpSpreadsheet#221]
free -h
              total        used        free      shared  buff/cache   available
Mem:           3.5G        3.2G        117M         28M        127M         35M
Swap:          2.0G        2.0G          0B

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
