### ISSUE TITLE
Can't write in an existing xls file: Cell coordinate can not be zero-length string

### ISSUE THREAD

**Issue by ClCfe** [PHPOffice/PhpSpreadsheet#2229]
Hello,

This is:

```
a bug report
```

### What is the expected behavior?

I am using PhpSpreadsheet 1.18.0

I need to read a xlsx file and add some information and then write it

### What is the current behavior?

PhpOffice\PhpSpreadsheet\Exception 
In file: PhpSpreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php 
line: 39 
message: Cell coordinate can not be zero-length string

Trace:
#0 PhpSpreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php(124): PhpOffice\PhpSpreadsheet\Cell\Coordinate::coordinateFromString('')
#1 PhpSpreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php(101): PhpOffice\PhpSpreadsheet\Cell\Coordinate::absoluteCoordinate('')
#2 PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx/DefinedNames.php(169): PhpOffice\PhpSpreadsheet\Cell\Coordinate::absoluteReference('')
#3 PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx/DefinedNames.php(45): PhpOffice\PhpSpreadsheet\Writer\Xlsx\DefinedNames->writeNamedRangeForPrintArea(Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), 1)
#4 PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Workbook.php(56): PhpOffice\PhpSpreadsheet\Writer\Xlsx\DefinedNames->write()
#5 PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(372): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Workbook->writeWorkbook(Object(PhpOffice\PhpSpreadsheet\Spreadsheet), true)
#6 example.php(12): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save('/tmp/test_out.xlsx')

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$file_in='/tmp/test_in.xlsx';
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
$spreadsheet = $reader->load($file_in);

//call xlsx writer without any modification

$file_out='/tmp/test_out.xlsx';
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save($file_out);
```

### Which versions of PhpSpreadsheet and PHP are affected?
php 7.4 and PhpSpreadsheet 1.18.0

I would prefer to send `test_in.xlsx` file privately

**Comment by stSaHiB** [comment]
same problem here when opening a file and saving it, using 1.21.0. 
Worked with old Versions (~8.12)

It seems like the printareas arent read from the source file, if they are defined in there. 
Quickfix to prevent the error occurring: open source file in excel and set **print scaling** in **page setup** to 100% (or just remove the print area).

Or if you need scaling, set the printarea by hand:
`$sheets['main']->getPageSetup()->setPrintArea("{$col_min}1:{$col_max}{$row_count}");`

**Comment by oleibman** [comment]
I created a spreadsheet with a print area, and read it and created a copy using the code above. No problem. To investigate further, I will need to see an example of a spreadsheet that demonstrates this problem.

**Comment by oleibman** [comment]
No update in 6 months. No file to demonstrate problem. Closing.
