### ISSUE TITLE
Keep leading 0 in postal code for csv export file

### ISSUE THREAD

**Issue by adam314315** [PHPOffice/PhpSpreadsheet#2230]
Hello,

Is there a way to format a cell as a postal code format (5 digit number for France for instance) for a csv export file because the leading 0 currently gets removed when the data are exported : so 01000 appears in the csv as 1000 (instead of 01000) expected. I tried the following solutions but all of them failed. I suspect they work with xls and xlsx export file but not with csv. Any solution please ?

$sheet->getStyle('A1')
                ->getNumberFormat()
                ->setFormatCode( '00000');

or 

$sheet->getStyle('A1')
                ->getNumberFormat()
                ->setFormatCode('#####')

ord 
$sheet->getStyle('A1')
                ->getNumberFormat()
   ->setFormatCode(
                    \PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_GENERAL
                );

**Comment by oleibman** [comment]
The following should work:
```php
$worksheet->getCell('A1')->setValueExplicit(
    '00123', 
    \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING
);
```
An alternate approach to setValueExplicit, which might or might not be better for you depending on the other data in the spreadsheet, is to use StringValueBinder rather than DefaultValueBinder before you begin to populate your cells:
```php
\PhpOffice\PhpSpreadsheet\Cell\Cell::setValueBinder(
    new \PhpOffice\PhpSpreadsheet\Cell\StringValueBinder()
);
```
Note that, with either approach, if you open the CSV in Excel, it will drop the leading zeros; I don't know a way to prevent that from happening. But the zeros will be present in the file.

**Comment by adam314315** [comment]
Thanks for the reply. I just checked and the csv contains the leading 0 as you mention.
But my issue still remains how to open the csv file with Excel and keep the leading 0.

**Comment by MarkBaker** [comment]
MS Excel's CSV loader will always convert a numeric string into a number value when the csv file is opened in Excel; that's behaviour that only Microsoft could change. The only way to retain that formatting is to use the Data/Get&Transform/FromCSV option inside MS Excel that allows you to specify the rules for import of the different columns

**Comment by fwilliamconceicao** [comment]
For Excel is understandable that but this is happening also with Apache Office, Open Office, and other packages as well, it's all these packages is problematic with that too?

**Comment by MarkBaker** [comment]
Please note that we develop and maintain PhpSpreadsheet; we are not responsible in any way for maintaining MS Excel, Apache Office, Open Office, etc.
