### ISSUE TITLE
Reading json inside csv

### ISSUE THREAD

**Issue by vishalv26** [PHPOffice/PhpSpreadsheet#2244]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
should read json correctly

### What is the current behavior?
it is splitting the json as well for comma 

### What are the steps to reproduce?
example file https://we.tl/t-YmfM4hG1Tp

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...

$reader->setDelimiter(',');
$spreadsheet = $reader->load("Book1.csv");
$worksheet2 = $spreadsheet->getActiveSheet()->toArray(null, false, true, true);
```

### Which versions of PhpSpreadsheet and PHP are affected?
Latest

**Comment by oleibman** [comment]
The builtin Php function fgetcsv has an unfortunate default escape character of back-slash, which does not match how Excel handles that character. Your file contains back-slashes, and that is what the problem is. There is an easy solution:
```php
$reader->setEscapeCharacter((version_compare(PHP_VERSION, '7.4') < 0) ? "\x0" : '');
```

**Comment by oleibman** [comment]
No update since July. Believe suggestion addresses issue.
