### ISSUE TITLE
[Page order] is set, Excel 2013 or earlier has an error.

### ISSUE THREAD

**Issue by soony1st** [PHPOffice/PhpSpreadsheet#2245]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

In relation to #1528, 
I followed the same steps to save an excel file,

[Page Setup]->[Sheet]->[Page order]
    - [Over, then down]

Make file test.xlsx:
![image](https://user-images.githubusercontent.com/47043312/127839886-351f6b8b-25f3-4da3-b29f-e8bcb65fc477.png)

The file is then loaded into PhpSpreadsheet and saved as is.

```php
<?php
use PhpOffice\PhpSpreadsheet\Reader\Xlsx as ReaderXlsx;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as WriterXlsx;

    public function main()
    {
        $reader = new ReaderXlsx();
        $spread = $reader->load('test.xlsx');
        $writer = new WriterXlsx($spread);
        $writer->save('test_out.xlsx');
    }
```

Then, when I open the saved file, Excel 2016 or later has no problem, 
but Excel 2013 or earlier has an error. 

![image](https://user-images.githubusercontent.com/47043312/127844106-68591866-01b0-4b2b-af7b-9c9cdbd9f985.png)

### Which versions of PhpSpreadsheet and PHP are affected?

```
"name": "phpoffice/phpspreadsheet",
"version": "1.18.0",
```

**Comment by oleibman** [comment]
In the test suite, tests/data/Reader/XLSX/PageSetup.xlsx sets Page Order differently on different sheets. Running your test script, I create a copy, and it opens correctly in Excel 365 and Excel 2007, using PhpSpreadsheet Releases 18 and 19, and master. If you have a file that behaves differently, can you please upload it.

**Comment by oleibman** [comment]
No update in 6 months. No problem with files matching reported symptom, and no file upload to show a different result. Closing.
