### ISSUE TITLE
Fraction formatting incorrect for decimals with leading zeros

### ISSUE THREAD

**Issue by crobbinsdg** [PHPOffice/PhpSpreadsheet#2253]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The function \PhpOffice\PhpSpreadsheet\Style\NumberFormat\FractionFormatter::format should convert decimals that lead with a zero.  Example 0.0625 to 1/16

### What is the current behavior?
Currently the example 0.0625 will be returned as 5/8

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$value = 0.0625;
$fraction = \PhpOffice\PhpSpreadsheet\Calculation\TextData::TEXTFORMAT($value, "#???/???");

// or

$fraction = \PhpOffice\PhpSpreadsheet\Style\NumberFormat\FractionFormatter::format($value, "#???/???");

```
The issue looks to be use of the TRIM() function on line 16 of /PhpSpreadsheet/Style/NumberFormat/FractionFormatter.php
The TRIM() function will remove the leading zero from 0625 and thus the incorrect $decimalLength is returned in like 17.

### Which versions of PhpSpreadsheet and PHP are affected?

1.18.0

Thanks!

**Comment by crobbinsdg** [comment]
@oleibman new code works great.  Thank you!

**Comment by oleibman** [comment]
Glad to hear it. Thank you for pointing out the problem, and confirming the resolution.
