### ISSUE TITLE
set background of charts to be transparent /  hide axis

### ISSUE THREAD

**Issue by komgrip** [PHPOffice/PhpSpreadsheet#2257]
<img width="888" alt="Screen Shot 2564-08-06 at 21 46 13" src="https://user-images.githubusercontent.com/84488643/128528468-a2a7141d-cc8c-4be3-bec8-0fa5df669cf7.png">

1. Does the package have a function to set background of charts to be transparent? If not, Can you add a feature to set them?

2. Does the package have a function to hide Axis on charts ? If not, Can you add a feature to set them? I found the solution here
https://github.com/cwolcott/PhpSpreadsheet

**Comment by oleibman** [comment]
PR 2950 will add these features. You will need to specify both $chart->setNoFill() and $plotArea->setNoFill() to control the background (you can do this for chart on its own, but that will do only part of what you want; doing it for plotArea alone will be ineffective). You will be able to specify $axis->setAxisOption('hidden', '1') to hide the axis.
