### ISSUE TITLE
mb_convert_encoding(): Illegal character encoding specified

### ISSUE THREAD

**Issue by hadishahpuri** [PHPOffice/PhpSpreadsheet#2261]
this is a bug report for reading .xls files in Linux.
the code is : 
        $reader = new Xls();
        $excel = $reader->load($file); // $file is a .xls file

the code above works normally in windows but when trying to load that file on a Linux server the process exits with this error:
mb_convert_encoding(): Illegal character encoding specified,
the file that throws the error: src/PhpSpreadsheet/Shared/StringHelper.php -> line: 454
the requested encoding is UTF-8 and the current encoding (as what the log file says) is "MAC"

**Comment by oleibman** [comment]
Unable to duplicate with some xls files on my Linux system. Can you share a file that demonstrates this problem?

**Comment by hadishahpuri** [comment]
yes. give me an email address

**Comment by hadishahpuri** [comment]
[31.5.21 price file.xls](https://github.com/PHPOffice/PhpSpreadsheet/files/6962505/31.5.21.price.file.xls)

**Comment by oleibman** [comment]
I am unable to duplicate your problem. But my system supports the 'MAC' encoding:
```
$ iconv -l | grep MAC
CSISO111ECMACYRILLIC//
CSMACINTOSH//
ECMACYRILLIC//
MAC-CENTRALEUROPE//
MAC-CYRILLIC//
MAC-IS//
MAC-SAMI//
MAC-UK//
MAC//
MACCYRILLIC//
MACINTOSH//
MACIS//
MACUK//
MACUKRAINIAN//
MS-MAC-CYRILLIC//
MSMACCYRILLIC//
```
I am guessing that yours doesn't. If not, there are ways to extend it - see, for example:
https://unix.stackexchange.com/questions/626852/is-there-a-way-to-extend-iconv-to-support-more-encodings

**Comment by hadishahpuri** [comment]
thanks for the response! it worked for me
