### ISSUE TITLE
Read Big files with IReadFilet

### ISSUE THREAD

**Issue by K0cmoc** [PHPOffice/PhpSpreadsheet#2268]
This is:

- [ ] a bug report
```

### What is the expected behavior?
When I'm trying to read big xlsx file (200k+ rows) - I want to read only first three rows. I'm using IReadFilter. I expect that reader read just 3 rows of file and I get data.

### What is the current behavior?
The library tries first to read the whole file, so process crashed with allocation memory error.

### Which versions of PhpSpreadsheet and PHP are affected?
Confirmed affected version: 1.18.0

**Comment by MarkBaker** [comment]
Perhaps you could show some code for your Read Filter, and how you're using it to load the file... note that the whole file will stil be ___read___ but only the cells that match the Read Filter will be ___loaded into memory___

**Comment by K0cmoc** [comment]
Thank you so much for your answer. I really thought that the library read just first three rows instead of the whole file. This will solve my problem.
