### ISSUE TITLE
SYLK Comments

### ISSUE THREAD

**Issue by SheetJSDev** [PHPOffice/PhpSpreadsheet#2276]
This is:

```
- [ ] a bug report
- [x] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

This SYLK file includes cell comments:

```
ID;PWXL;N;E
P;PGeneral
F;P0;DG0G10;M320
B;Y3;X1;D0 0 9 0
C;Y1;X1;AZeratul: :En Taro Adun!
C;Y2;X2;AArthas: :Frostmourne Hungers.
C;Y1;X1;K1
C;Y1;X2;K2
C;Y2;X1;K3
E
```

(The control characters are `\x1b` and are part of the encoding of newlines characters)

The `A` field in SYLK apparently specifies a cell comment.

### What is the expected behavior?

Comment text should be available at `$sheet->getComment("A1")->getText()` and `$sheet->getComment("B2")->getText()`

### What is the current behavior?

No text is available

### What are the steps to reproduce?

Save the SYLK codeblock to `comment.slk` and run

```php
<?php

require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load("comment.slk");
$sheet = $spreadsheet->getActiveSheet();
print_r($sheet->getComment("B2")->getText());
```

### Which versions of PhpSpreadsheet and PHP are affected?

All versions of PHPSpreadsheet and every commit of PHPExcel on github

**Comment by oleibman** [comment]
See #2267 for an additional issue regarding SYLK.

This one actually involves two separate issues - lack of support for comments, and lack of support for escape sequences. The latter aren't particularly well-documented. https://outflank.nl/upload/sylksum.txt has a description under "ASCII Escapes" which completely describes the "encoding of newlines" above. It also describes "ISO Escape Codes", although I find that section to be incomplete; in particular, I find no reference which tell which values are assigned for for "accent designators" (though some of these can be determined by trial and error).

**Comment by PowerKiKi** [comment]
https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.19.0
