### ISSUE TITLE
It's impossible to set the CSV delimiter to null after it is set to another value.

### ISSUE THREAD

**Issue by ozanhazer** [PHPOffice/PhpSpreadsheet#2287]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

We should be able to set the delimiter to `null` so that the delimiter is inferred from the file.

```php
$reader->setDelimiter(',');
$reader->setDelimiter(null); // throws TypeError
```

Laravel-excel package sets the delimiter to a comma by default (for performance issues I guess) and it's not possible to set it back to `null` afterwards. See also [laravel-excel #3346](https://github.com/Maatwebsite/Laravel-Excel/issues/3346)

### What is the current behavior?

It throws `TypeError` since the signature of `\PhpOffice\PhpSpreadsheet\Reader\Csv::setDelimiter` does not allow null values.

### Which versions of PhpSpreadsheet and PHP are affected?

`v1.17.*` is fine, got the error with `v1.18` and php8.

**Comment by PowerKiKi** [comment]
Fixed in [1.19.0](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.19.0)
