### ISSUE TITLE
Existing PHP 8.1 fix - Maybe better the other way around?

### ISSUE THREAD

**Issue by brainfoolong** [PHPOffice/PhpSpreadsheet#2291]
I had found this bug in current stable and i searched if it is already fixed in master.
It is, but maybe should be fixed the other way around, to prevent other unexpected conversation problems?

https://github.com/PHPOffice/PhpSpreadsheet/blob/bc9234e5a505e54ce00d3c815d826cd0f5a435c6/src/PhpSpreadsheet/Calculation/Calculation.php#L4480

I suggest

    if (is_string($token) && isset(self::$binaryOperators[$token])) {

As, maybe in some time in the future, boolean will also be not accepted for implicit conversation.
As `self::$binaryOperators[$token]` cannot logically only contain strings, it should be the best way to do this.

I don't created a pull request, as i don't have the insights that the patcher had for this fix. Maybe it is for a reason.

**Comment by oleibman** [comment]
Using is_string here does not solve the problem that was the reason for this change in the first place - a key such as `'8.2'` was treated as numeric, and additional type checking in more recent releases of PHP will not accept a floating-point key - earlier releases of PHP cast the float to int.

**Comment by brainfoolong** [comment]
Ok. Thanks for the answer. I've tested it with a string `"8.1"` and in PHP 8.1 this is no problem, as it is a real string. It is only a problem when it is a real float.
Therefore i thought of fixing all other possible issues when probably a boolean is in `$token` and when this become a problem in a future version.

The check for `is_string` would fix any possible rare case that can be problematic.
Also because only `strings` are in `self::$binaryOperators[$token]`, so it would somehow make sense to check for the type before trying to access the key with an unsupported value.

The fix with `is_numeric` does work for PHP 8.1, no problems here. But the fix with `is_string` will fix it once and for all. I can imagine that PHP will be more strict in future version, where probably a boolean, for example, will also throw implicit conversation errors.

Anyway, it was just a hint from my side, to probably fix this better. No problems with the current solution what so ever.
