### ISSUE TITLE
Define point size on scatter chart

### ISSUE THREAD

**Issue by GajowyJ** [PHPOffice/PhpSpreadsheet#2298]
This is:

```
- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
An user can define point size on scatter chart.

### What is the current behavior?
Point size is hardcoded for 3.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// just create any scatter chart 
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 8.0.10
PhpSpreadsheet 1.18.0

**Comment by GajowyJ** [comment]
Proposed solution:

1. Add following code to Chart\DataSeriesValues.php:
```
class DataSeriesValues
{
	// ...
	private $pointSize;
	public function __construct( // ...
	{
		// ...
		$this->pointSize = 3;
	}
	// ...
}
```

2. Change following code in Writer\Xlsx\Chart.php:
```
	if ($plotSeriesMarker !== 'none') {
		$objWriter->startElement('c:size');
		//$objWriter->writeAttribute('val', 3);	//  removed
		$objWriter->writeAttribute('val', $plotSeriesValues->getPointSize());	// added
		$objWriter->endElement();
	}
```

**Comment by bridgeplayr** [comment]
I can verify that this modification is effective.  Thank you @GajowyJ
