### ISSUE TITLE
Define color of the marker on a chart

### ISSUE THREAD

**Issue by GajowyJ** [PHPOffice/PhpSpreadsheet#2299]
This is:

```
- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
An user can define marker's (point) color on a chart.

### What is the current behavior?
The marker's color is not definable.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// just create any scatter chart 
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 8.0.10
PhpSpreadsheet 1.18.0

**Comment by GajowyJ** [comment]
Proposed solution:
Modify (add) code in Writer\Xlsx\Chart.php
```
private function writePlotGroup( // ...
	// ...
	 if ($plotSeriesMarker) {
		// ...
		// marker (point) color
		$fillColor = $plotSeriesValues->getFillColor();
		if( !is_null($fillColor) ) 
		{
			$objWriter->startElement('c:spPr');
			$objWriter->startElement('a:solidFill');
			$objWriter->startElement('a:srgbClr');
			$objWriter->writeAttribute('val',$fillColor);
			$objWriter->endElement();	// a:srgbClr
			$objWriter->endElement();	// a:solidFill
			$objWriter->endElement();	// c:spPr
		}
	// ...
```

**Comment by bridgeplayr** [comment]
Thank you, @GajowyJ.  This proposed code in Writer\Xlsx\Chart.php must be modified to account for non-hex (string) colors, which require xml color attribute 'schemeClr'.  Something like this: 

> 

            // specify marker type, size & color 
            $fill = $border = $fillColorType = $borderColorType = 0;
            if ($plotSeriesValues) 
            {
                $plotSeriesMarker = $plotSeriesValues->getPointMarker();
                if ($plotSeriesMarker) 
                {
                    $objWriter->startElement('c:marker');
                    $objWriter->startElement('c:symbol');
                    $objWriter->writeAttribute('val', $plotSeriesMarker);
                    $objWriter->endElement();

                    if ($plotSeriesMarker !== 'none') 
                    {
                        $objWriter->startElement('c:size');
                        $objWriter->writeAttribute('val', $plotSeriesValues->getPointSize());
                        $objWriter->endElement();
                    }

                    // marker (point) fill | [fill border] color 
                    $fillColor = $plotSeriesValues->getFillColor();
                    if (!is_null($fillColor) ) 
                    {
                        if (is_array($fillColor))
                        {
                            $fill   = array_shift($fillColor);
                            $border = array_shift($fillColor);
                            if (is_int($fill))
                            {
                                $fillColorType    = 'srgbClr' ;
                                // excel expects 6 character hex color; dechex suppresses leading zeroes
                                $fill = sprintf("%'06X",$fill); // excel expects 6 character hex value
                            }
                            else 
                            {
                                $fillColorType    = 'schemeClr';
                            }
                            if (is_int($border))
                            {
                                $borderColorType = 'srgbClr' ;
                                $border = sprintf("%'06X",$border);
                            }
                            else 
                            {
                                $borderColorType = 'schemeClr';
                            }
                        }
                        else // if not array, $fillColor is border color
                        {
                            $border = $fillColor;
                            $borderColorType    = is_int($border) ? 'srgbClr' : 'schemeClr';
                        }
                        $objWriter->startElement('c:spPr');
                        if ($fill) 
                        {
                            $objWriter->startElement('a:solidFill');
                            $objWriter->startElement('a:' . $fillColorType);
                            $objWriter->writeAttribute('val',$fill);
                            $objWriter->endElement();  // a:xxxxClr
                            $objWriter->endElement();  // a:solidFill
                        }
                        if ($border) 
                        {
                            $objWriter->startElement('a:ln');
                            $objWriter->startElement('a:solidFill');
                            $objWriter->startElement('a:' . $borderColorType);
                            $objWriter->writeAttribute('val',$border);
                            $objWriter->endElement();  // a:xxxxClr
                            $objWriter->endElement();  // a:solidFill
                            $objWriter->endElement();  // a:ln
                        }
                        $objWriter->endElement();  // c:spPr
                    }
                    $objWriter->endElement(); // marker
                }
            }
`

**Comment by oleibman** [comment]
@bridgeplayr Thank you for the explanation of schemeClr. It explains a lot of the color anomalies I'm seeing in the Chart samples. However, it shows up in many more places than just the original "color of the marker on a chart". Please open up a new issue specific to schemeClr. In addition to cross-referencing this issue, you should point out that it currently isn't supported for, among many others, 32readwriteAreaChart1.
