### ISSUE TITLE
Is it possible to memory leak?

### ISSUE THREAD

**Issue by alcom93** [PHPOffice/PhpSpreadsheet#23]
```php
$identify = IOFactory::identify($pathToFile);
$reader = IOFactory::createReader($identify);

$spreadsheet = $reader->load($pathToFile);

unset($reader, $identify);

$worksheet = $spreadsheet->getSheet(0);
$maxRowNumber = $worksheet->getHighestDataRow();

for($row = 1; $row<=$maxRowNumber; ++$row)
{
	$rowToArr = array();

    for($column = 0; $column <= 7; ++$column) {
    	$cell = $worksheet->getCellByColumnAndRow($column,$row);
        if (!is_null($cell)) {
        	$value = $cell->getValue();
					
            // Date/time
            if($column == 7) {
            	if ($value >= 1) {
                	$value = NumberFormat::toFormattedString($cell->getCalculatedValue(), 'd:hh:mm:ss');
                }
                if ($value < 1) {
                	$value = NumberFormat::toFormattedString($cell->getCalculatedValue(), 'hh:mm:ss');
                }
            }

            array_push($rowToArr, $value);
        }
        $cell  = null;
        $value = null;
        }
}
```
18000 rows
8 columns
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4104 bytes) in /var/www/rgmc/administrator/components/com_muzplaylist/vendor/phpspreadsheet-dev/PhpSpreadsheet/Style/NumberFormat.php on line 477

**Comment by PowerKiKi** [comment]
It's a known fact that PhpSpreadsheet use quite a lot of memory. Try increasing your memory limit or have a look at [cell caching](https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/Documentation/markdown/Overview/04-Configuration-Settings.md#cell-caching).

If nothing works and you think it's a bug, then please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue.

**Comment by permanovd** [comment]
@alcom93 i think it is leak. found workaround. see #556 

This case can be resolved by

```php
<?php

$cell->detach(); // instead of $cell  = null;

```
