### ISSUE TITLE
Problem with isFormula() / Calculation::CALCULATION_REGEXP_CELLREF

### ISSUE THREAD

**Issue by billynoah** [PHPOffice/PhpSpreadsheet#2304]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

In **PhpSpreadsheet/Calculation/Functions.php** the function `isFormula()` uses regex `Calculation::CALCULATION_REGEXP_CELLREF` which should be able to successfully parse `$cellReference`.

### What is the current behavior?

Regex `Calculation::CALCULATION_REGEXP_CELLREF` fails to parse `$cellReference`.  Actually - the regex is not even checked before referencing `$matches`.

### What are the steps to reproduce?

In the spreadsheet I am trying to read when I echo `$cellReference` I get: `Load Sheet!F3`.  The regex fails in this case and so the following lines reference keys which do not exist since `$matches` is empty:
```
$cellReference = $matches[6] . $matches[7];
$worksheetName = str_replace("''", "'", trim($matches[2], "'"));
```

At the very least there should be a check like:
```
if preg_match(...) {
```

And probably, the regex `Calculation::CALCULATION_REGEXP_CELLREF` should be updated to address this case.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';
PhpOffice\PhpSpreadsheet\IOFactory::load('test_case.xlsx');
```

**Using this file for testing**: [test_case.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7217271/test_case.xlsx)

### Which versions of PhpSpreadsheet and PHP are affected?

This has been an ongoing issue and affects 1.18.0 (Current version) + all previous versions I have used

**Comment by PowerKiKi** [comment]
Fixed in [1.19.0](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.19.0)
