### ISSUE TITLE
$validation->setSqref('B5:B1048576'); method not found

### ISSUE THREAD

**Issue by init-database** [PHPOffice/PhpSpreadsheet#2310]
Hi, I have read about applying validation to a range of cells by using this:

`$validation->setSqref('B5:B1048576');`

So I gave it a try but my IDE complaint saying `setSqref ` method not found in `\PhpOffice\PhpSpreadsheet\Cell\DataValidation`

How can I use that method correctly?

Thanks,

Doc: https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#setting-data-validation-on-a-cell

**Comment by oleibman** [comment]
The change which added this has not yet been merged. Are you able to test against master?

**Comment by pleaseyang** [comment]
Composer V1.18.0 无方法 ``` setSqref ``` 什么时候可以更新

**Comment by pleaseyang** [comment]
> Composer V1.18.0 无方法`setSqref`什么时候可以更新

Composer V1.18.0 Error : Call to undefined method PhpOffice\PhpSpreadsheet\Cell\DataValidation::setSqref()

**Comment by oleibman** [comment]
Fixed in [1.19.0](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.19.0)

**Comment by BlueSky-Software** [comment]
Many thanks for the update. 
I've had to move onto another project at the moment but I'll check it out as soon as I can.

Thanks again.
Derek
