### ISSUE TITLE
How can I keep the cell height from changing from the original formatting?

### ISSUE THREAD

**Issue by tsutsu221** [PHPOffice/PhpSpreadsheet#2313]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
How can I keep the cell height from changing from the original formatting?

### What is the current behavior?
Every time I save my Excel file to XLSX, the cell height in the sheet changes from how I originally formatted it when I output Excel by PhpSpreadsheet.

### What are the steps to reproduce?
$spreadsheet->getActiveSheet()->getRowDimension($row)->getRowHeight();

I tried using this method but it didn't fix the problem.

Thanks in advance!

**Comment by oleibman** [comment]
```php
$spreadsheet->getActiveSheet()->getRowDimension($row)->setRowHeight($value);
```
That should work. If you don't think it does, please supply the spreadsheet and code which fails, and PhpSpreadsheet and Php version numbers.

**Comment by oleibman** [comment]
Closing, no update in 6 months, no reason to think suggested solution doesn't work.

**Comment by apmuthu** [comment]
```php
$value = $spreadsheet->getActiveSheet()->getRowDimension($row)->getRowHeight();
```
will yield `-1` if it was not set and a value of `15` would be taken as default.

Hence it is essential that when a spreadsheet is loaded, we will need to explicitly provide Row Height values for accurate rendering using:
```php
$value = $spreadsheet->getActiveSheet()->getRowDimension($row)->setRowHeight($value);
```
