### ISSUE TITLE
TypeError: Illegal offset type in file Xlsx.php on line xxx

### ISSUE THREAD

**Issue by terrylinooo** [PHPOffice/PhpSpreadsheet#2316]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Load .xlsx file without error.

### What is the current behavior?

TypeError: Illegal offset type in file xxxxx/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 962

### What are the steps to reproduce?

Create a spreadsheet from Google Doc, then download it to local disk.
Load the .xlsx file.

### Which versions of PhpSpreadsheet and PHP are affected?

1.18

I trace the bug and see this

![image](https://user-images.githubusercontent.com/11989371/136150377-5eb4d538-f28e-48a4-abfb-67dc5bcf43f8.png)

Should check the blue part instead of red part.
I comment out the line and thing goes good now. But I think it should be fixed in here instead of modifying the vendor code.

**Comment by oleibman** [comment]
Can you supply a test file which demonstrates this problem?

**Comment by terrylinooo** [comment]
Thank you. I will test it again later.

**Comment by Michel-Cavaud** [comment]
Hello,
Do you have a date for correcting the problem on the master?
Thank you
