### ISSUE TITLE
my SonarQube analisys mark this as a Blocker security issue

### ISSUE THREAD

**Issue by braguzz** [PHPOffice/PhpSpreadsheet#2324]
https://github.com/PHPOffice/PhpSpreadsheet/blob/cb8ee73355b78db0ff23d54ebf9618e0b57c7e8b/src/PhpSpreadsheet/Document/Security.php#L35

Credentials should not be hard-coded
'password' detected in this variable name, review this potentially hardcoded credential.

What can we do?

**Comment by braguzz** [comment]
I'll test it thanks. Ill let you know.

Il ven 8 ott 2021, 17:40 oleibman ***@***.***> ha scritto:

**Comment by oleibman** [comment]
No update in 5 months, closing.
