### ISSUE TITLE
Writing XLSX decimal or floats, strips the trailing zero

### ISSUE THREAD

**Issue by Formability** [PHPOffice/PhpSpreadsheet#2334]
This is a bug report.

What is the expected behavior?
Write a decimal with a trailing zero. i.e. 
1.10
1.20
1.30

What is the current behavior?
Writes a decimal with the trailing zero removed. i.e.
1.1
1.2
1.3

What are the steps to reproduce?
Write decimals or floats to an xlsx spreadsheet

`<?php
require (classes . "/phpSpreadsheet/vendor/autoload.php");
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$data = Array(1.10,1.20,1.30);

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->fromArray($data, NULL, 'A1');
$sheet->freezePane('A2');

$writer = new Xlsx($spreadsheet);

$file = ("myfile.xlsx");
header('Content-disposition: attachment; filename='.$file);
header('Content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Transfer-Encoding: binary');
header('Cache-Control: must-revalidate');
header('Pragma: public');

$writer->save('php://output');`

**Comment by oleibman** [comment]
Not a bug. Excel will behave exactly the same way - if you enter 1.10 into a cell, it will nevertheless display as 1.1. You need to specify formatting for the cells in question. In Excel, use the Format Cells command. In PhpSpreadsheet:

```php
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;

$lastcol = Coordinate::stringFromColumnIndex(count($data));
$sheet->getStyle("A1:{$lastcol}1")
    ->getNumberFormat()
    ->setFormatCode('0.00');
```

**Comment by mhcwebdesign** [comment]
A bit late to jump in here, but facing a similar issue with trailing zeros being stripped off, even when using PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_TEXT for the format_code, I was wondering if there is a suitable format so it will genuinely see it as an unmodified text?

**Comment by oleibman** [comment]
You can use `setValueExplicit` rather than `setValue`when populating the field to ensure that it is treated as a string. If you do not set the value within your own code, there might be solutions available, e.g. if are reading from a file and you want everything to be treated as a string, you can try using `StringValueBinder`.

**Comment by dominikfiala** [comment]
Just experienced something similiar.
I used the PhpSpreadsheets `fromArray` method. Then figured out I have absolutely no control of the column data type. The value "2010063.020" (a product number) would become "2010063,02" (dot replaced with comma, trimed trailing zeros).
Later I tried converting the cells data type explicitly with `$cell->setValueExplicit($cell->getValue());`
It seemed OK at first, then I realized that the dot-comma replacement was fixed, but the trailing zero was still missing.
In the end I had to abandon the `fromArray` method completely.
Would be nice to be able to combine this method with the columns data type.

**Comment by oleibman** [comment]
You'll have to be more explicit about the problem you're seeing. The following code works for me:
```php
use PhpOffice\PhpSpreadsheet\Cell\StringValueBinder;
use PhpOffice\PhpSpreadsheet\Spreadsheet;

class issue2334 {
    public static function issue() {
        $spreadsheet = new Spreadsheet();
        $spreadsheet->setValueBinder(new StringValueBinder());
        $sheet = $spreadsheet->getActiveSheet();
        $array = [['2010063.020']];
        $sheet->fromArray($array, null, 'A1', true);
        var_dump($sheet->getCell('A1')->getFormattedValue());
    }
}

issue2334::issue();
```

Output:
```
C:\git\issue.2334.php:15:
string(11) "2010063.020"
```
Do you get a different result? You can even set the binder back to DefaultValueBinder once your fromArray call is complete if you wish.

**Comment by dominikfiala** [comment]
Apologies for not being more specific.

What I am looking for is a way to **set a dataType for a whole column**. Current options include writing a custom `valueBinder` class, or using a `setCellValueExplicit` method. Both quite cumbersome.

Lets say I am writing this data (very common) into a spreadsheet and need to keep their bool, string, numeric data types:

```php
$data = [
  [true, '2010063.010', 123.45],
  [false, '2010063.020', 236.78],
  [true, '2010063.030', 498.23],
];
```

The `valueBinder` method:

```php
class CustomValueBinder implements PhpSpreadsheet\Cell\IValueBinder
{
    public function bindValue(PhpSpreadsheet\Cell\Cell $cell, mixed $value): bool
    {
        switch ($cell->getColumn()) {
            case 'A':
                $cell->setValueExplicit($value, PhpSpreadsheet\Cell\DataType::TYPE_BOOL);
                break;
            case 'B':
                $cell->setValueExplicit($value, PhpSpreadsheet\Cell\DataType::TYPE_STRING);
                break;
            default:
                $cell->setValueExplicit($value, PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
                break;
        }

        return true;
    }
}

$spreadsheet = new PhpSpreadsheet\Spreadsheet();
$spreadsheet->setValueBinder(new CustomValueBinder);
$sheet = $spreadsheet->getActiveSheet();
$sheet->fromArray($data);
```

The `setValueExplicit` method:

```php
foreach ($data as $rowIndex => $row) {
    foreach ($row as $columnIndex => $cell) {
        switch ($columnIndex) {
            case 0:
                $sheet->setCellValueExplicit('A' . $rowIndex + 1, $cell, PhpSpreadsheet\Cell\DataType::TYPE_BOOL);
                break;
            case 1:
                $sheet->setCellValueExplicit('B' . $rowIndex + 1, $cell, PhpSpreadsheet\Cell\DataType::TYPE_STRING);
                break;
            default:
                $sheet->setCellValueExplicit('C' . $rowIndex + 1, $cell, PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
                break;
        }
    }
}
```

Suggested way of **setting the column type for whole spreadsheet** (not specified columns use the default data type):

```php
$sheet->setColumnsDataType([
    PhpSpreadsheet\Cell\DataType::TYPE_BOOL,
    PhpSpreadsheet\Cell\DataType::TYPE_STRING,
    PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC,
]);
$sheet->fromArray($data);
```

Suggested way of **setting the column type using `fromArray` method** (not specified columns use the default data type):

```php
$sheet->fromArray($data, null, 'A1', false, [
    PhpSpreadsheet\Cell\DataType::TYPE_BOOL,
    PhpSpreadsheet\Cell\DataType::TYPE_STRING,
    PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC,
]);
```

**Comment by oleibman** [comment]
I will think about this. However, you can already do what you want in a manner that does not seem too burdensome to me (no custom value binder, no set value explicit). Instead of loading the sheet with one `fromArray` call, you can make multiple calls using different value binders.
```php
$dvb = new DefaultValueBinder();
$svb = new StringValueBinder();

$columnA = [
  [true],
  [false],
  [true],
];
$spreadsheet->setValueBinder($dvb);
$sheet->fromArray($columnA, null, 'A1', true);

$columnB = [
  ['2010063.010'],
  ['2010063.020'],
  ['2010063.030'],
];
$spreadsheet->setValueBinder($svb);
$sheet->fromArray($columnB, null, 'B1', true);

$columnC = [
  [123.45],
  [236.78],
  [498.23],
];
$spreadsheet->setValueBinder($dvb);
$sheet->fromArray($columnC, null, 'C1', true);
```

**Comment by oleibman** [comment]
Or you can go back to using a single `fromArray` with the following custom binder, which, again, doesn't seem too onerous and does seem to solve your current predicament:
```php
class PreserveStringsBinder extends DefaultValueBinder
{
    public function bindValue(Cell $cell, mixed $value): bool
    {
        if (is_string($value) && is_numeric($value)) {
            $cell->setValueExplicit($value, DataType::TYPE_STRING);

            return true;
        }

        return parent::bindValue($cell, $value);
    }
}
```
