### ISSUE TITLE
ods writer ignores column width

### ISSUE THREAD

**Issue by black-silence** [PHPOffice/PhpSpreadsheet#2346]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When a column width is set it should be exported and have an effect in Libreoffice. 
Something like `style:column-width="12.118cm"` is expected in content.xml

### What is the current behavior?
Custom column width and autosize have no effect, columns always have the default width in Libreoffice. content.xml contains no column width setting.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$sheet = $spreadsheet->getActiveSheet();

$sheet->setCellValue('A1', 'not so long text');
$sheet->setCellValue('A2', 'longer text to test column width');
$sheet->setCellValue('B1', 0.51);
$sheet->setCellValue('B2', 100051);

$sheet->getColumnDimension('A')->setWidth(666);
#$sheet->getColumnDimension('A')->setAutoSize(true);

#$sheet->getColumnDimension('B')->setWidth(333);
$sheet->getColumnDimension('B')->setAutoSize(true);

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Ods($spreadsheet);
$writer->save('./odsFormating.ods');

```

### Which versions of PhpSpreadsheet and PHP are affected?
phpspreadsheet 1.18.0, php 7.3.31

**Comment by MarkBaker** [comment]
Implemented in `master` read for 1.23.0 release
