### ISSUE TITLE
Verticle line issue in graph/chart, not controllable. 

### ISSUE THREAD

**Issue by dev-deepak-soni** [PHPOffice/PhpSpreadsheet#2353]
In the graph there is a property called setAxisOptionsProperties, we are not able to manage that line according to the bars.
We want to control the vertical line and want to show it accordingly to us.

![image](https://user-images.githubusercontent.com/56436066/138677943-9c80b42a-4058-409e-8ec9-964ac3d340e3.png)

**Comment by oleibman** [comment]
I would need to see your spreadsheet, not just a picture of it, to figure out what is causing that line.

**Comment by oleibman** [comment]
No update in 9 months, closing.
