### ISSUE TITLE
borders and fill colors not working after replacing PHPExcel

### ISSUE THREAD

**Issue by russmenum** [PHPOffice/PhpSpreadsheet#2371]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Have installed PhpSpreadsheet using composer, and overall seems to be working, in that it makes the spreadsheets, but some of the sheets used ```PHPExcel_Style_Border::BORDER_THIN```, ```PHPExcel_Style_Border::BORDER_MEDIUM```, and ```PHPExcel_Style_Fill::FILL_SOLID```. But the ```\PhpOffice\PhpSpreadsheet``` replacements are just exporting a no background no borders spreadsheet 

### What is the current behavior?
The spreadsheets exported have no borders or background colors

### What are the steps to reproduce?

```php
$objPHPExcel->getActiveSheet()->getStyle('A'.$style['start'].':'.$endLetter.$style['end'])->applyFromArray(
  array('fill' => array(
    // 'type' => PHPExcel_Style_Fill::FILL_SOLID,
    'type' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
    'color' => array('argb' => 'FFCCFFCC')
  )
));
```

and

```php
{
$objPHPExcel->getActiveSheet()->getStyle('A'.$style['start'].':'.$endLetter.$style['end'])->applyFromArray(
  array('borders' => array(
    // 'bottom'	=> array('style' => PHPExcel_Style_Border::BORDER_THIN),
    // 'right'		=> array('style' => PHPExcel_Style_Border::BORDER_MEDIUM)
    'bottom'	=> array('style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN),
    'right'		=> array('style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_MEDIUM)
  )
));
}
```

are examples of the changes when switching to PhpSpreadsheet that are just not working right. Any ideas?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet and PHP are affected?
Am using PHP 7.4.21

**Comment by oleibman** [comment]
There were some changes between PhpExcel and PhpSpreadsheet affecting property names, and therefore the indexes used in applyFromArray. Your fill example should be:
```php
        $objPHPExcel->getActiveSheet()->getStyle('A'.$style['start'].':'.$endLetter.$style['end'])->applyFromArray(
          array('fill' => array(
            'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
            'color' => array('argb' => 'FFCCFFCC')
          )
        ));
```

Your border example should be:
```php
        $objPHPExcel->getActiveSheet()->getStyle('A'.$style['start'].':'.$endLetter.$style['end'])->applyFromArray(
          array('borders' => array(
            'bottom => array('borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN),
            'right' => array('borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_MEDIUM)
          )
        ));
```

**Comment by oleibman** [comment]
No update in 4 months, believe the suggestion solves the problem, closing.
