### ISSUE TITLE
PhpOffice\PhpSpreadsheet\Exception: Invalid datatype: d

### ISSUE THREAD

**Issue by ClCfe** [PHPOffice/PhpSpreadsheet#2373]
Hello

I am using v1.19.0
I am openning an existing Xlsx file and I want to write something in a new sheet

The following error occurs:
```
type: PhpOffice\PhpSpreadsheet\Exception
file: /opt/PhpSpreadsheet/src/PhpSpreadsheet/Cell/Cell.php
line: 233
message: Invalid datatype: d
trace: 
#0 /opt/PhpSpreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php(828): PhpOffice\PhpSpreadsheet\Cell\Cell->setValueExplicit('2021-03-29', 'd')
#1 myscript.php(xxx): PhpOffice\PhpSpreadsheet\Reader\Xlsx->load('...')
```

I can share the file in private

**Comment by ziming** [comment]
My generated excel file had errors on a certain sheet after the latest patch 1.19.0 too

**Comment by alfilipe** [comment]
Hi all

I'm facing the same issue trying to load a xlsx file

what I've done to correct it is to add the datatype on the file \PhpOffice\PhpSpreadsheet\Cell\DataType `const TYPE_DATETIME = 'd';`
and on the file \PhpOffice\PhpSpreadsheet\Cell under the function setValueExplicit  inside the switch case added a new case like bellow
`            case DataType::TYPE_DATETIME:`
`                $cValue=Date::PHPToExceldate(strtotime($pValue));`
`                if (is_string($cValue) && !is_numeric($cValue)) {`
 `                   throw new Exception('Invalid numeric value for datatype Numeric');`
 `               }`
`                $this->value = 0 + $cValue;`
 `               `
`                break;`

**Comment by ziming** [comment]
fixed for me in the latest patch
