### ISSUE TITLE
AUTOFILTER_COLUMN_RULE_NOTEQUAL is actual showing EQUAL

### ISSUE THREAD

**Issue by cwolcott** [PHPOffice/PhpSpreadsheet#2378]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Creating an autofilter rule of **NOTEQUAL** should hide the rows that match the rule.
```
$autoFilter = $worksheet->getAutoFilter();
$columnFilter = $autoFilter->getColumn('G');
$columnFilter->setFilterType(Column::AUTOFILTER_FILTERTYPE_FILTER);
$columnFilter->createRule()->setRule(Rule::AUTOFILTER_COLUMN_RULE_NOTEQUAL, 'LC');
```
### What is the current behavior?
It is showing the rows that are **EQUAL** to 'LC'

### What are the steps to reproduce?
Create a spreadsheet and attempt to filter column NOTEQUAL to a specific text value.

### Which versions of PhpSpreadsheet and PHP are affected?
1.18.0

### Images
Spreadsheet view after performing **NOTEQUAL**, it is actually showing **EQUAL**
```$columnFilter->createRule()->setRule(Rule::AUTOFILTER_COLUMN_RULE_NOTEQUAL, 'LC');```
<img width="368" alt="AUTOFILTER_COLUMN_RULE_NOTEQUAL" src="https://user-images.githubusercontent.com/3777526/140607285-4917e7d8-865b-4c16-aee0-f9252ad6356c.png">

This is what the spreadsheet looks like with no AutoFilter applied (Note: EW rows are further down in the spreadsheet and aren't show in the screen capture)
<img width="368" alt="No AUTOFILTER applied" src="https://user-images.githubusercontent.com/3777526/140607350-118af2e7-0295-417f-9f28-b91bb6b38149.png">

**Comment by oleibman** [comment]
On its own, when Excel creates a sheet with an EQUAL filter, the XML uses a `<filters>` tag followed by `<filter>` without attribute `operator`; when it creates a sheet with a NOTEQUAL filter, it uses a `<customFilters>` tag followed by `<customFilter operator='notEqual' ...>`. PhpSpreadsheet is currently generating `<filters>` in both cases, leading to your result. I need to research when exactly `<customFilters>` is required.

**Comment by oleibman** [comment]
At least for the moment, you should change your code. It won't be sufficient, but you should probably be specifying:
```php
        $columnFilter->setFilterType(Column::AUTOFILTER_FILTERTYPE_CUSTOMFILTER);
        $columnFilter
            ->createRule()
            ->setRule(Rule::AUTOFILTER_COLUMN_RULE_NOTEQUAL, 'LC')
            ->setRuleType(Rule::AUTOFILTER_RULETYPE_CUSTOMFILTER);
```
That is not yet sufficient because the code in AutoFilter filterTestInCustomDataSet does not yet support Not Equal for strings. That has to change (I think I already know how), test cases need to be added, and documentation changes are probably needed. It will take a while for me to figure out exactly what is needed here. For example, to ease the burden on the developer, it would be easy to change the RuleType when NotEqual is the rule, but I don't know if it's legitimate to also change the column filter type at the same time.

**Comment by cwolcott** [comment]
Thanks @oleibman, this is not a critical issue for me.  It is just an option I wanted to show the end user.
The suggestion doesn't work either, see code and image below:
```
$autoFilter = $worksheet->getAutoFilter();
$columnFilter = $autoFilter->getColumn('G');
$columnFilter->setFilterType(Column::AUTOFILTER_FILTERTYPE_CUSTOMFILTER);
$columnFilter->createRule()
            ->setRule(Rule::AUTOFILTER_COLUMN_RULE_NOTEQUAL, 'LC')
            ->setRuleType(Rule::AUTOFILTER_RULETYPE_CUSTOMFILTER);
```
<img width="387" alt="AlternateCodeAttempt" src="https://user-images.githubusercontent.com/3777526/140618973-f410fde8-95e6-44cb-b85d-071ab2c5d69b.png">

**Comment by oleibman** [comment]
As I mentioned, the suggestion isn't sufficient without a code change. I'm looking into it.

**Comment by cwolcott** [comment]
Sorry, I guess I overlooked that.  Thank you for looking into it.  Like I said earlier this is not a priority issue for me.  It is a minor option that I am presenting to the end user on how to configure the initial spreadsheet.  Obviously they can do this by hand after opening the spreadsheet.
