### ISSUE TITLE
diagonal border cannot working

### ISSUE THREAD

**Issue by rusdiyuqing** [PHPOffice/PhpSpreadsheet#2379]
$styleArray = [
    'borders' => [
        'diagonal' => [
            'borderStyle' => Border::BORDER_THICK,
            'color' => ['argb' => 'FFFF0000'],
        ],
    ],
];

$spreadsheet->getActiveSheet()->->getStyle('A5')->applyFromArray($styleArray);

i type it code, but cannot make diagonal border. 

thanks for your help.

**Comment by oleibman** [comment]
You need to specify a diagonal direction, e.g.
```php
        $styleArray = [
            'borders' => [
                'diagonal' => [
                    'borderStyle' => Border::BORDER_THICK,
                    'color' => ['argb' => 'FFFF0000'],
                ],
                'diagonalDirection' => Borders::DIAGONAL_BOTH,
            ],
        ];
```

**Comment by oleibman** [comment]
Closing. No update in a month, believe the suggested change solves the problem.
