### ISSUE TITLE
Error installing with composer

### ISSUE THREAD

**Issue by bart-prosite** [PHPOffice/PhpSpreadsheet#238]
This is:

- [X] a bug report
- [ ] a feature request

When trying install the package using this command: _composer require phpoffice/phpspreadsheet_ I receive this error:
===============
[InvalidArgumentException]
Could not find package phpoffice/phpspreadsheet at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
===============

Tried with PHP version 5.6 and 7.1

**Comment by treadmillian** [comment]
Have you got this in your composer.json file?

```
"minimum-stability": "dev",
"prefer-stable": true,
```

**Comment by bart-prosite** [comment]
So it was as easy as this. :-/
Maybe this requirement should be in the documentation as wel.
Thank you!

**Comment by treadmillian** [comment]
This issue is not specific to this project at all. Is specific to understanding how composer works.  This isn't a bug, and really, this isn't the forum for help, this is for bug reports only.

However, I felt I'd help a fellow colleague, even if this is really what this should be used for. :)

**Comment by bart-prosite** [comment]
Thank you so much! New to composer. Still a lot to learn.

**Comment by PowerKiKi** [comment]
@bart-prosite you will be able to (and should) remove those lines from composer.json once PhpSpreadsheet 1.0.0 is released

**Comment by chris-schofield1** [comment]
Do you have a rough estimate of when that may be?
