### ISSUE TITLE
Unable to carry forward MS excel Theme colors

### ISSUE THREAD

**Issue by DeekshaPrabhub96** [PHPOffice/PhpSpreadsheet#2387]
This is: I have an excel with text in standard colours and theme colours, Standard colours are working fine on save  but theme colours are converted to black on save.

Using PHPSpreadsheet I. am just opening and saving the file with different name.

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The text with themed colours are saved as it is in the new file.

### What is the current behavior?
In the new file Theme Coloured Text are converted to Black Colour text. (Even White colour text gets converted. For some reason Excel considers white as Theme colour)

### What are the steps to reproduce?
Create an Excel with text in Theme colour and some cells with text in standard colours, Open this file using PHPSpreadsheet and save it with different file name.  

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

// Create new Spreadsheet object
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();

// add code that show the issue here...

 $spreadsheet = $reader->load($file);

$writer = new Xlsx($spreadsheet);
$writer->save('TextColorOutput.xlsx');
[TextColorInput.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7510411/TextColorInput.xlsx)
[TextColorOutput.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7510414/TextColorOutput.xlsx)
<img width="836" alt="Screenshot 2021-11-10 at 12 16 55 PM" src="https://user-images.githubusercontent.com/93675905/141063676-f69d1086-87c7-4c65-a3d8-71370551917a.png">

### Which versions of PhpSpreadsheet and PHP are affected?
1.19

**Comment by oleibman** [comment]
This appears to have worked in 1.17.1, and failed in 1.18.0. It may take a while for me to get to this.

**Comment by DeekshaPrabhub96** [comment]
Hey any update on this?

**Comment by oleibman** [comment]
Yes, I believe I see what happened in 1.18.0 with themes. It will take a day or two to prepare a PR.
