### ISSUE TITLE
Button and list box getting hidden

### ISSUE THREAD

**Issue by DeekshaPrabhub96** [PHPOffice/PhpSpreadsheet#2394]
This is: 
I have an excel with few buttons and list boxes added using Developer Menu. Using PHPSpreadsheet I am just opening and saving the file with different name.

### What is the expected behavior?
The buttons and ListBoxes should be visible

### What is the current behavior?
The Buttons and ListBoxes are in hidden state in the new excel. To make it visible, we have to go to Find and Select -> Selection Pane and Mark it as 'Show'.

### What are the steps to reproduce?
Please check the attachments. I have attached sample input and output file.

```php
<?php
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();

// add code that show the issue here...

$spreadsheet = $reader->load($file);

$writer = new Xlsx($spreadsheet);
$writer->save('TextColorOutput.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.19

[ListandButtonInput.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7520037/ListandButtonInput.xlsx)
[ListandButtonOutpot.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7520039/ListandButtonOutpot.xlsx)

**Comment by oleibman** [comment]
Closing. Testing against a recent version, the output file matches the input, almost certainly because of PR #3130, part of version 1.27.0 Jan. 24, 2023.
