### ISSUE TITLE
Failed to store cell in cache

### ISSUE THREAD

**Issue by Syfele** [PHPOffice/PhpSpreadsheet#2406]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Store current cell to cache  

### What is the current behavior?
CRITICAL : Error thrown while running command "symfony-command-name". Message: "Failed to store cell BB18118 in cache" {"exception":"[object] (PhpOffice\\PhpSpreadsheet\\Exception(code: 0): Failed to store cell BB18118 in cache at project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Cells.php:393)"

### What are the steps to reproduce?

I am using multiple csv files to populate the tables in a database.
As I am on Symfony, I created a command which from a given directory read files in a defined order.
A csv file equals a table in my BD.
File sizes differ from file to file and may contain over than 65 thousand lines.

### The error is displayed with the largest files I am going to use and there are no weird values formats in it, I only have strings and integers 
 
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

In Symfony Command to  setting cache I do  
```php
        $pool = new FilesystemAdapter();
        $simpleCache = new SimpleCacheBridge($pool);
        Settings::setCache($simpleCache); // PhpOffice\PhpSpreadsheet\Settings
        
        // loop directories and call Symfony service ...
<?php 
```
In Symfony Service 
```php
        $spreadSheet = IOFactory::load($csvPath);
        $sheet = $spreadSheet->getActiveSheet()->toArray();
                
        // loop sheet and databases operations ... 
<?php 
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP : 7.4
PhpSpreadsheet : 1.18

What i'm doing wrong ?? Thank you in advance for your answer

**Comment by Syfele** [comment]
anyone can help ?

**Comment by thirsch** [comment]
Hi @Syfele ,

can you check the available space and/or available inodes on the device you are using for your cache? I've had an issue with the same error message and our server ran out of free inodes.

HTH
Thomas
