### ISSUE TITLE
Can't remove empty arrays in a multidimensional array

### ISSUE THREAD

**Issue by guilhems1** [PHPOffice/PhpSpreadsheet#2407]
This is:

```
- [YES] a bug report
- [NO] a feature request
- [NO] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

I am currently working on a small script that gets information from an Xlsx Excel file and puts it in an array (one array per row).
The file isn't exclusively made for IT and it contains lots of empty rows and text that I need to filter out.

I have used a read filter on the range of columns that I need, and a 'setReadEmptyCells(false);' on my reader.
I used an array_filter on my active spreadsheet.

As of now, I'm only displaying the result in the console.

### What is the current behavior?

I still get all of the empty arrays/rows, and the reader only null the columns I don't need but doesn't remove them. So I have 5 columns instead of 3.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;


// Filters on row and column
class ReadFilter implements \PhpOffice\PhpSpreadsheet\Reader\IReadFilter {
    function readCell($col, $row, $worksheetName = '') {
            if(in_array($col,range('B','E'))) { 
                return true;
            }
        return false;
    }
}


$reader = new Xlsx();
$reader->setReadFilter(new ReadFilter());
$reader->setReadEmptyCells(false);

$spreadsheet = $reader->load('./tarifs2022.xlsx');
$array = $spreadsheet->getActiveSheet()->toArray();


//Filter out empty arrays 
$af = array_filter($array, 
    function($v){
        return !is_null($v) && $v !== '';
    }
);

dump($af);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.19.0
PHP 7.4.25

**Comment by Syfele** [comment]
$array contains arrays that match the lines in your excel file, it cannot be null or '' ( $v is an array)
You may need to loop over $array and use array_values(array_filter($ array))

```
$af = []
foreach($arrays as $row) {
 $af[] = array_values(array_filter($row));
}
dump($af);
```

I have not tested this code yet but it should be something like it
I dont think setReadEmptyCells will delete items from $row

**Comment by guilhems1** [comment]
Thank you ! What I did in the end is not actually using an array_filter but a if condition that tests whether the second row is null or contains an "empty" string. Might sound like a newbie because I am lol

Here is my code : 

`$spreadsheet = $reader->load('./tarifs2022.xlsx');
$array = $spreadsheet->getActiveSheet()->toArray();


foreach($array as $row) {
    if(!is_null($row[1]) && $row[1] !== " ") {
        //I have to put these in a DB, this is just for test purpose
        echo "Code : ".$row[1]
        ." Tarif EXP : ".$row[2]
        ." Tarif FR HT : ".$row[3]
        ." Tarif FR TTC : ".$row[4];
        echo "<br/><br/>";
    }
}`

The rest is basically the same, just added a range for the rows too in the filter

**Comment by Syfele** [comment]
Nice ;) Good luck for the rest 
can you please close the issue if it is resolved ?
