### ISSUE TITLE
Formulas are not getting carry forwarded correctly

### ISSUE THREAD

**Issue by DeekshaPrabhub96** [PHPOffice/PhpSpreadsheet#2436]
This is:  In one of the scenario I observed that formula is not carry forwards correctly. I have mentioned the steps to reproduce below.

### What is the expected behavior?
correct formulas has to be carry forwarded 

### What is the current behavior?
formuls are getting changed

### What are the steps to reproduce?

Create a Xlsx sheet.
add Formula for AD6 cell
then drag that cell to copy formulas to different rows in same column.

After opening and saving the file with different name using PHPSpreadsheet, the formula has changed. I have attached a sample excel where issue can be easily reproduced.

```php
<?php
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();

// add code that show the issue here...

$spreadsheet = $reader->load($file);

$writer = new Xlsx($spreadsheet);
$writer->save('TextColorOutput.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.19
[formulaIP.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7666734/formulaIP.xlsx)
[formulaOP.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7666736/formulaOP.xlsx)

**Comment by oleibman** [comment]
Error confirmed in 1.19, but things seem to be working correctly in 1.20 (and master). Please confirm.

**Comment by oleibman** [comment]
3 months, no update, believe issue is fixed. Closing.
