### ISSUE TITLE
Cell style modified

### ISSUE THREAD

**Issue by toboul70** [PHPOffice/PhpSpreadsheet#2441]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Cell Style not modified

### What is the current behavior?
Cell Style modified

### What are the steps to reproduce?
I created an xlsx model with Excel with cells like that 
![1](https://user-images.githubusercontent.com/34251846/145288922-9c915e31-ce65-40c4-a201-4abeb765043f.png)

I made a reader.
I modified some cells (not the cell I show)
I made a writer.

I opened the file. The cell style was modified like that 
![2](https://user-images.githubusercontent.com/34251846/145289228-9e35089b-f984-41a3-b857-ebd03ead728b.png)

File :
[Classeur1.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7679166/Classeur1.xlsx)

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$excel  = new PhpOffice\PhpSpreadsheet\Spreadsheet();
$excel  = PhpOffice\PhpSpreadsheet\IOFactory::load($file);
$org    = $excel->getSheetByName('Sheet1');
$org->setCellValue('A1', 'Hello World');

$writer = PhpOffice\PhpSpreadsheet\IOFactory::createWriter($excel, 'Xlsx');
$writer->save($newfile);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.3.21 (cli) (built: Aug  4 2020 11:21:19) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.21, Copyright (c) 1998-2018 Zend Technologies

"name": "phpoffice/phpspreadsheet",
            "version": "1.20.0",
            "source": {
                "type": "git",
                "url": "https://github.com/PHPOffice/PhpSpreadsheet.git",
                "reference": "44436f270bb134b4a94670f3d020a85dfa0a3c02"

**Comment by oleibman** [comment]
I can tell you what happened. I need to do some research to figure out what should happen. Fill patterns are assigned a start and end color in the constructor. In your original spreadsheet, the fill pattern is output without a start and end color. In the copied version, it is output with a start and end color, which I believe is correct for some other patterns, but apparently not correct for lightUp and, presumably, other patterns.

**Comment by toboul70** [comment]
My original file 
![2](https://user-images.githubusercontent.com/34251846/145352490-ca2a9f02-4618-464c-bd8a-9118bbe53ed9.png)

The copy file
![1](https://user-images.githubusercontent.com/34251846/145352521-5936b35d-a02e-4990-94ba-6d2c23f25d60.png)

**Comment by toboul70** [comment]
Another try

My file
![1](https://user-images.githubusercontent.com/34251846/145352950-dd89fb39-55da-4565-9a95-803e31f659b2.png)

The copy file
![2](https://user-images.githubusercontent.com/34251846/145352980-6b671916-0195-4b71-952c-bb61f461fa0f.png)

In the two cases, the background color is set to grey, just under blank.

**Comment by toboul70** [comment]
Another example :

A cell style modified by PHPExcel :

![3](https://user-images.githubusercontent.com/34251846/145353392-f51a53ff-96e8-4064-bb67-df76909b2532.png)

**Comment by lucasres** [comment]
I have similar problem, when  set a background color in 1.20.0 version dont fill range cell but works well in 1.17.1

```
$spreadsheet
  ->getActiveSheet()
  ->getStyle("$range1:$range2")
  ->getFill()
  ->setFillType(Fill::FILL_SOLID)
  ->getStartColor()
  ->setARGB($cellColor);
```

I dont know if same problem.

Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.4.16 (cli) (built: Apr  1 2021 15:55:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

"name": "phpoffice/phpspreadsheet",
"version": "1.20.0",
"source": {
    "type": "git",
    "url": "https://github.com/PHPOffice/PhpSpreadsheet.git",
    "reference": "44436f270bb134b4a94670f3d020a85dfa0a3c02"
}

**Comment by oleibman** [comment]
I am guessing that you are specifying `$cellColor` as a 6-hex-character string. Argb needs to be 8 characters, rgb needs to be 6. This was not enforced in 1.17.1 but is enforced in 1.20.0.
