### ISSUE TITLE
removeRow 

### ISSUE THREAD

**Issue by toboul70** [PHPOffice/PhpSpreadsheet#2442]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
remove Row and keep style of other cells

### What is the current behavior?
remove Row and keep style of removed Row.

Before removeRow
![1](https://user-images.githubusercontent.com/34251846/145366548-d7f0ace7-6e44-4883-826e-b9f7e3d52a39.png)

After removeRow (row 4)
![2](https://user-images.githubusercontent.com/34251846/145366596-0e5e7aa3-87ea-4243-a6db-be5900494a49.png)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$excel  = new PhpOffice\PhpSpreadsheet\Spreadsheet();
$excel  = PhpOffice\PhpSpreadsheet\IOFactory::load($file);
$org    = $excel->getSheetByName('Feuil1');

$org->removeRow(4, 1);

$writer = PhpOffice\PhpSpreadsheet\IOFactory::createWriter($excel, 'Xlsx');
$writer->setPreCalculateFormulas(false);
$writer->save($filemodified);

?>
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.3.21 (cli) (built: Aug 4 2020 11:21:19) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.21, Copyright (c) 1998-2018 Zend Technologies

"name": "phpoffice/phpspreadsheet",
"version": "1.20.0",
"source": {
"type": "git",
"url": "https://github.com/PHPOffice/PhpSpreadsheet.git",
"reference": "44436f270bb134b4a94670f3d020a85dfa0a3c02"

**Comment by MarkBaker** [comment]
Why wold you expect that behaviour? Like the content, the styling of the cells in a row is removed when those cells are removed; shuffling all subsequent rows up. And this is exactly the behaviour that MS Excel demonstrates when you remove a row.

**Comment by toboul70** [comment]
I expect that the height of the "new line 4" would be the same as "the old line 5".
In my example, it's not the case.

**Comment by MarkBaker** [comment]
Ah! Now I understand. Yes, that looks like a bug, we should also adjust the row heights (and column widths when removing a column as well). Row height isn't maintained as an aspect of cell style; but as an aspect of the worksheet.
