### ISSUE TITLE
 PhpSpreadsheet save with directory

### ISSUE THREAD

**Issue by nadia-am** [PHPOffice/PhpSpreadsheet#2445]
```php
<?php
$writer = new Xlsx($spreadsheet);

$upload_dir = wp_upload_dir();

$basedir   = $upload_dir['basedir'].'/next_shoppingcart';

if (!file_exists($basedir)) {

    mkdir($basedir, 0777, true);

}

$writer->save($basedir.DIRECTORY_SEPARATOR.$file_name);

```
`Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Writer\Exception: Could not open C:\xampp\htdocs\test3\wp-content\plugins\next-shopping-list\admin\templateshoppingcart_report_2021-12-13 17:12:02.xlsx for writing.`

**Comment by oleibman** [comment]
I can't reconcile your code with your error message. According to the code, the string `next_shoppingcart` should be part of the path name to which you are writing. However, I don't see that string in your error message. What are the values of basedir and file_name before you attempt the save?

**Comment by nadia-am** [comment]
i find the solution. that was because of file name "templateshoppingcart_report_2021-12-13 17:12:02.xlsx" I remove _ and : and it's working now
