### ISSUE TITLE
v1.19 has known bug/s which are fixed in v1.20/master, but v1.19 is last version to support php7.2

### ISSUE THREAD

**Issue by davidbuzz** [PHPOffice/PhpSpreadsheet#2446]
```
- [ X] a bug report  and/or
- [ X] a feature request [backport]

```

### What is the expected behavior?
We have a php7.2 based server running PhpSpreadsheet, and it can not run 1.19 due multiple known XLSX bugs documented elsewhere.  it can not be upgraded to 1.20 as the minimum php version supported was increased to php7.3

### What is the current behavior?
broken.

### What are the steps to reproduce?
install 1.19 on a php7.2 server, and discover its currently broken with no upgrade path and no 'lts' fixes.

I'd very much appreciate if a v1.19.1 could be dropped with backported fixes for the XLSX saving bug/s that are currently in 1.19.... or alternatively if 1.20 could be made to work with 7.2, which i presume is harder.

thx

**Comment by oleibman** [comment]
If you must work on a no-longer-supported version of PHP, and there are many reasons why shouldn't, the best that I can suggest is using Composer to download the version you want, and then manually apply the changes you need.

**Comment by MarkBaker** [comment]
There is currently nothing in the 1.20 release that will prevent it running with PHP 7.2; but you will have to install it manually overriding the platform requirement for the PHP version; however, we will no longer actively support 1.20 under PHP 7.2.
```
composer install --ignore-platform-req=php phpoffice/phpspreadsheet
```
Our LTS is to support EOL PHP versions for one year after the reach the end of PHP Security support; PHP 7.2 is now beyond that date, having reached EOL on November 30, 2019, and end of security patches on November 30, 2020; so we dropped support with the 1.20 release on 23 Nov 2021.

**Comment by davidbuzz** [comment]
thx for the tips, i will try it .

**Comment by wardance-ferret** [comment]
@davidbuzz were you successful?
