### ISSUE TITLE
how to get cell style in PhpSpreadsheet with conditional formatting

### ISSUE THREAD

**Issue by duongp131994** [PHPOffice/PhpSpreadsheet#2449]
- [ X] a bug report  and/or

**What is the expected behavior?**

I'm building a function to read excel files using PhpSpreadsheet lib, but I don't know how to read the style of cells with conditional formatting applied. can you help me?

**What is the expected behavior?**

$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($file);
$sheet = $spreadsheet->getActiveSheet();
$maxCell = $sheet->getHighestRowAndColumn();
$maxColIndex = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::columnIndexFromString($maxCell['column']);
for ($ci = 1; $ci <= $maxColIndex; $ci++) {
   for ($ri = 1; $ri <= $maxCell['row']; $ri++) {
     $column = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($ci);
     //background that i need
     $background = $sheet->getStyle($column . ($ri))->getFill()->getEndColor()->getRGB();
   }
}

$background not by conditional formatting.

**Comment by MarkBaker** [comment]
There is no simple approach for doing this. You need to identify if the cell has a conditional style; read the conditional style definition; evaluate the conditions to identify which applies; and then read the style for that matching condition

**Comment by MarkBaker** [comment]
A new Cell method, `getAppliedStyle()` has been provided, which evaluates any CF and attempts to return a single Style object that reflects the styling for that cell. While not perfect, it does give a better reflection of the actual styling that would be displayed in MS Excel for that cell

**Comment by oleibman** [comment]
Closing, resolved by PR #2491 over 2 years ago.
