### ISSUE TITLE
getFormattedValue method return 'GENERAL' value

### ISSUE THREAD

**Issue by mathgr** [PHPOffice/PhpSpreadsheet#2450]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Calling `PhpOffice\PhpSpreadsheet\Cell::getFormattedValue` on a number cell must return the actual number value (but string typed).

### What is the current behavior?

Calling `PhpOffice\PhpSpreadsheet\Cell::getFormattedValue` on a number cell return 'GENERAL' value.

### What are the steps to reproduce?

With this file: [persons.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7726388/persons.xlsx)

and this code:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$sheet = PhpOffice\PhpSpreadsheet\IOFactory::load('persons.xlsx')->getActiveSheet();

$birthYears = [
   'C2' => $sheet->getCell('C2')->getFormattedValue(),
   'C3' => $sheet->getCell('C3')->getFormattedValue(),
   'C4' => $sheet->getCell('C4')->getFormattedValue(),
];
```

with the version 1.17.1, the result is:
```php
[
   'C2' => '1932',
   'C3' => '1964',
   'C4' => '1988',
];
```

but with the version 1.18.0 and older, the result is :
```php
[
   'C2' => 'GENERAL',
   'C3' => 'GENERAL',
   'C4' => 'GENERAL',
];
```

### Which versions of PhpSpreadsheet and PHP are affected?

1.18.0 and older.

Thank you

**Comment by oleibman** [comment]
Thank you for providing the sample file. This seems very similar to issue #2239 which was fixed by PR #2242. The issue was reported, and therefore fixed, only for Xls. Apparently it needs to be dealt with for Xlsx as well. Working on it.
