### ISSUE TITLE
$writer->save() error when has  picture in excel

### ISSUE THREAD

**Issue by albin504** [PHPOffice/PhpSpreadsheet#2461]
This is:

```
- [1 ] a bug report

```

### What is the current behavior?
use ` $writer->save()` ,output a new excel file, when open the file, it show warning:
![image](https://user-images.githubusercontent.com/3232275/147329276-7c7a4398-6d7e-4afd-8221-35a71d30e562.png)

There is a picture in the above excel, when I delete the picture from excel, it is ok.

the source excel and the output excel is:
[error3.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7773164/error3.xlsx)
[new_error3.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7773165/new_error3.xlsx)

my PhpSpreadsheet version is 1.8.2. and when id test in PhpSpreadsheet 1.20, it is ok.
but my php version is 7.0, And cannot use the latest PhpSpreadsheet version.
Is it possible to fix this problem in version 1.8.x。

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// add code that show the issue here...
       $tmpFileDir = '/tmp';
        FileHelper::createDirectory($tmpFileDir);
        $spreadsheet = IOFactory::load($tmpFileDir . '/error3.xlsx');
        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
        $newFile = $tmpFileDir . "/new_error3.xlsx";
        ob_end_clean();
        $writer->save($newFile);
        die();

```

### Which versions of PhpSpreadsheet and PHP are affected?
php 7.0
PhpSpreadsheet 1.8.2

**Comment by albin504** [comment]
#1462
Just like this issue，The issue has been resolved in version 1.13.0.
I would be very grateful if it can be resolved in version 1.8.2

**Comment by oleibman** [comment]
If you must work on a no-longer-supported version of PHP, and there are many reasons why shouldn't, the best that I can suggest is using Composer to download the version you want, and then manually apply the changes you need.

**Comment by albin504** [comment]
ok，thank you !
