### ISSUE TITLE
[BUG] Notice: Undefined offset: 8

### ISSUE THREAD

**Issue by WoutervanderLoopNL** [PHPOffice/PhpSpreadsheet#2463]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Opening the XLS feed generated by bol.com 

### What is the current behavior?
Get an error `Notice: Undefined offset: 8` 
![image](https://user-images.githubusercontent.com/8301044/147354972-9e2ef6ca-8ec1-409b-b2f3-ec4cf7a5445e.png)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

        $finder = new \Symfony\Component\Finder\Finder();
        $files = $finder->files()->in(__DIR__)->name('bol.xls');
        $file = array_keys(iterator_to_array($files->getIterator()))[0];
        
        $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($file);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.20.0
PHP 7.4.27
Symfony 5.4.1

**Comment by WoutervanderLoopNL** [comment]
[bol.xls](https://github.com/PHPOffice/PhpSpreadsheet/files/7774383/bol.xls)

**Comment by WoutervanderLoopNL** [comment]
![image](https://user-images.githubusercontent.com/8301044/147355369-5eb12e1f-b13c-4a7f-b3ff-422d498856d1.png)

![image](https://user-images.githubusercontent.com/8301044/147355394-d795d8a7-618f-4fce-9fb7-8d0dce2b125f.png)


tried it on many ways, also with the flag

**Comment by oleibman** [comment]
Can you upload the spreadsheet that is causing the problem. I would need to see it before I can investigate.

**Comment by WoutervanderLoopNL** [comment]
@oleibman  I already did, in the first comment. bol.xls

**Comment by oleibman** [comment]
My apologies for missing that. I will work on it.
