### ISSUE TITLE
Migration guide - renamed methods

### ISSUE THREAD

**Issue by KacerCZ** [PHPOffice/PhpSpreadsheet#247]
During migration from PHPExcel I found out, that migration guide (https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/docs/topics/migration-from-PHPExcel.md) does not mention renaming of following methods:

- `\PHPExcel_Shared_Date::ExcelToPHPObject()` is now `\PhpOffice\PhpSpreadsheet\Shared::excelToDateTimeObject()` 
-- https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Shared/Date.php#L155
--https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Shared/Date.php#L165
- `\PHPExcel_Shared_Date::ExcelToPHP()` is now `\PhpOffice\PhpSpreadsheet\Shared::excelToTimestamp()` 
-- https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Shared/Date.php#L115
-- https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Shared/Date.php#L214

**Comment by simkimsia** [comment]
Another one missing is \PHPExcel_Shared_Date::FormattedPHPToExcel is now \PhpOffice\PhpSpreadsheet\Shared::PHPToExcel

**Comment by davidespagnoli** [comment]
> Another one missing is \PHPExcel_Shared_Date::FormattedPHPToExcel is now \PhpOffice\PhpSpreadsheet\Shared::PHPToExcel

No, it is not, \PhpOffice\PhpSpreadsheet\Shared\Date::formattedPHPToExcel is still there
