### ISSUE TITLE
Not getting Right color code instead getting FFFFFF

### ISSUE THREAD

**Issue by osama-synapse** [PHPOffice/PhpSpreadsheet#2484]
I have an excel sheet with multiple data and cell have different colors.
I am getting right color code of common colors like red, blue green. But for some colors it is returning #FFFFFF. 

```
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$reader->setReadDataOnly(false);
$spreadsheet = $reader->load("seating.xlsx");
$seating_sheet = $spreadsheet->getSheet(1)->toArray();
$i=1;

foreach ($seating_sheet as $t) {
 	$sr = $t[0]; 
      $section = $t[1];
      $row = $t[2];
    $seat = $t[3];
    $color = $spreadsheet->getSheet(1)->getStyle("D".$i)->getFill()
    ->getStartColor()->getRGB();

    echo "S.no : ".$sr."\t". "Section : ".$section."\t"."Row : ".$row. "\t Seat: ". $seat." \t Color : ".$color. "<br />";

    $i++;
} 
```

**Comment by oleibman** [comment]
Please upload the file that has a problem.

**Comment by JorisJ1** [comment]
This may be related but I am not certain. When reading and then writing [test-background-colors.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7950253/test-background-colors.xlsx) one cell background color turns white while the one in another cell stays the same color.

```
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load('storage/test-background-colors.xlsx');

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, "Xlsx");
$writer->save("storage/output.xlsx");
```

**Comment by oleibman** [comment]
I do not duplicate your result with your sample code and file and PhpSpreadsheet V21.0 - the fill colors in both cells look right. Please let me know what release of Php and PhpSpreadsheet you are using.

**Comment by JorisJ1** [comment]
My apologies. I assumed I was using the latest version because `composer update phpoffice/phpspreadsheet` in my Laravel application changed nothing. I had the issue with PhpSpreadsheet version 1.18.0 and PHP 7.4.9.

Forcing the upgrade through `composer remove phpoffice/phpspreadsheet` and then `composer require phpoffice/phpspreadsheet` installed PhpSpreadsheet 1.21 and fixed the problem.
