### ISSUE TITLE
setValueExplicit sets the Value wrongly? to "0" instead of "null"

### ISSUE THREAD

**Issue by Wolfy7** [PHPOffice/PhpSpreadsheet#2488]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
If you want to set the Value explicit to TYPE_Numeric but the value ($pValue) ist "null" the value should be also set to "null".

### What is the current behavior?
If a Cell looks like that in the xml-file:
`<c r="A1" s="109" t="n" />`
the Value for this cell will be set to "0" instead of "null".

### What are the steps to reproduce?
If you call setValueExplicit with $pValue = null and  $pDataType = DataType::TYPE_NUMERIC the value will be set to "0".

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpeadsheet = 1.18.0 - 2021-05-31
PHP = 7.2.4

### Possible solution
Change the line 217 in \src\PhpSpreadsheet\Cell\Cell.php from:

```php
                $this->value = 0 + $pValue;
```
to 
```php
                if(is_null($pValue)){
                    $this->value = null;
                }else{
                    $this->value = 0 + $pValue;
                }
```
If you want you can assigne this to me and i will provide a PR with this fix.

**Comment by MarkBaker** [comment]
It does raise the question of why you want to specify type `TYPE_NUMERIC` with a value of `NULL` rather than specifying `TYPE_NULL`

**Comment by Wolfy7** [comment]
@MarkBaker justified question.
The think is I have (i think) no choice, I have a xlsx-file with some empty cells and in the XML they are defined as mentioned above:
<c r="A1" s="109" t="n" />
So if I read this file in PHPspreadsheet converts this empty cell to "0" cause if the t="n". Maybe the XLSX (XML) file is not "correct" but that's what I don't know.

And also just for my understanding I think if a cell is empty it should stay empty independent of the type. So probably the function should always return empty if the value is null or?

Thanks for your reply.
