### ISSUE TITLE
Invalid numeric value for datatype Numeric

### ISSUE THREAD

**Issue by krissss** [PHPOffice/PhpSpreadsheet#2493]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
```php
$pValue = "123\n";
echo DefaultValueBinder::dataTypeForValue($pValue);
```

This dataType should be 's'(string).

### What is the current behavior?

This dataType is 'n'(numeric)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValueByColumnAndRow(1, 1, "123\n");
```

### Which versions of PhpSpreadsheet and PHP are affected?

current use php7.4 and PhpSpreadsheet 1.12.0

same as #1439

**Comment by oleibman** [comment]
With a current version of PhpSpreadsheet, I get your expected result with PHP7. However, the behavior you describe returns in PHP8. This is due to a change in PHP8 to the is_numeric function:

"Numeric strings ending with whitespace ("42 ") will now  return true. Previously, false was return instead."

**Comment by krissss** [comment]
Sorry, I tested it with PhpSpreadsheet 1.21.0 and PHP 7.4. This is correct! My mistake!
