### ISSUE TITLE
Problem writing Excel file

### ISSUE THREAD

**Issue by ibnbd** [PHPOffice/PhpSpreadsheet#250]
I have a very wide Excel file which goes to ZN columns. When I open the file I can horizontal scroll and read all these columns without any problem. When I use PhpSpreadsheet to open and save the file again (only for testing) using the bellow codes 
 
```php
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load(fileWriteLoc);


$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->setPreCalculateFormulas(false);
$writer->save(fileWriteLoc);
```
I can't horizontal scroll any more, there is a horizontal scroller and scrolling it changes nothing. I used `Find` to see if all data are there and it was there, even the ZN columns as well but I can't horizontal scroll, it stay on the same screen.

Any help will be amazing

Thank You

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
