### ISSUE TITLE
Invalid cell coordinate 1 during IOFactory::load

### ISSUE THREAD

**Issue by petruchek** [PHPOffice/PhpSpreadsheet#2501]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
$spreadsheet object successfully created

### What is the current behavior?
Error: PhpOffice\PhpSpreadsheet\Exception: Invalid cell coordinate 1

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load("./example.xlsx");
```

### Which versions of PhpSpreadsheet and PHP are affected?
Latest (1.21.0) is still affected, tested on PHP 7.4.

### File to reproduce 
I'm attaching the file - I don't know how it was generated, but I can open it with Excel 2013 without any warnings. When I re-save the file without applying any changes, the problem disappears (but the file is obviously not the same one - even file size differs). It looks like the original file some weird structure that PhpSpreadsheet is unable to handle correctly.
[example.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/7873074/example.xlsx)

**Comment by oleibman** [comment]
Thank you for supplying your example file. It has a merge range stored as `1:1`, i.e. the entire first row is merged as cell A1. PhpSpreadsheet is not expecting this. When you resave the file with Excel, the merge range is now stored as `A1:XFD1`, and PhpSpreadsheet does understand that.

This is a relatively easy oversight to fix. But, in doing so, it appears that the logic for setting up the merge range within PhpSpreadsheet is very costly in terms of memory and speed, a problem which isn't really exposed until you deal with large ranges like that. So, the fix, which I am working on, will be a little more complicated than merely fixing the reported problem.
