### ISSUE TITLE
Vertical alignment does not seem to work

### ISSUE THREAD

**Issue by akinuri** [PHPOffice/PhpSpreadsheet#2508]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question
```

### What is the expected behavior?
Cell should switch to vertical alignment.

### What is the current behavior?
Cell alignment is horizontal.

### What are the steps to reproduce?

```php
<?php

require "vendor/autoload.php";

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$sheet->setCellValue("A1", "Hello");
$sheet->setCellValue("B1", "World");

// $sheet->getStyle("A1:B1")->applyFromArray([
//     "alignment" => [
//         "vertical" => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER,
//     ],
// ]);
$sheet->getStyle("A1")
    ->getAlignment()->setVertical(\PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_TOP);

$fileName = "test-file.xlsx";
$writer = new Xlsx($spreadsheet);
header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
header("Content-Disposition: attachment; filename=\"". urlencode($fileName)."\"");
$writer->save("php://output");
```

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet 1.21.0
PHP 8.0.6 (XAMPP, Windows 10 x64)

---

I've just started using this library. Trying to print a document that contains 500~ rows. I'd like some cells to be vertical.

I managed to make a cell vertical at first, but later I started styling and did some other modifications. Then, I could no longer make a cell vertical.

Thinking that my modifications might have messed something up, I tried to do it in a simple test case, but it still doesn't work. In my original code, I'm merging some cells vertically, and then change the alignment of the merged cell(s). Thought I should mention this just in case.

This is what I'm seeing:

![Annotation 2022-01-18 205018](https://user-images.githubusercontent.com/13146977/149991472-9537a3a7-f926-4241-9f08-2913be0780ea.png)

**Comment by oleibman** [comment]
I think that your vertical styling is being honored; it's just hard to see it in your screenshot. But, here's what I see when I make row 1 higher:
![image](https://user-images.githubusercontent.com/10341515/150052934-301b39cd-0fa7-44db-89d6-10b3bb73aa4d.png)

**Comment by oleibman** [comment]
From your description, you might want your cell to look like one of the following:
![image](https://user-images.githubusercontent.com/10341515/150054576-e889511d-fc6b-44fa-a598-c612f6006ead.png)
The code for each of those would be:
```php
        $sheet->getStyle('A2')->getAlignment()->setTextRotation(90);
        $sheet->getStyle('B2')->getAlignment()->setTextRotation(-90);
        $sheet->getStyle('C2')->getAlignment()->setTextRotation(Alignment::TEXTROTATION_STACK_PHPSPREADSHEET);
```

**Comment by akinuri** [comment]
Using the text rotation helped. Maybe I'm misremembering things, but I thought I made it work before using only alignment. This made things weirder :) (Now that I think about it, I also have an HTML document for preview. I probably mixed the two.)

This is what I'm currently using.

```
$sheet->mergeCells("A1:A8");

$sheet->getStyle("A1")->applyFromArray([
    "alignment" => [
        "vertical" => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_TOP,
        "textRotation" => \PhpOffice\PhpSpreadsheet\Style\Alignment::TEXTROTATION_STACK_PHPSPREADSHEET,
    ],
]);
```

![Annotation 2022-01-19 100340](https://user-images.githubusercontent.com/13146977/150080775-75fac5e0-13fa-46ee-85a9-3841994c5c0b.png)

Since the issue is solved, I'll be closing this.
