### ISSUE TITLE
Got an error after installing composer

### ISSUE THREAD

**Issue by juvyc** [PHPOffice/PhpSpreadsheet#252]
Hello Guys,

Anyone encountered this issue before?

if I type composer --version
Composer version 1.5.2 2017-09-11 16:59:25
If I type "composer require phpoffice/phpspreadsheet" 
I get[InvalidArgumentException]  Could not find package phpoffice/phpspreadsheet at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Here's some requirements that were enabled.

PHP version: 5.6.30
mbstring enable
iconv enable
xml enable
xmlwriter enable
zip enable

Thanks in advance.

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question related to composer rather than PhpSpreadsheet. Please read their documentation. Also in the future if you encounter an actual bug, please fill the issue template instead of writing free text.

Thank you!
