### ISSUE TITLE
Starting From 8th Rows By Default

### ISSUE THREAD

**Issue by UmeshKrRana** [PHPOffice/PhpSpreadsheet#2521]
I am trying to generate a CSV file in Yii2 framework. File is generating but the issue is it doesn't start with 1st row as I defined A1. Instead, it is starting from A9. 
Also, I have put a string "**Hello World**" in A1. But, it is displaying in A9 as "**Hello W**" only. Last 4 characters are not showing as well.
Can anyone help me on this. What I am doing wrong here? 
My source code is -
`
     use PhpOffice\PhpSpreadsheet\Spreadsheet;
     use PhpOffice\PhpSpreadsheet\IOFactory;
     
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();

        $sheet->setCellValue("A1", 'Hello World');
    
        // store file in runtime cache
        $writer = IOFactory::createWriter($spreadsheet, "Csv");
        $writer->save(__DIR__ . '/../../../../../../../runtime/cache/reports/' . $fileName);
        $filePath = __DIR__ . '/../../../../../../../runtime/cache/reports/' . $fileName;
![spreadsheet issue](https://user-images.githubusercontent.com/30307542/150680980-7c059cd6-34cc-42ae-b730-8291a6765c03.PNG)
`

**Comment by oleibman** [comment]
Unable to duplicate either symptom using the supplied code.
![image](https://user-images.githubusercontent.com/10341515/150702702-f075277a-443f-497e-aac3-29ab6a957543.png)
What else can you tell me about your environment (Php release, PhpSpreadsheet version, etc.)?

**Comment by UmeshKrRana** [comment]
Hi thank you for your immediate response.
Let me tell you the scenario. In my local development, I have **PHP 7.4.10** and **"phpoffice/phpspreadsheet": "^1.21"**. In local it is working without any issue.
When, I am deploying the code on AWS EC2 where, I have **PHP 7.3.2** with same spreadsheet version. I am getting the issue there on production.

**Comment by MarkBaker** [comment]
Is there anything generated by the framework that could be writing newline characters to output? This could be as basic as a closing `?>` in script files followed by a newline.

**Comment by UmeshKrRana** [comment]
Finally, it is resolved by adding the **ob_end_clean()**; function before writing the csv.
Thank you very much.
