### ISSUE TITLE
Migration guide - missing info about renamed readers and writers

### ISSUE THREAD

**Issue by KacerCZ** [PHPOffice/PhpSpreadsheet#253]
This is:

- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
During migration from PHPExcel I found out, that readers and writers were renamed (Excel2007 is now Xlsx and so on). This renaming is not mentioned in migration guide.

### Which versions of PhpSpreadsheet and PHP are affected?
Latest version from develop branch

**Comment by PowerKiKi** [comment]
True, the info is missing. The tool should migrate the class names for you automatically. But I assume you got bitten when using `IOFactory` and writers short names. Is that correct ?

**Comment by KacerCZ** [comment]
Exactly - I use `IOFactory::createReader()`, `IOFactory::createWriter()` and `IOFactory::identify()`.
