### ISSUE TITLE
loaded XLSX has wrong behavior of cell->setValue()

### ISSUE THREAD

**Issue by SailorMax** [PHPOffice/PhpSpreadsheet#255]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
As in Excel, with recognition of dates and times: if put "12:21" in the cell, it has to be number - not string.

### What is the current behavior?
without recognition of dates and times: if put "12:21" in the cell, cell type in result = "string"

### What are the steps to reproduce?
load xlsx file and try to modify it.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$excel_worksheet = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($file_type)->load($file_path)->getActiveSheet();
$excel_worksheet->setCellValue("A1", "12:21");
$excel_worksheet->setCellValue("A2", "=TYPE(A1)");
$cell_type = $excel_worksheet->getCell("A2")->getCalculatedValue();
```
$cell_type has to be 1, but now it 2

### Which versions of PhpSpreadsheet and PHP are affected?
latest build

### P.S.
Currently we have to manual setup `\PhpOffice\PhpSpreadsheet\Cell::setValueBinder( new \PhpOffice\PhpSpreadsheet\Cell\AdvancedValueBinder() );` to fix it. I spent few hours to find it :)
But if user open Excel / LibreOffice document, I think, phpSpreadsheet has to work as original program?

**Comment by SailorMax** [comment]
So, any comments about it?

**Comment by PowerKiKi** [comment]
I don't think it should be changed. As it stands now, you can do what you want with code like that:

```php
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValueExplicit("A1", "12:21", \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->setCellValue("A2", "=TYPE(A1)");
$type = $sheet->getCell("A2")->getCalculatedValue();
var_dump($type);
```

So that "special case" is possible, but if we were to change things around, and make the DefaultBinder more clever, then it would become much more tedious to "cancel" that behavior if we don't want it. Said otherwise, it is easier to build upon things for a few specific cases (now), than to "undo the magic" for most cases (if we implemented it).
