### ISSUE TITLE
Removal of the old deprecated function classes from the codebase.

### ISSUE THREAD

**Issue by MarkBaker** [PHPOffice/PhpSpreadsheet#2552]
This is:

```
- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### Why is this required?

Planned removal of deprecated classes and methods in anticipation of PhpSpreadsheet 2.0 release.

Note that this may require some PHPStan baseline cleanup; and there may still be some unit tests that directly call the deprecated methods, which will need to be modified either to call the replacement class/method directly, or rewritten to call the Excel function through the Calculation Engine.

This work can be done against the `2.0-dev` branch once it has been created after the next release.

**Comment by MarkBaker** [comment]
WIP on the `2.0-development` branch

**Comment by oleibman** [comment]
Closing. This was done as part of release 2.0.0.
