### ISSUE TITLE
Parse worksheets on demand

### ISSUE THREAD

**Issue by SailorMax** [PHPOffice/PhpSpreadsheet#258]
This is:

- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
Reader parse only default active Worksheet from import file. Other worksheets store in worksheet as raw data (xml) and parse only on first access to it. 

### What is the current behavior?
Reader parse all worksheets on open file. In result if document has very large lists in not primary worksheets load-process can be very slow and take large amount of memory.

### What are the steps to reproduce?
1. Create document with 2 worksheets. First is empty, but second with 10000 rows of data. Active is first.
2. Try to load this document in PHPSpreadsheet

### Which versions of PhpSpreadsheet and PHP are affected?
latest build.

**Comment by PowerKiKi** [comment]
A workaround to this kind of issue might be [to read only a specific sheet](reading-only-named-worksheets-from-a-file).

Otherwise implementing this kind of behavior would probably be a non-trivial task. Would you be willing to work on that ?

**Comment by SailorMax** [comment]
Currently I don't have time for it. May be later will try.

P.S. you link is broken - 404

**Comment by PowerKiKi** [comment]
The link was http://phpspreadsheet.readthedocs.io/en/develop/topics/reading-files/#reading-only-named-worksheets-from-a-file

**Comment by SailorMax** [comment]
Looks like Lazy init cells ( #276 ) is enough as alternative to this suggestion.
