### ISSUE TITLE
simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found

### ISSUE THREAD

**Issue by GarikBelik** [PHPOffice/PhpSpreadsheet#2603]
Error in line: 126 method loadZip

if i'm load xlsx file
[income - 2022-02-18T151218.155.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8097493/income.-.2022-02-18T151218.155.xlsx)

**Comment by mix5003** [comment]
may duplicate with #2516 it should fixed in [1.22.0](https://github.com/PHPOffice/PhpSpreadsheet/releases/latest) . 
can you update to latest version and try again?

**Comment by oleibman** [comment]
No update in 4 months, and I believe it is fixed. Closing.
