### ISSUE TITLE
Spreadsheet `toArray()` function throws exception if refrence column formula name has `'` in the title.

### ISSUE THREAD

**Issue by talhaamir4130** [PHPOffice/PhpSpreadsheet#2612]
This is:

- [x] a bug report

### What is the expected behavior?
The function should return the array without throwing exception.

### What is the current behavior?
Throws exception `Formula Error: An unexpected error occurred`

### What are the steps to reproduce?
Sheet 1 has a French name "Some d'name"
In sheet 2 in cell A2 we reference the cell from sheet 1 like 'Some d'name'!C5
After this when we do get `toArray()` function for sheet 2. It will throw exception.:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet->getSheet(1)->setTitle('Some d'name');
$spreadsheet->getSheet(2)->toArray();
```

### Which versions of PhpSpreadsheet and PHP are affected?
`^1.21`

**Comment by MarkBaker** [comment]
Ok! A few issues in our sample code.
 - Quotes around the worksheet name
 - Passing sheet ids to `getSheet()` that don't exist

The following code replicates what you appear to be trying to do:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet->getActiveSheet()->setTitle("Some d'name");

var_dump($spreadsheet->getActiveSheet()->getTitle());
var_dump($spreadsheet->getActiveSheet()->toArray());
```
But it works exactly as I would expect it to

**Comment by MarkBaker** [comment]
If you're having problems with a cell reference to another worksheet in an Excel formula; then I need to know the details... what is the formula? etc

**Comment by talhaamir4130** [comment]
@MarkBaker Sorry for not explaining it correctly.

```
public function getDataForAccordion(?Spreadsheet $spreadsheet): array
    {
        if (is_null($spreadsheet)) {
            return [];
        }

        // some code 

        return [
            ....
            'absenceCategory' => $this->accordionService->getAbsenceCategoryInfo($spreadsheet->getSheet(2)), // works
            'rightsOfCategory' => $this->accordionService->getRightsOfCategoryInfo($spreadsheet->getSheet(7)), // exception
            ....
        ];
    }
```

```
// Accordion Service
public function getRightsOfCategoryInfo(Worksheet $worksheet): array
    {
        $rows = $worksheet->toArray(); //exception here
     }
```

- Sheet 2 name `Catégorie d'absence`
- Sheet 7 name `Droit Catégorie d'absence`

Formula in Cell : `=CONCAT('Catégorie d'absence'!A4)` 

The exception thrown: 
![image](https://user-images.githubusercontent.com/18555977/155019120-b0bc66f7-678c-4194-8617-365f0b5d08b5.png)

**Comment by talhaamir4130** [comment]
I can't change the excel file,

I got the solution by changing the title of sheet in code (which is not good).

please let me know if you need more explanation

**Comment by MarkBaker** [comment]
Hmmm! Normally a quote inside a Worksheet name would need to be escaped when it's used in a formula:
```xml
<f>_xlfn.CONCAT('Catégorie d''absence'!A1)</f>
```
![image](https://user-images.githubusercontent.com/770298/155027042-d413c474-2fcb-4b8e-9cb9-e6a69a3ca4aa.png)

But that doesn't seem to work either; so I'll have to do a few more tests to see what's happening inside the calculation engine when it tries to parse that formula.

**Comment by talhaamir4130** [comment]
Exactly. Thanks a lot. 👍

**Comment by MarkBaker** [comment]
Looks like I'm going to be delving into the dark arts of regular expressions again

**Comment by MarkBaker** [comment]
Hopefully the code on the latest master branch should solve this problem
