### ISSUE TITLE
Unchecked return value of ZipArchive::locateName

### ISSUE THREAD

**Issue by anton-harvey** [PHPOffice/PhpSpreadsheet#262]
This is:

- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
The [`Reader\Xlsx::getFromZipArchive`] function should return `false` if the zip entry could not be located.

### What is the current behavior?
If it exists, the contents of the zip entry at index `0` is returned.

### What are the steps to reproduce?
_Provided upon (further) request._ 😅

### Which versions of PhpSpreadsheet and PHP are affected?
All PhpSpreadsheet versions. Tested on PHP 7.0.17.

---

[`ZipArchive::locateName`]
>Returns the index of the entry on success or **`FALSE`** on failure. 

The [`Reader\Xlsx::getFromZipArchive`] function does not check whether the return value of `ZipArchive::locateName` is `false`. When it is, it's passed straight into [`ZipArchive::getFromIndex`], which casts it to an integer, resulting in it retrieving the entry at index `0`.

https://github.com/PHPOffice/PhpSpreadsheet/blob/25ff914aa656dc713134836c703f2a3f7f29838e/src/PhpSpreadsheet/Reader/Xlsx.php#L304-L312

[`ZipArchive::getFromName`] appears to be a good alternative:
>```php
>string ZipArchive::getFromName ( string $name [, int $length = 0 [, int $flags ]] )
>```
>Returns the entry contents using its name. 
>Returns the contents of the entry on success or **`FALSE`** on failure. 

```php
$contents = $archive->getFromName($fileName, 0, ZipArchive::FL_NOCASE);
```

[`ZipArchive::locateName`]: https://secure.php.net/manual/ziparchive.locatename.php
[`ZipArchive::getFromIndex`]: https://secure.php.net/manual/ziparchive.getfromindex.php
[`ZipArchive::getFromName`]: https://secure.php.net/manual/ziparchive.getfromname.php
[`Reader\Xlsx::getFromZipArchive`]: https://github.com/PHPOffice/PhpSpreadsheet/blob/25ff914aa656dc713134836c703f2a3f7f29838e/src/PhpSpreadsheet/Reader/Xlsx.php#L287-L294

**Comment by PowerKiKi** [comment]
That sounds about right. Would you mind providing a PR for that ?

**Comment by anton-harvey** [comment]
I'll make a PR in a few days.
