### ISSUE TITLE
How to connect PhpSpreadsheet with production?

### ISSUE THREAD

**Issue by SailorMax** [PHPOffice/PhpSpreadsheet#263]
Current repository of PhpSpreadsheet is repository for developers.

- It has bin/ with developer tools
- It has docs/ for users-developers
- It has samples/ for user-developers
- It has tests/ with developer tests
- It has phpunit and other developer config files

For production I need only content of src/ plus few psr-libraries (36MB vs 3.6MB).  And I need to has connection with your repository for possibility to update PhpSpreadsheet in any time.

How can I do this?

thank you.

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
