### ISSUE TITLE
indirect function calls error

### ISSUE THREAD

**Issue by rrd108** [PHPOffice/PhpSpreadsheet#2641]
This is:

```
- [ x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

When I use `rangeToArray` or `toArray` with `$calculateFormulas` set to `true` the calculation should be done.

### What is the current behavior?

An error message created:
`Sheet1!A1 -> Formula Error: An unexpected error occurred`

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$worksheet1 = $spreadsheet->createSheet();
$worksheet1->setTitle('Sheet1');
$worksheet1 = $spreadsheet->createSheet();
$worksheet1->setTitle('Sheet2');

$sheet = $spreadsheet->setActiveSheetIndexByName('Sheet2');
$sheet->setCellValue('A1', '108');

$sheet = $spreadsheet->setActiveSheetIndexByName('Sheet1');
$sheet->setCellValue('A1', '=INDIRECT(CONCATENATE(B1;"!";C1))');
$sheet->setCellValue('B1', 'Sheet2');
$sheet->setCellValue('C1', 'A1');
var_dump($sheet->getCell('A1')->getCalculatedValue());
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 8.1.3
PhpSpreadsheet 1.22.0

**Comment by MarkBaker** [comment]
As stated in the documentation:
 > Inside the Excel file, formulas are always stored as they would appear
in an English version of Microsoft Office Excel, and PhpSpreadsheet
handles all formulae internally in this format. This means that the
following rules hold:

-   Decimal separator is `.` (period)
-   Function argument separator is `,` (comma)
-   Matrix row separator is `;` (semicolon)
-   English function names must be used

so try writing your formula as:
```php
$sheet->setCellValue('A1', '=INDIRECT(CONCATENATE(B1,"!",C1))');
```

**Comment by rrd108** [comment]
Ah, I did not know that that English uses commas, there...
Thanks.

**Comment by rrd108** [comment]
I have checked an example file what I use. 

I have a cell with this content: `=INDIRECT(CONCATENATE($R142;"!";D$140))`

It works in Excel, but PhpSpreadsheet gives that error. So I guess I have to change the formula itself.
