### ISSUE TITLE
Problem with cells with currency formatting

### ISSUE THREAD

**Issue by aramhuseiny** [PHPOffice/PhpSpreadsheet#2645]
Hello
I try to format a column as currency. Based on examples in documentation, I used "getNumberFormat" which formats the column as number. Also It does not show currency icon in front of the cell.

How I can do this?

Thanks

**Comment by MarkBaker** [comment]
`getNumberFormat()` returns the current NumberFormat object; how are you then setting it? What value are you using for the format mask?

**Comment by aramhuseiny** [comment]
Here is my code.
`
        $spreadsheet->getActiveSheet()->getStyle('J')->getNumberFormat()->
        setFormatCode(OdisseNumberFormat::FORMAT_CURRENCY_GB_SIMPLE );`

I added my own constant as the parameter to "setFormatCode", and its value  is "'£#,##0.00_-'".

**Comment by MarkBaker** [comment]
I'm not having any problems:

```php
$worksheet = $spreadsheet->getActiveSheet();

$values = [
    12345.67,
    12345678.90,
];
$mask = '£#,##0.00_-';

$worksheet->getStyle('A')->getNumberFormat()
    -> setFormatCode($mask);

foreach ($values as $key => $value) {
    $cellAddress = 'A' . ($key + 1);
    $worksheet->getCell($cellAddress)
        ->setValue($value);
    echo $worksheet->getCell($cellAddress)->getFormattedValue(), PHP_EOL;
}
```

displays
```
£12,345.67
£12,345,678.90
```

**Comment by aramhuseiny** [comment]
The problem in display the values in MS Excel and LibreOffice calc.
I attach a screenshot of the Excel to clarify my problem.
![Capture](https://user-images.githubusercontent.com/12831959/156819609-540f87ee-acca-421c-a443-ca55c08e6f96.PNG)

**Comment by MarkBaker** [comment]
From the fact that the are left justified, I would guess that your cell values are strings rather than numbers; number format masks only work with numbers, not with strings (even if those strings contain numeric values).
