### ISSUE TITLE
Help with Deleting row

### ISSUE THREAD

**Issue by ibnbd** [PHPOffice/PhpSpreadsheet#267]
My column "D" has Epoch time (eg. 1509442086). I want to fetch data from column and check if this date is too old. If yes, I want to delete this row (eg. A2,B2,C2,D2). The whole row will be deleted. I am using something like this :

```
$rows = $worksheet->getHighestDataRow();
for ($i = 2; $i <= $rows; $i++) {
 $index = $i;
 $time = $worksheet->getCell("D" . $index)->getValue();
 if ($time < ANOTHER_EPOCH) {
   //DELETE THE ROW HERE
 }
}
``` 

Please let me know if there any other way to achieve my goal or how can I delete the row.

Thank You

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
