### ISSUE TITLE
how to get color row when import excel

### ISSUE THREAD

**Issue by franky-tampubolon** [PHPOffice/PhpSpreadsheet#2670]
i want to import excel and get color row...  i cannot read in documentation, only to set fill color row.

thank you

**Comment by MarkBaker** [comment]
You mean something like
```
$spreadsheet->getActiveSheet()->getStyle(1) // get style for Row 1
->getFill()->getStartColor()->getARGB()
```
or
```
$spreadsheet->getActiveSheet()->getStyle(1) // get style for Row 1
->getFill()->getEndColor()->getARGB()
```

**Comment by franky-tampubolon** [comment]
$spreadsheet = new Spreadsheet($file);
        $color = $spreadsheet->getActiveSheet()->getStyle(3) // get style for Row 3
                    ->getFill()->getEndColor()->getARGB();
        dd($color);
the result is FF000000

when i use getStartColor, the result is FFFFFFFF

But in my excel file the color of row 3 is yellow...
![image](https://user-images.githubusercontent.com/67570602/158020289-5c077913-54fd-49ea-9f9c-f2059be1945b.png)

**Comment by MarkBaker** [comment]
Then it's quite probable that the colour isn't set for that individual row, but for multiple rows, or it could be set for individual cells in that row.

If that's the case, then the best option is to check the first cell in each row:
```
for($row = 1; $row <= 10; ++$row) {
    echo "Row number {$row}", PHP_EOL;
    $startColour = $spreadsheet->getActiveSheet()
        ->getStyle("A{$row}")->getFill()->getStartColor()->getARGB());
    echo "Start Colour: {$startColour}", PHP_EOL;
    $endColour = $spreadsheet->getActiveSheet()
        ->getStyle("A{$row}")->getFill()->getEndColor()->getARGB());
    echo "End Colour: {$endColour}", PHP_EOL;
}
```

**Comment by franky-tampubolon** [comment]
this is my code :
![image](https://user-images.githubusercontent.com/67570602/158040705-8a05b673-e0fb-40fc-bb29-fb6629f28c3a.png)

this is the result :

![image](https://user-images.githubusercontent.com/67570602/158040649-c7bb4d24-2b03-4566-86ee-393115344995.png)

source excel :

![image](https://user-images.githubusercontent.com/67570602/158040679-eabe38c1-9a97-4ca9-9e86-4bee1c8cf543.png)

why the result same for every row?

**Comment by MarkBaker** [comment]
I haven't a clue!!! Without seeing the file itself, I can only guess. Are you looking at the correct worksheet? Is it possible that the file is using conditional formatting?

**Comment by franky-tampubolon** [comment]
The coloring cell without condition formatting.... just coloring the cell by user....

**Comment by MarkBaker** [comment]
Then are you loading the file using `readDataOnly`?

**Comment by MrMacvos** [comment]
I have the same problem. In a rare case, a fill color is returned, but in 99% not, see screenshots:

![Screenshot 2022-04-22 at 10 56 03](https://user-images.githubusercontent.com/1470464/164673335-f6cfa37b-5cdc-48a4-9030-3692adc808e4.png)

![Screenshot 2022-04-22 at 10 56 36](https://user-images.githubusercontent.com/1470464/164673459-0c1dc2b3-7eeb-4341-a9f0-6be7d78b0cf5.png)

In the second screenshot, I return the value, startColor, endColor and fillType.

```
$styleObject1 = $worksheet->getCellByColumnAndRow($ix, $wsrow)->getStyle()->getFill()->getStartColor()->getARGB();
$styleObject2 = $worksheet->getCellByColumnAndRow($ix, $wsrow)->getStyle()->getFill()->getEndColor()->getARGB();
$styleObject3 = $worksheet->getCellByColumnAndRow($ix, $wsrow)->getStyle()->getFill()->getFillType();
```

**Comment by MarkBaker** [comment]
Without seeing an actual Excel file that demonstrates this problem, I simply cannot give an answer. I don't know how the colour has been set in your file: there's many ways of setting a colour, including the automagic of colour themes for tables or autofilter ranges where the colour isn't directly linked to the row in the file, but only in the UI

**Comment by MrMacvos** [comment]
@MarkBaker Ok, here it is.

[phpspreadsheet-reading-fill-color-problem.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8540865/phpspreadsheet-reading-fill-color-problem.xlsx)

I hope you can find it...

\- -
Thanks,
Marc

**Comment by MarkBaker** [comment]
Thanks. I can't guarantee to provide an actual solution; but at least an inspection of the styles defined in the file and how they're applied should at least give me enough information to work out why.

I have introduced a new method (`getAppliedStyle()`) that looks at some of the ways styles defined in different ways are combined together (primarily for the sake of conditional styles that override the basic cell styling), so I may be able to extend that.

**Comment by MrMacvos** [comment]
@MarkBaker How do I use getAppliedStyle() ?

I tried :
```
$a = $worksheet->getCellByColumnAndRow($col, $row)->getAppliedStyle()->exportArray();
```
and
```
$a = $worksheet->getAppliedStyle()->exportArray();
```
but in both cases I get `Call to undefined method`

I use a phpspreadsheet version without composer, from here: https://github.com/YoloZoloo/PhpSpreadSheet/tree/master

\- -
Thanks,
Marc

**Comment by MarkBaker** [comment]
You're running a 7-month old version, about 4 releases behind, and the new method that I mentioned hasn't ever been included in a release yet.


And that repository is in breach of the license conditions of PhpSpreadsheet at that: the only condition of the MIT License is that any distribution should include the license.
 > The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by MrMacvos** [comment]
@MarkBaker Darn, I fell for it ... sorry. I hoped that guy would keep it up-to-date. I now installed v1.22.0.0 via [php-download.com](https://php-download.com) and now I get the colors!

**Comment by MarkBaker** [comment]
@MrMacvos You also now have a complete version of PhpSpreadsheet; the YoloZoloo repo was missing a lot more files than just the license
