### ISSUE TITLE
output file is incorrect when running on server

### ISSUE THREAD

**Issue by RamenChan** [PHPOffice/PhpSpreadsheet#2672]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet and PHP are affected?

output file is incorrect when running on server
![image](https://user-images.githubusercontent.com/32162964/158024081-6128b00f-c3ca-4ac6-9eb0-15e6c96fbb37.png)

**Comment by MarkBaker** [comment]
It looks like something in your code is adding a blank line before you send the file to the browser.
