### ISSUE TITLE
Compatibility with list validation on Excel

### ISSUE THREAD

**Issue by marcomoscardini** [PHPOffice/PhpSpreadsheet#2688]
This is:

```
- [?] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Data validation on listType fails on Excel but works on LibreOffice/OpenOffice

### What is the current behavior?
Excel complains about file format and "repair" file, removing all validation and conditional formats.

### What are the steps to reproduce?
Open the file [2b7727c9-a54c-11ec-b2d3-0242c0a80003(service)(1).xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8282550/2b7727c9-a54c-11ec-b2d3-0242c0a80003.service.1.xlsx)

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...

                $validation = $sheet->getCell($cellId)->getDataValidation();
                $validation->setType(DataValidation::TYPE_LIST);
                $validation->setErrorStyle(DataValidation::STYLE_INFORMATION);
                $validation->setAllowBlank(false);
                $validation->setShowInputMessage(true);
                $validation->setShowErrorMessage(true);
                $validation->setShowDropDown(true);
                $validation->setErrorTitle('Input error');
                $validation->setError('Value is not in list.');
                $validation->setPromptTitle('Pick from list');
                $validation->setPrompt('Please pick a value from the drop-down list.');
                $validation->setFormula1('"'.implode(',', $enums).'"');
                $validation->setSqref($cellRange);

                $conditionalStyles = [];
                $wizardFactory = new Wizard($cellRange);

                /** @var Wizard\Expression $expressionWizard */
                $expressionWizard = $wizardFactory->newRule(Wizard::EXPRESSION);

                $allowedValues = [];
                foreach ($enums as $validValue) {
                    $allowedValues[] = sprintf('A1="%s"', $validValue);
                }
                $expression = 'NOT(OR('.implode(',', $allowedValues).'))';
                $expressionWizard->expression($expression)->setStyle($redStyle);
                $conditionalStyles[] = $expressionWizard->getConditional();
                $sheet->getStyle($cellRange)->setConditionalStyles($conditionalStyles);

```

### Which versions of PhpSpreadsheet and PHP are affected?
1.22 and PHP8.0

**Comment by oleibman** [comment]
You appear to be using the function `REGEX` as  part of your data validation. As discussed in issue #2658, Excel does not support that function.

**Comment by oleibman** [comment]
Thanks, that is a different problem, and it is again Excel's problem. There appears to be a length limit for a formula used in Data Validation of 255 characters, and one of yours exceeds that length by a lot. I have not yet found an "official" source for this rule, but there's plenty of anecdotal evidence that it exists, e.g. https://www.excelforum.com/excel-formulas-and-functions/1085435-how-to-increase-characters-limits-from-255-in-data-validation-formulas.html or https://www.contextures.com/xldataval08.html.
