### ISSUE TITLE
Excel file can not be parsed, exception is thrown

### ISSUE THREAD

**Issue by 1G07** [PHPOffice/PhpSpreadsheet#27]
Hi all,
I am using your library for loading Amazon flat files. When I try to load, for example, this flat file https://s3.amazonaws.com/seller-templates/ff/eu/de/Flat.File.Jewelry.de.xls I get the exception. I think that`s the bug in the code. I get undefined offset. Maybe you can take a look at it.
Thanks!

**Comment by Quix0r** [comment]
Can you provide the error message itself? Just writing about it is not enough. And PHPSpreadsheet breaks many things (as it is unstable code). If you need a reliable lib, use PHPExel (I ran into same mistake, good that the developers updated README.md).

**Comment by PowerKiKi** [comment]
Closing because of lack of feedback
