### ISSUE TITLE
psr/simple-cache:3.0.0

### ISSUE THREAD

**Issue by rakibhoossain** [PHPOffice/PhpSpreadsheet#2703]
Do you have any plan to upgrade psr/simple-cache version to 3.0.0?

```
phpoffice/phpspreadsheet 1.21.0 requires psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1]
```

**Comment by MarkBaker** [comment]
Simple answer, no! Not for the moment. See the discussion [here](https://github.com/PHPOffice/PhpSpreadsheet/issues/2468)

**Comment by rakibhoossain** [comment]
> psr/simple-cache

Thank you for your response.
