### ISSUE TITLE
Set color text in a cell 

### ISSUE THREAD

**Issue by thaomd-2569** [PHPOffice/PhpSpreadsheet#2708]
This is:
I want to set color a special text. Example : color 1 /n color 2
```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
![image](https://user-images.githubusercontent.com/86293405/159238476-36041aa1-a0e1-4ad6-a183-ae3f52115d31.png)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by thaomd-2569** [comment]
Please help me

**Comment by MarkBaker** [comment]
Read about "rich text" in [the documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#add-rich-text-to-a-cell)

**Comment by thaomd-2569** [comment]
@MarkBaker 
Thank you so much, it worked for me
