### ISSUE TITLE
Not able to set Cell value as Date format

### ISSUE THREAD

**Issue by pbabugn** [PHPOffice/PhpSpreadsheet#2709]
This is:

```
- [ ] a bug report

```
I am setting the cell value to date format as below
    $sheet->getStyle('A1')->getNumberFormat()->setFormatCode("mm/dd/yy");

### What is the expected behavior?

The format of the cell type is DATE 

### What is the current behavior?
the format of the cell type is custom , Due to this the when I am applying the conditional format function (TODAY()-1) is not working

### What are the steps to reproduce?
$sheet->getStyle('A1')->getNumberFormat()->setFormatCode("mm/dd/yy");

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
$sheet->getStyle('A1')->getNumberFormat()->setFormatCode("mm/dd/yy");

**Comment by pbabugn** [comment]
The value of the cell is "03/19/2022"

**Comment by MarkBaker** [comment]
Then you have a string value; not a number... how is that cell value being set?

**Comment by pbabugn** [comment]
Here $valuearray array has group of values and then after am setting the format
$rowcnt =  6;
$cellvalue =  \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex(1) . $rowcnt;
$sheet->fromArray($valuearray, NULL, $cellvalue);

**Comment by MarkBaker** [comment]
Then your array contains a string.... either convert it to an Excel serialized timestamp value before calling `fromArray()`.

Or there are cell value binders that will attempt do any conversion that's necessary; the AdvancedValueBinder contains code that looks at strings to see if they contain a value that looks like a date (or a time) and converts it to an Excel serialized timestamp, setting a default format code of 'yyyy-mm-dd'

**Comment by pbabugn** [comment]
I also tried below .

use PhpOffice\PhpSpreadsheet\Cell\Cell;
\PhpOffice\PhpSpreadsheet\Cell\Cell::setValueBinder( new \PhpOffice\PhpSpreadsheet\Cell\AdvancedValueBinder() );
and then set the value and format, Still no luck.

Can you please let me know how to convert "03/19/2022" string to Excel serialized timestamp value ?

**Comment by MarkBaker** [comment]
There is a whole section in the [documentation about handling dates](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#write-a-date-or-time-into-a-cell) that should help.

When I run the following code,
```php
$value = '03/19/2022';

\PhpOffice\PhpSpreadsheet\Cell\Cell::setValueBinder( new \PhpOffice\PhpSpreadsheet\Cell\AdvancedValueBinder() );

$spreadsheet->getActiveSheet()
    ->setCellValue('A1', $value);
var_dump($worksheet->getCell('A1')->getValue());

$spreadsheet->getActiveSheet()->getStyle('A1')
    ->getNumberFormat()
    ->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_DATE_YYYYMMDDSLASH);

var_dump($worksheet->getCell('A1')->getFormattedValue());
```
I get the results:
```
float(44639)
string(10) "2022/03/19"
```

The alternative approach:
```php
$value = '03/19/2022';
$dateValue = \PhpOffice\PhpSpreadsheet\Shared\Date::PHPToExcel($value);

var_dump($dateValue);

$worksheet->setCellValue('A1', $dateValue);
$worksheet->getStyle('A1')
    ->getNumberFormat()
    ->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_DATE_YYYYMMDDSLASH);

var_dump($worksheet->getCell('A1')->getFormattedValue());
```
gives
```
float(44639)
string(10) "2022/03/19"
```

There may occasionally be mistakes (is '03/12/2022' the 3rd of December or is it 12th of March?) but both approaches work.

**Comment by pbabugn** [comment]
<img width="375" alt="date" src="https://user-images.githubusercontent.com/47426091/159296922-60e15397-d4d8-4d35-9954-ed07f16f21ab.PNG">

By doing above we are getting date with locale Afrikanas. I need to set that locale to English united states as below. Can we do that one ?
<img width="370" alt="date1" src="https://user-images.githubusercontent.com/47426091/159297343-8651e2af-08cf-41ac-b741-3ab0247924b4.PNG">

**Comment by MarkBaker** [comment]
Then set the format mask to whatever you want it to be; the underlying value has been converted to an Excel serialized timestamp that you can now format however you choose

**Comment by pbabugn** [comment]
You mean by doing below ?

$validLocale = \PhpOffice\PhpSpreadsheet\Settings::setLocale('en_us');
 if (!$validLocale) { echo 'Unable to set locale en_us<br />\n'; }
Still showing in the Afrikanas.

**Comment by MarkBaker** [comment]
No! That will have absolutely no effect whatsoever on the formatting: `setLocale()` affects a very few elements, the language of the calculation engine, some imports from CSV, that's about it! I never mentioned setting the locale.

You format the date using a number format mask:
```
$worksheet->getStyle('A1')
    ->getNumberFormat()
    ->setFormatCode('dddd "day" dd "in the month of" mmmm "in the year AD" yyyy');```


Is it a major issue that it's showing Afrikaans as the date locale in MS Excel GUI? Has it changed the actual value in the cell? Is the date correct? What does the actual formatted value look like, and what should it look like?

**Comment by pbabugn** [comment]
The date is correct
![image](https://user-images.githubusercontent.com/47426091/159406151-e481d4bf-b950-414d-a86d-ff949e0c7013.png)
but the date locale should be english united states , then only the other users can use the excel which is generated with phpspreadsheet effectively.

Not using any specific settings in the excel

**Comment by MarkBaker** [comment]
Well I'm sorry, but date locale is not maintained in the file, but is an aspect of the MS Excel GUI, so there is no way that PhpSpreadsheet can control it; and your end users may all have completely different locale settings to each other.

**Comment by pbabugn** [comment]
Basically I have a template with cell as Date with locale as English united states as showed in the above screenshot. but when I write data to that cell the datatype shoudn't change.

Steps to reproduce:
1. Take a excel and format cell with date like below and save the template
2. Now read that template excel using the phpspreadseet and write a date to cell and save it to another excel.
3. Now the generated excel will not have the cell data type as original.

**Comment by MarkBaker** [comment]
No! And I'm not going to waste any more hours of my time with a "perceived" issue that is part of the MS Excel GUI, and nothing whatsoever to do with PhpSpreadsheet.

Unless you're using the Advanced Value Binder, then if you write a serialized date value (i.e. an integer or a floating point number) to a cell that already exists in your loaded template with number datatype and a format mask to display it as a date, then the datatype will not change unless you change it yourself; nor will the format mask change unless you change it in your code.


If you don't like it, I suggest you find yourself an alternative library

**Comment by fedorUsual** [comment]
> This is:
> 
> ```
> - [ ] a bug report
> ```
> 
> I am setting the cell value to date format as below $sheet->getStyle('A1')->getNumberFormat()->setFormatCode("mm/dd/yy");
> 
> ### What is the expected behavior?
> The format of the cell type is DATE
> 
> ### What is the current behavior?
> the format of the cell type is custom , Due to this the when I am applying the conditional format function (TODAY()-1) is not working
> 
> ### What are the steps to reproduce?
> $sheet->getStyle('A1')->getNumberFormat()->setFormatCode("mm/dd/yy");
> 
> Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:
> 
> ```
> <?php
> 
> require __DIR__ . '/vendor/autoload.php';
> 
> // Create new Spreadsheet object
> $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
> 
> // add code that show the issue here...
> ```
> 
> $sheet->getStyle('A1')->getNumberFormat()->setFormatCode("mm/dd/yy");
> 
> ### Which versions of PhpSpreadsheet and PHP are affected?

May be you already has answer, but somebody, who looked here for answer for same will look decision))
It need to make from Your date unix timestamp, after make it like excel date timestamp:
```
$time = strtotime('03/12/2022');
$dateExcel = \PhpOffice\PhpSpreadsheet\Shared\Date::PHPToExcel($time);
$cell = $worksheet->getCell('B2');
$cell->getStyle()->getNumberFormat()->setFormatCode('dd/mm/yyyy');
```
