### ISSUE TITLE
how to check excel format in PHPOffice/PhpSpreadsheet

### ISSUE THREAD

**Issue by mayaloremine** [PHPOffice/PhpSpreadsheet#2712]
I am using PHPOffice/PhpSpreadsheet 1.0 extension in yii2.It returns

 PHP Fatal Error – yii\base\ErrorException
The allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

when using the excel format 2007-2019. Is it possible to check the excel format in PHP PHPOffice/PhpSpreadsheet 1.0?

or anyone can suggest any other solutions for this?

**Comment by MarkBaker** [comment]
The `IOFactory::identify()` method will tell you which reader would be used to load the specified file

**Comment by mayaloremine** [comment]
Thank you for the reply.

Sorry . Could you please explain in a little more detail?
Here I have already used a function like this

private static function getReaderTypeFromExtension($filename)
	{
		$pathinfo = pathinfo($filename);
		if (!isset($pathinfo['extension'])) {
			return null;
		}
		
		switch (strtolower($pathinfo['extension'])) {
			case 'xlsx': // Excel (OfficeOpenXML) Spreadsheet
			case 'xlsm': // Excel (OfficeOpenXML) Macro Spreadsheet (macros will be discarded)
			case 'xltx': // Excel (OfficeOpenXML) Template
			case 'xltm': // Excel (OfficeOpenXML) Macro Template (macros will be discarded)
				return 'Xlsx';
			case 'xls': // Excel (BIFF) Spreadsheet
			case 'xlt': // Excel (BIFF) Template
				return 'Xls';
			case 'ods': // Open/Libre Offic Calc
			case 'ots': // Open/Libre Offic Calc Template
				return 'Ods';
			case 'slk':
				return 'Slk';
			case 'xml': // Excel 2003 SpreadSheetML
				return 'Xml';
			case 'gnumeric':
				return 'Gnumeric';
			case 'htm':
			case 'html':
				return 'Html';
			case 'csv':
				// Do nothing
				// We must not try to use CSV reader since it loads
				// all files including Excel files etc.
				return null;
			default:
				return null;
		}
	}

This will Create Reader for files using automatic Reader resolution.

**Comment by MarkBaker** [comment]
Yes, `identify()` will create Readers for each possible filetype, then try to read the beginning of the file. If it can read the file, then it knows it's the correct Reader for that file. If it can't read it, then the next type of Reader will try to read it, and so on.
Whichever Reader succeeds in reading from the file tells what type of file it is; so if the Ods Reader is able to read the file then it's an Open/Libre Office format file.

**Comment by MarkBaker** [comment]
Your `getReaderTypeFromExtension()` method relies on the correct extension to identify the filetype, which isn't always the case: a lot of different filetypes masquerade as Excel with an `.xls` extension, but aren't actually BIFF-format Excel files

**Comment by mayaloremine** [comment]
Thank you for you support.Let me try and get back to you

**Comment by mayaloremine** [comment]
Thank you. Yes, I have already tried. But doesn't work

**Comment by MarkBaker** [comment]
Doesn't work? In what way?
You asked if it was possible to check the Excel format: `identify()` identifies the file format, so that it knows what Reader should be used, that's as close as you're going to get. What were you expecting?

**Comment by mayaloremine** [comment]
> The`getReaderTypeFromExtension()` method that you've shown relies on the correct extension to identify the filetype, which isn't always the case: a lot of different filetypes masquerade as Excel with an `.xls` extension, but aren't actually BIFF-format Excel files

Yes, I tried the identity() function and it reurns the correct result.
But when I debugged the code, I realize that the issue returns from the below code
$sheetData = $spreadsheet->getActiveSheet()->toArray(null,true,true,true);
this functions returns  error 
"PHP Fatal Error – yii\base\ErrorException
The allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)"
for excel format 2007-2019, but no issues with 2007-2013 excel format.

$sheetData = $spreadsheet->getActiveSheet();
This function returns the same result for both formats. But after being added toArray() it does not work for the 2007-2019 format.

I tried the fromArray() function. But it didn't work for me. 
here is my code 

$sheetData = $spreadsheet->getActiveSheet(); 
$sheetData = $sheetData->fromArray($sheetData,NULL,A1);
Not sure how to use the third parameter here
How can I solve this Issue?Please help

**Comment by MarkBaker** [comment]
This has absolutely nothing whatsoever to do with the format of the file being loaded: files with the same number of cells, styles, etc take up as much memory in PhpSpreadsheet regardless of the file they're loaded from.

There are a lot of ways that you can reduce the memory usage, described in the documentation; but methods like `toArray()` wiil always take a lot f memory because you're asking to create a 2-d array of spreadsheet data from PhpSpreadsheet, and that array requires a lot of memory (as does any large array in PHP).

What do you want to do with that array? There may be alternatives that mean you don't need to copy the entire worksheet into an array (for example, using a Row Iterator)

You also seem to be confusing the use of `fromArray()` and `toArray()`.

**Comment by mayaloremine** [comment]
Thank you. Yes you are correct, I am a little bit confused about these methods

Actually what I want to do is after reading the excel, it will display in the grid, and when the user presses the confirm button the data will save into DB. Users can remove something from here or can update something from this grid before saving it into DB. That is my requirement 
 Kindly guide me on how can I do this?
After getting data from getActivesheet() function, what can I do to place this data into a form or grid?

**Comment by mayaloremine** [comment]
Thank you so much for your valuable support. The issue was solved. It was the array conversion problem.Also replaced my "getReaderTypeFromExtension()" function with IOFactory::identify() method.Thanks once again
