### ISSUE TITLE
Missing cell style after copying range

### ISSUE THREAD

**Issue by JonWallsten** [PHPOffice/PhpSpreadsheet#272]
This is: 
- [?] a bug report
- [?] a feature request

### What is the expected behavior?
When copying multiple cells with rangeToArray and then adding another instance of these cells with fromArray I expect both data and styles to be added.

### What is the current behavior?
When copying multiple cells with rangeToArray and then adding another instance of these cells with fromArray I get all the data but not the styles. 

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here
$cellValues = $spreadsheet->getActiveSheet()->rangeToArray('A1:A2');
$spreadsheet->getActiveSheet()->fromArray($cellValues, null, 'B1');
```

### Which versions of PhpSpreadsheet and PHP are affected?
Lastest

Notes:
Is this intended behavior? Could it be solved differently?
Are the styles lost in the copying phase or the pasting phase?

**Comment by PowerKiKi** [comment]
`rangeToArray()` return cell values and nothing related to styles. This a mis-usage of API.

**Comment by JonWallsten** [comment]
Was actually looking for a proper support forum. Glad to hear you're sing Gitter. Maybe add that to the readme? Was actually looking for a support forum before I wrote the ticket.

**Comment by keithbox** [comment]
agree, the copy rows and copy range is necessary for generating excel report, merge the data to the excel template.
I use this self-made function, fortunately, the solution below used the function exists in both of PHPExcel and PHPSpreadsheet
https://stackoverflow.com/questions/34590622/copy-style-and-data-in-phpexcel

**Comment by JonWallsten** [comment]
@keithbox: I actually made that one! 😅Didn't find a simpler way unfortunately.
