### ISSUE TITLE
Add support for Structured References

### ISSUE THREAD

**Issue by MarkBaker** [PHPOffice/PhpSpreadsheet#2725]
This is:

```
- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

Add support for Structured References in formulae: [Using structured references with Excel tables](https://support.microsoft.com/en-us/office/using-structured-references-with-excel-tables-f5ed2452-2337-4f71-bed3-c8ae6d2b276e)

With a PR in the pipeline to provide basic support for Excel Tables and Pivot Tables, the Calculation Engine will need modification to support the structured references used in Table formulae.

**Comment by billynoah** [comment]
Yes please.  These are becoming more and more common.

**Comment by oleibman** [comment]
Closing, fixed over a year ago.
