### ISSUE TITLE
Scrutinizer is Broken

### ISSUE THREAD

**Issue by oleibman** [PHPOffice/PhpSpreadsheet#2732]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Scrutinizer should run correctly for each pull request/commit.

### What is the current behavior?
In the step "Compiling PHP runtime 8.1.1", the following error occurs:
```
configure: error: Package requirements (openssl >= 1.0.2) were not met:

Requested 'openssl >= 1.0.2' but version of OpenSSL is 1.0.1f
```
As a result, Scrutinizer terminates with "Test Setup Failed", and does not perform any analysis of the code. While we can still merge code despite such a failure, it would be better to have the Scrutinizer results available. I do not see any way to report this problem to the Scrutinizer folks.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

This has affected PRs #2728 (so April 4 is the approximate starting date for this problem), #2731, #2718, and #2723, and will presumably affect all future activity until the problem is resolved..

### Which versions of PhpSpreadsheet and PHP are affected?
Scrutinizer is attempting to set up PHP 8.1.1. The version of PhpSpreadsheet is irrelevant.

**Comment by MarkBaker** [comment]
I think it might by approaching time to drop Scrutinizer from the CI pipeline; though I do like the reports that show how code quality, test coverage, etc change from week to week (especially when the trend is positive). Since we added phpstan, it's probably less relevant than it used to be.

**Comment by odan** [comment]
I've had the same issue. You may try to use another build-image:

```yaml
build:
  image: default-bionic
```

**Comment by oleibman** [comment]
Thanks - that's an interesting idea. Based on PR #2759, it does seem to work, although it took over 9 minutes for Scrutinizer to compile PHP. I can't find any documentation on the `image` parameter. Can you tell me what it does?

**Comment by odan** [comment]
I found this workaround on this blob: https://prinsfrank.nl/2022/02/04/Configuring-PHP8.1-on-scrutinizer

The scrutinizer documentation for the `image` parameter is here: https://scrutinizer-ci.com/docs/guides/upgrading-trusty-image

**Comment by oleibman** [comment]
After one successful Scrutinizer run, two subsequent runs failed, without any indication of why. Reverted my PR to draft status, and will continue to try from time to time.

**Comment by oleibman** [comment]
Scrutinizer appears to be fixed this morning (2022-09-12). Two successful runs, although one still shows "pending" on the PR even though test is complete.

**Comment by oleibman** [comment]
Issue appears resolved. Closing ticket.
