### ISSUE TITLE
PHP 8.1.3: Deprecated: Return type of MyCLabs\Enum\Enum::jsonSerialize()

### ISSUE THREAD

**Issue by reruesch** [PHPOffice/PhpSpreadsheet#2733]
This is **deprecation warning** report:

Deprecated: Return type of MyCLabs\Enum\Enum::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in **vendor\myclabs\php-enum\src\Enum.php on line 246**

PhpSpreadsheet v1.22.0
PHP v8.1.3

**Comment by MarkBaker** [comment]
Thanks for the warning: but it's very difficult to prevent deprecation notices in dependencies without updating that library itself. And please note that a deprecation is a notice, not a warning.

**Comment by reruesch** [comment]
Thanks for your answer, you're of course absolutely right about the warning/notice, my fault.
So I suppose there's no new version of this library yet.

**Comment by oleibman** [comment]
This came up when we started adding 8.1 to our tests, and this class did add the needed annotation. Is it possible that you do not have a current version of MyCLabs\Enum\Enum? I believe we are using version 1.8.3 of that library. In a new directory, when I require PhpSpreadsheet, the declaration for jsonSerialize is at line 314, not line 246, and includes the following code, including the annotation which your error message suggests is absent:
```php
    /**
     * Specify data which should be serialized to JSON. This method returns data that can be serialized by json_encode()
     * natively.
     *
     * @return mixed
     * @link http://php.net/manual/en/jsonserializable.jsonserialize.php
     * @psalm-pure
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return $this->getValue();
    }
```

**Comment by MarkBaker** [comment]
The `composer.lock` file should tell you exactly what version of the library is being pulled in

**Comment by reruesch** [comment]
Thank you all for your help/remarks. I finally have to conclude that it was an error while updating my installation, parts of the dependencies weren't updated.
