### ISSUE TITLE
broken xls writer: lost EMF embed image

### ISSUE THREAD

**Issue by SailorMax** [PHPOffice/PhpSpreadsheet#274]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
Readable XLS file with embed image.

### What is the current behavior?
If open in Excel, XLS file with broken image.
If try to read it by PhpSpreadsheet, we've got:
```
Uncaught Error: Call to a member function getBlipType() on null in lib\PHPOffice\PHPSpreadsheet\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xls.php:1137
```
`$BSECollection` is empty array.

### What are the steps to reproduce?
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$fileType = 'Xlsx';
$fileName = __DIR__.'/imgBook1.xlsx';

// Read the file
$objReader = PhpOffice\PhpSpreadsheet\IOFactory::createReader("Xlsx");
$objPHPExcel = $objReader->load($fileName);

$output_type = "Xls";
$output_file_name = __DIR__.'/output';
$objWriter = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($objPHPExcel, $output_type);
$objWriter->save($output_file_name);

$outputReader = PhpOffice\PhpSpreadsheet\IOFactory::createReader($output_type);
$outputPHPExcel = $outputReader->load($output_file_name);
```
[imgBook1.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1470089/imgBook1.xlsx)
Sample Xlsx with 1 embed EMF picture.

### Which versions of PhpSpreadsheet and PHP are affected?
sources from 13.11.2017
PHP 7.2.0rc6

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code without relying on an external Excel file.

**Comment by SailorMax** [comment]
@PowerKiKi 
"lost EMF embed image"
Create new document in any editor, put in it EMF file and convert it to xls via PHPSpreadsheet.
How I can write example without external file? EMF file from where to get?
I did easier - prepared sample xlsx.

**Comment by SailorMax** [comment]
will recheck later

**Comment by SailorMax** [comment]
Looks like not critical for everyone. Can be forgotten.
May be I will try to fix it later by myself.

**Comment by oleibman** [comment]
Php offers no native support for EMF (or WMF) images. Xlsx can support such images via mime type `application/octet-stream`. No such support is available for Xls. Ods appears able to handle WMF but not EMF. Most browsers support neither. So, your choices are to convert the image to a more portable format, or stick to Xlsx.

Changing status to closed not planned (wontfix). Removing stale label.
