### ISSUE TITLE
Installation error on PHPOffice PHPSpreadSheet with Composer

### ISSUE THREAD

**Issue by wieb18** [PHPOffice/PhpSpreadsheet#2743]
Hi,

I am using Windows 10 with Laragon 5.0 WAMP (PHP 7.4.19 & Apache 2.4.47).

Trying install PHPOffice/PHPSpreadSheet with Composer using this command:

> **composer require phpoffice/phpspreadsheet**

Nothing wrong with Composer installation, but when trying run this PHP code:

```
<?php
$spreadsheet = \PhpSpreadsheet\IOFactory::load('template.xlsx');

$worksheet = $spreadsheet->getActiveSheet();

$worksheet->getCell('A1')->setValue('John');
$worksheet->getCell('A2')->setValue('Smith');

$writer = \PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xls');
$writer->save('write.xls');
?>

```

it gets error:

> **Fatal error: Uncaught Error: Class 'PhpSpreadsheet\IOFactory' not found in C:\laragon\www\excel.php:2 Stack trace: #0**

Please help, thanks

[https://stackoverflow.com/questions/71835456/installation-error-on-phpoffice-phpspreadsheet-with-composer](url)

**Comment by oleibman** [comment]
Three problems. No require statement, and incorrect class name for load (and writer). Try:
```php
require __DIR__ .  '/vendor/autoload.php'; /* will vary depending upon your environment */
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('template.xlsx');

$worksheet = $spreadsheet->getActiveSheet();

$worksheet->getCell('A1')->setValue('John');
$worksheet->getCell('A2')->setValue('Smith');

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xls');
$writer->save('write.xls');
```

**Comment by oleibman** [comment]
```php
require "C:/Users/user/vendor/autoload.php";
```

**Comment by wieb18** [comment]
Finally it works, thanks for your kindness
