### ISSUE TITLE
Write to PDF issue

### ISSUE THREAD

**Issue by wieb18** [PHPOffice/PhpSpreadsheet#2747]
Hello,

Thanks to PHPSpreadsheet so I am able edit Excel file from PHP and the result is like bellow:

![2022-04-13_19-05-40](https://user-images.githubusercontent.com/45317320/163168916-eb59b953-e68d-4d2d-a1af-a3593caec498.jpg)

Then write it to PDF using this code:

```
$class = \PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf::class;
\PhpOffice\PhpSpreadsheet\IOFactory::registerWriter('Pdf', $class);
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Pdf');
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf($spreadsheet);
$writer->save('test.pdf');
```

But unfortunately the PDF file is not as good as original Excel file.

![2022-04-13_19-06-18](https://user-images.githubusercontent.com/45317320/163169005-0942af43-b349-4ae2-acf3-385526cd4e77.jpg)

I know this issue is about PDF Writer and not PHPSpreadsheet, but maybe you know the solution.

Please help, thanks

**Comment by MarkBaker** [comment]
Note that all of the PDF Writers work by using the HTML Writer to generate standard HTML markup before passing that to the actual PDF generator library that you are using.

The "Risk Warning" could probably be improved by merging the cells in that bottom row rather than assuming that it will overlap.

The "colour" notifications could probably be resolved by finding a similar colour value that is recognised by the PDF Writer; the red and blue colours are clearly identified correctly, so I'm sure that there will be a similar green value that can be set. Alternatively, other PDF libraries like DomPdf might work better than MPdf.

You probably need to call `setImagesRoot()` to define a URL path for the images in the heading before calling `save()`.

I'm more concerned about those percentage values, which seem to be out by a factor of 100.

**Comment by MarkBaker** [comment]
`setImagesRoot()` is a method in the Writer, not a function; so
```php
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf($spreadsheet);
$writer->setImagesRoot($_SERVER['DOCUMENT_ROOT'] . '/img/');
$writer->save('test.pdf');
```

**Comment by MarkBaker** [comment]
> But the good thing, now there is an icons on header (see the arrow) which indicate header images not found.

It should work if the path is correct: try using the HTML Writer instead (setting the image root in the same way) and see what the markup look like. Make sure that the image url is valid.

> Also I am just noticed, why the values on each cell different than the Excel file?

That's what I was talking about when I said `I'm more concerned about those percentage values, which seem to be out by a factor of 100.` That's something that I'll need to investigate.

**Comment by wieb18** [comment]
Maybe it helps, I tried using all the PDFs writer (MPdf, DomPdf, and TCPdf) which produce the same result. 

All PDFs writer produce different values than Excel.

Image bellow when tried using DomPDF

![2022-04-14_04-20-01](https://user-images.githubusercontent.com/45317320/163269587-ceb64711-ce5b-4ccf-a36b-a5091a585693.jpg)

Hope you will find the solution for this issue

**Comment by MarkBaker** [comment]
> All PDFs writer produce different values than Excel.

All the PDF Writers build the PDF from the same HTML that's generated by the HTML Writer, so the values that they display will all be the same. The only aspect that will change is how they render the styling.

That's why I said that I need to investigate it.

**Comment by MarkBaker** [comment]
I've tried to recreate, setting a value of `0.125` and formatting it as a percentage.:
```php
$cell->setValue(0.125);
$cell->getStyle()
    ->getNumberFormat()
    ->setFormatCode('0.00%');
```
Then writing the worksheet to file in all formats

This is the Xlsx
![image](https://user-images.githubusercontent.com/770298/163330738-3889e7a0-d986-462e-bf6c-11d00cb14c2b.png)
And this is the HTML
![image](https://user-images.githubusercontent.com/770298/163330849-114acf17-0132-44d8-a264-cbec63f7f9c8.png)
So it works exactly as expected

I can't replicate that discrepancy you're getting

**Comment by wieb18** [comment]
I am using bellow code to fill the Excel cell with values:

`$worksheet->getCell('C10')->setValue(0.125);`

My code doesn't set number format because Excel template file already has it - Excel Custom Number Format  `[Color10]#.##0,00 %_ ;[Red]-#.##0,00 % `

Maybe because Excel Custom Number Format then the PDF Writers produce different values on each cell. 

But never mind if you not able replicate the issue, I will stick with Excel file.

To convert Excel to PDF (or even PNG/JPG), I found something more simple. 

Now I am using [File Converter](https://github.com/Tichau/FileConverter) which less headache than using PDF Writers and the PDF/PNG/JPG output as good as the original Excel.

```
<?php
echo exec('"C:\Program Files\File Converter\FileConverter.exe" --conversion-preset "To Png" "C:\laragon\www\report\test.xlsx"');
sleep(10);
?>
```

Thanks a lot [MarkBaker](https://github.com/MarkBaker) for all the guidance and all the help
