### ISSUE TITLE
allow to set maximum column width for autowidth (enhancement)

### ISSUE THREAD

**Issue by SimonHeimberg** [PHPOffice/PhpSpreadsheet#275]
This is: a feature request

### What is the expected behavior?
Please allow to set a maximum value for automatic column width (and maybe row height).

### What is the current behavior?
Reason: Currently the limited to the maximum supported value of 255. A width of 255 is more than 2 screens wide, which is very unhandy.

### How to implement:
I suggest this value to be set as setting (or maybe for each Worksheet instead).

While calculating the width value, the result is checked. If the width is too big, the width is replaced by the configured width (and if required disable autosize).

### How to reproduce:
```php
$spshObj = PhpOffice\PhpSpreadsheet\Spreadsheet;
$spshObj->setColumValue('A2', str_repeat('abcd '*200));
$spshObj->getColumnDimension('A')->setAutoSize(true);
// generate the file now
```

### My work-around:
```php
// after data is filled into 
$maxWidth = 50;
foreach ($spshObj->getAllSheets() as $sheet) {
    $sheet->calculateColumnWidths();
    foreach ($sheet->getColumnDimensions() as $colDim) {
        if (!$colDim->getAutoSize()) {
            continue;
        }
        $colWidth = $colDim->getWidth();
        if ($colWidth > $maxWidth) {
            $colDim->setAutoSize(false);
            $colDim->setWidth($maxWidth);
        }
    }
}
// now serve/save the $spshObj

**Comment by PowerKiKi** [comment]
Current behavior matches what is done by Excel and LibreOffice as far as I can tell. It is unlikely that this new feature will be implemented in the foreseeable future. Unless somebody contribute a patch that include unit testing.
