### ISSUE TITLE
PHPSpreadsheet setAutoSize function not working as expected

### ISSUE THREAD

**Issue by matthewknill** [PHPOffice/PhpSpreadsheet#2750]
This is: PHPSpreadsheet setAutoSize function not working as expected

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When using the auto resize in Excel, it looks like this:
![image](https://user-images.githubusercontent.com/50228686/163519891-50c73dd5-1a10-438c-9a9c-bdc6b0946761.png)

### What is the current behavior?
However, by using `setAutoSize`, this is the output:
![image](https://user-images.githubusercontent.com/50228686/163519979-810736f0-6e70-4261-80a4-c34767c46ce8.png)

The greater the cell, the greater the gap...

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$productsSheet= $spreadsheet->getActiveSheet();

// ... add product data and headings

foreach (range('A', 'K') as $col) {
    $productsSheet->getColumnDimension($col)->setAutoSize(true);
}
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.21

**Comment by MarkBaker** [comment]
PhpSpreadsheet has two methods (or modes) for `setAutoSize`.

The first of these is an approximation, based simply on the number of characters in the cells (allowing for text wrapping and rotation), and a simple multiplier based on the font (Calibri, Arial or Verdana) and font size.
The second method is much more accurate (but also a lot slower when saving the file) and requires the gd library, and also requires any fonts used to be installed on the server and accessible by gd.

Neither approach is perfect; but we consider it better than seeing lots of cells filled with '#####' in the generated spreadsheet when cell content overspills the cell size.

The alternative is that you estimate for yourself, and set column width to an actual value.

The code used for these calculations can be found in the `calculateColumnWidth()` method of the `Shared\Font` class. If you can come up with a better algorithm, then feel free to submit a PR and we'll take a look at your suggestion.

**Comment by matthewknill** [comment]
Thanks for that, at this stage we are just estimating the size ourselves.

**Comment by don-odyssey** [comment]
I find that the setAutoSize() method works for the cell contents but there is a bug in that it stretches' images, even if the image properties are set not to change with the cell.
