### ISSUE TITLE
how to set custom config to mpdf when using mpdf writer

### ISSUE THREAD

**Issue by jmluang** [PHPOffice/PhpSpreadsheet#2766]
It seems the Mpdf config  is fixed to the code, if I want to pass a custom config how should I pass?

https://github.com/PHPOffice/PhpSpreadsheet/blob/f48044cb94c202d7c4ba9baad479fc25f4f2e5c6/src/PhpSpreadsheet/Writer/Pdf/Mpdf.php#L40

**Comment by MarkBaker** [comment]
There is no option to do this within the library; but we are open for PRs

**Comment by oleibman** [comment]
Solution suggested in issue #3015. Closing this issue.
