### ISSUE TITLE
getFormattedValue does not honor brackets in time formats

### ISSUE THREAD

**Issue by iclukas** [PHPOffice/PhpSpreadsheet#2768]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
A table cell formatted with e.g. "[hh]:mm" and a value higher than 1 should display more the correct hours.
A value of 1.15 should yield a formatted value of "27:36".

### What is the current behavior?
The formatted value is "[03]:36".

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$sheet = $spreadsheet->getActiveSheet();
$sheet->getStyle('A1')->getNumberFormat()->setFormatCode('[hh]:mm');
$sheet->setCellValue('A1', 1.15);
echo $sheet->getCell('A1')->getFormattedValue();
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.22.0, PHP 7.4

**Comment by oleibman** [comment]
For now, you can get the result you want with format code `'[h]:mm'`. I agree that `'[hh]:mm'` should also work as you described, and there is also probably work that needs to be done to support similarly-bracketed minutes and seconds.

**Comment by MarkBaker** [comment]
Will also need to check `[d]` and `[dd]` as well
