### ISSUE TITLE
It is not possible to read the URL of a hyperlink in an XLS(X) file

### ISSUE THREAD

**Issue by chx** [PHPOffice/PhpSpreadsheet#2769]
This is:

```
- [ ] a bug report
- [X] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

`->getHyperLink()` works on spreadsheets exported from LibreOffice and such.

### What is the current behavior?

It doesn't.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

well, that can't be done, the problem is with external Excel files :/

### Which versions of PhpSpreadsheet and PHP are affected?

all

**Comment by oleibman** [comment]
The test suite does test this successfully (tests/PhpSpreadsheetTests/Reader/Ods/OdsTest.php, function testReadHyperlinks). Can you share the spreadsheet and code which is failing for you?

**Comment by chx** [comment]
[2769.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8546244/2769.xlsx)
[2769.xls](https://github.com/PHPOffice/PhpSpreadsheet/files/8546245/2769.xls)

It's the same sheet, I just wanted to make sure it's not the file format.

<?php

use PhpOffice\PhpSpreadsheet\Reader\Xlsx as Reader;
use PhpOffice\PhpSpreadsheet\Spreadsheet;

function loadSheet($path): Spreadsheet {
  $reader = new Reader();
  $reader->setReadDataOnly(TRUE);
  $sheet = $reader->load($path);
  return $sheet;
}

require './vendor/autoload.php';
$path = './2769.xlsx';
$sheet = loadSheet($path);
$cell = $sheet->getActiveSheet()->getCell('A2');
$link = $cell->getHyperlink();
var_dump($link);
var_dump($link->getUrl());

**Comment by chx** [comment]
I can confirm the ODS version works!

It's something with Excel. I will re-title.

**Comment by oleibman** [comment]
It is `$reader->setReadDataOnly(TRUE);` which is causing your result. If you comment out that statement, the URL is retrieved correctly. This is true for both Xls and Xlsx.

**Comment by chx** [comment]
I should've recorded which tutorial I copied this from originally :/ but that was years ago and now I have no clue. i always just copied that function from one script to the next :) Thanks.
