### ISSUE TITLE
when use the \t split the string , the last cloumn miss

### ISSUE THREAD

**Issue by lwx2615** [PHPOffice/PhpSpreadsheet#277]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
use \t split the string ,the column is full

### What is the current behavior?
when I used the  \t to split the string,then the libreoffice open it lose the last column.use in windows ,the column is full.

### What are the steps to reproduce?
get an array from the csv file,then split with the string with \t and then write it into a xlsx file,and meantimes change the column to DataType::TYPE_STRING.when I use \s split ,the xlsx is right,but when  I use \t  ,the last column missing though, I open it in windows it appears the full columns!if this a bug? Or something I did wrong!
   my system is Linux Mint 18.PHP version is 7.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$line = file('20171110.xls');
$ssheet = new Spreadsheet();
$columns = range('A', 'Z');
foreach ($line as $key => $value) {
    $cells = mb_split("\\t+", $tmp);
    foreach ($cells as $keys => $values) {
        $coo = $columns[$keys] . ($key + 1);
        $ssheet->getActiveSheet()->setCellValueExplicit($coo, $values, DataType::TYPE_STRING);
    }
    $wter = new Xlsx($ssheet);
    $wter->save('20171110.xlsx');
}
```

### Which versions of PhpSpreadsheet and PHP are affected?

the current version.

**Comment by PowerKiKi** [comment]
The code provided cannot be run. Please provide an example which can be run and does not depend on an external file.

**Comment by lwx2615** [comment]
get it!
