### ISSUE TITLE
Merging a single cell now throws exception

### ISSUE THREAD

**Issue by mmarton** [PHPOffice/PhpSpreadsheet#2776]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Merging a single cell does nothing.
I don't know if this is a legal use-case, but it was an undocumented breaking change for me. (I don't do this on purpose, I have a dynamic layout and sometime it happend.)
I already fixed with some `if` statements, just wanted you to know about this.

### What is the current behavior?
Merging a single cell throws an exception. "Merge must be set on a range of cells.;

### What are the steps to reproduce?
` $sheet->mergeCells('A1:A1');`

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$spreadsheet->getActiveSheet()->mergeCells('A1:A1');
```

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
latest (1.23.0)

**Comment by MarkBaker** [comment]
Hmmm! I don't see any change in behaviour between `1.22.0` and `1.23.0`

```php
$worksheet->mergeCells('A1:A1');
```
works in both versions (although it probably shouldn't)

```php
$worksheet->mergeCells('A1');
```
throws an exception in both versions

**Comment by mmarton** [comment]
Oh, i oversimplified my exampleI simplified a bit.

my original code on 1.22.0 was:
```php
$sheet->mergeCellsByColumnAndRow(72, 1, 72, 1);
```

the new one (as ByColumnAndRow was deprecated) on 1.23.0:
```
$sheet->mergeCells([72, 1, 72, 1]);
```
the array gets resolved to 'BT1' at vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php:1759 and throws exception at 1785

**Comment by MarkBaker** [comment]
Ah! That makes things clearer. An unintended breaking change. My apologies.

As you've already fixed it (you could also have used try/catch and done nothing on the catch), I'm inclined to leave it "as is" and see if anybody else raises it. The code should prevent creating a single cell merge range anyway, as it does when a string address was passed in before; it's just that the now-deprecated "byColumnAndRow" method previously allowed the creation of a single cell range.

**Comment by morungos** [comment]
To confirm, this exact issue broke my code too. This will cause old code to break. It might be sloppy old code, but it is not all that obscure. I have a feeling this will hit a good few people down the line.

**Comment by MarkBaker** [comment]
@morungos So what would be your suggested approach? Do you think that the restriction should be relaxed to allow something that shouldn't have been permitted in the first place? Or perhaps that it should simply ignore a merge request for a single cell reference? Or are there options that I haven't thought about?
