### ISSUE TITLE
Version 1.23.0 of PhpSpreadsheet breaks PHP 7.3+ support

### ISSUE THREAD

**Issue by granadeeu** [PHPOffice/PhpSpreadsheet#2779]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
PhpSpreadsheet to work under PHP Version 7.3+, as described here:
https://github.com/PHPOffice/PhpSpreadsheet/blob/master/composer.json

### What is the current behavior?
because of the following commit, PhpSpreadsheet doesn't work in PHP 7.3+ anymore:
https://github.com/PHPOffice/PhpSpreadsheet/commit/3a4da89bfe1450c69adfa2d35fcd724c4c11aa95
Reason is that simple-cache requires PHP in version 8:
https://github.com/php-fig/simple-cache/releases/tag/2.0.0

### What are the steps to reproduce?
-

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
-

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: 1.23.0
PHP: 7.4.7

**Comment by MarkBaker** [comment]
simple-cache 2.0 requires PHP>=8; simple-cache 1.0 requires PHP>=5.3.0

PhpSpreadsheet should work with either simple-cache 1.0 or with simple-cache 2.0, as determined by composer and your PHP version
```
"psr/simple-cache": "^1.0 || ^2.0"
```
So for PHP versions 7.3 and 7.4 it should use simple-cache 1.0; for PHP 8.0 or 8.1 it should use simple-cache 2.0 (dependent on any other dependencies that have a requirement for simple-cache)

I've just done vanilla installs of PhpSpreadsheet with PHP 7.3, 7.4, 8.0 and 8.1: composer pulls in simple-cache 1.0 for PHP 7.3 and 7.4 as expected; and simple-cache 2.0 for PHP 8.0 and 8.1 as expected.

So what am I missing here?
