### ISSUE TITLE
Class 'PhpOffice\\PhpSpreadsheet\\Cell' not found

### ISSUE THREAD

**Issue by r0073rr0r** [PHPOffice/PhpSpreadsheet#278]
This is:

- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
To read a Cell

### What is the current behavior?

PHP Fatal error:  Uncaught Error: Class 'PhpOffice\\PhpSpreadsheet\\Cell' not found in /var/www/html/upload-xls.php:96\nStack trace:\n#0 {main}\n  thrown in /var/www/html/upload-xls.php on line 96

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';


if ($_FILES["xls"]["size"] > 0) {
                    $header = "";
                    $inputFileName = $target_file;
                    $objPHPExcel = \PhpOffice\PhpSpreadsheet\IOFactory::load($inputFileName);
                    foreach ($objPHPExcel->getWorksheetIterator() as $worksheet) {
                        $worksheetTitle = $worksheet->getTitle();
                        $highestRow = $worksheet->getHighestRow(); // e.g. 10
                        $highestColumn = $worksheet->getHighestColumn(); // e.g 'F'
                        $highestColumnIndex = PhpOffice\PhpSpreadsheet\Cell::columnIndexFromString($highestColumn);
                        $nrColumns = ord($highestColumn) - 65;
                    }
//Some other code
}
```

### Which versions of PhpSpreadsheet and PHP are affected?
New beta version, old version works fine!

**Comment by PowerKiKi** [comment]
See https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/CHANGELOG.md#breaking-change

**Comment by r0073rr0r** [comment]
phpoffice is first framework where numbers starts from 1 👎

**Comment by PowerKiKi** [comment]
It is unconventional indeed. But this has been the case for rows, and some usage of columns, from the very beginning of PHPExcel more than 7 years ago. And it is well documented.
