### ISSUE TITLE
Incorrect cell returned from Worksheet::getCellByColumnAndRow

### ISSUE THREAD

**Issue by dmoylan** [PHPOffice/PhpSpreadsheet#2789]
This is:

```
-  a bug report
```

### What is the expected behavior?
Getting a cell with column index = 0 should return column A

### What is the current behavior?
Returned cell is in column Z

### What are the steps to reproduce?
See provided code

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
// add code that show the issue here...
$spreadsheet->setActiveSheetIndex(0);
$worksheet = $spreadsheet->getActiveSheet();
$cell = $worksheet->getCellByColumnAndRow(0, 0);
echo 'CELL COL: ' . $cell->getColumn() . ' CELL ROW: ' . $cell->getRow() . "\n";



```

### What features do you think are causing the issue

- [ ] Reader
- [X ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
1.22.0

**Comment by oleibman** [comment]
Column indexes are based on 1. This is a change from PHPExcel, and is in the official documentation at https://phpspreadsheet.readthedocs.io/en/latest/topics/migration-from-PHPExcel#column-index-based-on-1
