### ISSUE TITLE
Excel date variable wrongly converted to date in $activeSheet->rangeToArray('A' . $row . ':' . $highestColumn . $row, NULL, TRUE, FALSE);

### ISSUE THREAD

**Issue by schultz-it-solutions** [PHPOffice/PhpSpreadsheet#280]
This is:
- [X] a bug report (found in PHPExcel, not sure if this is still an issue in PhpSpreadsheet)
I am reading an excel document with PHPExcel, one column contains the "date of birth" of real people.

When using the "rangeToArray" function, the Excel date-number is correctly transferred to the array, IF the date of birth is more recent than "1927/may/17" . If the date of birth is this date or earlier, I am getting a completely wrong number.

List of dates as example:

Date               correct Excel datenumber   result from "rangeToArray"
19.05.1927     10001                               10001
18.05.1927     10000                               10000 
17.05.1927       9999                               2958434 
16.05.1927       9998                               2958069 
15.05.1927       9997                               2957704
14.05.1927       9996                               2957339
13.05.1927       9995                               2956973

Interesting feature of this behaviour:
Difference in the first wrong number is :   2948435
then the differences are 365 or 366 numbers for each day down the timeline...

I am sure this has to do with the fact that the wrongly interpreted datenumbers are only 4-digit...
For my usecase, I am implenting a hardcoded fix, but you might want to check this in PhpSpreadsheet to find a more general solution (if this still exists in PhpSpreadsheet)

Kind regards
Ruediger Schultz

**Comment by PowerKiKi** [comment]
Thank you for reporting the issue. However please make sure to test against latest PhpSpreadsheet before reporting. Date handling where significantly changed between PHPExcel and PhpSpreadsheet.
