### ISSUE TITLE
Html Reader change all zeros to empty string

### ISSUE THREAD

**Issue by adrienprioul** [PHPOffice/PhpSpreadsheet#2810]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Html Reader should read document without altering it (or at least make it configurable)

### What is the current behavior?
Html Reader will replace all '0' by empty cell

### What are the steps to reproduce?
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = IOFactory::createReader('Html');
$spreadsheet = $reader->loadFromString('<html><body><table><tr><td>10</td><td>0</td></tr></table></body></html>');
$sheet = $spreadsheet->getActiveSheet();
echo 'A1 (expected 10): ', $sheet->getCell('A1')->getValue(), PHP_EOL; // A1 (expected 10): 10
echo 'A2 (expected 0): ', $sheet->getCell('A2')->getValue(), PHP_EOL; // A2 (expected 0): 
```

It's caused by [this PR](https://github.com/PHPOffice/PhpSpreadsheet/pull/2649) imho. '0' being a falsy value code like `$child->nodeValue ?: ''` make it an empty string.

However I don't quite understand why this change was necessary so I cannot propose a solution right now.

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
1.23

**Comment by oleibman** [comment]
Your analysis is correct - operator should have been `??` rather than `?:`. Working on change, need to add some test cases.

**Comment by adrienprioul** [comment]
Thank you for your answer and the PR, will be watching for this to be released.
