### ISSUE TITLE
result of a formula is printed over the previous one in Excel 2007

### ISSUE THREAD

**Issue by felix-the-real-cat** [PHPOffice/PhpSpreadsheet#283]
This is:

- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
The cell content should firstly be cleared and then the new result 'inserted' in the cell. 

### What is the current behavior?
In excel 2007 it looks like all the results of the formula are are stacked ! The content is not erased before the new result is printed. 

### What are the steps to reproduce?
create a file with phpspreadsheet, save it, load it and save it again into a new file.

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

details here : 
https://stackoverflow.com/questions/47630995/phpexcel-1-8-result-of-a-formula-is-printed-over-the-previous-one-in-excel-200

### Which versions of PhpSpreadsheet and PHP are affected?
PHPExcel 1.8.1 (last release) & PHPSpreadsheet-devel (as of 2017-12-04)
PHP v 7.1.7

**Comment by PowerKiKi** [comment]
Canot reproduce. With the following code:

```php
$fileName_init = "test_init.xlsx";
$fileName_reloaded = "test_reloaded.xlsx";

// initial file creation
$objPHPExcel = new Spreadsheet();
$objPHPExcel->getActiveSheet()->setCellValue('B3', 'test 3')
    ->setCellValue('D3', 'val 1')
    ->setCellValue('D4', 'val 2')
    ->setCellValue('D6', 'total')
    ->setCellValue('E3', 1)
    ->setCellValue('E4', 2)
    ->setCellValue('E6', '=SUM(E3:E4)');

// save initial file
$objWriter = IOFactory::createWriter($objPHPExcel, 'Xlsx');
$objWriter->save($fileName_init); // works and displays fine

// reload saved file
$inputFileType = IOFactory::identify($fileName_init);
$objPHPExcel_2 = IOFactory::load($fileName_init, $inputFileType);

// save again
$objWriter_2 = IOFactory::createWriter($objPHPExcel_2, 'Xlsx');
$objWriter_2->save($fileName_reloaded); // this file won't display the result of the sum correctly !
```
I can correctly open both files with Excel 2016 (and LibreOffice 5.1):
![image](https://user-images.githubusercontent.com/72603/33589560-79bf24b4-d9bc-11e7-92b6-6e1f7471a838.png)

**Comment by felix-the-real-cat** [comment]
OK you can open the file but you didn't try to change the values in cell E3 or E4... The problem comes when you do !
