### ISSUE TITLE
Invalid cell coordinate BA1 

### ISSUE THREAD

**Issue by Damsjov** [PHPOffice/PhpSpreadsheet#2831]
I apologize if this is a trivial question, but I am trying to write a lot of columns to a spreadsheet and everything is going well until I get to cell BA1. I get the above error message. Is this a build in limitation? To my eye BA1 seems to be a totally valid coordinate.

Thanks, Claus

**Comment by oleibman** [comment]
No problem with the following code for me:
```php
require __DIR__ . '/PhpSpreadsheet' . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->getCell('BA1')->setValue(1);
$writer = new Xlsx($spreadsheet);
$writer->save('issue.2831.xlsx');
```
I will need to see your code and/or spreadsheet to investigate further.

**Comment by MarkBaker** [comment]
`BA1` should not create any issues, the only limitations on rows/columns are those of memory constraints, and those applied by the file formats themselves
e.g.
Xlsx supports up to 16384 (XFD) columns, and this is used as the upper limit within PhpSpreadsheet
Xls is limited to 256 columns (IV), and the Xls Writer will silently discard any columns beyond that point

**Comment by Damsjov** [comment]
Thanks both - I made it work - it seems to have been an invalid character.
