### ISSUE TITLE
if I put a title it does not print the graph

### ISSUE THREAD

**Issue by ivangy** [PHPOffice/PhpSpreadsheet#2838]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
print the chart

### What is the current behavior?
if I put ($this->setActiveSheetIndex($this->nSHEET)->setTitle("prueba");) does not print the chart

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [x] Charts
- [ ] AutoFilter
- [ ] Form Elements

php 7.4.29
"psr/simple-cache": "1.0.1",
"phpoffice/phpspreadsheet": "^1.23"

**Comment by MarkBaker** [comment]
Unable to replicate: please provide some more details of exactly what you are doing, or even example code to demonstrate the problem

**Comment by oleibman** [comment]
Closing. Unable to replicate, and no update in a year and a half.
