### ISSUE TITLE
Deprecated situation on

### ISSUE THREAD

**Issue by sebastian-czarnecki** [PHPOffice/PhpSpreadsheet#2862]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
No warning

### What is the current behavior?
Message in PHP 8.1.6: PHP Deprecated:  substr(): Passing null to parameter #1 ($string) of type string is deprecated in (...)\PHPSpreadsheet\PHPSpreadsheet\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\Worksheet.php on line 1224

### What are the steps to reproduce?
(long procedure in source code, difficult to find exactly code)

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Not registered for now. Probably will be in the future.

### Which versions of PhpSpreadsheet and PHP are affected?
newest for now.

**Comment by oleibman** [comment]
Closing. No update in 2.5 years. Several similar deprecations fixed since this issue, and, with no sample supplied, no reason to think this isn't fixed now.
