### ISSUE TITLE
Incorrect formula parsing

### ISSUE THREAD

**Issue by Zhonkey** [PHPOffice/PhpSpreadsheet#2874]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
Formulas for check:
='Sheet1'!$A3 + MIN('Sheet1'!A:A)

### What is the expected behavior?
'Sheet1'!$A3 + MIN('Sheet1'!A:A) - should be parsed as 'Some page'!$A3 plus  MIN('Sheet1'!A:A)

### What is the current behavior?
'Sheet1'!$A3 + MIN('Sheet1'!A:A) - parsed as cell with address A:A on sheet "'Some page'!$A3 + MIN('Sheet1'"

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
        $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
        $sheet1 = new Worksheet($spreadsheet, 'sheet1');
        $spreadsheet->addSheet($sheet1, 1);
        $sheet1->setCellValue('A1', 1);
        $sheet1->setCellValue('A2', 1);

        $sheet2 = new Worksheet($spreadsheet, 'sheet2');
        $spreadsheet->addSheet($sheet2, 2);
        $sheet2->setCellValue('A1', '=MIN(\'sheet1\'!A:A) + \'sheet1\'!A1');
//        If you change two terms, it parsed correctly
//        $sheet2->setCellValue('A1', '=\'sheet1\'!A1 + MIN(\'sheet1\'!A:A)');

        var_dump($sheet2->getCell('A1')->getCalculatedValue());
```

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [* ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?

Main problem is in regexp patterns from PhpOffice\PhpSpreadsheet\Calculation\Calculation.
As i understand, need to replace all '.*?' to '([^']|'')*?'

**Comment by MarkBaker** [comment]
I can recreate the problem; but simply replacing `'.?'` with `'([^']|'')?` in the regexps will create a lot of additional problems; support for row/column ranges is relatively new in the calculation engine. I can see how the problem occurs, but finding a valid regexp to cover it without breaking other cases will take a while (and probably the sacrifice of several goats under a full moon)

**Comment by Zhonkey** [comment]
Yes, my bad. Correct replace is `'(?:[^']|'')*?'`.
