### ISSUE TITLE
Consider updating to psr/simple-cache 3.0

### ISSUE THREAD

**Issue by looksystems** [PHPOffice/PhpSpreadsheet#2876]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Add support for  "psr/simple-cache": "^3.0"

### What is the current behavior?

Only supports "psr/simple-cache": "^1.0 || ^2.0"

### Which versions of PhpSpreadsheet and PHP are affected?

PHP v8.0+

**Comment by MarkBaker** [comment]
It's has been considered [here](https://github.com/PHPOffice/PhpSpreadsheet/issues/2468), and as noted in the discussions related to that issue:

> Because of the use of mixed type in simple-cache 3.0, we can't match our implementation to the simple-cache 3.0 interface until we support only PHP8 and above. The only way we could work it would be to have two version-specific implementations, and a run-time identifier that chose which one to use.

At this point I'm reluctant at this point to add extra complexity (with multiple implementations of the Cell Cache) in PhpSpreadsheet as a "workround".

and also [here](https://github.com/PHPOffice/PhpSpreadsheet/issues/2790)

**Comment by looksystems** [comment]
Understood and makes sense, thank you.

Sorry I missed those tickets - I did a search but didn't look in closed issues.

**Comment by neopheus** [comment]
"psr/simple-cache": "^1.0 || ^2.0" in "psr/simple-cache": "^1.0 || ^2.0 || ^3.0"

please

**Comment by MarkBaker** [comment]
> "psr/simple-cache": "^1.0 || ^2.0" in "psr/simple-cache": "^1.0 || ^2.0 || ^3.0"
> 
> please

[Please read](https://github.com/PHPOffice/PhpSpreadsheet/issues/2790) and try to understand why the answer is "No"
