### ISSUE TITLE
DataSeries::TYPE_DOUGHTNUTCHART_3D missing

### ISSUE THREAD

**Issue by ReneLuecking** [PHPOffice/PhpSpreadsheet#288]
The constant for 3D doughnut charts is missing in the class PhpOffice\PhpSpreadsheet\Chart\DataSeries:

`const TYPE_DOUGHTNUTCHART_3D = 'doughnut3DChart';`

**Comment by PowerKiKi** [comment]
I am afraid it's not only the constant missing, but support to read and write 3D doughnut. If this feature is important to you, please consider contributing a PR to add it.

**Comment by ReneLuecking** [comment]
I just saw that Excel itself does not support 3D doughnut charts. Therefore, this feature can not be developed.
