### ISSUE TITLE
Fetching (simple) table ranges from Excel sheet

### ISSUE THREAD

**Issue by NiLon** [PHPOffice/PhpSpreadsheet#2892]
This is:

```
- [ ] a bug report
- [X] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

Reading Excel tables doesn't seem to be supported because some corruption(?) issues. However, it would be still useful to get ranges (only reading) of the tables because that way data is still readable. Right now there is no way to get tables even listed.

In Python such solution exists:
```python
from openpyxl import load_workbook
wb = load_workbook(filename)
ws = wb["Sheet1"]
print(ws.tables)
```

that outputs something like {'dSalesReps': 'A1:C26', 'dProduct': 'E1:I17', 'dCategory': 'K1:L6', 'dSupplier': 'N1:R5'}

Having method to get those table ranges would allow user to fetch data from them with rangeToArray() method.

**Comment by oleibman** [comment]
Closing. No update in 2 years, and Tables are now implemented.
