### ISSUE TITLE
Button Disappear When Using Funtion Load in IOFactory 

### ISSUE THREAD

**Issue by thaomd-2569** [PHPOffice/PhpSpreadsheet#2904]
This is: error, when i use function load in IOFactory my button in file xls disappear. Please help me with issue.
[
![image](https://user-images.githubusercontent.com/86293405/174774561-805ad831-9920-4e1f-993a-db1ecc095a2b.png)
](url)
```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by MarkBaker** [comment]
https://github.com/PHPOffice/PhpSpreadsheet/issues/2661

Form elements like buttons are not currently supported, providing that support is Work-in-Progress
