### ISSUE TITLE
Timezone not used when converting from PHP to Excel

### ISSUE THREAD

**Issue by mikehaertl** [PHPOffice/PhpSpreadsheet#291]
This is:

- [ ] a bug report
- [x] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?

The methods that convert date and time from PHP to Excel should respect the timezone and convert to the correct Excel timezone (`Date::getDefaultTimezone()`). 

If a `DateTime` has a specific timezone set (i.e. with `DateTime::setTimeZone()`), this information should be used to convert to the correct Excel timezone.

It should also be possible to pass a timezone string or object to some methods.

### What is the current behavior?

The following methods do not take any timezone into consideration:

* `Date::PHPToExcel()`
* `Date::dateTimeToExcel()`
* `Date::formattedPHPToExcel()`
* `Date::stringToExcel()`

I suggest that `stringToExcel()` and `formattedPHPToExcel` get another argument `$timezone`, which can either be a timezone object or a PHP `DateTimeZone` object. It could default to `null` in which case the `Date::getDefaultTimeZone()` should be used. The actual timzone conversion should be implemented in `formattedPHPToExcel()`

`dateTimeToExcel()` should check the `DateTime::getTimeZone()` of the passed `$dateValue` and pass this to `formattedPHPToExcel()`.

**Comment by PowerKiKi** [comment]
@MarkBaker, you recently worked on refactoring dates. What are your thought about that ?

**Comment by mikehaertl** [comment]
@PowerKiKi Sorry, I was wrong. There should not be any conversion. It should simply ignore any timezone and simply render the time as is. So everything is fine and datetime appears in excel as expected.
