### ISSUE TITLE
class TCPDF not found

### ISSUE THREAD

**Issue by ronrun** [PHPOffice/PhpSpreadsheet#2914]
This is:

```
- [x ] a bug report
```

### What is the expected behavior?
download pdf file

### What is the current behavior?
Shows error message: class Tcpdf not found, in vendor/phpoffice/.../Writer/PDF/Tcpdf.php  line 33
```
    protected function createExternalWriterInstance($orientation, $unit, $paperSize)
    {
        return new \TCPDF($orientation, $unit, $paperSize);
    }
```
That line is the return line.

### What are the steps to reproduce?
I use laravel, installed maatwebsite/excel. I realized that it is based on PhpSpreadsheet. Then I use PhpSpreadsheet directly,   

Copy the sample code to my service file:  phpoffice/phpspreadsheet/samples/Pdf/21_Pdf_TCPDF.php, and chage the path needed.

In my service file.

```
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;

class MemberService
{
	public function export($data)
	{
		require base_path() . '/vendor/phpoffice/phpspreadsheet/samples/Header.php';
		$spreadsheet = require base_path() . '/vendor/phpoffice/phpspreadsheet/samples/templates/sampleSpreadsheet.php';
		
		$helper->log('Hide grid lines');
		$spreadsheet->getActiveSheet()->setShowGridLines(false);
		
		$helper->log('Set orientation to landscape');
		$spreadsheet->getActiveSheet()->getPageSetup()->setOrientation(PageSetup::ORIENTATION_LANDSCAPE);
		
		$className = \PhpOffice\PhpSpreadsheet\Writer\Pdf\Tcpdf::class;
		$helper->log("Write to PDF format using {$className}");
		IOFactory::registerWriter('Pdf', $className);
		
		// Save
		$helper->write($spreadsheet, __FILE__, ['Pdf']);
		return;
	}
```
The content inside my service export() is the content in the sample file.
It keeps saying class Tcpdf not found, in vendor/phpoffice/.../Writer/PDF/Tcpdf.php  line 33.
After googled for hours, I think maybe I should install Tcpdf itself, 
`composer require elibyy/tcpdf-laravel`
After this, it's OK, I can download pdf. But in your official website or articles on internet, no one says explicitly that we should install elibyy/tcpdf-laravel. 

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [x ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
PDF

### Which versions of PhpSpreadsheet and PHP are affected?
1.23

**Comment by MarkBaker** [comment]
From the [documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/reading-and-writing-to-file/#pdf):

> PhpSpreadsheet’s PDF Writer is a wrapper for a 3rd-Party PDF Rendering library such as TCPDF, mPDF or Dompdf. You must now install a PDF rendering library yourself; but PhpSpreadsheet will work with a number of different libraries.

I'm not sure how much clearer I can make this in the documentation, perhaps if I highlight **"You must now install a PDF rendering library yourself"**

**Comment by ronrun** [comment]
Sorry, my fault. Actually I use laravel-excel which is based on PhpSpreadsheet, then I checked your github... Anyway, I really missed the words. Very sorry. Maybe highlight is a good suggestion.
