### ISSUE TITLE
load template

### ISSUE THREAD

**Issue by dgIngenieria** [PHPOffice/PhpSpreadsheet#2927]
This is:
Fatal error: Constructor PhpOffice\PhpSpreadsheet\Reader\Xlsx\Styles::__construct() cannot declare a return type in D:\xampp\htdocs\dlogger\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx\Styles.php on line 18
```
- [ X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by MarkBaker** [comment]
Insufficient information to diagnose problem.

But there are no return types declared for any constructors anywhere in the PhpSpreadsheet codebase; and the Xlsx Style Reader doesn't even declare a constructor in the code.
