### ISSUE TITLE
Error with the Calculation of VLOOKUP cells

### ISSUE THREAD

**Issue by c-louis** [PHPOffice/PhpSpreadsheet#2934]
Hello 😄 

This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
VLOOKUP should find the cell and retrieve the value

### What is the current behavior?
TypeError because of `strToLower` which happens because of an error of the evaluation of the formula

`PHP Fatal error:  Uncaught TypeError: PhpOffice\PhpSpreadsheet\Shared\StringHelper::strToLower(): Argument #1 ($textValue) must be of type string`

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use \PhpOffice\PhpSpreadsheet\Calculation\Calculation;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$doc = "doc2.xlsx";

$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($doc);
$sheet = $spreadsheet->getActiveSheet();

evaluate($spreadsheet, $sheet, "C2");

function evaluate( $spreadSheet,  $workSheet,  $cellAddress)
{
    // Initialise the calculation engine for debug logging
    $calculationEngine = Calculation::getInstance($spreadSheet);
//    $calculationEngine->disableBranchPruning();
    $debugLog = $calculationEngine->getDebugLog();

    $calculationEngine->flushInstance();
    $debugLog->setWriteDebugLog(true);
//    $debugLog->setEchoDebugLog(true);

    $formulaValue = $workSheet->getCell($cellAddress)->getValue();

    echo PHP_EOL, 'Formula value for evaluation is ', $formulaValue, PHP_EOL;

    $canExecuteCalculation = false;

    try {
        $tokens = $calculationEngine->parseFormula($formulaValue);
        $canExecuteCalculation = true;
    } catch (Exception $e) {
        echo 'PARSER ERROR: ', $e->getMessage(), PHP_EOL;
    } finally {
        echo 'Parser Stack :-';
        print_r($tokens ?? PHP_EOL . 'NULL');
    }

    $callStartTime = microtime(true);

    if ($canExecuteCalculation) {
        //  calculate
        try {
            $cellValue = $workSheet->getCell($cellAddress)
                ->getCalculatedValue();

            echo 'Result is ', $cellValue, PHP_EOL;

            echo 'Evaluation Log:', PHP_EOL;
            print_r($debugLog->getLog());
        } catch (Exception $e) {
            echo 'CALCULATION ENGINE ERROR: ', $e->getMessage(), PHP_EOL;

            echo 'Evaluation Log:', PHP_EOL;
            print_r($debugLog->getLog());
        }
    }

    $callEndTime = microtime(true);
    $callTime = $callEndTime - $callStartTime;

    echo PHP_EOL;
    echo 'Call time to evaluate formula was ', sprintf('%.4f', $callTime), ' seconds', PHP_EOL;

    return $cellValue ?? null;
}
```
Here is the file I use to test (It's a minimal version of it, showing the bug) : 

[doc2.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9093478/doc2.xlsx)

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [x] Formula Calulations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
1.24.0

### What I did try to investigate : 

If you remove the "FALSE" of `=VLOOKUP(B2;Sheet2!B:C;2;FALSE)` then it doesnt bug anymore.

**Comment by Moongun** [comment]
Hey. Have the same issue. Part of exception message below :):
`"PhpOffice\\PhpSpreadsheet\\Shared\\StringHelper::strToLower(): Argument #1 ($textValue) must be of type string, null given, called in \/.\/vendor\/phpoffice\/phpspreadsheet\/src\/PhpSpreadsheet\/Calculation\/LookupRef\/VLookup.php on line 72"`

**Comment by pcphatweb** [comment]
I have same issue when I work with merge cell null value and luckily the bug was fixed ^^
THANKS ALL!
