### ISSUE TITLE
Deprecate use of $smoothLine as well as $plotStyle='lineMarker' in Chart/DataSeries for ScatterCharts

### ISSUE THREAD

**Issue by bridgeplayr** [PHPOffice/PhpSpreadsheet#2935]
This is:

```
- [x] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
N.B. DataSeries->plotStyle property value STYLE_LINEMARKER (='lineMarker') is currently examined only in Chart/Renderer/JpGraph.php, whose use is deprecated.  Otherwise, DataSeries property value 'lineMarker' is unused.

Similarly, the DataSeries->smoothLine property is never tested, but its presence potentially confuses users who mistakenly use this (identically named) property and its (identically named) getter/setter methods in both DataSeries as well as DataSeriesValues.

### What is the expected behavior?
When the user assigns the 'smoothLine' property to a DataSeriesValues array [via $DSV->set_smoothLine(true) ] then the Chart line should be displayed as a smooth Bezier line regardless of any property in its DataSeries, (in my opinion).

### What is the current behavior?
If DataSeriesValues->smoothLine == TRUE its line will be straight if its DataSeries->plotStyle == 'lineMarker' (regardless of the value of DataSeries->smoothLine,)  This is because Chart/Writer/Xlsx qualifies its writing of the <c:smooth> element with a logical AND of '$plotType ===DataSeries::TYPE_SCATTERCHART' and '$plotStyle' === 'smoothMarker'.  Therefore, a DataSeriesValues array with a specified property value of TRUE for 'smoothLine' will not be expressed in the xml as <c:smooth val="1"> unless the DataSeries' plotStyle == 'smoothMarker'.  Instead, <c:smooth> will be absent from the xml.

### What are the steps to reproduce?
In example file samples/Chart/33_Chart_create_scatter2.php, change as follows:
WAS: DataSeries::STYLE_SMOOTHMARKER  // plotStyle

1. IS:     DataSeries::STYLE_LINEMARKER  // plotStyle
This changes the original smooth (Bezier) line nature of the first DataSeriesValues series to a straight line point connection (which is the default behavior).

2. IS:     // DataSeries::STYLE_LINEMARKER  // plotStyle
Same result.

Neither result is affected by any value of property DataSeries->smoothLine, including null.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calulations
- [x] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Xlsx is affected

### Which versions of PhpSpreadsheet and PHP are affected?
1.24 7.3

**Comment by oleibman** [comment]
JpGraph is not deprecated. It is just not maintained in Composer, and the version there is not Php8 compatible (maybe not even some versions of 7) so we can't allow its use in our test suite. However, you can manually substitute the current version of that product for the version that Composer brings in, and it should work just fine. I have no idea what it's doing with lineMarker, but am reluctant to make it stop working (under the uncertain assumption that it works now).

As for smoothLine, that was one of your first requests that I worked on. It seemed to me at the time that Excel required it at both the DS and the DSV levels. I can look into it again.

**Comment by bridgeplayr** [comment]
This annoying behavior tripped me up while I was testing Axis cases.

Thank you for the JpGraph clarification - I had hoped to use it, and I now feel free to try it - if I can find a compatible version.

[N.B. I understand removing properties is a breaking change, but having two identically-named properties in two similarly-named classes (DataSeriesValues & DataSeries) with identical getter/setter methods is seriously confusing.  At least to me.]

I repeat my previous request to remove DataSeries property $smoothLine and its getter/setter methods.  In a ScatterChart, the accidental assignment of 'lineMarker' to $plotStyle will suppress a $DSV whose $smoothLine property is true, and the user will have a difficult time discovering the reason for the resultant straight-line.  To prevent this unfortunate circumstance, I propose that Writer/Xlsx change the qualification for the call to startElement('c:smooth') in the "// Values" section of function writePlotArea() from:

WAS: if ($groupType === DataSeries::TYPE_SCATTERCHART && $plotGroup->getPlotStyle() === 'smoothMarker')

IS: if ($groupType === DataSeries::TYPE_SCATTERCHART)

This will allow a $DSV->smoothLine property value of TRUE to be expressed correctly in the xml regardless of its containing $DS->plotStyle value, (which is the correct behavior in my opinion.)

**Comment by oleibman** [comment]
Under what circumstances would you "accidentally" set the style to lineMarker? It sounds like you're trying to get PhpSpreadsheet to ignore something the programmer has explicitly requested - it certainly isn't used as any kind of a default. Perhaps, after looking at the finished product, smooth lines aren't desired after all, and it's easier to change the DataSeries property to lineMarker in one place than it is to remove the smooth declarations from all the DSVs? It is possible that you can make a stronger case for using the c:smooth tag for "not lineMarker"; I would still need to think about that.

Issue #2783 has more details about how to use JpGraph.

**Comment by bridgeplayr** [comment]
Excel describes 'smooth line' charts as well as 'line charts'.  It is not a stretch to associate those choices with 'lineMarker' and 'smoothMarker'.  But what if you want a mix?

I submit that a programmer who assembles a ScatterChart may simply ignore assigning any value to the DS->plotStyle property since it is possible to desire an XY chart with both smooth lines and straight lines, and maybe no lines. So the programmer omits it, and its value is null.  If the programmer has assigned TRUE to any DSV->smoothLine property, she will be mystified why it doesn't work.  (We'll know, but she won't have much of a clue.)  Changing Writer masks her (unfortunate) choice of not assigning 'smoothMarker' to DS->plotStyle.

Thank you for the JpGraph link.

**Comment by oleibman** [comment]
Sorry, I don't think you've made a case for any code changes. You have made a case for documentation changes, and 2950, which will close this ticket when merged, will document (in both places) that scatterLines needs to be set at both the DS and DSV level.

**Comment by bridgeplayr** [comment]
Ok.  Your call certainly.  Documenting will help avoid the possibility shown below using sample/Chart/33_Chart_create_scatter2.php.

Case 1: As written - behavior as expected
```
$series = new DataSeries(
    DataSeries::TYPE_SCATTERCHART, // plotType
    ...
    DataSeries::STYLE_SMOOTHMARKER  // plotStyle
);
```
![image](https://user-images.githubusercontent.com/103679672/179808092-1379183f-ca38-4517-a8a3-0b035abe7cd7.png)

Case 2: Modified to comment the SMOOTHMARKER designation.  I suggest this might be reasonable thinking since, after all, I know one line will be smooth, one straight, and one has no line at all.  To ensure the correct display, I have specified each DSV's line charactieristics.  Since I don't want to have the series combination ($series) override each DSV assignment, I comment the last line,)
The smooth line is now a straight line.  
```
$series = new DataSeries(
    DataSeries::TYPE_SCATTERCHART, // plotType
    ...
    // DataSeries::STYLE_SMOOTHMARKER  // plotStyle
);
```
![image](https://user-images.githubusercontent.com/103679672/179808606-75b5ae21-8d77-49af-8ab5-98ec7a39c666.png)
