### ISSUE TITLE
Persian character issue in version 1.24 

### ISSUE THREAD

**Issue by afshinhatampour** [PHPOffice/PhpSpreadsheet#2946]
After new release and update composer
In version 1.24 and Laravel version v8.83.19
I have a problem with Persian character 
In version 1.23 and Laravel v8.83.18 I don't have problem like that

**Comment by afshinhatampour** [comment]
I think problem is from PhpSpreadsheet package
Is there any change in your package dependencies ?

**Comment by oleibman** [comment]
What is the problem you are seeing? Note that there was a problem with Html Reader which was fixed yesterday in master.

**Comment by afshinhatampour** [comment]
In export Xlsx files the Persian character print like this 

Ú©Ø±Ù Ø¶Ø¯ Ø¢ÙØªØ§Ø¨ Ø³ÛÙØ±Ù +SPF 30 Ø­Ø¬Ù 50 Ù ÛÙÛ ÙÛØªØ± - Ø¨Ú Ø±ÙØ´Ù | Ø
-- | --

**Comment by oleibman** [comment]
Can you upload the code which generates that spreadsheet? I cannot investigate further without it.

**Comment by avpet979** [comment]
In version 1.24 export had problems with Russian language too. After downgrading to 1.23 there is no problem.

**Comment by afshinhatampour** [comment]
here is mt code:
in controller:

    `public function exportOrders()
        {
            $file_name = 'orders' . Verta::now()->format('Y-m-d_H:i') . '.xlsx';
            header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
            header("Content-Disposition: attachment; filename=$file_name");  //File name extension was wrong
            header("Expires: 0");
            header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
            header("Cache-Control: private", false);
    
            $excel = Excel::download(new OrderExport(), 'orders' . Verta::now()->format('Y-m-d_H:i') . '.xlsx');
            echo file_get_contents($excel->getFile());
            unlink($excel->getFile());
            exit;
        }`

in OrderExport.php:

      ` $filtered_seller = null;
        try {

            if ($seller_id = request('seller', null))
                $filtered_seller = Seller::find($seller_id);

            $order_repository = new OrderRepository(app());
            $orders = $order_repository->getOrdersReport(false, seller: $filtered_seller);
        } catch (\Exception $e) {
            $orders = [];
        }

        return view('finance.contents.order.export', ['orders' => $orders,'filtered_seller'=>$filtered_seller]);`

**Comment by MarkBaker** [comment]
If this does resolve the issue, then I'll get a `1.24.1` release done as quickly as possible

**Comment by avpet979** [comment]
> I don't know anything about Laravel. Is it possible for you to test with the current version of Laravel-Excel and the master version of PhpSpreadsheet? I suspect that the problem is with a bug introduced into Html Reader in 1.24 which is fixed by PR #2943, which is now merged into master.

Yeah, it's working (maatwebsite/excel 3.1.40 + PhpSpreadsheet dev-master 051598e

**Comment by afshinhatampour** [comment]
Thank you so much for your response 
I’ll should be check with new version 1.24.1

**Comment by avpet979** [comment]
> [Version 1.24.1](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.24.1) Released

work as expected! thanks!

**Comment by avpet979** [comment]
> [Version 1.24.1](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.24.1) Released

Work as expected! Thanks!
