### ISSUE TITLE
Array to string conversion as flattenArray() is not fully flattening an array

### ISSUE THREAD

**Issue by u01jmg3** [PHPOffice/PhpSpreadsheet#2955]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

This following formula is _partially_ supported - although it works it causes a PHP notice.

```
=CONCAT(INDEX(Lookup!$A$2, MATCH($A2, Lookup!$B$2, 0)))
```

### What is the current behavior?

```
Notice: Array to string conversion in \phpoffice\phpspreadsheet\src\PhpSpreadsheet\Calculation\TextData\Helpers.php on line 34
```

1. Follow this to [`extractString()`](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Calculation/TextData/Helpers.php#L25)
1. This then takes you to [`Concatenate.php`](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Calculation/TextData/Concatenate.php#L29)
1. And just above that is [`flattenArray()`](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Calculation/TextData/Concatenate.php#L26) and where the issue lies

It appears [`flattenArray()`](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Calculation/Functions.php#L570), a method that's been untouched in ~12 years, is not fully flattening an array as it returns the following if PHPSpreadsheet is used with the formula in the uploaded [`test.xlsx`](https://github.com/PHPOffice/PhpSpreadsheet/files/9149534/test.xlsx)
 file:

```php
array(1) {
  [0]=>
  array(1) {
    ["B"]=>
    string(6) "PHP"
  }
}
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader       = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet  = $reader->load('test.xlsx');
$worksheet    = $spreadsheet->getActiveSheet();
$fileContents = $worksheet->toArray();
```

If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

📁 [`test.xlsx`](https://github.com/PHPOffice/PhpSpreadsheet/files/9149534/test.xlsx)

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [x] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

`.xlsx`

### Which versions of PhpSpreadsheet and PHP are affected?

`1.24.1`

**Comment by oleibman** [comment]
While there is nothing technically wrong with your test case, it would be better to (also) demonstrate that it solves the original problem, i.e. it correctly calculates the results of the spreadsheet formula that it was not correctly calculating before. Can you add such a test?

**Comment by u01jmg3** [comment]
Done 👍🏻
