### ISSUE TITLE
Compatibility with php 7.3

### ISSUE THREAD

**Issue by lBeJIuk** [PHPOffice/PhpSpreadsheet#2957]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Package will be installed.

### What is the current behavior?
Package is not installed

### What are the steps to reproduce?
- use php 7.3
- Try to install library `composer.phar require phpoffice/phpspreadsheet`
- As result you wil get
```
  Problem 1
    - phpoffice/phpspreadsheet[1.24.0, ..., 1.24.1] require maennchen/zipstream-php ^2.1 -> satisfiable by maennchen/zipstream-php[2.2.1].
    - maennchen/zipstream-php 2.2.1 requires php ^7.4 || ^8.0 -> your php version 7.3 does not satisfy that requirement.
    - Root composer.json requires phpoffice/phpspreadsheet ^1.24 -> satisfiable by phpoffice/phpspreadsheet[1.24.0, 1.24.1].
```

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet: 1.24.1
Php: 7.3

**Comment by MarkBaker** [comment]
No, this isn't a bug with PhpSpreadsheet, and PhpSpreadsheet is still fully compatible with PHP 7.3

![image](https://user-images.githubusercontent.com/770298/180228979-38bd53b9-a811-48fc-a273-a0b9a2ff38c2.png)

Take a look at the problem that composer has identified: while PhpSpreadsheet requires `maennchen/zipstream-php` at version `2.1` or above; composer is saying that it has `maennchen/zipstream-php`  verson `2.2.1` (which doesn't work with PHP 7.3). Why isn't it trying to install `maennchen/zipstream-php` version `2.1`? Do you have  pinned version?

**Comment by lBeJIuk** [comment]
Oh.. my mistake. now it works. Thanks.
