### ISSUE TITLE
Calculation Named Range issue

### ISSUE THREAD

**Issue by bryancolligan** [PHPOffice/PhpSpreadsheet#296]
This is:
a bug report

### What is the expected behavior?
Name Range should be able to reference another sheet in the file.

### What is the current behavior?
"!" in named range errors out

### What are the steps to reproduce?
reference a named range in a formula calculation in a separate sheet.

### Which versions of PhpSpreadsheet and PHP are affected?
1

**Comment by oleibman** [comment]
Reopening. Expect a fix in a day or two.
