### ISSUE TITLE
Documentation Rendering Issue

### ISSUE THREAD

**Issue by tyfai** [PHPOffice/PhpSpreadsheet#2980]
Hi,

I think there is a rendering issue with the documentation on this page:

https://phpspreadsheet.readthedocs.io/en/latest/#software-requirements

It looks like the triple backtick is not being evaluated properly by the Markdown parser.

![image](https://user-images.githubusercontent.com/102683359/182574072-a4a3016f-94cd-49e8-9f24-924f79c9c827.png)

**Comment by MarkBaker** [comment]
Thanks for pointing this out; discrepancy between the markdown parser on github, and the equivalent on readthedocs.

**Comment by tyfai** [comment]
No worries, thank you for this library. :)
