### ISSUE TITLE
Error reading password protected xlsx file

### ISSUE THREAD

**Issue by RoyvanEmpel** [PHPOffice/PhpSpreadsheet#2981]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
For the library to load the password protected xlsx without any errors.

### What is the current behavior?
```
Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Reader\Exception: Could not find zip member zip:///tmp/phpvyIr1s#_rels/.rels in
/var/www/excel_project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/File.php:159 Stack trace: #0
/var/www/excel_project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php(400): PhpOffice\PhpSpreadsheet\Shared\File::assertFile() #1
/var/www/excel_project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/BaseReader.php(166): PhpOffice\PhpSpreadsheet\Reader\Xlsx->loadSpreadsheetFromFile() #2
/var/www/excel_project/libraries/importer.php(51): PhpOffice\PhpSpreadsheet\Reader\BaseReader->load() #3 /var/www/excel_project/controllers/admin.php(909): Importer->load() #4
/var/www/excel_project/controllers/admin.php(710): Admin->settings_import_profile() #5 /var/www/excel_project/redirector.php(112): Admin->settings() #6
/var/www/excel_project/controllers/core/loader.php(56): require_once('...') #7 /var/www/excel_project/index.php(10): include_once('...') #8 {main} thrown in
/var/www/excel_project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/File.php on line 159
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load($_FILES['template_document']['tmp_name']);

$sheet = $spreadsheet->getActiveSheet();
$sheet->getProtection()->setSheet(true);
$sheet->getProtection()->setPassword('123');
echo $sheet->getCell('A1')->getValue() . "\n";
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

Example file:
[example.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9252642/example.xlsx)

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Only tested .xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
phpspreadsheet: 1.24.1
PHP: 8.1.8

**Comment by oleibman** [comment]
PhpSpreadsheet supports password protection to prevent certain updates to a spreadsheet. If, by password protection, you mean not being able to open the file at all without knowing the password, PhpSpreadsheet does not support that. This is in the documentation: 'If you need to completely prevent reading a file by any tool, including PhpSpreadsheet, then you are looking for "encryption", not "protection". Your file is encrypted (and therefore unsupported), not merely password-protected.

**Comment by RoyvanEmpel** [comment]
> [example.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9252642/example.xlsx)

I am trying to open the example.xlsx above with the password "123". Using the code in the issue i am not able to open the file.

**Comment by oleibman** [comment]
PhpSpreadsheet cannot open an encrypted workbook.

**Comment by RoyvanEmpel** [comment]
For other people needing a solution i used library to decrypt the file before using it with PhpSpreadsheet.
[PHPDecryptXLSXWithPassword](https://github.com/jaydadhania08/PHPDecryptXLSXWithPassword)
It has a few deprecated errors in php 8.1 but those are fixed by changing a few lines.
