### ISSUE TITLE
UConverter

### ISSUE THREAD

**Issue by Sab-tech-lab** [PHPOffice/PhpSpreadsheet#2982]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Installing the library with composer and being able to use it without dependency errors.

### What is the current behavior?
After installing the library with composer and creating the spreadsheet I get an error on the UConverter class which is not found.

### What are the steps to reproduce?
1 - Install with composer
2 - Example for create file with one cell value

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Hello World !');

$writer = new Xlsx($spreadsheet);
$writer->save('hello world.xlsx');

```
The error line is into Shared/StringHelper ad line 337.

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
For Xlsx file

### Which versions of PhpSpreadsheet and PHP are affected?
1.24.1 - 2022-07-18 Latest

**Comment by Sab-tech-lab** [comment]
I have found the error, is my error.

**Comment by MoroAlberto** [comment]
I have the same problem after update from 1.23.0 to 1.24.0

error "**Can not find class UConverter**"

how did you solve?

**Comment by oleibman** [comment]
What PHP release are you using? Are you running under any particular framework? The code in question is designed to use other techniques if class UConverter does not exist. My own testing indicates the sample code works correctly in several releases of PHP even when intl is not enabled. I also see no documentation to indicate that class_exist ever issues an error message - it just returns true or false.
