### ISSUE TITLE
Worksheet does not match UTF8 letters for cell names

### ISSUE THREAD

**Issue by cekaon** [PHPOffice/PhpSpreadsheet#2987]
https://github.com/PHPOffice/PhpSpreadsheet/blob/06d2682c5bdfe38c1cfa0d75d47d95e11e030454/src/PhpSpreadsheet/Worksheet/Worksheet.php#L1268

Can you update the preg_match regexp to allow UTF8 characters for cell names? If I load excel with named cells, I am not able to read name e.g. Caché, because \p{L} does not work correctly if UTF8 is not defined at start of the preg_match in PHP.

The line 1268 should be:
`preg_match('/(*UTF8)^' . Calculation::CALCULATION_REGEXP_DEFINEDNAME . '$/i', $coordinate)`

**Comment by cekaon** [comment]
**Example**

This does not work:
`preg_match("/^([\p{L}]*)$/i", "Caché");`

But this work correctly:
`preg_match("/(*UTF8)^([\p{L}]*)$/i", "Caché");`

**Comment by MarkBaker** [comment]
Fixed, although using the `/u` switch rather than `(*UTF8)` for consistency with the rest of the codebase

**Comment by cekaon** [comment]
Thank you sir.
