### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by Sedaj** [PHPOffice/PhpSpreadsheet#299]
Hello,

thank you for the work on this project.

Like in previous version i have this issue:

Uninitialized string offset 10 fired in Xls:getUInt2d method 
on line

`return ord($data[$pos]) | (ord($data[$pos + 1]) << 8);`

reported here

https://github.com/PHPOffice/PHPExcel/issues/1347
https://github.com/PHPOffice/PHPExcel/issues/811
https://github.com/PHPOffice/PHPExcel/issues/883

Does anybody know how to deal with it ?

**Comment by PowerKiKi** [comment]
Please use the issue template when submitting new issues. In particular this is missing the very important [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file.
