### ISSUE TITLE
Coordinate::extractAllCellReferencesInRange no longer accepts sheet name in reference

### ISSUE THREAD

**Issue by rasmuscnielsen** [PHPOffice/PhpSpreadsheet#3005]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

In `v1.23.0` it was possible to have sheet name in a reference:

```php
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;

Coordinate::extractAllCellReferencesInRange('Sheet1!D3') // array:1 [ 0 => "SHEET1!D3" ]
```

### What is the current behavior?

In v1.24.0 and v1.24.1 the above statement results in the following exception:

> PhpOffice\PhpSpreadsheet\Exception 
>
> Column string index can not be longer than 3 characters

### What are the steps to reproduce?

See above code snippet.

### Which versions of PhpSpreadsheet and PHP are affected?

v1.24.0 and v1.24.1

**Comment by MarkBaker** [comment]
To be honest, extractAllCellReferencesInRange() should never have accepted a cell reference with a sheet name anyway; it always threw an exception if the reference was for a range of cells with a sheet name; but somehow a single cell reference with a sheet name wasn't handled correctly.

I'll take a look at what I can do to make the method more consistent

**Comment by oleibman** [comment]
Closing, issue appears to have been resolved over a year ago.
