### ISSUE TITLE
some special words can not read

### ISSUE THREAD

**Issue by lwx2615** [PHPOffice/PhpSpreadsheet#301]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I just want phpspreadsheet to compatible some other language。

### What is the current behavior?
when I tried to read the csv file ,with some different language cullomns. some can read,some return bool(false)  .

### What are the steps to reproduce?
1. create a csv file named "test.xls" ,type some different  value in english, rusia,chinese,jappen,and some big numbers and so on.
2. 

```php 
 $inputFileName="test.xls";
$spreadsheet = IOFactory::load($inputFileName);
$sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);
var_dump($sheetData)
```

### Which versions of PhpSpreadsheet and PHP are affected?
latest version.

**Comment by PowerKiKi** [comment]
Cannot reproduce. The following code:

```php
$filename = 'test.csv';
file_put_contents($filename, 'test;테스;트テスト;контрольная;测试' . PHP_EOL);
$spreadsheet = IOFactory::load($filename);
$sheet = $spreadsheet->getActiveSheet();
$data = $sheet->rangeToArray('A1:E1');
var_dump($data);
```

Will correctly output:
```
array(1) {
  [0] =>
  array(5) {
    [0] =>
    string(4) "test"
    [1] =>
    string(6) "테스"
    [2] =>
    string(12) "트テスト"
    [3] =>
    string(22) "контрольная"
    [4] =>
    string(6) "测试"
  }
}
```

**Comment by lwx2615** [comment]
I  found the reason. The file I select from mysql is not saved as utf8,when I turned it to UTF8 ,it can read normal.  thank you!
