### ISSUE TITLE
Invalid fill color is returned when cell has fill pattern

### ISSUE THREAD

**Issue by nepeee** [PHPOffice/PhpSpreadsheet#3022]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?

``` $sheet->getStyle('A1')->getFill()->getStartColor()->getARGB() ``` returns the correct color when fill pattern is set on the cell.

### What is the current behavior?

``` $sheet->getStyle('A1')->getFill()->getStartColor()->getARGB() ``` returns FFFFFFFF when fill pattern is set on the cell.

### What are the steps to reproduce?
Create a xlsx file where cell A1 has fill pattern and background color.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$exc = $reader->load('xyz.xlsx');
$sheet = $exc->getSheet(0);
echo $sheet->getStyle('A1')->getFill()->getStartColor()->getARGB();
```

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Only tested xlsx.

### Which versions of PhpSpreadsheet and PHP are affected?
1.24.1 but i have the same issue with the old PHPExcel lib so probably all.

**Comment by nepeee** [comment]
Found the issue, i had to use getEndColor

**Comment by oleibman** [comment]
Issue seems resolved, closing.
