### ISSUE TITLE
About exporting to excel with formula

### ISSUE THREAD

**Issue by Ademgenc53** [PHPOffice/PhpSpreadsheet#3027]
Hello,

I want to produce excel with formula with php
I'm trying for the first time I'm a beginner

I applied the formula as below, but the percent discount field should be 50, but 5000 is displayed.
where am i doing wrong

```
$sheet->setCellValue("A16","MARKA");

$spreadsheet->getActiveSheet()->mergeCells('B16:D16');
$sheet->setCellValue("B16","ÜRÜN ADI");

$spreadsheet->getActiveSheet()->getStyle('E16:F16')
    ->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_RIGHT);
$spreadsheet->getActiveSheet()->getStyle('E16')->getNumberFormat()
    ->setFormatCode('General');
$sheet->setCellValue("E16","3");

$spreadsheet->getActiveSheet()->getStyle('F16')->getNumberFormat()
    ->setFormatCode('[$$-409]#,##0.00');
$sheet->setCellValue("F16","1000.00");

$spreadsheet->getActiveSheet()->getStyle('G16:H16')
    ->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_RIGHT);
$spreadsheet->getActiveSheet()->getStyle('G16')->getNumberFormat()
    ->setFormatCode('0.00%');
$sheet->setCellValue("G16","50");

$spreadsheet->getActiveSheet()->getStyle('H16')->getNumberFormat()
    ->setFormatCode('[$$-409]#,##0.00');
$sheet->setCellValue("H16","=(E16*F16)-(E16*F16*G16)");
```
Excel output
![Ekran görüntüsü 2022-08-24 202415](https://user-images.githubusercontent.com/55327675/186485989-78a55608-37fc-469d-9431-4f716710babf.png)

**Comment by oleibman** [comment]
You need to set cell G16 to 0.50, not 50. This is the same way that Excel handles it.

**Comment by Ademgenc53** [comment]
Thank you for the answer
I don't know much about Excel
The correct result I entered as '0.50'
But it is seen as '0.50' in the table
![Ekran görüntüsü 2022-08-25 100342](https://user-images.githubusercontent.com/55327675/186598417-7deaee67-6c8c-4434-9443-b093b940007d.png)


However, when I manually enter 50 instead of 0.50 in the excel table, it still gives the correct result and it appears as 50.00 in the table, I want it to look like this.
![Ekran görüntüsü 2022-08-25 100419](https://user-images.githubusercontent.com/55327675/186598460-3a6cac7e-ff03-40a1-8e74-bee887a8e947.png)
