### ISSUE TITLE
Roadmap / upcoming breaking changes?

### ISSUE THREAD

**Issue by f1rf1n** [PHPOffice/PhpSpreadsheet#303]
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

Is there a roadmap or timetable for a stable release. There are a few issues about breaking changes etc. Also projects having phpspreadsheet as a dependency need to be refactored. 

Some kind of indication of upcoming breaking changes would be very nice to have in order to help other projects plan their updates.

All versions are affected.

**Comment by PowerKiKi** [comment]
The roadmap are the [milestones](https://github.com/PHPOffice/PhpSpreadsheet/milestones).

**Comment by f1rf1n** [comment]
I don't get how to get (estimated dates) from the milestones. Or what issues / features will be in the milestone releases. But then 1.0 was just released with the stable tag, so my question is answered for now :-)
Thanks!

**Comment by PowerKiKi** [comment]
You don't see much, because nothing much is planned.
