### ISSUE TITLE
About going to the bottom line of text

### ISSUE THREAD

**Issue by Ademgenc53** [PHPOffice/PhpSpreadsheet#3031]
Hello,

![Ekran görüntüsü 2022-08-27 094745](https://user-images.githubusercontent.com/55327675/187018886-c7c06733-18ab-4c40-8b6a-ba53486dee5e.png)

With the variable comes the text as in the picture
however, it doesn't go to the bottom line

I'm trying both options below
```
$sheet->setCellValue('E48', $uydu_adlarinigoster);
//$spreadsheet->getActiveSheet()->getCell('E48')->setValue($uydu_adlarinigoster);

$spreadsheet->getActiveSheet()->getStyle('E48:G50')->getAlignment()->setWrapText(true);
```
However, when I copy text from excel and try below without making any changes, it goes to the bottom line
`$sheet->setCellValue('E'.$artibir, "*Türksat 3A/4A @ 42° Doğu\n*Hot Bird 13B/13C/13E @ 13° Doğu\n*Eutelsat 7A @ 7° Doğu\n");`
![Ekran görüntüsü 2022-08-27 095923](https://user-images.githubusercontent.com/55327675/187019009-cb876e02-b320-462c-a236-2d53c1e86992.png)

Where am I doing wrong?

Thank you

**Comment by MarkBaker** [comment]
Standard [PHP string rules](https://www.php.net/manual/en/language.types.string.php) apply:
`'\n'` (single quoted) is a literal `\` followed by a literal `n`
`"\n"` (double quoted) is interpreted a newline character

**Comment by Ademgenc53** [comment]
actually I know it won't interpret single quotes and interpret double quotes
I found it when I searched for an error based on your answer.
`$uydu_adlarinigoster = str_replace('<br />','\n', $uydu_adlarini_goster)`
The problem was here when I did double quotes the problem was fixed
`$uydu_adlarinigoster = str_replace("<br />","\n", $uydu_adlarini_goster)`

Thank you very much
