### ISSUE TITLE
Add rich text to a cell

### ISSUE THREAD

**Issue by Ademgenc53** [PHPOffice/PhpSpreadsheet#3032]
Hello,
I made a part of the text in the cell bold using the code below
However, while the font size of the whole page was 8, the font size of this bold text became 11
![Ekran görüntüsü 2022-08-27 134114](https://user-images.githubusercontent.com/55327675/187026636-0ccfa378-6b8e-4860-a2d7-4915c1964fe8.png)

How do I make their font size 8?

Thank you
```
$richText = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
$payable = $richText->createTextRun('Gsm: ');
$payable->getFont()->setBold(true);
$richText->createText("$firma_gsm");
$spreadsheet->getActiveSheet()->getCell('C4')->setValue($richText);
```

**Comment by MarkBaker** [comment]
Rich Text runs will default to Calibri 11pt unless you set the style and size yourself.

```php
$richText = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
$payable = $richText->createTextRun('Gsm: ');
$payable->getFont()->setBold(true);
$payable->getFont()->setSize(8);
$richText->createText("$firma_gsm");
$spreadsheet->getActiveSheet()->getCell('C4')->setValue($richText);
```

**Comment by Ademgenc53** [comment]
Thank you very much problem solved
