### ISSUE TITLE
Operate with a value of 1 if it's text, or a number value if it's a number

### ISSUE THREAD

**Issue by Ademgenc53** [PHPOffice/PhpSpreadsheet#3039]
Hello,
With the local language on Excel, it performs the process smoothly as in the picture.

![Ekran görüntüsü 2022-08-29 154702](https://user-images.githubusercontent.com/55327675/187204834-16df04ea-9838-4d65-8f09-e1d7bc8828dc.png)

![Ekran görüntüsü 2022-08-29 154729](https://user-images.githubusercontent.com/55327675/187204839-e468358d-bf24-4bdc-90f1-e7c9a730bb4a.png)
However, when I apply the following English formula to the code, an error occurs.
Where am I doing wrong?

`$sheet->setCellValue("G30","=IF(ISTEXT(D30);1*E30;D30*E30)");`

Thank you

**Comment by Ademgenc53** [comment]
There are formulas in the excel table I exported
```
=(D16*E16)-(D16*E16*F16)
=SUM(M16:M25)
=SUM(D29+G30+G31)
```
There is an English formula as above in the code and it works without any problems.

I know very little about Excel

Why is this code not working? is it in English?
I think it is not necessary to translate into local language
`$sheet->setCellValue("G30","=IF(ISTEXT(D30);1*E30;D30*E30)");`

I even tried the formula by making my 2016 office program English, it worked fine but it doesn't work in the code

**Comment by MarkBaker** [comment]
```php
$sheet->setCellValue("G30","=IF(ISTEXT(D30);1*E30;D30*E30)");
```
will not work because you are using `;` as the argument separator for the Excel `IF()` function. Yoiu ___must___ use `,` instead.
```php
$sheet->setCellValue("G30","=IF(ISTEXT(D30),1*E30,D30*E30)");
```

**Comment by Ademgenc53** [comment]
Worked
Thank you so much
The whole problem is that it is necessary to use only commas instead of semicolons, we couldn't understand
Formula in excel after export ";" appears as a semicolon

Thank you very much again

**Comment by MarkBaker** [comment]
The formula as you see it in MS Excel will depend entirely on your locale settings: if somebody with different locale setings opens it, they will see that formula according to their locale and language. You see it with the function names in Turkish, with a `;` argument separator... if you sent me that file and I opened it now, I'd see it with dutch language function names and a `;` on my new laptop, and in English with a `,` separator on my old laptop.

Internally in an Xlsx file, it is stored using `en_us`

**Comment by Ademgenc53** [comment]
Knowledge that requires expertise, we haven't reached this level yet ;)))
Thanks again for the solution and information.
