### ISSUE TITLE
Trim last char

### ISSUE THREAD

**Issue by DevMostafa** [PHPOffice/PhpSpreadsheet#3051]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I expect to have the right Card Number stored in column.

### What is the current behavior?
I have added a column for a VISA Card Number which is 16 characters and always the last number is converted to 0.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [x] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [x] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 8 and Last Version of Library

**Comment by MarkBaker** [comment]
Store it as a string, not as a number, using `setCellValueExplicit()`

**Comment by DevMostafa** [comment]
@MarkBaker should it's correct
$sheet->setCellValue('H' . $count, $lCase->tenure_no);
==> $sheet->setCellValue('H' . $count, $lCase->tenure_no)->setCellValueExplicit();

**Comment by MarkBaker** [comment]
No!


```php
$sheet->setCellValueExplicit('H' . $count, $lCase->tenure_no, DataType::TYPE_STRING);
```

**Comment by DevMostafa** [comment]
@MarkBaker Many thanks it's working now with the same you have written.

$sheet->setCellValueExplicit('H' . $count, $lCase->tenure_no, 'str');
