### ISSUE TITLE
Xlsx to html choose thead or not

### ISSUE THREAD

**Issue by Martin82sf** [PHPOffice/PhpSpreadsheet#3063]
This is:

```
- [ x] a bug report
- [ x] a feature request
```

### What is the expected behavior?

Hi! 

I'm not sure if it is a bug or simply is the default behavior. 

### What is the current behavior?

Always that I want to convert a a xlsx to html **always** set the first row of the excel insite a html -> tbody tag

I can't find any way ( without modify constants ) to change it to set the first row of the xlsx like a html -> thead

### What are the steps to reproduce?

basic example file

[basic.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9566888/basic.xlsx)

```php
$xlsxName = 'basic.xlsx';
require $_SERVER['DOCUMENT_ROOT']. '/vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\IOFactory;
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$excel = $reader->load($xlsxName);
$writer = IOFactory::createWriter($excel, 'Html');
$writer->generateSheetData();
$message = $writer->save('php://output');
echo $message;
```

Output:
```php
<table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0 gridlines">
        <colgroup><col class="col0">
        </colgroup><tbody>
          <tr class="row0">
            <td class="column0 style0 s">HEAD</td>
          </tr>
          <tr class="row1">
            <td class="column0 style0 s">BODY</td>
          </tr>
    </tbody></table>
```
### What features do you think are causing the issue

- [x ] Writer

In the writer

in line 

https://github.com/PHPOffice/PhpSpreadsheet/blob/3e8d50547c0b7a8acf9352834b3e9155a86210b3/src/PhpSpreadsheet/Writer/Html.php#L405

405 to 406 I can modify the values and set

        $tbodyStart = $rowMin = 2;
        $theadStart = $theadEnd = 1;

But I would like a method to choose the current behavior or assume the first row in the xlsx file is a thead.

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

xlsx

### Which versions of PhpSpreadsheet and PHP are affected?

Lastest

**Comment by oleibman** [comment]
PhpSpreadsheet will generate `thead` (with `th` tags)  if "rows to repeat at top" is set for the worksheet's page setup, e.g.
```php
$sheet->getPageSetup()->setRowsToRepeatAtTop([1, 1]);
```
The first item in the array is the start row for the header (starting with 1), and we act on that setting only if its value is 1. The second item in the array is the last row in the header. BTW, there is some slight confusion in your message - `thead` is a separate child of `table`, not of `tbody`.

**Comment by Martin82sf** [comment]
Thanks @oleibman !!!

It works.

I let a little code for is sometime someone needs it.

```php

$xlsxName = 'basic.xlsx';

require $_SERVER['DOCUMENT_ROOT']. '/vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Writer\Html;

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$excel = $reader->load($xlsxName);

$worksheet = $excel->getSheet(0);
$worksheet->getPageSetup()->setRowsToRepeatAtTop(array(1,1)); 

$writer = IOFactory::createWriter($excel, 'Html');
$writer->setSheetIndex(0);

echo $writer->generateSheetData();
```


I close this issue.
