### ISSUE TITLE
Unmerge cells removes content

### ISSUE THREAD

**Issue by peterrehm** [PHPOffice/PhpSpreadsheet#3065]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

When unmerging cells in Excel, the content of the cells is preserved. Attached is the original file where I have merged 
cells and the content is not in the main cell. Unmerging it shows the colored cells and the content when using excel.

### What is the current behavior?

The background color is preserved, not the content.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

        $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($fileName);

        $sheetNames = $spreadsheet->getSheetNames();

        foreach ($sheetNames as $sheetName) {
            foreach ($worksheet->getMergeCells() as $cells) {
                $worksheet->unmergeCells($cells);
            }
        }

        $writer = new Xlsx($spreadsheet);
        $writer->save(__DIR__ . '/../../file_output.xlsx');

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

```
- [X] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements
```

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

[file_original.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9567585/file_original.xlsx)
[file_output_unmerged_phpspreadsheet.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9567586/file_output_unmerged_phpspreadsheet.xlsx)
[file_unmerged_excel.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9567587/file_unmerged_excel.xlsx)
Unmerg
### Which versions of PhpSpreadsheet and PHP are affected?
PHP 8.1 and phpspreadsheet 1.24.1

**Comment by MarkBaker** [comment]
When cells are merged using MS Excel, only the top left cell in the merge range retains any value

![image](https://user-images.githubusercontent.com/770298/190265054-4bdeac01-d0ad-4511-a356-afc720ca1246.png)

So how did you create an xlsx spreadsheet file that retains the values in other cells within that merge range?

**Comment by peterrehm** [comment]
Thanks for the very fast response. I got that through an Excel Export of an application.

**Comment by MarkBaker** [comment]
It's certainly non-standard for an Xlsx file; I'm currently trying to recreate it using the standard Spreadsheet applications that can be used to generate Xlsx files

I know that OpenOffice allows cell values (other than the top-left cell) to be retained or removed when merging cells; but OO doesn't support saving to Xlsx.
LibreOffice 7.4 also seems to support that feature, and will save as Xlsx to create a file similar to your own where the cells can be unmerged to show their original content.

**Comment by MarkBaker** [comment]
> Thanks for the great analysis - would be awesome if you could find any solution.
> Let me know if I can help.

Probably just testing against the latest master branch
