### ISSUE TITLE
Prevent raise error while loading xml

### ISSUE THREAD

**Issue by GhasemGoli** [PHPOffice/PhpSpreadsheet#3067]
https://github.com/PHPOffice/PhpSpreadsheet/blob/a846a93f52eb9eba66bf1f41b5d7a0f37c874422/src/PhpSpreadsheet/Settings.php#L124

```php
return self::$libXmlLoaderOptions | LIBXML_NOERROR |  LIBXML_ERR_NONE;
```

**Comment by MarkBaker** [comment]
Why not simply call `setLibXmlLoaderOptions()` with the value that you want before doing your load?
