### ISSUE TITLE
Code explodes when inserting a column in ALL the DefinedNames example files

### ISSUE THREAD

**Issue by savilaj** [PHPOffice/PhpSpreadsheet#3076]
In all of the DefinedNames example files, inserting a column before column B causes the code to explode.
For example in DefinedNames/AbsoluteNamedRange.php
insert a column between column A and B at the end of the spreadsheet generation fails and the NamedRange get out of control.

.....
        ->setCellValue("B{$row}", $hours)
        ->setCellValue("C{$row}", "=B{$row}*CHARGE_RATE");
    ++$row;
}
$endRow = $row - 1;

++$row;
$worksheet
    ->setCellValue("B{$row}", "=SUM(B{$startRow}:B{$endRow})")
    ->setCellValue("C{$row}", "=SUM(C{$startRow}:C{$endRow})");

$worksheet->insertNewColumnBefore('B');  <------------------------ line inserted
.....

the code explodes with error in cell coordinate.

**Comment by MarkBaker** [comment]
Resolved in `1.25.0`
