### ISSUE TITLE
Xlsx Writer problem with Vapor

### ISSUE THREAD

**Issue by brunomcpena** [PHPOffice/PhpSpreadsheet#3079]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Download the spreadsheet.

### What is the current behavior?
Vapor returns "Internal server error".
It works locally.

AWS Log: 
Fatal error: Uncaught Exception: Error encoding runtime JSON response: Malformed UTF-8 characters, possibly incorrectly encoded in /var/task/vendor/laravel/vapor-core/src/Runtime/NotifiesLambda.php:49

Stack trace:
#0 /var/task/vendor/laravel/vapor-core/src/Runtime/NotifiesLambda.php(19): Laravel\Vapor\Runtime\LambdaRuntime->lambdaRequest('http://127.0.0....', Array)
#1 /var/task/vendor/laravel/vapor-core/src/Runtime/LambdaRuntime.php(53): Laravel\Vapor\Runtime\LambdaRuntime->notifyLambdaOfResponse('9701efbf-d000-4...', Array)
#2 /var/task/fpmRuntime.php(88): Laravel\Vapor\Runtime\LambdaRuntime->nextInvocation(Object(Closure))
#3 /var/task/runtime.php(36): require('/var/task/fpmRu...')
#4 /opt/bootstrap.php(6): require('/var/task/runti...')

### What are the steps to reproduce?

```php
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="filename.xlsx"');
$writer->save('php://output');
```

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Xlsx (I tried with Csv and it worked)

### Which versions of PhpSpreadsheet and PHP are affected?
I'm using PHP 7.4.30, Laravel Framework 8.83.23 and PhpSpreadsheet 1.24.1

**Comment by MarkBaker** [comment]
So why do you think this is a problem with PhpSpreadsheet? And not a problem with Vapor (whatever Vapor is)? Your stack trace shows nothing of PhpSpreadsheet?
