### ISSUE TITLE
`1.25.0` regression: `ezyang/htmlpurifier` composer dependency can not be installed

### ISSUE THREAD

**Issue by BrokenSourceCode** [PHPOffice/PhpSpreadsheet#3085]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

This regression is due to https://github.com/PHPOffice/PhpSpreadsheet/commit/a3921d20bc5c9a2ba6add05ad96fb41f873e36bd. The caret version range `^` is missing (https://getcomposer.org/doc/articles/versions.md#caret-version-range-).

### What is the expected behavior?

The `ezyang/htmlpurifier` (v4.16) composer dependency should be installable.

### What is the current behavior?

The `ezyang/htmlpurifier` (v4.16) composer dependency is not installable.

### What are the steps to reproduce?

`composer.json`:
```json
{
	"require": {
		"ezyang/htmlpurifier": "^4.16.0",
		"phpoffice/phpspreadsheet": "^1.25.0"
	}
}
```

Error occured when running the `composer install` command:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires phpoffice/phpspreadsheet ^1.25.0 -> satisfiable by phpoffice/phpspreadsheet[1.25.0].
    - phpoffice/phpspreadsheet 1.25.0 requires ezyang/htmlpurifier 4.15 -> found ezyang/htmlpurifier[v4.15.0] but it conflicts with your root composer.json require (^4.16.0).
```

### Which versions of PhpSpreadsheet and PHP are affected?

v1.25.0

**Comment by MarkBaker** [comment]
Thanks
