### ISSUE TITLE
Fatal error after upgrade to 1.25.0

### ISSUE THREAD

**Issue by webard** [PHPOffice/PhpSpreadsheet#3087]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the current behavior?

```
PHP Fatal error:  Declaration of Maatwebsite\Excel\Cache\MemoryCache::get($key, $default = null) must be compatible with Psr\SimpleCache\CacheInterface::get(string $key, mixed $default = null): mixed in /var/www/html/vendor/maatwebsite/excel/src/Cache/MemoryCache.php on line 62

   Symfony\Component\ErrorHandler\Error\FatalError 

  Declaration of Maatwebsite\Excel\Cache\MemoryCache::get($key, $default = null) must be compatible with Psr\SimpleCache\CacheInterface::get(string $key, mixed $default = null): mixed

  at vendor/maatwebsite/excel/src/Cache/MemoryCache.php:62
     58▕ 
     59▕     /**
     60▕      * {@inheritdoc}
     61▕      */
  ➜  62▕     public function get($key, $default = null)
     63▕     {
     64▕         if ($this->has($key)) {
     65▕             return $this->cache[$key];
     66▕         }


   Whoops\Exception\ErrorException 

  Declaration of Maatwebsite\Excel\Cache\MemoryCache::get($key, $default = null) must be compatible with Psr\SimpleCache\CacheInterface::get(string $key, mixed $default = null): mixed

  at vendor/maatwebsite/excel/src/Cache/MemoryCache.php:62
     58▕ 
     59▕     /**
     60▕      * {@inheritdoc}
     61▕      */
  ➜  62▕     public function get($key, $default = null)
     63▕     {
     64▕         if ($this->has($key)) {
     65▕             return $this->cache[$key];
     66▕         }
```

### What are the steps to reproduce?

Just update to latest version.

### Which versions of PhpSpreadsheet and PHP are affected?

1.25.0

**Comment by joostdebruijn** [comment]
Please see: https://github.com/SpartnerNL/Laravel-Excel/pull/3733

**Comment by fiyuang** [comment]
I got similar error on Laravel 9, it because of the simple-cache dependency, you will have to specify the psr/simple-cache version as ^2.0 in your composer.json. Just try this command:

`composer require psr/simple-cache:^2.0 maatwebsite/excel`

Source from: https://docs.laravel-excel.com/3.1/getting-started/installation.html

**Comment by JeanErnest** [comment]
tank bro

**Comment by jarwonozt** [comment]
> I got similar error on Laravel 9, it because of the simple-cache dependency, you will have to specify the psr/simple-cache version as ^2.0 in your composer.json. Just try this command:
> 
> `composer require psr/simple-cache:^2.0 maatwebsite/excel`
> 
> Source from: https://docs.laravel-excel.com/3.1/getting-started/installation.html

yes that's right, it turns out that you have to install this package, tanks

**Comment by miyanda31** [comment]
In case anyone is still facing this issue, just disable psr in your cpanel if you are in production. I have attached a photo
![Uploading Screenshot (269).png…]()
