### ISSUE TITLE
Allowed memory size of xxx bytes exhausted with a small file

### ISSUE THREAD

**Issue by katsar0v** [PHPOffice/PhpSpreadsheet#3088]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
To convert a specific sheet from an xls file to csv

### What is the current behavior?
Throws an error

### What are the steps to reproduce?

I have the following function

```php
    public static function convert_xls_to_csv($xls_file_path, $sheet_name, $csv_file)
    {
        $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
        $reader->setLoadSheetsOnly([$sheet_name]);
        $spreadsheet = $reader->load($xls_file_path);

        $writer = new PhpSpreadsheet\Writer\Csv($spreadsheet);
        $writer->save($csv_file);
    }
```
and an 8MB .xls file with 10+ sheets. However `Allowed memory size of xxx bytes exhausted` error is thrown, e.g.:
```
Allowed memory size of 576716800 bytes exhausted (tried to allocate 4096 bytes) in ....../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 104
```

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
`1.24.1`

**Comment by MarkBaker** [comment]
A small file does not necessarily mean a small number of cells; and remember that an Excel cell may contain an empty string, or a null value, or a formula that evaluates to these, so isn't necessarily visible when you look at the file in MS Excel itself.

**Comment by katsar0v** [comment]
Ah okay, there are empty cells and around 30k lines, what can I do about it?

**Comment by MarkBaker** [comment]
```
$reader->setReadEmptyCells(false);
```

**Comment by katsar0v** [comment]
Thanks, life saver!
