### ISSUE TITLE
[BUG] Failed to load as a DOM Document from View export

### ISSUE THREAD

**Issue by mendizalea** [PHPOffice/PhpSpreadsheet#3089]
I have an export of a view in laravel in which I have a table with an SVG image and it gives an error: Failed to load as a DOM Document

**Comment by oleibman** [comment]
I would need to see the spreadsheet and/or code in question.

**Comment by fikurimax** [comment]
I already figured out what could be the problem if I get this error. It's related to HTML code such as
```html
<tdstyle="......">data</td>
```
in that code HTML cant be parsed because there is a wrong tag. So in ur case maybe it's related to SVG tags

**Comment by oleibman** [comment]
Closing. Almost a year old, and still nothing uploaded that would allow the problem to be debugged.

**Comment by jadamec** [comment]
Any updates on this? Still it's not possible to export from View when online SVG is present.

**Comment by oleibman** [comment]
No sample file, therefore no update. Please open a new ticket, with a file, if you want it investigated further.
