### ISSUE TITLE
Allow creating drawings from strings or streams

### ISSUE THREAD

**Issue by rimas-kudelis** [PHPOffice/PhpSpreadsheet#3101]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

It would be great if PhpSpreadsheet allowed to create Drawings not just from files in the file system, but from streams and/or strings as well.

This would help in cases when the file in question is stored not locally, but on the cloud, or in a filesystem abstraction such as FlySystem. It seems like right now, if an image is stored in FlySystem for example, it has to be downloaded and stored locally to be available for inclusion. It would be great if that step of storing it locally (and cleaning up afterwards) could be skipped.

**Comment by MarkBaker** [comment]
Closed by [PR #3157](https://github.com/PHPOffice/PhpSpreadsheet/pull/3157) in 1.26.0
