### ISSUE TITLE
CellRange trimmed if from and to is equal, result in auto filter errors 

### ISSUE THREAD

**Issue by brainfoolong** [PHPOffice/PhpSpreadsheet#3102]
This is:

```
- [x] a bug report
```

I have found this line:
https://github.com/PHPOffice/PhpSpreadsheet/blob/88bbac9849cea9642c874e6ca2bd29ee81f99910/src/PhpSpreadsheet/Cell/CellRange.php#L127

Which effectively convert a range into a single cell, which then causes errors in other functions that explicitely require a range cell name, even of the range consists of just one field.

So the result is, i cannot set AutoFilter with a range of one cell and it will throw an error

Cell get's converted here (__toString is called):
https://github.com/PHPOffice/PhpSpreadsheet/blob/88bbac9849cea9642c874e6ca2bd29ee81f99910/src/PhpSpreadsheet/Worksheet/Validations.php#L32

Error thrown here
https://github.com/PHPOffice/PhpSpreadsheet/blob/88bbac9849cea9642c874e6ca2bd29ee81f99910/src/PhpSpreadsheet/Worksheet/AutoFilter.php#L127

Filter isset with:
https://github.com/PHPOffice/PhpSpreadsheet/blob/88bbac9849cea9642c874e6ca2bd29ee81f99910/src/PhpSpreadsheet/Worksheet/Worksheet.php#L2143

The current workaround is to use `setAutoFilter` instead of `setAutoFilterByColumnAndRow` and providing a string range.

**Comment by MarkBaker** [comment]
I hate to ask, but why would you set autofilter on a single cell?

**Comment by brainfoolong** [comment]
Thanks for answer. To provide a interface where the user can filter, sort, etc... without the need to do anything. It's valid for just one column, or more. Anyway, a single cell works when using `setAutoFilter`, it's just not working with `setAutoFilterByColumnAndRow`.

**Comment by brainfoolong** [comment]
It created that for the user, which is pretty handy, even on a single column.

![image](https://user-images.githubusercontent.com/1684236/193568597-b99af6fb-c1e6-46d5-acf2-25d09f17ab60.png)

**Comment by MarkBaker** [comment]
I'm still not sure that I understand the case for this: I'm trying to create a single cell autofilter in MS Excel itself, but it always seems to adjust it to the full data range

You are also aware that the `*byColumnAndRow()` methods are deprecated?

**Comment by brainfoolong** [comment]
Hm. Ok. That `*byColumnAndRow()` is deprecated is new to me. Seems that PhpStorm doesn't check that when `@Depreceted` where it's `D` is uppercase. Werid :)

Thanks for that excel info. Our internal use cases and codes always only used setAutoFilter with a single row and 1 or X columns. So we can have zero or more rows after.

So we have, for example, to mark row 1 as auto filter, with given numer of columns:
```
setAutoFilterByColumnAndRow(1, 1, 1, 1);
setAutoFilterByColumnAndRow(1, 1, 3, 1);
setAutoFilterByColumnAndRow(1, 1, 9, 1);
```

This always worked perfectly fine. However, the case with only one column is indeed pretty rare and can only be when user do some weird settings on the reports. But we never provide more then one row... 

Are we doing this wrong, ever since? We have hundreds of phpspreadsheet reports using it like that.

**Comment by brainfoolong** [comment]
I have also tested in my excel, and no errors appear when using a filter settings for that.
Is auto filter in phpspreadsheet not just doing that?

See animation:

![screeny](https://user-images.githubusercontent.com/1684236/193570819-84a8f67a-1442-4b99-aedd-887894b2fe83.gif)

**Comment by MarkBaker** [comment]
Defining an AntoFilter in PhpSPreadsheet has always assumed a range of cells, but only ever validated that the provided string matched the expected pattern for a range. I'd never even considered that range might be `E4:E4`, and I suspect that would break a few of the AutoFilter methods if you tried setting filter values for that range.
It was purely oversimplistic validation that allowed a single cell range to be applied in the first place.

MS Excel actually stores this as a cell reference, and not as a range reference; so it stored `E4`, and not `E4:E4`.

But if I remove that validation check, and allowed a single cell reference to match MS Excel, then I see that it will break a few things in the `save()`, because we also created DefinedNames for the range, and that expects an actual range.

**Comment by brainfoolong** [comment]
Ok, i understand. So, what is your advice on how i should do it? Should i do it, the way i do, defining a range `E4:E4` by hand, to overcome the check in autofilter?

**Comment by brainfoolong** [comment]
Great. Thanks for your replies.

**Comment by MarkBaker** [comment]
If you want to do some testing, take a look at https://github.com/PHPOffice/PhpSpreadsheet/pull/3111

**Comment by brainfoolong** [comment]
Thanks for the fast respond and code fixes. Unfortunetely i don't have time to test those changes.
