### ISSUE TITLE
Modifying a formula when keeping cell from an iterator change another cell value

### ISSUE THREAD

**Issue by alarai** [PHPOffice/PhpSpreadsheet#3103]
This is:

- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?

There should be no change to the files cell except to the formula. In this example case the formula is not actually updated just set again to the same value.
The expected result is : 
<img width="365" alt="lica_good" src="https://user-images.githubusercontent.com/7099355/193754422-1cf5b313-75d8-436b-b89c-02a219a3b35f.png">

### What is the current behavior?

The file is changed and one other cell has it's content replaced by the formula.
This is what the wrong result looks like : 
<img width="316" alt="lica_bad" src="https://user-images.githubusercontent.com/7099355/193754498-15c77142-cdf3-4439-b4a9-48b461dbfe35.png">

As far as I can tell there is indeed a single setValue call from the processCellFormula function, and the iteration ony find one formula cell.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require("vendor/autoload.php");

function processCellFormula($cell) {
    $formula = $cell->getValue();
    $formula = str_replace('[0]!', '', $formula);
    $cell->setValue($formula);
}

$xlsxReader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
$workbook = $xlsxReader->load('test_lica.xlsx');    

$formulaCells = [];

$doItInForeach = false;


foreach ($workbook->getWorksheetIterator() as $worksheet) {
    foreach ($worksheet->getRowIterator() as $row) {
        $cellIterator = $row->getCellIterator();
        $cellIterator->setIterateOnlyExistingCells(true);
        foreach ($cellIterator as $cell) {
            if ($cell->isFormula()) {                    
                $formulaCells[] = $cell;  
                if ($doItInForeach) {                        
                    processCellFormula($cell);
                }
            }
        }
    }
}

if (!$doItInForeach) {    
    foreach($formulaCells as $formulaCell) {
        processCellFormula($formulaCell);        
    }
}

$writer = new  \PhpOffice\PhpSpreadsheet\Writer\Xlsx($workbook);
$writer->save('lica.xlsx');
```
The test file is provided as an attachment : [test_lica.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9703255/test_lica.xlsx)

The issue seems to happen only when storing the formulaCells and doing something with them later. 
In my real use case (not the test above) I'm doing several things before modifying the formulas if I need, as I've had to browse the cells for a previous step I would like to avoid going through all the cells a second time by keeping them stored for the time I need them.

In this test case if you switch the boolean for $doItInForEach to true the result will be correct, although logically there should not be a difference between both version. In both cases there is only one formula in the example file, and it will modify a non formula cell without reason, if not doing it right when doing the cell iteration.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [X] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

Tested and reproduced on XLSX and ODS files.

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet version 1.16 and above example is not working on earlier versions.
Tested with PHP 7.3.1, 8.1.0 and 8.1.11

**Comment by MarkBaker** [comment]
Only one cell is ever in memory at a time: what you store isn't the cell object, it is a pointer to the current active cell object. if you store a cell object in a variable `$a`, then the next cell that you access will become the current active cell, and your pointer `$a` will now point to the cell object that you are currently accessing, overriding the cell object that you thought you had stored.

THIS IS NOT A BUG !!

If you have to save a cell, don't save the cell object, save a value that can be used to retrieve that cell, such as the cell address.
```
foreach ($workbook->getWorksheetIterator() as $worksheet) {
    foreach ($worksheet->getRowIterator() as $row) {
        $cellIterator = $row->getCellIterator();
        $cellIterator->setIterateOnlyExistingCells(true);
        foreach ($cellIterator as $cell) {
            if ($cell->isFormula()) {                    
                $formulaCells[] = ['worksheet' => $worksheet, 'cell' => $cell->getCoordinate()];  
                if ($doItInForeach) {                        
                    processCellFormula($cell);
                }
            }
        }
    }
}

if (!$doItInForeach) {    
    foreach($formulaCells as $formulaCell) {
        $cell = $workbook->getSheetByName($formulaCell['worksheet'])->getCell($formulaCell['cell']);
        processCellFormula($cell);
    }
}
```
