### ISSUE TITLE
Style apply to all the column rather than the specified cell

### ISSUE THREAD

**Issue by 411x** [PHPOffice/PhpSpreadsheet#3106]
### Discussed in https://github.com/PHPOffice/PhpSpreadsheet/discussions/3105

<div type='discussions-op-text'>

<sup>Originally posted by **411x** October  5, 2022</sup>
I'm trying to create a first row with 3 different coloured cells. But the colour is applied to the whole column. I just want the style on the specified cell. How can I achieve this?

```
$spreadsheet = new Spreadsheet();

$sheet = $spreadsheet->getActiveSheet();

$sheet->setCellValue('A1', 'N')
      ->setCellValue('B1', 'Name')
      ->setCellValue('C1', 'Firstname');

$sheet->getStyle('A1')->getFill()
    ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
    ->getStartColor()->setARGB('FFFF00');

$sheet->getStyle('B1')->getFill()
    ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
    ->getStartColor()->setARGB('00b0f0');

$sheet->getStyle('C1')->getFill()
    ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
    ->getStartColor()->setARGB('a8d08d');


for ($i = 1; $i <= 10; $i++) {
    $row = $sheet->getHighestRow()+1;
    $sheet->insertNewRowBefore($row);
    $sheet->setCellValue('A'.$row, $i);
}

$writer = new Xlsx($spreadsheet);
$writer->save('hello world.xlsx');
```

Result : [https://i.imgur.com/nrthnfq.png](https://i.imgur.com/nrthnfq.png)</div>

**Comment by MarkBaker** [comment]
Insert the new rows before setting the style in the individual cells

**Comment by MarkBaker** [comment]
And for better code efficiency; don't insert a single row 10 times; tell PhpSpreadsheet to insert 10 rows once:
```php
$row = $sheet->getHighestRow()+1;
$sheet->insertNewRowBefore($row, 10);
```
The `insertNewRowBefore()` method is very compute intensive; this way, you only do that compute once, not ten times

**Comment by oleibman** [comment]
My comment in #3105 was wrong; PhpSpreadsheet is working as Excel does. Sorry for the misinformation.

**Comment by MarkBaker** [comment]
MS Excel inherits style from the cells immediately above when inserting a new row; PhpSpreadsheet replicates this behaviour. We could perhaps add a new boolean argument for the method:
```php
public function insertNewRowBefore(int $before, int $numberOfRows = 1, bool $copyPreviousRowStyle = true);
```
