### ISSUE TITLE
Wrong priority for conditional formatting rules

### ISSUE THREAD

**Issue by adrian-esc** [PHPOffice/PhpSpreadsheet#3107]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The conditional formatting rules are in the same order as in the source file

### What is the current behavior?
The conditional formatting rules are sorted by row - A, B, C, D, E...

### What are the steps to reproduce?

1. Prepare a file in MS Excel that will be read by Reader.
2. The file should have the conditional rules in the order:
- The first rule applies to the range of columns Z1 - Z10
- The second rule applies to the range of columns A1 - A10
3. Save the file with XLSX Writer.
4. Open the file in MS Excel, the conditional rules will be in order:
- The first rule applies to the range of columns A1 - A10
- The second rule applies to the range of columns Z1 - Z10

### **My quick fix for this issue:**
```
src/PhpSpreadsheet/Reader/Xlsx/ConditionalStyles.php:
private function readConditionalStyles(SimpleXMLElement $xmlSheet): array
    {
        $conditionalsRaw = [];
        $conditionals = [];

        foreach ($xmlSheet->conditionalFormatting as $conditional) {
            foreach ($conditional->cfRule as $cfRule) {
                if (Conditional::isValidConditionType((string) $cfRule['type']) && isset($this->dxfs[(int) ($cfRule['dxfId'])])) {
                    $conditionalsRaw[(int) $cfRule['priority']][(string) $conditional['sqref']][(int) ($cfRule['priority'])] = $cfRule;
                } elseif ((string) $cfRule['type'] == Conditional::CONDITION_DATABAR) {
                    $conditionalsRaw[(int) $cfRule['priority']][(string) $conditional['sqref']][(int) ($cfRule['priority'])] = $cfRule;
                }
            }
        }

        ksort($conditionalsRaw);
        foreach ($conditionalsRaw as $conditional) {
            $key = array_key_first($conditional);
            $conditionals[$key] = $conditional[$key];
        }

        return $conditionals;
    }

```

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
XLSX

### Which versions of PhpSpreadsheet and PHP are affected?
1.25.2

**Comment by MarkBaker** [comment]
Can I ask why this should make a difference?

**Comment by adrian-esc** [comment]
I thought that if a user enters the rules in a particular order, he would like to keep that order all the time. The fix shouldn't cause any problems, and the rule entered first will always remain first. 

I don't add anything new to this feature. I just sort the array by priority.
Would there be a chance to add this fix to PhpSpreadsheet?

**Comment by MarkBaker** [comment]
But if there are 3 rules for cell 'A1', at priority 1, 2 and 3 respectively? How many rules will be returned in `$conditionals`? Your logic is only returning the single highest priority rule for the cell, losing the lower priority rules completely.

I'd suggest that it's more important to return all three rules than to "lose" rules completely

**Comment by adrian-esc** [comment]
In my test file, all rules had unique priority, so I used this "simple" sorting. 
I will check it and come back with an answer.
