### ISSUE TITLE
HTML writer <meta> generator

### ISSUE THREAD

**Issue by criztovyl** [PHPOffice/PhpSpreadsheet#312]
This is:

```
- [ ] a bug report
- [x] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

The produced HTML includes a PhpSpreadsheet as a generator.

### What is the current behavior?

It's only included as a HTML comment.

https://github.com/PHPOffice/PhpSpreadsheet/blob/4f1fae529856bb0608a970b3c179fd4f59b163f0/src/PhpSpreadsheet/Writer/Html.php#L355

**Comment by PowerKiKi** [comment]
Sounds like a good idea, [according to spec](https://www.w3.org/TR/html5/document-metadata.html#generator). I'd accept a PR for that.

It should not include the version (too hard to get it right for little benefits), but it should contains either the project name, the package name or the URL. I am not sure which would make more sense...

- `PhpSpreadsheet`
- `phpoffice/phpspreadsheet`
- `https://github.com/PHPOffice/Spreadsheet`

?

**Comment by criztovyl** [comment]
I'd vote for the second, although the first one meight already be unique enough. I just like the `creator/package` notation.

**Comment by PowerKiKi** [comment]
OK for me
