### ISSUE TITLE
SUMIF is not working

### ISSUE THREAD

**Issue by gsigmund** [PHPOffice/PhpSpreadsheet#313]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I have a simple SUMIF and it should have the same result as the excel file produces

### What is the current behavior?
It returns a value of 0

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: geraldsigmund
 * Date: 21.05.15
 * Time: 21:46
 */

require 'vendor/autoload.php';


try {
    $inputFileType = \PhpOffice\PhpSpreadsheet\IOFactory::identify("c:\\Temp\\test.xlsx");
    $objReader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($inputFileType);
    $objSpreadsheet = $objReader->load("c:\\Temp\\test.xlsx");
} catch(Exception $e) {
    die('Error loading file');
}

$sheet = $objSpreadsheet->getSheet(0);
    $rowData = $sheet->rangeToArray('A1:A1',
        null,
        true,
        false);

    print_r($rowData);



?>


### Which versions of PhpSpreadsheet and PHP are affected?
1.0.0, 7.0
[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1598753/test.xlsx)

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue without relying on an external Excel file.

And don't forget to mention what version of this project you are using.
