### ISSUE TITLE
Method applyFromArray() throws undefined exception

### ISSUE THREAD

**Issue by realtec** [PHPOffice/PhpSpreadsheet#314]
This is:

```
- [X] a bug report
```

### What is the expected behavior?
Expecting the method to throw an existing exception class

### What is the current behavior?
Doc block is wrong
Throwing an undefined class

### Which versions of PhpSpreadsheet and PHP are affected?
1.0.0

The following function `PhpOffice\PhpSpreadsheet\Style\Style::applyFromArray()` throws an Exception class without namespace, PHP will use the current namespace which doesn't contain the class Exception.
```
/**
* ...
* @throws Exception
*
* @return Style
*/
public function applyFromArray(array $pStyles, $pAdvanced = true)
{
    // ...
}
```

**Comment by PowerKiKi** [comment]
Is this only the docblock, or did you actually see an error when running code ?

**Comment by realtec** [comment]
Haven't seen an error while running the code, was only a docblock issue.
