### ISSUE TITLE
MATCH() match type smallest value has inferior handling of numeric types than greatest or equal matches

### ISSUE THREAD

**Issue by Natrak** [PHPOffice/PhpSpreadsheet#3141]
matchSmallestValue does not have any extra handling to make sure double and integer types are treated as matchable.
`            $typeMatch = gettype($lookupValue) === gettype($lookupArrayValue);
`

Both matchFirstvalue and matchLargestValue use:
`            $typeMatch = ((gettype($lookupValue) === gettype($lookupArrayValue)) ||
                (is_numeric($lookupValue) && is_numeric($lookupArrayValue)));
`

This results in the matcher for matchSmallestValue skipping valid comparisons when one of the values is an integer and the other a double.

I had no problems just reusing the logic from the other matching functions.

**Comment by MarkBaker** [comment]
It isn't quite so straightforward, because we can't then use the same comparison for numerics and non-numeric strings; but I'll take a look and see how best we can do that check

**Comment by oleibman** [comment]
@MarkBaker I've looked and I think I have something that will work. I believe the logic in matchFirstValue is also not correct.
