### ISSUE TITLE
Generated Excel file loses page breaks when prininting area does not start in the first column

### ISSUE THREAD

**Issue by alarai** [PHPOffice/PhpSpreadsheet#3143]
This is:

```
- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

The Printing configuration should be kept after saving the document.

### What is the current behavior?

When the printing area does not start on the first column, the page breaks disappears or ar return to automatic ones.

### What are the steps to reproduce?

This simple code allows to test the case, it just opens the file and save it without modification. 
The [area_ko.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9870198/area_ko.xlsx) gives the following result (left is the original file, right is after opening and saving it with PhpSpreadsheet.)
![image](https://user-images.githubusercontent.com/7099355/198047326-c3acbc83-5de5-4fab-ad01-a2799b3300cd.png)

The [area.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/9870241/area.xlsx) file is the same case just with the printing area set to start on the first column, and works as expected 
![image](https://user-images.githubusercontent.com/7099355/198048020-4fb134c4-5459-42ee-a278-7838de825b1a.png)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Load the file
$xlsxReader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
$workbook = $xlsxReader->load('area.xlsx');    
//$workbook = $xlsxReader->load('area_ko.xlsx');    

// Save the file
$writer = new  \PhpOffice\PhpSpreadsheet\Writer\Xlsx($workbook);
$writer->save('result.xlsx');
```

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by oleibman** [comment]
When I look at the xml in area_ko, the difference between the original and the version generated by PhpSpreadsheet is that the original `brk` tag includes the attribute `max="16383"` and the PhpSpreadsheet file does not. Furthermore, when I add that tag to the PhpSpreadsheet version, the spreadsheet is now as expected. What surprises me is that exactly the same difference occurs between the two versions of area.xlsx, but now it is not necessary to add the new attribute. I imagine it is not a problem to always add it, but I need to think about it some more. FWIW, the documentation on that attribute says "Zero-based index of end row or column of the break. For row breaks, specifies column index; for column breaks, specifies row index". There is also an analogous `min` parameter; based on your analysis of the problem, it makes more sense to me to set that, but setting that to 1 breaks the spreadsheet, and setting it to 0 doesn't break it but also doesn't fix the problem.
