### ISSUE TITLE
SimpleXMLElement::addChild(): unterminated entity reference &quot;Col&quot;)),1)

### ISSUE THREAD

**Issue by zappzerapp** [PHPOffice/PhpSpreadsheet#3145]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Read the xlsx file with multiple sheets and dropdown-values, also with formulas including quotations

### What is the current behavior?
```php
ErrorException
SimpleXMLElement::addChild(): unterminated entity reference &quot;Col&quot;)),1)
vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:938
```

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$file = __DIR__ . DIRECTORY_SEPARATOR . 'reproduce.xlsx';
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($file);
$spreadsheet = $reader->load($file);
```

### What features do you think are causing the issue

- [X] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
XSLX

### Which versions of PhpSpreadsheet and PHP are affected?
- 1.25.2
- master

**Comment by oleibman** [comment]
Closing. Should be fixed by PR #3146.
