### ISSUE TITLE
Docs typos on Accessing Cells page.

### ISSUE THREAD

**Issue by GreeKatrina** [PHPOffice/PhpSpreadsheet#315]
On the Accessing Cells page, under the [Setting a cell value by column and row](http://phpspreadsheet.readthedocs.io/en/develop/topics/accessing-cells/#setting-a-cell-value-by-column-and-row) section, it has:

> ```php
> // Set cell B5 with a string value
> $spreadsheet->getActiveSheet()->setCellValueByColumnAndRow(1, 5, 'PhpSpreadsheet');;
> ```
> Note that column references start with **1** for column **A**.

The comment should say `//Set cell A5 with a string value`, not `B5`.

Also, `from` is misspelled as `fom` multiple times in the [Retrieving a cell value by column and row](http://phpspreadsheet.readthedocs.io/en/develop/topics/accessing-cells/#retrieving-a-cell-value-by-column-and-row) and [Retrieving a cell value by coordinate](http://phpspreadsheet.readthedocs.io/en/develop/topics/accessing-cells/#retrieving-a-cell-value-by-coordinate) sections.

**Comment by PowerKiKi** [comment]
Thanks for reporting !
