### ISSUE TITLE
Possible error in writer

### ISSUE THREAD

**Issue by dabrjn** [PHPOffice/PhpSpreadsheet#3150]
phpspreadsheet xlsx appears to be writing out a unicode 2033 (double prime ″) as unicode 201d (closing double curly ”). I know it happens in 1.18 and don't see any mention of any fix in newer change logs.

**Comment by oleibman** [comment]
Do you have a sample program or spreadsheet where this is happening?

**Comment by dabrjn** [comment]
It turns out this was not a phpSpreadsheet error but rather a macOS
Monterrey error which is now fixed in MacOS Ventura. You may delete or
close the issue. Sorry to have troubled you.

david bergman
