### ISSUE TITLE
[Feature] counting number of rows

### ISSUE THREAD

**Issue by oleg-andreyev** [PHPOffice/PhpSpreadsheet#3151]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Would be awesome that have some "count" method without loading entire file.
At least for `xlsx` it's possible by `\count($xmlSheetNS->sheetData->row)`

### What is the current behavior?
Need to load entire file to count.

**Comment by MarkBaker** [comment]
Have you looked at the Reader's `listWorksheetInfo()`? What doesn't it provide that you need?
