### ISSUE TITLE
[Bug] @Deprecated annotations are not used by IDEs to show warnings

### ISSUE THREAD

**Issue by nicolanrizzo** [PHPOffice/PhpSpreadsheet#3162]
This is:

```
- [X ] a bug report
- [ ] a feature request
- [X ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
IDEs show warnings for deprecated methods (like `setCellValueByColumnAndRow`).

### What is the current behavior?
IDEs do not show warnings for deprecated methods.

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
// the method in the next line should be marked deprecated by IDEs, but it's not
$sheet->setCellValueByColumnAndRow(1, 1, 'test');
```

### What features do you think are causing the issue

The annotation `@Deprecated` does not exist. The annotation `@deprecated` should be used instead (see: https://docs.phpdoc.org/guide/references/phpdoc/tags/deprecated.html).

### Which versions of PhpSpreadsheet and PHP are affected?
The current master branch presents this issue.

**Comment by oleibman** [comment]
Although much of the work will happen in #3166, I have started to subdivide that ticket. Tickets #3174, #3175, and #3176, and four others which I will push later today, also address this problem, and my plan is to merge those before 3166.

**Comment by oleibman** [comment]
Other PRs are #3177, #3178, #3180, #3181, and #3183. I have moved 3166 to draft status - it probably won't be needed.

**Comment by oleibman** [comment]
All PR's are now merged. I will close this issue in a few days. If you have a chance to test against master, please do so.

**Comment by oleibman** [comment]
Closing. This should be fixed in master, and will be fixed for all with the next release.
