### ISSUE TITLE
Error: Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by bastien70** [PHPOffice/PhpSpreadsheet#3171]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

I want to open a large xlsx file (around of 30Mo) (around of 800K rows):

`$spreadsheet = $reader->load($path);`

### What is the current behavior?

The script is trying to load the file during 30 seconds, and after that, I've an error : 

`Error: Maximum execution time of 30 seconds exceeded`, error 500

### What are the steps to reproduce?

Just try to open xlsx file with 800K lines

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
1.25.2

**Comment by MarkBaker** [comment]
NOT A F***ING BUG!
