### ISSUE TITLE
Github Still Requires Php7.3 Unit Test

### ISSUE THREAD

**Issue by oleibman** [PHPOffice/PhpSpreadsheet#3179]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Php7.3 was recently removed as a supported environment, and a 7.3 unit test is no longer run. However, something tells Github that a successful 7.3 unit test is still required. As a result, the "squash and merge" button is grayed out, and changes cannot be merged; or, at least, I don't know any way to merge them. Until this problem is resolved, the project is effectively frozen.

**Comment by MarkBaker** [comment]
Even if I update the minimum [PHPUnit Version](https://github.com/PHPOffice/PhpSpreadsheet/pull/3182) to `9.5`, I'm still seeing that extra entry in the CI; I'll have to experiment with different dependencies to see if I can resolve what it might be, if it is one of the dependencies.

In the meanwhile, if you flag any individual PRs that are ready for merge for my attention, I can still force a merge.

**Comment by oleibman** [comment]
Thanks. PR #3163 is the only one I would like to expedite for now.

**Comment by oleibman** [comment]
Might it be possible to re-add Php7.3 unit test, except in experimental mode? Composer would fail the test because the minimum criterion for Php is no longer met, but, since it's experimental, perhaps it would appear to Github (or whoever) that it passed anyhow. I don't think this would prevent us from moving ahead with the "real" fix whenever we determine what that should be, but it would allow the break-up of the current logjam.

**Comment by MarkBaker** [comment]
Temporarily added: I wish I could figure out why CI thinks that we need 7.3
