### ISSUE TITLE
Conditionals formatting rules applied to columns are removed

### ISSUE THREAD

**Issue by sdespont** [PHPOffice/PhpSpreadsheet#3184]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When defining a conditional behavior applied to column, the conditional rules must not be automatically removed by the library.

### What is the current behavior?
The conditionals rules applied to columns are removed. All conditionals' rules based on cells number or rows are still existing and working fine.

Template file
![image](https://user-images.githubusercontent.com/646632/202402662-5571b7fd-7396-4d7c-8f82-ac1dfbde99f5.png)

After using it
![image](https://user-images.githubusercontent.com/646632/202402796-9787b471-207f-49f4-9500-6e4620ae6b55.png)

### What are the steps to reproduce?
Create an Excel file, create a conditional rule applied to columns. Load it and insert some cells contents, then save the file. The output file no longer contents the conditional rules applied to columns.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet = IOFactory::createReader('Xlsx');
$spreadsheet ->setIncludeCharts(true);
$spreadsheet  = $objReader->load($filename);

$spreadsheet  = $phpExcel->getActiveSheet();
$activeSheet->setCellValue('A1', 'ABCDE');

$writer = IOFactory::createWriter($spreadsheet , 'Xlsx');
$writer->save('path);

If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?


### Which versions of PhpSpreadsheet and PHP are affected?
1.25.2

**Comment by MarkBaker** [comment]
Unable to replicate

This is the file that I'm reading:
![image](https://user-images.githubusercontent.com/770298/202467225-515961cb-bcef-4794-8dcd-f2f0c8cdab2f.png)

[ConditionalFormat_Ranges.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/10032212/ConditionalFormat_Ranges.xlsx)

Before
![image](https://user-images.githubusercontent.com/770298/202466689-7d81f966-be62-43e0-b89e-711bef207ce1.png)

After
![image](https://user-images.githubusercontent.com/770298/202466866-79844140-d8c9-4742-bb82-9e078049bc72.png)

**Comment by sdespont** [comment]
@MarkBaker Thank you for your tests.

I have spotted the problem, try to execute `$activeSheet->insertNewRowBefore(1, 1);` before saving. The conditional rules applied to columns will be removed.

**Comment by MarkBaker** [comment]
Ah, understood; and I can see why that would cause a problem. Excel doesn't store the rule range as a row or column range (despite what it displays) but as a full cell range like `A7:XFD8`, and that's how we store it internally. Adding a new column will adjust that range to `A7:XFE8`, which exceeds Excel's column limit, so it discards the entry as invalid when it's saved and re-loaded. So I need to add some range check logic to the ReferenceHelper code that adjusts the range.

**Comment by MarkBaker** [comment]
That PR should resolve the issue for Xlsx files; but the Xls Writer has different limits; and it also breaks Xls if you have both a row range and a column range for CF ranges in the same worksheet... I've raised a separate Issue for Xls

**Comment by sdespont** [comment]
Thank you so much ! Xlsx is fine for me, I am not using Xls format for years.
