### ISSUE TITLE
Need a way to load larger spreadsheet using less memory

### ISSUE THREAD

**Issue by duprasf** [PHPOffice/PhpSpreadsheet#3186]
This is:

```
- [ ] a bug report
- [X] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When loading a spreadsheet using Worksheet::toArray() with large amount of rows, I expect to be able to get the data.

### What is the current behavior?
It crash with message that more memory is needed

### What are the steps to reproduce?
Unfortunately, I cannot share the spreadsheet I'm using, but it has 6 columns and ~1300 rows. One column is date, the other columns are text, one of those has a lot of text.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$inputFileType = IOFactory::identify($inputFileName);
$reader = IOFactory::createReader($inputFileType);

// Load only the rows that match our filter from $inputFileName to a PhpSpreadsheet Object
$spreadsheet = $reader->load($inputFileName);

foreach($spreadsheet->getActiveSheet()->rangeToArray(range:'A2:F1300', calculateFormulas:false, formatData: true, returnCellRef:false) as $key=>$cr) {
    // Add to DB...
}

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [X] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
I don't know, I only tried with an xlsx.

### Which versions of PhpSpreadsheet and PHP are affected?
Using PHP 8.1, not sure about PhpSpeadsheet, but I downloaded the latest files from composer (```composer require phpoffice/phpspreadsheet```)

### How could this be fixed?
Using Generators syntax (https://www.php.net/manual/en/language.generators.syntax.php). I will submit a pull request shortly hoping that it will be accepted.

**Comment by MarkBaker** [comment]
Do you think that perhaps `$spreadsheet->getActiveSheet()->rangeToArray(range:'A2:F1300'` might be your problem... you're building a very large 2-dimensional array with this call, that will use a lot of memory

Have you looked at using row and cell iterators instead? Try using the features that already exist in the library before requesting/adding new features.

Note that this is nothing to do with the `Reader`: that's the code which loads the spreadsheet, and which you're invoking through the IOFactory and the call to `load()`
