### ISSUE TITLE
Cell coordinates which are already a range cause an exception

### ISSUE THREAD

**Issue by MaxTingle** [PHPOffice/PhpSpreadsheet#319]
Because Coordinate::mergeRangesInCollection is now used in the the Xlsx worksheet writer for data validation and it doesn't support existing ranges you can no longer call Worksheet\Worksheet setDataValidation with a column range as it'll cause the "Cell coordinate string can not be a range of cells" exception.

https://github.com/PHPOffice/PhpSpreadsheet/blob/27d83b44045ee5e497b6fe825a00c8fc857ea306/src/PhpSpreadsheet/Cell/Coordinate.php#L405

I suggest moving the definition of $mergedCoordCollection to line 403 then skip coordinate parsing if the coord is already a range like so:

```
if (strpos($coord, ':') !== false) || (strpos($coord, ',') !== false)) {
     $mergedCoordCollection[$coord] = $value;
     continue;
}
```

**Comment by PowerKiKi** [comment]
Would you have a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue ?

**Comment by MaxTingle** [comment]
[Cell range error replication.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/1611390/Cell.range.replication.zip)

**Comment by PowerKiKi** [comment]
Thanks, I can indeed reproduce with your code. Copy/pasted here for convenience:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Cell\DataValidation;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xls;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$spreadsheet->getActiveSheet()->setDataValidation(
    'A1:A2',
    (new DataValidation())
        ->setType(DataValidation::TYPE_LIST)
        ->setShowDropDown(true)
        ->setFormula1('"A,B,C,"')
);

// XLS saving - Works with ranges as it doesn't merge cell coordinates
(new Xls($spreadsheet))->save('out.xls');

// XLSX saving - Worked with ranges before cell coordinates were merged into ranges
(new Xlsx($spreadsheet))->save('out.xlsx');
```

If you are able to submit a PR with your suggested fix and include unit tests, we might get it to be merged.
