### ISSUE TITLE
The formula =[@Асв][@eb]  is not calculated

### ISSUE THREAD

**Issue by jsden** [PHPOffice/PhpSpreadsheet#3191]
This is:

```
 a bug report
```

### What is the expected behavior?

The cell should contain the result of the formula calculation.

![image](https://user-images.githubusercontent.com/18567690/202893484-d794a3e6-bd12-4cb6-bf5b-cd95e53d9d50.png)

### What is the current behavior?

If you apply setPreCalculateFormulas(false) (disable formula pre-calculation), then after saving the saveXlsx file, we get in the saved file in this cell where the formula  =[@Асв]*[@Eb]             --------->           #LINK!*#LINK!
![image](https://user-images.githubusercontent.com/18567690/202893659-faf34dfa-58e4-4d7d-9b9f-7397786a5a13.png)

If we apply setPreCalculateFormulas(true), we get an error

[PhpOffice\PhpSpreadsheet\Calculation\Exception] 
Лист1!J7 -> Formula Error: An unexpected error occurred (0)
/home/process/www/vendor/phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:304
#0: PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()

### What features do you think are causing the issue

-  Writer

### Which versions of PhpSpreadsheet and PHP are affected?
current

**Comment by MarkBaker** [comment]
No it isn't: this isn't a bug, it's a feature that is in the process of being implemented: if we had a team of 20 or 30 developers working full time on this, then it might have been finished already.
Support for Structured References is still a work-in-progress. This is [PR #3173](https://github.com/PHPOffice/PhpSpreadsheet/pull/3173).

And it's absolutely nothing to do with the `Writer`, and everything to do with the `Calculation Engine`

**Comment by MarkBaker** [comment]
Structured References should now be fully supported in the Calculation Engine, except for reference to [#Headers] returning a `#Ref!` error if the headers are hidden

**Comment by MarkBaker** [comment]
[#Headers] will return a #Ref! error if the headers are hidden in the next release
