### ISSUE TITLE
Unserializing Spreadsheet instance leaks memory

### ISSUE THREAD

**Issue by ConnectGrid** [PHPOffice/PhpSpreadsheet#3195]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Repeated calls to `unserialize()` does not increase memory usage.

_Note that using the available cell caching feature does not offer sufficient performance for our application since we are dealing with thousands of spreadsheets. Instead, we are caching each entire Spreadsheet instance into Redis, which requires they be serialized._

### What is the current behavior?

Repeated calls to `unserialize()` is increasing memory usage on each call, even for the same Spreadsheet instance. Yet this same issue also affects our application when we unserialize many individual instances in succession. So, one or many, memory usage increases every time `unserialize()` is called on PhpSpreadsheet instances.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add some mock data
$worksheet = $spreadsheet->getActiveSheet();
foreach (range('A', 'F') as $char) {
    foreach (range(1, 100) as $num) {
        $worksheet->getCell("{$char}{$num}")->setValue($num + $num);
    }
}

$txt = serialize($spreadsheet);

// memory usage increases after each call to unserialize():

unserialize($txt);
unserialize($txt);
unserialize($txt);

// memory is eventually exhausted when dealing with many very large spreadsheet instances

```

If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

n/a

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

n/a

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet v1.24
PHP 8.1

**Comment by MarkBaker** [comment]
Looks like I'm going to have to explicitlyt disable the ability to serialize a spreadsheet... it isn't a serializable object.

**Comment by ConnectGrid** [comment]
We worked around the issue by using the `toArray()` and `fromArray()` methods on the Worksheet. Reconstructing a Spreadsheet instance using those methods does not impact performance noticeable, and we can easily store the resulting array in a serialized fashion. It feels like the right way to handle this. Solved.
