### ISSUE TITLE
json_encode got "Unable to JSON encode payload. Error code: 5" error

### ISSUE THREAD

**Issue by alexmuravyov** [PHPOffice/PhpSpreadsheet#3196]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
json_encode runs without errors.

### What is the current behavior?
Got an error "Unable to JSON encode payload. Error code: 5"
https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Collection/Cells.php
```php
private function getUniqueID()
    {
        $cacheType = Settings::getCache();

        return ($cacheType instanceof Memory\SimpleCache1 || $cacheType instanceof Memory\SimpleCache3)
            ? random_bytes(7) . ':'
            : uniqid('phpspreadsheet.', true) . '.';
    }
```
random_bytes(7)  - generates unvalid UTF-8 value

### What are the steps to reproduce?
Run json_encode at PhpSpreadsheet object.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

json_encode($spreadsheet);
```

### Which versions of PhpSpreadsheet and PHP are affected?
php 7.4, 1.25.2

**Comment by MarkBaker** [comment]
What cache are you using?
If you're using the default memory cache, then there is no json encoding in either implementation of SimpleCache; and if you use another cache, then nothing that uniqid generates should be invalid, it's just a numeric value prefixed with a string.

**Comment by MarkBaker** [comment]
But you should not be trying to json_encode the spreadsheet object, or to serialize it in any way. Consider it as a PHP resource that cannot be serialized.
