### ISSUE TITLE
[Bug] Worksheet name in formula fails if title contains parentheses

### ISSUE THREAD

**Issue by XGhozt** [PHPOffice/PhpSpreadsheet#3201]
This is:

- [X] a bug report

### What is the expected behavior?
Unchanged cell value.

### What is the current behavior?
A working formulae is erroring which results in calculating the formula (correctly) instead of preserving the cell value.

"Syntax error: 'Example (A), lookahead: ', current char: 31"

### What are the steps to reproduce?
On a spreadsheet that has tabs, if a formula includes a reference to a tab that has a parentheses in the title, it fails to parse the formula.

For example: `=SUM('Example (A)'!$A$2:$A$9999)`

Where the name of the other tab is `Example (A)`

Looks to be a problem with the `writeFormula()` parser script that just assumes and `(` and `)` is some kind of formula.

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Have only tested **Xls**.

### Which versions of PhpSpreadsheet and PHP are affected?
Last tested on: v1.25.2

**Comment by MarkBaker** [comment]
Unable to replicate:
```php
$spreadsheet = new Spreadsheet();

$worksheet = $spreadsheet->getActiveSheet();
$dataSheet = new \PhpOffice\PhpSpreadsheet\Worksheet\Worksheet($spreadsheet, 'Example (A)');
$spreadsheet->addSheet($dataSheet);

$data = [["DATA"], [1], [2], [3]];
$formula = "=SUM('Example (A)'!\$A\$2:\$A\$9999)";

$worksheet->getCell('A1')->setValue($formula);
$dataSheet->fromArray($data, null, 'A1');

var_dump($worksheet->getCell('A1')->getValue(), $worksheet->getCell('A1')->getCalculatedValue());

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xls($spreadsheet);

$writer->save('BraceInWorksheetName.xls');
```

**Comment by MarkBaker** [comment]
Neither the Writer, nor the Calculation Engine has a problem with worksheet names that contain braces
