### ISSUE TITLE
array_unshift

### ISSUE THREAD

**Issue by panjirai** [PHPOffice/PhpSpreadsheet#3207]
{
    "message": "PnL by Group!F39 -> PnL by Group!H39 -> PnL by Group!W39 -> array_unshift() expects at least 2 parameters, 1 given",
    "exception": "PhpOffice\\PhpSpreadsheet\\Calculation\\Exception",
    "file": "/var/www/html/live/cubic_pro/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php",
    "line": 295,

**Comment by MarkBaker** [comment]
Insufficient information to infer anything
