### ISSUE TITLE
Error after load and write excel with calculated (array_unshift)

### ISSUE THREAD

**Issue by panjirai** [PHPOffice/PhpSpreadsheet#3208]
This is:

```
- [- ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ -] Reader
- [-] Writer
- [ ] Styles
- [ ] Data Validations
- [-] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
i use version 1.19 laravel 5 php7.1 and server php 7.4

error: array_unshift in Cell.php handler

**Comment by MarkBaker** [comment]
Insufficient information to infer anything
