### ISSUE TITLE
createWriter($showPHPExcel, "Xlsx"); save(file) 2 times crash

### ISSUE THREAD

**Issue by alaindev** [PHPOffice/PhpSpreadsheet#3209]
### Discussed in https://github.com/PHPOffice/PhpSpreadsheet/discussions/2770

<div type='discussions-op-text'>

<sup>Originally posted by **alaindev** April 23, 2022</sup>
Hello PhpSpreadsheet Team

I Face a Bug when i need to **reopen** a phpspreadsheet created template. 

crash when save if images where in the footer

IOFactory::load eval-crash.xlsx whith image in footer 
create a IOFactory::createWriter and save it to file2.xlsx 

 IOFactory::load(file2.xlsx) produced by phpspreasheet
create a IOFactory::createWriter and save it to dest.xlsx 

and crash bescause of missing zip image  stuff ?

Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Writer\Exception: File zip://C:\temp\file2.xlsx# does not exist in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\aplitec\includes\modules\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Writer\Xlsx\ContentTypes.php on line 215

=========================================
<?php
        require_once (DIR_WS_MODULES . 'autoload.php');
         
          $file = 'c:\tmp\eval-crash.xlsx';
          $showPHPExcel = \PhpOffice\PhpSpreadsheet\IOFactory::load($file);
          $sheets_array = $showPHPExcel->getSheetNames();
          $liassewriter = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($showPHPExcel,"Xlsx");
          $file = 'c:\tmp\file1.xlsx';
          $liassewriter->save($file);
         
          $step2PHPExcel = \PhpOffice\PhpSpreadsheet\IOFactory::load($file);
          $sheets_array = $showPHPExcel->getSheetNames();
          $liassewriter = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($step2PHPExcel, "Xlsx");
          $liassewriter->save('c:\tmp\file2.xlsx');
?>
================================================
Thanks a lot Regards
Alain
</div>
[eval-crash.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/10089647/eval-crash.xlsx)

**Comment by oleibman** [comment]
This seems similar to issue #3126, which was fixed (I hope) by PR #3140, which was merged around Nov. 2. Does your error still occur when you test against master?

**Comment by alaindev** [comment]
@all
I cannot understand why composer update keep phpspreadsheet stuck to 1.16 version and do not update to 1.25

**Comment by oleibman** [comment]
Closing. PhpSpreadsheet problem is solved. If there is a problem with Composer, it is unrelated and should be opened as a new issue.
