### ISSUE TITLE
Freeze Panes takes wrong coordinates

### ISSUE THREAD

**Issue by juanmatias** [PHPOffice/PhpSpreadsheet#322]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When I set a cell XY to freeze panes the following should happen:
  - Columns on left of X must freeze
  - Rows above of Y must freeze
  - Cell on the right of XY must be selected

### What is the current behavior?
For example if I set freeze to D7 (from coordinates 4,7), the cell referenced to the freeze is G4 (from coordinates 7,4).
The "topLeftCell" is correctly set to this value (7,4).

### What are the steps to reproduce?
Just try to freeze on D7 and the output will be freeze on 7,4.
 
```php
<?php

use PhpOffice\PhpSpreadsheet\Helper\Sample;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

(...)

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();

(...)


// with coordinates: 
$spreadsheet->getActiveSheet()->freezePaneByColumnAndRow(7,4);

// with cell name:
$spreadsheet->getActiveSheet()->freezePane('D7');

(...)
```

If I change this code in file vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xls/Worksheet.php:

```
        $y = isset($panes[0]) ? $panes[0] : null;
        $x = isset($panes[1]) ? $panes[1] : null;
```

to this one:
```
        $x = isset($panes[0]) ? $panes[0] : null;
        $y = isset($panes[1]) ? $panes[1] : null;
```

... all works ok.

### Which versions of PhpSpreadsheet and PHP are affected?

Installed via composer:
```
$ php composer.phar info phpoffice/phpspreadsheet
name     : phpoffice/phpspreadsheet
descrip. : PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
keywords : OpenXML, excel, gnumeric, ods, php, spreadsheet, xls, xlsx
versions : * 1.0.0
```

**Comment by PowerKiKi** [comment]
Thanks for reporting !

**Comment by juanmatias** [comment]
Thank you for programming! ;)
