### ISSUE TITLE
Error on reading XLSX with tables but removed filters

### ISSUE THREAD

**Issue by alexpicolin** [PHPOffice/PhpSpreadsheet#3239]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

When reading an XLSX file with tables and removed auto-filters, it is expected that the file is successfully loaded. 

### What is the current behavior?

However, when an XLSX file contains tables, e.g. via selecting a data range and run "Format as Table" (creating xl/tables/table1.xml) and remove the table's filters, the table1.xml does not contain an element `Table->autoFilter`. This means that `$tableXml->autoFilter` (called in PhpOffice\PhpSpreadsheet\Reader\TableReader::readTable(), line 50) is null; that throws a warning in TableReader::readTableAutoFilter(), line 63 because `$autoFilterXml->filterColumn` is not an array or object and the foreach loop cannot operate.

### What are the steps to reproduce?

PHP
```php
<?php
require __DIR__ . '/vendor/autoload.php';

// Create Excel file demo.xlsx with a table (e.g. "Format as Table") and remove filters
$fileName = "demo.xlsx";
$inputFileType = \PhpOffice\PhpSpreadsheet\IOFactory::identify($fileName);
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($inputFileType);
$excel = $reader->load($tmpName);
// throws "foreach() argument must be of type array|object, null given" in \PhpOffice\PhpSpreadsheet\Reader\Xlsx\TableReader::63
```

demo.xlsx/xl/tables/table1.xml
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="xr xr3" xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision" xmlns:xr3="http://schemas.microsoft.com/office/spreadsheetml/2016/revision3" id="1" xr:uid="{2F8FD251-2F2D-43C9-B125-1E8AB709A085}" name="Table1" displayName="Table1" ref="C4:E7" totalsRowShown="0">
	<tableColumns count="3">
		<tableColumn id="1" xr3:uid="{E3FD8A73-06CF-465E-8C63-61EFF3508DBC}" name="Table C1"/>
		<tableColumn id="2" xr3:uid="{07D71973-619E-4E12-9BEE-87E00D0A6EF7}" name="Table C2"/>
		<tableColumn id="3" xr3:uid="{D08DE071-0A3D-423D-9CA6-6E3B44BF1CC3}" name="Table C3"/>
	</tableColumns>
	<tableStyleInfo name="TableStyleLight9" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/>
</table>
```

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

Only detected with XLSX.

### Which versions of PhpSpreadsheet and PHP are affected?

Detected with 1.25.2, seems to be in case since introduction of class PhpOffice\PhpSpreadsheet\Reader\TableReader. 1.23 is working fine. Tested and detected with latest PHP versions 7.4 and 8.0.

**Comment by MarkBaker** [comment]
Fixed in 1.26.0
