### ISSUE TITLE
RATE function doesn't work

### ISSUE THREAD

**Issue by arthurdev83** [PHPOffice/PhpSpreadsheet#324]
This function doesn't work very well, ie in this case:

RATE(360, -570.3, 93550)

it returns this value: 3.19311841954E-16

and Excel returns a very different value (0,51300% in percentage)

Can you help me please ?

**Comment by PowerKiKi** [comment]
Unfortunately, the RATE function [has been known to buggy](https://github.com/PHPOffice/PhpSpreadsheet/blob/55689caa1dcb62ef1ce79e174728215229ba8197/tests/PhpSpreadsheetTests/Calculation/FinancialTest.php#L489) for a while now. We need somebody to remove that `markTestIncomplete()` line and suggest a fix to make the test pass.

**Comment by oleibman** [comment]
Given example now returns correct result.
