### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by mzvarik** [PHPOffice/PhpSpreadsheet#3240]
1) There's NO functionality difference for Excel 2003 compared to PHPExcel lib... just github loading sh*
2) Examples are loaded from Samples class??? Nobody can make sense of that... can't even show an example with how to load a file.

**There should be big red warning on this page to use this library only for learning purposes.**

**Comment by MarkBaker** [comment]
So do something about it then!!! Create a few PRs to provide additional functionality for Excel 2003; or to provide clear examples for how to load a file; or improve the documentation

**Comment by mzvarik** [comment]
I would just remove this library if I could.

**Comment by MarkBaker** [comment]
It's just as well that you can't then; you seem very happy to complain; you don't consider that this library supports versions of PHP up to and including the newest PHP 8.2, but less happy about the thought of helping improve the things that you see as issues.

What extra functionality do you want for Excel2003 (SpreadsheetML). What features doesn't it support that you want?

And a little bit more civility please toward maintainers that spend many hours every week maintaining this library free of charge and in their own time.

**Comment by mzvarik** [comment]
Sorry, I'm being upset, because I lost 2 hours trying to make something work... at first I used PHPExcel and then I used this and noticed it works identically.
The samples are awful.
My issue is that it seems to be adding some empty columns (in XLS) compared to MS Office Excel.

**Comment by MarkBaker** [comment]
PHPSpreadsheet loads all the content that exists in the Excel file; but content in Excel may include null values or empty strings that aren't visble when looking at the worksheet in Excel itself; or cells that contain style information, data validations, or calculations that result in an empty string.

There is a Reader option to ignore empty cells. If you instantiate the Reader, then call that Reader's `setReadEmptyCells(false)` method, it won't load cells that contain a null value or an empty string. It will still load style information, data validations formulae, etc because they are a part of the spreadsheet content.

**Comment by mzvarik** [comment]
**Thank you, I appreciate your time to help.**

Specifically... DPD-Germany (https://dpd.de/) has old administration and they use XLS to import packages.
When I import a file made in MS Office it works.
But when I import the same file that has been opened and saved with PHPExcel / PHPSpreadsheet the DPD says there is invalid count of columns, but that makes no sense, because when I open it in MS Office it is okay.
However if I then save it again in MS Office it works.
---
The files are here:
https://zvarik.cz/dpd/File_not_working.xls (generated from this library)
https://zvarik.cz/dpd/File_working.xls (generated from this library and then resaved in MS Office)

But we will contact DPD, because they should be supporting CSV/XLSX already.

**Comment by openjck** [comment]
I'm not a maintainer of this project, but I was searching through issues and wanted to say... don't be a jerk, @mzvarik. You're lucky @MarkBaker took the time to respond to you at all.

I wouldn't discourage anyone from blocking @mzvarik and closing this issue.
