### ISSUE TITLE
RichText is not parsed in xlsx

### ISSUE THREAD

**Issue by doekenorg** [PHPOffice/PhpSpreadsheet#3244]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Text formatting is applied on `RichText` objects with a `Xlsx` writer

### What is the current behavior?
The text is formatted as normal text. No styling is applied.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\RichText\RichText;
use PhpOffice\PhpSpreadsheet\RichText\Run;
use PhpOffice\PhpSpreadsheet\Style\Color;

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xlsx');

$run1 = new Run('test text' . chr(10));
$run1->getFont()->setBold(true)
    ->setItalic(true)
    ->setColor(new Color(Color::COLOR_DARKGREEN));

$richText = new RichText();
$richText->addText($run1);

$spreadsheet->getActiveSheet()->getCell('A1')->setValue($richText);

$writer->save('file.xlsx');

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
I've tested `1.12` and `1.25` on PHP 7.4 and 8.0. 

### Context

I've searched the closed issues for `RichText`, but am not seeing anyone with this problem. The funny thing is, it works fine when I use the `Xls` writer; but for my purposes I need `xlsx`. I'm probably missing some vital piece of code; but even the default example from the docs isn't working for me with `xlsx`.

I'm sorry if this is a duplicate I haven't found.

**Comment by oleibman** [comment]
I am unable to duplicate your problem with the code supplied. See image below. I get the same result with 7.4/8.0/8.1/8.2 using master and 1.25.2. I'll need to think what else could be different between our environments.
![image](https://user-images.githubusercontent.com/10341515/207442683-ca77ba39-8e42-4017-8fc3-a1a3744fdc6e.png)

**Comment by MarkBaker** [comment]
I run your code, and this is what I see in the generated file:
![image](https://user-images.githubusercontent.com/770298/207442933-1e78fca8-a749-478e-be2a-6f28e1605ed6.png)

That looks like it works as it should

**Comment by doekenorg** [comment]
@oleibman @MarkBaker Super fast response times guys; amazing! 😆 Thanks a lot. 

I guess I'll have to take a look at my environment then. Is either of you checking this out on a mac? Perhaps in preview mode? I use Numbers to read the xlsx; so it might be that; but Preview usually works pretty wel; and again, with the xls it works great. 

If you want to close this go ahead. The problem appears to be totally on my end. I'll try it on a different environment soon.

**Comment by oleibman** [comment]
I'm on Windows (no easy access to a Mac), and my screen capture is from Excel.

**Comment by doekenorg** [comment]
Ah, found a co-worker that actually has Microsoft Excel; so it's a Numbers problem. Thanks guys! I'll close this issue.
