### ISSUE TITLE
"!" characters in Worksheet title will make reference formulas crash

### ISSUE THREAD

**Issue by hampusiggstrom** [PHPOffice/PhpSpreadsheet#325]
This is:

```
- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The calculation should be valid. The "!" needs to be added to `$invalidCharacters` or calculations needs to be updated to support exclamation mark characters in sheet titles. 

### What is the current behavior?
```Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Title!!C1 -> Cell coordinate can not be zero-length string```

### What are the steps to reproduce?

```php
<?php

require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setTitle('Title!');
$sheet->fromArray([1, 2,'=SUM(A1:A2)']);

$writer = new Xlsx($spreadsheet);
$writer->save('hello world.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
all

**Comment by hampusiggstrom** [comment]
https://github.com/PHPOffice/PhpSpreadsheet/blob/4635d39b4ab341904562e0079d054e117fc56341/src/PhpSpreadsheet/Calculation/Calculation.php#L3463

**Comment by PowerKiKi** [comment]
Can confirm it will crash even wihtout saving like so:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setTitle('Title!a');
$sheet->fromArray([1, 2,'=SUM(A1:A2)']);
$sheet->getCell('C1')->getCalculatedValue();
```

**Comment by hampusiggstrom** [comment]
Bug still present in latest release

**Comment by JonHaymanFCX** [comment]
I'm having this issue as well.
When trying to reference another worksheet within a formula, I get an exception thrown.

`$spreadsheet->getActiveSheet()
            ->setCellValue('A2', '=SUM("Handset Activity"!C:C)*"Handset Activity"!D:D');`

Exception:
Fatal error: Uncaught exception 'PhpOffice\PhpSpreadsheet\Calculation\Exception' with message 'Totals!A2 -> Totals!C2 -> undefined variable '!''

**Comment by PowerKiKi** [comment]
Would still be nice if somebody can come up with a PR for this issue
