### ISSUE TITLE
Exception when inserting value into empty cell

### ISSUE THREAD

**Issue by abryser** [PHPOffice/PhpSpreadsheet#3250]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Save the value for the cell `$cell1`

### What is the current behavior?
```
Exception 'Error' with message 'Call to a member function update() on null'
in /var/www/html/public/api/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:78
```

### What are the steps to reproduce?

Reading two cells, the first of which is empty, saving them to variables. Then trying to write a value to the first one results in an exception

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$worksheet = $spreadsheet->getActiveSheet();
$cell1 = $worksheet->getCell('A1');
$cell2 = $worksheet->getCell('B1');
$cell1->setValue('aaa');

```

If we delete the reading of another cell then writing works fine.

```php

<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$worksheet = $spreadsheet->getActiveSheet();
$cell1 = $worksheet->getCell('A1');
$cell1->setValue('aaa');
$cell2 = $worksheet->getCell('B1');

```

It also works fine if we read a real file and cell A1 is not empty.

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
I tested on xlsx

### Which versions of PhpSpreadsheet and PHP are affected?

1.25.2 - 2022-09-25

**Comment by MarkBaker** [comment]
THIS IS NOT A BUG!

DO NOT ASSIGN CELLS TO A VARIABLE!

`getCell()` does not actually return the specified cell, it sets the current active cell to the specified cell, and returns that pointer as a reference to the current active cell.
Calling `getCell()` a second time with a different cell reference sets that pointer to the new current active cell, changing any previous assignments to variables to point to that cell, because they are references rather than values.

```php
$cell1 = $worksheet->getCell('A1'); // Sets the active cell pointer to A1 in the cell collection, and assigns that pointer to $cell1
$cell2 = $worksheet->getCell('B1'); // Sets the active cell pointer to B1 in the cell collection, and assigns that pointer to $cell2
// But because the active cell pointer has now been changed to B1, all assigned references to that pointer are now pointing
//      to cell B1, including $cell1
$cell1->setValue('aaa');
```

**Comment by abryser** [comment]
I see. I suggested the comment of the `getCell` method, there is no information that it is only a reference. Might be worth adding it. Thanks for the explanation.

**Comment by MarkBaker** [comment]
It's never easy to explain to people, even to developers, and I've never found a wording for the documentation that I'm happy with using.

The best that I've managed to come up with is:

> Because the cell collection can be cached to reduce memory, it only allows one "active" cell at a time in memory. If you assign a cell to a variable, then select another cell using `getCell()` or any of its variants, the newly selected cell becomes the "active" cell, and any previous assignment becomes an empty reference because the active cell has changed.

But I'm still unsure if it really explains the situation, or how many developers ever actually read the documentation anyway.

**Comment by abryser** [comment]
In my opinion, this explanation is OK, but it was missing in the comment to the method. In this case, I didn't look at the documentation, because the method seemed obvious to me :) Lesson for me: review the documentation before reporting a bug. Sorry for the unnecessary report
