### ISSUE TITLE
Documentation refers to "Drawing from String/Stream" feature that hasn't been released.

### ISSUE THREAD

**Issue by Offlein** [PHPOffice/PhpSpreadsheet#3254]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The documentation contains a setting on [Creating a Drawing from string or stream data](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#creating-a-drawing-from-string-or-stream-data) so we should be able to use this.

### What is the current behavior?
This appears in the master branch from 45 days ago but hasn't been released.

...I think I'm just saying it shouldn't be in the documentation if it hasn't been released. :)

**Comment by MarkBaker** [comment]
Released now as 1.26.0, so all good
