### ISSUE TITLE
PHP 8 TypeError

### ISSUE THREAD

**Issue by dashakuh22** [PHPOffice/PhpSpreadsheet#3259]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
### What is the current behavior?

There are some errors like "Unsupported operand types in 'SimpleXMLElement - int' will cause a PHP 8 TypeError" in: 
- src/PhpSpreadsheet/Reader/Gnumeric.php,
- src/PhpSpreadsheet/Reader/Xml.php
- src/PhpSpreadsheet/Reader/Gnumeric/Styles.php
- src/PhpSpreadsheet/Reader/Xlsx/Styles.php

![Screenshot from 2022-12-23 14-01-17](https://user-images.githubusercontent.com/87013128/209340479-78639926-fec8-42c6-a865-919e9f02268c.png)

### What features do you think are causing the issue

- [ ] Reader

### Which versions of PhpSpreadsheet and PHP are affected?
PHP >=8.0

**Comment by oleibman** [comment]
Can you supply a spreadsheet which demonstrates this problem?

**Comment by oleibman** [comment]
No update in 2 months. Closing.
