### ISSUE TITLE
Inserting new row causes some address to return "XFD" instead.

### ISSUE THREAD

**Issue by brianwong3** [PHPOffice/PhpSpreadsheet#3263]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Upon calling "insertNewRowBefore", the cell references should be updated correctly.

### What is the current behavior?
Currently, after calling "insertNewRowBefore", any columns starting with "Y", and "Z" evaluates to "true" and PhpSpreadsheet sets the new column value to "AddressRange::MAX_COLUMN" 

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [x ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
So far only XLSX has been tested.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet v1.26.0

After some digging, the issue seems to be from 
https://github.com/PHPOffice/PhpSpreadsheet/blob/e7a0e8092d186998852598a27a50840912bdc010/src/PhpSpreadsheet/CellReferenceHelper.php#L120

**Comment by oleibman** [comment]
Confirmed, but this appears to be a bug in Php, not PhpSpreadsheet. I will attempt to open a ticket there. As far as I can tell, the code in question worked through PHP7.3, and became broken in PHP7.4.

**Comment by oleibman** [comment]
Actually, it is possible that PHP7.4 changed the way that column comparisons happened. I think we can probably fix this in PhpSpreadsheet after all.

**Comment by MarkBaker** [comment]
Hmmmm, that looks like my bad; it was a bugfix that targeted ensuring that row/column ranges didn't fall outside the Excel max rows/columns, rather than cell ranges; but looks like I may have introduced a new bug for cell ranges in doing so
