### ISSUE TITLE
Currency Brazilian Format

### ISSUE THREAD

**Issue by skay1994** [PHPOffice/PhpSpreadsheet#327]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
Format values with parameter

### What is the current behavior?
I create a parameter mask in excel 2016

### What are the steps to reproduce?

Sorry for my bad english, for better explanation, i'm using images for example.

I'm need format a some cells with the Brazilian Real format. The library does not include this format by default.

I took the format used by Excel, using the program interface. When using within the library, the generated file does not apply the format.

Format gerated:
![print1](https://user-images.githubusercontent.com/5720296/34742072-13917fd6-f56c-11e7-924b-66ee969d1d2e.PNG)

With used:
![print2](https://user-images.githubusercontent.com/5720296/34742102-31b0f9ba-f56c-11e7-90a6-233f6978928b.PNG)

Final Result:
![print3](https://user-images.githubusercontent.com/5720296/34742114-4013a336-f56c-11e7-9ebd-8153c2858a89.PNG)
![print4](https://user-images.githubusercontent.com/5720296/34742143-558b6924-f56c-11e7-938e-fece4bee61fe.PNG)

### Which versions of PhpSpreadsheet and PHP are affected?

PHP: 7.1.9
Php Spreadsheet: 1.0 by composer.json

**Comment by MarkBaker** [comment]
Use `.` for the decimal separator, `,` for the thousands separator in your format mask for PHPSpreadsheet.... the code is not locale-aware, and won't change it for you internally where the mask is stored as `.` for decimals and `,` for thouands ; in MS Excel, localisation for thousands and decimal separators are handled within the Excel GUI.

**Comment by skay1994** [comment]
are working, thanks!

**Comment by studiogyngo** [comment]
Onde setar esta função? ->setFormatCode('R$ #,##0.00_-');
na minha planilha esta saindo assim: R$ 90,000.00
