### ISSUE TITLE
Server overload IOFactory

### ISSUE THREAD

**Issue by CamiloPerezOrtiz** [PHPOffice/PhpSpreadsheet#3285]
Hello, I hope you can guide me with this detail
I am using laravel 5.8, php 7.3, and the IOFactory library, I am loading an excel file that has an algorithm to create payment references, the issue here is that the file (excel) comes encrypted with the cells, therefore I cannot manipulate anything, when I load the file, the server loads, simply to do the operation that generates the reference, any ideas on how to improve this? The Excel file has a size of 10 MB

This is how I am generating that reference, I need to place it in a cell.

Sorry for my English is not very good.

$fecha_limite_pago = date("dmy", strtotime($request->fecha_vigencia));
$fecha_pago = date('Y-m-d', strtotime($request->fecha_vigencia));
nuevo_saldo = 100;

$ruta_archivo = "algoritmo.xlsx";
$documento = IOFactory::load($ruta_archivo);
$usuario_clave = $documento->getSheet(0)->getCell('A12');
$usuario_clave = $usuario_clave->setValue($usuario->clave);
$fecha_limite = $documento->getSheet(0)->getCell('B12');
$fecha_limite = $fecha_limite->setValue($fecha_limite_pago);
$importe = $documento->getSheet(0)->getCell('C12');
$importe = $importe->setValue($nuevo_saldo);
$contenido = $documento->getSheet(0)->getCell('D12');
$referencia = $contenido->getCalculatedValue();

**Comment by MarkBaker** [comment]
If the file is encrypted, then there's nothing that we can do. PhpSpreadsheet does not read encrypted files.

**Comment by CamiloPerezOrtiz** [comment]
Hello, thanks for the information @MarkBaker . Excel has protected cells, but if you do the operation, detail it will overload the server a lot, it consumes 2 GB of ram and does not consume processor resources, only ram.

**Comment by MarkBaker** [comment]
It's difficult to say anything about memory usage without seeing the file, so that I can see why it needs so much memory; but a lot of files contain empty cells.
Perhaps you might try using the Reader's `setReadEmptyCells(false)` method, to tell it not to read empty cells.

**Comment by CamiloPerezOrtiz** [comment]
Is there any way to free the RAM memory? Since at the end of the process, it does not free the memory, I already tried this

Calculation::getInstance($documento)→clearCalculationCache();

Similarly apply the destructor
$documento→__destruct();

Likewise with the leaves.
$documento→disconnectWorksheets();
unset($documento);

Even with the PHP function
ob_end_clean();

I am using laravel in version 5.8, php 7.3 and apache2, all mounted on an ubuntu server 22.04

**Comment by PowerKiKi** [comment]
See https://phpspreadsheet.readthedocs.io/en/latest/topics/reading-files/#spreadsheet-reader-options on how to save memory by not reading the whole file.
