### ISSUE TITLE
Could not process 

### ISSUE THREAD

**Issue by ibracadabra59** [PHPOffice/PhpSpreadsheet#3286]
Hi I run "vendor/bin/rector process web/sites/libraries/PHPExcel/ --dry-run"
I got this : 

````
In NotAnInterfaceReflection.php line 17:

  Provided node "PhpParser\Node\Stmt\Class_" is not interface, but "class"

````

How fix this issue please ?

**Comment by MarkBaker** [comment]
Whatever you're trying to do, I'd suggest using PhpSpreadsheet rather than PHPExcel.

PHPExcel was officially deprecated in 2017 and permanently archived in 2019.

**Comment by ibracadabra59** [comment]
ok thanks
