### ISSUE TITLE
Error in import strings and float values from XLSX: Spreadsheet objects cannot be json encoded

### ISSUE THREAD

**Issue by samuel-lujan** [PHPOffice/PhpSpreadsheet#3291]
This is:

```
- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I built some command to read an xlsx file with many products to import info from  the products, images in base64 and price to import in my database.

### What is the current behavior?
Now when I run the command, trow me an error "PhpOffice\PhpSpreadsheet\Exception: Spreadsheet objects cannot be json encoded"
![image](https://user-images.githubusercontent.com/17858893/211884574-ad3b4cfc-ba11-457b-98d3-ba7ccb446eec.png)

### What are the steps to reproduce?
I should send the copy of xlsx for you guys if needed!
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;


// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$inputFileName = public_path('files/TABELA_IMPORT.xlsx');
$reader = new Xlsx;
$spreadsheet = $reader->load($inputFileName);
$sheet = $spreadsheet->getSheetByName('TSSHARA');
$maxRow = $sheet->getHighestRow();

for ($row = 2; $row < $maxRow; $row++) { // Começa na linha 2 porque a linha 1 é o cabecalho da tabela
    $productAttributes = [
        'name'          => $sheet->getCell("Q{$row}")->getValue(), // Nome do Produto
        'price'         => number_format($sheet->getCell("X{$row}")->getValue(), 2, '.', ''), // Valor do produto
        'description'   => $sheet->getCell("U{$row}")->getValue(), // Descrição do Produto,
        'category_id'   => Category::firstOrCreate(['category' => $sheet->getCell("S{$row}")->getValue()])->id, // Categoria do produto
        'is_available'  => true,
        'part_number'   => $sheet->getCell("R{$row}")->getValue(), // PN do produto
        'sheet_tab'     => "TSSHARA",
        'link'         => $sheet->getCell("Z{$row}")->getValue(), // Link do produto
    ];

    $product = $this->createOrUpateProductByProductAttributes($productAttributes);

    $productImage = $sheet->getCell("A{$row}")->getValue();

    $this->addOrUpdateProductImage($product, $productImage);
}

private function addOrUpdateProductImage(Product $product, mixed $productImage)
    {
        try {
            if ((isset($productImage) && ! is_null($productImage)) && (str_starts_with($productImage, 'data:image') || str_starts_with($productImage, 'http'))) {
                if (str_starts_with($productImage, 'data:image')) {
                    $product->clearMediaCollection('products');
                    $product->addMediaFromBase64($productImage)->toMediaCollection('products');
                } else {
                    $product->clearMediaCollection('products');
                    $product->addMediaFromUrl($productImage)->toMediaCollection('products');
                }
            }
        } catch (Exception $ex) {
            Log::error("Houve uma falha ao importar a imagem do produto {$product->id}, {$ex->getMessage()}", $ex->getTrace());
        }

    }
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ X] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
format used: xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
1.26.0

**Comment by samuel-lujan** [comment]
When running on version ```version": "1.25.2",``` works fine! :)

**Comment by MarkBaker** [comment]
We very deliberately set a thrown exception on any attempt to serialize a spreadsheet object, because spreadsheet objects are not serializable, but people keep trying to do it, and it leads to nasty little bugs and issues in the code if it isn't prevented, and I got fed up with having to tell people not to use serialize oor jsonserialize... to be honest, I don't understand how it ever worked fine prior to that change.

**Comment by MarkBaker** [comment]
I think the problem is a result of 
```php
Log::error("Houve uma falha ao importar a imagem do produto {$product->id}, {$ex->getMessage()}", $ex->getTrace());
```
I think that the `getTrace()` might include the Spreadsheet object; and something is triggering that error logging, so you're getting an Exception thrown in `addOrUpdateProductImage()` somewhere. Removing the `getTrace()` should at least reveal the real problem, because the actual error should then be logged

**Comment by samuel-lujan** [comment]
Pretty good man thanks :)

**Comment by epertinez** [comment]
Tinkerwell serializes the spreadsheet to show it, simply for debugging reasons. Not being able to do it makes it fail. I had to touch the vendor dir only to keep using Tinkerwell: 

 public function jsonSerialize(): mixed
    {
        return(json_encode($this));
        //throw new Exception('Spreadsheet objects cannot be json encoded');
    }

I understand jsonSerializing a speradsheet is a very bad idea... but that is what Tinkerwell does. Do not know if is there any other way to avoid the exception while letting Tinkerwell do its thing.
