### ISSUE TITLE
PhpOffice\PhpSpreadsheet\Writer\Html::setEditHtmlCallback(): Argument #1 ($callback) must be of type ?callable, string given

### ISSUE THREAD

**Issue by pud-micha** [PHPOffice/PhpSpreadsheet#3293]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the current behavior?
21b_Pdf.php is not working under 8.1

### What are the steps to reproduce?

$writer->setEditHtmlCallback('replaceBody') gives back exception
PhpOffice\PhpSpreadsheet\Writer\Html::setEditHtmlCallback(): Argument #1 ($callback) must be of type ?callable, string given

### What features do you think are causing the issue

- [ ] Reader
- [ x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
current version. php 8.1

**Comment by oleibman** [comment]
Sample works fine for me, and no problem is being reported when it is run as part of PR unit testing. Perhaps it is a specific point release that is failing - I am using Php 8.1.13. I have tested against both the latest official release and master, testing from both the command line and a web server.

**Comment by oleibman** [comment]
No response in over a month. Closing.
