### ISSUE TITLE
Scatterchart X-axis is always set as type "category"

### ISSUE THREAD

**Issue by u01jmg3** [PHPOffice/PhpSpreadsheet#3294]
This is:

- [x] a bug report

### What is the expected behavior?

To be able to control the type applied to the X-axis of a Scatterchart and have it read `0-6`. Type "value" achieves this.

<img width="342" alt="value-axis" src="https://user-images.githubusercontent.com/1266205/212287299-4c33de30-fce8-42ee-a894-6ba0e7d4c7e5.png">

### What is the current behavior?

The X-axis reads `3,4,4,3,5,4`. This is because it has been set by PHPSpreadsheet as type "category" after a change in PR #2841. Prior to #2841 / v1.24.0 it was set by PHPSpreadsheet as type "value".

<img width="342" alt="category-axis" src="https://user-images.githubusercontent.com/1266205/212287380-80d7b099-bf97-4b30-b6d2-6d47fa865030.png">

### What are the steps to reproduce?

1. Run `samples\Chart\33_Chart_create_scatter5_trendlines.php` from my [fork](https://github.com/PHPOffice/PhpSpreadsheet/compare/master...u01jmg3:PhpSpreadsheet:master)
1. Open XLSX file and note the X-axis reads `3,4,4,3,5,4` and says "Horizontal (Category) Axis" on hover

Notes:
- If you click on the chart and navigate to "Chart Design" → "Change Chart Type" then press <kbd>OK</kbd> (without any changes) and go back and look at the chart. The X-axis will now read `0-6` and "Horizontal (Value) Axis" on hover (i.e. Excel has fixed the issue).
- In my fork, I've indicated where I think the code could be changed.
- Alternatively, instead of hard-coding this setting, could there be a way of controlling the X-axis type so it can be changed to "value"?

### What features do you think are causing the issue

- [x] Writer
- [x] Charts

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

I expect it will but I've focussed on XLSX

### Which versions of PhpSpreadsheet and PHP are affected?

v1.24.0 onwards according to when PR #2841 was released

**Comment by oleibman** [comment]
In your fork, please restore the changed sample to its original, and make your sample a new member. If we make any changes as a result of this issue, we want to make sure they don't break the existing one (assuming it isn't already broken). Also, could you upload a spreadsheet which shows what things ought to look like. In your diagrams above, I see only axes, and I see the horizontal axis is not labeled as you want; but presumably there should be some data points on the correct chart which are missing or badly placed on the incorrect one. It will just help the resolution of the problem if I have the whole picture.

**Comment by u01jmg3** [comment]
- Fork updated
- [33_Chart_create_scatter6_trendlines.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/10413383/33_Chart_create_scatter6_trendlines.xlsx)

**Comment by oleibman** [comment]
After `$xAxis->setAxisOptionsProperties` in your sample, you can add any one of the following statements:
```php
$xAxis->setAxisType(ChartAxis::AXIS_TYPE_VALUE);
$xAxis->setAxisNumberProperties(Properties::FORMAT_CODE_NUMBER);
$xAxis->setAxisNumberProperties(Properties::FORMAT_CODE_GENERAL, true);
```
I believe you will then have the result you are seeking. Please confirm. If that is so, there is no need for a change to the chart generation code. There may, nevertheless, be merit in adding your sample to the test suite. Please submit a PR if you wish.

**Comment by oleibman** [comment]
BTW, the existing sample is already correct because it already calls `setAxisNumberProperties` (using a belt and suspenders - it sets a format which will automatically be treated as numeric, and it explicitly uses the second parameter to specify `true`).

**Comment by u01jmg3** [comment]
That does the trick. Thanks for taking a look. I'll PR a small change to showcase `setAxisType(ChartAxis::AXIS_TYPE_VALUE)` in one of the scatterchart samples. Unless you want a completely new sample?

Note it worked without:

```php
$xAxis->setAxisNumberProperties(Properties::FORMAT_CODE_NUMBER);
$xAxis->setAxisNumberProperties(Properties::FORMAT_CODE_GENERAL, true);
```

Are these additional method calls needed to prevent the X-axis values being treated as strings? Can you explain why 2 calls are required to the same `setAxisNumberProperties` method?

✌🏻

**Comment by oleibman** [comment]
You can use any of the statements I suggested; you do not need to use them all. The one that makes the most sense might differ from application to application.

**Comment by oleibman** [comment]
A completely new sample would be fine.

**Comment by u01jmg3** [comment]
> _You can use any of the statements I suggested; you do not need to use them all. The one that makes the most sense might differ from application to application._

Ah yes, you did say "_add any **one** of the following_".

I can confirm that separately either of the 3 will solve my issue although `FORMAT_CODE_NUMBER` results in 2 decimal places.
