### ISSUE TITLE
XIRR NonPeriodic rate function not calculating as in Excel

### ISSUE THREAD

**Issue by DilipsinhChudasama** [PHPOffice/PhpSpreadsheet#3297]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$XIRR = NonPeriodic::rate($values_1, $dates) * 100;

Date | Cash Flow
2022-05-02 | -19646.10172
2022-05-31 | -22288.58964
2022-06-01 | -1483.5
2022-06-26 | -12597.54406
2022-06-30 | -46629.45777
2022-07-01 | -2472.769
2022-07-15 | 0
2022-07-31 | -25616.37076
2022-09-02 | -30055.68344
2022-09-05 | 1038.5
2022-09-27 | -13621.9742
2022-09-28 | 13629.539
2022-09-29 | -36736.0694
2022-10-03 | -944.605609
2022-10-06 | -49020.77156
2022-10-10 | 27308.87082
2022-11-01 | -63912.64722
2022-11-03 | 8764.136
2022-11-04 | 3162
2022-12-01 | -23946.7257
2022-12-02 | -5428.8
2022-12-28 | -83899.24172
2022-12-30 | 58242.82346
2023-01-02 | -11147.78101
2023-01-13 | 287092.5749

NonPeriodic Rate function result : -37.933273330331
MS Excel result 0.00000030

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by DilipsinhChudasama** [comment]
@oleibman

**Comment by oleibman** [comment]
I doubt you'll like this answer, but I believe that PhpSpreadsheet is correct and Excel is wrong. There are several unit test cases where I explicitly note that we don't agree with Excel's answer, and this appears to be another case. The PhpSpreadsheet results agrees with Java (https://github.com/RayDeCampo/java-xirr) *and LibreOffice*. It will take me a few minutes to set up an equivalent test in Python; I will post that result here when I have done so.

**Comment by oleibman** [comment]
Python package XIRR (https://github.com/tarioch/xirr/) agrees with PhpSpreadsheet as well.

**Comment by oleibman** [comment]
Gnumeric also agrees with PhpSpreadsheet.

**Comment by oleibman** [comment]
Finally, XNPV(*xirr*,*amounts*,*dates*) should be very close to 0 if XIRR gives a good answer. On LibreOffice, that formula with the PhpSpreadsheet result is `-5.8E-11`, which certainly qualifies. OTOH, Excel and its XIRR result yield `-50210.2` - nowhere close (LibreOffice gives the same result for XNPV using the Excel result). In fact, I see several other problems using this verification method with Excel even when its XIRR result agrees with PhpSpreadsheet, so it probably has XNPV problems as well as XIRR. For example, for dates `2018-09-05` and `2018-09-26` and amounts `-1000000.706` and `947003.58`, everybody including Excel calculates XIRR as `-0.6...`. But, plugging that rate and those dates and amounts into XNPV, Excel returns #NUM!, where LibreOffice returns `1.2E-10`.

**Comment by DilipsinhChudasama** [comment]
I am ok with your answer, I have also calculated XIRR manually also in this same answer given by PhpSpreadsheet.

I have raise XIRR problem problem in MS Excel team.. waiting for this.. 

Thank you very much @oleibman 

given below manual calculation of XIRR for reference.
[XIRR Calculation.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/10441533/XIRR.Calculation.xlsx)

**Comment by DilipsinhChudasama** [comment]
@oleibman  - Thanks for quick support....!
