### ISSUE TITLE
Excel range modified to cell A to XFC when calling insertNewRowBefore or removeRow

### ISSUE THREAD

**Issue by sdespont** [PHPOffice/PhpSpreadsheet#3308]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When calling  `$activeSheet->insertNewRowBefore($firstLine+1, $lineCount-1);` or `$activeSheet->removeRow($firstLine, $lineCount);` the cells' range must not be modifed to max cell XFC

I am pretty sure that the problem comes from this PR https://github.com/PHPOffice/PhpSpreadsheet/pull/3213 driven by issue https://github.com/PHPOffice/PhpSpreadsheet/issues/3184 after discussing with @MarkBaker. Working well with v1.25.2

### What is the current behavior?
Everytime `insertNewRowBefore `or `removeRow `is called, the cells' range is modified to the max cell XFC

![image](https://user-images.githubusercontent.com/646632/213666079-5c2a5b5b-138a-47e0-9dae-fc02ba4ea19f.png)

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet = IOFactory::createReader('Xlsx');
$spreadsheet->setIncludeCharts(true);
$spreadsheet = $objReader->load($filename);

$activeSheet = $spreadsheet->getActiveSheet();
$activeSheet->insertNewRowBefore(1, 10);
$activeSheet->setCellValue('A1', 'ABCDE');

$writer = IOFactory::createWriter($spreadsheet , 'Xlsx');
$writer->save('path);

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
1.26.0

**Comment by MarkBaker** [comment]
Can you test against master? PR https://github.com/PHPOffice/PhpSpreadsheet/pull/3264, which is part of master but not yet a release, fixes a problem that might be related to yours.

**Comment by sdespont** [comment]
@MarkBaker Yes, it is working 👍
