### ISSUE TITLE
Something not valid when importing in ERP

### ISSUE THREAD

**Issue by mauro-miatello** [PHPOffice/PhpSpreadsheet#3316]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

export an xls file compatible with an ERP that have to import it

### What is the current behavior?

the import failed, but if the user opens the file with Excel and save it without any changes, it works
the original file is very small (10-15KB) while the file saved by Excel is greater (30-35Kb)
comparing the 2 files it seems a very large quantity of data is missing

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

namespace App\Http\Controllers\Traits;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xls;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Writer\Csv;
use Symfony\Component\HttpFoundation\StreamedResponse;

trait StampeExcelTrait {
    public $spreadsheet;
    public $sheet;

    public $arrCols;
    public $row = 1;

    public function initXLS($sheetName = "Foglio1") {
        $this->spreadsheet = new Spreadsheet();
        $this->spreadsheet->getProperties()
            ->setCreator("APP")
            ->setLastModifiedBy("APP");

        $this->sheet = $this->spreadsheet->getActiveSheet();
        $this->sheet->setTitle($sheetName);

        $this->setArrColls();
        $this->setHeaderCell();
    }

    public function formatNumber($number) {
        $v = (float) $number;
        return round(number_format($v, 3, '.', ''), 3);
    }

    public function setArrColls() {
        $this->arrCols = range('A', 'Z');

        // Aggiunge le col "doppie"
        foreach (range('A', 'Z') as $columnID) {
            $this->arrCols[] = 'A' . $columnID;
        }
        foreach (range('A', 'Z') as $columnID) {
            $this->arrCols[] = 'B' . $columnID;
        }
        foreach (range('A', 'Z') as $columnID) {
            $this->arrCols[] = 'C' . $columnID;
        }
        foreach (range('A', 'Z') as $columnID) {
            $this->arrCols[] = 'D' . $columnID;
        }
    }

    public function setHeaderCell() {
        $this->spreadsheet->getActiveSheet()->getRowDimension('1')->setRowHeight(30);
        $this->spreadsheet->getActiveSheet()->getStyle('1')->getAlignment()->setVertical('center');
        foreach ($this->colonne as $key => $colonna) {
            $this->spreadsheet->getActiveSheet()->getStyle($this->arrCols[$key] . $this->row)->getFont()->setSize(12)->setBold(true);
            $this->spreadsheet->getActiveSheet()->getStyle($this->arrCols[$key])->getAlignment()->setVertical('center');

            // Titolo colonna
            $this->sheet->setCellValue($this->arrCols[$key] . $this->row, $colonna['label']);

            // Per ogni colonna di ogni riga dimensioni automatiche
            $this->spreadsheet->getActiveSheet()->getColumnDimension($this->arrCols[$key])->setAutoSize(true);
        }
    }

    public function generaXLS($title, $fileName, $type) {
        $this->spreadsheet->getProperties()->setTitle($title);

        switch ($type) {
            case 'csv':
                $writer = new Csv($this->spreadsheet);
                $writer->setDelimiter(';');
                $writer->setEnclosure('');
                $writer->setLineEnding("\r\n");
                $writer->setEnclosureRequired(false);
                $writer->setSheetIndex(0);
                break;

            case 'xls':
                $writer = new Xls($this->spreadsheet);
                break;

            default:
                $writer = new Xlsx($this->spreadsheet);
                break;
        }

        $response = new StreamedResponse(
            function () use ($writer) {
                $writer->save('php://output');
            }
        );

        $response->headers->set('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        $response->headers->set('Content-Disposition', 'attachment;filename="' . $fileName . '"');

        return $response;
    }
}
```
I will attach 2 example files later

### What features do you think are causing the issue

something related to headers/properties

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

the ERP accepts only XLS

### Which versions of PhpSpreadsheet and PHP are affected?

1.25.x - 1.26.0
it worked with PHPExcel 1.8.1

**Comment by mauro-miatello** [comment]
here you can see the original file, where CODICE is in line 7 with some NUL between characters
![image](https://user-images.githubusercontent.com/11910225/214242825-38c4429a-9387-4527-8f82-5baff5f69a5d.png)
and the file opened and saved by Excel, where CODICE is without extra characters
![image](https://user-images.githubusercontent.com/11910225/214242915-c9d26e7c-634a-4697-aaba-7253e25febd6.png)
 I used Notepad++ for this test

**Comment by MarkBaker** [comment]
Does your ERP provide any error meaasges that might help explain what it considers to be invalid in the file?

**Comment by mauro-miatello** [comment]
no, they simply told me that "they can't find the row CODICE"

**Comment by MarkBaker** [comment]
Not a very helpful error report; CODICE isn't even an Excel row, (rows are numbers in Excel); I'm assuming that CODICE is a value stored in the row that the ERP tries to identify.
PhpSpreadsheet always uses codepage `0x4B0` (`UTF16LE`) to encode text in the xls files that it generates. This is a DBCS (Double Byte Character Set) [codepage](https://learn.microsoft.com/en-us/globalization/encoding/code-pages), hence the null bytes as the second byte in each character pair. The ERP system's xls Reader should be capable of recognising codepages and handling the character set encoding; especially as codepage `0x4B0` is the standard default for all BIFF8 Files.

**Comment by mauro-miatello** [comment]
first of all, many thanks for reply
no, not a helpful error report :( 
these are the columns
![image](https://user-images.githubusercontent.com/11910225/214309379-7fd09c98-2583-4ff1-8259-1f0e2f7d2138.png)
when the program import the xls starts analyzing the content and look for the value CODICE in the first position
the program hangs immediately but probably it will have the same behaviour with the other text
can I change in some way the codepage ?

**Comment by MarkBaker** [comment]
If the ERP doesn't support the standard `UTF16-LE` codepage for xls files since BIFF8 was introduced in 1997, then that will be a problem.

We don't provide functionality for changing the codepage in the Writer because `UTF16-LE` has been Microsoft's standard for over 25 years, and it would creates a large element of complexity, and would require that all string values were converted from UTF to the appropriate encoding for the codepage that was used instead (which isn't always possible).

If you want to try this yourself, then the code to handle UTF-8 to UTF16-LE is in the `UTF8toBIFF8UnicodeShort()` method of the `StringHelper` class; while the codepage flag is hard-coded in the constructor for the `xls\Workbook` class. But it isn't something that we would support because of the high potential for problems.

An alternative might be to see if the ERP system will work with more modern spreadsheet formats, such as `xlsx`

**Comment by mauro-miatello** [comment]
it seems a hard way to follow, and with possible unknown consequences.
so I've installed gnumeric and I will try to generate a csv and then convert it with ssconvert
I close the issue, it is not a bug but a problem with an old unsupported format
thank you very much for your help
