### ISSUE TITLE
.xlsx corrupting when using charts and PNG

### ISSUE THREAD

**Issue by azonX33** [PHPOffice/PhpSpreadsheet#3317]
This is:

```
- [ * ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I am trying to modify an .xlsx document with excel charts inside, i want it to modify the B4 cell.

### What is the current behavior?
When i open the xlsx file with phpspreadsheet, the charts and PNG image get corrupted and are deleted when openning the new .xlsx file.

### What are the steps to reproduce?

```php
<?php
require '../vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Chart\Chart;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$inputFileName = 'C:/www/test.xlsx';  //use your own path
$spreadsheet = IOFactory::load($inputFileName);

// access the sheet
$sheet = $spreadsheet->getSheetByName('test');

// Write to cell B4
$sheet->setCellValue('B4', '10');

// Save the spreadsheet
ob_end_clean();
$writer = new xlsx($spreadsheet);
$writer->save('C:/www/Export/test.xlsx'); //use your own path
exit();
```
To replicate the behaviour, you need an .xlsx file with a sheet called test, if you try the code with an empty xlsx file everything will word, however when you add a .PNG, the .PNG will corrupt and disapear from the document

### What features do you think are causing the issue

- [ * ] Reader
- [ * ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
Using phpspreadsheet 1.26.0, i also tried in version 1.16.0 and 1.21.0, and i am on php version 7.4.27

**Comment by MarkBaker** [comment]
If you want the charts to be loaded and saved again, then you have to tell the PhpSpreadsheet Reader explicitly to include the charts when it loads the file:

```php
$inputFileType = 'Xlsx';
$inputFileName = 'C:/www/test.xlsx';

$reader = IOFactory::createReader($inputFileType);
$reader->setIncludeCharts(true);

$spreadsheet = $reader->load($inputFileName);
```

And similarly tell the Writer to include the charts when it saves the file:
```php
$writer = new Xlsx($spreadsheet);
$writer->setIncludeCharts(true);
$writer->save(''C:/www/Export/test.xlsx'');
```

As for the png file, that's impossible to say without being able to analyse the file

**Comment by azonX33** [comment]
Thank you for your fast repply, i tried your code and it is working, sorry for saying it was a bug, i was misslead when i saw similar issues then #877.
