### ISSUE TITLE
PHP 8.2 Return type of PhpOffice\PhpSpreadsheet\Worksheet\Iterator::valid()

### ISSUE THREAD

**Issue by fredmatrack** [PHPOffice/PhpSpreadsheet#3322]
We are testing the 1.27.0 version on PHP 8.2. When enabling all the errors, we get this error:

> Return type of PhpOffice\PhpSpreadsheet\Worksheet\Iterator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/vhosts/inc/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Iterator.php</b> on line <b>69</b>

**Comment by MarkBaker** [comment]
What is the test that you're running, because the Worksheet Iterator's `valid()` method should always return a boolean, and I'm struggling to work out how it could return a non-boolean result.

**Comment by fredmatrack** [comment]
This is some basic code that returns the error:

`<?php

	error_reporting(E_ALL);
    ini_set('display_errors', '1');


    include('inc/config.php');
    include('inc/functions.php');

	require_once('inc/vendor/autoload.php');

	use PhpOffice\PhpSpreadsheet\Spreadsheet;
	use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
	use PhpOffice\PhpSpreadsheet\Cell\DataType;

    // Create new PHPExcel object
    	$objPHPExcel =  new Spreadsheet();

    // Set document properties
    	$objPHPExcel->getProperties()->setCreator("Toolbox")
    							 	 ->setLastModifiedBy("Toolbox")
    							 	 ->setTitle("ExportFietsvergoeding")
    							 	 ->setSubject("ExportFietsvergoeding ");

    // Tabblad 1
	    $objPHPExcel->setActiveSheetIndex(0);

	// Test
		$objPHPExcel->getActiveSheet()->setCellValue('A1', 'TestA1');

	// Rename worksheet
		$objPHPExcel->getActiveSheet()->setTitle('Test');


    // Set active sheet index to the first sheet, so Excel opens this as the first sheet
    	$objPHPExcel->setActiveSheetIndex(0);


    // Redirect output to a client’s web browser (Excel2007)
	    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
	    header("Content-Disposition: attachment;filename=Test.xlsx");
	    header('Cache-Control: max-age=0');

	    $writer = new Xlsx($objPHPExcel);
	    $writer->save('php://output');

	    exit;
	    
?>`

**Comment by MarkBaker** [comment]
Unable to replicate against PHP 8.2.1

We run a fairly comprehensive set of tests for every pull request, every commit, and every release, against PHP versions 7.4.33, 8.0.27, 8.1.14, 8.2.1 and even the 8.3.0-dev branch, covering a wide range of functionality.

None of these tests report any errors; and the Worksheet Iterator shouldn't even be used with the code sample that you have provided.

**Comment by fredmatrack** [comment]
We use PHP Version 8.2.1. Are you also monitoring for 'deprecated' warnings?

**Comment by MarkBaker** [comment]
Yes, I'm monitoring for everything', error_reporting(E_ALL); and phpunit should display all notifications as well, including deprecations

Can you double check the version of PhpSpreadsheet that you are running for your tests.

The signature for the `valid()` method was changed to include the return type in release `1.19.0` (Oct 31, 2021); so if you're running an earlier version of PhpSpreadsheet against PHP 8.2, then you will get this notification

**Comment by fredmatrack** [comment]
I'm sorry, my mistake. My composer prevented upgrading to the latest version...
