### ISSUE TITLE
PHP 8.2 - Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by fredmatrack** [PHPOffice/PhpSpreadsheet#3323]
We are testing the 1.27.0 version on PHP 8.2. When enabling all the errors, we get this error:

> <b>Deprecated</b>:  Implicit conversion from float 26.2 to int loses precision in <b>/var/www/vhosts/inc/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/StringTable.php</b> on line <b>45</b><br />

This is some code:
`$objPHPExcel->getActiveSheet()->setCellValue('A1', $row['data']);`

$row['data'] contains a decimal from a database.

**Comment by MarkBaker** [comment]
I have a horrible feeling that this might be related to locale settings, because the Default Value Binder should always recognise a float as a sumeric value, or a string containing a value of '26.2' as a numeric string and set the cell datatype to NUMERIC; but that error in the Shared String table should only occur if the cell has a string datatype set.

But I'm unable to replicate such a situation.

Can you help debugging the issue by doing a var_dump of your locale settings (use `setlocale(LC_ALL, 0);` to get the current locale setting without changing it); and on the value in `$row['data']` before setting the cell value; then of the cell value and datatype after setting the cell value.

**Comment by fredmatrack** [comment]
Hi Mark

Thanks for your reply. I added this code to a script:
`$currentLocale = setlocale(LC_ALL, 0);
	
	echo "<pre>";
		var_dump($currentLocale);
	echo "</pre>";`

The output is:
string(1) "C"


This is the code I use:

`error_reporting(E_ALL);
    ini_set('display_errors', '1');


    include('inc/config.php');
    include('inc/functions.php');

	require_once('inc/vendor/autoload.php');

	use PhpOffice\PhpSpreadsheet\Spreadsheet;
	use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
	use PhpOffice\PhpSpreadsheet\Cell\DataType;

    // Create new PHPExcel object
    	$objPHPExcel =  new Spreadsheet();

    // Set document properties
    	$objPHPExcel->getProperties()->setCreator("Toolbox")
    							 	 ->setLastModifiedBy("Toolbox")
    							 	 ->setTitle("ExportFietsvergoeding")
    							 	 ->setSubject("ExportFietsvergoeding ");

    // Tabblad 1
	    $objPHPExcel->setActiveSheetIndex(0);

	// Test
		$objPHPExcel->getActiveSheet()->setCellValue('A1', 25.3);

	// Rename worksheet
		$objPHPExcel->getActiveSheet()->setTitle('Test');


    // Set active sheet index to the first sheet, so Excel opens this as the first sheet
    	$objPHPExcel->setActiveSheetIndex(0);


    // Redirect output to a client’s web browser (Excel2007)
	    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
	    header("Content-Disposition: attachment;filename=Test.xlsx");
	    header('Cache-Control: max-age=0');

	    $writer = new Xlsx($objPHPExcel);
	    $writer->save('php://output');

	    exit;`

**Comment by MarkBaker** [comment]
Unable to replicate against PHP 8.2.1

We run a fairly comprehensive set of tests for every pull request, every commit, and every release, against PHP versions 7.4.33, 8.0.27, 8.1.14, 8.2.1 and even the 8.3.0-dev branch, covering a wide range of functionality. That includes the most basic functionality, such as writing a number to a cell and saving the file.

None of these tests report any errors; and the basic situation that you describe with a number being identified as a string by the value binder, then the writer trying to store it in the Shared String table should never occur.

**Comment by fredmatrack** [comment]
I'm sorry, my mistake. My composer prevented upgrading to the latest version...
