### ISSUE TITLE
7.4 compatibility broken due to zipstream-php library

### ISSUE THREAD

**Issue by sc0ttdav3y** [PHPOffice/PhpSpreadsheet#3327]
This is:

```
- [X] a bug report
```

### What is the expected behavior?

According to your EOL policy, I expect PhpSpreadsheet to run on PHP 7.4 until June 2023.

### What is the current behavior?

Currently, a fresh install fails due to a dependency problem with `zipstream-php`. They removed PHP 7 support as of 2.3.0 (2.2.6 is the last version supporting 7).

PhpSpreadsheet is using this:

```
        "maennchen/zipstream-php": "^2.1",
```

### What are the steps to reproduce?

Delete your lock file and your vendor folder and run this using PHP 7.4.33:

```
composer install
composer check-platform-reqs
```

### What features do you think are causing the issue

This is a problem with the upstream library `zipstream-php` no longer supporting PHP 7 as of 2.3.0:
https://github.com/maennchen/ZipStream-PHP/releases/tag/2.3.0

### Which versions of PhpSpreadsheet and PHP are affected?

My composer file has this:
```
"phpoffice/phpspreadsheet": "^1"
```

This pulls the latest library version, which is `1.27.0`.

### Workaround / other comments

I realise PHP 7 is the past, so the workaround is to pin `zipstream-php` to this:

```
        "maennchen/zipstream-php": "2.2.6",
```

**Comment by oleibman** [comment]
Why are you deleting the lock file, which *is* locked to 2.2.6? Regardless, when I clone the repository, delete composer.lock, and composer install using Php7.4, I get zipstream 2.2.6, as expected. Are you attempting your install using Php8.* and then trying to run the result using 7.4?

**Comment by oleibman** [comment]
No response in a month. Closing.
