### ISSUE TITLE
Support for autofitting the rows height

### ISSUE THREAD

**Issue by leandrogm** [PHPOffice/PhpSpreadsheet#333]
This is:

```
- [ ] a bug report
- [X] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

The lib should be able to have a function that autofits the rows based on the largest cell. I couldn't find any place to do it. 

After struggling with this issue I came up with a solution that I would like to share. That's why i'm creating this issue.

### What is the current behavior?

I'm not sure if it only happens on Libre Office Calc but if I have a text that has been wrapped before using `getAlignment()->setWrapText(true)` I'm was not able to fit the rows based on the new height of the cells, like when we double click excel/calc rows.

### Which versions of PhpSpreadsheet and PHP are affected?
"phpoffice/phpspreadsheet": "1.0.0-beta",
"php": ">=5.6.4"

**Comment by ianfoulds** [comment]
Hi leandrodm. A good start but there are some errors in you code and it doesn't take into account merged cellls.

Here is a version of your method that can be placed into the client code and does not require your fork to implement the function.

Rather than use a row range, I've gone for performing the action on a single row but this could be adapted to your methodology easily. To get the row you need to do the following:

```
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Row;
use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
...
    const DEFAULT_CELL_WIDTH = 9.14;
    const DEFAULT_ROW_HEIGHT = 15;
...
            $row = new Row($myWorksheet, $myRowNum);
            $this->autofitRowHeight($row);

```

```
    /**
     * Auto-fit the row height based on the largest cell
     *
     * @param Row $start
     * @return Worksheet
     */
    public function autofitRowHeight(Row $row, $rowPadding = self::ROW_PADDING)
    {
        $ws = $row->getWorksheet();
        $cellIterator = $row->getCellIterator();
        $cellIterator->setIterateOnlyExistingCells(true);

        $maxCellLines = 1;
        /* @var $cell Cell */
        foreach ($cellIterator as $cell) {
            $cellLength = strlen($cell->getValue());
            $cellWidth = $ws->getColumnDimension($cell->getParent()->getCurrentColumn())->getWidth();
            // If no column width is set, set the default
            if($cellWidth === -1) {
                $ws->getColumnDimension($cell->getParent()->getCurrentColumn())->setWidth(self::DEFAULT_CELL_WIDTH);
                $cellWidth = $ws->getColumnDimension($cell->getParent()->getCurrentColumn())->getWidth();
            }
            // If the cell is in a merge range we need to determine the full width of the range
            if($cell->isInMergeRange()) {
                // We only need to do this for the master (first) cell in the range, the rest need to have a line height of 1
                if($cell->isMergeRangeValueCell()) {
                    $mergeRange = $cell->getMergeRange();
                    if($mergeRange) {
                        $mergeWidth = 0;
                        $mergeRefs = Coordinate::extractAllCellReferencesInRange($mergeRange);
                        foreach($mergeRefs as $cellRef) {
                            $mergeCell = $ws->getCell($cellRef);
                            $width = $ws->getColumnDimension($mergeCell->getParent()->getCurrentColumn())->getWidth();
                            if($width === -1) {
                                $ws->getColumnDimension($mergeCell->getParent()->getCurrentColumn())->setWidth(self::DEFAULT_CELL_WIDTH);
                                $width = $ws->getColumnDimension($mergeCell->getParent()->getCurrentColumn())->getWidth();
                            }
                            $mergeWidth += $width;
                        }
                        $cellWidth = $mergeWidth;
                    } else {
                        $cellWidth = 1;
                    }
                } else {
                    $cellWidth = 1;
                }
            }

            // Calculate the number of cell lines with a 10% additional margin
            $cellLines = ceil(($cellLength * 1.1) / $cellWidth);
            $maxCellLines = $cellLines > $maxCellLines ? $cellLines : $maxCellLines;
        }

        $rowDimension= $ws->getRowDimension($row->getRowIndex());
        $rowHeight = $rowDimension->getRowHeight();
        // If no row height is set, set the default
        if($rowHeight === -1) {
            $rowDimension->setRowHeight(self::DEFAULT_ROW_HEIGHT);
            $rowHeight = $rowDimension->getRowHeight();
        }

        $rowLines = $maxCellLines <= 0 ? 1 : $maxCellLines;

        $rowDimension->setRowHeight( ($rowHeight * $rowLines) + $rowPadding);

        return $ws;
    }

```

**Comment by gitrequests** [comment]
> Hi leandrodm. A good start but there are some errors in you code and it doesn't take into account merged cellls.
> 
> Here is a version of your method that can be placed into the client code and does not require your fork to implement the function.
> 
> Rather than use a row range, I've gone for performing the action on a single row but this could be adapted to your methodology easily. To get the row you need to do the following:
> 
> ```
> use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
> use PhpOffice\PhpSpreadsheet\Worksheet\Row;
> use PhpOffice\PhpSpreadsheet\Cell\Cell;
> use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
> ...
>     const ROW_PADDING = 5;
>     const DEFAULT_CELL_WIDTH = 9.14;
>     const DEFAULT_ROW_HEIGHT = 15;
> ...
>             $row = new Row($myWorksheet, $myRowNum);
>             $this->autofitRowHeight($row);
> ```
> 
> ```
>     /**
>      * Auto-fit the row height based on the largest cell
>      *
>      * @param Row $start
>      * @return Worksheet
>      */
>     public function autofitRowHeight(Row $row, $rowPadding = self::ROW_PADDING)
>     {
>         $ws = $row->getWorksheet();
>         $cellIterator = $row->getCellIterator();
>         $cellIterator->setIterateOnlyExistingCells(true);
> 
>         $maxCellLines = 1;
>         /* @var $cell Cell */
>         foreach ($cellIterator as $cell) {
>             $cellLength = strlen($cell->getValue());
>             $cellWidth = $ws->getColumnDimension($cell->getParent()->getCurrentColumn())->getWidth();
>             // If no column width is set, set the default
>             if($cellWidth === -1) {
>                 $ws->getColumnDimension($cell->getParent()->getCurrentColumn())->setWidth(self::DEFAULT_CELL_WIDTH);
>                 $cellWidth = $ws->getColumnDimension($cell->getParent()->getCurrentColumn())->getWidth();
>             }
>             // If the cell is in a merge range we need to determine the full width of the range
>             if($cell->isInMergeRange()) {
>                 // We only need to do this for the master (first) cell in the range, the rest need to have a line height of 1
>                 if($cell->isMergeRangeValueCell()) {
>                     $mergeRange = $cell->getMergeRange();
>                     if($mergeRange) {
>                         $mergeWidth = 0;
>                         $mergeRefs = Coordinate::extractAllCellReferencesInRange($mergeRange);
>                         foreach($mergeRefs as $cellRef) {
>                             $mergeCell = $ws->getCell($cellRef);
>                             $width = $ws->getColumnDimension($mergeCell->getParent()->getCurrentColumn())->getWidth();
>                             if($width === -1) {
>                                 $ws->getColumnDimension($mergeCell->getParent()->getCurrentColumn())->setWidth(self::DEFAULT_CELL_WIDTH);
>                                 $width = $ws->getColumnDimension($mergeCell->getParent()->getCurrentColumn())->getWidth();
>                             }
>                             $mergeWidth += $width;
>                         }
>                         $cellWidth = $mergeWidth;
>                     } else {
>                         $cellWidth = 1;
>                     }
>                 } else {
>                     $cellWidth = 1;
>                 }
>             }
> 
>             // Calculate the number of cell lines with a 10% additional margin
>             $cellLines = ceil(($cellLength * 1.1) / $cellWidth);
>             $maxCellLines = $cellLines > $maxCellLines ? $cellLines : $maxCellLines;
>         }
> 
>         $rowDimension= $ws->getRowDimension($row->getRowIndex());
>         $rowHeight = $rowDimension->getRowHeight();
>         // If no row height is set, set the default
>         if($rowHeight === -1) {
>             $rowDimension->setRowHeight(self::DEFAULT_ROW_HEIGHT);
>             $rowHeight = $rowDimension->getRowHeight();
>         }
> 
>         $rowLines = $maxCellLines <= 0 ? 1 : $maxCellLines;
> 
>         $rowDimension->setRowHeight( ($rowHeight * $rowLines) + $rowPadding);
> 
>         return $ws;
>     }
> ```

**Does this code work with line breaks?**

**Comment by fbudin** [comment]
Hi,

I used a light version of this method to handle line breaks, but it assumes the columns widths are corrects berforehand.
`private function _autofitRowHeight(\PhpOffice\PhpSpreadsheet\Worksheet\Row &$row, $rowPadding = 5)
    {
        $ws = $row->getWorksheet();
        $cellIterator = $row->getCellIterator();

        $maxCellLines = 0; // Init
        
        // Find out max cell line count
        foreach ($cellIterator as $cell) {
            $lines = explode("\n",$cell->getValue());
            $lineCount = 0;
            // Ignore empty lines
            foreach($lines as $idx => &$line) {
                if(0 !== strlen(trim($line, " \t\n\r\0\x0B"))) {
                    $lineCount++;
                }
            }
            $maxCellLines = max($maxCellLines, $lineCount);
        }
        
        // Force minimum line height to 1
        $maxCellLines = max($maxCellLines, 1);
        
        // Adjust row height
        $rowDimension= $ws->getRowDimension($row->getRowIndex());
        $rowHeight = (XLSX_LINE_HEIGHT * $maxCellLines) + $rowPadding; // XLSX_LINE_HEIGHT = 13
        $rowDimension->setRowHeight($rowHeight);
        return $ws;
    }`

**Comment by Collie-IT** [comment]
In the Code from @ianfoulds is an little issue on line 33 by using the generated template again. The $width will added at every use again and again. If you use the code add a condition for only one add.

>                             $mergeWidth += $width;

Like 

```
if(!isset($temp) || $temp ==0){
   $mergeWidth += $width
}
```

**Comment by schmidtl4** [comment]
I can't see that this has been addressed. Am I right?  It's 2024.
I am trying to auto adjust the height of merged cells to the height necessary to accommodate all of the text set by a "setCellValue" method.  Like this:
$sheet->setCellValue("E{$msgRow}", "a very very long message...." );
$sheet->getStyle("E{$msgRow}")->getFont()->setSize(10);
$range = "E{$msgRow}:J{$msgRow}";
$sheet->mergeCells($range);
$sheet->getStyle($range)->getAlignment()->setWrapText(true);

To force all rows in the spreadsheet to auto-adjust to the height of the text, I use:
                $highestRow = $analysisSheet->getHighestRow();
                for ($row = 1; $row <= $highestRow; $row++) {
                    $sheet->getRowDimension($row)->setRowHeight(-1);
                }
But it doesn't have any effect on the merge cell range...  What am I missing?
