### ISSUE TITLE
Development install broken by dealerdirect renaming their `master` branch to `main`

### ISSUE THREAD

**Issue by MarkBaker** [PHPOffice/PhpSpreadsheet#3351]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

You may need to do a full composer install from the new composer.lock; or to manually reinstall `phpcodesniffer-composer-installer:dev-main`

```
composer require dealerdirect/phpcodesniffer-composer-installer:dev-main --dev
```
or (if you have pipelines breaking for merge requests) merge from master to your branch to pick up the change.

Listed here in `Issues` for notification purposes; the changes already merged should resolve it going forward

**Comment by ntwb** [comment]
Hey, we were caught out by this change breaking our build and deploy pipelines

For now we're switching to `dev-master` via Composer to install PhpSpreadsheet

Any chance you could perform a release, say `1.27.1` with this change so we can switch from `dev-master` to `1.27.1` so as we're not caught out by additional changes being merged here to `master`?

I guess a similar release to https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.25.2

**Comment by MarkBaker** [comment]
> Any chance you could perform a release, say `1.27.1` with this change so we can switch from `dev-master` to `1.27.1` so as we're not caught out by additional changes being merged here to `master`?

The things that a maintainer might do when their sleeping patterns are shot to h*** ;-)

**Comment by ntwb** [comment]
Greatly appreciated 💯
