### ISSUE TITLE
Calculation/LookupRef.php - wrong function name _getMatrixDimensions

### ISSUE THREAD

**Issue by ArtemBro** [PHPOffice/PhpSpreadsheet#336]
Hi!

_Calculation/LookupRef.php_ contains function call `Calculation::_getMatrixDimensions` on lines 141 and 221, 
but `Calculation` class has function `getMatrixDimensions` (without _) and it's `private`

//Same problem in PHPExcel 1.8.1

**Comment by PowerKiKi** [comment]
thanks for reporting
