### ISSUE TITLE
getCoordinate() throws Exception 'Coordinate no longer exists' after getting another cell by getCell()

### ISSUE THREAD

**Issue by hikaen2** [PHPOffice/PhpSpreadsheet#3375]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

getCoordinate() does not throw Exception 'Coordinate no longer exists' after getting another cell by getCell()

### What is the current behavior?

getCoordinate() throws Exception 'Coordinate no longer exists' after getting another cell by getCell()

### What are the steps to reproduce?

```php
<?php
require './vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$cell1 = $sheet->getCell('A1');
$cell2 = $sheet->getCell('A2');
echo $cell1->getCoordinate(); // => expected 'A1' but thrown
```

↓

```
$ php test2.php
PHP Fatal error:  Uncaught PhpOffice\PhpSpreadsheet\Exception: Coordinate no longer exists in /home/taro/src/test/phpspreadsheet-test/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:168
Stack trace:
#0 /home/taro/src/test/phpspreadsheet-test/test2.php(11): PhpOffice\PhpSpreadsheet\Cell\Cell->getCoordinate()
#1 {main}
  thrown in /home/taro/src/test/phpspreadsheet-test/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php on line 168
```

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet 1.27.1

PHP 8.1.2

**Comment by MarkBaker** [comment]
No! This is **NOT** a bug!!!!

DO NOT ASSIGN A CELL TO A VARIABLE AND THEN SELECT ANOTHER CELL.

We [document](https://phpspreadsheet.readthedocs.io/en/latest/topics/accessing-cells/#beware-cells-assigned-to-variables-as-a-detached-reference) this behaviour as a big warning message for a reason!

**Comment by hikaen2** [comment]
ok. understood
