### ISSUE TITLE
ZipArchive disabled on shared hosting

### ISSUE THREAD

**Issue by projecthate** [PHPOffice/PhpSpreadsheet#3390]
This is:

```
- [ ] a bug report
- [X ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

My scripts used to work great. Yesterday I was migrated to a new host (GoDaddy absorbing MediaTemple's accounts) and now they are not working so great.

### What is the current behavior?

Because ZipArchive is disabled, and they refuse to provide a reason as to why, besides saying that it's an outdated/vulnerable extension, iof::load(XXX.xlsx) causes a fatal error.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

In order to replicate, you would need to disable the ZipArchive extension within your php.ini - then replace XXX.xlsx with a file of your choosing.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet =iof::load(XXX.xlsx)

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ X] Reader
- [ X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

I only work with XLSX

### Which versions of PhpSpreadsheet and PHP are affected?

I'm on 1.27.1 (latest per composer) and 7.3.33

I'm guessing this will be a non-starter - you wouldn't be relying on zip functionality if it wasn't absolutely necessary, but figured it couldn't hurt to ask. This will be a major blow to my workflow, so I am hoping I'm missing an obvious workaround. Sorry if this is not the proper forum!

**Comment by oleibman** [comment]
Sorry, Xlsx (and Ods) files are really just a zipped collection of Xml files. Zip is required to read and/or write them. Xls, Html, and Csv do not require zip.

**Comment by oleibman** [comment]
Does the discussion at https://community.godaddy.com/s/question/0D53t00006VmDSpCAN/php-zip-is-not-installed-or-has-been-disabled provide a way around your problem?

**Comment by projecthate** [comment]
Very strange issue. During the migration the host added a .htaccess directive to force PHP v7.3, I guess due to compatibility concerns. The zip extension was not being loaded by PHP for this reason. Upon forcing v7.3 through cPanel instead of .htaccess, the library began working as expected.

**Comment by oleibman** [comment]
I'm glad that you found a solution, but I should note that Php7.3 is no longer supported with the most recent versions of PhpSpreadsheet. If there is a way for you to move to 7.4 (or preferably to 8.0/8.1/8.2), that would be better.
