### ISSUE TITLE
Using the setAutoFilter and setAutoSize on a Header with HORIZONTAL_CENTER

### ISSUE THREAD

**Issue by cwolcott** [PHPOffice/PhpSpreadsheet#3395]
This is:

```
- [x] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I would have hoped that the calculateColumnWidth would take into consideration the alignment of the header.

### What is the current behavior?
The calculation looks great if the header has a HORIZONTAL_LEFT, but if the header is HORIZONTAL_CENTER the calculation could be to small.

Header is **HORIZONTAL_LEFT**
<img width="503" alt="image" src="https://user-images.githubusercontent.com/3777526/220789919-74556dfa-2b37-4735-ac1f-c5aa074a594b.png">

Header is **HORIZONTAL_CENTER**
<img width="387" alt="image" src="https://user-images.githubusercontent.com/3777526/220790322-46e44041-323f-430e-9239-619698524324.png">

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet - 1.27.1
PHP - 8.1.13

**Comment by MarkBaker** [comment]
You may notice a very specific aspect of these headings that you omit to mention. This isn't simply a header value in a cell, or about the alignment of the header; but these headers all have a filter icon.

Please see [Issue #3356](https://github.com/PHPOffice/PhpSpreadsheet/issues/3356) and [PR #3358](https://github.com/PHPOffice/PhpSpreadsheet/pull/3358) and test against the latest master branch to see if this resolves your issue.

If it is a resolution, then `1.28.0` is due for release in the next week.

**Comment by oleibman** [comment]
@MarkBaker I have 3 PR's which I think should be part of the next release PR #3372, PR #3391, PR #3392. I will try to merge them by tomorrow morning (California time).

**Comment by cwolcott** [comment]
I installed the master branch via composer

_composer require "phpoffice/phpspreadsheet":dev-master_
![image](https://user-images.githubusercontent.com/3777526/221087403-f5c97299-0e70-455b-8a9a-9eb2ed5be5a8.png)

The master branch didn't fix the issue that I described when the header text is centered and has AutoFilter.
<img width="404" alt="image" src="https://user-images.githubusercontent.com/3777526/221087579-7bb8dd5e-015d-484b-9a6d-0969dc049d7f.png">

**Comment by cwolcott** [comment]
@MarkBaker loaded the latest master branch 
_composer require "phpoffice/phpspreadsheet":dev-master_
![image](https://user-images.githubusercontent.com/3777526/221325233-df3550fb-b5ae-496f-be37-0f58f95a124a.png)

Looks good, thank you so much.
<img width="234" alt="image" src="https://user-images.githubusercontent.com/3777526/221325061-e26f3f73-74c1-4a18-b3dd-be906d423f3d.png">
