### ISSUE TITLE
中文自动列宽设置后无效

### ISSUE THREAD

**Issue by hmwdt** [PHPOffice/PhpSpreadsheet#3405]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php
           
 $dataSheet->getColumnDimension("G")->setAutoSize(true); 

如果某一列是CJK 其中的一种，这样的设置方式无效

 version     "phpoffice/phpspreadsheet": "^1.19",





If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?


### Which versions of PhpSpreadsheet and PHP are affected?

**Comment by MarkBaker** [comment]
We don't have any CJK fonts defined in the library for autosizing.
What font are you using? Is it the standard Excel font for your locale?

**Comment by hmwdt** [comment]
My system is a Chinese system, so the text in excel includes numbers, English and Chinese.

At present, I calculate the column width by myself according to the content in the cell, and each Chinese text occupies 2 lengths

I used this method 'mb_strwidth' to determine the width of each cell, take the largest value in the column, and set it as the width of the column. Although this is not a good job, it also meets my current needs. I hope you can be compatible with CJK content.

demo cell value like :  你好

**Comment by oleibman** [comment]
If you can, please test against PR 3416. I'm sure you can give it a more thorough test than I can. Thank you for mentioning mb_strwidth; I was not familiar with it, and the PR depends on it.
