### ISSUE TITLE
  $this->_document->getSecurity()->setWorkbookPassword('123456')Have no effect

### ISSUE THREAD

**Issue by PoemRainPR** [PHPOffice/PhpSpreadsheet#3406]
$this->_document = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
            $this->_document->getSecurity()->setLockWindows(true);
            $this->_document->getSecurity()->setLockStructure(true);
            $this->_document->getSecurity()->setWorkbookPassword('123456');
Have no effect

**Comment by oleibman** [comment]
What effect are you looking for it to have? The password should be effective in that a user opening your spreadsheet in Excel will not be able to change some things without supplying the password.

It is possible that you want to require a password to view/read the file. This requires encryption, which PhpSpreadsheet does not support. This is in the documentation: 'If you need to completely prevent reading a file by any tool, including PhpSpreadsheet, then you are looking for "encryption", not "protection"'. https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#setting-security-on-a-spreadsheet

**Comment by oleibman** [comment]
Closing, no update in 7 months, no reason to think suggested explanation is not correct.
