### ISSUE TITLE
Graph without fill

### ISSUE THREAD

**Issue by ByronSilvaOlvera** [PHPOffice/PhpSpreadsheet#3408]
This is:
Hello, how do I make the charts do not have padding. When sorting the graph,
 the filling is white. I can't remove the padding.

Graphic 1 has a white background. Graph 2 contains no padding. I want the code of a graph without padding. I await your response, thank you
![chart](https://user-images.githubusercontent.com/33814057/221724563-839dabe5-d1bd-44ee-88fd-c6096008c42f.png)

**Comment by oleibman** [comment]
I believe this will do what you want.
```php
$chart->setNoFill(true);
```
You can also get the same result in Excel by right-clicking on the Chart, choosing "Format Chart Area", "Fill", "No Fill".

**Comment by ByronSilvaOlvera** [comment]
Excellent!

**Comment by ByronSilvaOlvera** [comment]
Now. I can't change the color of Title. I have the following code

$labelLayoutText = new Layout();
            $labelLayoutText
            ->setLabelFontColor( new ChartColor('FFFFFF') )
            ;
            $title = new Title( $data[$key]['title'] , $labelLayoutText );

**Comment by oleibman** [comment]
I am not sure if there is a way to use Layout for this purpose. However, this will set your Chart title to red:
```php
$richText = new RichText();
$run = $richText->createTextRun('VENTAS EN UNIDADES POR MES');
$run->getFont()->setChartColor(['value' => 'ff0000']);
$run->getFont()->setSize(18)->setBold(true);
$title = new Title($richText);
```

**Comment by oleibman** [comment]
The x-axis and y-axis titles can be handled in the same way.
