### ISSUE TITLE
Help whit PhpSpreadsheet.

### ISSUE THREAD

**Issue by LordBinario** [PHPOffice/PhpSpreadsheet#341]
**Code:**
use LibreriaCrearExcel\src\PhpSpreadsheet\Cell\DataValidation;
use LibreriaCrearExcel\src\PhpSpreadsheet\Spreadsheet;
use LibreriaCrearExcel\src\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();

**Fatal error:** Class 'LibreriaCrearExcel\src\PhpSpreadsheet\Spreadsheet' not found in C:\xampp\htdocs\provision\CrearExcel.php on line 18
![untitled](https://user-images.githubusercontent.com/32313074/35122009-02c9bf3a-fc63-11e7-9151-614732400ba5.png)

![untitled](https://user-images.githubusercontent.com/32313074/35122053-2c083930-fc63-11e7-8a9e-a6c1a8314b82.png)

**Comment by PowerKiKi** [comment]
Read the doc there: http://phpspreadsheet.readthedocs.io/en/develop/#installation
