### ISSUE TITLE
Change the color of the Title and data

### ISSUE THREAD

**Issue by ByronSilvaOlvera** [PHPOffice/PhpSpreadsheet#3414]
Hello, 
I want to change the color of the white title and the vertical data on the left, and the data on the x axis, but it does not allow me to change. Could you help me with the code.
![datacolor](https://user-images.githubusercontent.com/33814057/221991929-f4c110f0-f248-4620-a074-97a4fdf6e583.jpg)

**Comment by oleibman** [comment]
I don't see "the white title and vertical data on the left ...". Is it the characters in black that you wish to change?

**Comment by oleibman** [comment]
Changing the color of the chart and axis titles is dealt with in issue #3408. If you agree, please close that issue.

I do not think that changing the color of the data points on the axes is yet supported by PhpSpreadsheet. I will need to do some more research to confirm, and to see what might be required to support it.

**Comment by ByronSilvaOlvera** [comment]
If the black characters I want to change

**Comment by oleibman** [comment]
Thanks for the images. As I mentioned above, this might not yet be supported. I will research.

**Comment by ByronSilvaOlvera** [comment]
Ok, I'll be waiting for your answer

**Comment by oleibman** [comment]
If you can test against PR #3434, please do so.
```php
$xAxisText = new AxisText();
$xAxisText->getFillColorObject()->setValue('00FF00')->setType(ChartColor::EXCEL_COLOR_TYPE_RGB);
$xAxis->setAxisText($xAxisText);
```
