### ISSUE TITLE
Not able to read file with live data which is a calculation from another application (DDE function)

### ISSUE THREAD

**Issue by ishan501** [PHPOffice/PhpSpreadsheet#3415]
Hi, I'm trying to read an XLS file. Data of which is being updated by an external application through a formula (DDE function). So, the file is getting updated every second. When I try to read the file, I'm getting the below error.

Error:
ErrorException: Uninitialized string offset 0 in file C:\xampp\htdocs\gold-rate\gold-rate-web-test\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xls.php on line 7803

Code:
```
$inputFileType = 'Xls';
$inputFileName = 'sources/win.xls';
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($inputFileType);
$spreadsheet = $reader->load($inputFileName);

```
How can I read the file?
Thanks in advance!

**Comment by MarkBaker** [comment]
DDE isn't supported by PhpSpreadsheet; but I'd need to see the actual files to understand why the Reader was giving this particular error

**Comment by MarkBaker** [comment]
I can modify PhpSpreadsheet to suppress the warnings; but it can't provide you with the data.
Those cells are populated by the DDE, and that's something that PhpSpreadsheet will not do for you.

My suggestion would be to find what the DDE is calling to retrieve those values, and then to get your PHP script to access that datasource directly

**Comment by MarkBaker** [comment]
DDE is not something that we will ever implement in PhpSpreadsheet.

If you want to script those DDE calls, then you need PHP's [COM extension](https://www.php.net/manual/en/book.com.php) and [this tutorial](https://marcelwijayacc.wordpress.com/2011/09/22/obtaining-live-data-feed-from-excel-or-any-windows-object-using-php/) may help

**Comment by ishan501** [comment]
Yes, I also came across that tutorial and it worked like a charm.
Thank you so much!

Here is the code if anyone need,

```
    $excel = com_get_active_object("Excel.application") or die ("ERROR: Unable to instantaniate COM!\n");
    
    // Retrieve data
    $Worksheet = $excel->Worksheets("first"); //name of the opened tab
    $Worksheet->Activate;
    $cell = $Worksheet->Range("B2");
    $cell->activate();
    $value = $cell->value;
    echo $value;
        
    // Close connection
    unset($Worksheet);
    unset($excel);
```
