### ISSUE TITLE
Not formatting cell correctly with `[MM`] code

### ISSUE THREAD

**Issue by garrettgjb** [PHPOffice/PhpSpreadsheet#342]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I expect for the column containing "Duration" should come in as "mm" format as defined in excel. Meaning it should look like an integer as you see when you are in excel.
<img width="134" alt="screen shot 2018-01-19 at 9 07 59 pm" src="https://user-images.githubusercontent.com/549725/35180085-f750d49a-fd5c-11e7-8892-ee3e9b0f83a3.png">

The column subtracts one date from another date.
I.e.

2018-01-22 02:00:00 PM - 2018-01-22 01:00:00 PM

We format is as [mm] so it would be 60.

I think what is happening is this library doesn't know how to do binary operations with dates. If you multiple the decimal number by 1440 you get the correct number.

### What is the current behavior?
Duration column comes in as a decimal in the php code.
<img width="267" alt="screen shot 2018-01-19 at 9 00 56 pm" src="https://user-images.githubusercontent.com/549725/35180048-05b7b40a-fd5c-11e7-8719-1a153176c1f8.png">

### What are the steps to reproduce?
Import the following file with phpspreadsheet:
[importtest-phpspreadsheet.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1648584/importtest-phpspreadsheet.xlsx)

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

	require __DIR__ . '/vendor/autoload.php';

	$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();

	$file="importtest-phpspreadsheet.xlsx";
	$spreadsheet = $reader->load($file);
	$worksheet = $spreadsheet->getActiveSheet();

	echo "Should be 60";
	echo "\nActual: " . ($spreadsheet->getActiveSheet()->getCell('K2')->getFormattedValue());
	echo "\nFinished";
```

toArray return will have incorrect values.

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 5.6, Latest phpspreadsheet from composer

**Comment by PowerKiKi** [comment]
The code provided is not valid PHP code and cannot be run. And even if it could it would  not show anything useful regarding this issue.

Anyway the described behavior is the expected behavior. The value you got are indeed the values stored in the file. What you see in Excel is not the raw values, but formatted value. You should have a look at `getFormattedValue()`

**Comment by garrettgjb** [comment]
Please check again. I updated the code so it is runnable, just put the spreadsheet in the same dir.

Output:
Should be 60
Actual: 0.041666666671517

My previous example called toArray with no params which my research showed should have formatted. In my updated sample, I have called getFormattedValue as you said so you can see its not working.

**Comment by garrettgjb** [comment]
I've reposted the issue here since this one is closed:
https://github.com/PHPOffice/PhpSpreadsheet/issues/343

**Comment by garrettgjb** [comment]
Can this issue be reopened? I'm guessing you were able to recreate it since you changed the title.

**Comment by PowerKiKi** [comment]
Please refrain from opening new issue for the same problem, we can continue the discussion here and re-open as needed.

The MCVE should not rely on an external file and the code should have been simplified down to:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Style\NumberFormat;

var_dump(NumberFormat::toFormattedString(0.041666666671517, '[MM]'));
```

**Comment by garrettgjb** [comment]
@PowerKiKi sorry, I'm new to github issue reporting process and didn't realize the problem was with toFormattedString.

**Comment by garrettgjb** [comment]
I did a little debugging and it looks like in an attempt to remove color information, we clear out the format variable so it doesn't go into the date format code.

From toFormattedString:

`
        $color_regex = '/^\\[[a-zA-Z]+\\]/';
        $format = preg_replace($color_regex, '', $format);
`
It goes from "[MM]" to ""

<img width="1417" alt="screen shot 2018-01-22 at 7 24 59 pm" src="https://user-images.githubusercontent.com/549725/35256724-059d470a-ffaa-11e7-828e-6b1a713f7c77.png">

I'm not an expert and regexp's and I don't know what color formatting looks like or I would attempt a fix.

**Comment by PowerKiKi** [comment]
I suggest you add a case for colors in `tests/data/Style/NumberFormat.php` and  case for `[MM]` in `tests/data/Style/NumberFormatDates.php` and keep trying to debug/fix it while testing `tests/PhpSpreadsheetTests/Style/NumberFormatTest.php`.

The following page should help you find out what syntaxes should be supported: https://support.office.com/en-us/article/create-or-delete-a-custom-number-format-78f2a361-936b-4c03-8772-09fab54be7f4

**Comment by oleibman** [comment]
Fixed by https://github.com/PHPOffice/PhpSpreadsheet/commit/699da091760d39ddc9f0656b507b7c26b9dc4f4b
