### ISSUE TITLE
ScatterPlot as DataSeries::STYLE_MARKER not implemented

### ISSUE THREAD

**Issue by cwolcott** [PHPOffice/PhpSpreadsheet#3428]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

A scatter plot without lines, only markers.  Below is an example created strictly in Excel
![image](https://user-images.githubusercontent.com/3777526/222443424-a5e0a5de-f90a-4027-bcb0-954ba9a4ec71.png)

### What is the current behavior?

<img width="945" alt="image" src="https://user-images.githubusercontent.com/3777526/222443731-96f1e024-0889-4f10-b520-99fbb5017e64.png">

I have written about this in an earlier issues [#1431](https://github.com/PHPOffice/PhpSpreadsheet/issues/1431), but it was at the beginning of COVID and against PhpSpreadsheet 1.10.1.  I had it working with my own modifications, but eventually it was marked as stale.  Others commented in 2020 and 2021 as to still having the issue.

I could try to look at it again a trace where the issue is occurring unless my comments from [#1431](https://github.com/PHPOffice/PhpSpreadsheet/issues/1431) gives enough clues for you all to fix.

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [x] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Only testing in Xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.28.0
Php 8.1.3

**Comment by oleibman** [comment]
We have some samples which create a scatter chart with markers and without lines, e.g. 33_chart_create_scatter6_value_axis. Can you compare what you are doing with what that sample is doing to see what might be different. I believe the code in the sample which does this is:
```php
$dataSeriesValues = [
    new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Data!$A$2:$A$' . count($results), Properties::FORMAT_CODE_NUMBER, 4, null, 'diamond', null, 7),
];

$dataSeriesValues[0]->setScatterLines(false); // Points not connected

$dataSeriesValues[0]->getMarkerFillColor()
    ->setColorProperties('accent1', null, ChartColor::EXCEL_COLOR_TYPE_SCHEME);
```

**Comment by cwolcott** [comment]
Thank you.  I was able to get it to work based on the example **33_chart_create_scatter6_value_axis**.

I have some other tasks to work on today and then I will put the final polishing touches onto the report.   Need to enable major gridlines with a light gray color like in the original image above (No issues, I got this one).
<img width="908" alt="image" src="https://user-images.githubusercontent.com/3777526/222735327-ae5c0cc7-86b0-4ef5-9eae-410aefd89f8e.png">

**QUESTION:** Does PhpSpreadsheet allow for drawing on the chart area?  The two red dash lines are drawn at 50 on both the x and y axis.
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/3777526/222735883-fde737bf-2949-4d31-bd7e-77edbee3d6ac.png">

**Comment by oleibman** [comment]
You might be able to get the effect you want with "combo" charts. See 33_chart_create_composite.php (perhaps you can adapt its code), or 32readwriteComboChart1.xlsx (perhaps you can analyze and adapt its xml).

**Comment by cwolcott** [comment]
Will take a look this weekend.
