### ISSUE TITLE
It does not accept the SUMPRODUCT SUBTOTAL OFFSET ROW formula, bug?

### ISSUE THREAD

**Issue by AdamovicBoban** [PHPOffice/PhpSpreadsheet#3432]
I have a problem with the formula, I'm not sure if it's a bug, PhpSpreadsheet doesn't accept my formula, when I insert it manually in excel then it works.
The formula is as follows:

```php
$spreadsheet->getActiveSheet()->setCellValue('F69',"=SUMPRODUCT(SUBTOTAL(109;OFFSET(J2;ROW(J2:J63)-ROW(J2);;1));--(I2:I63=D69))");
```
This is an excel example [https://dreamcode.dev/bug.xlsx](https://dreamcode.dev/bug.xlsx)

**### This is the error I am getting**

![errorr](https://user-images.githubusercontent.com/68257663/222776595-aa671a80-4eb6-4de7-9058-a8dc3fbe9806.png)

Has anyone had experience with something like this?

**Comment by MarkBaker** [comment]
From the [PhpSpreadsheet Documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/calculation-engine/):

 > When writing a formula to a cell, formulae should always be set as they would appear in an English version of Microsoft Office Excel, and PhpSpreadsheet handles all formulae internally in this format. This means that the following rules hold:
>
> - Decimal separator is . (period)
> - Function argument separator is , (comma)
> - Matrix row separator is ; (semicolon)
> - English function names must be used
 
You're using `;` as an argument separator
