### ISSUE TITLE
Xlsx Reader parse quotePrefix attribute error

### ISSUE THREAD

**Issue by littleylv** [PHPOffice/PhpSpreadsheet#3435]
This is:

- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
Load `quotePrefix` Correctly

### What are the steps to reproduce?

Source code: https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Reader/Xlsx.php#L621

test code:

```php
<?php
$str = '<cellXfs count="2">
<xf numFmtId="0" fontId="0" fillId="0" borderId="0" pivotButton="0" quotePrefix="0" xfId="0" />
<xf numFmtId="0" fontId="0" fillId="0" borderId="0" pivotButton="0" quotePrefix="1" xfId="0" /></cellXfs>';
$xml = new \SimpleXMLElement($str);
foreach ($xml->xf as $xfTag) {
    $xf = $xfTag->attributes();
    var_dump((bool) ($xf['quotePrefix'] ?? false)); // source code copied from Xlsx.php#L621
    var_dump($xf['quotePrefix']);
    var_dump((string)$xf['quotePrefix']);
    var_dump((bool)(string)$xf['quotePrefix']);
}

/*
the above code returns:
bool(true)
object(SimpleXMLElement)#7 (1) {
  [0]=>
  string(1) "0"
}
string(1) "0"
bool(false)

bool(true)
object(SimpleXMLElement)#6 (1) {
  [0]=>
  string(1) "1"
}
string(1) "1"
bool(true)
*/
```

the source xml has two xf tags with `quotePrefix="0"` and `quotePrefix="1"` but `var_dump((bool) ($xf['quotePrefix'] ?? false));` both return `true`.
Should `$xf['quotePrefix']` be converted to string first?

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: All
PHP: I am using 7.4.33

**Comment by oleibman** [comment]
I think that you are theoretically correct. Excel omits `quotePrefix` rather than including `quotePrefix="0"`; PhpSpreadsheet does the same. So, despite the theoretical exposure, we are probably okay. Which does not mean that it shouldn't be fixed - do you have an example where this is causing a problem? This particular code example occurs a second time in the module where you found it, and fortunately does not also occur in Reader/Xlsx/Styles.

**Comment by littleylv** [comment]
> Excel omits quotePrefix rather than including quotePrefix="0"

@oleibman You are right! My mistake.

I'm using PhpSpreadsheet for a long time without error until dealing with a file download from Amazon Sellercentral:

[ManifestFileUpload_Template_MPL.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/10904298/ManifestFileUpload_Template_MPL.xlsx)

It uses `quotePrefix="0"` in xl/styles.xml and after I load and save it, all cells has a `'`:

```php
include 'vendor/autoload.php';
$inputFileName = '/path/to/ManifestFileUpload_Template_MPL.xlsx';
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($inputFileName);
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save('/path/to/ManifestFileUpload_Template_MPL-new.xlsx');
```

**Comment by oleibman** [comment]
Thank you for the sample file. If you can test against PR 3438, please do so.

**Comment by littleylv** [comment]
I have confirmed that PR 3438 works correctly with my ManifestFileUpload_Template_MPL.xlsx
