### ISSUE TITLE
How to rotate a 3D bar chart

### ISSUE THREAD

**Issue by yikezh** [PHPOffice/PhpSpreadsheet#344]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I plot a 3D bar chart as below: 
![capture1](https://user-images.githubusercontent.com/30990743/35305704-8a1db52a-0057-11e8-8155-125a785d62a6.PNG)
But what I want is: 
![capture2](https://user-images.githubusercontent.com/30990743/35305720-9619628e-0057-11e8-8480-eb6ca313c6e3.PNG)
So, how to set the fields in Layout class to rotate a 3D chart

**Comment by PowerKiKi** [comment]
It seems this features does not exists yet. If this is important to you, please consider submitting a PR to add this feature.

**Comment by yikezh** [comment]
@PowerKiKi Could you tell me which variables are for chart rotation?

**Comment by PowerKiKi** [comment]
I don't know, you'll have to look for it

**Comment by MikhalevAY** [comment]
Is this issue solved? I have the same problem.

**Comment by oleibman** [comment]
The Chart object has properties rotX, rotY, rAngAx, and perspective, each with setter and getter, that can be used to rotate the chart.
