### ISSUE TITLE
Charts - Passing Custom $dataValues to DataSeriesValues

### ISSUE THREAD

**Issue by titansoftime** [PHPOffice/PhpSpreadsheet#3446]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Charts to represent custom values passed to $dataValues parameter.

### What is the current behavior?
Values are seemingly accepted but not rendered.

### What are the steps to reproduce?
This is based on the line graph example: https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Chart/33_Chart_create_line.php

Place null for $dataSources parameter and place an array of values for the $dataValues parameter of DataSeriesValues.

I have asked about this at StackOverflow already thinking it was a usage issue (it may be) and have not received a response. However, I did today see this issue raising the same exact issue. The apparent solution was exactly what I am trying to do (pass an array of values to $dataValues). That user had success apparently. Maybe there is an issue with line graphs? I do not know.

https://stackoverflow.com/questions/75607486/php-spreadsheet-charts-passing-data-values-instead-of-using-worksheet-data

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$dataSeriesValues = [

	// attempting to pass values to dataValues parameter	
        new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, 4, [15, 73, 61, 32]),
	new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, 4, [15, 73, 61, 32]),
	new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, 3, [86, 69, 55]),
	
	// original way using the workbook as a data source
	//new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$B$2:$B$5', null, 4),
        //new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$C$2:$C$5', null, 4),
        //new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$D$2:$D$5', null, 3),
	
];
```

### What features do you think are causing the issue

- [ ] Reader
- [x ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ x] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.4
phpspreadsheet 1.28 (just upgraded from 1.23 thinking that may solve it, it did not).

**Comment by titansoftime** [comment]
Ah... the issue is apparently open office. Excel (browser version) looks correct. I'm not sure if I should close this or not. Perhaps there is some formatting issue throwing off 3rd party xlsx readers that may warrant investigating? Your call lol!

**Comment by titansoftime** [comment]
So MS Excel is actually showing some values correctly when passed as $dataValues, but some are all over the place. I do not understand.

The 2021 values are fine. But starting as 2022 Q2, things are off. 2023 looks way off. Am I doing something wrong here? Sorry if this is in the wrong place but I really need help.

![image](https://user-images.githubusercontent.com/6549763/224172306-57e11207-f857-4fd5-8863-c42ab24d1b3b.png)


```
$dataSeriesLabels = [

	new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, 1, ['2021']), 
	new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, 1, ['2022']), 
	new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, 1, ['2023'])

];

$dataSeriesLabels[0]->setFillColor('FF0000');

// Set the X-Axis Labels
//     Datatype
//     Cell reference for data
//     Format Code
//     Number of datapoints in series
//     Data values
//     Data Marker
$xAxisTickValues = [
    new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, null, null, 4, ['Q1', 'Q2', 'Q3', 'Q4']), // Q1 to Q4	
];

// Set the Data values for each data series we want to plot
//     Datatype
//     Cell reference for data
//     Format Code
//     Number of datapoints in series
//     Data values
//     Data Marker
$dataSeriesValues = [

	// attempting to pass values to dataValues parameter	
        new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, 4, [20000, 40000, 60000, 30000]),
	new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, 4, [10000, 50000, 25000, 10000]),
	new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, null, null, 4, [30000, 10000, 50000, 20000]),

];

$dataSeriesValues[2]->setLineWidth(60000 / Properties::POINTS_WIDTH_MULTIPLIER);

// Build the dataseries
$series = new DataSeries(
    DataSeries::TYPE_LINECHART, // plotType
    DataSeries::GROUPING_STACKED, // plotGrouping
    range(0, count($dataSeriesValues) - 1), // plotOrder
    $dataSeriesLabels, // plotLabel
    $xAxisTickValues, // plotCategory
    $dataSeriesValues        // plotValues
);

// Set the series in the plot area
$plotArea = new PlotArea(null, [$series]);
// Set the chart legend

$legend = new ChartLegend(ChartLegend::POSITION_TOPRIGHT, null, false);

$title = new Title('Test Stacked Line Chart');
$yAxisLabel = new Title('Value ($k)');

// Create the chart
$chart = new Chart(
    'chart1', // name
    $title, // title
    $legend, // legend
    $plotArea, // plotArea
    true, // plotVisibleOnly
    DataSeries::EMPTY_AS_GAP, // displayBlanksAs
    null, // xAxisLabel
    $yAxisLabel  // yAxisLabel
);

// Set the position where the chart should appear in the worksheet

$chart->setTopLeftPosition('A7');
$chart->setBottomRightPosition('H20');

// Add the chart to the worksheet
$worksheet->addChart($chart);

// Save Excel 2007 file
$filename = 'test_line';
$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->setIncludeCharts(true);

// Redirect output to a client’s web browser (Excel5)
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="line.xlsx"');

$writer->save('php://output');
```

**Comment by oleibman** [comment]
I think your problem is that this is a "stacked" line chart. I am not 100% confident in this explanation, but I believe that 2010 Q1 shows a value of 12; 2011 Q1 shows a value of 15 *plus* the value of 2010 Q1, so 27 in all; and 2012 Q1 shows a value of 21 plus the other Q1 values, so 48 in all. Similarly for Q2 (56, 129, 217), Q3, and Q4.

**Comment by MarkBaker** [comment]
That's correct: it's because this is a stacked chart, with each set of X-axis values stacked on top of each other. The 2021 line is baseline values for 2021; the red line is _cumulative_ 2021Qx+2022Qx; and the green line is _cumulative_ 2021Qx+2022Qx + 2023Qx.

**Comment by titansoftime** [comment]
Ahh. I see. I have changed the plotGrouping parameter of DataSeries to GROUPING_STANDARD vs. GROUPING_STACKED and it now works perfectly!!! Thank you! A weight has been lifted!

So this wound up being a 3rd party excel software issue and a usage issue... Sorry about that. I will close this. Thanks again for all the help here!

**Comment by MarkBaker** [comment]
This particular chart would probably seem more meaningful as a stacked chart if your X-axis was by year, and you stacked by Quarter; making it cumulative for the year; but I find that reading a stacked chart is normally more intuitive for column or area charts than for line charts.

**Comment by titansoftime** [comment]
> 

No doubt haha. I didn't know stacked charts were a thing lol. I just copy pasted the line graph code from the examples here =]
