### ISSUE TITLE
Alignment not working with default style array

### ISSUE THREAD

**Issue by SantiagoToledo** [PHPOffice/PhpSpreadsheet#3456]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Set default style to alignment to spreadsheet. 
### What is the current behavior?
Ignoring default style. Its currently ignoring horizontal and vertical alignment. And also ignoring wrap property

### What are the steps to reproduce?
It stoped working going from v1.27.0 to v1.28.0

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$styleArray = [
	'alignment' => [
		'horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER,
		'vertical' => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER,
		'wrapText' => true,
	],
];
$spreadsheet->getDefaultStyle()->applyFromArray($styleArray);
```

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
php 7.4.32 
PhpSpreadsheet v1.27.0

**Comment by oleibman** [comment]
Confirmed, regression due to PR #3372. Fix available shortly.
