### ISSUE TITLE
interface file CacheInterface bug

### ISSUE THREAD

**Issue by SealinGp** [PHPOffice/PhpSpreadsheet#346]
CacheInterface.php is not included in this project, but It was used in /src/Collection/Memory.php, such as 
class Memory implements CacheInterface, but when i used this ,It throw an issue said that  " Interface 'Psr\SimpleCache\CacheInterface' not found "

**Comment by SealinGp** [comment]
I'm sorry about my knowledge~~I've written the interface myself ,and It worked ,I was new here ~

**Comment by meclg** [comment]
I have the same problem.Can you tell me how to solve it?Sorry to be a nuisance

**Comment by SealinGp** [comment]
Hi, It's simple, just write the file ,and put it in the relevant place(or dir). The interface needs to be written the same function with Memory.php file , you can connact me with email if you still don't understand about this question~ sealingp@163.com

**Comment by PowerKiKi** [comment]
Don't write the class yourself. Instead [follow the install instruction](http://phpspreadsheet.readthedocs.io/en/develop/#installation).

**Comment by meclg** [comment]
Thank you. I wrote a interface CacheInterface,namespace Psr\SimpleCache.now, Can be read .xlsx file.I don't know if it's going to be a problem in the future.

**Comment by PowerKiKi** [comment]
Not following the official documentation for installation will end up being a problem at some point. You should delete your code and install it properly.

**Comment by meclg** [comment]
Ok,thank you.I install composer first.Hope that the official documents are more detailed
