### ISSUE TITLE
NETWORKDAYS function erroneously being converted to NETWORK_xlfn.DAYS by phpspreadsheet

### ISSUE THREAD

**Issue by dwbrott** [PHPOffice/PhpSpreadsheet#3461]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The Excel function "NETWORKDAYS" outputs correctly in the Excel XLSX output

### What is the current behavior?
When using the function NETWORKDAYS in a cell, it is replaced with NETWORK_xlfn.DAYS

### What are the steps to reproduce?

      $ws->setCellValue($c.($keyrow+2),
        "=NETWORKDAYS(".$c.$keyrow.",".$c.($keyrow+1).")");

### What features do you think are causing the issue

- [ ] Reader
- [*] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

Unsure as I only output XLSX format.

### Which versions of PhpSpreadsheet and PHP are affected?
1.28.0

-- Note, I fixed this issue for myself (in a decidedly poor way) by modifying Writer/Xlsx/FunctionPrefix.php
I commented out one row in the file:

```
        . '|csch'
#        . '|days'
        . '|dbcs'
```

The function addXlfnPrefix is being overly aggressive and while it may be correct to modify the "DAYS" function to be "_xlfn.DAYS" the preg_replace is also doing this to the "NETWORKDAYS" by converting it to "NETWORK_xlfn.DAYS" which it either (1) should not do or (2) should do it correctly.

My workaround is fine for my situation, but this will likely cause others problems as well.

**Comment by MarkBaker** [comment]
A simple 2-character change, establishing a word boundary condition in the regexp: it took my longer to write the unit tests than it did to write the fix ;-)

**Comment by oleibman** [comment]
Closing, fixed by PR 3463.
