### ISSUE TITLE
Error gets thrown when Xlsx zip uses Windows directory separator

### ISSUE THREAD

**Issue by cameronjohnson-mz** [PHPOffice/PhpSpreadsheet#3472]
This is:

```
- [ X]([url](url)) a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I should be able to parse cells with line breaks.

### What is the current behavior?
The package throws and exception because there's a row with multiple cells with line breaks. When I remove the row with line breaks it starts working again.

[2023-03-20 19:19:18] local.ERROR: Could not find zip member zip:///tmp/phpANFbmg#_rels/.rels {"userId":3,"exception":"[object] (PhpOffice\\PhpSpreadsheet\\Reader\\Exception(code: 0): Could not find zip member zip:///tmp/phpANFbmg#_rels/.rels at /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/File.php:159)
[stacktrace]
#0 /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php(408): PhpOffice\\PhpSpreadsheet\\Shared\\File::assertFile()
#1 /var/www/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/BaseReader.php(166): PhpOffice\\PhpSpreadsheet\\Reader\\Xlsx->loadSpreadsheetFromFile()
#2 /var/www/html/app/Utils/Util.php(382): PhpOffice\\PhpSpreadsheet\\Reader\\BaseReader->load()

### What are the steps to reproduce?

Try uploading the attached XLSX file. I don't believe there's a problem with the file or the code, the package just can't parse the cell with line breaks. 

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$reader = PhpExcel::createReader('Xlsx');
$spreadsheet = $reader->load($file);
```
[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/11024492/test.xlsx)

If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [X] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?

PHP 8.1.16
phpoffice/phpspreadsheet * 1.25.2

**Comment by MarkBaker** [comment]
There should be no problems with cells containing line breaks, it's just a normal character.

But your sample file loads without any issues:
```
$ php testing/readerTest.php
File LineBreaks.xlsx Identified as Xlsx
Loading File LineBreaks.xlsx using Xlsx Reader

Call time to load spreadsheet file was 0.0360 seconds
Max Row: 1000, Max Column: Z
Max Data Row: 3, Max Data Column: U
 Current memory usage: 8192 KB
    Peak memory usage: 8192 KB
```

**Comment by cameronjohnson-mz** [comment]
That's odd, it worked for me too. Here's the original XLSX which **shouldn't** work.
[ffane_email_jpn.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/11057020/ffane_email_jpn.xlsx)

**Comment by MarkBaker** [comment]
It doesn't appear to be anything to do with blank lines.

And if Excel can read it, then it's technically valid; although in this case, highly unusual.

An Xlsx file is a zip file containing a collection of XML files; and normally it contains a relationship file `_rels/.rels` for each main component file, identifying all its related files. If I unzip the Xlsx, then I can see those relationship files where I'd expect; but for some reason the Zip Reader can't access them.

However, a closer look revealed the reason why PhpSpreadsheet can't read them.
A standard `xlsx` file uses the unix `/` as a folder separator inside the zip archive (no matter how or where it was created); this file is using the Windows `\` instead. So the relationship file isn't `_rels/.rels`, it's `_rels\.rels`; the workbook file isn't `xl/workbook.xml`, it's `xl\workbook.xml`; etc.

**Comment by MarkBaker** [comment]
I have a potential fix for this; but it's going to need a lot of testing to ensure that I don't break anything for normal Xlsx files

**Comment by oleibman** [comment]
Closing, issue appears to have been resolved five months ago.
