### ISSUE TITLE
Hard to extend functionality

### ISSUE THREAD

**Issue by jasverix** [PHPOffice/PhpSpreadsheet#348]
This is:

```
- [ ] a bug report
- [ x ] a feature request
```

### What is the expected behavior?
I have some problems with formulas referencing columns in a table in excel. The formula looks like this: ```@[FirstName] & @[LastName]```.

I also have another problem where an Excel document exported from another system have invalid data zoomScaleNormal="0".

I have fixed both problems in an inherited class of Spreadsheet - but it is hard to implement, because the load() method for instance creates a ```new Spreadsheet()```. In simplexml_load_string() it is possible to specify classname. Is it possible to implement something like this? Or maybe a ```public static fuction setSpreadsheetClass(string $className)```

**Comment by jasverix** [comment]
#349 - a proposal how it could be solved.

**Comment by PowerKiKi** [comment]
It would probably better to fix bugs in the core, for everybody, rather than trying to fix them in a custom class that is actually hard to implement.

**Comment by jasverix** [comment]
I agree... the problem is that my fix is too quick and should not be implemented in this project. But I will try to make PRs on the problems sometime soon.
