### ISSUE TITLE
"Invalid page format" Exception when exporting as a PDF with $sheet->getPageSetup()->setPaperSize('USLETTER');

### ISSUE THREAD

**Issue by lindymad** [PHPOffice/PhpSpreadsheet#3491]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The paper size should be set to USLETTER and no error should be thrown

### What is the current behavior?
An error is thrown with the message "Invalid page format: ".
Note - If I change the code to `$sheet->getPageSetup()->setPaperSize(1);` then it works

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$sheet = $spreadsheet->getActiveSheet();
$sheet->getPageSetup()->setPaperSize('USLETTER');

\PhpOffice\PhpSpreadsheet\IOFactory::registerWriter('Pdf', \PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf::class);
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, "Pdf");

$writer->save('php://output');

```

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
PDF

### Which versions of PhpSpreadsheet and PHP are affected?
I found the issue in PHPSpreadsheet 1.28.0 / PHP 7.4. It was working fine in PHPSpreadsheet 1.2.1 / PHP 7.4

**Comment by oleibman** [comment]
setPaperSize takes an integer argument, not a string. The following should work:
```php
$sheet->getPageSetup()->setPaperSize(\PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_LETTER);
```
Unsurprisingly, that constant has a value of 1, which is what you said above that you were using as a workaround.

**Comment by MarkBaker** [comment]
You can find the set of valid constants defined in the [`PageSetup` class](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Worksheet/PageSetup.php#L83)
