### ISSUE TITLE
composer 1.1.0 tag

### ISSUE THREAD

**Issue by Gemorroj** [PHPOffice/PhpSpreadsheet#351]
update [packagist.org](https://packagist.org/packages/phpoffice/phpspreadsheet) to view 1.1.0 version

**Comment by PowerKiKi** [comment]
I am aware that something went wrong, unfortunately I don't have access to packagist. I am waiting for @MarkBaker's help on that... Or maybe @Progi1984 could add me on packagist too ?

**Comment by Progi1984** [comment]
If @MarkBaker is 🆗 , I can give you access :)

**Comment by PowerKiKi** [comment]
Solved https://packagist.org/packages/phpoffice/phpspreadsheet#1.1.0

Thanks !
