### ISSUE TITLE
Error when creating RichText on Spreadsheet. getFont return null instead Font Class

### ISSUE THREAD

**Issue by owaisahmed5300** [PHPOffice/PhpSpreadsheet#3514]
Class NameSpace: PhpOffice\PhpSpreadsheet\RichText
Method: getFont()
Error: Return null instead \PhpOffice\PhpSpreadsheet\Style\Font Class.

When trying to work on rich text
$rich_text = new PhpOffice\PhpSpreadsheet\RichText\RichText();
$text = $rich_text->createText( 'Test' );
$text->getFont()->setBold( true );
$text->getFont()->setItalic( true );
$text->getFont()->setColor( \PhpOffice\PhpSpreadsheet\Style\Color::COLOR_GREEN );

**Comment by MarkBaker** [comment]
Replace `$text = $rich_text->createText( 'Test' );` with `$text = $rich_text->createTextRun( 'Test' );`

**Comment by owaisahmed5300** [comment]
Thanks that works! but this should return the correct Font Class in both ways.

**Comment by MarkBaker** [comment]
> Thanks that works! but this should return the correct Font Class in both ways.

No! They're two different things. Text is unstyled (raw) text that inherits all its font styling from the cell; a Text Run is text that has its own styling that overrides the cell style.
You shouldn't be able to override the styling of Text, only of Text Runs.

**Comment by owaisahmed5300** [comment]
Ok,
But in PHPDOC it says that it could return Font Class or null, but, when calling getFont() method from getText() instead getTextRun(). it always returns null. It's better to update PHP Doc then.
