### ISSUE TITLE
A simple scatter chart with no lines does not display correctly

### ISSUE THREAD

**Issue by GajowyJ** [PHPOffice/PhpSpreadsheet#3519]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
When creating a scatter chart with no lines, e.g. using
`$servalues->setScatterLines(FALSE);`
the marker also is not displayed.

### What is the expected behavior?
I would like to see a scatter chart containing only points.

### What is the current behavior?
If I switch off line display, the point are not displayed neither.

### What are the steps to reproduce?

Create a spreadsheet and scatter chart with serieValues and set
setScatterLines(FALSE);
for this serie.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [X] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
I tested with *.xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 8.1.17 (TS/Windows/64-bit) 
PhpSpreadsheet 1.27.0

### Workaroud/proposed solution
1. Add following method to DataSeriesValues class:
```
public function setMarkerFillColor(string $color): void
{
	$this->markerFillColor = new ChartColor($color);
}

```
2. Set the marker's color value for the data serie:
`$servalues->setMarkerFillColor('000000');`

**Comment by oleibman** [comment]
In sample 33_Chart_create_scatter3, two of the three dataSeriesValues show both the line and the markers, and the other shows the marker without the lines. If you are seeing a different result, can I see your spreadsheet/code to see how it differs from the sample.

BTW, that sample also demonstrates that what you want to add (setting the marker fill color) is essentially there already:
```php
// series 3 - markers, no line
$dataSeriesValues[2] // triangle fill
    //->setPointMarker('triangle') // let Excel choose shape
    ->setPointSize(7)
    ->getMarkerFillColor()
    ->setColorProperties('FFFF00', null, ChartColor::EXCEL_COLOR_TYPE_RGB);
```

**Comment by GajowyJ** [comment]
Thank you, that works. The problem was that setting a marker fill color in the way you described is not intuitive for me, and - if not set - probably a white color was used as a default.
