### ISSUE TITLE
Black empty cells after writting

### ISSUE THREAD

**Issue by TheSoundOfTNT** [PHPOffice/PhpSpreadsheet#355]
This is:

```
- [ ] a bug report
```

### What is the expected behavior?

The same blank cell background as before writing.

### What is the current behavior?

After setting a value and saving content to file all empty cells have a black background.

### Which versions of PhpSpreadsheet and PHP are affected?
php 7.1
spreadsheat 1.1.0

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue without relying on an external Excel file.

I'll re-open the issue once the MCVe is provided.
