### ISSUE TITLE
Unable to carry forward MS excel Theme colors in phpspreadsheet 

### ISSUE THREAD

**Issue by HenisPatel** [PHPOffice/PhpSpreadsheet#3550]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by oleibman** [comment]
Your description is very vague. Can you upload a spreadsheet which demonstrates your problem, and tell us what you think is wrong with it? FWIW, PR #3476 added better support for theme colors. For compatibility reasons, it defaults to Excel 2007-2010 colors, but it is very easy to switch to Excel 2013+ colors.
```php
$spreadsheet->getTheme()->setThemeColorName(SpreadsheetTheme::COLOR_SCHEME_2013_PLUS_NAME);
```

**Comment by HenisPatel** [comment]
Cell A1 background color and font color is theme color.
i can't get this color code or theme color name file import time.
i am using laravel.

**Comment by HenisPatel** [comment]
Cell B2 background color and font color is theme color.
i can't get this color code or theme color name file import time.
i am using laravel.
[Roster_01.May-07.May.2023.xls](https://github.com/PHPOffice/PhpSpreadsheet/files/11398506/Roster_01.May-07.May.2023.xls)

**Comment by oleibman** [comment]
The file you uploaded is xlsx, not xls (as implied by the file name). This is not a big deal. You still weren't specific about the problem you were seeing, but I think I can make a guess now. If PhpSpreadsheet loads your spreadsheet and saves it as a new one, the background color for cell B2 does not quite match. Please confirm if my guess is correct.

There may be a problem in our "tint" calculation. @MarkBaker, are you familiar with `Style/Color/changeBrightness`? A web page describing tint, https://c-rex.net/samples/ooxml/e1/Part4/OOXML_P4_DOCX_fgColor_topic_ID0EX1B6.html, uses an algorithm which doesn't resemble our code, and it is difficult for me to see how we might even adapt it (if our existing code is wrong). Here's what I know about this situation:
- In the uploaded spreadsheet, cell B2 has a fillColor of `538dd5`. In an ideal world, the result of changeBrightness would be this value, or at least close to it.
- In the xml, that cell uses a style which specifies `<fgColor theme="3" tint="0.39997558519241921"/>`.
- I believe theme 3 is 'dk2', which has an rgb value in the xml of `1F497D`.
- In the spreadsheet which results from load and save, cell B2 has a fillColor of `78d1b0`.
- I wrote a program to list all `256*256*256` values for the result of changeBrightness.
- That program confirms that the result of changeBrightness given an input of `1F497d` is `78d1b0`.
- However, not a single changeBrightness result begins with 5, let alone matches our target value of `538dd5`.

**Comment by HenisPatel** [comment]
Please, can you give me an example ?

**Comment by oleibman** [comment]
The theme color is converted to rgb (possibly incorrectly when tint is applied). It is not available to the application.

**Comment by oleibman** [comment]
The Python code at https://gist.github.com/Mike-Honey/b36e651e9a7f1d2e1d60ce1c63b9b633 for converting theme/tint to rgb gets us quite close to our target (final value is `558ed5` rather than `538dd5`). It can probably be adapted to Php; I'm not sure that the effort is worthwhile.

**Comment by HenisPatel** [comment]
Got it.

**Comment by HenisPatel** [comment]
Thank you

**Comment by HenisPatel** [comment]
$sheet->setDataValidation($r_cell_address, (new
\PhpOffice\PhpSpreadsheet\Cell\DataValidation())
                        ->setType(\PhpOffice\PhpSpreadsheet\Cell\
DataValidation::TYPE_LIST)
                        ->setErrorStyle(\PhpOffice\PhpSpreadsheet\Cell\
DataValidation::STYLE_INFORMATION)
                        ->setAllowBlank(false)->setShowInputMessage(true)->
setShowErrorMessage(true)->setShowDropDown(true)
                        ->setErrorTitle('Input error')->setError('Value is
not in list.')
                        ->setPromptTitle('Pick from list')->setPrompt('Please
pick a value from the drop-down list.')
                        ->setFormula1('"Entry Level,Leadership"')
                    );


i can't use array in setFormula1.
How to use array in setFormula1 can you guide me in php?

**Comment by MarkBaker** [comment]
Sorry I've not been active here much lately; real life issues can be a real problem.

The original algorithm used for tint with themes was found through trial and error, enough to try and get close to the expected shade in most cases, but there was nothing that I could find that described the actual algorithm used, so there was nothing that I could base it on. I'm pleased to know that python now has a more accurate algorithm, and at some point we should implement it for PhpSpreadsheet. So I'll leave this Issue open until that time.

For the additional issue with data validation and lists from an array, I've opened a [separate issue](https://github.com/PHPOffice/PhpSpreadsheet/issues/3579)
