### ISSUE TITLE
ISFORMULA() not recognized / throws exception

### ISSUE THREAD

**Issue by billynoah** [PHPOffice/PhpSpreadsheet#356]
ISFORMULA() not recognized and throws exception.  Steps to reproduce.  Create a new spreadsheet.  In the cell A1 enter

    =ISFORMULA(B1)

The result should be `FALSE` and is valid.  Try loading the spreadsheet in PhpSpreadsheet and read cells like this:

```
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($filename);
$rows = $spreadsheet->getSheet($sheet)->toArray();
```

Results in an exception:

> Sheet1!A1 -> undefined named range / function '_xlfn.ISFORMULA'

Related: https://github.com/PHPOffice/PHPExcel/issues/1136

[formula_test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1689719/formula_test.xlsx)

**Comment by PowerKiKi** [comment]
I can reproduce it with:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$cell = $sheet->getCell('A1');
$cell->setValue('=ISFORMULA(B1)');
var_dump($cell->getCalculatedValue());
```

Would you like to submit a PR to add support for `ISFORMULA` ?
