### ISSUE TITLE
setCellValueExplicit formatting eliminated once you delete or insert a row/column

### ISSUE THREAD

**Issue by northtron** [PHPOffice/PhpSpreadsheet#3560]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Once setting a Cell Value Explicitly, I would expect that explicit formatting to remain on the value when altering rows/columns later on that might move or shift the original data.
eg. I have text data formatting with leading zeroes: 00412100021400000, that if handled by default would remove leading zero, and treat as a number, unless Explicity Set.

### What is the current behavior?
If you set a Cell Value Explicitly, then perform an InsertNewRowBefore() or removeColumnByIndex() type of function, the Explicit Cell Value formatting is lost, and it reverts back to a default number.

eg: 00412100021400000 as text set explicitly as Cell Value, reverts to a number, 412100021400000 if a row/column is added or removed later on in the script.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$spreadsheet->getActiveSheet()->setCellValueExplicit('A1', "00412100021400000", \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);  //set the value explicitly, and properly show a numeric as text

$spreadsheet->getActiveSheet()->insertNewRowBefore(1); // adding a new row will reset the Cell Value (now A2) to a number, and removes the Explicit type formatting.
```

If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [] Styles
- [X] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
PHP version 7.1.
uncertain PHPSpreadsheet version to be honest, but my timestamps shows May 2019 from when downloaded

**Comment by MarkBaker** [comment]
Unable to replicate:
```php
$worksheet = $spreadsheet->getActiveSheet();

$spreadsheet->getActiveSheet()
    ->setCellValueExplicit('A1', "00412100021400000", \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);  //set the value explicitly, and properly show a numeric as text

echo 'CELL A1', PHP_EOL;
var_dump(
    $spreadsheet->getActiveSheet()->getCell('A1')->getDataType(),
    $spreadsheet->getActiveSheet()->getCell('A1')->getValue(),
    $spreadsheet->getActiveSheet()->getCell('A1')->getStyle()->getNumberFormat()->getFormatCode()
);

echo 'Insert new row, A1 becomes A2', PHP_EOL;
$spreadsheet->getActiveSheet()->insertNewRowBefore(1); // adding a new row will reset the Cell Value (now A2) to a number, and removes the Explicit type formatting.

echo 'CELL A2', PHP_EOL;
var_dump(
    $spreadsheet->getActiveSheet()->getCell('A2')->getDataType(),
    $spreadsheet->getActiveSheet()->getCell('A2')->getValue(),
    $spreadsheet->getActiveSheet()->getCell('A1')->getStyle()->getNumberFormat()->getFormatCode()
);
```

gives me

```
CELL A1
string(1) "s"
string(17) "00412100021400000"
string(7) "General"
Insert new row, A1 becomes A2
CELL A2
string(1) "s"
string(17) "00412100021400000"
string(7) "General"
```
Which is exactly what I would expect. The value is still a string, datatype still says that it's a string, and the format code remains unchanged.

I'm testing against current `master`, but this is something that should always have worked since the very earliest release, and even back to PHPExcel days.

**Comment by MarkBaker** [comment]
Note that data validation relates to the Excel data validation feature, restricting the values that can be set for a cell

**Comment by northtron** [comment]
When opened in MS Excel though, it switches the explicit TEXT format to
General, and the cell is rendered as a Number, with leading zero stripped
though. At least in my testing on the exported XLSX file.

The underlying data in the cell is correct if you click into it, however it
is displayed as a number, leading zero removed, and because it's large, as
an exponent nomenclature.

Note your $spreadsheet->getActiveSheet()->getCell('A1')->getStyle()->g
etNumberFormat()->getFormatCode() returns General.
Shouldn't this be some type of TEXT formatting, to match the explicit
DataType::TYPE_STRING

**Comment by MarkBaker** [comment]
> When opened in MS Excel though, it switches the explicit TEXT format to General,
> and the cell is rendered as a Number, with leading zero stripped though. At least
> in my testing on the exported XLSX file.
>
What explicit text format? Your demonstration code doesn't set any text format.

> Note your `$spreadsheet->getActiveSheet()->getCell('A1')->getStyle()->getNumberFormat()->getFormatCode()`
> returns General. Shouldn't this be some type of TEXT formatting, to match the explicit DataType::TYPE_STRING
>
No. The default Excel formatting is `General`, which is why we use that. `General` should work with all datatypes.
If you want an explicit text format, then that's something you should specify yourself.

**Comment by MarkBaker** [comment]
I'm still unable to replicate, even when I save the file:
![image](https://user-images.githubusercontent.com/770298/236871512-8c3726a7-d082-4526-b0e4-78edcdec6d87.png)
The value in Cell A2 appears as I would expect it to appear.

**Comment by northtron** [comment]
closing issue, as contributor cannot duplicate. 
must be a local issue I'm having, and will complete more testing.
