### ISSUE TITLE
Phpspreadsheet wont build on graviton ARM64 

### ISSUE THREAD

**Issue by ivanbishop** [PHPOffice/PhpSpreadsheet#3562]
This is:

```
- [ X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I expected composer install to build the package

### What is the current behavior?
composer require phpoffice/phpspreadsheet --prefer-source

Info from https://repo.packagist.org: #StandWithUkraine

./composer.json has been updated
Running composer update phpoffice/phpspreadsheet
Loading composer repositories with package information
Updating dependencies
Lock file operations: 11 installs, 0 updates, 0 removals
  - Locking ezyang/htmlpurifier (v4.16.0)
  - Locking maennchen/zipstream-php (2.2.6)
  - Locking markbaker/complex (3.0.2)
  - Locking markbaker/matrix (3.0.1)
  - Locking myclabs/php-enum (1.8.4)
  - Locking phpoffice/phpspreadsheet (1.28.0)
  - Locking psr/http-client (1.0.2)
  - Locking psr/http-factory (1.0.2)
  - Locking psr/http-message (1.1)
  - Locking psr/simple-cache (1.0.1)
  - Locking symfony/polyfill-mbstring (v1.27.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 11 installs, 0 updates, 0 removals
  - Syncing myclabs/php-enum (1.8.4) into cache
  - Syncing psr/simple-cache (1.0.1) into cache
  - Syncing psr/http-message (1.1) into cache
  - Syncing psr/http-factory (1.0.2) into cache
  - Syncing psr/http-client (1.0.2) into cache
  - Syncing markbaker/matrix (3.0.1) into cache
  - Syncing markbaker/complex (3.0.2) into cache
  - Syncing symfony/polyfill-mbstring (v1.27.0) into cache
  - Syncing maennchen/zipstream-php (2.2.6) into cache
  - Syncing ezyang/htmlpurifier (v4.16.0) into cache
  - Syncing phpoffice/phpspreadsheet (1.28.0) into cache
  - Installing myclabs/php-enum (1.8.4): Cloning a867478eae from cache
  - Installing psr/simple-cache (1.0.1): Cloning 408d5eafb8 from cache
  - Installing psr/http-message (1.1): Cloning cb6ce4845c from cache
  - Installing psr/http-factory (1.0.2): Cloning e616d01114 from cache
  - Installing psr/http-client (1.0.2): Cloning 0955afe482 from cache
  - Installing markbaker/matrix (3.0.1): Cloning 728434227f from cache
  - Installing markbaker/complex (3.0.2): Cloning 95c56caa1c from cache
  - Installing symfony/polyfill-mbstring (v1.27.0): Cloning 8ad114f6b3 from cache
  - Installing maennchen/zipstream-php (2.2.6): Cloning 30ad6f93cf from cache
  - Installing ezyang/htmlpurifier (v4.16.0): Cloning 523407fb06 from cache
  - Installing phpoffice/phpspreadsheet (1.28.0): Cloning 6e81cf39bb from cache
7 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
3 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
Using version ^1.28 for phpoffice/phpspreadsheet

composer install

Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files
3 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

### What are the steps to reproduce?
run composer require on the package on ARM64 running PHP 8.1

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by ivanbishop** [comment]
ubuntu@liberation:~/composer/phpspreadsheet$ php new.php 
PHP Fatal error:  Uncaught
 Error: Class "PhpOffice\PhpSpreadsheet\Reader\Xlsx" not found in /home/ubuntu/composer/phpspreadsheet/new.php:54
Stack trace:
#0 {main}
  thrown in /home/ubuntu/composer/phpspreadsheet/new.php on line 54


Not really sure if it has built.... how do I check classes?

**Comment by MarkBaker** [comment]
The composer output doesn't indicate any problems.

You don't show the code that's in your `new.php` file. Are you including the composer `autoload.php` file from the `vendor` folder?

**Comment by ivanbishop** [comment]
Hi. Yes. What should 'pwd' be when trying to inclufe class? Do PATHS need to be absolute?


Thanks

Ivan

Sent from Nine
________________________________

**Comment by MarkBaker** [comment]
PHP should have an include path specified in php.ini that normally includes the cwd. Paths can be relative to that.

If `new.php` is in the folder where you ran your composer require command, then `vendor` should be a subfolder under that.
```php
require __DIR__ . '/vendor/autoload.php';
```

**Comment by ivanbishop** [comment]
Ah  I know PHP... I suspect its an .ini file issue Mark


Ill test tomorrow

930 here


Thanks for your help

ill sync tomorrow


Ivan

Sent from Nine
________________________________

**Comment by ivanbishop** [comment]
Setting 

require __DIR__ . '/vendor/autoload.php' ; 

seems to have fixed everything. 

Many thanks 



Ivan

**Comment by oleibman** [comment]
Closing. Issue seems to have been resolved as of May 13.
