### ISSUE TITLE
Viewport Implementation

### ISSUE THREAD

**Issue by kissadamfkut** [PHPOffice/PhpSpreadsheet#3565]
This is:

```
- [ ] a bug report
- [X] a feature request
- [X] **not** a usage question
```

Solution given in: https://github.com/PHPOffice/PhpSpreadsheet/commit/7f77c0ad940851b06cde7715d837e4d29205b6bc

Can I open a pull request?

### What is the expected behavior?
If an attribute is set to a html writer, then the given html should fit the width of the browser.

### What is the current behavior?
Nothing.

**Comment by MarkBaker** [comment]
Certainly you can submit a PR

Have a read of the [contributing guidelines](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/CONTRIBUTING.md), and please remember to include unit tests as part of the submission
