### ISSUE TITLE
Worksheet/Table/Column[Span] in XML reader

### ISSUE THREAD

**Issue by SlowFox71** [PHPOffice/PhpSpreadsheet#3569]
This is:

```
- [X] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Apply <Column> to the appropriate number of columns if the attribute ss:Span is given.

ss:Span simply instructs excel to repeat the <Column> definition the given number of times. <Column ss:Span="3"> will thus in total affect 4 columns. The attached example uses this to set colum widhts for A to D (this example is not hand-crafted but was created exactly like this by Excel).
[test.txt](https://github.com/PHPOffice/PhpSpreadsheet/files/11486885/test.txt)

### What is the current behavior?
ss:Span is ignored and <Column> applied to a single column

### What features do you think are causing the issue

- [X] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
XML format only

### Which versions of PhpSpreadsheet and PHP are affected?
all versions

**Comment by oleibman** [comment]
Thanks for the sample, I understand the request now. I am able to include this request in my PR.
