### ISSUE TITLE
mapping of XML document properties

### ISSUE THREAD

**Issue by SlowFox71** [PHPOffice/PhpSpreadsheet#3573]
This is:

```
- [ ] a bug report
- [X] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Parse <o:DocumentProperties> from XML files

### What features do you think are causing the issue

- [X] Reader

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
XML only

I finally managed to find an XSL of the office namespace used in DocumentProperties: https://schemas.liquid-technologies.com/Office/2003/?page=office_xsd.html

With this a mapping of tags to PhpSpreadsheet-methods should be straightforward. So far I identified:

Titel => setTitle()
Subject => setSubject()
Keywords => setKeywords()
Description => setDescription()
Author => setCreator()
LastAuthor => setLastModifiedBy()
Created => setCreated()
LastSaved => setModified()
Manager => setManager()
Company => setCompany()
Category => setCategory()

If have not found PhpSpreadsheet-equivalents so far for:

HyperlinkBase
Version

CustomDocumentProperties are supported as well - however somewhat strange with the property name as the tag name, the type as a dt-namespaced dt-Attribute and the value as the content (see example). The schema for dt namespace is also available at the url above, but I could only use types
"string", "dateTime.tz", "boolean" and "float"; anything else (even "int") was converted into "string" by my Excel365.

[test.txt](https://github.com/PHPOffice/PhpSpreadsheet/files/11507590/test.txt)

**Comment by MarkBaker** [comment]
@oleibman Thanks both to you and @SlowFox71 for picking up all these improvements to the Xml Reader.
It was written as an MVP, but so few people ever used the SpreadsheetML format that I never expanded it beyond that; but it's good to know that you've been working on all these improvements

**Comment by oleibman** [comment]
@SlowFox71 As far as I can tell, almost all of these are already supported. When I use PhpSpreadsheet to load your spreadsheet and save it as Xlsx, all the standard properties (except not yet supported HyperlinkBase) are present in the output file (and equal to the values in the input file); the same is true for all but one of the custom properties (DateProperty). I shall certainly look into DateProperty (and maybe see about adding HyperlinkBase, which I do see, but I don't see Version - where do you see it?). In the meantime, do your results differ from mine?

**Comment by oleibman** [comment]
Just to clarify about Version - I see it in the XML, but I don't see it listed as a Property (or Advanced Property) in Excel.

**Comment by oleibman** [comment]
HyperlinkBase is really interesting. All the other document properties are 'meta'; but HyperlinkBase is functional - if you supply a relative address for a link, Excel will use HyperlinkBase, if supplied, to convert to an absolute address. (Default is directory where spreadsheet is located.) Now, guess what? Excel messes up this processing for Xml spreadsheets. It gets it right for Xlsx. I don't know, or particularly care, about Xls for the moment. Gnumeric and Odt, and of course Csv, have no equivalent that I can find. Html allows for an equivalent `base` tag in the `head` section. I'll have to think about how far I want to go with this.

**Comment by SlowFox71** [comment]
> @SlowFox71 As far as I can tell, almost all of these are already supported.

Oh dear, my bad - sorry :-(
I am using an older version of PhpSpreadsheet (which does not support them) and was missing them due to the changed file structure.
