### ISSUE TITLE
Auto-tables and pivot tables

### ISSUE THREAD

**Issue by smartlara** [PHPOffice/PhpSpreadsheet#358]
Thanks for the awesome library.

However, is it possible to create an auto-table (like one created using Ctrl + D in Excel) or create a pivot tables? 

I know auto-tables can be mocked using library features but will not be the same as a real table.

**Comment by smartlara** [comment]
No it is not support question. You can consider as a feature request as I'm almost sure this feature is not found.

**Comment by Apezdr** [comment]
Can this be re-opened? I'd like to see Pivot Tables as a new feature.

**Comment by Apezdr** [comment]
@PowerKiKi

**Comment by PowerKiKi** [comment]
The best way to reopen the topic is by submitting a PR for it. If need be the discussion can be continued on this closed issue until somebody find enough time/motivation to implement it.
