### ISSUE TITLE
Line in StringTable::createStringTable() with PHP 8.1 throws "Implicit incompatible float to int conversion is deprecated"

### ISSUE THREAD

**Issue by rvaldezgarcia** [PHPOffice/PhpSpreadsheet#3581]
This is:

```
- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

The function StringTable::createStringTable() should be able handle floating point numbers in PHP 8.1+.

### What is the current behavior?

This line of the code throws the following: PHP Deprecated:  "**Implicit conversion from float-string "6.8" to int loses precision in ... on line ...**"

![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/10903407/48645c78-f383-43d7-bf10-e48e8816c5b0)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$column = 1;
$renglon = 1;

$objPHPExcel->getActiveSheet()->setCellValueExplicitByColumnAndRow($column,$renglon,111.111, DataType::TYPE_NUMERIC);


$filename = str_replace(array(" "), '_', trim($_SESSION["data_report"]["name"]))."_".date("YmdHis").".xlsx";
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8'); 
header("Content-Disposition: attachment;filename=$filename");
header('Cache-Control: max-age=0'); 

$writer = new Xlsx($spreadsheetl);

$writer->save('php://output');
```

### What features do you think are causing the issue

- [ ] Reader
- [ X ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

I'm using XLSX.

### Which versions of PhpSpreadsheet and PHP are affected?

Current PhpSpreadsheet
PHP 8.1

**Comment by oleibman** [comment]
Unable to duplicate problem with code as given. Is there additional code that you omitted from the code you provided? In particular, I don't see why a string table would even be involved because there is only one cell populated, and it has a numeric value, not a string. Also, I do not see where `"6.8"`, which is part of the reported message, would come from.

**Comment by rvaldezgarcia** [comment]
My mistake. The issue can closed as a coworker is unable to replicate the issue with his provided code.
