### ISSUE TITLE
Deprecation warnings in PHP 8.1 when opening XLSX files using the IOFactory

### ISSUE THREAD

**Issue by farrance** [PHPOffice/PhpSpreadsheet#3586]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
For there to be no deprecated warnings when opening a spreadsheet.

### What is the current behavior?
Deprecated warnings as follows...

```
DEPRECATED  trim(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 1680.
```

### What are the steps to reproduce?

- [ ] Install PHP 8.1
- [ ] Install PHPOffice/PhpSpreadsheet using composer

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\IOFactory::load( 'Spreadsheet.xlsx' );
```

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
XLSX

### Which versions of PhpSpreadsheet and PHP are affected?
^1.28

**Comment by oleibman** [comment]
Is it possible to provide a copy of the spreadsheet so that we can verify that any solution we apply fixes the problem?

**Comment by farrance** [comment]
Bizaarly, I'm now unable to recreate this. Feel free to marked as resolved.
