### ISSUE TITLE
Cell reading bug in Cell.php

### ISSUE THREAD

**Issue by fledoux** [PHPOffice/PhpSpreadsheet#3587]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
A cell reading

### What is the current behavior?
Crash

### What are the steps to reproduce?

ERROR - 2023-05-26 15:02:38 --> Error - syntax error, unexpected '=' in /var/www/vhosts/inauguration.sagarmatha.fr/httpdocs/fuel/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php on line 232

I replace line 232:

from
$binder ??= self::getValueBinder();
to
$binder = self::getValueBinder();

And now it works fine

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
I don't know

### Which versions of PhpSpreadsheet and PHP are affected?
phpoffice/phpspreadsheet 1.28.0

**Comment by MarkBaker** [comment]
What version of PHP are you running?
The Null Coalescence Assignment Operator was introduced in PHP 7.4
The minimum requirement for PhpSpreadsheet 1.28 is PHP 7.4, but it sounds as though you are running an earlier version

**Comment by oleibman** [comment]
Closing. No update in 3 months, no reason to think the suggested explanation is not correct.

**Comment by fledoux** [comment]
Bonjour,

Merci pour votre mail. Je suis actuellement en congé.

Pour toute rupture de services, je vous invite à contacter le support sur le site https://extranet.yellowcactus.com

Je ne manquerai pas de reprendre contact avec vous à compter du lundi 4 septembre 2023.

Très cordialement.
Frédéric Ledoux
