### ISSUE TITLE
Error to install PhpSpreadsheet

### ISSUE THREAD

**Issue by alfianwi97** [PHPOffice/PhpSpreadsheet#359]
I want to install PhpSpreadsheet at my linux server. I follow first instruction in https://phpspreadsheet.readthedocs.io/en/develop/ . It gone well in my localhost, but i got error when i tried to install it in server.

That instruction is : 
composer require phpoffice/phpspreadsheet

This is the error:
"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpoffice/phpspreadsheet ^1.1 -> satisfiable by phpoffice/phpspreadsheet[1.1.0].
    - phpoffice/phpspreadsheet 1.1.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.

  To enable extensions, verify that they are enabled in those .ini files:
    - /opt/alt/php70/etc/php.ini
    - /opt/alt/php70/link/conf/alt_php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
"

My PHP version is 7.0

**Comment by criztovyl** [comment]
As the error message tells: You are missing the mbstring extension, you will need to install it on your system.
