### ISSUE TITLE
FreezePanes in XML reader

### ISSUE THREAD

**Issue by SlowFox71** [PHPOffice/PhpSpreadsheet#3594]
> I will not be adding SplitHorizontal and its 4 associated items to my PR;
> it will need a lot more research.

I have been going through the trunk code and either am I missing something or PhpSpreadsheet does not (yet) understand *split* mode, even though it is still supported in modern Excel.

*Freeze* is supported, however, so this could be imported from XML as well. A pane is frozen if  (and only if) the /FreezePanes/ tag is present. In this case /SplitHorizontal/ and /SplitVertical/ determine the number of rows to be seen in the top-left pane (if any, otherwise the respective tag can be left out), /TopRowBottomPane/ and /LeftColumnRightPane/ determine the first row/column visible in the other panes.
Worksheet::freezePane() seems for me the corresponding method for all of those tags.

I could not find any method matching /ActivePane/, so perhaps this is not yet supported by PhpSpreadsheet.

A minimum example implementing this is here:
[freeze.txt](https://github.com/PHPOffice/PhpSpreadsheet/files/11616454/freeze.txt)
The top-left pane contains 2 rows (SplitHorizontal) and 6 columns (SplitVertical). The top-left cell of the bottom-right pane is set to row 11 and column 21 (U), as XML-values are 0-based.

A completely different thing is *splitting* which occurs if /FreezePanes/ is not used. /SplitHorizontal/ and /SplitVertical/ then specify offsets in *points* from the upper left corner to mark where the windows is split (with separate scroll bars for the left/right and top/bottom part). If PhpSpreadsheet does not support this, there is no use to care for this mode at the moment.

**Comment by oleibman** [comment]
I think it would be fairly easy to implement FreezePanes in the XML reader. I am changing the title of this issue to FreezePanes rather than SplitHorizontal. I encourage you to open a new feature request issue for implementing SplitHorizontal for both Xlsx and Xml (not sure if we have enough information to implement it for other formats).
