### ISSUE TITLE
Change column width not work

### ISSUE THREAD

**Issue by mzawodzinski** [PHPOffice/PhpSpreadsheet#3609]
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

```php
<?php
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet->getActiveSheet()->getColumnDimension('A')->setWidth(0.45, 'cm');
$spreadsheet->getActiveSheet()->getColumnDimension('J')->setWidth(0.45, 'cm');



$writer = new PhpOffice\PhpSpreadsheet\Writer\Ods($spreadsheet);
$writer->save(__DIR__ . '/test.ods');

```
This code should change width columns A and J. 
But Change A and B
![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/36850550/405cbb0c-d7b4-4fb4-970a-71fecece3381)

Jeśli spróbuję zmienić tylko J, to skrypt zmieni kolumnę A

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
phpoffice/phpspreadsheet:1.28.0
php:8.1

**Comment by oleibman** [comment]
Please upload file and/or code so that I can investigate.

**Comment by lukaszgasiorek** [comment]
@oleibman please, eample code to create XLSX from existsing file. Up to version 1.25 I can change column widths from 1.26 I can't.

[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/11734102/test.xlsx)

```
<?php
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;

$xlsxReader = new Xlsx();

$sheet = $xlsxReader->load('test.xlsx');
$sheet->setActiveSheetIndex(0);

$ws = $sheet->getActiveSheet();

$ws->getProtection()->setSheet(true);
$ws->getProtection()->setSort(true);
$ws->getProtection()->setInsertRows(true);
$ws->getProtection()->setFormatCells(true);

$writer = IOFactory::createWriter($sheet, 'Xlsx');
$writer->save('sheet-' . date('Ymd-His') . '.xlsx');
```

**Comment by oleibman** [comment]
I agree that this is a change in behavior. While I try to figure out what kind of fix is needed, you should be able to get the result you want via:
```php
$ws->getProtection()->setFormatColumns(false);
```
Most protection properties in the Excel file default to false. FormatColumns appears to default to true (and I assume FormatRows as well). I need to find some documentation to see if there are others.

**Comment by oleibman** [comment]
Here's the documentation:
```xml
<complexType name="CT_SheetProtection">
<attribute name="password" type="ST_UnsignedShortHex" use="optional"/>
<attribute name="sheet" type="xsd:boolean" use="optional" default="false"/>
<attribute name="objects" type="xsd:boolean" use="optional" default="false"/>
<attribute name="scenarios" type="xsd:boolean" use="optional" default="false"/>
<attribute name="formatCells" type="xsd:boolean" use="optional" default="true"/>
<attribute name="formatColumns" type="xsd:boolean" use="optional" default="true"/>
<attribute name="formatRows" type="xsd:boolean" use="optional" default="true"/>
<attribute name="insertColumns" type="xsd:boolean" use="optional" default="true"/>
<attribute name="insertRows" type="xsd:boolean" use="optional" default="true"/>
<attribute name="insertHyperlinks" type="xsd:boolean" use="optional" default="true"/>
<attribute name="deleteColumns" type="xsd:boolean" use="optional" default="true"/>
<attribute name="deleteRows" type="xsd:boolean" use="optional" default="true"/>
<attribute name="selectLockedCells" type="xsd:boolean" use="optional" default="false"/>
<attribute name="sort" type="xsd:boolean" use="optional" default="true"/>
<attribute name="autoFilter" type="xsd:boolean" use="optional" default="true"/>
<attribute name="pivotTables" type="xsd:boolean" use="optional" default="true"/>
<attribute name="selectUnlockedCells" type="xsd:boolean" use="optional" default="false"/>
</complexType>
```
I am not sure I can come up with a sensible approach that will not cause a lot of breaks to existing code. I will continue to think about it, but, for now, it would be best to explicitly set those Protections properties which you are interested in enabling or disabling. The version 25 code defaulted to its own set of initial values, and seems more likely to require you to explicitly set `true` when desired; the current code defaults to Excel's, and seems more likely to require you to explicitly set `false` when desired.
