### ISSUE TITLE
Sharing properties are reset when saving a spreadsheet

### ISSUE THREAD

**Issue by jessicamorin** [PHPOffice/PhpSpreadsheet#361]
This is:

- [x] a bug report

### What is the expected behavior?
Sharing properties are not modified after saving.

### What is the current behavior?
When manually turning on the "Shared Workbook" option in an excel spreadsheet, then loading and saving it with PHPSpreadsheet, the Shared Workbook will be turned off. 

### What are the steps to reproduce?
1) Create a stylesheet manually and turn on the Shared Workbook option
2) With PHPSpreadsheet, load the excel file
3) Save it 
4) Note that the Shared Workbook option is now turned off and that the file is now much smaller.  

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Load Spreadsheet object
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('/tmp/excel.xls');
$worksheet = $spreadsheet->getActiveSheet();
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xls');
$writer->save('/tmp/excel.xls');

```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP Spreadsheet 1.1.0. Php 7.0

**Comment by oleibman** [comment]
Although it still supports it, Excel has really moved on from sharing in this manner (see https://support.microsoft.com/en-us/office/about-the-shared-workbook-feature-49b833c0-873b-48d8-8bf2-c1c59a628534). We will not be introducing it into PhpSpreadsheet - sorry. Leaving issue closed, removing stale label.
