### ISSUE TITLE
Total mess in dependencies

### ISSUE THREAD

**Issue by webdenis77** [PHPOffice/PhpSpreadsheet#3611]
Hello, i can not install this package with PHP 8.1 and Laravel 10.
The errors are on screenshot.

![Screenshot_8](https://github.com/PHPOffice/PhpSpreadsheet/assets/2351520/fee469ef-99d9-4d8f-838f-919d6a96e680)

The old PHPExcel library installed fine, so I use the old one by far.

**Comment by MarkBaker** [comment]
So did you actually try what composer suggests in that screenshot, and us the `-W` option?
