### ISSUE TITLE
Cell.php: Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by FFCZ** [PHPOffice/PhpSpreadsheet#3613]
This is:

```
- [x] a bug report
```

php 8.2.6 + PhpSpreadsheet 1.28.0
my project , recently upgraded php 7.4 to 8.4, frequent errors occur when reading excel, but not found in old php 7.4

warning tips:
vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php
line: 393
msg: aa!N4 -> bb!O4 -> strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated

It may be an adaptation issue to the new environment. hope can be compatible it. thank you!

### What features do you think are causing the issue
```
- [x] Reader
```

**Comment by oleibman** [comment]
It would be helpful if you could upload the failing spreadsheet so that we can verify the problem and confirm that any fix that we make solves it.

**Comment by FFCZ** [comment]
[tax.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/11743503/tax.xlsx)

**Comment by FFCZ** [comment]
The Excel file I used will generate the same error during the PHP 8.2.6 test.
Checking the official document, in PHP 8.1, 'Passing null to non nullable internal function parameters is deprecated.'. 
https://www.php.net/releases/8.1/en.php
May be necessary to improve the relevant code, such as $aa? '' Or (string) $aa

`
$Reader = $path_info['extension'] === 'xls' ? new Xls() : new Xlsx();
            $Spreadsheet = $Reader->load($op_file);
            $sheet_num = $Spreadsheet->getSheetCount();
            for ($i = 0; $i < $sheet_num; $i++) {
                $Spreadsheet->setActiveSheetIndex($i);
                $Spreadsheet->getActiveSheet()->getPageSetup()->setOrientation(PageSetup::ORIENTATION_LANDSCAPE);
                $Spreadsheet->getActiveSheet()->getPageSetup()->setPaperSize(PageSetup::PAPERSIZE_A4);
                $Spreadsheet->getActiveSheet()->getPageSetup()->setFitToWidth(1);
                $Spreadsheet->getActiveSheet()->getPageSetup()->setFitToHeight(0);
                $Spreadsheet->getActiveSheet()->getPageMargins()->setTop(0.39);
                $Spreadsheet->getActiveSheet()->getPageMargins()->setRight(0.39);
                $Spreadsheet->getActiveSheet()->getPageMargins()->setLeft(0.39);
                $Spreadsheet->getActiveSheet()->getPageMargins()->setBottom(0.39);
            }
            $Writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($Spreadsheet);
            $Writer->save($op_file2);
            unset($Reader, $Writer);
`

**Comment by oleibman** [comment]
Thank you for the sample file. I am not sure what makes your spreadsheet so "special", but I definitely duplicate your problem.

**Comment by FFCZ** [comment]
Thanks for your reply. The null issue was caused by a change in the new version of PHP. 
And the formula is really a bit complicated. It is used by financial colleagues to calculate personal income tax.

**Comment by oleibman** [comment]
PR 3617 should eliminate the exceptions. It does not fix the incorrect internal calculations, which may or may not be adequate for your use case. I have used the debugging features available in PhpSpreadsheet, and cannot even see where it's going wrong, let alone how. Disabling branch pruning is a suggestion that has sometimes worked for Calculation problems, but it not only does not succeed here, it causes a new exception.
