### ISSUE TITLE
Artefacts with transparency in png drawing

### ISSUE THREAD

**Issue by artygrand** [PHPOffice/PhpSpreadsheet#3624]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?

In excel I can insert png image with transparency without problems

### What is the current behavior?
Problem is artefacts in transparent background, like in example below. This is one file made from 2 in Photoshop.<br/>Absolutely opaque, with grey zones.

![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/2451297/da92f920-bf04-46a8-bd5c-bec2aec10c44)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$sheet = $spreadsheet->getActiveSheet();

$stamp = MemoryDrawing::fromString($stamp_file);
$stamp->setName('Stamp');
$stamp->setHeight(120);
$stamp->setCoordinates('A2');
$stamp->setWorksheet($sheet);

$writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save($path);
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet  1.28
PHP 8.1

**Comment by oleibman** [comment]
You do not show how you arrived at the value in `$stamp_file`. Please compare your code to the following:
```php
        $stamp_file = file_get_contents('issue.3624.png'); // the file you uploaded above
        $stamp = PhpOffice\PhpSpreadsheet\Worksheet\MemoryDrawing::fromString($stamp_file);
```
Or, more simply (use drawing as-is rather than as memory drawing):
```php
        $stamp = new PhpOffice\PhpSpreadsheet\Worksheet\Drawing();
        $stamp->setPath('issue.3624.png');
```
In either case, the result appears to be exactly the same as if I had added the drawing directly in Excel (adjusting the height appropriately). If your results differ, please show how.

Excel:
![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/10341515/019d4b6e-b2ba-4697-95b4-64a9d95684ba)

PhpSpreadsheet:
![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/10341515/e279b1eb-1be6-4799-8e2f-c5c3364f11ff)

**Comment by artygrand** [comment]
@oleibman , my attachment isn't original picture, but the broken result
I use it with laravel S3 Storage, so I can get only as string (I don't want to copy it on server and then wipe)

Okay, I tested different approaches and looks like found the bug. Lets try these 3 snippents

**file_get_contents with storage path**
```
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$stamp = PhpOffice\PhpSpreadsheet\Worksheet\MemoryDrawing::fromString(file_get_contents(storage_path('app/test.png')));
$stamp->setName('Stamp');
$stamp->setHeight(120);
$stamp->setCoordinates('A2');
$stamp->setWorksheet($sheet);

$writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save(storage_path('app/res-fgc.xlsx'));
```

**Storage getter, that I use. It is almost file_get_contents**
```
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$stamp = PhpOffice\PhpSpreadsheet\Worksheet\MemoryDrawing::fromString(Storage::disk('local')->get('test.png'));
$stamp->setName('Stamp');
$stamp->setHeight(120);
$stamp->setCoordinates('A2');
$stamp->setWorksheet($sheet);

$writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save(storage_path('app/res-stor.xlsx'));
```

**Not memory drawing but  base**
```
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$stamp = new PhpOffice\PhpSpreadsheet\Worksheet\Drawing();
$stamp->setPath(storage_path('app/test.png'));
$stamp->setName('Stamp');
$stamp->setHeight(120);
$stamp->setCoordinates('A2');
$stamp->setWorksheet($sheet);

$writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save(storage_path('app/res-path.xlsx'));
```

Original picture:
![test](https://github.com/PHPOffice/PhpSpreadsheet/assets/2451297/a749e297-e4b2-4f8d-ab35-35be1bcda5ad)

Results:
[res-fgc.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/11918011/res-fgc.xlsx)
[res-stor.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/11918013/res-stor.xlsx)
[res-path.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/11918012/res-path.xlsx)

Drawing with path
![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/2451297/3fa75f2f-d22c-4211-9e32-4fd332a90e2c)

MemoryDrawing it is absolutely broken
![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/2451297/b963df0d-b4b4-4a39-9cda-0cb5084d6dc5)

**Comment by oleibman** [comment]
Thank you, I am now able to duplicate your problem. However, I believe the problem lies in Php, not in PhpSpreadsheet.
```php
        $stamp_file = file_get_contents('issue.3624b.png'); // your new image
        $gdImage = imagecreatefromstring($stamp_file);
        imagepng($gdImage, 'issue.3624c.png');
```
This code snippet, which does not use PhpSpreadsheet at all, shows that its output file does not match the input file (and, in fact, matches your 'bad' image). When I substitute your original input file, the output file does match it, so I believe this code is correct, and therefore that one or both of the native Php functions `imagecreatefromstring` or `imagepng` has a problem. For the record, specifying PNG_NO_FILTER or PNG_ALL_FILTERS on the imagepng call does not change anything.

**Comment by oleibman** [comment]
I have opened an issue with Php.

**Comment by oleibman** [comment]
From the Php issue, an extra call was suggested (imagesavealpha). I will create a PR to incorporate this suggestion into PhpSpreadsheet. Look for it in a day or two.
