### ISSUE TITLE
Row and Column Ids must be positive integer values

### ISSUE THREAD

**Issue by ersunnyroy** [PHPOffice/PhpSpreadsheet#3637]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
IT SHOULD GENERATE THE FILE

### What is the current behavior?

**throwing error**
{
    "message": "Row and Column Ids must be positive integer values",
    "exception": "PhpOffice\\PhpSpreadsheet\\Exception",
    "file": "C:\\wamp64\\www\\sharing-api\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Cell\\CellAddress.php",
    "line": 49,
    "trace": [
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Cell\\CellAddress.php",
            "line": 59,
            "function": "validateColumnAndRow",
            "class": "PhpOffice\\PhpSpreadsheet\\Cell\\CellAddress",
            "type": "::"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Cell\\CellAddress.php",
            "line": 69,
            "function": "fromColumnAndRow",
            "class": "PhpOffice\\PhpSpreadsheet\\Cell\\CellAddress",
            "type": "::"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Worksheet\\Validations.php",
            "line": 30,
            "function": "fromColumnRowArray",
            "class": "PhpOffice\\PhpSpreadsheet\\Cell\\CellAddress",
            "type": "::"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Worksheet\\Worksheet.php",
            "line": 1275,
            "function": "validateCellAddress",
            "class": "PhpOffice\\PhpSpreadsheet\\Worksheet\\Validations",
            "type": "::"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Style\\Style.php",
            "line": 551,
            "function": "getCell",
            "class": "PhpOffice\\PhpSpreadsheet\\Worksheet\\Worksheet",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Style\\Style.php",
            "line": 382,
            "function": "getOldXfIndexes",
            "class": "PhpOffice\\PhpSpreadsheet\\Style\\Style",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\phpoffice\\phpspreadsheet\\src\\PhpSpreadsheet\\Style\\Alignment.php",
            "line": 272,
            "function": "applyFromArray",
            "class": "PhpOffice\\PhpSpreadsheet\\Style\\Style",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\app\\Exports\\LensablEnrollmentFileExport.php",
            "line": 30,
            "function": "setHorizontal",
            "class": "PhpOffice\\PhpSpreadsheet\\Style\\Alignment",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\maatwebsite\\excel\\src\\HasEventBus.php",
            "line": 51,
            "function": "App\\Exports\\{closure}",
            "class": "App\\Exports\\LensablEnrollmentFileExport",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\maatwebsite\\excel\\src\\Sheet.php",
            "line": 432,
            "function": "raise",
            "class": "Maatwebsite\\Excel\\Sheet",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\maatwebsite\\excel\\src\\Sheet.php",
            "line": 231,
            "function": "close",
            "class": "Maatwebsite\\Excel\\Sheet",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\maatwebsite\\excel\\src\\Writer.php",
            "line": 71,
            "function": "export",
            "class": "Maatwebsite\\Excel\\Sheet",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\maatwebsite\\excel\\src\\Excel.php",
            "line": 195,
            "function": "export",
            "class": "Maatwebsite\\Excel\\Writer",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\maatwebsite\\excel\\src\\Excel.php",
            "line": 99,
            "function": "export",
            "class": "Maatwebsite\\Excel\\Excel",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php",
            "line": 261,
            "function": "store",
            "class": "Maatwebsite\\Excel\\Excel",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\app\\Http\\Controllers\\APSReport.php",
            "line": 373,
            "function": "__callStatic",
            "class": "Illuminate\\Support\\Facades\\Facade",
            "type": "::"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\app\\Http\\Controllers\\APSReport.php",
            "line": 199,
            "function": "generateLensableEnrollmentFile",
            "class": "App\\Http\\Controllers\\APSReport",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
            "line": 54,
            "function": "generateEnrollmentFile",
            "class": "App\\Http\\Controllers\\APSReport",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 239,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 196,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 685,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\ThrottleRequests.php",
            "line": 59,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 687,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 662,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 628,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 617,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\app\\Http\\Middleware\\Cors.php",
            "line": 18,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "App\\Http\\Middleware\\Cors",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\app\\Http\\Middleware\\ForceJsonResponse.php",
            "line": 19,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "App\\Http\\Middleware\\ForceJsonResponse",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\public\\index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "C:\\wamp64\\www\\sharing-api\\server.php",
            "line": 21,
            "function": "require_once"
        }
    ]
}

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [*] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
NO

### Which versions of PhpSpreadsheet and PHP are affected?
 "maatwebsite/excel": "^3.1",
 "phpoffice/phpspreadsheet": "^1.29"

**Comment by oleibman** [comment]
Can you share your code, and possibly your spreadsheet, which leads to this error. It will be impossible to debug without it.

**Comment by oleibman** [comment]
Closing. Almost 5 months with no update, no way to duplicate and therefore no way to debug the problem.
