### ISSUE TITLE
Problem with complicated formulas

### ISSUE THREAD

**Issue by vojjin-gmail** [PHPOffice/PhpSpreadsheet#3639]
This is:

```
- [ ] a bug report
```

### What is the expected behavior?
formula should be applied regularily

### What is the current behavior?
receiving an error:
````
Fatal error:  Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Formula Error: An unexpected error occurred in ..../PhpSpreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php:5463
Stack trace:
#0 ..../PhpSpreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php(4550): PhpOffice\PhpSpreadsheet\Calculation\Calculation->raiseFormulaError('Formula Error: ...')
#1 ..../PhpSpreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php(3761): PhpOffice\PhpSpreadsheet\Calculation\Calculation->internalParseFormula('IF(G6<=0;SUM(D6...', Object(PhpOffice\PhpSpreadsheet\Cell\Cell))
#2 ..../PhpSpreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php(3535): PhpOffice\PhpSpreadsheet\Calculation\Calculation->_calculateFormulaValue('IF(G6<=0;SUM(D6...', 'L6', Object(PhpOffice\PhpSpreadsheet\Cell\Cell))
#3 ..../PhpSpreadsheet/src/PhpSpreadsheet/Cell/Cell.php(380): PhpOffice\PhpSpreadsheet\Calculation\Calculation->calculateCellValue(Object(PhpOffice\PhpSpreadsheet\Cell\Cell), true)
#4 ..../PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1274): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()
#5 ..../PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1343): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeCellFormula(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), '=IF(G6<=0;SUM(D...', Object(PhpOffice\PhpSpreadsheet\Cell\Cell))
#6 ..../PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1195): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeCell(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), 'L6', Array)
#7 ..../PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(87): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeSheetData(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), Array)
#8 ..../PhpSpreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(393): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeWorksheet(Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), Array, false)
````

### What are the steps to reproduce?
When I try to add simple formula, like `=SUM(D6:J6)+K6` all works fine and as expected.
however my formula is `=IF(G6<=0;SUM(D6:F6)-MAX(D6:F6)-MIN(D6:F6);IF(I6<=0;SUM(D6:H6)-MAX(D6:H6)-MIN(D6:H6);SUM(D6:J6)-MAX(D6:J6)-MIN(D6:J6)))+K6` and it is reproducing an error.

when I use this formula directly in excel, works fine.

### What features do you think are causing the issue

- [ ] Formula Calculations

### Which versions of PhpSpreadsheet and PHP are affected?
the latest, 1.29.0, PHP 8.1

**Comment by vojjin-gmail** [comment]
Same thing happend with another cell formula: `=MATCH(L6;SORT(FILTER(L6:L8;L6:L8<>"";"");1;-1);0)`

Stack trace is identical

**Comment by MarkBaker** [comment]
Are you using `;` or `,` as the argument separator for function calls in your formulae?

From the [Documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/calculation-engine/):


 - Decimal separator is `.` (period)
 - Function argument separator is `,` (comma)
 - Matrix row separator is `;` (semicolon)
 - English function names must be used

unless you've explicitly changed the locale

**Comment by vojjin-gmail** [comment]
I just found out that in formula written in PHP i ahve to use `,` comma, and then it works. However, when I need to create function directly in excel (for Mac) I need `;` semicolon....

**Comment by MarkBaker** [comment]
> I just found out that in formula written in PHP i ahve to use `,` comma, and then it works. However, when I need to create function directly in excel (for Mac) I need `;` semicolon....

That's because the Excel GUI is set for your locale, so it accepts/displays formulae using your locale settings. PhpSpreadsheet doesn't know your locale, so unless you explicitly tell it, you have to use the settings for `en_us`.
