### ISSUE TITLE
getimagesize segmentation fault

### ISSUE THREAD

**Issue by Hashiko** [PHPOffice/PhpSpreadsheet#364]
There is a possibility of a segmentation fault with the usage of the getimagesize method.

For more information please see :
- https://bugs.php.net/bug.php?id=74481
- PHPOffice/PHPExcel#482

This is:

```
- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
There is no segmentation fault killing apache processes while saving the spreadsheet.

### What is the current behavior?
There is a segmentation fault killing apache processes while saving the spreadsheet.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$writer = IOFactory::createWriter($this->spreadsheet, 'Xls');
ob_start();
$spreadsheet->save('php://output');
return ob_get_clean();
```
### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet : 1.1.0
PHP: 5.6

**Comment by PowerKiKi** [comment]
I cannot reproduce, and segmentation fault are likely to be a bug in PHP core (or its extensions), so it should tracked over there, not here.
