### ISSUE TITLE
Correct CSV Enclosure + Delimiter handling 

### ISSUE THREAD

**Issue by RP-TG** [PHPOffice/PhpSpreadsheet#3647]
This is:

```
- [X] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
CSV writer should be able to apply enclosures to handle cells with the default delimiting character present (apply enclosure only when  needed as per Excel)

### What is the current behavior?
Enclosures are handled on an 'all or nothing' basis. 
From #https://github.com/PHPOffice/PhpSpreadsheet/commit/ce6ac1f0404ae5bd9155faeba4d1f5816b354e34 - "A better choice would be to add an option to write the enclosure only when it is needed, which is what Excel does. The RFC4180 spec at https://tools.ietf.org/html/rfc4180 states when it is needed - when the cell contains the delimiter, or the enclosure, or a newline.
New test TestGoodReread demonstrates that the file is read as intended."

There is currently no combination of flags which can correct this behaviour.

### What are the steps to reproduce?
Using sample.xlsx which contains two columns and 3 rows as follows, with the desire to read this file then output as csv.

1 | 2
1 | A,B,42,C
1 | 2

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$sample = $reader->load('sample.xlsx',$reader::IGNORE_EMPTY_CELLS|$reader::READ_DATA_ONLY);
$csvwriter = new \PhpOffice\PhpSpreadsheet\Writer\Csv($sample);
//$csvwriter->setEnclosure('');
$csvwriter->save('output.csv');

The output.csv file from the Csv writer with default enclosure behaviour gives this:
"1","2"
"1","A,B,42,C"
"1","2"

Uncommenting //$csvwriter->setEnclosure(''); and the expected output with the setting of 'no enclosures' should be **as per excel**;  
1,2
1,"A,B,42,C"
1,2

But instead this is now the result (row 2 now contains 5 columns);
1,2
1,A,B,42,C
1,2

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Yes

### Which versions of PhpSpreadsheet and PHP are affected?
1.29.0

**Comment by RP-TG** [comment]
[sample.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/12123461/sample.xlsx)

**Comment by RP-TG** [comment]
I was incorrect, this case has already been handled, just the documentation / information wasn't the most forthcoming. 
For anyone else coming up against this issue the solution is to not specify no enclosures via `->setEnclosure('')`, but instead to leave the setEnclosure behavior as the default and instead specify `->setEnclosureRequired(false)`

**Comment by oleibman** [comment]
@RP-TG the function that you mentioned is described in the documentation (e.g. search for "enclosure"). If you can suggest a way to improve it so that it is more "forthcoming", we would certainly consider it.
