### ISSUE TITLE
Unable to read PDF

### ISSUE THREAD

**Issue by nawazm92** [PHPOffice/PhpSpreadsheet#3650]
How can I read PDF, it always says 

### Error: Unable to identify a reader for this file, when I use following code
```
$inputFileName = WWW_ROOT.'/pdf/sample.pdf'; 
$reader = IOFactory::createReaderForFile($inputFileName); 
```
OR 
### Error: No reader found for type PDF, when using following code
`$reader = IOFactory::createReader('PDF'); `

**Comment by MarkBaker** [comment]
The very good reason for this particular "error" is that PhpSpreadsheet does not read PDF files. A PDF file is not a spreadsheet file.
