### ISSUE TITLE
Comments will not be read

### ISSUE THREAD

**Issue by GooseDL** [PHPOffice/PhpSpreadsheet#3665]
This is:

```
- [ X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Return comments into a cell

### What is the current behavior?
Return empty comments

### What are the steps to reproduce?
First of all, sorry for my poor English.

If relationships Targets are defined as full paths Xlsx::loadSpreadsheetFromFile will not work properly.

Example: 
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"&gt;
	&lt;Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/tableSingleCells" Target="/xl/tables/tableSingleCells1.xml" Id="R7794038cb2c64bae"/&gt;
	&lt;Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="/xl/comments1.xml" Id="Red2c67a5311c43a9"/&gt;
	&lt;Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing" Target="/xl/drawings/vmldrawing.vml" Id="Re97db53ed0e14c5f"/&gt;
	&lt;Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" Target="/xl/tables/table1.xml" Id="Rc27115a48a714b5e"/&gt;
&lt;/Relationships&gt;

This is the way Microsoft Business Central (formerly Navision) exports data to XLSX format.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$file = "MIG01.xlsx";
$spreadsheet = (PhpOffice\PhpSpreadsheet\IOFactory::createReader(PhpOffice\PhpSpreadsheet\IOFactory::identify($file)))->load($file);
// add code that show the issue here...
echo $spreadsheet->getSheetByName("Cuenta")->getComment("A3")->getText();
// Will show nothing even when you can see "Code20" comment in A3 cell if you open MIG01.xlsx on Excel

```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

Sample:
[MIG01.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/12228787/MIG01.xlsx)

### What features do you think are causing the issue

- [ X] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

WA I have used this and It works for me, although I am not sure if it will work right always:
In Reader/Xlsx.php, line 795, just after $fileWorksheet = (string) $worksheets[$sheetReferenceId]; I have added this piece of code:

```php
$fileWorksheet = (string) $worksheets[$sheetReferenceId];
if ($fileWorksheet[0] == "/") {
	$fileWorksheet = substr($fileWorksheet, strlen($dir) + 2);
}

```
### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: 1.29.0
php: 8.2.8

**Comment by GooseDL** [comment]
[MIG01.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/12228817/MIG01.xlsx)

**Comment by oleibman** [comment]
Thank you for providing a sample spreadsheet. Your fix is okay as far as it goes. However, it is not the only problem with this spreadsheet. Even with your change, it does not read the Table correctly, because the third party package uses namespacing for Tables which PhpSpreadsheet does not yet expect. So, the complete solution may take a while. As a workaround which might be useful for you, you can open the spreadsheet in Excel and save it as a new spreadsheet; PhpSpreadsheet will not have a problem with the new one.

**Comment by GooseDL** [comment]
Thank you for the WA. I've tested it and I've seen that it works as
expected. Later on Business Central accepts it back, so there's no need to
fix the library but just advising the user to do the WA.

*Gustavo Díaz López*

*Segopi Corporate Group*


*ADVERTENCIA LEGAL*: De conformidad con lo establecido en el REGLAMENTO
(UE) 2016/679 de protección de datos de carácter personal, le informamos *que
los datos que usted nos facilite serán incorporados al sistema de
tratamiento titularidad de TELLING CONSULTING, S.L. con CIF **B40271926 y
domicilio social sito en C/ GUADARRAMA, No 11, SEGOVIA, con la finalidad de
PUBLICIDAD Y PROSPECCIÓN COMERCIAL; GESTIÓN DE CLIENTES, CONTABLE, FISCAL Y
ADMINISTRATIVA.*

*Se procederá a tratar los datos de manera lícita, leal, transparente,
adecuada, pertinente, limitada, exacta y actualizada.* Mientras no nos
comunique lo contrario, entenderemos que sus datos no han sido modificados
y que usted se compromete a notificarnos cualquier variación.

De acuerdo con los derechos que le confiere la normativa vigente *podrá
ejercer los derechos de acceso, rectificación, limitación de tratamiento,
supresión, portabilidad y oposición al tratamiento de sus datos de carácter
personal *así como revocar el consentimiento prestado, dirigiendo su
petición a la dirección postal indicada o al correo electrónico
***@***.*** y podrá dirigirse a la Autoridad de Control competente para
presentar la reclamación que considere oportuna.

*ADVERTENCIA*: La información contenida en este correo electrónico, y en su
caso, cualquier fichero anexo al mismo, son de carácter privado y
confidencial siendo para uso exclusivo de su destinatario. Si usted no es
el destinatario correcto, el empleado o agente responsable de entregar el
mensaje al destinatario, o ha recibido esta comunicación por error, le
informamos que está totalmente prohibida cualquier divulgación,
distribución o reproducción de esta comunicación según la legislación
vigente y le rogamos que nos lo notifique inmediatamente, procediendo a su
destrucción sin continuar su lectura.

El consumo de papel es perjudicial para el medio ambiente. Por favor
téngalo en cuenta antes de imprimir este mensaje.
