### ISSUE TITLE
PHPSpreadsheet shouldn't have gd as dependency

### ISSUE THREAD

**Issue by lionel-sticky** [PHPOffice/PhpSpreadsheet#367]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I don't think PHPSpreadsheet should have ext-gd as a dependency. 
PHPExcel didn't have it as dependency. 
Most of what PHPSpreadsheet can do doesn't require gd.
The confusion is also visible in the composer.json as ext-gd and ext-dom are both in "dependency" and "suggests". 

### What is the current behavior?
PHPSpreadsheet requires ext-gd.

### What are the steps to reproduce?

```bash
composer install
```
### Which versions of PhpSpreadsheet and PHP are affected?
Tested with PHPSpreadsheet 1.1.0

**Comment by PowerKiKi** [comment]
Some of the features does indeed require gd, and as such the entire package does require it. They are quite a few extensions required, but all of them are rather common and should be available, or easily installable, in most environnements.

**Comment by donatj** [comment]
I second this. I'm wanting to move from `PHPExcel` to `PHPSpreadsheet` but our servers do not have GD installed. Seeing as we don't use any GD requiring features, this is particularly obnoxious.

**Comment by luxemate** [comment]
It's sad that if you're already using ImageMagick you're forced to also install GD. IMHO, imaging library should be not a requirement, but rather a suggestion, if someone wants to use certain features.

**Comment by arturock** [comment]
@PowerKiKi I think this should be reconsidered. In our case, we have an application with web servers, worker servers and a test server, also, we process our images with Imagick. It may not be that cumbersome to install GD once, even with the current justification, but on bigger infrastructures it gets really annoying.

**Comment by PowerKiKi** [comment]
Many use-cases would involve reading user submitted spreadsheet files and there is no way to ensure that those do not contain images before actually reading them.

For now, Xls reader has a clear, hard dependency on GD. If GD is not present and you try to read a XLS file containing an image it will crash. This would be a very poor experience for the user and the developer where some files would work and other would not.

If your infrastructure is big enough to be a worry, then it should be automated anyway to be replicable consistently and predictability.

**Comment by devnix** [comment]
Couldn't it be a suggested package? If a function of the library GD is called, it could be wrapped to check if the function exists, and return a controlled exception explaining that you need the GD extension to open that kind of documents. It seems a little overkill to make it a hard requirement for everybody.

**Comment by jamesmehorter** [comment]
Chiming in from 2026! Please implement @devnix's suggestion—we don't want GD in our docker images when we don't use it.

**Comment by oleibman** [comment]
Not going to happen. You can use the `ignore-platform-req` of Composer if you are sure you will not need it.
