### ISSUE TITLE
Missing PHP 8.0.x support

### ISSUE THREAD

**Issue by mhcwebdesign** [PHPOffice/PhpSpreadsheet#3684]
This is:

- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
PHPOffice/PhpSpreadsheet 1.29.0 is supposed to support PHP 8.0.x releases, but it only works with PHP 8.1 or 8.2. See docs at https://phpspreadsheet.readthedocs.io/en/latest/ which says this:

> PHP 8.0 is officially End of Life on 26th November 2023, and PhpSpreadsheet will continue to support PHP 8.0 for six months after that date.

### What is the current behavior?
PHPOffice/PhpSpreadsheet should also support PHP 8.0 until at least 26th November 2023, plus another six months.

### What are the steps to reproduce?

1. 
Create it via a `composer require phpoffice/phpspreadsheet:1.29.0` command

2.
Run this PHP script on a Linux system with PHP 8.0.x:
```
<?php

require './vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$activeWorksheet = $spreadsheet->getActiveSheet();
$activeWorksheet->setCellValue('A1', 'Hello World !');

$writer = new Xlsx($spreadsheet);
$writer->save('hello world.xlsx');
?>
```
3.
The resulting 'hello world.xlsx' is a zero bytes empty file, it should have been a valid spreadsheet file.

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet version 1.29.0
PHP version 	8.0.30

**Comment by MarkBaker** [comment]
All tests pass when run against PHP 8.0, so I'm not sure exactly what is happening here.
I'll take a look and see if I can identify the problem

**Comment by mhcwebdesign** [comment]
I got this in my local test server's error.log:

PHP Parse error:  syntax error, unexpected identifier "Closure", expecting variable in /home/juergen/htdocs/test-phpspreadsheet/vendor/maennchen/zipstream-php/src/ZipStream.php on line 111

Looking at the 'composer.lock' for the 'maennchen/zipstream-php' package, it appears to require PHP 8.1 or later, maybe that's what causes the issue?

**Comment by oleibman** [comment]
See https://github.com/PHPOffice/PhpSpreadsheet/issues/3615#issuecomment-1595846986. A clean install of PhpSpreadsheet with Composer using Php8.0 should use Zipstream V2 and avoid this problem.

**Comment by oleibman** [comment]
Closed as duplicate of #3615.

**Comment by mhcwebdesign** [comment]
I understand the workarounds.

However, the issue hasn't yet been resolved, because a plain `composer require phpoffice/phpspreadsheet` always uses **maennchen/zipstream-php version 3.1.0**, and the latter won't work on PHP 8.0.x releases anymore. Please re-open this issue. 

Below is the result from above command:

```
composer require phpoffice/phpspreadsheet
Using version ^1.29 for phpoffice/phpspreadsheet
./composer.json has been created
Running composer update phpoffice/phpspreadsheet
Loading composer repositories with package information
Updating dependencies
Lock file operations: 9 installs, 0 updates, 0 removals
  - Locking ezyang/htmlpurifier (v4.16.0)
  - Locking maennchen/zipstream-php (3.1.0)
  - Locking markbaker/complex (3.0.2)
  - Locking markbaker/matrix (3.0.1)
  - Locking phpoffice/phpspreadsheet (1.29.0)
  - Locking psr/http-client (1.0.2)
  - Locking psr/http-factory (1.0.2)
  - Locking psr/http-message (2.0)
  - Locking psr/simple-cache (3.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing psr/simple-cache (3.0.0): Extracting archive
  - Installing psr/http-message (2.0): Extracting archive
  - Installing psr/http-factory (1.0.2): Extracting archive
  - Installing psr/http-client (1.0.2): Extracting archive
  - Installing markbaker/matrix (3.0.1): Extracting archive
  - Installing markbaker/complex (3.0.2): Extracting archive
  - Installing maennchen/zipstream-php (3.1.0): Extracting archive
  - Installing ezyang/htmlpurifier (v4.16.0): Extracting archive
  - Installing phpoffice/phpspreadsheet (1.29.0): Extracting archive
9 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!

```

**Comment by oleibman** [comment]
I am sorry that you are having problems, but composer.json requires:
```
"maennchen/zipstream-php": "^2.1 || ^3.0",
```
We run all of our PRs through unit tests with 8.0, and they all run just fine.

Now, here's what I get on a clean system:
```
C:\git\php80>php80 ..\composer.phar require phpoffice/phpspreadsheet
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been created
Running composer update phpoffice/phpspreadsheet
Loading composer repositories with package information
Updating dependencies
Lock file operations: 10 installs, 0 updates, 0 removals
  - Locking ezyang/htmlpurifier (v4.16.0)
  - Locking maennchen/zipstream-php (2.4.0)
  - Locking markbaker/complex (3.0.2)
  - Locking markbaker/matrix (3.0.1)
  - Locking myclabs/php-enum (1.8.4)
  - Locking phpoffice/phpspreadsheet (1.29.0)
  - Locking psr/http-client (1.0.2)
  - Locking psr/http-factory (1.0.2)
  - Locking psr/http-message (1.1)
  - Locking psr/simple-cache (3.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 10 installs, 0 updates, 0 removals
  - Installing myclabs/php-enum (1.8.4): Extracting archive
  - Installing psr/simple-cache (3.0.0): Extracting archive
  - Installing psr/http-message (1.1): Extracting archive
  - Installing psr/http-factory (1.0.2): Extracting archive
  - Installing psr/http-client (1.0.2): Extracting archive
  - Installing markbaker/matrix (3.0.1): Extracting archive
  - Installing markbaker/complex (3.0.2): Extracting archive
  - Installing maennchen/zipstream-php (2.4.0): Extracting archive
  - Installing ezyang/htmlpurifier (v4.16.0): Extracting archive
  - Installing phpoffice/phpspreadsheet (1.29.0): Extracting archive
6 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
Using version ^1.29 for phpoffice/phpspreadsheet
```
It is only when I use Php8.1 (or higher) to run Composer that I get Zipstream 3. It sounds like you are using 8.1 for your Composer, but 8.0 when you run PhpSpreadsheet, and that's why you are having problems.

**Comment by mhcwebdesign** [comment]
Thanks for the clarification. I think you are right, I just ran this command:
`php8.0 -f /usr/bin/composer require phpoffice/phpspreadsheet`
which generates the correct version 2.4.0 for the **maennchen/zipstream-php**:
```
Using version ^1.29 for phpoffice/phpspreadsheet
./composer.json has been created
Running composer update phpoffice/phpspreadsheet
Loading composer repositories with package information
Updating dependencies
Lock file operations: 10 installs, 0 updates, 0 removals
  - Locking ezyang/htmlpurifier (v4.16.0)
  - Locking maennchen/zipstream-php (2.4.0)
  - Locking markbaker/complex (3.0.2)
  - Locking markbaker/matrix (3.0.1)
  - Locking myclabs/php-enum (1.8.4)
  - Locking phpoffice/phpspreadsheet (1.29.0)
  - Locking psr/http-client (1.0.2)
  - Locking psr/http-factory (1.0.2)
  - Locking psr/http-message (1.1)
  - Locking psr/simple-cache (3.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 10 installs, 0 updates, 0 removals
  - Installing myclabs/php-enum (1.8.4): Extracting archive
  - Installing psr/simple-cache (3.0.0): Extracting archive
  - Installing psr/http-message (1.1): Extracting archive
  - Installing psr/http-factory (1.0.2): Extracting archive
  - Installing psr/http-client (1.0.2): Extracting archive
  - Installing markbaker/matrix (3.0.1): Extracting archive
  - Installing markbaker/complex (3.0.2): Extracting archive
  - Installing maennchen/zipstream-php (2.4.0): Extracting archive
  - Installing ezyang/htmlpurifier (v4.16.0): Extracting archive
  - Installing phpoffice/phpspreadsheet (1.29.0): Extracting archive
8 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found

```

And I can run the resulting phpspreadsheet in any of the PHP versions 8.0 to 8.2, which is what we wanted in our OpenCart project at https://github.com/opencart/opencart

**Comment by oleibman** [comment]
I am glad to hear that you are now up and running correctly. Thank you for confirming.
