### ISSUE TITLE
Border doesn't work in ods

### ISSUE THREAD

**Issue by mzawodzinski** [PHPOffice/PhpSpreadsheet#3690]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Generating a border in the ods file

### What is the current behavior?

Border is invisible
### What are the steps to reproduce?

```php
<?php

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$styleArray = [
    'borders' => [
        'outline' => [
            'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THICK,
            'color'       => ['argb' => '00000000'],
        ],
    ],
];

$spreadsheet->getActiveSheet()->getStyle('B2:I40')->applyFromArray($styleArray);


$writer = new PhpOffice\PhpSpreadsheet\Writer\Ods($spreadsheet);
$writer->save(__DIR__ . '/out/test.ods');

$writer2 = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer2->save(__DIR__ . '/out/test.xlsx');
```
in ods file:
![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/36850550/eb4b172b-88e5-40a1-9d1a-9625ae46d729)
in xlsx file:
![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/36850550/577d8e81-97e2-4a49-84c3-5080cc3a9d93)

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: 1.29
php: 8.1

**Comment by Progi1984** [comment]
@mzawodzinski I added a PR for this bug : #3693
