### ISSUE TITLE
BUG: setValue in formulas automatically sets @ in formula when using ranges

### ISSUE THREAD

**Issue by HAL0594** [PHPOffice/PhpSpreadsheet#3708]
This is:

```
- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
when defining my form I am doing it in the following way

```
$formula = '=IF(A' . $row . '<>"",SUM(SUMIFS(\'TABLE1\'!C2:C713,\'TABLE1\'!A2:A713,\'WORKSHEET\'!$H$' . $row . ':$Q$' . $row . ')),"")';
$cell->setValueExplicit($formula, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_FORMULA);
```

but when generating the .xlsx document an @ has been automatically added to the range preventing it from being calculated correctly, for example:

```
=IF(A19<>"",SUM(SUMIFS('TABLE1'!C2:C713,'TABLE1'!A2:A713,@'WORKSHEET'!$H$19:$Q$19)),"")
```

### What is the current behavior?

        for ($row = $range[2]; $row <= $range[3]; $row++) {
            for ($col = $this->getColumnIndex($range[0]); $col <= $this->getColumnIndex($range[1]); $col++) {
                $cell = $sheet->getCellByColumnAndRow($col, $row);
                $formula = '=IF(A' . $row . '<>"",SUM(SUMIFS(\'TABLE1\'!C2:C713,\'TABLE1\'!A2:A713,\'WORKSHEET\'!$H$' . $row . ':$Q$' . $row . ')),"")';
                $cell->setValueExplicit($formula, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_FORMULA);
            }
        }

### Which versions of PhpSpreadsheet and PHP are affected?
v.1.28

**Comment by oleibman** [comment]
See https://github.com/PHPOffice/PhpSpreadsheet/pull/3659#issuecomment-1663040464 for an explanation of the at sign. As I mentioned in that comment, I haven't been able to figure out what has to be done to keep Excel from adding it (it is *not* present in the spreadsheet generated by PhpSpreadsheet).
