### ISSUE TITLE
Make `ext-gd` an optional dependency by moving it to `suggests`

### ISSUE THREAD

**Issue by ruudk** [PHPOffice/PhpSpreadsheet#3719]
This is:

```
- [ ] a bug report
- [x a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

We'd like to use PhpSpreadsheet but we don't want to install `ext-gd`. 

### What is the current behavior?

Currently, not possible because `ext-gd` is required in `composer.json`

It would be great if `ext-gd` was only required when generating graph's etc.

**Comment by mu1f407** [comment]
Definitely would like to see this too. Workaround is to use `--ignore-platform-req=ext-gd` when installing packages, but it is not really nice solution. ext-gd is pretty large module with all its libraries and I try to keep my Docker images as small as possible.

**Comment by oleibman** [comment]
After discussion on PR 3766, the PR was closed, so we will not be moving forward with this suggestion.
