### ISSUE TITLE
Content with <t xml:space="preserve"> get additional LF before and after text.

### ISSUE THREAD

**Issue by fglueck** [PHPOffice/PhpSpreadsheet#3725]
This is:

```
- [X] a bug report
```

### What is the expected behavior?
only the content with spaces before and after would be returned

### What is the current behavior?
Content This is:

```
- [X] a bug report
```

### What is the expected behavior?
only the content with spaces before and after would be returned

### What is the current behavior?
Content with <t xml:space="preserve"> get additional LF before and after text.

### What are the steps to reproduce?
add spaces beforea/after the cell data, xlsx "sharedStrings.xml" will create:
<si><t xml:space="preserve">   XXXX   </t></si>

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
...
$cell = $wrks->getCellByColumnAndRow(1, 1);
echo "|{$cell->getValue()}|";
```
### What features do you think are causing the issue

- [*] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

It look like, that the XML was formated (LF added) and than the content written to the value property.

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
only xlsx testet

### Which versions of PhpSpreadsheet and PHP are affected?
current versionwith <t xml:space="preserve"> get additional LF before and after text.

### What are the steps to reproduce?
add spaces beforea/after the cell data, xlsx "sharedStrings.xml" will create:
<si><t xml:space="preserve">   XXXX   </t></si>

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
...
$cell = $wrks->getCellByColumnAndRow(1, 1);
echo "|{$cell->getValue()}|";
```
### What features do you think are causing the issue

- [*] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

It look like, that the XML was formated (LF added) and than the content written to the value property.

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
only xlsx testet

### Which versions of PhpSpreadsheet and PHP are affected?
current version

**Comment by oleibman** [comment]
I am sorry, I do not understand the problem. Are you saying that `getValue` is returning LF which is *not* in the spreadsheet cell? If so, can you provide the complete program which demonstrates the problem? I cannot tell from your sample what is supposed to be in the erroneous cell.

**Comment by fglueck** [comment]
This issue was generated by tidy workaround for #3130/#3125. And it is not need any more because there was a fix some month ago.
