### ISSUE TITLE
Undefined array key with $sharedStrings when upload file excel

### ISSUE THREAD

**Issue by technghiath** [PHPOffice/PhpSpreadsheet#3730]
This is:

```
- [x] a bug report
https://github.com/PHPOffice/PhpSpreadsheet/blob/f17e16653dbcdc7177efc91deb1f87a5faa096b5/src/PhpSpreadsheet/Reader/Xlsx.php#L850
```

### What is the expected behavior?
Don't call an element when the element is undefined. Do you know what is the cause of this error?

### What is the current behavior?
 I don't know what causes this error. 
An exception error occurred: 
```
Undefined array key 1604 {"exception":"[object] (ErrorException(code: 0): Undefined array key 1604 at /var/www/html/publisher_web/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:850
```
### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [x] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by oleibman** [comment]
Please upload the spreadsheet that causes this problem. Without it, there is no chance of debugging it.

**Comment by wsabol** [comment]
[112579-promediapostlogswk2-12.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/14442124/112579-promediapostlogswk2-12.xlsx)

I'm getting it with this file

```
$inputFileType = IOFactory::identify($file_name);
$objReader = IOFactory::createReader($inputFileType);
$objReader->setReadDataOnly(false);
$objExcel = $objReader->load($file_name); // tons of warnings.... example: PHP Warning:  Undefined array key 1153 in .../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 839
```

also it doesn't seem to read most of the cell data either. cell data types are null.

**Comment by oleibman** [comment]
Thank you for the sample file. This is another case of unexpected absolute addressing in a rels file. Expect a PR in a day or two.

**Comment by wsabol** [comment]
FWIW i tried reading that file with a python (openpyxl) and this was thrown "There is no item named 'xl/sharedStrings.xml' in the archive"

**Comment by oleibman** [comment]
Thank you for the info on openpyxl - I hope you have opened an issue with them as well. In the meantime, please test against PR 3923 if you can.

**Comment by leuchtdiode** [comment]
Hi,

I have the same problem, but it is very weird. It just happens on my production machine (Red Hat), but it does not happen - with the same file - in my local docker environment. Both are on the same PHP version (8.2.x) and of course the same library version (2.2.2).

Has any one an idea what could cause this issue?

Unfortunately I can't upload the file as there are customer data in it.

Thx & BR,
Alex

**Comment by oleibman** [comment]
I don't know that I can be any help. Even if you were to upload the file, my guess is that my test would end up like your Docker image, not your production one. Just out of idle curiosity, if you open the misbehaving spreadsheet in Excel and save it to another file, does your production image have a problem with the newly saved version?

**Comment by leuchtdiode** [comment]
Good idea, I will give it a try the next time.
