### ISSUE TITLE
No buffer to delete

### ISSUE THREAD

**Issue by newnewcoder** [PHPOffice/PhpSpreadsheet#3739]
This is:

```
- [x] a bug report
https://github.com/PHPOffice/PhpSpreadsheet/blob/78726021363368207fbb0736299039726c28af98/src/PhpSpreadsheet/Helper/Downloader.php#L52
```

### What is the expected behavior?
Consistent and successful file downloads every time.

### What is the current behavior?
Occasionally unable to download excel file, and throwing the exception below:

```
ob_clean(): Failed to delete buffer. No buffer to delete {"userId":1,"exception":"[object] (ErrorException(code: 0): ob_clean(): Failed to delete buffer. No buffer to delete at /var/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Helper/Downloader.php:52)
```

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
no

### Which versions of PhpSpreadsheet and PHP are affected?
1.29.0

**Comment by oleibman** [comment]
I can't duplicate this problem. Since you say it happens occasionally on your system, can you try replacing the ob_clean call in Downloader.php with:
```php
if((int) ob_get_length() > 0) {
    ob_clean();
}
```
If you confirm that change eliminates your problem, we can consider doing that.

**Comment by newnewcoder** [comment]
Yes, that seems to have solved my problem. Please consider implementing that change.
