### ISSUE TITLE
Long numbers (trillions) with a 2-digit decimal are always rounded

### ISSUE THREAD

**Issue by atmanegara** [PHPOffice/PhpSpreadsheet#3749]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
float 2633064508380.94 should be written to xlsx exactly the same not text but number format,  I will do the sum of each cell

### What is the current behavior?
The data values ​​are taken from the database, looped, then entered into the excel template, each cell has been formatted into a number, for example I entered a variable with the value 2633064508380.94
You can see in the picture, I have done all the value formatting, it is always round 2633064508380.90 or 2633064508381

### What are the steps to reproduce?
<img width="1263" alt="format_decimal" src="https://github.com/PHPOffice/PhpSpreadsheet/assets/9096711/26d7b6f1-04c0-49da-a947-e233a8d1c497">
begin cell 22 - 34

```php

     $nilai='2633064508380.94';
$sheet->setCellValueExplicit('B22', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B22')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_GENERAL);
$sheet->setCellValueExplicit('B23', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B23')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_NUMBER);
$sheet->setCellValueExplicit('B24', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B24')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_NUMBER_0);
$sheet->setCellValueExplicit('B25', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B25')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_NUMBER_0);
$sheet->setCellValueExplicit('B26', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B26')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1);
$sheet->setCellValueExplicit('B27', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B27')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED2);
$sheet->setCellValueExplicit('B28', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B28')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_ACCOUNTING_EUR);
$sheet->setCellValueExplicit('B29', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B29')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_ACCOUNTING_USD);
$sheet->setCellValueExplicit('B30', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B30')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_CURRENCY_EUR);
$sheet->setCellValueExplicit('B31', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B31')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_CURRENCY_EUR_INTEGER);
$sheet->setCellValueExplicit('B32', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B32')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_CURRENCY_USD);
$sheet->setCellValueExplicit('B33', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B33')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_CURRENCY_USD_INTEGER);
$sheet->setCellValueExplicit('B34', $nilai, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC);
$sheet->getStyle('B34')->getNumberFormat()->setFormatCode(\PhpOffice\PhpSpreadsheet\Style\NumberFormat::FORMAT_TEXT);

```

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
xls and xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
php 8.1.4
phpspreadsheet 1.29.0

**Comment by oleibman** [comment]
I think you have hit a limit in Php, not in PhpSpreadsheet. See https://www.php.net/manual/en/language.types.float.php, in particular the statement "The size of a float is platform-dependent, although a maximum of approximately 1.8e308 with a precision of roughly 14 decimal digits is a common value (the 64 bit IEEE format)." Your number is 15 digits long, which exceeds that precision.

**Comment by atmanegara** [comment]
> I think you have hit a limit in Php, not in PhpSpreadsheet. See https://www.php.net/manual/en/language.types.float.php, in particular the statement "The size of a float is platform-dependent, although a maximum of approximately 1.8e308 with a precision of roughly 14 decimal digits is a common value (the 64 bit IEEE format)." Your number is 15 digits long, which exceeds that precision.

OK, but I can still calculate correctly in PHP with that nominal value (trillions), but when displayed in the excel template it becomes problematic

**Comment by oleibman** [comment]
Out of curiosity, what happens when you assign a float rather than a string to $nilai?

**Comment by atmanegara** [comment]
> ```
> $nilai='2633064508380.94';
> ```

**Comment by atmanegara** [comment]
> Out of curiosity, what happens when you assign a float rather than a string to $nilai?

ok, example code, I made it using the string $value='2633064508380.94';
, we focus on displaying that $value into an excel file, which results in 2633064508380.9 or 2633064508381
even though the cells are already in number format

**Comment by atmanegara** [comment]
sorry, I accidentally clicked finish

**Comment by atmanegara** [comment]
up, is there a solution to my problem?

**Comment by oleibman** [comment]
You will need to set precision to a higher value, either directly in php.ini, or by adding a statement to your program like:
```php
ini_set('precision', 20);
```

**Comment by atmanegara** [comment]
> ```
> ini_set('precision', 20);
> ```

solved , thanks sir
