### ISSUE TITLE
Is it possible to render <UL> <LI> tag in cell with format?

### ISSUE THREAD

**Issue by ajaysharma296781** [PHPOffice/PhpSpreadsheet#3750]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
Issue is: 
we have html string with ul li tag. for example
$html = `"<ul><li><ul><li>A</li><li>B</li></ul></li></ul>"`;`  
Now when we do render in phpspreadsheet, it is not taking into consideration these tags as it is showing in HTML view(Order/disorder list) but it is just replacing with new line. 

### What is the expected behavior?
It should show same as HTML inside cell. Means, UL LI tag should be well formatted inside cell.

### What is the current behavior?
it is considering as a string. we have also used below code but not found any solution.
```
$html = new PhpOffice\PhpSpreadsheet\Helper\Html();
$HTMLCODE = $html->toRichTextObject($testStr);
```

### What are the steps to reproduce?

```
<?php 
require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$activeWorksheet = $spreadsheet->getActiveSheet();
$testStr = "<ul><li><b>Executive Summary</b><ul><li>Market Overview</li><li>Wheel of Fortune</li></ul>";

$html = new PhpOffice\PhpSpreadsheet\Helper\Html();
$htmlCode = $html->toRichTextObject($testStr);

$activeWorksheet->setCellValue('A1', $htmlCode);
$writer = new Xlsx($spreadsheet);
$writer->save('hello world.xlsx');
echo 'done';
?>
```

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by oleibman** [comment]
It seems clear that #3751 was created in response to this. Even though this one was first, I would prefer to continue the discussion there, so am closing this as a duplicate. Please feel free to follow and comment on the other issue.
