### ISSUE TITLE
Calculate cell value

### ISSUE THREAD

**Issue by Sab-tech-lab** [PHPOffice/PhpSpreadsheet#3753]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I expected to see the calculated value of the cell as in Excel

### What is the current behavior?
The calculated value of the cell is empty while reading only the value reports '='.

### What are the steps to reproduce?
Try reading the attached file, specifically line 2762, the third cell should be like the second one

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';
$file = "file.xlsx";
// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader(ucfirst("Xlsx"));
$reader->load($file);
$row = 2762;
$RowIt = $sheet->getRowIterator($row, $row + 1);
foreach ($RowIt as $idx => $Row) {
    $CellIterator = $Row->getCellIterator();
    $data = array();
    foreach ($CellIterator as $Cell) {
        array_push($data, (string) $Cell->getCalculatedValue());
    }
}
print_r($data);
[20230928155638_it-IT_en-GB.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/12764644/20230928155638_it-IT_en-GB.xlsx)
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [x ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [x ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
1.24.1

**Comment by MarkBaker** [comment]
Seems to be working as expected, unable to replicate any problem.

```
vagrant@homestead:~/projects/PHPOffice/PhpSpreadsheet$ php testing/formulaTest.php

Formula value for evaluation is =B2762
Parser Stack :-Array
(
    [0] => Array
        (
            [type] => Cell Reference
            [value] => B2762
            [reference] => B2762
        )

)
Result is DOCDI0002017

Evaluation Log:
Array
(
    [0] => Testing cache value for cell Inglese!C2762
    [1] => Evaluating formula for cell Inglese!C2762
    [2] => Formula for cell Inglese!C2762 is B2762
    [3] => Inglese!C2762 => Evaluating Cell B2762 in worksheet Inglese
    [4] => Inglese!C2762 => Evaluation Result for cell 'Inglese'!B2762 in worksheet Inglese is a string with a value of "DOCDI0002017"
)

Call time to evaluate formula was 0.0031 seconds

Call time to process all formulae was 0.0127 seconds
 Current memory usage: 14336 KB
    Peak memory usage: 14336 KB
```

**Comment by Sab-tech-lab** [comment]
Which version did you test with? In fact, one of the next steps for me is to update the library.

**Comment by Sab-tech-lab** [comment]
Can you share your testing code please?

**Comment by Sab-tech-lab** [comment]
With last version the result is correct.
Thank you very much
Have a nice day
