### ISSUE TITLE
Class "MyCLabs\Enum\Enum" not found

### ISSUE THREAD

**Issue by Sab-tech-lab** [PHPOffice/PhpSpreadsheet#3758]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Not load class, Class "MyCLabs\Enum\Enum" not found

### What is the current behavior?
Load class

### What are the steps to reproduce?
Write a simple file Xlsx

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [X ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by Sab-tech-lab** [comment]
I hava add library to composer and now the error is:
PHP Fatal error:  Uncaught TypeError: ZipStream\ZipStream::__construct(): Argument #1 ($operationMode) must be of type ZipStream\OperationMode, null given,
If downgrade from 3.1.0 => 3.0.2 writing file function

**Comment by billynoah** [comment]
Running php 8.3.11 here - this is what I did to get things working again:
```
composer require myclabs/php-enum
composer require maennchen/zipstream-php:3.0.2
```

As @Sab-tech-lab points out above, ZipStream 3.1.0 (current version at this time) will cause issues. Not sure why php-enum was missing.

**Comment by abdulrehman25** [comment]
Thank you @billynoah . This worked for me when I used PHP 8.3
