### ISSUE TITLE
Csv output all sheets to a single file

### ISSUE THREAD

**Issue by GarethCarter** [PHPOffice/PhpSpreadsheet#377]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
It would be useful to be able to output all sheets for CSV output in a single file.

### What is the current behavior?
You can only select 1 sheet per file

### What are the steps to reproduce?
n/a
### Which versions of PhpSpreadsheet and PHP are affected?
All

**Comment by PowerKiKi** [comment]
CSV file by definition cannot hold more than one sheet. If you want multiple CSV sheets, you'll need multiples files. Or come up with a custom way to merge your data.

**Comment by GarethCarter** [comment]
I know what you mean, it doesn't make sense in the strict sense of csv files. Certainly excel won't output multiple sheets as a csv file. Currently in my application I output each sheet into separate files and then merge all the files together. I thought this could be useful for others but maybe I'm mainly thinking about my own use case. I'm happy to submit a pull request of what I was thinking but if you don't agree then I'll hold off.

Awesome library BTW.

**Comment by PowerKiKi** [comment]
It is very unlikely to be merged, because I assume it would be very specific to data structure, and it goes against what is usually expected from a CSV. Thus it is best to leave it up to the user instead.
