### ISSUE TITLE
Error: Call to a member function children() on null

### ISSUE THREAD

**Issue by uaa0203** [PHPOffice/PhpSpreadsheet#3770]
This is a bug report

Error: Call to a member function children() on null in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:466
Stack trace:
#0 vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/BaseReader.php(182): PhpOffice\PhpSpreadsheet\Reader\Xlsx->loadSpreadsheetFromFile()
#1 vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/IOFactory.php(108): PhpOffice\PhpSpreadsheet\Reader\BaseReader->load()
#2 ... PhpOffice\PhpSpreadsheet\IOFactory::load()

PHP 7.4.28

[93887c81db717fe35a996850ba96bbaa.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/12997149/93887c81db717fe35a996850ba96bbaa.xlsx)

**Comment by oleibman** [comment]
Thank you for supplying the file. In the spreadsheet, a rels file points to a theme file, but the theme file does not exist. This is unexpected, but easy to detect. Expect a fix in a day or two.
