### ISSUE TITLE
HTML from Excel didn't copy charts

### ISSUE THREAD

**Issue by SevymolSebastian** [PHPOffice/PhpSpreadsheet#3777]
When I trying to convert excel to html, charts didn't show in html file

### What is the expected behavior?

All charts which included in excel should show in html

### What is the current behavior?

No charts which included in excel shows in html

### What are the steps to reproduce?

```php

        $spreadsheet = IOFactory::load("05featuredemo.xlsx", \PhpOffice\PhpSpreadsheet\Reader\IReader::LOAD_WITH_CHARTS);
        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Html($spreadsheet);
        $writer->setIncludeCharts(true);
        $writer->writeAllSheets();
        $writer->save("05featuredemo.html");
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [x] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

Yes

### Which versions of PhpSpreadsheet and PHP are affected?

phpoffice/phpspreadsheet: 1.29.0

**Comment by oleibman** [comment]
See https://github.com/PHPOffice/PhpSpreadsheet/issues/382#issuecomment-1780531568

**Comment by oleibman** [comment]
Closing. Issue reporter has indicated via emoji that problem is resolved.
