### ISSUE TITLE
Select all data with `rangeToArray()` (0 parameters)

### ISSUE THREAD

**Issue by kurdtpage** [PHPOffice/PhpSpreadsheet#378]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Calling `rangeToArray()` with no parameters should select all of the data on the entire sheet

### What is the current behavior?
`Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PhpOffice\PhpSpreadsheet\Worksheet\Worksheet::rangeToArray(), 0 passed in /var/www/html/exceltest.php on line 8 and at least 1 expected in ...`

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($filename);

// add code that show the issue here...
print_r($spreadsheet->getActiveSheet()->rangeToArray()); //note rangeToArray has 0 parameters
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: downloaded 2018-02-16
PHP: version 7.1

**Comment by PowerKiKi** [comment]
This should be easily doable with existing API via something like:

```php
$spreadsheet->rangeToArray($spreadsheet->calculateWorksheetDataDimension());
```

**Comment by maximnl** [comment]
just use toArray() instead :)
