### ISSUE TITLE
Password protect for the xlsx file

### ISSUE THREAD

**Issue by KuSai18** [PHPOffice/PhpSpreadsheet#3781]
This is:

```
- [*] a bug report
- [*] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Prompt a password request when user open excel file.

Prompt password request :
![demo](https://github.com/PHPOffice/PhpSpreadsheet/assets/70496731/29838573-e5d8-47dc-b73a-7b8dbb870215)

Setting password page :
![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/70496731/76e42932-9ebb-4152-926a-e72f8040a4bb)

### What is the current behavior?
Just only lock the wordsheet.

### What are the steps to reproduce?
1. Read from local xlsx file
2. Change some column records
3. Set the security password for excel (expect lock whole file, but only locked wordsheet)
4. Save the xlsx with password and new records

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use \PhpOffice\PhpSpreadsheet\Spreadsheet;
use \PhpOffice\PhpSpreadsheet\IOFactory;

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();

// reading demo xlsx for edit
$reader = IOFactory::createReader("Xlsx");
$spreadsheet = $reader->load("demo.xlsx");

/** 
  // change column records coding
  // all the same with below format
  // $spreadsheet->getActiveSheet()->setCellValue('B4', 'test');
*/

// want to lock the excel with password
$security = $spreadsheet->getSecurity();
$security->setLockWindows(true);
$security->setLockStructure(true);
$security->setWorkbookPassword("PhpSpreadsheet");

// save excel with new name
$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$fileName='demo_'.time().'.xlsx'; 
$writer->save($fileName);

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [*] Reader
- [*] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
xlsx

### Which versions of PhpSpreadsheet and PHP are affected?
1.29

**Comment by oleibman** [comment]
From the official documentation:
```md
Note that "protection" is not the same as "encryption".
Protection is about preventing parts of a spreadsheet from being changed,
not about preventing the spreadsheet from being looked at.
PhpSpreadsheet does not support encrypting a spreadsheet; nor can it read encrypted spreadsheets.
```

**Comment by KuSai18** [comment]
Thank you very much for answering this question.

**Comment by peterafh** [comment]
I know it is a bit late, but maybe my response is useful for someone else looking for spreadsheets encryption.

I needed encryption for a project and begun to use the Encryptor package from **xlsx-populate** tool (https://github.com/dtjohnson/xlsx-populate/blob/master/lib/Encryptor.js) to encrypt the files created with **PHPOffice/Spreadsheet** via cli, but finally had to port it to PHP, for security reasons.

You can use this class to encrypt an Excel file:
https://gist.github.com/peterafh/55b21beb58a91c3e13a2005902ad207b

Decryption was not needed at the moment, so it is not yet implemented/ported.

Repository owners are free to make it part of **PHPOffice/PhpSpreadsheet**, if they want 😊

**Comment by lintangpanggalih** [comment]
@peterafh how to use the encryptor?

**Comment by peterafh** [comment]
> @peterafh how to use the encryptor?

Hi!

Just load the unencrypted **Xlsx** file contents, encrypt with a password and save it to a file. This example builds a simple Excel file and encrypts it with password `1234`:

```php
use App\Helpers\OpenXmlEncrypter;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Create Hello world Excel
$spreadsheet = new Spreadsheet();
$activeWorksheet = $spreadsheet->getActiveSheet();
$activeWorksheet->setCellValue('A1', 'Hello World!');

$writer = new Xlsx($spreadsheet);
$writer->save('hello world.xlsx');

// Load data
$data = file_get_contents('hello world.xlsx');

// Encrypt and save
$encrypter = new OpenXmlEncrypter;
$encryptedData = $encrypter->encrypt($data, "1234");
file_put_contents('hello world - encrypted.xlsx', $encryptedData);
```

If you don't want to write the unencrypted contents to a file, you can do an in-memory processing instead:
```php
...

// Save Xlsx to memory
$writer = new Xlsx($spreadsheet);
$file = fopen('php://memory', 'w+');
$writer->save($file);

// Load data
fseek($file, 0);
$data = stream_get_contents($file);

// Encrypt and save
$encrypter = new OpenXmlEncrypter;
$data = $encrypter->encrypt($data, "1234");
file_put_contents('hello world - encrypted.xlsx', $data);
```

In the example I assume the encrypter class can be autoloaded from the `App\Helpers` namespace. You can modify its namespace to adjust it to your needs. 

Hope this helps.
