### ISSUE TITLE
ReflectionMethod constructor usage not compliant with PHP 8.4

### ISSUE THREAD

**Issue by andrewnicols** [PHPOffice/PhpSpreadsheet#3782]
This is:

- [x] a bug report
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
PHP 8.3 does not support use of `new ReflectionMethod(string $functionCall)` any more.
https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#reflectionmethodconstruct

### What is the current behavior?
Update it to `new ReflectionMethod(...explode("::", $functionCall))` as per https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#reflectionmethodconstruct

src/PhpSpreadsheet/Calculation/Calculation.php::addDefaultArgumentValues
```
$reflector = new ReflectionMethod(implode('::', $functionCall));
```

### What are the steps to reproduce?
I haven't reproduced this and I'm not sure how to reach this code. I came across it during an audit of our code for PHP 8.3.

### Which versions of PhpSpreadsheet and PHP are affected?
master with PHP 8.3 onwards

**Comment by oleibman** [comment]
Looking at the RFC, it appears that this deprecation will happen with Php 8.4, not 8.3. This is confirmed by the fact that our PR's test against nightly PHP (currently 8.3) and report no deprecation messages (the code in question is executed by many tests). Once 8.3 is formally introduced, and the change is added to the nightly code, we should see the deprecation messages and will act on them. I will leave this ticket open until that happens.

**Comment by andrewnicols** [comment]
Bah- thank you. I'd missed that detail in the vote.

**Comment by oleibman** [comment]
Unsurprisingly, the first nightly version of 8.4 does not treat this as a deprecation. I will continue to monitor.

**Comment by oleibman** [comment]
It appears that the change was applied to 8.4 in the nightly build yesterday. Assuming that the PR shows no errors this morning, I will merge it.
