### ISSUE TITLE
for saving memory, how to save xlsl full with setLoadSheetsOnly in cycle

### ISSUE THREAD

**Issue by cokeTsang** [PHPOffice/PhpSpreadsheet#3798]
This is:

```
 a usage question
```

### What is the expected behavior?
 my export system need to export more than one million rows
 want to take some rows into one sheet,like one hundred thousand for one sheet
 for saving memory i would like to deal on: get rows->save->add sheet->free memory->recycle
 file cache too slow i try
 see my example code thanks

### What is the current behavior?
save without all sheet

### What are the steps to reproduce?
```php
<?php

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;



$filePath = 'path';
$spreadsheet = new Spreadsheet();
$writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
for ($activeSheetIndex = 0; $activeSheetIndex < 5; $activeSheetIndex++) {
    // save some rows as first sheet

    //ready next sheet
    $spreadsheet->addSheet(new Worksheet($spreadsheet))->setTitle('Sheet' . $activeSheetIndex);

    //save to file
    $writer->save($filePath);

    ///free memory
    $spreadsheet->disconnectWorksheets();

    //read and load the saved file
    $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
    $spreadsheet = $reader->load($filePath);

    /**
     * if set setLoadSheetsOnly, other sheet can not save, how to fix it or how to do this
     */
    //$reader->setLoadSheetsOnly(['Sheet' . $activeSheetIndex]);

    //using next sheet
    $spreadsheet->setActiveSheetIndexByName('Sheet' . $activeSheetIndex);

    //update writer
    $writer = new Xlsx($spreadsheet);
}
```

### What features do you think are causing the issue

- [√] Reader
- [√ ] Writer

### Which versions of PhpSpreadsheet and PHP are affected?
php7.3

**Comment by MarkBaker** [comment]
Why do you need to save and reload?

**Comment by cokeTsang** [comment]
> Why do you need to save and reload?
@MarkBaker 
Beasause got too much rows for export in xlsx, if save to spreadsheet onetime will memory limit.
My server only 16G memory,but i need to save many rows to one xlsx file

**Comment by cokeTsang** [comment]
ok,i got it.thanks
