### ISSUE TITLE
HTML export with wrong styles

### ISSUE THREAD

**Issue by libo7878** [PHPOffice/PhpSpreadsheet#38]
Hi,
I use several days PhpSpreadsheet for a project. It works great, I'm excited! But I have a problem now with HTML excport. I first set the default border with an array to all cells:

```php
        $this->stdStyle = [
            'borders' => [
                'allborders' => [
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                    'color' => [
                        'argb' => 'FFC0C0C0'
                    ],
                ],
            ],
        ];
```

Then I use following style array for the first two rows on the right side:

```php
        $this->blackBorderStyle = [
            'borders' => [
                'outline' => [
                    'style' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_MEDIUM,
                    'color' => [
                        'argb' => \PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLACK
                    ],
                ],
            ],
        ];
```

But I see the left Border of the third row has the black border. It should be grey. And the right border disappears. This happens just in HTML export. The borders in exported Xlsx File are correct.

Can somebody correct this?  Thanks in advance!

Bobo
![html_style_error](https://cloud.githubusercontent.com/assets/23209899/19923056/d96e3122-a0e5-11e6-8c23-ad0a335627ba.PNG)

**Comment by PowerKiKi** [comment]
If you are able to submit a PR (including unit tests) to fix this, I would merge it.

**Comment by libo7878** [comment]
I think there is no simple solution because of border-collapse:collapse. With this style we can get nice table with 1px border. But if two cells have different styles on same position, we can do nothing here, because this behavior is defined on the page https://www.w3.org/TR/CSS21/tables.html#collapsing-borders

"If none of the styles are 'hidden' and at least one of them is not 'none', then narrow borders are discarded in favor of wider ones."

This behavior is not a bug and please close this issue!
