### ISSUE TITLE
Bug: Calculation.php & Logger.php

### ISSUE THREAD

**Issue by abhi11verma** [PHPOffice/PhpSpreadsheet#380]
This is:

```
- [* ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Generate an excel file.

### What is the current behavior?
On generating excel file it throws a 500 server error.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
under file .vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Calculation\Calculation.php
Line number 3036 :  private static function mkMatrix(...$args) 
&
.\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Calculation\Engine\Logger.php
Line number 93:  public function writeDebugLog(...$args)

removing ... makes the code work properly

**Comment by abhi11verma** [comment]
editing these 2 files makes the code work properly.

**Comment by PowerKiKi** [comment]
What is your PHP version ?

**Comment by abhi11verma** [comment]
5.5

**Comment by PowerKiKi** [comment]
[PhpSpreadsheet does not support PHP 5.5](https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/composer.json#L36).
