### ISSUE TITLE
Invalid cell coordinate error

### ISSUE THREAD

**Issue by Plasmatron** [PHPOffice/PhpSpreadsheet#381]
This is:

```
- [ ] a bug report
```

### What are the steps to reproduce?
When I load a template which has a formula e.g. =SUM(Sheet2!E:E) it causes an error. Other similar formulas don't cause the error like =SUM(Sheet2!E2:E27) or =SUM(E:E).

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\IOFactory;
$reader=IOFactory::createReader('Xlsx');
$spreadsheet=$reader->load($file_path);
$writer=new Xlsx($spreadsheet);
$writer->save($file_path);


### Which versions of PhpSpreadsheet and PHP are affected?

**Comment by PowerKiKi** [comment]
Please provide a MCVE without relying on an external to reproduce the issue.

**Comment by Plasmatron** [comment]
1. Create an excel spreadsheet with the formula =SUM(Sheet2!E:E) on cell A1 on Sheet1.
2. Use earlier provided generic PHPSpreadsheet code - to open that newly created excel spreadsheet and then save it. It will be unable to save claiming an invalid cell coordinate error.

**Comment by oleibman** [comment]
Cell coordinate AAAC2 *is* invalid. Excel does not permit columns beyond XFD (which is how  `Cell\AddressRange::MAX_COLUMN` is defined).

**Comment by fwilliamconceicao** [comment]
> Cell coordinate AAAC2 _is_ invalid. Excel does not permit columns beyond XFD (which is how `Cell\AddressRange::MAX_COLUMN` is defined).

I do not understand how this issue is closed without any investigation.

But to reproduce this is very simple:

Just create a large. CSV (my case was with .csv extension) file with 800+ lines and at least 20 columns. You'll see it happening while you're trying to read.

**Comment by oleibman** [comment]
The issue was closed over 5 years ago. The fact that you added a comment to it 4 days ago did not reopen it. Nevertheless, based on the incomprehensibly small amount of information you supplied, PhpSpreadsheet was acting correctly, and I explained why. There was certainly no reason to reopen it based on that. You have now supplied new information which may or may not change my assessment. When I get a chance, I will try to use that information to see if I can duplicate your symptom. However, it will make things quicker if you can supply the CSV (or a program which generates it), and a program which fails in the manner you describe when PhpSpreadsheet tries to read it.

**Comment by oleibman** [comment]
The following code, based on your "reproduce" instructions above, performs hideously, but that's not what this issue is about.
```php
use PhpOffice\PhpSpreadsheet\Reader\Csv;

$row = "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21\n";
$maxRows = 850000;
$filename = 'issue.381.csv';
echo "creating $filename\n";
$fh = fopen($filename, 'wb');
for ($i = 0; $i < $maxRows; ++$i) {
    if ($i % 10000 === 9999) {
        echo "writing row $i\n";
    }
    fwrite($fh, $row);
}
fclose($fh);
echo "file is written - starting read\n";
$reader = new Csv();
$spreadsheet = $reader->load($filename);
echo "read is complete\n";
$sheet = $spreadsheet->getActiveSheet();
var_dump($sheet->getCell('T99')->getValue()); // expect int(20)
var_dump($sheet->getCell('D810000')->getValue()); // expect int(4)
```
When the code finally completes, I do not see any exception messages, and the var_dumps show the expected results. So, there is apparently more to your problem than what you have posted so far. At any rate, when you do have a reproducible bug, please open a new issue, rather than adding on to this one.

**Comment by fwilliamconceicao** [comment]
> The following code, based on your "reproduce" instructions above, performs hideously, but that's not what this issue is about.
> 
> ```
> use PhpOffice\PhpSpreadsheet\Reader\Csv;
> 
> $row = "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21\n";
> $maxRows = 850000;
> $filename = 'issue.381.csv';
> echo "creating $filename\n";
> $fh = fopen($filename, 'wb');
> for ($i = 0; $i < $maxRows; ++$i) {
>     if ($i % 10000 === 9999) {
>         echo "writing row $i\n";
>     }
>     fwrite($fh, $row);
> }
> fclose($fh);
> echo "file is written - starting read\n";
> $reader = new Csv();
> $spreadsheet = $reader->load($filename);
> echo "read is complete\n";
> $sheet = $spreadsheet->getActiveSheet();
> var_dump($sheet->getCell('T99')->getValue()); // expect int(20)
> var_dump($sheet->getCell('D810000')->getValue()); // expect int(4)
> ```
> 
> When the code finally completes, I do not see any exception messages, and the var_dumps show the expected results. So, there is apparently more to your problem than what you have posted so far. At any rate, when you do have a reproducible bug, please open a new issue, rather than adding on to this one.

Hi, 

I'm providing my file example (without the real data but with the right numbers of headers + cols) to contribute.

The attachment
[ISSUE #381.csv](https://github.com/PHPOffice/PhpSpreadsheet/files/12926236/ISSUE.381.csv)
 is my file.

**Comment by oleibman** [comment]
I still don't see a problem.
```php
$filename = 'issue.381c.csv';
echo "starting read\n";
$reader = new Csv();
$spreadsheet = $reader->load($filename);
echo "read is complete\n";
$sheet = $spreadsheet->getActiveSheet();
var_dump($sheet->getCell('T99')->getValue()); // expect V98
var_dump($sheet->getCell('AR243')->getValue()); // last cell - expect V242
```
Program output:
```
starting read
read is complete
C:\git\issue.381c.php:14:
string(3) "V98"
C:\git\issue.381c.php:15:
string(4) "V242"
```
