### ISSUE TITLE
error in reading

### ISSUE THREAD

**Issue by fakol** [PHPOffice/PhpSpreadsheet#3813]
This is:

### What is the current behavior?
An error is occurring
Fatal error: Uncaught Error: Call to a member function log() on null
### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php
require "../../vendor/autoload.php";

use PhpOffice\PhpSpreadsheet\IOFactory;


$inputFileType = 'Xlsx';
$inputFileName = '../forma.xlsx';

$helper->log('Loading file ' . pathinfo($inputFileName, PATHINFO_BASENAME) . ' using IOFactory with a defined reader type of ' . $inputFileType);
$reader = IOFactory::createReader($inputFileType);
$helper->log('Turning Formatting off for Load');
$reader->setReadDataOnly(true);
$spreadsheet = $reader->load($inputFileName);

$sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);
$helper->displayGrid($sheetData);
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [*] Reader

### Which versions of PhpSpreadsheet and PHP are affected?
1.28 \ 7.4

**Comment by oleibman** [comment]
You will need to upload the spreadsheet; I will not be able to solve this without it. Also, although this may not factor into the problem you should be making plans to migrate to newer versions of Php (7.4 is no longer supported) and PhpSpreadsheet (we are on release 1.29).

**Comment by fakol** [comment]
![image](https://github.com/PHPOffice/PhpSpreadsheet/assets/41354153/b641bff1-bf6f-4690-905a-34276a7dc598)
I have the most ordinary table, but for some reason an error occurs

**Comment by fakol** [comment]
If you remove the log function, then the error occurs in the last line

Fatal error: Uncaught Error: Call to a member function displayGrid() on null

**Comment by fakol** [comment]
I figured out everything that was missing
