### ISSUE TITLE
Image does not appear in Excel file

### ISSUE THREAD

**Issue by 1X9X8X4** [PHPOffice/PhpSpreadsheet#3843]
This is:

```
- [x] a bug report
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Image appears in Excel file.

### What is the current behavior?
Image does not appear in Excel file.

### What are the steps to reproduce?
The phenomenon occurs when the following code is executed
I would like to display an image in excel loaded using phpspreadsheet but it does not show up.
I have confirmed that the text is displayed.
I would appreciate it if you could show me how to get the images to display.
"template.xlsx" is not default Excel file.
[template.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/13784596/template.xlsx)

```php
<?php

require __DIR__ . '/vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as XlsxWriter;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;

$filePath = __DIR__ . '/template.xlsx';
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($filePath);
$worksheet = $spreadsheet->getSheetByName('Sheet1');

$worksheet->setCellValue('A1', 'test');

$image_path = __DIR__ . '/images/test.jpg';
$drawing = new Drawing();
$drawing->setPath($image_path);
$drawing->setCoordinates('A2');
$drawing->setWidth(100);
$drawing->setHeight(100);
$drawing->setResizeProportional(false);
$drawing->setWorksheet($worksheet);
	
$fileName = 'test.xlsx';
$savePath = __DIR__ . '/test.xlsx';
$writer = new XlsxWriter($spreadsheet);
$writer->save($savePath);
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;');
header("Content-Disposition: attachment; filename=\"{$fileName}\"");
header('Cache-Control: max-age=0');
readfile($savePath);
exit;
```

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet : 1.29.0
PHP : 7.4.33

**Comment by oleibman** [comment]
Unable to duplicate. I used your code with a template and image file of my own, and the resulting spreadsheet contained the image. Perhaps if you upload your file here, I can try to see what might be wrong.

**Comment by 1X9X8X4** [comment]
Sorry, there was one mistake.
template.xlsx is a non-default file.
Please check it.
[template.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/13784607/template.xlsx)

**Comment by oleibman** [comment]
Thank you for uploading the file. This is a strange case. The xml in your template file has references to some drawings (possibly textbox form controls) which apparently are not part of the worksheet, and, when we add a new drawing, PhpSpreadsheet is getting confused about which drawings are needed. While I study what needs to be done, you might be able to use this edited template, which does not have the unused drawings, in place of your template:
[issue.3843a.template.edited.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/13788657/issue.3843a.template.edited.xlsx)

**Comment by 1X9X8X4** [comment]
Thank you for the issue.3843a.template.edited.xlsx.
I can confirm that the images are displayed.
What is the difference between that file and the template.xlsx I attached?

**Comment by oleibman** [comment]
I removed the (unused) data that was being handled incorrectly.

**Comment by 1X9X8X4** [comment]
I see.
It was very helpful.
Thank you very much.
