### ISSUE TITLE
Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes)

### ISSUE THREAD

**Issue by yugandharjaiswal92** [PHPOffice/PhpSpreadsheet#386]
This is:
i'm getting error while copying a sheet with an image from external file in folder
without image its working fine but with image it runs for a while and i got memory error

please help me
```
- [ Y] a bug report
- [ N] a feature request
- [ N] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
i want to copy a spreadsheet with image to new worksheet

### What is the current behavior?
gettin memory error

### What are the steps to reproduce?
```php
<?php 
require 'spreadsheet/autoload.php';
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\IOFactory;

header('Access-Control-Allow-Origin: *'); 
//header('Content-Type: application/json');
include_once('../functions/functions.php');

$spreadsheetDemo = IOFactory::load("copyfrom.xlsx");  // xl file with one worksheet with image
$clonedWorksheet = clone $spreadsheetDemo->getActiveSheet();
//$clonedWorksheet->setTitle('copied file');

$spreadsheet = new Spreadsheet();
$spreadsheet->removeSheetByIndex(0);
	
$spreadsheet->addExternalSheet($clonedWorksheet);
$writer = new Xlsx($spreadsheet);
$writer->save('copy12.xlsx');
	
?>
```

**Comment by PowerKiKi** [comment]
The code example cannot be run. Try increasing your memory limit.

**Comment by Yugandharjaiswal** [comment]
i can not i'm on shared hosting they wont allow me to do that

**Comment by stevencsf** [comment]
I have almost same case. Now i try to upgrade my project form phpexcel to phpspreadsheet.
Some old report using a image form a template in phpexcel still work fine but will over memory usage in phpspreadsheet. i checked the copy function, the spreadsheet is difference then phpexcel which phpexcel will clone whole drawcollection object but in spreadsheet will look inside and copy the collect one by one. but i am not sure d othe drawcollect looping have any problem which will make the copy again and again. then use over the memory pool.

**Comment by PowerKiKi** [comment]
@stevencsf see #437 and related PR

**Comment by tjvg91** [comment]
Do you still encounter this issue? I encounter this every time I execute `$writer->writeToAllSheets()`.
