### ISSUE TITLE
Need pivot table functionality with phpoffice/phpspreadsheet

### ISSUE THREAD

**Issue by arunahkk** [PHPOffice/PhpSpreadsheet#3870]
Need pivot table functionality with phpoffice/phpspreadsheet

**Comment by MarkBaker** [comment]
This is an Open Source project and you're always free to submit a PR with the solution yourself

**Comment by arunahkk** [comment]
@MarkBaker  I am completely new to php code. Currently I need pivot table functionality with phpoffice/phpspreadsheet. I request you to provide if you have anything

**Comment by PowerKiKi** [comment]
It is not planned by the core team. However if somebody creates a PR for it, it could be merged.

**Comment by oleibman** [comment]
Pivot table support was added with PR #4942. Changing close status to from not-planned to completed.
