### ISSUE TITLE
Does this still support PHP 7.4.33?

### ISSUE THREAD

**Issue by AgungPutra0708** [PHPOffice/PhpSpreadsheet#3874]
Because I am running on php 7.4.33 the following error appears

ParseError
syntax error, unexpected '|', expecting variable (T_VARIABLE)
### VENDORPATH\psr\simple-cache\src\CacheInterface.php at line 34

```
27      *                                      for it or let the driver take care of that.
28      *
29      * @return bool True on success and false on failure.
30      *
31      * @throws \Psr\SimpleCache\InvalidArgumentException
32      *   MUST be thrown if the $key string is not a legal value.
33      */
34     public function set(string $key, mixed $value, null|int|\DateInterval $ttl = null): bool;
35 
36     /**
37      * Delete an item from the cache by its unique key.
38      *
39      * @param string $key The unique cache key of the item to delete.
40      *
41      * @return bool True if the item was successfully removed. False if there was an error.
```

**Comment by oleibman** [comment]
The most recent formal release (1.29) does support Php 7.4; the next release will not.

The problem you are seeing indicates a Composer problem. The version of psr/simple-cache which you have installed is usable only with Php 8+. Is it possible that you you did your Composer install/require with Php8 and then attempted to run PhpSpreadsheet with Php7?
