### ISSUE TITLE
How to apply file encryption password?

### ISSUE THREAD

**Issue by rodrigoguariento** [PHPOffice/PhpSpreadsheet#3878]
This is:

```
- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Apply file encryption password programmatically, namely, the password is required to open the file in Excel.

### What is the current behavior?
I haven't found documentation explaining this: https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#setting-security-on-a-spreadsheet

### What are the steps to reproduce?

N/A

### What features do you think are causing the issue

- [ ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
XLSX

### Which versions of PhpSpreadsheet and PHP are affected?
phpoffice/phpspreadsheet: ^1.29

**Comment by MarkBaker** [comment]
This feature isn't supported, and unless you can find details online of how Microsoft implements their file encryption then it's not practical.

**Comment by rodrigoguariento** [comment]
Alternatives? Suggestion? Someone?

**Comment by oleibman** [comment]
PR #4975 implements encryption support. Changing close reason from "not planned" to "completed".
