### ISSUE TITLE
Root package 'phpoffice/phpspreadsheet' cannot require itself in its composer.json

### ISSUE THREAD

**Issue by WhiteDragonD** [PHPOffice/PhpSpreadsheet#3881]
installed Composer through Windows/WAMP, 
When inside the directory of composer.json and running the require command:

D:\wamp\Server Apps Scripts\phpspreadsheet>composer require phpoffice/phpspreadsheet
Root package 'phpoffice/phpspreadsheet' cannot require itself in its composer.json

Help?

Composer version 2.6.6 2023-12-08 18:32:26
PHP 8.1.8

**Comment by WhiteDragonD** [comment]
I found a Chinese website that had a picture saying remove this line in composer.json

    "name": "phpoffice/phpspreadsheet",

https://blog.csdn.net/m0_47175673/article/details/132000933





D:\wamp\Server Apps Scripts\phpspreadsheet>composer require phpoffice/phpspreadsheet
./composer.json has been updated
Running composer update phpoffice/phpspreadsheet
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking phpoffice/phpspreadsheet (2.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading phpoffice/phpspreadsheet (2.0.0)
  - Installing phpoffice/phpspreadsheet (2.0.0): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
59 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
Using version ^2.0 for phpoffice/phpspreadsheet

D:\wamp\Server Apps Scripts\phpspreadsheet>composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 83 installs, 0 updates, 0 removals
  - Installing squizlabs/php_codesniffer (3.8.1): Extracting archive
  - Installing dealerdirect/phpcodesniffer-composer-installer (dev-main 290bcb6): Extracting archive
  - Installing composer/pcre (3.1.1): Extracting archive
  - Installing symfony/polyfill-iconv (v1.28.0): Extracting archive
  - Installing sabberworm/php-css-parser (8.4.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.28.0): Extracting archive
  - Installing phenx/php-svg-lib (0.5.1): Extracting archive
  - Installing phenx/php-font-lib (0.5.5): Extracting archive
  - Installing masterminds/html5 (2.8.1): Extracting archive
  - Installing dompdf/dompdf (v2.0.4): Extracting archive
  - Installing psr/container (2.0.2): Extracting archive
  - Installing symfony/service-contracts (v3.0.2): Extracting archive
  - Installing symfony/stopwatch (v6.0.19): Extracting archive
  - Installing symfony/process (v6.0.19): Extracting archive
  - Installing symfony/polyfill-php81 (v1.28.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.28.0): Extracting archive
  - Installing symfony/deprecation-contracts (v3.0.2): Extracting archive
  - Installing symfony/options-resolver (v6.0.19): Extracting archive
  - Installing symfony/finder (v6.0.19): Extracting archive
  - Installing symfony/polyfill-ctype (v1.28.0): Extracting archive
  - Installing symfony/filesystem (v6.0.19): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v3.0.2): Extracting archive
  - Installing symfony/event-dispatcher (v6.0.19): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.28.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.28.0): Extracting archive
  - Installing symfony/string (v6.0.19): Extracting archive
  - Installing symfony/console (v6.0.19): Extracting archive
  - Installing sebastian/diff (4.0.5): Extracting archive
  - Installing psr/log (3.0.0): Extracting archive
  - Installing composer/xdebug-handler (3.0.3): Extracting archive
  - Installing composer/semver (3.4.0): Extracting archive
  - Installing friendsofphp/php-cs-fixer (v3.48.0): Extracting archive
  - Installing mitoteam/jpgraph (10.4.1): Extracting archive
  - Installing setasign/fpdi (v2.6.0): Extracting archive
  - Installing psr/http-message (1.1): Extracting archive
  - Installing paragonie/random_compat (v9.99.100): Extracting archive
  - Installing myclabs/deep-copy (1.11.1): Extracting archive
  - Installing mpdf/psr-log-aware-trait (v3.0.0): Extracting archive
  - Installing mpdf/psr-http-message-shim (1.0.0): Extracting archive
  - Installing mpdf/mpdf (v8.2.2): Extracting archive
  - Installing myclabs/php-enum (1.8.4): Extracting archive
  - Installing phpcompatibility/php-compatibility (9.3.5): Extracting archive
  - Installing voku/portable-ascii (2.0.1): Extracting archive
  - Installing symfony/polyfill-php72 (v1.28.0): Extracting archive
  - Installing voku/portable-utf8 (6.0.13): Extracting archive
  - Installing voku/anti-xss (4.1.42): Extracting archive
  - Installing psr/simple-cache (3.0.0): Extracting archive
  - Installing psr/http-factory (1.0.2): Extracting archive
  - Installing psr/http-client (1.0.3): Extracting archive
  - Installing markbaker/matrix (3.0.1): Extracting archive
  - Installing markbaker/complex (3.0.2): Extracting archive
  - Installing maennchen/zipstream-php (2.4.0): Extracting archive
  - Installing phpoffice/phpspreadsheet (2.0.0): Extracting archive
  - Installing phpstan/phpstan (1.10.57): Extracting archive
  - Installing phpstan/phpstan-phpunit (1.3.15): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (3.2.1): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.5): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.6): Extracting archive
  - Installing sebastian/exporter (4.0.5): Extracting archive
  - Installing sebastian/environment (5.1.5): Extracting archive
  - Installing sebastian/comparator (4.0.8): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing theseer/tokenizer (1.2.2): Extracting archive
  - Installing nikic/php-parser (v5.0.0): Extracting archive
  - Installing sebastian/lines-of-code (1.0.4): Extracting archive
  - Installing sebastian/complexity (2.0.3): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.30): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing doctrine/instantiator (1.5.0): Extracting archive
  - Installing phpunit/phpunit (9.6.16): Extracting archive
  - Installing tecnickcom/tcpdf (6.6.5): Extracting archive
Generating autoload files
59 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility

D:\wamp\Server Apps Scripts\phpspreadsheet>

**Comment by PowerKiKi** [comment]
This is an incorrect use of composer. Not a bug in PhpSpreadsheet.

**Comment by WhiteDragonD** [comment]
I am a newb.... was just following the instructions without knowing what to do :D
