### ISSUE TITLE
First Php8.4 Problem - ROUNDUP and ROUNDDOWN

### ISSUE THREAD

**Issue by oleibman** [PHPOffice/PhpSpreadsheet#3896]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Under Php7 and Php8 <= 8.3
```
var_dump(2..26 + 2.94);

double(5.2)
```

### What is the current behavior?
Under Php8.4 nightly:
```
float(5.199999999999999)
```
I don't know if the difference between `double` and `float` is significant. But the difference in the result can affect, at the very least, ROUNDUP and ROUNDDOWN.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->getCell('A1')->setValue('=ROUNDDOWN(2.26 + 2.94, 2)');
$result1 = $sheet->getCell('A1')->getCalculatedValue();
var_dump($result1);
```
The result is 5.19 in Php8.4, 5.20 in earlier releases.

If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [x] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
All

### Which versions of PhpSpreadsheet and PHP are affected?
Any version of PhpSpreadsheet using Php8.4 is affected.

**Comment by oleibman** [comment]
One AMORDEGRC test is also affected.

**Comment by oleibman** [comment]
According to https://stackoverflow.com/questions/3280892/difference-between-float-and-double-in-php, the difference between `float` and `double` in the output depends merely on the availability of xdebug.

**Comment by lucasnetau** [comment]
Hi @oleibman, PHP8.4 has a change to round which extends the precision by one digit https://github.com/php/php-src/commit/703ead5a26a57cd4de03e4a9d978646b01107ee5 which is the likely cause of the issue.

FWIW float(5.199999999999999) is the output value since PHP8 per https://github.com/php/php-src/blob/PHP-8.0/UPGRADING#L584#L587 because var_dump moved to using serialize_precision instead of precision. In 8.0 serialize_precision is defaulted to -1. If you ini_set precision to -1 in PHP 7.1 to 7.4 you also get float(5.199999999999999) as the output. See https://3v4l.org/duI8M

**Comment by oleibman** [comment]
@lucasnetau Thank you for the research. It is always nicer to be able to point to the smoking gun rather than fall back on "something changed".
