### ISSUE TITLE
UNIQUE and SORT are amended with a "@" making the calculation incorrect.

### ISSUE THREAD

**Issue by roland-jungwirth** [PHPOffice/PhpSpreadsheet#3901]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The function "UNIQUE" or "SORT" should not append a "@" breaking it.

### What is the current behavior?
If I read a sheet with the formula "=UNIQUE(A1:A19)" or "=SORT(A1:A19)", the resulting formulas are "=@UNIQUE(A1:A19)" and "=@SORT(A1:A19)" respectively. This is irrelevant of whether the sheet already has that formula in a cell, or I set the cell's value with the formula.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$test_numbers = array( 41, 57, 51, 54, 49, 43, 35, 35, 44, 47, 48, 26, 57, 34, 61, 34, 28, 29, 41 );
$columnArray = array_chunk($test_numbers, 1);
$spreadsheet->setActiveSheetIndex( 0 )->fromArray( $columnArray, 'A1' );

$spreadsheet->setActiveSheetIndex( 0 )->setCellValue('C1', '=UNIQUE(A1:A19)');
$spreadsheet->setActiveSheetIndex( 0 )->setCellValue('D1', '=SORT(A1:A19)');

$writer = new Xlsx( $spreadsheet );
ob_end_clean();
$writer->save( 'php://output' );
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [X ] Reader
- [X] Writer
- [ ] Styles
- [ ] Data Validations
- [X] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
No idea, I only tested it with .xlsx files.

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 8.1, PhpSpreadsheet: whatever this version is: https://github.com/PHPOffice/PhpSpreadsheet/issues/3767

[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/14283238/test.xlsx)

**Comment by oleibman** [comment]
See https://github.com/PHPOffice/PhpSpreadsheet/pull/3659#issuecomment-1663040464 for an explanation of the at sign. As I mentioned in that comment, I haven't been able to figure out what has to be done to keep Excel from adding it (it is *not* present in the spreadsheet generated by PhpSpreadsheet).

**Comment by roland-jungwirth** [comment]
Thank you for the explanation. I'll extract the data via PHP and write them as values.
