### ISSUE TITLE
Writing a CSV file with many lines noticeable slower than before

### ISSUE THREAD

**Issue by ArtoNiittukari** [PHPOffice/PhpSpreadsheet#3904]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Writing a CSV file with many lines was generally fast in 1.29.0, as expected.

### What is the current behavior?
Writing a file with many lines is noticeable slower in 2.0.0 than 1.29.0. I have pinpointed the issue to commit 096e193495754784cee5d9212728a0f366dc4f75 because the earlier commit 9f87d7c8e6139fb3117b04372e7fad409f5e647e before that is fast. The culprit seems to be \PhpOffice\PhpSpreadsheet\Worksheet\namedRangeToArray(). The writing time seems to increase more and more when more lines are added. This can be tested by writing 10k lines vs. 20k lines where the difference is already big.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$rows = [];

// Add many lines to one column only
for ($i = 0; $i < 50000; $i++) {
    $rows[] = ['A' . $i + 1];
}

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, \PhpOffice\PhpSpreadsheet\IOFactory::WRITER_CSV);

$worksheet = $spreadsheet->getActiveSheet();
$worksheet->fromArray($rows);

$start = \microtime(true);

$writer->save('test.csv');

echo \microtime(true) - $start . "\n";
// 0.71157717704773 in 1.29.0
// 350.71549415588 in 2.0.0
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
I think this only affects CSV. Writing an XLSX file with the same code is still fast.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 2.0.0, tested with PHP 8.2.13

**Comment by oleibman** [comment]
Thank you for the report and the analysis. Expect a fix in a day or two.
