### ISSUE TITLE
setReadDataOnly function is deprecated or missing

### ISSUE THREAD

**Issue by spectoras** [PHPOffice/PhpSpreadsheet#3943]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The function should exist didnt found any deprecated issue.

### What is the current behavior?
Some numbers like 3.2.11 is read 3 february 2012

### Which versions of PhpSpreadsheet and PHP are affected?
Newest i use composer

Iam trying to use setReadDataOnly(true) but vs code writes me its undefined. Iam using composer to install the library and It is working except this function. I try the below code :

$reader = IOFactory::createReader('Xlsx');
$spreadsheet = $reader->load($file['tmp_name']);
$worksheet = $spreadsheet->getSheet(9);
$worksheet->getParent()->setReadDataOnly(true);

**Comment by MarkBaker** [comment]
`setReadDataOnly()` is a method of the Reader, called before you load the spreadsheet. Calling it against the Spreadsheet once you've already loaded it is rather pointless because the purpose of the method is to tell the Reader whether it should load spreadsheet style and structure information or not.

**Comment by MarkBaker** [comment]
> `Some numbers like 3.2.11 is read 3 february 2012`

What is `3.2.11`? It certainly isn't a number

**Comment by spectoras** [comment]
It should be a string but with or without setreaddataonly it is no
use.....it reads it like a date....

Στις Κυρ 10 Μαρ 2024, 10:24 μ.μ. ο χρήστης Mark Baker <
***@***.***> έγραψε:

**Comment by MarkBaker** [comment]
If this was an Excel xls or xlsx file, then it should be defined as a string in the file, and treated as such by PhpSpreadsheet.
If it's being treated otherwise, then please provide an example file that will allow us to identify why it is being considered as a date and not as a string.

**Comment by oleibman** [comment]
No update in 5 months, closing.
