### ISSUE TITLE
Need help regarding download of excel file.

### ISSUE THREAD

**Issue by ehtishamalli** [PHPOffice/PhpSpreadsheet#3948]
Hi,

I need a help regarding installing this library i install it with composer and when i try to download file with sample basic example [01_Simple_download_xlsx.php](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Basic/01_Simple_download_xlsx.php) 
it download the file.

but when I try to open file it give me an error of "The file format or extension doesn`t match provide valid extension or verify your file". and when i try to open it some random alphabets is written in file. can you help me with this.

thanks  

<img width="677" alt="Screenshot 2024-03-16 173814" src="https://github.com/PHPOffice/PhpSpreadsheet/assets/154227711/536a6a65-62c5-4eaa-9c05-95c4d693fb5d">
<img width="734" alt="Screenshot 2024-03-16 174023242" src="https://github.com/PHPOffice/PhpSpreadsheet/assets/154227711/7a8ddf0f-6def-45d9-ae55-292ee5ded82e">

**Comment by adsheff** [comment]
What was your solution?
