### ISSUE TITLE
Protect Sheet But Allow Sort not working

### ISSUE THREAD

**Issue by don-odyssey** [PHPOffice/PhpSpreadsheet#3951]
Hi,

When applying a filter and protecting the sheet, the Sort does not work

**Comment by don-odyssey** [comment]
Here is my PHP code

    // set security
    $protection = $spreadsheet->getActiveSheet()->getProtection();
    $protection->setPassword($mslReportsPassword);
    $protection->setSheet(true);
    $protection->setInsertRows(true);
    $protection->setFormatCells(true);
    $protection->setObjects(true);
    $protection->setAutoFilter(false);
    $protection->setSort(true);

**Comment by oleibman** [comment]
Enabling sorting on a protected sheet in Excel seems more complicated than it ought to be. See https://www.extendoffice.com/documents/excel/4673-excel-sort-filter-protected-sheet.html. This means that you have to explicitly protect ranges that you want to be able to sort/filter on a protected sheet. PhpSpreadsheet does not currently support that. I will treat this issue as a feature request, and start looking into that.
