### ISSUE TITLE
Make voku packages optional

### ISSUE THREAD

**Issue by jasverix** [PHPOffice/PhpSpreadsheet#3954]
This is:

```
- [ ] a bug report
- [ x ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
PhpSpreadsheet is about handling spreadsheets like Excel and LibreCalc files. We don't use the HTML support part of the package at all. While it is great that there is a HTML support, it should be optional.

Move the voku package to the "suggested" part of the composer.json.

The reason for this being a problem is that it in turn gets "voku/portable-utf8" which has a bootstrap.php running a ini_set(). We don't want a open source package to run ini_set on our application without our knowledge. voku/portable-utf8 did take down our system some time ago, so we have a company restriction against using that package. It is too bad if we cannot use phpspreadsheet because of a HTML support that we don't really use.

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
Yes, it affect all formats, but it should only affect the HTML format.

### Which versions of PhpSpreadsheet and PHP are affected?
2.*

**Comment by oleibman** [comment]
I know it's not optimal, but you can always use Composer to delete the Voku packages. We cannot make this optional - it exposes our users to security issues. For that reason, I am closing the PR associated with this. We could replace it with another package - we tried another earlier but people complained about aspects of it as well. I am working on a different approach which I think could eliminate the need for a sanitizer package; I will leave this issue open while I work on it.

**Comment by jasverix** [comment]
Only the users that use the HTML writer. Maybe disable the entire HTML writer if the voku package is not included? Then it will not be a security risk. I don't need it, and we cannot accept the ini_set() in bootstrap.php.

**Comment by cmanley** [comment]
Can't it just be documented as the responsibility of the caller to sanitize the html if and however they see fit instead of pulling in who knows what for dependencies?

**Comment by cmanley** [comment]
But what do you think about the idea I offered?

**Comment by oleibman** [comment]
I think the merged PR renders your suggestion moot. There is no longer a need for the users to do anything with their Html.
