### ISSUE TITLE
IOFactory::load() loads files that are not spreadsheet files without throwing an exception

### ISSUE THREAD

**Issue by ajabusch** [PHPOffice/PhpSpreadsheet#396]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Loading a file that is not a spreadsheet file should throw an exception, like it happened in PHPExcel.

### What is the current behavior?
\PhpOffice\PhpSpreadsheet\IOFactory::load($path) loads files (e.g. a php source file) as xlsx spreadsheet. If you save that file via IOFactory::createWriter you can see the content of the file put in an xlsx file.

### What are the steps to reproduce?

Load a file that is not an Xlsx via IOFactory::load($path)  (e.g. a php source file). => no exception is thrown.
Save that file via IOFactory::createWriter, inspect the output => the content of the txt/php file is saved as a xlsx file.

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object

// add code that show the issue here...

        try {
            $excel = \PhpOffice\PhpSpreadsheet\IOFactory::load(__FILE__);
        } catch (\Exception $e) {
            // 'This should not work!';
        }

        try {
            $writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($excel, "Xlsx");
            $writer->save("/tmp/tmp.xlsx");
        } catch (Exception $e) {
            // 'This should not work!' ;
        }

```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.1
Php 7.1

**Comment by ajabusch** [comment]
Okay, I found a workaround.
If you know, that you expect an xlsx, you can use 

    $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();

or

    $reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');

to get the reader and from then on the expected old behavior is back and an exception is thrown.
Might be hard to validate if an file is an spreadsheet when CSVs are supported, so maybe this is not really a bug.

**Comment by PowerKiKi** [comment]
Your conclusion is correct, but it should be mitigated once https://github.com/PHPOffice/PhpSpreadsheet/commit/e31878ceb12c3cb6deba8cbfbff9cd3f2de4de17 is released.
