### ISSUE TITLE
Some methods removed in v2.0 but not mentioned in CHANGELOG file

### ISSUE THREAD

**Issue by wajdijurry** [PHPOffice/PhpSpreadsheet#3964]
Some methods (ex.:  `setCellValueByColumnAndRow`) has been removed in v2.0 but not mentioned in the [CHANGELOG](https://github.com/PHPOffice/PhpSpreadsheet/blob/2.0.0/CHANGELOG.md) file.

Please consider updating it as it might misleading for whom are using this package.

**Comment by MarkBaker** [comment]
It does kind of get a mention:
> All deprecated things have been removed, for details, see [816b91d0b4](https://github.com/PHPOffice/PhpSpreadsheet/commit/816b91d0b4a0c7285a9e3fc88c58f7730d922044)

And then, in the [code linked by the above] (https://github.com/PHPOffice/PhpSpreadsheet/commit/816b91d0b4a0c7285a9e3fc88c58f7730d922044#diff-50511008e409893e5826291c61bad6a05b641e4a81dfb56da7c9b5b4f97a2ed5L1108)

The method had also been flagged as deprecated for several releases before 2.0, specifically in [release 1.23.0](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.23.0) on 24th April 2022, when it appeared in the Change Log.

**Comment by oleibman** [comment]
Hopefully release notes for 3.3.0 (should have been 3.0.0, but I made a typo) were clearer about what has gone away, and how to deal with it. Closing this issue. Feel free to add comments if I still missed the mark.
