### ISSUE TITLE
syntax error in xls.php file

### ISSUE THREAD

**Issue by Amrin3456** [PHPOffice/PhpSpreadsheet#3965]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I am trying to import data fro excel to database.

### What is the current behavior?
I am getting this error
PHP version is 8.1.10

{
    "require": {
        "phpoffice/phpspreadsheet": "^2.0"
    }
}

Parse error: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in C:\laragon\www\crosslink\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xls.php on line 382

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by oleibman** [comment]
Can you tell me what version of PhpSpreadsheet you are using? Can you tell me what is on:
```
\laragon\www\crosslink\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xls.php
```
