### ISSUE TITLE
Could not close zip file

### ISSUE THREAD

**Issue by isopen** [PHPOffice/PhpSpreadsheet#397]
This is:
[PhpOffice\PhpSpreadsheet\Writer\Exception] 
Could not close zip file ...report.xlsx. (0)
..phpspreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php:375
#0: PhpOffice\PhpSpreadsheet\Writer\Xlsx->save(string)
	...cron.php:396

php5.6
php5-zip php5-gd php5-dom install

**Comment by flohw** [comment]
Path to file may not exist.

**Comment by dvlpr91** [comment]
fucking...

**Comment by abrakadabra-go** [comment]
fak...

**Comment by RecentForce99** [comment]
Fuck
