### ISSUE TITLE
giao dịch đồng thời php

### ISSUE THREAD

**Issue by thnhat8282** [PHPOffice/PhpSpreadsheet#3974]
This is:
tôi muốn khi một kết nối tới cơ sở dữ liệu thì môt table trong cơ sở dữ liệu không cho một kết nối khác chèn thêm hàng mới cho đến khi kết nối trước đó thực hiện xong nhiệm vụ (tôi đang học php) làm như thế nào? xin được giúp đỡ!
```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

**Comment by idovdw** [comment]
I tried to translate your question in English, translating into: _

> "Concurrent transactions"
"I want when a connection to the database prevents a table in the database from allowing another connection to insert new rows until the previous connection has completed its task (I'm learning php). any? Please help!"._ 

Can you verify this? Please ask questions and responses in English, so most people can understand.
Can you explain the relation of your question to PhpSpreadsheet?

**Comment by oleibman** [comment]
Closing. Not relevant to PhpSpreadsheet.
