### ISSUE TITLE
Reader destroys formulas

### ISSUE THREAD

**Issue by chrostek** [PHPOffice/PhpSpreadsheet#398]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Should output:
=SUM(E11:T11)

Cell V10, V32 and some others are correct, but V11 to V30 and others are wrong.

Same problem if i convert the file to xlsx before.

In the "old" PHPExcel everything was correct.

### What is the current behavior?
Output:
=SUM(E11:E11)

### What are the steps to reproduce?

Template File:
https://www.dropbox.com/s/v2z3xrnmeba94j5/37_UEBG_Einnahmemeldung.xls?dl=0

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
$filename = "37_UEBG_Einnahmemeldung.xls";
$spreadsheet = IOFactory::load($filename);
$spreadsheet->setActiveSheetIndexByName('verkauf');
echo $spreadsheet->getActiveSheet()->getCell('V11')->getValue();
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: 1.1.0
PHP: 7.0

**Comment by PowerKiKi** [comment]
Please provide an example that do **not** rely on an external file.

**Comment by chrostek** [comment]
How should i provide an example for a bug in the reader without an external file?!?

**Comment by PowerKiKi** [comment]
You can create a file from scratch with PhpSpreadsheet and then load that file.

**Comment by chrostek** [comment]
Sorry, but in PHPExcel this worked and i have not the time to create a file from scratch that will provide the same error. the file worked over years with PHPExcel, so it is not broken. the reader reads completely wrong formulars in some cells. even in xlsx. if i unzip the xlsx and look in the xml files the formula is correct. so its definitely a reader bug ... if you do not try to fix this, phpspreadsheet is unusable for me and i will migrate back to phpexcel ...
