### ISSUE TITLE
AdvancedValueBinder destroys style of previously loaded file

### ISSUE THREAD

**Issue by chrostek** [PHPOffice/PhpSpreadsheet#399]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Cell style (startColor / argb) of all cells should be the same in 37_UEBG_Einnahmemeldung.xls and 37_UEBG_Einnahmemeldung-test.xls

In the "old" PHPExcel everything was correct.

### What is the current behavior?
Cell style (startColor / argb) of the most colored cells (E10:T56, etc) is completely different

### What are the steps to reproduce?
Template File:
https://www.dropbox.com/s/v2z3xrnmeba94j5/37_UEBG_Einnahmemeldung.xls?dl=0

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Cell\AdvancedValueBinder;

$filename = "/var/www/intranet/htdocs/files/37_UEBG_Einnahmemeldung.xls";
$filename2 = "/var/www/intranet/htdocs/files/37_UEBG_Einnahmemeldung-test.xls";
$spreadsheet = IOFactory::load($filename);

Cell::setValueBinder( new AdvancedValueBinder() );
$spreadsheet->getActiveSheet()->SetCellValue('V3', '2018-02-01');

$objWriter = IOFactory::createWriter($spreadsheet, 'Xls');
$objWriter->save($filename2);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: 1.1.0
PHP: 7.0

**Comment by PowerKiKi** [comment]
Please provide an example that do not rely on an external file.

**Comment by chrostek** [comment]
How should i provide an example for a bug in the reader without an external file?!?
