### ISSUE TITLE
Password requested to open the Excel file

### ISSUE THREAD

**Issue by LauraBa** [PHPOffice/PhpSpreadsheet#40]
Hello,

how can I create a PHP Excel file that requires a Password to open the spreadsheet?
I only find functions to protect from writing.

Thanks

**Comment by PowerKiKi** [comment]
Please refrain to ask question on the issue tracker. Instead use the [Gitter chat](https://gitter.im/PHPOffice/PhpSpreadsheet) or StackOverflow.
