### ISSUE TITLE
Converting from excel to pdf

### ISSUE THREAD

**Issue by Cassio227** [PHPOffice/PhpSpreadsheet#400]
This is:

```
- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

The creation of a new PDF from an existing excel file.

### What is the current behavior?

It doesn't create it

### What are the steps to reproduce?

I'm using this simple code to test the feature, but I'm obtaining this report of fatal error

>  Fatal error: Fatal error: Uncaught exception 'PhpOffice\PhpSpreadsheet\Writer\Exception' with message 'Could not open file /pdf_finali/mario.pdf for writing.' in /membri/cassiodb/FEDEGARIPROVE/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Pdf.php:260 Stack trace: #0 /membri/cassiodb/FEDEGARIPROVE/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Pdf/Mpdf.php(33): PhpOffice\PhpSpreadsheet\Writer\Pdf->prepareForSave('/pdf_finali/mar...') #1 /membri/cassiodb/FEDEGARIPROVE/excel_to_pdf.php(29): PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf->save('/pdf_finali/mar...') #2 {main} thrown in /membri/cassiodb/FEDEGARIPROVE/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Pdf.php on line 260

```php
<?php
require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;
use PhpOffice\PhpSpreadsheet\Spreadsheet;

$new_excel_path = "prova_inserimento.xlsx";
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader("Xlsx");
$spreadsheet = $reader->load("$new_excel_path");

echo 'Fino alla creazione del foglio tutto bene <br> <br><br><br>';

//Conversione della variabile spreadsheet in pdf

//Creazione del writer
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Mpdf');

//Salvataggio del pfd
$pdf_path = '/pdf_finali/' . $name . '.pdf';
echo '<br>';
echo $pdf_path;
$writer->save($pdf_path);
		
```

### Which versions of PhpSpreadsheet and PHP are affected?

7.0

**Comment by PowerKiKi** [comment]
`$name` does not exist and `$pdf_path` is an absolute path that probably does not exist.

**Comment by sirlucast** [comment]
asdasdasasdad
