### ISSUE TITLE
XLS Writer truncates the last character from strings used inside formulas

### ISSUE THREAD

**Issue by UBEX** [PHPOffice/PhpSpreadsheet#401]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The cell A1 should contain the following formula: =IF(B1="HELLO";0;C1+D1)

### What is the current behavior?
The cell A1 contains instead the following formula: =IF(B1="HELL";0;C1+D1)
(notice the missing "O" character...)
Note: this issue does NOT affect the Xlsx Writer.

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$xls = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$xls->getActiveSheet()->SetCellValueExplicit('A1', '=IF(B1="HELLO",0,C1+D1)', PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_FORMULA);
$objWriter = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($xls, "Xls");
$objWriter->save("C:/temp/test.xls");
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHPSpreadsheet = Version 1.1.0
PHP Version 7.0.26

**Comment by PowerKiKi** [comment]
Fixed in https://github.com/PHPOffice/PhpSpreadsheet/commit/38b90715e2783da7206d37befd962b2c68279d7f.
