### ISSUE TITLE
PhpSpreadsheet can't retrieve images placed inside cell

### ISSUE THREAD

**Issue by AntonioA-D-C** [PHPOffice/PhpSpreadsheet#4014]
```
  
    $spreadsheet=  IOFactory::load($this->file);
    $i= 0;
    dd($spreadsheet->getActiveSheet($row)->getDrawingCollection());
    foreach ($spreadsheet->getActiveSheet()->getDrawingCollection() as $drawing) {
      if ($drawing instanceof MemoryDrawing) {
          ob_start();
          call_user_func(
              $drawing->getRenderingFunction(),
              $drawing->getImageResource()
          );
          $imageContents = ob_get_contents();
          ob_end_clean();
          switch ($drawing->getMimeType()) {
              case MemoryDrawing::MIMETYPE_PNG :
                  $extension = 'png';
                  break;
              case MemoryDrawing::MIMETYPE_GIF:
                  $extension = 'gif';
                  break;
              case MemoryDrawing::MIMETYPE_JPEG :
                  $extension = 'jpg';
                  break;
          }
      } else {
          $zipReader = fopen($drawing->getPath(), 'r');
          $imageContents = '';
          while (!feof($zipReader)) {
              $imageContents .= fread($zipReader, 1024);
          }
          fclose($zipReader);
          $extension = $drawing->getExtension();
      }
    
      $myFileName = time() .++$i. '.' . $extension;
      dd($myFileName);
    }
```

Here my script won't trigger when I have images that are inside cells, it ignores images inside the cells for images outside the cells, how to fix this or how to retrieve images contained within cells

**Comment by oleibman** [comment]
Confirming what you've already surmised. PhpSpreadsheet has no way to set a cell value to an image. As for retrieving such an image, I've looked at a spreadsheet which does this, and I really don't see how this is handled in the xml. Even if I do figure it out, it would probably be a pretty major change to extend the set of datatypes to which a cell value can be set.

**Comment by oleibman** [comment]
Closing as duplicate of #4034.

**Comment by vidya-balakrishnan** [comment]
> spreadsheet

Which spreadsheet library supports embedding an image directly into a cell as its value?

**Comment by raziel057** [comment]
@oleibman I had a look on how it works and I can see the following. Considering I added 3 images. I inserted a specific image in cell H3 and the same image in cell K3 and L3, in the XML I have:

<img width="1110" height="102" alt="Image" src="https://github.com/user-attachments/assets/a4d67931-fca0-414d-9306-27e6eafa5353" />

and in xl/media path I can see 2 images:

<img width="573" height="216" alt="Image" src="https://github.com/user-attachments/assets/d5073b52-4a53-498c-ad68-ff767978a3bb" />

So as you can see when a cell contains an image, a ``vm`` property is added with num of image.

**Comment by oleibman** [comment]
@raziel057 Thank you. There is, unfortunately, a lot more that needs to be done aside from adding the vm attribute, especially including changes to the vml file.

**Comment by raziel057** [comment]
@oleibman I just created a small PR that allow to take those images into account. I could test it in real life based on an import component used by our web applications.
