### ISSUE TITLE
Feature request: functionality to detect and read sheet tables and related styles

### ISSUE THREAD

**Issue by bokrma** [PHPOffice/PhpSpreadsheet#4020]
in order to fully use the repo. there should be away to detect and read the sheet tables and styles, specially when importing the files, because currently all sheets with tables are broken because of no table functionality exists

**Comment by oleibman** [comment]
Much table functionality has been added. If you find that it isn't working properly, please open a new issue so that we can take a look at it.

**Comment by bokrma** [comment]
the issue is that when I import an Excel file that has table from Google or excel sheet, it doesn't identify those tables and cant detect them
please let me know how to detect them, and handle them on the importing functionality

**Comment by bokrma** [comment]
$this->worksheet->getTableNames(), and $this->worksheet->getTableCollection() not getting anything from this example sheet
and I cant identify the tables inside the sheet in any way
[invoice (2).xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/15334945/invoice.2.xlsx)

**Comment by oleibman** [comment]
Thank you for the spreadsheet. I am unable to duplicate your problem.
```php
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load('issue.4020.xlsx');
$worksheet = $spreadsheet->getActiveSheet();
var_dump($worksheet->getTableNames());
```
Output:
```
C:\git\issue.4020.php:12:
array(1) {
  [0] =>
  string(7) "Table_1"
}
```
What release of PhpSpreadsheet, and what release of Php, are you using? What else can you tell me about your environment?

**Comment by bokrma** [comment]
oh i think there was problem with the version, thanks now I can get the names of the tables
