### ISSUE TITLE
HTML export ignores setSize / getColor cell formats

### ISSUE THREAD

**Issue by turucz** [PHPOffice/PhpSpreadsheet#4021]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Have the same font-size / font-color in generated HTML file as in the XLSX files what generated by phpspreadsheet 

### What is the current behavior?
Ignore the specified font-color, instead use black color

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// create the sheet
    
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setShowGridLines(false);
        $sheet->getPageSetup()->setPaperSize(PageSetup::PAPERSIZE_A4);

        $spreadsheet->getDefaultStyle()->getFont()->setName('Arial');
        $spreadsheet->getDefaultStyle()->getFont()->setSize(10);
        $line = 1;
        $position = 'A' . $line;
        $sheet->setCellValue(
            $position,
            'Invoice attachment for client: Expample GmbH'
        );
        $sheet->getStyle($position)->getFont()->setBold(true)->setSize(18);
        $sheet->getStyle($position)->getFont()->getColor()->setARGB('e52424');

            $htmlWriter = new HtmlWriter($spreadsheet);
            ob_start();
            $htmlWriter->save('php://output');
            $htmlContent = ob_get_clean();



```

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
I've tested on HTML generating only.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: 2.0
PHP: 8.2.12
Laravel: 10.48.8

Thank you in advance.

Best regards,
Sandor

**Comment by oleibman** [comment]
Seems okay when I try it. Are you seeing something different?
<img width="101" alt="issue4021a" src="https://github.com/PHPOffice/PhpSpreadsheet/assets/10341515/de7db15b-ee86-4f2f-964f-da54d189d0d1">

<img width="183" alt="issue4021b" src="https://github.com/PHPOffice/PhpSpreadsheet/assets/10341515/5d7d0149-d3c7-406c-b743-a8da753efd45">

**Comment by turucz** [comment]
Thank you for your quick response.

I've attached what I see:
[excel.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/15252503/excel.xlsx)
![excel_picture](https://github.com/PHPOffice/PhpSpreadsheet/assets/57491453/9a11bbb7-0f16-44a2-96a9-146237ed592c)
[html.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/15252511/html.zip)
![html_picture](https://github.com/PHPOffice/PhpSpreadsheet/assets/57491453/b94fae8c-9514-4e1d-8b42-bf4bb47842aa)

**Comment by oleibman** [comment]
Your issue title, and your sample code, says that there is a problem with Html export. But your diagram is of an Excel spreadsheet. Furthermore, cell A1 (which seems to be merged with B1 through E1) seems to be red, bold, Arial, and 18-point, all of which agree with what you've set in your code. Is there some other cell which doesn't look right to you? If so, please provide your code for filling that cell in.

**Comment by turucz** [comment]
What you mentioned with merge made me try to reverse the order of merging and text formating, when I firstly merge and after give style solve the issue. So not just works fine the formating in Excel spreadsheet now, but in HTML, furthermore in PDF too.
Thank you for your support.
Best regards,
Sandor

**Comment by oleibman** [comment]
User seems satisfied, closing.
