### ISSUE TITLE
The way to Protect only a particular cell is not working. How do i lock a particular row or column 

### ISSUE THREAD

**Issue by prakhar217** [PHPOffice/PhpSpreadsheet#4032]
This is:

```
- [>] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
There should be a function which can lock a particular cell in a sheet

### What is the current behavior?
//This is my code --> 
1. where I am trying to first lock the whole sheet 
2.Unlocking and only  locking the needed cell
3. But all it does lock whole sheet thats it
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
       $spreadsheet->getActiveSheet()->getProtection()->setSheet(true);
                        $spreadsheet->getDefaultStyle()->getProtection()->setLocked(false);
                        $spreadsheet->getActiveSheet()->getStyle('A1')->getProtection()->setLocked(
                        \PhpOffice\PhpSpreadsheet\Style\Protection::PROTECTION_PROTECTED
                        );

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
//This is my code --> 1. where I am trying to first lock the whole sheet 
2.Unlocking and only  locking the needed cell
3. But all it does lock whole sheet thats it
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
       $spreadsheet->getActiveSheet()->getProtection()->setSheet(true);
                        $spreadsheet->getDefaultStyle()->getProtection()->setLocked(false);
                        $spreadsheet->getActiveSheet()->getStyle('A1')->getProtection()->setLocked(
                        \PhpOffice\PhpSpreadsheet\Style\Protection::PROTECTION_PROTECTED
                        );
// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
almost the lastest

**Comment by oleibman** [comment]
Unable to duplicate, or I don't understand the problem you're reporting. I run your code, and save the spreadsheet. When I open it in Excel, I can change the value of every cell on the sheet except for A1. When I try to change A1, I get a message that the sheet needs to be unprotected first. Is that not what you intended? Do you see something different? If so, please let me know PhpSpreadsheet version, Php version, and your environment (e.g. Windows command line). You might also want to upload the file which is not working correctly.

**Comment by PaulCombal** [comment]
I ran into the exact same issue, I almost pulled my hair out.

I'm on Linux so I use LibreOffice. LibreOffice just freezes the whole sheet, but Excel Online has the desired behavior. I would think this is a LibreOffice bug.

**Comment by oleibman** [comment]
Closing. No update from person opening issue in 4 months. Per another user, this is a LibreOffice issue, which seems reasonable to me.

**Comment by siczmj** [comment]
I ran into this, and could be a useful message for the ones who find this post. 

I think what happens is later in code when you invoke `...->getStyle()` or `...->getStyleByColumnAndRow()`, the cell is not going to have default style anymore, therefore `setLocked(false)` on default style has no effect on those cells.
