### ISSUE TITLE
Cannot open XLSX file

### ISSUE THREAD

**Issue by don-odyssey** [PHPOffice/PhpSpreadsheet#4046]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
File opens for processing

### What is the current behavior?
File fails to open
Error: atal error: Uncaught PhpOffice\PhpSpreadsheet\Reader\Exception: Unable to identify a reader for this file in /home/httpd/www/odyssey-new/web/php/phplib/ext/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/IOFactory.php:172 
### What are the steps to reproduce?
$icargoInputFile = target file
$inputFileType = IOFactory::identify($icargoInputFile);
The above lines causes error

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
I only use XLSX format

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.4. 
I don't know how to find the version of PhpSpreadsheet

**Comment by oleibman** [comment]
If the file is encrypted (probably because it's password-protected), we can't open it. If that's not the explanation, I'd need you to upload it to determine the source of the problem.

**Comment by oleibman** [comment]
Closing. No sample file, no reply in over 4 months.
