### ISSUE TITLE
invalid range  when save xlsx file php

### ISSUE THREAD

**Issue by huyprowow** [PHPOffice/PhpSpreadsheet#4058]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the current behavior?
error Invalid range: "Z51:A51" when save xlsx file
PHP Fatal error:  Uncaught PhpOffice\\PhpSpreadsheet\\Exception: Invalid range: "Z51:A51" in /var/www/html/vision/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php:675\nStack trace:\n#0 /var/www/html/vision/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php(545): PhpOffice\\PhpSpreadsheet\\Cell\\Coordinate::validateRange()\n#1 /var/www/html/vision/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php(454): PhpOffice\\PhpSpreadsheet\\Cell\\Coordinate::getReferencesForCellBlock()\n#2 /var/www/html/vision/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(700): PhpOffice\\PhpSpreadsheet\\Cell\\Coordinate::extractAllCellReferencesInRange()\n#3 /var/www/html/vision/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(461): PhpOffice\\PhpSpreadsheet\\Worksheet\\Worksheet->calculateColumnWidths()\n#4 /var/www/html/vision/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(85): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx\\Worksheet->writeCols()\n#5 /var/www/html/vision/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(340): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx\\Worksheet->writeWorksheet()\n#6 /var/www/html/vision/output/allocation_table_output.php(398): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx->save()\n#7 {main}\n  thrown in /var/www/html/vision/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php on line 675...

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$sheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$sheet->getPageSetup()->setPrintArea('A1:D54');
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($book, "Xlsx");

$writer->save("file/".$filename);
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [x] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
php 8.1.28

**Comment by oleibman** [comment]
Unable to duplicate. Your sample code is incorrect - `$sheet` is a Workbook, but `pageSetup` is a property of a Worksheet. Even so, correcting the code to account for this creates a valid spreadsheet with no errors. Here's the code I used.
```php
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

for ($row = 1; $row <= 60; ++$row) {
    for ($col = 'A'; $col <= 'G'; ++$col) {
        $sheet->setCellValue("$col$row", "$col$row");
    }
}

$sheet->getPageSetup()->setPrintArea('A1:D54');
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xlsx');

$oufil = 'issue.4058.xlsx';
$writer->save($oufil);
```

**Comment by huyprowow** [comment]
i'm using stringFromColumnIndex and passing 0 then range has error, sory my bad
