### ISSUE TITLE
Calculation.php

### ISSUE THREAD

**Issue by renelmedina** [PHPOffice/PhpSpreadsheet#410]
tengo este error en todos los archivos que reazlio

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in /public_html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php on line 209

**Comment by PowerKiKi** [comment]
PhpSpreadsheet is not compatible with older PHP 5.6
