### ISSUE TITLE
Incorrect Attribute Value for forceFullCalc in writeCalcPr Method

### ISSUE THREAD

**Issue by heikyomuraichi** [PHPOffice/PhpSpreadsheet#4108]
https://github.com/PHPOffice/PhpSpreadsheet/blob/fcf03b95bf8ae12c05680141f3e0c3833f6e985c/src/PhpSpreadsheet/Writer/Xlsx/Workbook.php#L163

Issue Summary
The writeCalcPr method in the class contains an incorrect attribute value for forceFullCalc. The current implementation sets forceFullCalc to 0 when $recalcRequired is true, and to 1 when $recalcRequired is false. This seems to be the opposite of the intended behavior.

Suggested Fix
The attribute forceFullCalc should be set to 1 when $recalcRequired is true, and to 0 when $recalcRequired is false. This would correctly reflect the need for a full recalculation when recalcRequired is true.

```
$objWriter->writeAttribute('forceFullCalc', ($recalcRequired) ? '1' : '0'); 
```

**Comment by oleibman** [comment]
I believe PhpSpreadsheet is producing the desired result, but the parameter is, unfortunately, misnamed. When preCalculateFormulas (and therefore recalcRequired) is false, I see the following in the output:
```xml
<calcPr calcId="999999" calcMode="auto" calcCompleted="0" fullCalcOnLoad="1" forceFullCalc="1"/>
```
When it's true, I see the following:
```xml
<calcPr calcId="999999" calcMode="auto" calcCompleted="1" fullCalcOnLoad="0" forceFullCalc="0"/>
```
I think that both are as they should be. Do you have an example where you feel otherwise?

**Comment by heikyomuraichi** [comment]
Thank you for the clarification. I understand now that the actual behavior of the writeCalcPr method is correct and that the naming of the parameter might be a bit misleading. I don't have an example where the current implementation produces incorrect results. It was a misunderstanding on my part.

Thank you for your assistance and explanation.
