### ISSUE TITLE
Applying styles to multiple ranges with applyFromArray() throws Exception

### ISSUE THREAD

**Issue by GreeKatrina** [PHPOffice/PhpSpreadsheet#411]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
To be able to apply an array of styles to multiple ranges, like `A2:A4,K12:G20`. Since you are capable of selecting multiple ranges of cells with `getStyle()` from a worksheet, I think it makes sense that you should also be allowed to apply styles to multiple ranges.

### What is the current 
Throws the exception `Cell coordinate string can not be a range of cells` in `coordinateFromString()` from Cell.php.

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$styleArray = [  'font' => [ 'bold' => true ] ];
$spreadsheet->getActiveSheet()->getStyle('A2:A4,K12:G20')->applyFromArray($styleArray);
```

### Which versions of PhpSpreadsheet and PHP are affected?
I am using the develop branch.

**Comment by oleibman** [comment]
Reopening.
