### ISSUE TITLE
Bug in "Trunc" class

### ISSUE THREAD

**Issue by Alan-FSantana** [PHPOffice/PhpSpreadsheet#4113]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

PhpOffice\PhpSpreadsheet\Calculation\MathTrig\Trunc::evaluate(1.01, 1);  // expected: 1.0

### What is the current behavior?

PhpOffice\PhpSpreadsheet\Calculation\MathTrig\Trunc::evaluate(1.01, 1);  // current: 1.01

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

echo PhpOffice\PhpSpreadsheet\Calculation\MathTrig\Trunc::evaluate(1.01, 1);

```
### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [X] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?

Formats that use formulas.

### Which versions of PhpSpreadsheet and PHP are affected?

All?

**Comment by oleibman** [comment]
Confirmed. This appears to have been a bug for a long time. Researching.

**Comment by oleibman** [comment]
The following code in TRUNC is causing this problem:
```php
        if (($digits > 0) && (rtrim((string) (int) ((abs($value) - abs((int) $value)) * $adjust), '0') < $adjust / 10)) {
            return $value;
        }
```
If I remove it, all of our unit tests continue to succeed, and this case now returns the expected result. I do not understand the purpose of this code, which dates back to PHPExcel, and, if possible, I would like a better understanding before I remove it. @MarkBaker  @PowerKiKi any ideas on what it is supposed to do?

**Comment by Alan-FSantana** [comment]
Without those lines, it fails with the case: `$value = 10.04, $digits =  2 `
Maybe something like this should work:

```php
    $str = json_encode($value);
    if (($p = strpos($str, '.')) !== false) {
        $value = (float) (substr($str, 0, $p + 1 + $digits));
    }

    return $value;
```
[https://stackoverflow.com/questions/4668628/truncate-float-numbers-with-php](url)

**Comment by oleibman** [comment]
Thank you for the link and the additional example.

**Comment by oleibman** [comment]
It's hard to imagine that we need Json to solve this problem. I like the solution from [Juan](https://stackoverflow.com/users/1919269/juan). I think it clearly needs more testing, but it works for both test cases you've submitted and all our existing tests.
```php
        if ($value == 0) {
            return $value;
        }
        if ($value >= 0) {
            $originalNegative = false;
        } else {
            $originalNegative = true;
            $value = -$value;
        }
        $result = round($value - 5 * pow(10, -($digits + 1)), $digits);

        return $originalNegative ? -$result : $result;
```

**Comment by oleibman** [comment]
Sigh, that code breaks down in Php 8.4.

**Comment by oleibman** [comment]
The suggestion from [savageman](https://stackoverflow.com/users/211204/savageman) needs work (doesn't work for negative precision, and needs to use both sprintf and round). But it does seem to work in Php8.4, as well, of course, as 8.1-8.3.

**Comment by Alan-FSantana** [comment]
Hi, thanks for your work on this issue!
I did some tests using Php 3.9 and didn't find any failure with the Juan's solution, but some cases failed with the new function in Trunc class: 

```php
$value = -43747.99122596; $digits = 0; // float(-43748)
$value = -9.1196419; $digits = 2; // float(-9.12)
$value = -42300.65099338; $digits = 3; // float(-42300.651)
```

Obs: an alternative for `json_enconde` is `var_export($value, true)`.

**Comment by oleibman** [comment]
Thanks for keeping me honest :-) Please try again with the latest push.

**Comment by Alan-FSantana** [comment]
You're welcome!  =)

There is a problem with numbers that are represented in the exponential form after converting to string. 
Example: `$value = 0.0000123; // (string) = '1.23e-5'`

Also, prior to PHP 8.0, float to string conversions depended on the current locale set with the setlocale function (except for the functions `var_export`, `json_encode` and `serialize`).

https://php.watch/versions/8.0/float-to-string-locale-independent

**Comment by Alan-FSantana** [comment]
Excellent! No problems found this time ;)

**Comment by oleibman** [comment]
Changes to use non-locale-aware formats for sprintf are now pushed.
