### ISSUE TITLE
ChunkReadFilter does not skip rows

### ISSUE THREAD

**Issue by dorin-niscu** [PHPOffice/PhpSpreadsheet#412]
I am trying to split a large document into small chunks. (Something similar with LIMIT / OFFSET on SQL).

ChunkReadFilter does not skip the rows, it returns the rows with nulled cells and I need to apply rangeToArray() after that to select what I need.

Is it possible to only select a range of rows in one step to achieve something similar to SQL query?

_SELECT *FROM table LIMIT 10 OFFSET 10_

**Comment by zarte** [comment]
the func is this
// Read cell?
                if ($this->getReadFilter() !== null) {
                    if (!$this->getReadFilter()->readCell($column, $row, $worksheetName)) {
                        continue;
                    }
                }
i think it's useless。it‘s still load whole file in begin.

**Comment by oleibman** [comment]
Behavior is explained above, leaving issue closed, removing stale label.
