### ISSUE TITLE
Certain currency formats are handled incorrectly by formatter

### ISSUE THREAD

**Issue by Geries** [PHPOffice/PhpSpreadsheet#4124]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?
``1 HUF``

### What is the current behavior?
``#,##0 [$0000000f]``, which in turn causes auto column width to be unnecessarily wide.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// add code that show the issue here...
// Currency formats that have ISO codes and no digits will have issue.
echo \PhpOffice\PhpSpreadsheet\Style\NumberFormat\Formatter::toFormattedString(1, '#,##0_-[$HUF]');
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [x] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

#### The source of the issue is the following condition, designating the format to be a date format:

https://github.com/PHPOffice/PhpSpreadsheet/blob/1c77e0049902b245c92c233aadcc834f50d246af/src/PhpSpreadsheet/Style/NumberFormat/Formatter.php#L162

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
.xlsx, most likely others too.

### Which versions of PhpSpreadsheet and PHP are affected?
PHP: 8.2
PhpSpreadsheet: at least up from 2.1.0

**Comment by oleibman** [comment]
Confirmed. I will add  to my to-do list. It wouldn't surprise me if any solution to this brings up another problem elsewhere.
