### ISSUE TITLE
Error open file Xlsx when modify value

### ISSUE THREAD

**Issue by Fabacks** [PHPOffice/PhpSpreadsheet#4128]
Good morning, 

Since switching to version >= 2.2, the "setCellValue" method causes an error when opening Excel. 
The error is : "We found a problem in the content of XXX, but we can try to recover as much content as possible.". 
It only produces this with the "Xlsx" format. I tried to reproduce the error with minimal code. But, if you open the file and save without modifying a single line, the file opens correctly.

The function "error_reporting(E_ALL)" gives no error.

Thank you so much

This is:

```
- [ X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?
Execute the code

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$spreadsheet->getActiveSheet()->setCellValue('D1', 'MyDate');

$path = __DIR__.'/file_example.xlsx';
$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save($path);
?>

// add code that show the issue here...
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.
[file_example.xlsx](https://github.com/user-attachments/files/16507655/file_example.xlsx)
![error excel open](https://github.com/user-attachments/assets/8644e9f9-5354-463b-9d37-d18a7810dc00)

### What features do you think are causing the issue
- [ ] Reader
- [ X] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Which versions of PhpSpreadsheet and PHP are affected?
Phpspreasheet >=2.2
PHP >= 8.1
Excel 2016
Environment Windows
Langue French

**Comment by oleibman** [comment]
Agree that the file you uploaded is messed up. However, using your code, I am unable to see a problem with 2.2.0, 2.2.1, or master - the workbook opens just fine and is as expected (empty except for cell D1 which has its expected value). I am using Excel 365 rather than 2016, but I doubt that's the problem; similarly English rather than French, and even more doubtful of that as the problem.

**Comment by zapato** [comment]
I have the same **issue with Excel 2016** but I also **cannot** reproduce it with **Excel Home and Studen 2021**.
Seens to be a specific Problem when opening with PhpSpreadsheet generated files with Excel 2021.
Generating the XLSX-files with PhpSpreadsheet 2.1.* works fine. 
The opening error is onl shown for files generated with PhpSpreadsheet >=2.2.0 with Excel 2016.

**Comment by oleibman** [comment]
@zapato The contents of the file generated by PhpSpreadsheet don't change depending on the Excel release. @Fabacks  uploaded a file which clearly had problems, in Excel 2016 and any other release. Do you have a file which opens okay in Excel 2021 but not 2016?

**Comment by zapato** [comment]
@oleibman Opning the uploaded example files with my **Excel 2021** shows the following error message and I am not able to open the file.

![grafik](https://github.com/user-attachments/assets/b4691080-19b7-4210-9deb-6c4e87742844)

A self created XLSX file with the example code dos not show any problem when opening with Excel 2021.

At work I am using Excel 2016 and getting the error message like "We found a problem in the content of XXX, but we can try to recover as much content as possible." with my generated xlsx files. I will try to prepare some more example code to reproduce the problem.

**Comment by oleibman** [comment]
I already noted that the uploaded file is not suitable for any version of Excel. But, since my attempt to reproduce the problem with the supplied code generated a file which appears to usable with any version of Excel (I don't have 2016 but I have access to earlier and later versions), I don't know how to proceed for the moment. Your description of your problem (usable in Excel 2021 but not in 2016) seems to be a different case; I will look forward to your example code.

**Comment by oleibman** [comment]
Rather oddly, LibreOffice Calc is able to open the uploaded file even though Excel can't. I'm not sure how, and that, of course, does not solve the mystery of how the file was created in that particular manner.

**Comment by oleibman** [comment]
And now the mystery seems explainable. If I change the file extension from `xlsx` to `xls`, Excel can open it. In fact, like LibreOffice, PhpSpreadsheet can read this file:
```php
$filename = 'issue.4128.orig.xlsx';
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($filename);
var_dump($reader::class);
$spreadsheet = $reader->load($filename);
var_dump($spreadsheet->getActiveSheet()->getCell('D1')->getValue());
```
Result:
```
C:\git\issue.4128b.php:9:
string(35) "PhpOffice\PhpSpreadsheet\Reader\Xls"
C:\git\issue.4128b.php:11:
string(6) "MyDate"
```
 @Fabacks is it possible that you used the `Xls` writer to save the file with an `xlsx` extension?

**Comment by zapato** [comment]
I used the following example code and generated the following Excel files **(PHP 8.3.10 Windows**) 
    <?php
    require __DIR__ . '/../vendor/autoload.php';
    
    $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
    $spreadsheet->getActiveSheet()->setCellValue('D1', 'MyDate');
    
    $path = __DIR__.'/file_example.xlsx';
    $writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xlsx');
    $writer->save($path);

Using PhpSpreadsheet **2.1.0** - **No errors** when opening the file with Excel 2016:
[file_example_v2.1.0.xlsx](https://github.com/user-attachments/files/16521606/file_example_v2.1.0.xlsx)

Using PhpSpreadsheet **2.2.1** - **Errors** when opening the file with Excel 2016:
[file_example_v2.2.1.xlsx](https://github.com/user-attachments/files/16521619/file_example_v2.2.1.xlsx)

Error-Messages:
![excel_error_message](https://github.com/user-attachments/assets/f4d5be7a-3761-4e4a-9b26-bec5667b6ef5)

![repair_message](https://github.com/user-attachments/assets/a51dc19a-0638-48b6-b665-aad62f3fdcf6)

**Comment by oleibman** [comment]
Thank you for the sample files. There is a minor difference between the 2 files. While I research, can you add:
```php
$spreadsheet->getActiveSheet()->setSelectedCells('D1');
```
Is the resulting workbook now usable in Excel 2016?

**Comment by zapato** [comment]
Setting the selected cell seems to solve to problem.

    $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
    $spreadsheet->getActiveSheet()->setCellValue('D1', 'MyDate');
    $spreadsheet->getActiveSheet()->setSelectedCells('D1');

No matter if the selected cell is another cell. `$spreadsheet->getActiveSheet()->setSelectedCells('A1');` is also usable.

**Comment by oleibman** [comment]
@zapato If possible, please try your code (without setSelectedCells) against PR #4132.

**Comment by zapato** [comment]
@oleibman Yes, testing PR #4132 with Excel 2016 was successful. **No need anymore** to explicitly set `? $spreadsheet->getActiveSheet()->setSelectedCells('A1');`. 

Info for testing: It is important to always use an new xlsx filname because Excel memorizes the last selected cell from previous opening for the same filename. So you would not get the error message again when opening a (new generated) file with the same filename in which you explicitly had set the selected cell.

Many thanks for your support!

**Comment by Fabacks** [comment]
Hello,

Version 2.2.2 fixes the problem.
Thank you very much
