### ISSUE TITLE
PlotArea: Datatable

### ISSUE THREAD

**Issue by topaDev** [PHPOffice/PhpSpreadsheet#413]
### This is:

```
- [ ] a bug report
- [X] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Allow option to insert "Data Table" which adds a table of values to a chart instead of Legend (User Interface in screenshot is German obviously, but I suppose this feature is called "Data Table" in English)
![datatable](https://user-images.githubusercontent.com/37305076/37296655-ea516ca4-261b-11e8-97c0-226ce59386a0.png)

### What is the current behavior?
Feature is not implemented

### Analysis

After looking into chart-XML, I noticed the following lines have to be added:

```xml
<c:dTable>
    <c:showHorzBorder val="1"/>
    <c:showVertBorder val="1"/>
    <c:showOutline val="1"/>
    <c:showKeys val="1"/>
</c:dTable>
```

### Solution / Workaround
I've created the attached changes, please have a look at the patch-files.

**Usage:**
```php
$plotArea = new PlotArea(null, [$series]);
$plotArea->setDataTable(true);
```

### Disclaimer
Even this patch works perfectly for my project, I have no idea whether the way the option has been implemented is OK, but maybe it is useful for someone.

[Writer_Xlsx_Chart.patch.txt](https://github.com/PHPOffice/PhpSpreadsheet/files/1803714/Writer_Xlsx_Chart.patch.txt)
[Chart_PlotArea.patch.txt](https://github.com/PHPOffice/PhpSpreadsheet/files/1803715/Chart_PlotArea.patch.txt)

**Comment by oleibman** [comment]
Reopening.
