### ISSUE TITLE
 iconv(): Wrong encoding, conversion from "CP936" to "UTF-8" is not allowed

### ISSUE THREAD

**Issue by huelsgp27** [PHPOffice/PhpSpreadsheet#4133]
This is:

```
- [☑️] a bug report
```

### What is the expected behavior?
load a xls file.

### What is the current behavior?
[ERROR] iconv(): Wrong encoding, conversion from "CP936" to "UTF-8" is not allowed[401] in /opt/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/StringHelper.php
[ERROR] #0 [internal function]: Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler::Hyperf\ExceptionHandler\Listener\{closure}()
#1 /opt/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/StringHelper.php(401): iconv()
#2 /opt/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php(1356): PhpOffice\PhpSpreadsheet\Shared\StringHelper::convertEncoding()
#3 /opt/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xls.php(587): PhpOffice\PhpSpreadsheet\Reader\Xls->readSummaryInformation()
#4 /opt/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/BaseReader.php(194): PhpOffice\PhpSpreadsheet\Reader\Xls->loadSpreadsheetFromFile()

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$url = 'https://hk-1252104623.cos.ap-hongkong.myqcloud.com/%E5%B9%B4%E5%BA%A6%E8%B4%A2%E5%8A%A1%E6%8A%A5%E5%91%8A.xls';
file_put_contents("/tmp/test.xls", file_get_contents($url));
$spreadsheet = IOFactory::load('/tmp/test.xls');
```
If this is an issue with reading a specific spreadsheet file, then it may be appropriate to provide a sample file that demonstrates the problem; but please keep it as small as possible, and sanitize any confidential information before uploading.

### What features do you think are causing the issue

- [☑️] Reader
- [ ] Writer
- [ ] Styles
- [ ] Data Validations
- [ ] Formula Calculations
- [ ] Charts
- [ ] AutoFilter
- [ ] Form Elements

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
No, only .xls file.

### Which versions of PhpSpreadsheet and PHP are affected?
2.2.1

**Comment by oleibman** [comment]
Unable to duplicate. Using your sample code, I succeed and, after loading, I can save to a new (and it appears correct) spreadsheet on my system. Is it possible that iconv does not support CP936 (or, less likely, UTF8) on your system?

**Comment by huelsgp27** [comment]
> Unable to duplicate. Using your sample code, I succeed and, after loading, I can save to a new (and it appears correct) spreadsheet on my system. Is it possible that iconv does not support CP936 (or, less likely, UTF8) on your system?

Thank you for your reply. After upgrading the libiconv version, it is working now.

**Comment by jcleng** [comment]
```json
  "autoload": {
    "files": [
      "./libraries/overw/StringHelper.php"
    ]
  },
```
```shell
composer dump-autoload
```
 temporary processing: CP936=>GBK
```php
...
    public static function convertEncoding(string $textValue, string $to, string $from): string
    {
        if (self::getIsIconvEnabled()) {
            if ($from == 'CP936') {
                $from = 'GBK';
            }
            $result = iconv($from, $to . self::$iconvOptions, $textValue);
            if (false !== $result) {
                return $result;
            }
        }

        return self::returnString(mb_convert_encoding($textValue, $to, $from));
    }
...
```
