### ISSUE TITLE
Issue from Composer - XXE in PHPSpreadsheet encoding is returned

### ISSUE THREAD

**Issue by gensart-x** [PHPOffice/PhpSpreadsheet#4172]
I'm just informing this, while i do installing phpoffice/phpspreadsheet via Composer:

![image](https://github.com/user-attachments/assets/8dc9ad1c-9a37-4f09-ab1e-02d5f82a41ca)

Also, please refer me out to the solution if the issue is already solved, thankyou.

**Comment by oleibman** [comment]
What release of Php are you using? What release of PhpSpreadsheet are you requiring in your Composer command or composer.json?

**Comment by gensart-x** [comment]
Hi, thanks for the reply.

I use PHP 8.1.27 nts and the phpspreadsheet is 2.1.

If there's anything you need, please let me know.

**Comment by gensart-x** [comment]
I'm sorry, I think I haven't updated to the latest version of the library, the problem was fixed on the #4119 PR. I am updating now, thank you.
