### ISSUE TITLE
Is the latest release supposed to be 3.3.0 or 3.0.0?

### ISSUE THREAD

**Issue by mfn** [PHPOffice/PhpSpreadsheet#4176]
This is:

- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
- [x] a question

See https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/3.3.0

But https://github.com/PHPOffice/PhpSpreadsheet/blob/master/CHANGELOG.md#2024-09-29---300
> 2024-09-29 - 3.0.0

I guess a typo when creating the release? (hard to change probably, as its also on https://packagist.org/packages/phpoffice/phpspreadsheet#3.3.0

**Comment by oleibman** [comment]
You are exactly correct, a typo when creating the release. Since it is completely harmless, I have not looked into changing it, an activity which I also assessed as "hard". I will, however, update changelog so that it is consistent with the release id. That will probably happen in a day or two.
