### ISSUE TITLE
1.29.3 containing 3.5 fixes

### ISSUE THREAD

**Issue by patrickbrouwers** [PHPOffice/PhpSpreadsheet#4227]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

It seems the 1.29.3 got put on the wrong commit and is now containing 3.5.0 fixes too.

I've got this reported in Laravel Excel as broken:
https://github.com/SpartnerNL/Laravel-Excel/pull/4234

@oleibman Can you check if the tag is correct?

### Which versions of PhpSpreadsheet and PHP are affected?

1.29.3

**Comment by oleibman** [comment]
My apologies. I have released 1.29.4, which I think is correct. Please verify.

**Comment by patrickbrouwers** [comment]
Perfect, thank you!
