### ISSUE TITLE
require_once in src/PhpSpreadsheet/Chart/Renderer/JpGraph.php can be removed

### ISSUE THREAD

**Issue by cubiclesoft** [PHPOffice/PhpSpreadsheet#423]
[Decomposer](https://github.com/cubiclesoft/php-decomposer) discovered the following linting issue:

```
Found 'require_once' in 'php-spreadsheet/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Chart/Renderer/JpGraph.php' on line 8.
```

This is the relevant line of code:

```php
require_once __DIR__ . '/Polyfill.php';
```

The "dirty" contents of `Polyfill.php` can be merged into `JpGraph.php` (and `Polyfill.php` subsequently removed from the project) by using the empty namespace and braces for namespace wrapping of the main class:

```php
namespace {
if (!function_exists('imageantialias')) {
    function imageantialias(...$args)
    {
        // Do nothing
    }
}
}

namespace PhpOffice\PhpSpreadsheet\Chart\Renderer {
...
}
```

**Comment by PowerKiKi** [comment]
I'd rather have a dirty require, than mixing namespaces in a single file

**Comment by cubiclesoft** [comment]
The global namespace is always available.  You're not really mixing anything that isn't already there.

Decomposer wraps up the require anyway.
