### ISSUE TITLE
Migrator changed name of PHP variables to something invalid when the variable name contains PHPExcel

### ISSUE THREAD

**Issue by teunw** [PHPOffice/PhpSpreadsheet#425]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The migrator should migrate anyone using PHPExcel to PhpSpreadsheet.

### What is the current behavior?
The migrator changes the name of PHP variables to something unusable

### What are the steps to reproduce?
* Get some PHP code using a variable with PHPExcel in the name, for example: $objPHPExcel.
* Run the migrator
* The converted file will contain something like this:
`$obj\PhpOffice\PhpSpreadsheet\Spreadsheet = ... some other code`

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new object with PHPExcel in the name
$examplePHPExcelSpreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
```
Convert this using the migrator, code will look like
```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new object with PHPExcel in the name
$example$obj\PhpOffice\PhpSpreadsheet\SpreadsheetSpreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
```

Actual diff of converted code:

![](https://static.teunwillems.nl/sharex/phpstorm64_2018-03-16_14-08-47552cc5dc-84d0-42c2-a4d6-38f7ce288eb4.png "Actual diff of converted code")

### Which versions of PhpSpreadsheet and PHP are affected?
Newest version as of writing: 1.2.0

**Comment by PowerKiKi** [comment]
This is correct, and is the reason why you should backup your code before running the migrator. But I can't think of a robust solution that would be fine enough to implement. As it is, it's at least very easy to fix manually, but you're right, it could be better... Would you like to submit a PR for that ?

**Comment by teunw** [comment]
I did backup my code, it wasn't very much, so I was able to fix it quite quickly.
However it seems that this shouldn't be a too hard problem to implement, and it would change the QOL of the migrator.

**Comment by oleibman** [comment]
Migration tool was dropped in favor of Rector in 2020. Rector does not have this problem. Leaving this issue closed, but removing stale label.
