### ISSUE TITLE
Cells inside cell, how?

### ISSUE THREAD

**Issue by idem84** [PHPOffice/PhpSpreadsheet#4259]
Hello,

In excel i can made cells inside cell, can i do this through your class some how?

![test34534](https://github.com/user-attachments/assets/9f520313-3243-4c58-9a65-2d15e7aa0d50)

**Comment by oleibman** [comment]
I do not understand what you mean by "cell inside cell". I can't tell for sure from your diagram, but it looks like several of the vertical columns consist of a single merged cell. If that is the case, yes, PhpSpreadsheet can do that. But, if you have something different in mind, please upload the spreadsheet, and I will take a look.
