### ISSUE TITLE
column width skrink to 8.43 pt

### ISSUE THREAD

**Issue by VivBassman** [PHPOffice/PhpSpreadsheet#4284]
This is:

```
- [ ] a bug report
- [ ] a feature request
```

In my input file, my columns width are set by default to 10.71 pt.

When i generate output file from this file, using PhpSreadsheet all columns width are shrink to 8.43 pt.

In the file PhpOffice\PhpSpreadsheet\Writer\Xls\Worksheet, i've found this annotation : 

```php
 /**
     * Write BIFF record COLINFO to define column widths.
     *
     * Note: The SDK says the record length is 0x0B but Excel writes a 0x0C
     * length record.
     *
     * @param array $col_array This is the only parameter received and is composed of the following:
     *                0 => First formatted column,
     *                1 => Last formatted column,
     *                2 => Col width (8.43 is Excel default),
     *                3 => The optional XF format of the column,
     *                4 => Option flags.
     *                5 => Optional outline level
     */
    private function writeColinfo(array $col_array): void
    {
```
Its seems to be wrong that "Col width (8.43 is Excel default)" for me its 10.71

### What features do you think are causing the issue

- [ ] Reader
- [ ] Writer
- [ ] Styles

### Does an issue affect all spreadsheet file formats? If not, which formats are affected?
yes

### Which versions of PhpSpreadsheet and PHP are affected?
all

**Comment by oleibman** [comment]
On my system, the default remains 8.43 pt. Are you saying that all new spreadsheets on your system default to 10.71, or are you saying that you have a spreadsheet where you have manually set the default to 10.71 and PhpSpreadsheet is not handling it correctly? If the latter, can you upload a spreadsheet which fails in this manner, and tell me how you set the default width?

**Comment by VivBassman** [comment]
Hi,
I am saying that all new spreadsheets on my system default to 10.71.

**Comment by oleibman** [comment]
What is your default font?

**Comment by VivBassman** [comment]
Calibri 11 pt

**Comment by oleibman** [comment]
Is there a reason why your spreadsheets have to be Xls format rather than Xlsx?

**Comment by oleibman** [comment]
There's probably not much we can do if different environments use different default widths. You'll probably have to set the default you want explicitly, and chances are you want to specify a "real" unit like "in" or "cm" (note that Excel adds some padding).
```php
$sheet->getDefaultColumnDimension()->setWidth(2, 'in');
```
Even so, Xls seems to apply the default only to columns which are populated; Xlsx applies it to all columns.

Also of note - on my very old system with Excel 2003, the default column width displays as `8.34 (64 pixels)`. The default column width on a new spreadsheet with Excel 365 displays as `8.09 (96 pixels)`. The absolute value and the number of pixels seem to go in opposite directions. I have no explanation for this inconsistency.

**Comment by VivBassman** [comment]
I
