### ISSUE TITLE
Implicit conversion from float to int (PHP 8.X)

### ISSUE THREAD

**Issue by lubosdz** [PHPOffice/PhpSpreadsheet#4292]
Experiencing PHP error `Implicit conversion from float 71495.1 to int loses precision` on [line 47 in Xlsx/StringTable](https://github.com/PHPOffice/PhpSpreadsheet/blob/b21090027e462f8342e3fa0313c6aad67eabeeac/src/PhpSpreadsheet/Writer/Xlsx/StringTable.php#L47).
 
Floats are not allowed as numeric array keys (PHP 8.x).
Solution - just enclose in quotes on lines 47 and 50:

~~~php
&& !isset($aFlippedStringTable["{$cellValue}"])
...
$aFlippedStringTable["{$cellValue}"] = true;
~~~

**Comment by oleibman** [comment]
Can you upload a spreadsheet which demonstrates this problem?

**Comment by lubosdz** [comment]
@oleibman  There is no spreadsheet. It's PHP code that generates the spreadsheet & crashes during generation. If spreadsheet would generate, then there would be no problem :-) It quite simple code:

~~~php
$worksheet->setCellValueByColumnAndRow($col, $row, $val); // $val = 71495.1
~~~

**Comment by oleibman** [comment]
What release of PhpSpreadsheet are you using? `setCellValueByColumnAndRow` was deprecated long ago, and removed with PhpSpreadsheet 2.0 (we are currently on release 3.7). That, however, is not the cause of your problem. I am using the following code:
```php
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$val = 71495.1;
$sheet->getCell('A1')->setValue($val);
$sheet->getCell('A2')->setValue('some string'); // just to make sure we execute the StringTable code

$writer = new Xlsx($spreadsheet);
$outfile = 'issue.4292.xlsx';
$writer->save($outfile);
echo "saved $outfile\n";
```
I do not get an error when I run this code with any currently supported release, including 3.7, 2.3.5, 2.1.6, and 1.29.7. The output spreadsheet looks exactly as expected for all of them. So, back to my question - what version of PhpSpreadsheet are you running? Also, does my sample code run successfully for you? If it does, can you suggest additional code which will make it fail?

**Comment by lubosdz** [comment]
Oh, I have some ancient version, could not even found branch .. in changelog I see `v0.17.0 (01 oct 2019)`.
Library was committed into repo along with the application because at that time there were some specific issues & could not wait any longer for merging PR after some months ..
Sorry, you are right, library should be updated .. uff, big job is coming up ( :-o)
