### ISSUE TITLE
Get NamedRange Value

### ISSUE THREAD

**Issue by madorin** [PHPOffice/PhpSpreadsheet#43]
Hello,

In Excel I can define a named range for some cell and later get value by range name in formulas. Like "=CAPITAL*QUOTE".
Can we have some similar method in NamedRange class to retrieve value of the range?

Thanks!

**Comment by MarkBaker** [comment]
Named ranges should work in formulae in PHPExcel in exactly the same way as they do in MS Excel

And you can retrieve a named range of cell values to a PHP array using the worksheet's `namedRangeToArray()` method

**Comment by madorin** [comment]
Hi Mark,

After a bit more source inspection, I fount a way to get value I'm interested by:
$Range->getWorksheet()->getCell($Range->getRange())->getCalculatedValue();

Should check yet if Range point to a cell but not to multiple cells, testing for ":" in name.

OK, Question closed.

By the way, why you prefixed also Spreadsheet class also with Php?
I think it's parent, Office is enough, like:
\PhpOffice\Spreadsheet\IOFactory::load(

I'm using PhpSpreadsheet library (not PhpExcel) for a new project.

**Comment by PowerKiKi** [comment]
Closing as requested. 

The namespace names are exactly the organization and project names. And they both include `PHP`. I think it's part of the "branding" nowadays and if it was removed the projects would lose some of their identities. In practice those prefixes should mostly only appear in `use` statements, so it shouldn't be such an inconvenience.
