### ISSUE TITLE
SUMIF Formula Accessing Data on Another Sheet "Invalid cell coordinate"

### ISSUE THREAD

**Issue by Klownicle** [PHPOffice/PhpSpreadsheet#433]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Cell B7 to = 31434

### What is the current behavior?
Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Summary!B7 -> Invalid cell coordinate M

### What are the steps to reproduce?
Preform SUMIF Formula accessing another spreadsheet cell other than current sheet.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$objPHPExcel = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$objWriter = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($objPHPExcel);

$objPHPExcel->getActiveSheet()->setCellValue("M7", "2017");
$objPHPExcel->getActiveSheet()->setCellValue("M8", "2017");
$objPHPExcel->getActiveSheet()->setCellValue("M9", "2017");
$objPHPExcel->getActiveSheet()->setCellValue("I7", "7490");
$objPHPExcel->getActiveSheet()->setCellValue("I8", "14840");
$objPHPExcel->getActiveSheet()->setCellValue("I9", "9104");

$myWorkSheet = new \PhpOffice\PhpSpreadsheet\Worksheet\Worksheet($objPHPExcel,'Summary');
$objPHPExcel->addSheet($myWorkSheet, 0);
$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->setCellValue("A7", "2017");
$objPHPExcel->getActiveSheet()->setCellValue("B7", "=SUMIF(Worksheet!M:M,Summary!A7,Worksheet!I:I)");

$objWriter->save('test.xlsx');
?>
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.1.6
PHPSpreadsheet 1.2.0

**Comment by MarkBaker** [comment]
Note that PHPSpreadsheet's calculation engine doesn't full support row ranges or column ranges, though it does fully support cell ranges.
If you change this formula to 
```
=SUMIF(Worksheet!M7:M9,Summary!A7,Worksheet!I7:I9)
```
then it should work without issue

I will take a look at providing support for row/column ranges, but no guarantees that there will be any quick fixes

**Comment by oleibman** [comment]
Supplied code now works correctly. Removing stale label, leaving issue closed.
