### ISSUE TITLE
Fatal Error in Writer/Html.php

### ISSUE THREAD

**Issue by alpha-and-omega** [PHPOffice/PhpSpreadsheet#434]
This is:

```
- [ ] a bug report
```

I have valid xls document which after opening and saving using HTML writer leads to Fatal Error:
PHP Fatal error:  Uncaught Error: Call to a member function getNumberFormat() on null in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Html.php:1294
Here:
```
                    if ($this->preCalculateFormulas) {
                        $cellData = NumberFormat::toFormattedString(
                            $cell->getCalculatedValue(),
                            $pSheet->getParent()->getCellXfByIndex($cell->getXfIndex())->getNumberFormat()->getFormatCode(),
                            [$this, 'formatColor']
                        );

```
Well, I think this chain code is pretty naive in assuming success :)

### What are the steps to reproduce?
I can give example xls. I have no idea whats so special about it.

### Which versions of PhpSpreadsheet and PHP are affected?
Latest master branch.

**Comment by PowerKiKi** [comment]
Instead of upload your file, try to reproduce the bug by creating the spreadsheet from scratch with PhpSpreadsheet and share the code.

**Comment by oleibman** [comment]
Reopening.
