### ISSUE TITLE
Print area after load/save

### ISSUE THREAD

**Issue by madorin** [PHPOffice/PhpSpreadsheet#436]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Print preview with proper print area, real filled cells.

### What is the current behavior?
Preview with one more empty column on the right.
It seems like Excel sees one ghost column populated on the right of actual filled range.

### What are the steps to reproduce?
Load an Xlsx workbook, fill some cells and save it back.

### Which versions of PhpSpreadsheet and PHP are affected?
Tested with v1.1

**Comment by oleibman** [comment]
Created spreadsheet with print area A1:D10, with some cells filled in inside and outside print area. Then processed it with following code:
```php
        $reader = new XlsxReader();
        $spreadsheet = $reader->load('issue.436.xlsx');
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->getCell('A3')->setValue('added');
        $sheet->getCell('B5')->setValue('added');
        $sheet->getCell('C7')->setValue('added');
        $sheet->getCell('E2')->setValue('addout');
        $sheet->getCell('E4')->setValue('addout');
        $sheet->getCell('E6')->setValue('addout');
        $sheet->getCell('A12')->setValue('addout');
        $outfile = 'issue.436.out.xlsx';
        $writer = new XlsxWriter($spreadsheet);
        $writer->save($outfile);
```
Result was exactly as expected - no "ghost column". So problem no longer exists. Leaving issue closed, but removing stale label.
