### ISSUE TITLE
Can't escape from Worksheet's cloning loop and exhausts memory

### ISSUE THREAD

**Issue by t-iri** [PHPOffice/PhpSpreadsheet#437]
This is:

- [x] a bug report
- [ ] a feature request

File: /PhpSpreadsheet/Worksheet/Worksheet.php
Method: Worksheet->__clone()
Related: #92

### What is the expected behavior?
I hope to succeed in copying Worksheet containing relatively many cells but it fails in whiteout as below.
```php
<?php

//Load
require __DIR__ . '/vendor/autoload.php';

$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx'); 
$workbook = $reader->load('sample.xlsx');

//Prepare copying
$worksheet = $workbook->getActiveSheet(); //contains cells about 2,000 in this sheet
$worksheet->setTitle('Let me copy', false);

//Time to be copied but
$copysheet = $worksheet->copy(); //Infinite loop occurs...

$copysheet->setCellValue('B2', 'Copied?'); //Not reach here
```

### What is the current behavior?
In Worksheet->__clone(), I can see the problem at 'drawingCollection' logic.
```php
                } elseif ($key == 'drawingCollection') {
                    $newCollection = new ArrayObject();
                    foreach ($this->drawingCollection as $id => $item) {
                        if (is_object($item)) {
This Line! =>               $newCollection[$id] = clone $this->drawingCollection[$id];
                        }
                    }
                    $this->drawingCollection = $newCollection;
```
When $item is MemoryDrawing, it also has __clone() and try to clone own value. But in case that value is the Worksheet, it causes nested loop(= back to Worksheet->__clone(), to and fro). I haven't copied the sheet never once...

### What are the steps to reproduce?
f99eb8db 's Message:
>We need to make note of two things:
>
>- The old code was trying to clone an objectArray, and hence was performing a shallow copy of memoryDrawing objects (the __clone magic function was not getting invoked).
>Instead, if one loops over the objectArray, and then clones the individual memory drawing objects, then the __clone function for the MemoryDrawing object is invoked.
>
>- The __clone function for memory drawing was using the clone keyword which does not deal with circular references (Since memoryDrawing object had references to worksheet object, it was encountering an infinite loop). However, serializing and unserializing objects deals with circular references pretty well.

The latter is that but I don't grasp whether it has been solved.
I tried old code(previous of the commit), only declaring clone keyword.
```php
                } elseif ($key == 'drawingCollection') {
                    $newCollection = clone $this->drawingCollection;
                    $this->drawingCollection = $newCollection;
```
It surely goes well, completed copying in my case but this is just a shallow copy? as the message said. So I would appreciate if you have another look at this issue.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: 1.2.0
PHP: 7.0.16

**Comment by wnasich** [comment]
I got this issue when the worksheet to clone content an image

**Comment by PowerKiKi** [comment]
Please consider contributing a PR. The behavior was rather well explained
by OP and it should be possible to unit tests done behavior rather easily.

**Comment by oleibman** [comment]
Fixed by https://github.com/PHPOffice/PhpSpreadsheet/commit/048947e390276b24e42eae39d935384295a6749f in August 2018. Removing stale label, leaving closed.
