### ISSUE TITLE
RichText can not get the correct value, when one part is plain text and the other part is rich text.

### ISSUE THREAD

**Issue by expbenson** [PHPOffice/PhpSpreadsheet#442]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When I use RichText()->getPlainText(), I should get complete text, contain plain text and rich text.

### What is the current behavior?
In xlsx, Like cell value: "plain text, rich text", RichText()->getPlainText() only return the rich text part("rich text"). the first part is missing.

### What are the steps to reproduce?
In source code https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Reader/Xlsx.php, line 2070

```php
foreach ($is->r as $run) {
    if (isset($run->rPr)) {
        // ...
    }
}
```

missing the else part.

It should be
```php
if (isset($run->rPr)) {
    // ...
} else {
    $value->createText(StringHelper::controlCharacterOOXML2PHP((string) $run->t));
}
```
In Xlsx, a cell can contain part to plain text, and the other part of rich text.
In above, $run element can only have "t" attribute.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.2.0, PHP 7.1.6.

**Comment by BlueM** [comment]
I can confirm that the problem exists in 1.2.0 and was gone after downgrading to 1.1.0

**Comment by sztanpet** [comment]
Have tested the proposed solution, can confirm it works fine.

**Comment by expbenson** [comment]
Code in below can reproduce the bug. (Prepare an empty xlsx file)

```php
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('empty.xlsx');
$worksheet = $spreadsheet->getActiveSheet();
$richText = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
$richText->createText('plain text');
$payable = $richText->createTextRun('rich text');
$payable->getFont()->setBold(true);
$payable->getFont()->setColor( new \PhpOffice\PhpSpreadsheet\Style\Color( \PhpOffice\PhpSpreadsheet\Style\Color::COLOR_DARKGREEN ) );
$worksheet->getCell('A1')->setValue($richText);

$output = "richtext.xlsx";
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, "Xlsx");
$writer->save($output);

$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($output);
$worksheet = $spreadsheet->getActiveSheet();
$cell = $worksheet->getCell('A1');
/** @var \PhpOffice\PhpSpreadsheet\RichText\RichText $value */
$value = $cell->getValue();
echo $value->getPlainText();
// output: 'rich text'
```

**Comment by gintsmurans** [comment]
Yup, same issue here. v1.2.0

**Comment by sztanpet** [comment]
current develop branch (@  5f03659) still has the issue
