### ISSUE TITLE
PhpOffice\PhpSpreadsheet\Helper\Html() used for set html to cell, but russian charactor change to some special charactor

### ISSUE THREAD

**Issue by alagesanbe08** [PHPOffice/PhpSpreadsheet#444]
This is:

PhpOffice\PhpSpreadsheet\Helper\Html() used for set html to cell, but russian charactor change to some special character

### What is the expected behavior?

Смеситель для раковины Jacob Delafon Aleo E72277-CP

### What is the current behavior?

Ð¡Ð¼ÐµÑÐ¸ÑÐµÐ»Ñ Ð´Ð»Ñ ÑÐ°ÐºÐ¾Ð²Ð¸Ð½Ñ Jacob Delafon Aleo E72277-CP

### What are the steps to reproduce?

     require __DIR__ . '/vendor/autoload.php';

    // Create new Spreadsheet object
    $spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

    $wizard = new \PhpOffice\PhpSpreadsheet\Helper\Html();
     $value = "Смеситель для раковины Jacob Delafon Aleo E72277-CP";
    $cellValue = $wizard->toRichTextObject($value);
             print_r($cellValue);

**Comment by MarkBaker** [comment]
You need to pass UTF-8 to the helper, same as setting cell values from strings should always be UTF-8. Is this a UTF-8 value?
