### ISSUE TITLE
read xlsx using filesystem gaufrette

### ISSUE THREAD

**Issue by wladimiravila** [PHPOffice/PhpSpreadsheet#447]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

read files xslx like xsl or ods over s3 in aws

### What is the current behavior?

generate error Warning: ZipArchive::getFromName(): Invalid or uninitialized Zip object
in file vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php

trying to open this file 'xl/_rels/workbook.xml.rels'

### What are the steps to reproduce?

configure gaufrette to read files from s3 in aws in my case using gaufrette symfony bundle, its a weird case because works with files xls but not xlsx

```php
<?php

// Create new Spreadsheet object
use PhpOffice\PhpSpreadsheet\IOFactory;

  $path = 'gaufrette://importExcel/' . $event->getFile()->getName();

        $inputFileType = UploadListener::getReaderTypeFromExtension($event->getFile()->getName());
     
        $reader = IOFactory::createReader($inputFileType);

        $spreadsheet = $reader->load($path);
        $sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);

### Which versions of PhpSpreadsheet and PHP are affected?
      "phpoffice/phpspreadsheet": "^1.2",

**Comment by PowerKiKi** [comment]
Can you give an example of code that include gaufrette usage to reproduce it locally easily (without S3) ?

**Comment by wladimiravila** [comment]
thanks for your answer, here some steps:

install some packages

composer require knplabs/knp-gaufrette-bundle
composer require phpoffice/phpspreadsheet

setup your gaufrette usyng your aws se credentials
https://github.com/KnpLabs/KnpGaufretteBundle/blob/master/Resources/docs/adapters/awss3.md

generate a php file 

        $file='yourExcelFileLocatedInBucketS3.xlsx';
        $path = 'gaufrette://importExcel/' .  $file;
        $inputFileType = UploadListener::getReaderTypeFromExtension( $file);
        $reader = IOFactory::createReader($inputFileType);
        $spreadsheet = $reader->load($path);
        $sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);


thats all

**Comment by oleibman** [comment]
Php ZipArchive simply does not work for anything other than local files. For a workaround, see https://github.com/PHPOffice/PhpSpreadsheet/pull/2326#issuecomment-4166389344

Leaving issue closed, removing stale label.
