### ISSUE TITLE
Raw values are still interpreted for percent types

### ISSUE THREAD

**Issue by symcaster** [PHPOffice/PhpSpreadsheet#450]
This is:

```
- [X] a bug report
- [ ] a feature request
```

### What is the expected behavior?

When reading a spreadsheet as raw value, percent values are outputed as displayed in the cell (ie: `10 %`).

### What is the current behavior?

When reading a spreadsheet as raw value, percent values are still interpreted (ie: `10 %` in a cell result as `0.1`).

### What are the steps to reproduce?

Using `PhpOffice\PhpSpreadsheet\Worksheet::toArray(null, false, false)` on a speadsheet that contains percent values. Just need to dump the output to see.

### Which versions of PhpSpreadsheet and PHP are affected?

`^1.2.0`

**Comment by criztovyl** [comment]
the `10 %` is with formatting, so `0.1` is right for "raw" values or am I missing something here?

**Comment by romain-pierre** [comment]
Thank you for your reply. But what can we do if we want to get the exactly same value as shown in the spreadsheet editor software? This value will be checked by a regex in my case, I expect to have exactly `[0-9]+ %` in the cell.

**Comment by DurvalPaicheco** [comment]
Alternative:
$real_porc = $porc * 100;

**Comment by oleibman** [comment]
`toArray` has a parameter which controls whether values are formatted or not. Code supplied above says "not". Leaving issue closed, removing stale label.
