### ISSUE TITLE
SetAutoSize with text rotation doesn't calculate right width

### ISSUE THREAD

**Issue by nniicc** [PHPOffice/PhpSpreadsheet#457]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
What i except when i use ```$sheet->getColumnDimension('A')->setAutoSize(true);``` to be the same result as when you double click on a column in excel to auto size it.
<img width="412" alt="screen shot 2018-04-09 at 14 46 27" src="https://user-images.githubusercontent.com/5363602/38498468-d100ae64-3c04-11e8-903b-379bd8632b85.png">

### What is the current behavior?
The width is to big
<img width="863" alt="screen shot 2018-04-09 at 14 39 18" src="https://user-images.githubusercontent.com/5363602/38498170-d4a1b6a4-3c03-11e8-9b38-cc3d94b48d5b.png">

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$sheet = $spreadsheet->getActiveSheet();

$spreadsheet->getDefaultStyle()->getFont()->setName('Arial');
$spreadsheet->getDefaultStyle()->getFont()->setSize(8);
$spreadsheet->getDefaultStyle()->getFont()->setColor(new use \PhpOffice\PhpSpreadsheet\Style\Color(\PhpOffice\PhpSpreadsheet\Style\Color::COLOR_BLUE));

$sheet->setCellValue('A1', 'This is a long line that has a set height and auto width');
$sheet->getColumnDimension('A')->setAutoSize(true);
$sheet->getRowDimension(1)->setRowHeight(120);
$sheet->getStyle('A1')->applyFromArray($this->borderStyle);
$sheet->getStyle('A1')->getAlignment()->applyFromArray([
    'textRotation' => 70,
    'horizontal' => \PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER,
    'vertical' => \PhpOffice\PhpSpreadsheet\Style\Alignment::VERTICAL_CENTER,
    'wrapText' => true,
]);
$filepath = base_path() . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'excels' . DIRECTORY_SEPARATOR  . 'test.xlsx';
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save($filepath);
```
### Which versions of PhpSpreadsheet and PHP are affected?

- PHP: 7.2.4 
- Lumen: 5.6.1
- PhpSpreadsheet: 1.2.0

**Comment by oleibman** [comment]
Using the supplied code, I now get the following result:

<img width="277" height="346" alt="Image" src="https://github.com/user-attachments/assets/082d456f-739a-4b80-928d-4761211e52d0" />

So this appears to no longer be an issue. Leaving issue closed, removing stale label.
