### ISSUE TITLE
result from getStyle not same as excel

### ISSUE THREAD

**Issue by lintangtimur** [PHPOffice/PhpSpreadsheet#458]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Font must be `Arial`, and have border

### What is the current behavior?
Font is `Calibri`, and dont have border

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require 'vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Helper\Sample;

$inputFileType = 'Xlsx';
$inputFileName = __DIR__ . '/master/file.xlsx';
$reader = IOFactory::createReader($inputFileType);
$reader->setLoadSheetsOnly('laporan');
$spreadsheet = $reader->load($inputFileName);
$spreadsheet->getActiveSheet()->getStyle('B11')->getFont();
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.2
PHP 7.2.2

**Comment by odeland** [comment]
@lintangtimur did you ever find a solution for this? I have the same issue. It looks like PhpSpreadsheet simply ignores the Cell style and uses the "Style supervisor" instead.
