### ISSUE TITLE
Special Characters not in spreadsheet

### ISSUE THREAD

**Issue by ProtinusBennie** [PHPOffice/PhpSpreadsheet#467]
This is:
I'm fairly new in PHPSpreadsheet. I want to create a simple xlsx but the text contains special characters. At the moment a simple sepcial char (e.g. ë) this is not shown in the excel sheet. 

In the cell B2 the value ONWAAR (dutch for FALSE) is put in. What do I wrong?

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Hello World !');

$spreadsheet->getActiveSheet()
    ->setCellValue('A2', 'String')
    ->setCellValue('B2', 'this is a special char ë')
    ->setCellValue('C2', 'PhpSpreadsheet');

$writer = new Xlsx($spreadsheet);
$writer->save('hello world.xlsx');


### Which versions of PhpSpreadsheet and PHP are affected? PHP 5.6.3

**Comment by MarkBaker** [comment]
Are you using UTF-8 charset? It should work without issue if you are. Otherwise you need to convert the charset that you are using to UTF-8.
Note that using `htmlspecialchars()` is NOT an appropriate solution. Spreadsheets are not HTML files
