### ISSUE TITLE
Xlsx Reader doesn't use readEmptyCells

### ISSUE THREAD

**Issue by thisispaul** [PHPOffice/PhpSpreadsheet#468]
This is:

```
- a bug report
```

### What is the expected behavior?
When I set `readEmptyCells` to `false` on a Xlsx Reader and then call `$spreadsheet->getActiveSheet()->toArray()` I would expect an array with all the values in the sworksheet.

### What is the current behavior?
When I call `$spreadsheet->getActiveSheet()->toArray()` I get a huge array [~1000 rows] where most of the rows are filed with `null` arrays (in my example everything after row 100 is null).

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$reader = IOFactory::createReaderForFile($path);
$reader->setReadDataOnly(true);
$reader->setReadEmptyCells(false);
$spreadsheet = $reader->load($path);
$data = $spreadsheet->getActiveSheet()->toArray();
```

### Which versions of PhpSpreadsheet and PHP are affected?
`phpoffice/phpspreadsheet: 1.2.1`
`php: 7.1.15`

**Comment by gabrielgmm** [comment]
Hi ThisPaul,

I have been tested with a xlsx with  this file:
https://drive.google.com/open?id=1ka_KpKPJhIQqfAgRvNDgzMrS-wKh1tub
I installed in same directory of teste file

I used a PHP 7.1.11 and 7.1.16 

My code
[$inputFileName = "teste.xlsx";
$inputFileType = \PhpOffice\PhpSpreadsheet\IOFactory::identify($inputFileName);
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($inputFileType); // teste pass ok
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($inputFileName); // teste pass ok
$reader->setReadDataOnly(true);
$reader->setReadEmptyCells(true);
$spreadsheet = $reader->load($inputFileName);
$data = $spreadsheet->getActiveSheet()->toArray();](url)

**Comment by thisispaul** [comment]
yes yours seems to work.

I think something must be going on with the file I have. It was downloaded from google drive and has about 21 different sheets in it. I tried a different file download from google drive with much less data and that seemed to work fine. Would having loads of sheets in the file cause any issues you are aware of?

**Comment by zaifeng** [comment]
@gabrielgmm with your code I got an 30 rows returned, but in fact ,i have 70 rows in xlsx, what's  going wrong with? expect you reply

**Comment by gabrielgmm** [comment]
Can you send a xls file ?

**Comment by thisispaul** [comment]
@gabrielgmm unfortunately the file i'm using has some data in it that I can't release publicly right now. Not helpful I know. I am trying to create a new file that behaves the same with dummy data right now.

One thing I have noticed is that when i separate the one sheet from the whole file as a new XLXS then it works fine and doesn't pad the array with thousands of null values, but I still get the issue if I use the `setLoadSheetsOnly` to only load the one sheet.

The root of the problem I think after debugging some things is that the `getHighestRowAndColumn` function is bringing back incorrect values for the sheet which is why I end up with thousands of null values. The work by @monofone wouldn't solve this issue as it would just cache the incorrect values.

I will continue to try and create a spreadsheet with dummy data that behaves this way for better testing purposes.

**Comment by DavidNTV** [comment]
I have the same problem with .xlsx, a lot of nulls while reading the spreadsheet.
After some tests, looks like .xlsx files created by MS Office works perfectly, but .xlsx files created by LibreOffice Calc (version 5.1.6.2, compilation 1:5.1.6~rc2-0ubuntu1~xenial6) doesn't works as spected.
But LibreOffice works fine with .xls and .ods.
Hope this can be helpfull for someone.

**Comment by siarheipashkevich** [comment]
@DavidNTV did you resolve you problem with .xlsx file?
