### ISSUE TITLE
splitted RichElements

### ISSUE THREAD

**Issue by antonioaltamura** [PHPOffice/PhpSpreadsheet#476]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Not exactly a bug, it's a strange behaviour.
I want just 1 RichText object out of "Geneva Refugee Convention and Protocol"

### What is the current behavior?
Two RichText objects: "Geneva Refugee Convention " and " and Protocol" with exactly the same proprieties (Font Object).

### What are the steps to reproduce?
File: [rich.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/1957087/rich.xlsx)

```php
<?php
require __DIR__ . '/vendor/autoload.php';
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load("rich.xlsx");
$a1 = $spreadsheet->getActiveSheet()->getCell('A1');
print_r($a1->getValue()->getRichTextElements());

```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP: 7.2.4
phpspreadsheet: 1.2.1

**Comment by oleibman** [comment]
Reopening. Fix will be available in a day or two.
