### ISSUE TITLE
Add row with data

### ISSUE THREAD

**Issue by JanSchroeder** [PHPOffice/PhpSpreadsheet#48]
Is there a way to add a row with data like this?
 $spreadsheet->setActiveSheetIndex(0)->addRow(["Hello","Welt"])

i found only the example to set cells 

 $spreadsheet->setActiveSheetIndex(0)
            ->setCellValue('A1', 'Hello')
            ->setCellValue('B2', 'world!')
            ->setCellValue('C1', 'Hello')
            ->setCellValue('D2', 'world!');

**Comment by MarkBaker** [comment]
A number of the examples demonstrate the `fromArray()` method

**Comment by PowerKiKi** [comment]
http://phpspreadsheet.readthedocs.io/en/develop/Overview/07-Accessing-Cells/#setting-a-range-of-cells-from-an-array
