### ISSUE TITLE
Sheet reference doesn't work properly due to lower character 

### ISSUE THREAD

**Issue by riva76** [PHPOffice/PhpSpreadsheet#480]
This is:

```
- [ X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Formula '=$SHEET1.A1' display 1

### What is the current behavior?
Formula '=$sheet1.a1' display 0
cell does't display the correct value because formula is written in lower case characters.  

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$objPHPExcel = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$objWriter = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($objPHPExcel);

$objPHPExcel->getActiveSheet()->setTitle('SHEET1');
$objPHPExcel->getActiveSheet()->setCellValue("A1", "1");

$myWorkSheet = new \PhpOffice\PhpSpreadsheet\Worksheet\Worksheet($objPHPExcel,'Summary');
$objPHPExcel->addSheet($myWorkSheet, 0);
$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->setCellValue("A1", "=$SHEET1.A1");

$objWriter->save('test.xlsx');
?>
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.1.6
PHPSpreadsheet 1.2.0

**Comment by llvdl** [comment]
I ran into this issue as well and found a workaround on stackoverflow: https://stackoverflow.com/questions/51099953/formula-to-get-data-from-other-sheet-always-return-lowercase-in-phpspreadsheet

Hopefully this will save others time when running into this issue.

> Try quoting the sheet name, and using ! to reference the cell:

```php
$ac = $spreadsheet1->getActiveSheet(0);
$ac->setCellValue('B1', "='Sheet2'!B1");
```

**Comment by oleibman** [comment]
I am not familiar with the the format `$SHEET.A1` mentioned here. But I do know that `Sheet1!A1` will work as desired, no matter what case each of its characters uses.
