### ISSUE TITLE
Migration faux pas

### ISSUE THREAD

**Issue by Synchro** [PHPOffice/PhpSpreadsheet#481]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

The migration tool does a number of somewhat dumb, unexpected things.

### What is the expected behavior?
As far as it can, the migration tool should make the changes necessary to move from PHPExcel to PHPSpreadsheet, *but no more*.

### What is the current behavior?
The migration makes some changes that are inadvisable and easily avoided.

It appears to do a blanket global replacement of `PHPExcel` with `\PhpOffice\PhpSpreadsheet\Spreadsheet`, but this includes places that this change should not be made, causing breakages. For example, I had a private property that held a PHPExcel instance, and it did this:

    private $PHPExcel;

became:

    private $\PhpOffice\PhpSpreadsheet\Spreadsheet

Which is not even valid PHP.

The instructions for the migration suggest running it in the project root, which includes the vendor folder - so the migration is applied to the installed PHPExcel package, and also makes changes to PHPSpreadsheet package wherever it happens to mention PHPExcel.

The migration should not touch anything in a `vendor` folder.

### What are the steps to reproduce?

You don't even need any code to demonstrate this; an empty project is enough:

```sh
composer init
composer require phpoffice/phpexcel
composer require phpoffice/phpspreadsheet
vendor/phpoffice/phpspreadsheet/bin/migrate-from-phpexcel
```

The output shows that it has made changes to both the PHPExcel and PHPSpreadsheet files (excerpt):

```sh
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpexcel/install.txt converted
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpexcel/Classes/PHPExcel.php converted
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpexcel/Classes/PHPExcel/Autoloader.php converted
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpexcel/Classes/PHPExcel/CachedObjectStorageFactory.php converted
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpexcel/Classes/PHPExcel/Calculation.php converted
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php converted
...
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpspreadsheet/docs/topics/migration-from-PHPExcel.md converted
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpspreadsheet/samples/Basic/46_ReadHtml.php converted
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Helper/Migrator.php converted
/Users/marcus/Sites/pxtest/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods.php converted
/
```
Note that this also applies the replacements in non-PHP files, which is quite unnecessary.

### Which versions of PhpSpreadsheet and PHP are affected?
I'm using PHPExcel 1.8.1 and PHPSpreadsheet 1.2.1. It probably affects others.

As far as I can see, the current blanket search and replace mechanism is extremely unlikely to produce working code, and probably causes more problems than it solves. The matches and replacements could be made much more specific, or better still, be based on an AST search rather than simple text.

**Comment by Synchro** [comment]
I assume this is is still an issue...

**Comment by PowerKiKi** [comment]
Indeed nothing was done to improve the situation. A PR would be very welcome if you have time.

**Comment by blunket** [comment]
Hope my PR is sufficient. Let me know. This bug was affecting me directly also.
