### ISSUE TITLE
Required function parameters are not set (Error in PHP7)

### ISSUE THREAD

**Issue by KoenigsKind** [PHPOffice/PhpSpreadsheet#485]
This is:

```
- [x] a bug report
```

### Problem
PHP 7 throws an [_ArgumentCountError_](https://3v4l.org/dnfYQ) if a function call doesn't set all required parameters.

### Affected files

- Worksheet.php _(missing 1 argument)_
  > https://github.com/PHPOffice/PhpSpreadsheet/blob/36acc372875c4d894dc093825ce4f62209db5a76/src/PhpSpreadsheet/Writer/Xls/Worksheet.php#L830
  > https://github.com/PHPOffice/PhpSpreadsheet/blob/36acc372875c4d894dc093825ce4f62209db5a76/src/PhpSpreadsheet/Writer/Xls/Worksheet.php#L654
- PolynomialBestFit.php _(missing 3 arguments)_
  > https://github.com/PHPOffice/PhpSpreadsheet/blob/36acc372875c4d894dc093825ce4f62209db5a76/src/PhpSpreadsheet/Shared/Trend/PolynomialBestFit.php#L167
  > https://github.com/PHPOffice/PhpSpreadsheet/blob/36acc372875c4d894dc093825ce4f62209db5a76/src/PhpSpreadsheet/Shared/Trend/BestFit.php#L304

### Which versions of PhpSpreadsheet and PHP are affected?
branch develop on PHP 7

**Comment by oleibman** [comment]
Seems to have been fixed by PR #486, or at least part of it. Regardless, we no longer support Php7.
