### ISSUE TITLE
Incorrect reading conditional style

### ISSUE THREAD

**Issue by dven1** [PHPOffice/PhpSpreadsheet#487]
This is:

```
- [*] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Readed condition style doesn't contain default parameters for alignment.

### What is the current behavior?
Readed condition style contain alignment width default parameters

### What are the steps to reproduce?
Create some xlsx file with PhpSpreadsheet, added conditional style for some cell which merged width other cells. Store file into fs. Read generated file and store again. In result file, we see incorrect view for cell which conditional style apply. Value for this cell is duplicated. Research shows that problem width read style for condition: \PhpOffice\PhpSpreadsheet\Reader\Xlsx::readStyle. We don't check values exists for $style->alignment['horizontal'] and $style->alignment['vertical'] and set them to style. In case conditional style we set default values. 
<img width="352" alt="screen shot 2018-05-04 at 19 34 17" src="https://user-images.githubusercontent.com/38982780/39640068-8569ddea-4fd2-11e8-9e5d-2b86ddf56ed8.png">

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.2.1

**Comment by oleibman** [comment]
Fixed by PR #4027. Excel does not use Alignment or Protection in Conditional Styles, and has problems if you attempt to use them.
