### ISSUE TITLE
Any plans to support apples numbers format?

### ISSUE THREAD

**Issue by CodeBrauer** [PHPOffice/PhpSpreadsheet#49]
I don't know how much people are using actually Numbers from Apples iWork Suite but are there any plans to support this filetype too?

I know also that the Numbers file is not documented and it would be needed to reverse engineer this format `application/x-iwork-numbers-sffnumbers`

**Comment by PowerKiKi** [comment]
No plans that I am aware of. Most likely you (or another person) would have to create a PR for it if you want to see it one day in PhpSpreadsheet, because we lack the resource to invest in that kind of feature.
