### ISSUE TITLE
Color format for negative numbers is broken in HTML writer

### ISSUE THREAD

**Issue by jdwiese** [PHPOffice/PhpSpreadsheet#495]
This is:

```
- [X] a bug report
```

### What is the expected behavior?
Negative numbers should appear in red color when using a proper format

### What is the current behavior?
Instead the SPAN-tag used for formatting is displayed

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$worksheet = $spreadsheet->getActiveSheet();
$worksheet->getCell('A1')
          ->setValueExplicit(-1, \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_NUMERIC)
          ->getStyle()
          ->getNumberFormat()
          ->setFormatCode('0_ ;[Red]-0 ');
$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Html');
$writer->save('test.html');
?>
```

### Which versions of PhpSpreadsheet and PHP are affected?
The latest development version is still affected. The problem is in line 1296 in /PhpSpreadsheet/Writer/Html.php. The "htmlspecialchars" call is redundant as it has already been done by the "formatColor" method passed as callback to the "NumberFormat::toFormattedString" calls a few lines above.

**Comment by oleibman** [comment]
Code snippet above now produces expected result.
