### ISSUE TITLE
Number Formatted with thousands separator (,) Saved as Text instead of a Number

### ISSUE THREAD

**Issue by zd-zero** [PHPOffice/PhpSpreadsheet#496]
This is:

```
- [ x ] a bug report
```

### What is the expected behavior?
Variable with string data type that contains a formatted number should be saved in excel as a number not as a string.
```php
$value = '1,900.00';  // should be saved as number
```

![expected](https://user-images.githubusercontent.com/21978370/39962066-015a9c1e-5677-11e8-9dc6-08d0c11e0653.png)

### What is the current behavior?
The value set is stored as text instead of a number

![current behavior](https://user-images.githubusercontent.com/21978370/39962096-a9601cae-5677-11e8-9ce8-7ad1ad794828.png)

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
// Create new Spreadsheet object
public some_function() {
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();
    $value = '1,900.00'; // when the value contains comma (,) the value cannot be saved properly
    /*
     already tried casting
     $value = floatval($value); // tried this
     $value = (float) $value; // tried this
    */

    $sheet->setCellValueByColumnAndRow(1, 1, $value);

    $writer = new Xlsx($spreadsheet);
    $writer->save('anyfilename.xlsx');
}
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.2.1

**Comment by criztovyl** [comment]
I would say that this is out of scope for PhpSpreadsheet as this involves parsing of things that are not properly related to a spreadsheet library.

If you want to store a number - pass in a number. That's the API.

I guess this is for convenience, but it would add unneeded complexity to the library, e.g. what if one explicitly want to store a number as a string, for whatever reason? Why only support English numbers (`1,000.00`), why not also German ones (`1.000,00`)?

**Comment by zd-zero** [comment]
Yes I agree, but I thought that it was already implemented, because it was stated in the [PhpSpreadsheet Documentation](https://phpspreadsheet.readthedocs.io/en/develop/topics/accessing-cells)

See the emphasized sentence below for your reference:
> ...
By default, when you call the worksheet's `setCellValue()` method or the cell's `setValue()` method, PhpSpreadsheet will use the appropriate datatype for PHP nulls, booleans, floats or integers; or cast any string data value that you pass to the method into the most appropriate datatype, so **numeric strings will be cast to numbers**, while string values beginning with = will be converted to a formula. Strings that aren't numeric, or that don't begin with a leading = will be treated as genuine string values.
...

Thank you for your response

**Comment by zd-zero** [comment]
I tested the function `setCellValue()` but still doesn't work.
```php
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

$sheet->setCellValue('A1', '1,234.56');
$spreadsheet->getActiveSheet()->setCellValueExplicit(
    'A2',
    '1,234.56',
    DataType::TYPE_NUMERIC
);

$writer = new Xlsx($spreadsheet);
$writer->save('abc.xlsx');
```


![error](https://user-images.githubusercontent.com/21978370/40006037-f90ea5c2-57cb-11e8-8324-bbb707f19681.png)

Maybe I shouldn't just depend on the auto casting feature, yet it's still a good feature, but still the documentation is misleading, thank you.

**Comment by criztovyl** [comment]
What I can tell from the source so far is that it seems like only numeric values without thousand-separators are supported, compare `DefaultValueBinder`:
https://github.com/PHPOffice/PhpSpreadsheet/blob/38638268d8916c6138d2f8cabb2c9646ece16a72/src/PhpSpreadsheet/Cell/DefaultValueBinder.php#L62

I think in that case the documentation should be clarified a little bit more what "numeric values" are.

Thanks for the report. :)

**Comment by zd-zero** [comment]
Thank you for your time 💯
