### ISSUE TITLE
Will not open some *.xlsx files

### ISSUE THREAD

**Issue by xakepsoft** [PHPOffice/PhpSpreadsheet#500]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
[SMS_10.05.2018.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2012461/SMS_10.05.2018.xlsx)

This XLSX file opens in excel and in libreoffice without problems

### What is the current behavior?

PhpSpreadsheet won't open it.
The file was generated with Microsoft Navision standard library.

### What are the steps to reproduce?

Just try to open it.

I suspect the problem is related to unusual XML fields which are starting with "x:"
x:row , x:c , x:is , x:t  <<-----  BAD FIELDS  PhpSpreadsheet won't work
row , c , is , t            <<-----  GOOD FIELDS  PhpSpreadsheet works

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...

$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile( 'SMS_10.05.2018.xlsx' );
$spreadsheet = $reader->load( 'SMS_10.05.2018.xlsx' );



### Which versions of PhpSpreadsheet and PHP are affected?
1.2.1
PHP - 7.0.8

**Comment by criztovyl** [comment]
Is there an error you could provide?

**Comment by xakepsoft** [comment]
There are no errors.  PhpSpreadsheet just ignores all data in XLSX file.
The difference is in XML field names. PhpSpreadsheet understands only: "row" , "c" , "is"
but this file has: "x:row" , "x:c" , "x:is"

That's the difference.

**Comment by criztovyl** [comment]
My knowledge about OOXML and PhpSpreadsheet is limited, someone else will have to look into this.

Anyway, thanks for the report.

**Comment by xakepsoft** [comment]
Dirty hack to solve this problem can be found HERE:
https://github.com/PHPOffice/PHPExcel/issues/1187#issuecomment-295032648

Issue closed!

**Comment by isleshocky77** [comment]
Just a note, I modified the mentioned [dirty hack](https://github.com/PHPOffice/PHPExcel/issues/1187#issuecomment-295032648) above for PhpSpreadsheet with the following

```php
<?php
# /src/Org/Example/PhpOffice/PhpSpreadsheet/Reader/Excel2007_NonStandardNamespacesWorkaround.php
namespace Org\Example\PhpOffice\PhpSpreadsheet\Reader;

use PhpOffice\PhpSpreadsheet\Reader\Xlsx;

/**
 * @see https://stackoverflow.com/questions/29514200/phpexcel-parsing-xlsx-files-with-x-namespace
 * @see https://github.com/PHPOffice/PHPExcel/issues/1187#issuecomment-295032648
 * @see https://github.com/PHPOffice/PhpSpreadsheet/issues/500
 */
class Excel2007_NonStandardNamespacesWorkaround extends Xlsx
{
    public function __construct()
    {
        parent::__construct();
        $this->securityScanner->setAdditionalCallback([self::class, 'securityScan']);
    }

    public static function securityScan($xml)
    {
        return str_replace(
            [
                '<x:',
                '</x:',
                /*':x=',*/
                '<d:',
                '</d:'
                /*, ':d='*/
            ],
            [
                '<',
                '</',
                /*'=',*/
                '<',
                '</'
                /*, '='*/
            ],
            $xml
        );
    }
}
```

```php
# /src/Org/Example/Tests/NonStandardTest.php
use Org\Example\PhpOffice\PhpSpreadsheet\Reader\Excel2007_NonStandardNamespacesWorkaround;
class NonStandardExcelFileImporterTest extends PHPUnit_Framework_TestCase
{
    public function testPhpSpreadSheet()
    {
        $inputFileName = __DIR__ . '/./../../../../resources/data/Test.xlsx';
        $reader = new Excel2007_NonStandardNamespacesWorkaround();
        $spreadsheet = $reader->load($inputFileName);

        $sheets = $spreadsheet->getSheetNames();
        $this->assertNotEmpty($sheets);
        $this->assertEquals('First Sheet', $sheets[0]);
    }
```
