### ISSUE TITLE
Switch case duplicate test

### ISSUE THREAD

**Issue by tolbon** [PHPOffice/PhpSpreadsheet#508]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Choosing the right case

### What is the current behavior?
Choosing maybe the not good case

### Where to see this ###
Writer/Xls/Worksheet.php:writeCFRule()

You have a big switch case with lot of color some case are duplicate two time or more like:
"000080" : line 3272 & 3938
"FF00FF" : line 3276 & 3922
"FFFF00" : line 4002 & 4149
"00FFFF" : line 3284 & 3926
"800080" : line 3288 & 3946
"800000" : line 3292 & 3930

30 warnings like that with phpStorm

### Which versions of PhpSpreadsheet and PHP are affected?
latest

**Comment by oleibman** [comment]
Code has been moved to ColorMap, and is now deprecated. Regardless, all the duplicate entries are commented out now. Phpstan will flag duplicate array indexes (which is how these values are new used), though it doesn't seem to handle duplicate case entries within a switch.
