### ISSUE TITLE
Incorrect output for match function

### ISSUE THREAD

**Issue by balgf** [PHPOffice/PhpSpreadsheet#51]
Formula sample: `=MATCH(MAX({0,0,0,1,0,0,0,2,0,0,0,0,0,0,1,0,0}),{0,0,0,1,0,0,0,2,0,0,0,0,0,0,1,0,0})`

Code sample:

```php
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$spreadsheet->getActiveSheet()->setCellValue(
    'A1',
    '=MATCH(MAX({0,0,0,1,0,0,0,2,0,0,0,0,0,0,1,0,0}),{0,0,0,1,0,0,0,2,0,0,0,0,0,0,1,0,0})'
);
echo $spreadsheet->getActiveSheet()->getCell('A1')->getCalculatedValue();
```

This results to 4. The output i tested in excel, libreoffice calc and google sheets is 17.

**Comment by PowerKiKi** [comment]
Your help would be much appreciated to solve this. It would be great if you could create a unit test for it and propose a patch.

You could create new test data with a few cases, including yours, in a new file `tests/data/Calculation/LookupRef/MATCH.php`. And add the relevant methods in `tests/PhpSpreadsheetTests/Calculation/LookupRefTest.php` (mostly copy paste from existing code).

**Comment by agopaul** [comment]
The behavior of the function MATCH() when omitting the 3rd parameter should be:

> "finds the largest value that is less than or equal to the lookup value. The values in the lookup array must be sorted in ascending order, i.e. from smallest to largest."

The thing is, your set is not ordered like the specs require, but apparently Excel, LibreOffice, etc don't complain if that rule is not respected. 

Anyway, I'm looking into it and will provide a PR if I can reproduce the correct behavior (since I can't find any spec that covers this specific case).

**Comment by PowerKiKi** [comment]
FYI in case you didn't stumble upon it yet, there is also the Google Docs documentation [that talks about it](https://support.google.com/docs/answer/3093378). Unfortunately it does not seem to give much more info, but just in case...

**Comment by agopaul** [comment]
It turns out that the implementation of the MATCH function in Excel is quite weird when the mandatory order of the values is not respected, but I managed to "reverse-engineer" the underlying behavior.
