### ISSUE TITLE
IBM AIX iconv not disabled

### ISSUE THREAD

**Issue by nicolas-sapaig** [PHPOffice/PhpSpreadsheet#512]
This is:

- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

### Expected Behavior

On my system (IBM iseries) "ICONV_IMPL" equals to "IBM iconv"

### Current Behavior

Test is only for "ICONV_IMPL" equals to "unknown"

### Failure Information

Mistake is on IBM AIX iconv test in \phpoffice\phpspreadsheet\src\PhpSpreadsheet\Shared\StringHelper.php
```
         // CUSTOM: IBM AIX iconv() does not work
         if (defined('PHP_OS') && @stristr(PHP_OS, 'AIX') && defined('ICONV_IMPL') && (@strcasecmp(ICONV_IMPL, 'unknown') == 0) && defined('ICONV_VERSION') && (@strcasecmp(ICONV_VERSION, 'unknown') == 0)) {
             self::$isIconvEnabled = false;
 
             return false;
         }
```

### Context

* PHP version: 5.6.15
* PhpSpreadsheet version: 1.2.1

**Comment by PowerKiKi** [comment]
Why do you think iconv should be disabled ? What result do you get when it
is enabled ? And what do you expect instead ?

**Comment by nicolas-sapaig** [comment]
I have this :

> Notice: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-16LE//IGNORE//TRANSLIT' is not allowed in .../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/StringHelper.php on line 456

**Comment by nicolas-sapaig** [comment]
Je suis absent(e) du bureau jusqu'au 20/08/2018




Remarque : ceci est une réponse automatique à votre message  "Re:
[PHPOffice/PhpSpreadsheet] IBM AIX iconv not disabled (#512)" envoyé le
28/07/2018 19:03:11.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

**Comment by oleibman** [comment]
IGNORE/TRANSLIT options were disabled if they don't work by commit 3b0c68663012b0bfe3d8e297299c9cd51824cddd in 2019. Removing stable label, leaving issue closed.
