### ISSUE TITLE
ISERROR() function ignored and not in Stack array

### ISSUE THREAD

**Issue by treadmillian** [PHPOffice/PhpSpreadsheet#513]
This is:

```
- [*] a bug report
- [ ] a feature request
- [*] not a usage question 
```

### What is the expected behavior?
The parsed formula `=IF(ISERROR(SUM($C$25:D25)), 0,AVERAGE($C$25:D25))` in cells D24 to L24 should not ignore the `ISERROR()` function.

`ISERROR()` is used to prevent the `AVERAGE()` function executing and therefore basing an average on cells that contain `#DIV/0!`. 

NOTE: A similar formula `=IFERROR(AVERAGE($AM$25:AP25),NA())` also has the same result, `IFERROR()` function seems to be ignored.

```php
array(10) {
  [0]=>
  float(1.5579086209932)
  [1]=>
  float(0)
  [2]=>
  float(0)
  [3]=>
  float(0)
  [4]=>
  float(0)
  [5]=>
  float(0)
  [6]=>
  float(0)
  [7]=>
  float(0)
  [8]=>
  float(0)
  [9]=>
  float(0)
}
```

### What is the current behavior?
Calculates the average of referenced cells, regardless of the `ISERROR()` function, which appears to be excluded from the Stack (see below), and therefore returns the wrong average due to some some cells containing `#DIV/0!`.

The only correct result is array element zero, as this formulas does not reference any cells with `#DIV/0!`, all other array data is incorrect.

```php
array(10) {
  [0]=>
  float(1.5579086209932)
  [1]=>
  float(0.7221696672908)
  [2]=>
  float(0.48144644486053)
  [3]=>
  float(0.3610848336454)
  [4]=>
  float(0.28886786691632)
  [5]=>
  float(0.24072322243027)
  [6]=>
  float(0.20633419065451)
  [7]=>
  float(0.1805424168227)
  [8]=>
  float(0.16048214828684)
  [9]=>
  float(0.14443393345816)
}
```

## Token\Stack
```log
‌PhpOffice\PhpSpreadsheet\Calculation\Token\Stack::__set_state(array(
   'stack' => 
  array (
    0 => 
    array (
      'type' => 'Function',
      'value' => 'IF(',
      'reference' => NULL,
    ),
    1 => 
    array (
      'type' => 'Operand Count for Function IF()',
      'value' => 3,
      'reference' => NULL,
    ),
    2 => 
    array (
      'type' => 'Brace',
      'value' => '(',
      'reference' => NULL,
    ),
    3 => 
    array (
      'type' => 'Function',
      'value' => 'AVERAGE(',
      'reference' => NULL,
    ),
    4 => 
    array (
      'type' => 'Operand Count for Function AVERAGE()',
      'value' => 1,
      'reference' => NULL,
    ),
    5 => 
    array (
      'type' => 'Brace',
      'value' => '(',
      'reference' => NULL,
    ),
    6 => 
    array (
      'type' => 'Binary Operator',
      'value' => ':',
      'reference' => NULL,
    ),
    7 => 
    array (
      'type' => 'Operand Count for Function SUM()',
      'value' => 1,
      'reference' => NULL,
    ),
    8 => 
    array (
      'type' => 'Brace',
      'value' => '(',
      'reference' => NULL,
    ),
    9 => 
    array (
      'type' => 'Binary Operator',
      'value' => ':',
      'reference' => NULL,
    ),
  ),
   'count' => 5,
))
```

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';
$filename = __DIR__ . '/gh_example.xlsx';

$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($filename);
$reader->setLoadAllSheets(true);
$reader->setIncludeCharts(false);
$spreadsheet = $reader->load($filename);

$seriesData = $spreadsheet->getActiveSheet()->rangeToArray(
    'C24:L24',
    null,
    true,
    false,
    false
);

var_dump($seriesData[0]);
```

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet: 1.2.1
PHP: 5.6.25

### Example files

[gh_example.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2030580/gh_example.xlsx)

**Comment by PowerKiKi** [comment]
Can you provide code that reproduce the error **without** loading an existing file ?

**Comment by treadmillian** [comment]
How would I do that, if this issue is the reading the Excel spreadsheet and parsing the formula from it?

**Comment by treadmillian** [comment]
One last observation, is that the `#DIV/0!` in Excel is produced by the formula `SUM(0/0)`, in PhpSpreadsheet, this returns zero instead of an error.

```php
echo MathTrig::SUM('0/0');
```

**Comment by MarkBaker** [comment]
[gist link to code that can be used to submit details of calculation engine errors](https://gist.github.com/MarkBaker/3ea8664c73bfe6af5bc6f437803589f2)

**Comment by oleibman** [comment]
Submitted code run with submitted spreadsheet now returns 0 for all cells D24:L24, which I believe is correct.
