### ISSUE TITLE
Wont load XLS files with XML content

### ISSUE THREAD

**Issue by kaoz70** [PHPOffice/PhpSpreadsheet#522]
This is:

```
- [X ] a bug report
- [ ] a feature request
```

### What is the expected behavior?
Load XLS files created outside of Excel: We have some XLS files that are created by Facebook's LeadGen forms, they have the extension .xls, but their content is XML.

### What is the current behavior?

When I load the file through:

    IOFactory::load(Storage::path($path))

PhpSpreadsheet throws the exception:

     DOMDocument::loadHTML(): Tag workbook invalid in Entity, line: 5

The reason it does this is because in the method \PhpOffice\PhpSpreadsheet\Reader\Xml::canRead() there is a signature variable:

    $signature = [
            '<?xml version="1.0"',
            '<?mso-application progid="Excel.Sheet"?>',
        ];

Which tries to find it in the first bytes of the file, but in the case of these files they don't have the string: 

    <?mso-application progid="Excel.Sheet"?>

So it returns false and loads the Html reader.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

Sorry, I have to rely on an external file to be able to reproduce this issue:

[test.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/2055858/test.zip)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$path = 'test.xls';
 IOFactory::load($path);
```

If I remove the line in the method: \PhpOffice\PhpSpreadsheet\Reader\Xml::canRead()

    $signature = [
            '<?xml version="1.0"',
        ];

It loads as an XML file correctly.

### Which versions of PhpSpreadsheet and PHP are affected?
1.2.1

**Comment by oleibman** [comment]
Fixed by PR #1917 in March 2021.
