### ISSUE TITLE
Editing Xlsx document does not preserve workbook attributes

### ISSUE THREAD

**Issue by billblume** [PHPOffice/PhpSpreadsheet#523]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Editing a Xlsx document using PhpSpreadsheet should preserve the workbook view attributes of that document.  For example, if the worksheet tabs are hidden in the original document, they should remain hidden after updating.

### What is the current behavior?

Editing a Xlsx document resets most workbook attributes to hardwired values.  

See Writer\Xlsx\Workbook::writeBookViews.  All workbook attributes except for 'activeTabs' are hardwired constants.  For example, 'showSheetTabs' is always set to '1', meaning that worksheet tabs are always visible after updating.

### What are the steps to reproduce?

1. Create a Xlsx spreadsheet with multiple worksheets.
2. Hide the worksheet tabs in that spreadsheet.  (On a Excel 365 on Mac OS, go to Excel > Preferences > View and uncheck 'Sheet Tabs'.)
3. Read the Xlsx spreadsheet with PhpSpreadsheet.
4. Write the Xlsx spreadsheet.
5. The worksheet tabs are now visible again.

### Which versions of PhpSpreadsheet and PHP are affected?

This occurs in all versions of PhpSpreadsheet.  This also occurs in PhpExcel.

**Comment by billblume** [comment]
FYI.  I am working on a PR for this issue.

**Comment by PowerKiKi** [comment]
Thanks for this great addition ! I moved the tests as functional test and merged it.
