### ISSUE TITLE
CSV file with UTF-16LE encoding iconv() error

### ISSUE THREAD

**Issue by kaoz70** [PHPOffice/PhpSpreadsheet#524]
This is:

```
- [ X] a bug report
- [ ] a feature request)
```

### What is the expected behavior?
Correctly load a CSV file with UTF-16LE encoding.

### What is the current behavior?
When loading this file, iconv() throws the error:

    iconv(): Detected an incomplete multibyte character in input string

This happens in the method:

    \PhpOffice\PhpSpreadsheet\Shared\StringHelper::convertEncoding()

Changing the line from:

    $result = iconv($from, $to . '//IGNORE//TRANSLIT', $value);

To:

    $result = iconv(mb_detect_encoding($from, mb_detect_order(), false), $to . '//IGNORE//TRANSLIT', $value);

Fixes the issue, but I'm not sure if there are any side effects by doing this.

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$path = 'test.csv';

// Create new Spreadsheet object
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Csv();
$reader->setInputEncoding('UTF-16LE');
$reader->setDelimiter('	'); // Tab delimiter
$spreadsheet = $reader->load($path));

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.2.1
PHP 7.2

**Comment by gauravnewton** [comment]
is there any way by which we can identify the default encoding scheme used in imported file.

**Comment by oleibman** [comment]
Detecting encoding of CSV file was added by PR #1717 in Nov. 2020. Removing stale label from this issue, leaving it closed.
