### ISSUE TITLE
Does not work drawing

### ISSUE THREAD

**Issue by johndoejdg** [PHPOffice/PhpSpreadsheet#53]
Image  do not appear in spreadsheet after this code but in PhpExcel this works.
```
        $signaturePath = \Yii::$app->basePath.'/storage/for_documents/sign.png';
        $objDrawing = new Drawing();    //create object for Worksheet drawing
        $objDrawing->setName('Sign');
        $objDrawing->setDescription('Sign');
        $objDrawing->setPath($signaturePath);
        $objDrawing->setWidth(60);
        $objDrawing->setWorksheet($this->sheet);
        
        $objWriter = IOFactory::createWriter($saleDocumentInExcel, "Excel5");
```

**Comment by PowerKiKi** [comment]
I confirm that the following code wil output an xlsx with an image, but an xls without an image (assuming a `test.jpg` beside the script):

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new PhpOffice\PhpSpreadsheet\Spreadsheet();

$drawing = new PhpOffice\PhpSpreadsheet\Worksheet\Drawing(); 
$drawing->setPath('test.jpg');
$drawing->setWorksheet($spreadsheet->getActiveSheet());

$writer = new PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save('test.xlsx');

$writer = new PhpOffice\PhpSpreadsheet\Writer\Xls($spreadsheet);
$writer->save('test.xls');
```

Unfortunately I won't have time to investigate further. But if you could determine exactly what commit broke the feature, it would be very helpful.

**Comment by johndoejdg** [comment]
I found strange place when debug this problem:
![image](https://cloud.githubusercontent.com/assets/2064465/21461918/f2371f92-c95e-11e6-8fd7-680c65c0c3a0.png)

Switch never execute any switch block because expected that class will start with "\\" in but class name start from latin character. I guess it can be reason of this issue but not check it.

**Comment by johndoejdg** [comment]
I check it, drawing now attached.
Submit PR with fix: https://github.com/PHPOffice/PhpSpreadsheet/pull/61

**Comment by atiqShafi** [comment]
My need is same, I have tried from view with html img tag but it does not worked. then I have tried below methods :
 
    public static function beforeSheet(BeforeSheet $event) {
        
        $drawing = new Drawing();
        $drawing->setPath(public_path('sent_files/35/100_1521622088/35_final_card.png'));
        $drawing->setCoordinates('A3');
        $drawing->setWidth(150);
        $drawing->setHeight(100);
        $drawing->setWorksheet($event->sheet);
    }

I am getting bellow error : 

`Type error: Argument 1 passed to PhpOffice\\PhpSpreadsheet\\Worksheet\\BaseDrawing::setWorksheet() must be an instance of PhpOffice\\PhpSpreadsheet\\Worksheet\\Worksheet or null, instance of Maatwebsite\\Excel\\Sheet given, called in /php_projects/my-details/app/Exports/ReportDataFromSbExport.php on line 113`
