### ISSUE TITLE
clone $sheet fails when drawings are inside the sheet

### ISSUE THREAD

**Issue by stSaHiB** [PHPOffice/PhpSpreadsheet#538]
This is:

```
- [ x ] a bug report
```

### What is the expected behavior?
```php
$spreadsheet=IOFactory::load('test.xlsx');
clone $spreadsheet->getActiveSheet();
```
should get you a clone of the sheet.

### What is the current behavior?
Connection  to server breaks, if there is an image within the sheet to be cloned.

### What are the steps to reproduce?

Insert an image to an empty xlsx file, save, then import it and try to clone the sheet.
Seems like some referencing error in _PhpOffice\PhpSpreadsheet\Worksheet_ **__clone()** 
```PHP
//line 2960
foreach ($this->drawingCollection as $id => $item) {
    if (is_object($item)) {
        // $newCollection[$id] = clone $this->drawingCollection[$id]; 
        $newCollection[$id]=unserialize(serialize($this->drawingCollection[$id]));  //this quick n dirty fix solves at least the cloning part of the problem
    }
}
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.2.1 /  PHP 7.2.5

**Comment by 0bp** [comment]
Same issue here. Cloning a sheet with images leads to a segmentation fault (11).

* PHP 7.2.1 and PhpSpreadsheet 1.3.1
* PHP 7.2.8 and PhpSpreadsheet 1.3.1

**Comment by 0bp** [comment]
It looks like images embedded in worksheets are causing a reference loop in the worksheet object and `clone` would segfault at memory limit because of the infinite loop to clone an object. 

Only option would be a custom copy method instead of relying on PHP's `clone`

**Comment by 0bp** [comment]
The solution from @stSaHiB works for the creation process but the images are missing in the cloned  worksheet, so it's not really a solution but proves the issue with PHP's `clone` method.

**Comment by 0bp** [comment]
Version 1.4.0 and especially 
https://github.com/PHPOffice/PhpSpreadsheet/blob/1.4.0/src/PhpSpreadsheet/Worksheet/BaseDrawing.php#L512-L513

solved the issue.
