### ISSUE TITLE
=LOOKUP not working

### ISSUE THREAD

**Issue by nico388** [PHPOffice/PhpSpreadsheet#539]
`use PhpOffice\PhpSpreadsheet\Calculation\Calculation;`
`use PhpOffice\PhpSpreadsheet\Spreadsheet;`
[...]

`$spreadsheet->getActiveSheet()->setCellValue('A43', 10)
->setCellValue('B43', 10)
->setCellValue('C43', 'toto')
->setCellValue('D43', '=LOOKUP(A43;B43;C43)');  `

**the PHP error returns :** 

Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Worksheet!D43 -> Formula Error: An unexpected error occured in C:\...\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Cell\Cell.php on line 274

PhpOffice\PhpSpreadsheet\Calculation\Exception: Worksheet!D43 -> Formula Error: An unexpected error occured in C:\...\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Cell\Cell.php on line 274

**Comment by oleibman** [comment]
Formula needs to use commas, not semicolons, to separate its arguments.
