### ISSUE TITLE
will you add xlt support

### ISSUE THREAD

**Issue by cuixg** [PHPOffice/PhpSpreadsheet#540]
This is a feature request.

I have used phpexcel for two years. And in my business, I usually have to provide a model for users. Xlt file is better then xls in this situation.

**Comment by PowerKiKi** [comment]
AFAIK, [xltx format is the same as xlsx](https://stackoverflow.com/a/2702764/37706) (and xlt, xls). Nothing stops you from saving a file with ".xltx" extension
