### ISSUE TITLE
Opening an Excel file which reuses an image multiplies the image on save

### ISSUE THREAD

**Issue by MAKS-dev** [PHPOffice/PhpSpreadsheet#543]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When one imagefile is reused in the Excel document for e.g. 3 times, it is only placed once in the xlsx file (can be checked by opening it with WinRAR).
After opening the file with PhpSpreadsheet and saving it the image file must still be reused in the xlsx file and placed only once.
This prevents large Excel sheets containing multiple copies, of e.g. a company logo, for growing to a huge file.

### What is the current behavior?
After opening the xlsx file with PhpSpreadsheet and saving it, even without any additional processing, there are multiple image files in the xlsx file. When the document had 3 references, PhpSpreadsheet will put 3 image files in the xlsx. 

### What are the steps to reproduce?
Start a new document with Excel 2016, insert a small PNG image, copy and paste the image a few times. Save the document.
Rename it to .rar and open it with WinRAR, browse to xl/media to see only one png file.
Rename back to .xlsx and upload to webserver.

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = IOFactory::load('test-in.xls');

// add code that show the issue here...
$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save('test-out.xlsx');
```

You'll notice that the new file has increased roughly 2x the image size.
A check with WinRAR shows 3 copies of the file.

### Which versions of PhpSpreadsheet and PHP are affected?
Just downloaded the lastest version here.
PHP version 7.0.23

**Comment by pimpreneil** [comment]
I have just reproduced the problem. A workaround idea would be greatly appreciated 👍

**Comment by MAKS-dev** [comment]
I'd really appreciate to keep this one open since it's still a bug.

**Comment by MAKS-dev** [comment]
This is still an issue.
Recently updated to version 1.8.2 on PHP 7.1.25 and retested the above.
You can use the attached file as input: [test-in.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/3573609/test-in.xlsx)

Excel shows three times the same image and when checking the content (using unrar) there only one .png.
After opening and saving with PhpSpreadsheet, there are three .png files in the file.

When creating larger Excel reports based on a template containing multiple copies of a larger image, the PhpSpreadsheet generated file will grow very large.

Please let me know when more information is needed.
