### ISSUE TITLE
Validate Range Issue in v1.3

### ISSUE THREAD

**Issue by SimonJan** [PHPOffice/PhpSpreadsheet#545]
I see Fatal error: Uncaught exception 'PhpOffice\PhpSpreadsheet\Exception' with message 'Invalid range: "Z5:AA5"' in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php:537

When I debug and see:
$startCol: "W"
$endCol: "Z"
$startCol >= $endCol => FALSE  =>**Right**
→Called from ...Coordinate::validateRange()]
$startCol : "Z"
$endCol: "AB"
$startCol >= $endCol  => TRUE =>**Wrong**
**Can you recheck?**
Thanks

**Comment by PowerKiKi** [comment]
Please try develop branch and confirm that it fixes your problem

**Comment by dugwood** [comment]
@PowerKiKi can you push it to packagist? Easier to test :-) Thanks

**Comment by dugwood** [comment]
Oh, there's only one file to change. Works for me with your patch, thanks.

**Comment by PowerKiKi** [comment]
Thanks for confirming, it's been released as [1.3.1](https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.3.1)
