### ISSUE TITLE
How fix border in TcPDF writer?

### ISSUE THREAD

**Issue by silasrm** [PHPOffice/PhpSpreadsheet#548]
I've a PhpSpreadsheet proccess to export data to XLSX and PDF. I'm using TcPDF as PDF writer. But TcPDF has a problem to convert/translate border style.

XLSX
![captura de tela de 2018-06-12 23-58-35](https://user-images.githubusercontent.com/197187/41330803-e442a39a-6eab-11e8-9dde-4a9f3daed1c8.png)

PDF convert from XLSX object.
![captura de tela de 2018-06-12 23-58-50](https://user-images.githubusercontent.com/197187/41330806-e699ba98-6eab-11e8-82ed-b053321caa0f.png)

**Comment by silasrm** [comment]
I create before create this issue: https://stackoverflow.com/questions/50828542/how-fix-border-in-tcpdf-writer-in-phpspreadsheet

**Comment by tdb85** [comment]
Hi, sorry to reopen this same issue.  I've set up a reproducible test case.  Changing the border style does not apply to the TCPDF writer at all.  I get the exact same result @silasrm gets.

https://github.com/tdb85/tcpdf-phpspreadsheet

**Comment by Collie-IT** [comment]
There is an hotfix see [here](https://github.com/PHPOffice/PhpSpreadsheet/issues/1164)

**Comment by Paytah232** [comment]
No permanent fix yet? @Collie-IT

**Comment by oleibman** [comment]
Everything about this report says that a change has to be made to TCPDF, not PhpSpreadsheet. I have opened https://github.com/tecnickcom/TCPDF/pull/467. If accepted, it will fix this problem; if not, there is nothing further to be done.
