### ISSUE TITLE
MACCENTRALEUROPE instead MAC-CENTRALEUROPE

### ISSUE THREAD

**Issue by rokirokita** [PHPOffice/PhpSpreadsheet#549]
This is:

```
- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Normal encoding.

iconv -l return:

(...)
JIS_C62291984B, JOHAB, JP-OCR-B, JP, JS, JUS_I.B1.002, KOI-7, KOI-8, KOI8-R,
  KOI8-RU, KOI8-T, KOI8-U, KOI8, KOI8R, KOI8U, KSC5636, L1, L2, L3, L4, L5, L6,
  L7, L8, L10, LATIN-9, LATIN-GREEK-1, LATIN-GREEK, LATIN1, LATIN2, LATIN3,
  LATIN4, LATIN5, LATIN6, LATIN7, LATIN8, LATIN9, LATIN10, LATINGREEK,
  LATINGREEK1, **MAC-CENTRALEUROPE**, MAC-CYRILLIC, MAC-IS, MAC-SAMI, MAC-UK, MAC,
  MACCYRILLIC, MACINTOSH, MACIS, MACUK, MACUKRAINIAN, MIK, MS-ANSI, MS-ARAB,
  MS-CYRL, MS-EE, MS-GREEK, MS-HEBR, MS-MAC-CYRILLIC, MS-TURK, MS932, MS936,
  MSCP949, MSCP1361, MSMACCYRILLIC, MSZ_7795.3, MS_KANJI, NAPLPS, NATS-DANO,
  NATS-SEFI, NATSDANO, NATSSEFI, NC_NC0010, NC_NC00-10, NC_NC00-10:81,
  NF_Z_62-010, NF_Z_62-010_(1973), NF_Z_62-010_1973, NF_Z_62010,

(...)

### What is the current behavior?
PhpSpreadsheet has problem with file which has MAC-CENTRALEUROPE encoding
Notice: iconv(): Wrong charset, conversion from `MACCENTRALEUROPE' to `UTF-8//IGNORE//TRANS
LIT' is not allowed

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

//file with MAC-CENTRALEUROPE encoding
$file = 'file.xls';
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($file);

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet Newest
PHP 7.1

**Comment by Armstrong1992** [comment]
The problem still persists

**Comment by oleibman** [comment]
I have at least one system on which MACCENTRALEUROPE is defined without MAC-CENTRALEUROPE, and at least one on which the opposite situation is true. Can you upload a file which has this problem (and include some characters specific to that character set) so that I can experiment with a solution which will work on both?

**Comment by Armstrong1992** [comment]
Attached file: [111.xls](https://github.com/PHPOffice/PhpSpreadsheet/files/6776715/111.xls)

iconv -l:

(...)
  JIS_C6229-1984-B, JIS_C62201969RO, JIS_C62291984B, JOHAB, JP-OCR-B, JP, JS,
  JUS_I.B1.002, KOI-7, KOI-8, KOI8-R, KOI8-RU, KOI8-T, KOI8-U, KOI8, KOI8R,
  KOI8U, KSC5636, L1, L2, L3, L4, L5, L6, L7, L8, L10, LATIN-9, LATIN-GREEK-1,
  LATIN-GREEK, LATIN1, LATIN2, LATIN3, LATIN4, LATIN5, LATIN6, LATIN7, LATIN8,
  LATIN9, LATIN10, LATINGREEK, LATINGREEK1, MAC-CENTRALEUROPE, MAC-CYRILLIC,
  MAC-IS, MAC-SAMI, MAC-UK, MAC, MACCYRILLIC, MACINTOSH, MACIS, MACUK,
  MACUKRAINIAN, MIK, MS-ANSI, MS-ARAB, MS-CYRL, MS-EE, MS-GREEK, MS-HEBR,
  MS-MAC-CYRILLIC, MS-TURK, MS932, MS936, MSCP949, MSCP1361, MSMACCYRILLIC,
  MSZ_7795.3, MS_KANJI, NAPLPS, NATS-DANO, NATS-SEFI, NATSDANO, NATSSEFI,
  NC_NC0010, NC_NC00-10, NC_NC00-10:81, NF_Z_62-010, NF_Z_62-010_(1973),
  NF_Z_62-010_1973, NF_Z_62010, NF_Z_62010_1973, NO, NO2, NS_4551-1, NS_4551-2,
  NS_45511, NS_45512, OS2LATIN1, OSF00010001, OSF00010002, OSF00010003,

(...)


System: 

Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by oleibman** [comment]
I'm sorry, that file is much too large to be used as a test file. Also, I don't see any specifically Central European characters in the cells (they may be in the picture titles, which unfortunately appear in my version of Excel as mojibake). Can you create a file with just a few cells with some Central European characters? I unfortunately do not see a way for me to generate such a file on my system with my version of Excel.

**Comment by oleibman** [comment]
I believe I've found a suitable file at https://github.com/Maatwebsite/Laravel-Excel/issues/989
