### ISSUE TITLE
Phone numbers in format +1234567890 are being miss-interpreted as FORMAT_NUMERIC

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PhpSpreadsheet#55]
My CSV file looks like this:

> "FirstName";"FamilyName";"PhoneNumber";"Supplier";"Birthday"
> "Max";"Mustermann";"+49123456789";"csv-test";03.01.1981

The shown phone number is with current code being interpreted as FORMAT_NUMERIC. But as you can see, I have wrapped it into quotes which should mean FORMAT_STRING. This causes the correctly formatted phone number being returned as 49123456789 and not +49123456789.

If my code sees 49123456789, it auto-prepends a leading zero so the numer is being "fixed". Sadly I cannot turn leading 49 into zero because there are also valid phone numbers with 49 in pre-dial code.

So is there a clean way to force PHPSpreadsheet (same with PHPExcel!) to interpret it as FORMAT_STRING (e.g. with **@** symbol being set to text)?

**Comment by MarkBaker** [comment]
The recommended solution is to create your own cell binder (extending the default binder) that defines how that particular value should be stored

**Comment by Quix0r** [comment]
Okay.

**Comment by Quix0r** [comment]
The problem here is that the format is not always valid. Sometimes they event send numbers with words like "mother" or "phone" in it. So filtering invalid out would result in many rows being dropped. :-(

Any ideas how can I pre-define formats for each column?

**Comment by Quix0r** [comment]
@MarkBaker wrote:
> The recommended solution is to create your own cell binder (extending the default binder) that defines
> how that particular value should be stored... you might also want to get it to handle that date format as
> well
Yes, also Excel/LibreCalc don't have German date (only ISOs?) and never a data format "phone number". So I have to write my own value binder. Okay, but how can I prefine, e.g. column X is "phone" (custom format) and Y is "date" and then validate if the data matches the given format?

**Comment by Quix0r** [comment]
I think I have an idea:

- add helper field e.g. $columnFormats in value binder
- pre-set data type (from class `DataType`) per column/worksheet in helper field (through setter, of course)
- in bindValue() check if a format is set, if so use it for validation of value and bind it with correct format

**Comment by MarkBaker** [comment]
I wrote this quickly and tested against PHPExcel before realising that I should have used PHPSpreadsheet; but it should be easy enough for you to convert it:

```
$columnBindings = [
    'C' => function($cell, $value) {
                $cell->setValueExplicit($value);
                return true;
            },
    'E' => function($cell, $value) {
                $excelDateValue = PHPExcel_Shared_Date::PHPToExcel(DateTime::createFromFormat('d.m.Y', $value));
                $cell->setValueExplicit($excelDateValue, PHPExcel_Cell_DataType::TYPE_NUMERIC);
                $cell->getWorksheet()->getStyle($cell->getCoordinate())
                    ->getNumberFormat()->setFormatCode($formatCode);
                return true;
            },
];

class PHPExcel_Cell_CustomValueBinder extends PHPExcel_Cell_DefaultValueBinder implements PHPExcel_Cell_IValueBinder {
    protected $bindings;

    public function __construct(array $bindings = []) {
        $this->bindings = $bindings;
    }

    public function bindValue(PHPExcel_Cell $cell, $value = null)
    {
        if (isset($this->bindings[$cell->getColumn()])) {
            return $this->bindings[$cell->getColumn()]($cell, $value);
        }
        // Not bound yet? Use parent...
        return parent::bindValue($cell, $value);
    }
}

PHPExcel_Cell::setValueBinder( new PHPExcel_Cell_CustomValueBinder($columnBindings) );

echo date('H:i:s') , " Read from CSV format" , EOL;
$callStartTime = microtime(true);
$objReader = PHPExcel_IOFactory::createReader('CSV')->setDelimiter(';')
                                                    ->setEnclosure('"')
                                                    ->setSheetIndex(0);
$objPHPExcelFromCSV = $objReader->load('test.csv');
```

**Comment by Quix0r** [comment]
Thank you for sharing it. :-) I may give it a try when my high priority task is finished.

**Comment by Quix0r** [comment]
I would rewrite it a bit so not-found bindings are being "cached" ($bindings is something like an in-progress cache), too.

**Comment by PowerKiKi** [comment]
It does not seems to an issue with PhpSpreadsheet per see, but rather a question on how to use it. So I close it, but feel free to keep the discussion going...
