### ISSUE TITLE
Wrong timezone in ODS Reader

### ISSUE THREAD

**Issue by Zluka52** [PHPOffice/PhpSpreadsheet#559]
https://github.com/PHPOffice/PhpSpreadsheet/blob/c96e2dae02b49d1bc56970d4c44161a57ec3f303/src/PhpSpreadsheet/Reader/Ods.php#L259

Why use Europe/London timezone, it have DST. I suggest change it to UTC.
Already have issue with wrong timestamps from date/time cells.

**Comment by oleibman** [comment]
ODS Reader no longer makes any assumptions about timezone.
