### ISSUE TITLE
Secondary y-axis not available in PHP Spreadsheet

### ISSUE THREAD

**Issue by rf1234** [PHPOffice/PhpSpreadsheet#560]
This is:

```
- [ ] a bug report
- [ x ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
PHP Spreadsheet should be able to handle a secondary Y axis.

### What is the current behavior?
It is not possible to define a secondary Y axis.

### What are the steps to reproduce?
Somebody has already posted a solution for PHP Excel which wasn't implemented because PHP Excel is deprecated. Could you integrate the feature based on this post please:
https://github.com/PHPOffice/PHPExcel/pull/1037

### Which versions of PhpSpreadsheet and PHP are affected?
The current version

**Comment by rf1234** [comment]
Because I can't wait for a fix I have adapted Porrapat's fix to PHP Spreadsheet and it works. But of course it is hard coded ... would be better if it was integrated into the standard. If you need the code just let me know - and tell me how to post it please.

**Comment by PowerKiKi** [comment]
Consider contributing a PR with the new code to increase the change of
seeing this integrated

**Comment by rf1234** [comment]
I guess that requires I use github as version control solution which I currently don't. For your convenience I have attached the files that I changed and an example that I created. All is based on Ro
[FilesSecondaryAxis.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/2127523/FilesSecondaryAxis.zip)
[FileWriterXlsx.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/2127524/FileWriterXlsx.zip)

**Comment by qdkid** [comment]
Followed rf1234's codes, merge with current version 1.15.0 and create a patch
[chart_2nd_y_axis.patch.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/5557335/chart_2nd_y_axis.patch.zip)

rf1234 uploaded file has a test sample as well.
