### ISSUE TITLE
Line around charts should be removed

### ISSUE THREAD

**Issue by rf1234** [PHPOffice/PhpSpreadsheet#562]
This is:

```
- [ ] a bug report
- [x ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior
charts shouldn't have a line around them. This looks ugly and also unprofessional. It should be possible to remove the line or to never have a line around a chart:

### What is the current behavior?
The line cannot be removed. I use a hard coded solution to get rid of it.

### What are the steps to reproduce?

This is my hard coded fix in "Chart.php" in the "Xlsx" folder starting line 101 right before
$this->writePrintSettings($objWriter);
```php
<?php
//Roland Finke: Remove shape outline of chart
        $objWriter->startElement('c:spPr');
            $objWriter->startElement('a:ln');
                $objWriter->startElement('a:noFill');
                $objWriter->endElement();
            $objWriter->endElement();
        $objWriter->endElement();
        //Roland Finke: end
```

**Comment by oleibman** [comment]
Easily accomplished, reopening.
