### ISSUE TITLE
Could not open CSV files with "<a href" inside

### ISSUE THREAD

**Issue by ltressens** [PHPOffice/PhpSpreadsheet#564]
This is:

```
- [√] a bug report
```

### What is the expected behavior?

CSV file is opened by PhpSpreadsheet

### What is the current behavior?

An Exception is raised

### What are the steps to reproduce?

Try to open a CSV file with "<a href" inside.

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Reader\Csv();
$spreadsheet->setDelimiter(';');
$spreadsheet->setEnclosure('"');
$spreadsheet->load('test.csv');

// test.csv contains :
// "Column A";"<a href=''>Link</a>";"Column C"
```

### Which versions of PhpSpreadsheet and PHP are affected?

PHP 5.6.33 / PhpSpreadsheet 1.2.1
PHP 7.1.16 / PhpSpreadsheet 1.2.1

**Comment by PowerKiKi** [comment]
I just realized you use and outdated version. Upgrade to at least 1.4.0 to get the fix.
