### ISSUE TITLE
Number as text are showed as scientist

### ISSUE THREAD

**Issue by manuscle** [PHPOffice/PhpSpreadsheet#566]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Having a cell with number formatted as text without scientist value and the green triangle and warning about number storred as text.

### What is the current behavior?
If the number don't begin by 0, It is showed as scientist value without warning :
![image](https://user-images.githubusercontent.com/596562/41854827-70042de2-7891-11e8-973f-bfc398e32a06.png)

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$spreadsheet->setActiveSheetIndex(0);
$activeSheet = $spreadsheet->getActiveSheet();
// add code that show the issue here...
$activeSheet->getStyleByColumnAndRow(1, 1)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);
$activeSheet->setCellValueByColumnAndRow(1, 1, '44460046402180');
$activeSheet->getStyleByColumnAndRow(2, 1)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);
$activeSheet->setCellValueByColumnAndRow(2, 1, '0123456789');

// Write to xlsx, then open the file from windows file explorer
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.3.1

**Comment by manuscle** [comment]
This is still an issue

**Comment by oleibman** [comment]
This behavior is due to Excel, not to PhpSpreadsheet. PhpSpreadsheet can mitigate it by using:
```
$cell->setValueExplicit('44460046402180', DataType::TYPE_STRING);
```
Leaving issue closed, removing stale label.
