### ISSUE TITLE
Headers Already Sent

### ISSUE THREAD

**Issue by pr0ph0z** [PHPOffice/PhpSpreadsheet#567]
Hi there. I got error when uploaded my project to VPS.
![image](https://user-images.githubusercontent.com/17337978/41899775-7c15abb2-7957-11e8-846b-1e949d52b0ef.png)
It works successfully when i develop it in my computer. Any solution?

**Comment by MAKS-dev** [comment]
This is no issue of this package and you should ask such things on StackOverflow.
In your code you're sending information to the browser (e.g. echo) and want to set headers later (e.g. setcookie or header). This is not possible and you need to change your code.
Your develop environment probably uses output buffering (e.g. ob_start) that can be a workaround on this issue. So the easy solution can be to call ob_start() at the top of your code, not the best solution though.
