### ISSUE TITLE
Missing data labels in pie chart

### ISSUE THREAD

**Issue by diegomagikal** [PHPOffice/PhpSpreadsheet#568]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
When I load a spreadsheet (xlsx) that contains a pie chart with floating data labels and write in a new file, is expected that the data labels are shown.

### What is the current behavior?
The data labels are missing in the written file.

![image](https://user-images.githubusercontent.com/16082344/41977141-07655c56-79f5-11e8-808f-3fdf33bc4d2d.png)
![image](https://user-images.githubusercontent.com/16082344/41977206-252c448e-79f5-11e8-8a0d-a9513adf80eb.png)

### What are the steps to reproduce?
1. Create a xlsx file in Excel that contains a pie chart with data labels (so as the attached example);
2. Load file with $reader->load
3. Write a new file with $writer->save

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$inputFileName = "file.xlsx";
$inputFileType = 'Xlsx';
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($inputFileType);
$reader->setIncludeCharts(true);
$spreadsheet = $reader->load($inputFileName);

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, "Xlsx");
$writer->setIncludeCharts(true);
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header("Content-Disposition: attachment;filename='$inputFileName'");
header('Cache-Control: max-age=0');
		
$writer->save('php://output');

```
### Which versions of PhpSpreadsheet and PHP are affected?
1.3.1 and 7.0.10
[file.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2141392/file.xlsx)

**Comment by shahimclt** [comment]
@diegomagikal  Did you figure out a solution to this?

**Comment by diegomagikal** [comment]
@shahimclt No! My solution was to write a VBA code in a XLSM template to regenerate the chart when the file is open...

**Comment by arunharidas** [comment]
@diegomagikal Can you share some code doing that ?

**Comment by diegomagikal** [comment]
@arunharidas Just create a VBA Chart like https://stackoverflow.com/questions/18296535/defining-vba-chart-location and call it in `Auto_Open()` event:

```
Sub Auto_Open()
    Chart
End Sub
```
The file extension needs to be .XLSM

**Comment by sozik** [comment]
when output excel with some chart, I think some files are not created.
So, I just unzip the template excel, and copy the below setting files from the template, then overide the output file.
share my solution of the problem, wish this can help somebody.

```
        $xmlPath =  __DIR__ . '/excel';
        $zip = new ZipArchive;
        if ($zip->open($outputFile) === TRUE) {
            // add chart format file
            $zip->addFile($xmlPath . '/charts/chart1.xml', 'xl/charts/chart1.xml');
            // add below when needed
            $zip->addFile($xmlPath . '/charts/colors1.xml', 'xl/charts/colors1.xml');
            $zip->addFile($xmlPath . '/charts/style1.xml', 'xl/charts/style1.xml');
            $zip->addFile($xmlPath . '/charts/_rels/chart1.xml.rels', 'xl/charts/_rels/chart1.xml.rels');
            // some chart color styles
            $zip->addFile($xmlPath . '/theme/theme1.xml', 'xl/theme/theme1.xml');
            $zip->addFile($xmlPath . '/[Content_Types].xml', '[Content_Types].xml');
            $zip->close();
        }
```

**Comment by oleibman** [comment]
Data labels are now produced for pie charts.
