### ISSUE TITLE
Bug: Function type cell hex strings converting as an integer because of exponent 'e' character

### ISSUE THREAD

**Issue by almas** [PHPOffice/PhpSpreadsheet#569]
This is:

```
- [*] a bug report
```

### What is the expected behavior?
This is the cell function:
`=VLOOKUP($F$3:$F$7,'/Users/user/Documents/temp/カタログ呼称：品番.xlsx]番 (2)'!$C$7:$E$962,3,FALSE)`

This is current value of cell:
`1E3`

![screenshot](https://raw.githubusercontent.com/almas/myfiles/master/images/screenshots/phpspreadsheet_bug_569.png)

But /Users/user/Documents/temp/カタログ呼称：品番.xlsx file does not exits and value would not calculate again.

Expected current value "1E3" as string except "1000".

### What is the current behavior?
"1E3" converted to "1000".

### What are the steps to reproduce?
Prepare xlsx Excel file with cell like above example. Then just read like below.
```php
<?php
require __DIR__ . '/vendor/autoload.php';
$reader = IOFactory::createReader('Xlsx');
$spreadsheet = $reader->load($file_path);
var_dump($spreadsheet);
```

### Which versions of PhpSpreadsheet and PHP are affected?
Confirmed on Latest versions.

### Additional information
I tried to use custom value binder and did not have luck. Custom binder seems does not work with like this types of cells.

Now I'm copied and customized full code of Reader/Xlsx class and registering new class to IOFactory. 
Why castToBoolean, castToError, castToString, castToFormula functions of Xlsx are private? I think that those functions can be public. I do not want to copy full Xlsx class code and I just want to extend this class and override castToString function. But I think that it's just my solution. I think that this bug should be fixed.

This rejected pull request might help to fix this issue: https://github.com/PHPOffice/PhpSpreadsheet/pull/554.

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue without relying on an external Excel file. Your code is not minimal and should not rely on external file.

**Comment by almas** [comment]
First of all I’m not asking a question. I already solved my own problem. I just informing bug. All code you can redistribute bug is this. You just execute this and find value from car dump result and you can understand. What I am saying. Important part is not about code. It’s about special function cell. 
All Information I wrote here that I can give you guys. Sorry my contribution ended here.

**Comment by PowerKiKi** [comment]
Closing for incomplete information.
