### ISSUE TITLE
SUM Values from another sheet

### ISSUE THREAD

**Issue by ricardosaracino** [PHPOffice/PhpSpreadsheet#573]
This is: 
```
- [* ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
These all work

$sheet->getCellByColumnAndRow(2, $curRow)->setValue('=Locker!B3');
$sheet->getCellByColumnAndRow(2, $curRow)->setValue('=SUM(B3:B4)');
$sheet->getCellByColumnAndRow(2, $curRow)->setValue('=Locker!B3+Locker!B4+Locker!B5');

### What is the current behavior?
File is corrupted

### What are the steps to reproduce?
Try to access cell in another sheet
$sheet->getCellByColumnAndRow(2, $curRow)->setValue('=SUM(Locker!B3:Locker!B5)');

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
// This doesnt work
$sheet->getCellByColumnAndRow(2, $curRow)->setValue('=SUM(Locker!B3:Locker!B5)');
```

### Which versions of PhpSpreadsheet and PHP are affected?
"phpoffice/phpspreadsheet": "^1.2"

**Comment by MAKS-dev** [comment]
That won't even work in Excel itself.
You must use: **=SUM(Sheet2!B1:B4)**

**Comment by ricardosaracino** [comment]
Appreciate the response.

**Comment by ricardosaracino** [comment]
Non issue, i just didnt understand how to use excel
