### ISSUE TITLE
Formula Error: Wrong number of arguments for ROUNDUP() function: 1 given, 2 expected

### ISSUE THREAD

**Issue by Sorbing** [PHPOffice/PhpSpreadsheet#574]
I catch a Error: `Formula Error: Wrong number of arguments for ROUNDUP() function: 1 given, 2 expected` for formula `=ROUNDUP(SUM(E2:E10)) & " USD"`. Excel table imported from Google SpreadSheet.
How to fix it's problem. Thanks.

**Comment by Sorbing** [comment]
Problem is not resolved!

**Comment by MarkBaker** [comment]
The MS Excel `ROUNDUP()` function has 2 arguments, both are required. [https://support.office.com/en-gb/article/roundup-function-f8bc9b23-e795-47db-8703-db171d0c42a7]. My suggestion would be to fix the formula in the google spreadsheet
`=ROUNDUP(SUM(E2:E10), 0) & " USD"`
