### ISSUE TITLE
Reading the CSV file to make a mistake

### ISSUE THREAD

**Issue by huichen2017** [PHPOffice/PhpSpreadsheet#576]
Reading the CSV file to make a mistake.
Call to undefined function PhpOffice\PhpSpreadsheet\Reader\mime_content_type()

My version of PHP is 7.1.3

**Comment by vieraleonel** [comment]
Hi, I was having the same problem. In my case It wasn't enabled php_fileinfo extension. Check if that's your case.

**Comment by huichen2017** [comment]
Thanks！！

**Comment by Neeraj1005** [comment]
Call to undefined function PhpOffice\PhpSpreadsheet\Reader\mime_content_type()
I am getting the same error in form my cpanel server. But in localhost no error occurs.

**Comment by oleibman** [comment]
Fileinfo is a requirement for this package.
