### ISSUE TITLE
can't download/clone this repository

### ISSUE THREAD

**Issue by DivoPL** [PHPOffice/PhpSpreadsheet#577]
Hi

I'm a relatively new to GitHub but when I open https://github.com/PHPOffice/PhpSpreadsheet and click download Zip I expect repository to be packed and downloaded to my PC. It does not work (source file could not be read - Firefox). When I use desktop client (windows) to clone I get "Failed to connect to github.com port 443: Timed out". Am I missing something?

**Comment by tfaigle** [comment]
I had an issue too.  For some reason after I logged in I could down load it without problems.  I don't know if that will help but it's worth a shot.  FYI, I downloaded using Safari on a Mac

**Comment by MAKS-dev** [comment]
Download zip works without problems, no need to login. It's a local / user problem.
Besides that, this is a stackoverflow question and not an "issue".
Please close this one.

**Comment by DivoPL** [comment]
I’ll test on other machine. At least thanks for pointing me to some direction

**Comment by DivoPL** [comment]
I’ll test on other machine. At least thanks for pointing me to some direction

**Comment by PowerKiKi** [comment]
Downloading from GitHub will **not** work. Read http://phpspreadsheet.readthedocs.io/en/develop/#installation
