### ISSUE TITLE
Get style array from cell

### ISSUE THREAD

**Issue by creatorness** [PHPOffice/PhpSpreadsheet#580]
This is:

- [x ] a feature request

### What is the expected behavior?
Reverse funktion for applyFromArray to get the style array of a Cell

### What is the current behavior?
None existing.
I have to laboriously put together from the individual components of the style class.

### Which versions of PhpSpreadsheet and PHP are affected?
1.3.1

**Comment by PowerKiKi** [comment]
What would be the use case for this new feature?

**Comment by creatorness** [comment]
To get the style from an excel document quickly and save as configuration.
Then add it to a new document without having to worry about sorting everything out, which saves memory and time on a very large template document.

**Comment by Erwane** [comment]
Reopen and use case : 
I wan't to unit test my Spreadsheet generation and ... test styles to.

Tests can be very simple with a `PhpOffice\PhpSpreadsheet\Style::toArray()` method
Thanks

**Comment by PowerKiKi** [comment]
@Erwane, I'd accept a PR for this, as long as it is unit tested of course.

**Comment by oleibman** [comment]
Addressed by PR #1580.
