### ISSUE TITLE
Encoding issue from ASCII to UTF-8

### ISSUE THREAD

**Issue by badgujar-nagesh** [PHPOffice/PhpSpreadsheet#581]
There is a problem in conversion from the ASCII to UTF-8 for the string. The string is returning blank after the ```iconv()``` conversion when reading CSV.

In StringHelper.php

```
public static function sanitizeUTF8($value)
    {
        if (self::getIsIconvEnabled()) {
            $value = @iconv('UTF-8', 'UTF-8', $value);

            return $value;
        }

        $value = mb_convert_encoding($value, 'UTF-8', 'UTF-8');

        return $value;
    }
```

the iconv() returns blank string but if you add the //IGNORE at second parameter (output charset) then it will work. can you provide me any alternative of this or can you add //IGNORE.

**Comment by oleibman** [comment]
I believe this issue was fixed by PR #2994 in Aug. 2022. Removing stale label, leaving issue closed.
