### ISSUE TITLE
Composer issue: doctrine/annottations v1.6.0 requires php^7.1

### ISSUE THREAD

**Issue by cheinle** [PHPOffice/PhpSpreadsheet#582]
This is:

```
- [ ] a bug report

```

### What is the expected behavior?
Installation using composer on XAMPP using php v5.6

### What is the current behavior?
Composer error:
Your requirements could not be resolved to an installable set of packages.
Problem 1
-doctrine/annotations v1.6.0 requires php^7.1 -> your PHP version (5.6.23) does not satisfy that requirement

### What are the steps to reproduce?

>composer require phpoffice/phpspreadsheet

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet-1.3.1 and PHP 5.6.23

**Comment by Shade634** [comment]
You do know that php 5.6 is end of life by 31 Dec 2018?

**Comment by mintobit** [comment]
@Shade634 Does it make this behavior expected?
