### ISSUE TITLE
Importing Excel file with formula CONCAT() generates Formula Error

### ISSUE THREAD

**Issue by wgr-tomas** [PHPOffice/PhpSpreadsheet#583]
This is:

```
- [X ] a bug report
```

### What is the expected behavior?
Importing excel file with cell containing formula =CONCAT() to work as =CONCATENATE()
CONCAT is a alias(?) of CONCATNATE in Excel, it should also be supported in phpspreadsheet.

### What is the current behavior?
Generating error:
Formula Error: Unexpected ,

### What are the steps to reproduce?
Create an excel file with at least one cell containing for example:
=CONCAT(A1;B1)
and try to import/read it using "calculateFormulas"

### A possible solution to this
phpoffice\phpspreadsheet\src\PhpSpreadsheet\Calculation\Calculation.php
private static $phpSpreadsheetFunctions

Change this:
>         'CONCATENATE' => [
>             'category' => Category::CATEGORY_TEXT_AND_DATA,
>             'functionCall' => [TextData::class, 'CONCATENATE'],
>             'argumentCount' => '1+',
>         ],

To this:

>         'CONCAT' => [
>             'category' => Category::CATEGORY_TEXT_AND_DATA,
>             'functionCall' => [TextData::class, 'CONCATENATE'],
>             'argumentCount' => '1+',
>         ],
>         'CONCATENATE' => [
>             'category' => Category::CATEGORY_TEXT_AND_DATA,
>             'functionCall' => [TextData::class, 'CONCATENATE'],
>             'argumentCount' => '1+',
>         ],

**Comment by oleibman** [comment]
CONCAT was added with PR #608 soon after this issue was opened.
