### ISSUE TITLE
Column limit exceeded when reading a file and then saving it.

### ISSUE THREAD

**Issue by SamMousa** [PHPOffice/PhpSpreadsheet#584]
This is:

```
- [X] a bug report
```

### What is the expected behavior?
Excel file should open in LibreOffice and Excel without warnings.

### What is the current behavior?
I get a warning about column size exceeding the sheet limit in LibreOffice. Excel gives another warning.

### What are the steps to reproduce?
1. Make sure your machine has LibreOffice installed (the test script uses `soffice` commandline).
2. Run the script below.

```php
<?php


use PhpOffice\PhpSpreadsheet\IOFactory;

require 'src/vendor/autoload.php';

$testFile = 'src/vendor/phpoffice/phpspreadsheet/samples/Reader/sampleData/example1.xls';

// CONVERSION WITH PHPSPREADSHEET
$writer = IOFactory::createWriter(IOFactory::load($testFile), 'Xlsx');
$testFile1 = tempnam(sys_get_temp_dir(), 'test') . '.xlsx';
$writer->save($testFile1);

// CONVERSION WITH LIBREOFFICE
passthru('soffice --headless --convert-to xlsx --outdir ' . sys_get_temp_dir() . ' ' . $testFile);
$testFile2 = sys_get_temp_dir() . '/' . basename($testFile) . 'x';

foreach([$testFile1, $testFile2] as $file) {
    $writer = IOFactory::createWriter(IOFactory::load($file), 'Xlsx');
    $outFile = strtr($file, ['.xlsx' => '-output.xlsx']);
    $writer->save($outFile);
    echo "Created $outFile from $file\n";
}
```

3. Confirm that:
- The scripts executes without error.
- One of the created XLSX files throws error(s) when opening in Calc or MS Excel.

### Which versions of PhpSpreadsheet and PHP are affected?
1.3.1 on PHP 7.2

**Comment by SamMousa** [comment]
Bump

**Comment by tlesne** [comment]
I've the same problem with an existing XLSX file.

**Comment by SamMousa** [comment]
..

**Comment by akondas** [comment]
Any ideas?

**Comment by SamMousa** [comment]
I  think this project is dead..

**Comment by akondas** [comment]
```
Latest commit bf00f0c  8 days ago
```

:thinking: so probably not

**Comment by akondas** [comment]
This can help:
```php
$reader->setReadDataOnly(true);
```
but then we lose style :disappointed:

**Comment by Vitaliy-Svinchyak** [comment]
I have the same problem

**Comment by MarkBaker** [comment]
Believed resolved

**Comment by yar3333** [comment]
Have the same problem on v1.9.0. Read xlsx, some changes and save. Result: warning about limits when opening in LibeOffice Calc.

**Comment by yar3333** [comment]
I see next 
![1](https://user-images.githubusercontent.com/900330/64525772-4149cc80-d30a-11e9-8b88-e6904c892597.png)

**Comment by yar3333** [comment]
My be this is a problem? But I don't found a way to remove bad keys from rowDimansions/colDimensions.

**Comment by yar3333** [comment]
![1](https://user-images.githubusercontent.com/900330/64526073-05633700-d30b-11e9-814c-6b516f467051.png)

**Comment by yar3333** [comment]
I can approve, that this is a problem. I fix this in my project via reflection (remove bad keys). @PowerKiKi, can you reopen this issue?

**Comment by tstaylor7** [comment]
LibreOffice Calc only supports [1024 columns](https://wiki.documentfoundation.org/Faq/Calc/022), but it saves the last column of each sheet with a [max of 1025,](https://cgit.freedesktop.org/libreoffice/core/tree/sc/source/filter/oox/worksheethelper.cxx?h=libreoffice-6.3.2.2#n764) which PhpSpreadsheet [reads as-is](https://github.com/PHPOffice/PhpSpreadsheet/blob/1.8.2/src/PhpSpreadsheet/Reader/Xlsx/ColumnAndRowAttributes.php#L134).

PhpSpreadsheet should probably subtract 1 from the last column, but a simple workaround is to load the spreadsheet with a [Read Filter](https://github.com/PHPOffice/PhpSpreadsheet/blob/1.8.2/docs/topics/reading-files.md#reading-only-specific-columns-and-rows-from-a-file-read-filters):

```php
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Reader\IReadFilter;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;

class LOReadFilter implements IReadFilter
{
    public function readCell($column, $row, $worksheetName = '') {
        if (Coordinate::columnIndexFromString($column) > 1024) {
            return false;
        }
        return true;
    }
}

$reader = IOFactory::createReader('Xlsx');
$reader->setReadFilter(new LOReadFilter());
$spreadsheet = $reader->load('./sampleData/example1.xls');
```

**Comment by siarheipashkevich** [comment]
@yar3333 did you resolve your problem?

**Comment by yar3333** [comment]
@siarheipashkevich Yes. I wrote two functions to remove bad indexes:
```php
function removeTooHighColumnDimensions($worksheet)
{
    $maxColumnIndex = Coordinate::columnIndexFromString($worksheet->getHighestDataColumn());

    $columnDimensions = $worksheet->getColumnDimensions();
    foreach ($columnDimensions as $col => $dimension) {
        if (Coordinate::columnIndexFromString($col) > $maxColumnIndex) {
            unset($columnDimensions[$col]);
        }
    }

    $reflector = new ReflectionClass($worksheet);
    $property = $reflector->getProperty('columnDimensions');
    $property->setAccessible(true);
    $property->setValue($worksheet, $columnDimensions);
}

function removeTooHighRowDimensions()
{
    $maxRowIndex = $worksheet->getHighestDataRow();

    $rowDimensions = $worksheet->getRowDimensions();
    foreach ($rowDimensions as $row => $dimension) {
        if ($row > $maxRowIndex) {
            unset($rowDimensions[$row]);
        }
    }

    $reflector = new ReflectionClass($worksheet);
    $property = $reflector->getProperty('rowDimensions');
    $property->setAccessible(true);
    $property->setValue($worksheet, $rowDimensions);
}

```

**Comment by siarheipashkevich** [comment]
@yar3333 and you call these methods after loading file?

**Comment by yar3333** [comment]
@siarheipashkevich Yes. Load file and call these functions for your sheet(s).

**Comment by siarheipashkevich** [comment]
@yar3333 thanks, I'll try your solution

**Comment by Dreamer0x01** [comment]
> 
> ```
> function removeTooHighColumnDimensions($worksheet)
> {
> //....
> }
> ```

This solution is not work for me... Warning still showing :(

But this case works fine:

> ```
> class LOReadFilter implements IReadFilter
> {
>     //.....
> }
> ...
> ```

However, the number of columns had to be reduced to an even smaller number in order to work faster.
