### ISSUE TITLE
Password protect excel not working for multiple sheet

### ISSUE THREAD

**Issue by pravinkhot** [PHPOffice/PhpSpreadsheet#585]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

1. Document level security should not allow me to view excel with out entering password.
2. While exporting excel with password for multiple sheet its allow me to edit sheets but for single sheet it is working fine.

### What is the current behavior?

1. Document level security is not working it allow me to view excel with out entering password.
2. While exporting excel with password for multiple sheet it should not allow me to edit sheets.

### What are the steps to reproduce?

Create or download Excel with multiple sheet & password .

### Which versions of PhpSpreadsheet and PHP are affected?
Latest

**Comment by lugzdnas** [comment]
still looking for the same.
