### ISSUE TITLE
Missing getParent/getWorksheet() in Row class

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PhpSpreadsheet#59]
In constructor of `Row` class `Worksheet` is given as parameter and set in object but not exposed to outside. Currently I may need a simple getter to get the worksheet's title.

Or is there another way of getting a worksheet instance from a row instance? What I want to do is this:
```
// Create cache key
$cacheKey = sprintf(
    'column:%s:%s:%d:%s',
    pathinfo($fqfn, PATHINFO_BASENAME),
    $rowInstance->getWorksheet()->getTitle(),
    $rowInstance->getRowIndex(),
    $value
);
```

**Comment by PowerKiKi** [comment]
I suppose it would make sense and be coherent with the rest of the code. Would you also rename the parameter and property `parent` into `worksheet` and make a PR for that please ?

**Comment by Quix0r** [comment]
Okay.
