### ISSUE TITLE
column width gets lost

### ISSUE THREAD

**Issue by pYr0x** [PHPOffice/PhpSpreadsheet#596]
This is:

- [ x ] a bug report

### What is the expected behavior?
i have a template file that i created before in Excel. in that file i changed the column width of some columns.
in PHP i create a reader with `IOFactory::load($templateFile);`.
i send the same xlsx file to the php output buffer and opened the file in Excel again.
now the column width consolidated to 64px for all columns.

### What is the current behavior?
the new created file from the template should have the same column width as the template file itself.
in the old phpExcel (https://github.com/PHPOffice/PHPExcel) it works

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

 $spreadsheet = IOFactory::load($templateFile);

$objWriter = IOFactory::createWriter($spreadsheet, "Xlsx");

header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Content-Disposition: attachment;filename="Foo.xlsx"');
            header('Cache-Control: max-age=0');

$objWriter->save("php://output");
```

### Which versions of PhpSpreadsheet and PHP are affected?
"phpoffice/phpspreadsheet": "^1.3"

**Comment by pYr0x** [comment]
But that’s where the bug take place

**Comment by mrlukowski** [comment]
Hey,
I have also problem with column width lost. I'm creating xlsx file with multiple sheet (adding by $phpExcelObject->addExternalSheet($sheet)).
When i'm saving php excel ->  writer have setted column dimensions and save file.
After that load and only  second worksheetcollection has columnDimensions. First workSheetCollection havo no column dimensions setted :(

`   	

        $phpExcelWriter = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($phpExcelObject, 'Xlsx');
   	$phpExcelWriter->save($fileName);

        $tmpObj1 = \PhpOffice\PhpSpreadsheet\IOFactory::load($fileName);
        // tmpObj1 no columnDimensiond on worksheetCollection 0`

![obraz](https://user-images.githubusercontent.com/26492007/42802077-027286d0-89a2-11e8-94e9-ad3e64ee332c.png)

after load
![obraz](https://user-images.githubusercontent.com/26492007/42802122-2f01b888-89a2-11e8-8ae2-b75b84798a0d.png)

Which versions of PhpSpreadsheet and PHP are affected?

"phpoffice/phpspreadsheet": "^1.3"

I think problem is in Loader not saver, old ver phpexcel was on the same files working fine and read columndimensions on worksheet 0.
