### ISSUE TITLE
I output PDF from the Excel template, but something like an unnecessary cell is drawn. 

### ISSUE THREAD

**Issue by okayu8** [PHPOffice/PhpSpreadsheet#597]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I think that you do not want to output PDF from the Excel template, eliminate the collapse of the layout, and do not want to draw extra cells.

### What is the current behavior?
I made an Excel template with blank paper and did PDF output without rendering anything.
However, something like a cell is drawn in the output file.

### What are the steps to reproduce?
A file is attached to this URL.
http://firestorage.com/download/c7861b381bbd27d3c2ee94bd5554c6d326d7e230

### Which versions of PhpSpreadsheet and PHP are affected?
PHP: 7.0
PhpSpreadSheet: 1.0.0-beta
mpdf: 6.1.0

**Comment by PowerKiKi** [comment]
First of all, upgrade to latest PhpSpreadsheet. If it persists provide a mvce.
