### ISSUE TITLE
Is HLOOKUP supported?

### ISSUE THREAD

**Issue by donaldallen** [PHPOffice/PhpSpreadsheet#599]
The documentation for functions lists HLOOKUP as Not yet implemented. However, it looks like there is an HLOOKUP function in LookupRef.php:

https://github.com/PHPOffice/PhpSpreadsheet/blob/c96e2dae02b49d1bc56970d4c44161a57ec3f303/src/PhpSpreadsheet/Calculation/LookupRef.php#L739

Is this just a case of the documentation not being updated?

**Comment by PowerKiKi** [comment]
This is correct, doc is not up to date. I'm thinking we should automate the doc update process to avoid this kind of issue...

**Comment by oleibman** [comment]
HLOOKUP is supported, and documentation is now automatically updated.
