### ISSUE TITLE
Get a notice while try to load import file

### ISSUE THREAD

**Issue by SimonJan** [PHPOffice/PhpSpreadsheet#602]
### While I'm trying to load import file (xlsx) I get a notice:
```
Notice: Undefined index: in ../phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 1757
```
**It's only happen if the import's file have a image column - that inserted by "Pickture from file"**

Thanks

**Comment by SimonJan** [comment]
[test-with-image.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2381538/test-with-image.xlsx)
Sorry, not yet. This is file I used to import. When I tried to read the file:
`$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($inputFileType);
$spreadsheet = $reader->load($import_file);`
( I tested on v1.3, 1.3.1 and 1.4)

I got these errors:
`( ! ) Notice: Undefined index: in /homectl/wmec/live/..../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 1702
--
( ! ) Warning: PhpOffice\PhpSpreadsheet\Reader\Xlsx::getArrayItem(): Node no longer exists in /homectl/wmec/live/.../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 2328
---
( ! ) Warning: PhpOffice\PhpSpreadsheet\Reader\Xlsx::getArrayItem(): Node no longer exists in /homectl/wmec/live/.../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 2328
---
( ! ) Fatal error: Uncaught Error: Call to a member function attributes() on null in /homectl/wmec/live/.../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 1724
---
( ! ) Error: Call to a member function attributes() on null in /homectl/wmec/live/.../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 1724
`
Thanks

**Comment by damijanc** [comment]
This file is super strange. It contains links to other files. I believe this is not supported in the library.

**Comment by SimonJan** [comment]
Ok thanks @damijanc.
But in that case, can we with null value (or skip/pass it ) without errors?
If yes, can you update on the new version?

Thanks

**Comment by damijanc** [comment]
I am not a maintainer of the library. The best way to get it fixed is to provide a pull request.

**Comment by oleibman** [comment]
No further notices loading supplied file. Leaving issue closed, removing stale label.
