### ISSUE TITLE
Consider excluding samples/ from the final archive

### ISSUE THREAD

**Issue by dkarlovi** [PHPOffice/PhpSpreadsheet#605]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

Please consider [excluding `samples/` from the archive generated by Github](http://www.pixelite.co.nz/article/using-git-attributes-exclude-files-your-release/) (and used by Composer, etc) as currently it makes more than 50% of the size of the unpacked archive and might go totally unnoticed by the developer.

Also, it makes using tools like [`box`](https://github.com/humbug/box) a bit more cumbersome out of the box (heh).

### What is the expected behavior?
A minimal archive.

### What is the current behavior?
An archive which 50%+ consists of `samples/`.

**Comment by oleibman** [comment]
The final archive has excluded samples/ for over 5 years now. Removing stale label, keeping issue closed.
