### ISSUE TITLE
Create xls from template file generate 94 pages of file !

### ISSUE THREAD

**Issue by gabrielgmm** [PHPOffice/PhpSpreadsheet#615]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Create an excel file using template and, when you click on print, it prints only one page

This problem happens only in MS Excel, in Libreoffice it works ok

### What is the current behavior?

Generate an xls file, however when opening it in MS Excel and clicking to print, it appears 94 pages to print
### What are the steps to reproduce?

Generate a xls file from any template
Try to open a file created in MS Excel

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by konovalovk** [comment]
I have the same issue - when open template with one page to print, do nothing and just output - generated document has over 1000 pages which are empty. I supposed it was adding data to sheet issue, but clean template gives the same. BTW converting xlsx to pdf with libreoffice 6 gives one page again.

**Comment by konovalovk** [comment]
1.4.0 is also affected
