### ISSUE TITLE
Unable to convert an excel to pdf using custom dompdf implementation

### ISSUE THREAD

**Issue by judemanutd** [PHPOffice/PhpSpreadsheet#617]
This is:

```
- [ x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
I have installed PhpSpreadsheet and dompdf successfully using composer. My requirement is that I need to convert an excel sheet into pdf, I got it working using the default settings, this is the code I have used.

```
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Writer\Csv;
use PhpOffice\PhpSpreadsheet\Exception;
use PhpOffice\PhpSpreadsheet\IOFactory;
use \PhpOffice\PhpSpreadsheet\Writer\Pdf\Dompdf;

$spreadsheet = new Spreadsheet();
 try {
    $sheet = $spreadsheet->getActiveSheet();

    // code to fill in the data

    $spreadsheet->getActiveSheet()->fromArray(
        $data,                // The data to set
        NULL,        // Array values with this value will not be set
        'A2'         // Top left coordinate of the worksheet range where
    );
} catch (Exception $e) {
}

$writer = new Xlsx($spreadsheet);

try {
    IOFactory::registerWriter("PDF", Dompdf::class);
    $pdfwriter = IOFactory::createWriter($spreadsheet, 'PDF');
    $pdfwriter->save($filepath . 'pdf_test.pdf');
} catch (\PhpOffice\PhpSpreadsheet\Writer\Exception $e) {
}
```

I have skipped out code for brevity, this code works fine and generates a pdf file, I require the pdf to be printed in landscape mode, for that the docs mention a Custom implementation or configuration of the pdf library.

According to the docs

A `My_Custom_TCPDF` is created which extends TCPDF

 so I created a file called `PDFBase_DOMPDF` that looks like this

```
use Dompdf\Dompdf;

class PDFBase_DOMPDF extends Dompdf
{

}
```

Then in the docs a class  called `My_Custom_TCPDF_Writer` which extends `\PhpOffice\PhpSpreadsheet\Writer\Pdf\Tcpdf` is created

And I have created a file called `PDFBase_Writer` that looks like this.

```
use PhpOffice\PhpSpreadsheet\Writer\Pdf\Dompdf;

class PDFBase_Writer extends Dompdf
{
    protected function createExternalWriterInstance()
    {
        $instance = new PDFBase_DOMPDF();
        $instance->setPaper('A4', 'landscape');
        return $instance;
    }

}
```
The docs go on to mention the line `\PhpOffice\PhpSpreadsheet\IOFactory::registerWriter('Pdf', MY_TCPDF_WRITER::class);` where exactly does `MY_TCPDF_WRITER` come from?

In my file I modified the original code to use the new pdf class so the line changed to this.

`IOFactory::registerWriter("PDF", PDFBase_Writer::class);`

### What is the expected behavior?
Generate a pdf from the excel file.

### What is the current behavior?

The problem is I get an exception with the following error

Registered writers must implement PhpOffice\PhpSpreadsheet\Writer\IWriter

### What are the steps to reproduce?
As mentioned above

### Which versions of PhpSpreadsheet and PHP are affected?

```
"require": {
    "php": ">=7.1.9",
    "phpoffice/phpspreadsheet": "1.3.1",
    "dompdf/dompdf": "v0.8.2"
  }
```

**Comment by judemanutd** [comment]
@rf1234  thanks but that didn't really work out as planned, it still printed the tables on the pdf horizontally rather than vertically

**Comment by rf1234** [comment]
I think we have a misunderstanding here. Page orientation doesn’t change the orientation of the table. It changes the orientation of the page. A horizontal table doesn’t become vertical. Why would you use landscape page orientation? Because your table is too wide to fit on a portrait page.

**Comment by judemanutd** [comment]
Yes correct, the table is too wide to fit horizontally so my understanding was taking a basic spreadsheet and rendering it vertically on the pdf would work but I'm guessing that's not the way to go. Could you suggest a different approach to this.

**Comment by rf1234** [comment]
Well, my code above works. At least with Mpdf. I would try with Mpdf or Tcpdf. Doesn’t cost you anything and you can use all three of them in parallel. Just try and see. If you just use them in their standard version via PHPSpreadsheet you don’t need to know anything about them either. Use what works!

**Comment by judemanutd** [comment]
This is the code I have and it doesn't seem to be working, I've edited certain parts out for brevity

```
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Exception;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;
use PhpOffice\PhpSpreadsheet\IOFactory;

$spreadsheet = new Spreadsheet();

            try {
                $ws = $spreadsheet->getActiveSheet();
                $ws->getPageSetup()->setOrientation(PageSetup::ORIENTATION_LANDSCAPE);
                $ws->getPageSetup()->setFitToWidth(1);
                $ws->getPageSetup()->setFitToHeight(1);
                $ws->setShowGridlines(false);

                $spreadsheet->getActiveSheet()->fromArray(
                    $data,                // The data to set
                    NULL,        // Array values with this value will not be set
                    'A2'         // Top left coordinate of the worksheet range where
                );

                $writer = IOFactory::createWriter($spreadsheet, 'Mpdf');
                $writer->save($filepath . "05featuredemo.pdf");

            } catch (Exception $e) {
                return [
                    'flag' => true,
                    'path' => $e
                ];
            }
```

This still ends up printing a pdf with a horizontal table rather than a vertical one.

**Comment by rf1234** [comment]
Yes the table should be horizontal. I mean you want to be able to read it right? But the paper should be landscape so that its width hopefully fits on the page. I know there are crappy pdfs around which you can't read before turning the page by 90 degrees. But that's not what you want do you?
[Form_portrait.pdf](https://github.com/PHPOffice/PhpSpreadsheet/files/2259388/Form_portrait.pdf)
[The_same_form_landscape.pdf](https://github.com/PHPOffice/PhpSpreadsheet/files/2259389/The_same_form_landscape.pdf)



I attached two simple forms: One form is created using ORIENTATION_PORTRAIT. One form is created using ORIENTATION_LANDSCAPE. In both cases the form looks exactly the same. And the form fits on portrait paper anyway. The landscape form however needs two pages because it is too long for one landscape page.

**Comment by HakobArakelyan** [comment]
The Same Issue is with Mpdf. I think it does not matter which writer class you are extending because a result is the same as mentioned above.

**Comment by oleibman** [comment]
All 3 PDF writers can now output in either landscape or portrait mode without having to resort to a custom class. as suggested above using the PhpSpreadsheet `PageSetup` class. I believe that only Mpdf can switch orientation from page to page in the same document; getting Dompdf or Tcpdf to do that would require enhancements to those projects. Leaving issue closed, removing stale label.
