### ISSUE TITLE
DataValidation->setAllowBlank(false) not working

### ISSUE THREAD

**Issue by cainaleaouk** [PHPOffice/PhpSpreadsheet#621]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Cell validation to prevent it from blank (empty) value. And show validation error popup.

### What is the current behavior?
It does not prevent the cell value from being empty. And does not show the validation error popup.
***OBS: All the other validation options work as intended.**

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Protection;
use PhpOffice\PhpSpreadsheet\Cell\DataValidation;

function setValidation($sheet, $cellCord) {
    $sheet->getCell($cellCord)->getDataValidation()
        ->setAllowBlank(false)
        ->setType(DataValidation::TYPE_WHOLE)
        ->setErrorStyle(DataValidation::STYLE_STOP)
        ->setShowErrorMessage(true)
        ->setErrorTitle('Validation Error')
        ->setError('This cell value must be a whole number');
}

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

// Set headers
$sheet->setCellValue("A1", "field1");
$sheet->setCellValue("B1", "field2");

$sheet->setCellValue("A2", 2);
$sheet->setCellValue("B2", 3);

// Set number validation for field1 and field2
setValidation($sheet, "A2");
setValidation($sheet, "B2");

// field1
$sheet->getStyle('A2')->getProtection()
    ->setLocked(Protection::PROTECTION_UNPROTECTED);
// field2
$sheet->getStyle('B2')->getProtection()
    ->setLocked(Protection::PROTECTION_UNPROTECTED);

$sheet->getProtection()->setSheet(true);

$path = '/tmp/test.xlsx';

$writer = new Xlsx($spreadsheet);
$writer->save($path);
```

### Which versions of PhpSpreadsheet and PHP are affected?
```
"phpoffice/phpspreadsheet": "1.3.1"
PHP 7.1.14 (cli) (built: Feb  7 2018 18:33:30) ( NTS )
Zend Engine v3.1.0```

**Comment by oleibman** [comment]
I would say Excel's implementation of "ignore blanks" is not working correctly. PhpSpreadsheet will set the xml value appropriately. But, when I enter your data validation criteria manually into Excel, it seems to accept a null value whether or not I've ticked the "ignore blanks" box.

I thought maybe you could use a horrible custom formula like:
```
=AND(ISNUMBER(INDIRECT(ADDRESS(ROW(),COLUMN()))),MOD(INDIRECT(ADDRESS(ROW(),COLUMN())),1)=0)
```
But Excel claims the formula is invalid, without explaining why. It accepts each of the ISNUMBER and MOD parts on their own, but not when you AND them together. And that's about all the time I have for this problem.
