### ISSUE TITLE
problem for copying xlsx file with picture in header

### ISSUE THREAD

**Issue by amoulin974** [PHPOffice/PhpSpreadsheet#624]
This is a bug report

### What is the expected behavior?
I would like copy a spreadsheet wich picture (jpg) in header

### What is the current behavior?
I have the copy but if i open it i have an error message : 
Excel a terminé la validation et la réparation de niveau fichier. Certaines parties du classeur peuvent avoir été réparées ou abandonnées.
Partie supprimée: Forme de dessin.
Partie supprimée: Options d'impression.
Partie supprimée: Forme de dessin.
Partie supprimée: Forme de dessin.
Partie supprimée: Options d'impression.
Partie supprimée: Forme de dessin.

If I unzip original file I find my picture in
xl\media\**image1**.jpeg

And if I unzif the copy file I find a picture in
xl\media\**image11**.jpeg

I don't know if is it important but the name of picture are not equal...

code that show the issue here...

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$fichier=$_FILES["qqfile"]["tmp_name"];
 $reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($file);
  $reader->setReadDataOnly(false);
$spreadsheet = $reader->load($file);
$writer = new Xlsx($spreadsheet);
$writer->save($name.".xlsx");

### Which versions of PhpSpreadsheet and PHP are affected?
"name": "phpoffice/phpspreadsheet",
            "version": "1.3.1",

**Comment by oleibman** [comment]
Issue seems resolved - see https://github.com/PHPOffice/PhpSpreadsheet/issues/1645#issuecomment-1813734201. Removing stale label, leaving issue closed.
