### ISSUE TITLE
Cell lost coordinate

### ISSUE THREAD

**Issue by ofeig** [PHPOffice/PhpSpreadsheet#625]
This is  a bug report

### What is the expected behavior?
Get the same coordinate.

### What is the current behavior?
Second call return:
Fatal error: Uncaught Error: Call to a member function getCurrentCoordinate() on null in .../PhpSpreadsheet/PhpSpreadsheet/Cell/Cell.php on line 144

### What are the steps to reproduce?

```php
<?php

$phpSpreadsheet = new PhpOffice\PhpSpreadsheet\Spreadsheet();
$activeSheet = $phpSpreadsheet->getActiveSheet();

$firstCell = $activeSheet->getCellByColumnAndRow(1, 1);
var_dump($firstCell->getCoordinate());
$secondCell = $activeSheet->getCellByColumnAndRow(2, 1);
var_dump($firstCell->getCoordinate());


### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.2.8 (cli) (built: Jul 19 2018 15:54:51) (NTS)
PhpSpreadsheet from develop branch (download 23th of May 2018)

**Comment by MarkBaker** [comment]
This is because calls to get a cell don't actually return a cell object directly, but a pointer (reference) to a cell object in the cache. Calls to get another cell change that pointer, so your `$firstCell`value is now pointing to the cell referenced by the second get cell call.

**Comment by netdoggy** [comment]
I faced the same problem after migrating from PHPExcel

`foreach ( $cellIterator as $Cell ) `
`// get other cell value`
`$indexName = $worksheet->getCell ( $Cell->getColumn () . '' . $headerRowIndex )->getFormattedValue ();`

`// Error: Call to a member function getCurrentCoordinate() on null in ../Cell/Cell.php:141`
`$Cell->getCoordinate ()`

I started doing `$Cell = clone $Cell;`
but I think it's a  dirty hack in this case :-/

phpoffice/phpspreadsheet 1.16
php 7.2.34

**Comment by oleibman** [comment]
Explanation has been provided. Removing stale label, leaving issue closed.
