### ISSUE TITLE
Using a Cache leads to inpredictable Crashes on larger Exports

### ISSUE THREAD

**Issue by boredom2** [PHPOffice/PhpSpreadsheet#626]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

using a simple Caching Mechnism like:
$pool=new \Cache\Adapter\Apcu\ApcuCachePool();
$simpleCache=new \Cache\Bridge\SimpleCache\SimpleCacheBridge($pool);
\PhpOffice\PhpSpreadsheet\Settings::setCache($simpleCache);

and building a SpreadSheet with a few thousand Rows always leads to:
"CANNOT SET CELL A1 WITH VALUE planestream.de: Cell entry A1 no longer exists in cache. This probably means that the cache was cleared by someone else."

This looks to me, like the Cache wasnt big enough or some other Problem of the Cache occured.
Are there any Ways to raise Caching Size or handle this Behaviour somehow? What is the best Caching Mechanism in your Opinion for larger Files - or should we remove the Cache at all?

### What is the current behavior?
The Cache should cache all Rows and PHPExcel should render them correctly.

### What are the steps to reproduce?

Without a Database, this is complicated. The current Example has 5k Rows with 12 Columns.

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet and PHP are affected?
latest

**Comment by madrussa** [comment]
We're also experiencing this issue:

```
PhpOffice\PhpSpreadsheet\Exception: Cell entry A3 no longer exists in cache. 
This probably means that the cache was cleared by someone else. in 
/...dirs.../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Cells.php:433
```

We're using Memcache as the cache, running on CLI and through Apache, same issue. 

Approx 54 sheets, 2 charts, 12 cols x 30 rows in each sheet. 10 cols x 24 row  in each sheet with conditional formatting.

**Comment by madrussa** [comment]
After some extra debugging and code review I have found that our default TTL on our cache was not long enough. I've increased it and now we are able to export the spreadsheet. I had a custom cache implementation which used the cache services of Laravel. 

@boredom2 You should check your APC settings to see if you have a TTL or Expiry time set. I'm going on a hunch your issue is similar to mine. You could always alter the SimpleCache object to apply a default TTL on save.

**Comment by PowerKiKi** [comment]
This is clearly documented, see https://phpspreadsheet.readthedocs.io/en/develop/topics/memory_saving/#beware-of-ttl

**Comment by znau** [comment]
I didn't use redis, but I used Mongo as the cache。
 
I have the same problem：

```
In Cells.php line 446:

  [PhpOffice\PhpSpreadsheet\Exception]
  Cell entry A1 no longer exists in cache. This probably means that the cache was cleared by someone else.
```

I read the source code and found the problem:

  cache/simple-cache-bridge   SimpleCacheBridge.php 

```
 public function set($key, $value, $ttl = null)
    {
      ..... 
``` 


 vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Collection\Cells.php

```
 private function storeCurrentCell(): void
    {
        if ($this->currentCellIsDirty && !empty($this->currentCoordinate)) {
            $this->currentCell->detach();

            $stored = $this->cache->set($this->cachePrefix . $this->currentCoordinate, $this->currentCell);
      ..... 
``` 



**ttl = null**      
However, this parameter is not passed at the place of the call，I didn't find a place to set the cache time by default。



this is my  solution ：


```

/**
 *
 * Class CacheBridge
 *
 * @package App\Tools\Cache
 */
class CacheBridge extends SimpleCacheBridge
{
    /**
     * @var int
     */
    protected $ttl = null;

    /**
     * CacheBridge constructor.
     *
     * @param \Psr\Cache\CacheItemPoolInterface $cacheItemPool
     * @param int $defaultTtl
     */
    public function __construct(CacheItemPoolInterface $cacheItemPool, int $defaultTtl = 3600)
    {
        parent::__construct($cacheItemPool);
        $this->ttl = $defaultTtl;
    }

    /**
     * {@inheritdoc}
     */
    public function set($key, $value, $ttl = null): bool
    {
        if ($this->ttl && is_null($ttl)) {
            $ttl = $this->ttl;
        }

        try {
            $item = $this->cacheItemPool->getItem($key);
            $item->expiresAfter($ttl);
        } catch (CacheInvalidArgumentException $e) {
            throw new InvalidArgumentException($e->getMessage(), $e->getCode(), $e);
        }

        $item->set($value);

        return $this->cacheItemPool->save($item);
    }
}

```


Who has a better way, welcome to share!

**Comment by znau** [comment]
I also found a place that was easy to ignore，


vendor\cache\mongodb-adapter\MongoDBCachePool.php       fetchObjectFromCache  function 


```
/**
     * {@inheritdoc}
     */
    protected function fetchObjectFromCache($key)
    {
        $object = $this->collection->findOne(['_id' => $key]);

        if (!$object || !isset($object->data)) {
            return [false, null, [], null];
        }

        if (isset($object->expiresAt)) {
            if ($object->expiresAt < time()) {
                return [false, null, [], null];
            }
        }

        return [
            true,
            $this->thawValue($object->data),
            $this->thawValue($object->tags),
            $object->expirationTimestamp,
        ];
    }

```

The    **$object**   returned result is not necessarily an object， According to the options, it may be **array**

**Comment by Kozin-br** [comment]
so what is the solution???

**Comment by omarfarukmiah** [comment]
> I didn't use redis, but I used Mongo as the cache。
> 
> I have the same problem：
> 
> ```
> In Cells.php line 446:
> 
>   [PhpOffice\PhpSpreadsheet\Exception]
>   Cell entry A1 no longer exists in cache. This probably means that the cache was cleared by someone else.
> ```
> 
> I read the source code and found the problem:
> 
> cache/simple-cache-bridge SimpleCacheBridge.php
> 
> ```
>  public function set($key, $value, $ttl = null)
>     {
>       ..... 
> ```
> 
> vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Collection\Cells.php
> 
> ```
>  private function storeCurrentCell(): void
>     {
>         if ($this->currentCellIsDirty && !empty($this->currentCoordinate)) {
>             $this->currentCell->detach();
> 
>             $stored = $this->cache->set($this->cachePrefix . $this->currentCoordinate, $this->currentCell);
>       ..... 
> ```
> 
> **ttl = null** However, this parameter is not passed at the place of the call，I didn't find a place to set the cache time by default。
> 
> this is my solution ：
> 
> ```
> 
> /**
>  *
>  * Class CacheBridge
>  *
>  * @package App\Tools\Cache
>  */
> class CacheBridge extends SimpleCacheBridge
> {
>     /**
>      * @var int
>      */
>     protected $ttl = null;
> 
>     /**
>      * CacheBridge constructor.
>      *
>      * @param \Psr\Cache\CacheItemPoolInterface $cacheItemPool
>      * @param int $defaultTtl
>      */
>     public function __construct(CacheItemPoolInterface $cacheItemPool, int $defaultTtl = 3600)
>     {
>         parent::__construct($cacheItemPool);
>         $this->ttl = $defaultTtl;
>     }
> 
>     /**
>      * {@inheritdoc}
>      */
>     public function set($key, $value, $ttl = null): bool
>     {
>         if ($this->ttl && is_null($ttl)) {
>             $ttl = $this->ttl;
>         }
> 
>         try {
>             $item = $this->cacheItemPool->getItem($key);
>             $item->expiresAfter($ttl);
>         } catch (CacheInvalidArgumentException $e) {
>             throw new InvalidArgumentException($e->getMessage(), $e->getCode(), $e);
>         }
> 
>         $item->set($value);
> 
>         return $this->cacheItemPool->save($item);
>     }
> }
> ```
> 
> Who has a better way, welcome to share!

Hello @znau ,

I followed your custom CacheBridge class but it's the same issue i am facing. 

> Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Exception: Cell entry A1 no longer exists in cache. This probably means > > that the cache was cleared by someone else. in 
>  vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Cells.php on line 426 

Even though i am following your example: $simpleCache = new CacheBridge($pool, 888888888);

Any idea how i can solve this issue?

**Comment by omarfarukmiah** [comment]
> so what is the solution???

Did you find any solution ?

**Comment by omar-faruk-sust** [comment]
> so what is the solution???

Hey @jet-desk and @znau , 

Did you find any solution for caching ?? I am having same issue for writing large amount of data.
