### ISSUE TITLE
add chart color support

### ISSUE THREAD

**Issue by dtowell** [PHPOffice/PhpSpreadsheet#63]
Add a way to set data series color (and other attributes) for various chart types (at minimum bar and line). 

I am willing to pay for this addition.

**Comment by CrazyBite** [comment]
@PowerKiKi, hello. Can i help with my [commit](url='https://github.com/CrazyBite/PhpSpreadsheet/commit/4732ed52771c9e4d650f5eed0de0bf304782f667')? added fillColor.
try with \PhpSpreadsheet\samples\33_Chart_create_area.php
and change $dataSeriesLabels to:
`$dataSeriesLabels = [
    new \PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues('String', 'Worksheet!$B$1', null, 1, [], null, "C00000"), //	2010
    new \PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues('String', 'Worksheet!$C$1', null, 1, [], null, "8064A2"), //	2011
    new \PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues('String', 'Worksheet!$D$1', null, 1, [], null, "4BACC6"), //	2012
];`

**Comment by PowerKiKi** [comment]
I had a quick glance and it seems to be a good start. But it should be rebased on develop, and​ a setter should probably be added.

**Comment by CrazyBite** [comment]
#151 here

**Comment by krzysztofruszczynski** [comment]
Hello @PowerKiKi , if I read the code correctly, currently there is no support for customized color inside piechart, piechart_3d and donutchart (we need here different colors in one series of data; currently only one point is set with FF9900). Is there a plan to do it? (if yes, I can help with that issue)

**Comment by PowerKiKi** [comment]
There is #158 that is on-going and should address, at least partially, color filling. I suppose you could help by reviewing it. Though it might it not be quite ready yet...

**Comment by arpit0515** [comment]
I am looking for a similar support. I want to change the color of lines in trendline chart. The code mentioned by @PowerKiKi is not working for me. I have raised a separate issue. If this works for someone, please help me out. I will close the other issue.
```php
$dataSeriesLabels = [
    new \PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues('String', 'Worksheet!$B$1', null, 1, [], null, "C00000"), //	2010
    new \PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues('String', 'Worksheet!$C$1', null, 1, [], null, "8064A2"), //	2011
    new \PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues('String', 'Worksheet!$D$1', null, 1, [], null, "4BACC6"), //	2012
];
```

**Comment by oleibman** [comment]
Much support for Chart colors was added by PR #2898 (and subsequent) in June 2022.
