### ISSUE TITLE
HTML writer - cannot read filesize of pictures from XLSX (ZIP) file !

### ISSUE THREAD

**Issue by Echelon78** [PHPOffice/PhpSpreadsheet#630]
https://github.com/PHPOffice/PhpSpreadsheet/blob/125f462a718956f37d81305ca0df4f17cef0f3b9/src/PhpSpreadsheet/Writer/Html.php#L661

sollution:
							$filesize = 0;
							if (strncmp($filename, "zip://", 6)==0) {
								$pathparts =  explode("#", substr($filename, 6, strlen($filename)));
								if (file_exists($pathparts[0])) {
									$zip = zip_open($pathparts[0]);
									while ($zip_entry = zip_read($zip)){
										if (zip_entry_name($zip_entry)==$pathparts[1]) {
											$filesize = zip_entry_filesize($zip_entry);
										}
									}
									zip_close($zip);
								}
							} else {
								$filesize = filesize($filename);
							}
							$picture = fread($fp, $filesize);

**Comment by oleibman** [comment]
Loading an xlsx file with an image, and saving it as html specifying embedimages, did result in a failure for PhpSpreadsheet 1.6 (fread failed, length = FALSE). This seems to match the reported system. However, running a current version of PhpSpreadsheet succeeds, and the image is reproduced successfully. So, the issue appears to have been fixed at some point. Leaving issue closed, removing stale label.
