### ISSUE TITLE
Nesting formula

### ISSUE THREAD

**Issue by oscarml** [PHPOffice/PhpSpreadsheet#633]
Hi,
Are nested formula allowed?

I'm trying to write this formula to a cell:
`IF(     ISERROR(((B4/B5)-1)*100);     "";     (IF(((B4/B5)-1)*100=0;"";((B4/B5)-1)*100))    )`

(blanks inserted for readability)

but vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/Calculation.php throws an "Formula Error: An unexpected error occured" in line 3546,

I'm using version 1.4

Thanks

**Comment by MarkBaker** [comment]
It is perfectly accepted to nest functions in formulae. Your problems is that you're using a semi-colon (`;`) as an argument separator rather than a comma (`,`).

See the [Documentation](https://phpspreadsheet.readthedocs.io/en/develop/topics/recipes/#write-a-formula-into-a-cell) on this
