### ISSUE TITLE
Something got worry when I load a xls file which transform from a xlsx file by WPS

### ISSUE THREAD

**Issue by poxuan** [PHPOffice/PhpSpreadsheet#635]
This is:

```
- [ ] maybe a bug report
```

### What is the current behavior?

It throw error when i call the function load.

### How I resolve it?

I add a trim function in file 
```
vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/OLERead.php 
```
on line 268
```
$entryLen = strlen(trim($this->entry));
```
I known nothing about why it works.
what i see is $this->entry length 1024 but it has nothing after 640

### Which versions of PhpSpreadsheet and PHP are affected?

1.4

**Comment by oleibman** [comment]
Unable to debug without a sample file. Feel free to open a new issue if you feel this is still an issue. Leaving issue closed, removing stale label.
