### ISSUE TITLE
Fatal error: Uncaught exception 'PhpOffice\PhpSpreadsheet\Calculation\Exception' with message 'Measurement Values!K3 -> Formula Error: An unexpected error occured' in C:\wamp64\www\excel\3\spreadsheet\src\PhpSpreadsheet\Cell.php on line 286

### ISSUE THREAD

**Issue by AravinthanRamasamy** [PHPOffice/PhpSpreadsheet#636]
I tried to read data from excel sheet, am getting **Uncaught exception 'PhpOffice\PhpSpreadsheet\Calculation\Exception' with message 'Measurement Values!K3 -> Formula Error**

It seems error is displaying while reading cell which contains formula. 

**Formula in K3 cell " =IF([@[Month-Year]]="","",TEXT([@[Month-Year]],"MMM-YY")) "**

Here is my code ----
<?php
require 'spreadsheet/vendor/autoload.php';
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
$reader->setReadDataOnly(TRUE);
$spreadsheet = $reader->load("1234.xlsm");
$worksheet = $spreadsheet->getSheet(0)->rangeToArray('B3:AY3',null, true, true, true);
var_dump($worksheet);
?>

**Comment by MarkBaker** [comment]
Structured references aren't yet supported by the PHPExcel calculation engine
