### ISSUE TITLE
Mpdf export can exceed pcre.backtrack_limit

### ISSUE THREAD

**Issue by 00dani** [PHPOffice/PhpSpreadsheet#637]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

It should be possible to write large spreadsheets from PhpSpreadsheet to PDF, using the Mpdf writer. In order to achieve this, PhpSpreadsheet should pass HTML into Mpdf in reasonably-sized chunks using multiple calls to `WriteHTML`.

### What is the current behavior?

After the Mpdf writer converts a spreadsheet to HTML, it passes the entirety of the spreadsheet as one big HTML string into Mpdf's `WriteHTML` method. The string size can easily exceed the PHP setting `pcre.backtrack_limit` if a larger spreadsheet is being rendered, causing Mpdf to throw an exception and refuse to write the PDF.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

for ($row = 1; $row < 100; ++$row) {
    for ($col = 1; $col < 100; ++$col) {
        $sheet->getCellByColumnAndRow($col, $row)->setValue('foo bar baz');
    }
}

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Mpdf');
$writer->save('/dev/null');
```

### Which versions of PhpSpreadsheet and PHP are affected?

I'm working with PHP 7.1.20 and PhpSpreadsheet 1.3.1, but I believe this issue still affects newer versions - the Mpdf writer in PhpSpreadsheet 1.4.0 still passes all the HTML as a single string, so the behaviour is unlikely to have changed.

**Comment by PowerKiKi** [comment]
Not the answer you are hoping for, but I believe this is limitation of mpdf, not PhpSpreadsheet. I would suggest you comment on https://github.com/mpdf/mpdf/issues/287 and explain your use-case.

However if one of you were to submit a PR to fix this in PhpSpreadsheet, I would merge it.

Meanwhile I'll close the issue as it is not likely the core team would do anything about it in the foreseeable future.

**Comment by darkbluesun** [comment]
Righteo, we will attempt a workaround PR.
