### ISSUE TITLE
Fails to calculate INDEX() function

### ISSUE THREAD

**Issue by balgf** [PHPOffice/PhpSpreadsheet#64]
Sample formula:
=INDEX({"First","Second","Third","Fourth","Fifth","Sixth","Seventh"}, 4)

Errors thrown:
Undefined offset: 3 in `/var/www/html/hoosh/excel_v2/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/LookupRef.php on line 603`
`Undefined index: in /var/www/html/hoosh/excel_v2/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/LookupRef.php on line 610`

**Comment by balgf** [comment]
Turns out, $arrayValues passed to INDEX method is a 2 level array which is causing the issue.
```
array (size=1)
  0 => 
    array (size=7)
      0 => string 'First' (length=5)
      1 => string 'Second' (length=6)
      2 => string 'Third' (length=5)
      3 => string 'Fourth' (length=6)
      4 => string 'Fifth' (length=5)
      5 => string 'Sixth' (length=5)
      6 => string 'Seventh' (length=7)
```

**Comment by PowerKiKi** [comment]
You are probably experiencing the same issue as https://github.com/PHPOffice/PHPExcel/issues/1091. If you are able to provide a PR to solve it, that would very much appreciated.

**Comment by balgf** [comment]
There appears to be a breakage when I pulled the latest dev copy. Not sure which commit caused this. Now the $arrayValues only recieved the last element. My fix no longer works because of this.
```
array (size=1)
  0 => string 'Seventh' (length=7)
```

**Comment by ankitm123** [comment]
I will take a look, and understand the issue, and see if I can fix the issue

**Comment by oleibman** [comment]
Probably the oldest bug I've worked on on this project. Fix will be available in a day or two.
