### ISSUE TITLE
Feature: option to disable any macros'es for security

### ISSUE THREAD

**Issue by st0at** [PHPOffice/PhpSpreadsheet#650]
What if I want to disable any macros in generated Excel, is there any option for that? That would be a good feature for security reasons to disable any possibility for malicious macros'es.
More info here: https://www.contextis.com/blog/comma-separated-vulnerabilities

**Comment by Arr-n-D** [comment]
Came across this thread, why has this gone stale? Macros are a vulnerability

**Comment by oleibman** [comment]
Spreadsheet method `discardMacros` was introduced in PHPExcel, and remains available today. Removing stale label, leaving issue closed.
