### ISSUE TITLE
Set cell value set 0 instead of text

### ISSUE THREAD

**Issue by RushabhJoshi** [PHPOffice/PhpSpreadsheet#651]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
$sheet->setCellValue('A1', 'Comptabilité')

should set the A1 cell with text 'Comptabilité'

### What is the current behavior?
right now A1 is 0

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Comptabilité');
$writer = new Xlsx($spreadsheet);
$writer->save('file.xlsx');
```
PHP spreadsheet version 1.4.0

**Comment by damijanc** [comment]
I ran your code and it works perfectly with 1.4

` "require": {
        "phpoffice/phpspreadsheet": "^1.4"
    }
`

**Comment by RushabhJoshi** [comment]
make sure you did not try 'Comptabilite' instead of 'Comptabilité'

**Comment by damijanc** [comment]
![selection_014](https://user-images.githubusercontent.com/1586796/44854473-eac2a080-ac68-11e8-845d-e09acce8fc30.png)

**Comment by RushabhJoshi** [comment]
do we have to set character-set? because in my case it is storing 0

php 7.1
ubuntu 18.04

**Comment by damijanc** [comment]
Besides the `php-intl` package I do not have anything special installed. Can you check if you have charset set in your php.ini

`; PHP's default character set is set to UTF-8.
; http://php.net/default-charset
default_charset = "UTF-8"`

 if you are generating excel from the console you can run:
`php -i | grep charset`

or `phpinfo()` on your web server.

**Comment by PowerKiKi** [comment]
Cannot reproduce either. PhpSpreadsheet expect everything to be UTF-8.

**Comment by aizquier** [comment]
Just for the record, I could reproduce the problem, PhpSpreadsheet version ^1.8 . I was fetching data from a MySQL database with a non utf-8 collation (strings in french), and after inserting them using $sheet->setCellValue($str),  PhpSpreadsheet turned the strings into FALSE values in Excel. After changing the mysql connection charset ( $mysql->set_charset("utf8") ), the problem was solved. Conclusion: beware of  non utf-8 strings in PhpSpreadsheet!
