### ISSUE TITLE
loss on 'bootstrap' file

### ISSUE THREAD

**Issue by acclea** [PHPOffice/PhpSpreadsheet#655]
Excuse me,why unzip this folder has 'Bootstrap.php' and other folder,that means i must use Bootstrap?
when i was used PHPExcel that unzip  folder has 'PHPExcel.php' and other folder

**Comment by PowerKiKi** [comment]
You cannot use "Bootstrap.php" anymore. Things have changed. Instead you must use composer. See https://phpspreadsheet.readthedocs.io/en/develop/#installation
