### ISSUE TITLE
Failure to create temporary file: working in local but not working in ubuntu server

### ISSUE THREAD

**Issue by rahul-acclivity** [PHPOffice/PhpSpreadsheet#656]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Save a Excel file in temp dir and download on browser

### What is the current behavior?
getting this error
ZipArchive::close(): Failure to create temporary file: Permission denied-398-/var/www/vhosts/aec.com/htdocs/application/classes/vendors/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php

### What are the steps to reproduce?
$fileName = 'bs_'.$schedule_details[0]['schedule_name'].'.xlsx';
\PhpOffice\PhpSpreadsheet\Shared\File::setUseUploadTempDirectory(true);
            $writer = new Xlsx($spreadsheet); 
            $writer->save($fileName);
 After this line I am getting an error mention above.

I have debug some possibilities mention online by setting 
variable sys_temp_dir and open_basedir everything related to php is working but getting this error. 

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:
https://stackoverflow.com/questions/50470370/phpspreadsheet-permissions-ziparchiveclose-failure-to-create-temporary-f?rq=1

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
            $spreadsheet = new Spreadsheet();
            $sheet = $spreadsheet->getActiveSheet();

            $sheet->setCellValue('A1', 'some data');

$fileName = 'some_name.xlsx';
\PhpOffice\PhpSpreadsheet\Shared\File::setUseUploadTempDirectory(true);

            $writer = new Xlsx($spreadsheet); 
            $writer->save($fileName);
->> here we get an error.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet for PHP 5.6

**Comment by YECAPP** [comment]
Same problem for me, 

Some solution yet ?

**Comment by PowerKiKi** [comment]
Not a bug in PhpSpreadsheet, but a file permission issues.

**Comment by rideron89** [comment]
The solution is to make sure all necessary nested directories of your final file destination exist. Example:

```
$dirPath  = "/usr/share";
$fileName = "{$dirPath}/filename.xls";

// recursively creates all required nested directories
if (!file_exists($dirPath)) {
    mkdir($dirPath, 0774, true);
}
```

The error message makes it seem like you don't have access when creating the temporary file. This might not always be true.
