### ISSUE TITLE
PHP 7.3 Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by pqr** [PHPOffice/PhpSpreadsheet#657]
This is:

```
- [X] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Reading correct xls file should not rise any Warning message from PHP

### What is the current behavior?
On PHP 7.3 I see following:
`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?`

### What are the steps to reproduce?
Running on PHP 7.3 (I did on beta3) just read any .xls file

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load("any.xls");

```

Consider changing "continue" statement to "break" statement: https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Reader/Xls.php#L1130

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet version 1.4.0
PHP 7.3 beta3

**Comment by PowerKiKi** [comment]
Fixed in 9022c39dd8cd18b49bd6410edb971636f5c1c72b
