### ISSUE TITLE
Not keeping chart styling when reading from template

### ISSUE THREAD

**Issue by shahimclt** [PHPOffice/PhpSpreadsheet#661]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

I have a template file that has a Radar chart. The data for the chart is kept in the cells behind the chart. I read the template file. Change the values in the cells containing the chart data, and then export it. The chart should keep all its previous styling as in the template.

Here's how the chart in the template looks like : 

![capture](https://user-images.githubusercontent.com/8318002/45098602-eef82d80-b142-11e8-9f1d-ec720aea41dc.PNG)

### What is the current behavior?

The exported chart loses a lot of its styles. It looks like it resets to most of its default style no matter what style you set in the template. 

For instance, the data labels disappear and legends appear instead. The color of the gridlines also reset to black:

![capture2](https://user-images.githubusercontent.com/8318002/45098952-c45aa480-b143-11e8-92d8-0f914986ee45.PNG)

### What are the steps to reproduce?

The Radar chart in the examples works as it has mostly default styles. Use this file to view the issue:

[sot.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2353088/sot.xlsx)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

        $reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
        $reader->setIncludeCharts(true);

        $spreadsheet = $reader->load("/home/fod/public_html/signoff_graph/Sign_Off_Template.xlsx");

        $sheet = $spreadsheet->getActiveSheet();

        // Redirect output to a client’s web browser (Xlsx)
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="SignOff Sheet.xlsx"');
        header('Cache-Control: max-age=0');
        // If you're serving to IE 9, then the following may be needed
        header('Cache-Control: max-age=1');
        // If you're serving to IE over SSL, then the following may be needed
        header('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
        header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT'); // always modified
        header('Cache-Control: cache, must-revalidate'); // HTTP/1.1
        header('Pragma: public'); // HTTP/1.0

        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
        $writer->setIncludeCharts(true);
        $writer->save('php://output');
```

### Which versions of PhpSpreadsheet and PHP are affected?

Plugin version 1.4.0 and PHP version 5.6

**Comment by shahimclt** [comment]
I think #568  might be related to this issue.

**Comment by dericlima** [comment]
I'm having the same issue with some image in my template.
So far I found out the `xdr:to` property is missing in the `drawing.xml`.

A excel that's working fine contains these properties in the `drawning.xml`:
```
<xdr:from>
  <xdr:col>17</xdr:col>
  <xdr:colOff>390240</xdr:colOff>
  <xdr:row>0</xdr:row>
  <xdr:rowOff>74880</xdr:rowOff>
</xdr:from>
<xdr:to>
  <xdr:col>18</xdr:col>
  <xdr:colOff>833400</xdr:colOff>
  <xdr:row>1</xdr:row>
  <xdr:rowOff>110520</xdr:rowOff>
</xdr:to>
```

After reading my template and exporting again, the writer is removing the `xdr:to` attribute:
```
<xdr:from>
  <xdr:col>17</xdr:col>
  <xdr:colOff>390525</xdr:colOff>
  <xdr:row>0</xdr:row>
  <xdr:rowOff>76200</xdr:rowOff>
</xdr:from>
```

**Comment by sozik** [comment]
when output excel with some chart, I think some files are not created.
So, I just unzip the template excel, and copy the below setting files from the template, then overide the output file.
share my solution of the problem, wish this can help somebody.

```
        $xmlPath =  __DIR__ . '/excel';
        $zip = new ZipArchive;
        if ($zip->open($outputFile) === TRUE) {
            // add chart format file
            $zip->addFile($xmlPath . '/charts/chart1.xml', 'xl/charts/chart1.xml');
            // add below when needed
            $zip->addFile($xmlPath . '/charts/colors1.xml', 'xl/charts/colors1.xml');
            $zip->addFile($xmlPath . '/charts/style1.xml', 'xl/charts/style1.xml');
            $zip->addFile($xmlPath . '/charts/_rels/chart1.xml.rels', 'xl/charts/_rels/chart1.xml.rels');
            // some chart color styles
            $zip->addFile($xmlPath . '/theme/theme1.xml', 'xl/theme/theme1.xml');
            $zip->addFile($xmlPath . '/[Content_Types].xml', '[Content_Types].xml');
            $zip->close();
        }
```

**Comment by oleibman** [comment]
Reopening. Loading and saving the supplied spreadsheet results in a chart that matches the original more closely in some respects than the original report, but not identically.
