### ISSUE TITLE
Is it posible to create pivot table using PHPSpreadsheet

### ISSUE THREAD

**Issue by sidharth721** [PHPOffice/PhpSpreadsheet#663]
HI everyone ,

Please help me if its possible to create pivot tables while doing export using PHPExcel/PHPSPreadsheet.

**Comment by ocin35** [comment]
Hi,

<?php
        //call the autoload
	require 'PhpSpreadSheet/vendor/autoload.php';
	//load phpspreadsheet class using namespaces
	use PhpOffice\PhpSpreadsheet\Spreadsheet;
	//call xlsx writer class to make an xlsx file
	use PhpOffice\PhpSpreadsheet\IOFactory;

	//make a new spreadsheet object
	$spreadsheet = new Spreadsheet();
	//get current active sheet (first sheet)
	$sheet = $spreadsheet->getActiveSheet();

        //insert value
        $sheet->setCellValue('B1', 'A'); $sheet->setCellValue('C1', '1');
        $sheet->setCellValue('B1', 'A'); $sheet->setCellValue('C1', '1');
        $sheet->setCellValue('B1', 'A'); $sheet->setCellValue('C1', '1');

        //set the header first, so the result will be treated as an xlsx file
	header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
	//make it an attachment so we can define filename
	$filnam = 'ExtractGePi_'.date('ymdhis').'.xlsx';
	header('Content-Disposition: attachment;filename='.$filnam);
	//header('Content-Disposition: attachment;filename="Result.xlsx"');
	//create IOFactory object
	$writer=IOFactory::createWriter($spreadsheet, 'Xlsx');
	//save into php output
	$writer->save('php://output');
?>
