### ISSUE TITLE
time format for duration is incorrect

### ISSUE THREAD

**Issue by patrickomeara** [PHPOffice/PhpSpreadsheet#664]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

To display hours in excess of a day as a total `27:15`

The expected behavior of `[h]:mm` is to display the total hours as mentioned here https://stackoverflow.com/questions/16912568/working-with-time-duration-not-time-of-day

### What is the current behavior?

the output is `:15`

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

echo \PhpOffice\PhpSpreadsheet\Style\NumberFormat::toFormattedString(((27*60)+15)/1440, '[h]:mm'))
```

### Which versions of PhpSpreadsheet and PHP are affected?

I've tested this on PHP 7.1 and PHP 7.2. Both are displaying as above

PHPSpreadsheet v1.4.0

**Comment by GreatHumorist** [comment]
hello, this problem is solved related to #666
