### ISSUE TITLE
Date::formattedPHPToExcel fails if year 0 is given

### ISSUE THREAD

**Issue by gullij** [PHPOffice/PhpSpreadsheet#669]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
The documentation indicates that the year should be an int with no specified limits so passing a 0 should not cause a problem when the user considers the year, month and date irrelevant.

### What is the current behavior?
When calling the PhpOffice\PhpSpreadsheet\Shared\Date::formattedPHPToExcel() with the first parameter, year, as 0, it throws a warning: "Warning: A non-numeric value encountered"

It looks like the method attempts to read a substring from the year, substr fails and returns a boolean FALSE which triggers a warning. Using this within a framework like Symfony 3.4 stops execution completely.

### What are the steps to reproduce?

$var = PhpOffice\PhpSpreadsheet\Shared\Date::formattedPHPToExcel(0, 0, 0, 0, 0, 10);

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$var = PhpOffice\PhpSpreadsheet\Shared\Date::formattedPHPToExcel(0, 0, 0, 0, 0, 10);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.2
PHPSpreadsheet 1.4.0

**Comment by GreatHumorist** [comment]
I think the code is no problem, but you use with a wrong method.
Excel's date start from 1900/1/1 which number is 1，the negative number is not support for convert.
So, the $year you give should not less than 1900.

**Comment by gullij** [comment]
OK, in that case I'll use 1900 but maybe the method should check if the user gives an invalid year and return an error when that happens. Updating the documentation with this info would probably be a good idea too.

**Comment by gullij** [comment]
I'll create a pull request but does it make sense to have the method return an error on an invalid date? Does that too much of a backwards compatiliby break?

**Comment by oleibman** [comment]
Supplied code no longer issues a warning, and returns a large negative value. Removing stale label, leaving issue closed.

**Comment by yasar-luo** [comment]
您好，我是罗扬，您的邮件我已经收到，我会尽快回复您。
