### ISSUE TITLE
bug : Infinite loop in OLERead

### ISSUE THREAD

**Issue by atmacola** [PHPOffice/PhpSpreadsheet#67]
Trying to use OLERead::read() for build a xls file validator, I found an infinite loop.

It happen in lines 152 to 159 :

```php
while ($sbdBlock != -2) {
    $pos = ($sbdBlock + 1) * self::BIG_BLOCK_SIZE;

    $this->smallBlockChain .= substr($this->data, $pos, 4 * $bbs);
    $pos += 4 * $bbs;

    $sbdBlock = self::getInt4d($this->bigBlockChain, $sbdBlock * 4);
}
```

$sbdBloc takes that values : (0, 1, 2, 3, 4, 5, 6, 7, 8, 254) and reset to 0 (never become -2)
NOTE : (254 * 4) > strlen($this->bigBlockChain) causing problem in self::getInt4d()

You can try this with the attached file.
[corrupted_excel_file.xls.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/687073/corrupted_excel_file.xls.zip)

**Comment by PowerKiKi** [comment]
Reading a corrupted file is not a supported use-case and we probably won't have any time to dedicate to fixing it. But if you are able to submit a PR to fix it, it might still be merged.

Meanwhile I am closing this, not give anyone false hope.

**Comment by Quix0r** [comment]
Corrupted files cannot be "auto-magically" fixed, I think @atmacola is aware of that. What he means is that PHPSpreadsheet (and others, too) should become more robust and not end up in endless loops wih `E_NOTICE` or even `E_WARNING`. Programs should not be to positive about data they read, at least they should try to throw an exception if they encounter bad data so other programs can respond (means catch + handle) them.
