### ISSUE TITLE
COUNTIF whole column is very inefficient

### ISSUE THREAD

**Issue by thigg** [PHPOffice/PhpSpreadsheet#671]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [x ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
When using expressions like `=COUNTIF($Sheet2.D:D,A1)` the whole column (until 65,000) is iterated, this takes even for small files very long.

### What is the expected behavior?
Only fields should be considered for calculation which are in a sensible range.

### What is the current behavior?
All possible rows are iterated through. This takes even for the given example with a total of 10 rows more than 30 seconds.

### What are the steps to reproduce?
_Sample files to reproduce:_ [sample.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/2379378/sample.zip)

Doing a simple save in this project takes more than 30 seconds.
```php
$xls = PhpOffice\PhpSpreadsheet\IOFactory::load($xls_file);
$sheet = $xls->getSheet(1);
$sheet->getCell("D9")->setValue(4);
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xls($xls);
$writer->save($xls_file);
```

The file is looking like this:
Sheet1:
Count how often `1` appears in column D of `Sheet2`
 `=COUNTIF($Sheet2.D:D,1)`
Sheet2: 

D
--
1
1
1
1
2
3
2

### Which versions of PhpSpreadsheet and PHP are affected?
php spreadsheet: 1.4.0, PHP: `PHP 7.2.7-0ubuntu0.18.04.2 (cli)`

**Comment by GreatHumorist** [comment]
This is not a bug of PhpSpreadsheet, the ods file you provide is not current.
You can unzip the sample.ods file, and find the content.xml, in this file you can see some node like this:
`<table:table-cell table:formula="of:=COUNTIF([$Sheet2.D$1:.D$1048576];[.A1])" office:value-type="float" office:value="5" calcext:value-type="float">`

The formula is not D:D, but D$1:.D$1048576 instead, which 1048576 is max repeated rows number in ods.

So how to solve this problem? Maybe a check of max rows of actually is better.
