### ISSUE TITLE
Feature: disable calculation when saving

### ISSUE THREAD

**Issue by thigg** [PHPOffice/PhpSpreadsheet#672]
This is:

```
- [ ] a bug report
- [ x] a feature request
- [x ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
While running into #671, I thought it would be nice if calculation of formulas could be disabled.

The problem with #671 is, that saving does not work efficently, if certain formulas are present, so it would be nice to have a fallback option.

What I don't know, is how programs like LibreOffice or MS Office handle files where the formula results are outdated.

The feature would look something like this:

`$writer->save($xls_file,false);` where false indicates, that recalculation of formulas should be skipped.

**Comment by PowerKiKi** [comment]
See https://phpspreadsheet.readthedocs.io/en/develop/topics/reading-and-writing-to-file/#formula-pre-calculation
