### ISSUE TITLE
Example not found

### ISSUE THREAD

**Issue by refojunior** [PHPOffice/PhpSpreadsheet#682]
Please help, why this is happened to me, the example of phpspreadsheet was not found
i was googling and i don't get solution about this.
and the file sample is exist.

![image](https://user-images.githubusercontent.com/30499443/45731424-1dc5d780-bc0a-11e8-8739-b74c6847fa06.png)

![image](https://user-images.githubusercontent.com/30499443/45731415-169ec980-bc0a-11e8-9b72-9e173a816e07.png)

![image](https://user-images.githubusercontent.com/30499443/45731521-9e84d380-bc0a-11e8-8d0a-b7813ee2ef65.png)

**Comment by PowerKiKi** [comment]
Fixed in #653
