### ISSUE TITLE
undefined index

### ISSUE THREAD

**Issue by yalwayzm33** [PHPOffice/PhpSpreadsheet#685]
Hi,

Just updated from PhpExcel to Phpspreadsheet

While loading excel file through IOFactory::load method getting this error  again and again

'undefined index $' (error location: PhpSpreadsheet/Cell/Coordinate.php(291)) 

its because of autoFilter ($A$1:$K$1), the dollar sign is creating the problem

any help would be appreciated.

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue **without** relying on an external Excel file.

And don't forget to mention what version of this project you are using.

I'll close the issue for now, but feel free to re-open when you add more details.
