### ISSUE TITLE
Undefined index $ : while importing excel file

### ISSUE THREAD

**Issue by yalwayzm33** [PHPOffice/PhpSpreadsheet#687]
This is:

```
-  a bug report
```

### What is the expected behavior?
Trying to import an excel file (.xlsx) and file should be imported without any error

### What is the current behavior?
During import i am getting undefined index $ error (IOFactory::load method is  throwing this error) when i searched it,  its because of autoFilter being applied.

```
2018-09-26 07:05:22 : #0 /var/www/html/project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php(291): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/html/s...', 291, Array)
#1 /var/www/html/project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php(207): PhpOffice\PhpSpreadsheet\Cell\Coordinate::columnIndexFromString('$A')
#2 /var/www/html/project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/AutoFilter.php(111): PhpOffice\PhpSpreadsheet\Cell\Coordinate::rangeBoundaries('$A$1:$K$1')
#3 /var/www/html/project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php(1076): PhpOffice\PhpSpreadsheet\Worksheet\AutoFilter->setRange('$A$1:$K$1')
#4 /var/www/html/project/app/Excel/FileLoader.php(286): PhpOffice\PhpSpreadsheet\Reader\Xlsx->load('/var/www/html/s...')
```

### What are the steps to reproduce?
just upload an excel file downloaded through phpspreadsheet all filters applied (autoFilter are like this $A$1:$K$1  the dollar  sign is  creating problem when used in Coordinate.php line  291)

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$reader = IOFactory::createReaderForFile($file_name);
$excel    =   $reader->load($file_name);

```

### Which versions of PhpSpreadsheet and PHP are affected?
Latest
1.4.0

**Comment by PowerKiKi** [comment]
Can be easily reproduced with:

```php
<?php
require 'vendor/autoload.php';

var_dump(\PhpOffice\PhpSpreadsheet\Cell\Coordinate::columnIndexFromString('$A'));
```

PR welcome to fix it

**Comment by yalwayzm33** [comment]
@PowerKiKi i fixed it by removing "$" sign.

at line: /var/www/html/project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php(1076): PhpOffice\PhpSpreadsheet\Worksheet\AutoFilter->setRange('$A$1:$K$1')

so the values passed within setRange is "A1:K1"

and as we are changing the library directly so we added patch so that changes can persist themselves whenever we ran composer install or update.

**Comment by yudina-m** [comment]
I created PR with suggested change and also added an Exception to `Coordinate::columnIndexFromString`, similar to the symbol limit. Unit tests are updated as well.

**Comment by danaki** [comment]
This issue is not fixed but closed. If a sheet contains autofilter it produces an error similar to `undefined index $ error` while loading spreedsheet file. Please reopen the issue.

**Comment by beraldo** [comment]
I am facing the same issue :(

**Comment by yalwayzm33** [comment]
> I am facing the same issue :(

i added above the way how to fix it and it is working all fine..

**Comment by beraldo** [comment]
@yalwayzm33 yes, I saw. Thank you, by the way.

But it's a bug and it would be great if the project was updated. Changing the source of third party software is not a good idea, but I'll do it until there is an update

**Comment by yalwayzm33** [comment]
> @yalwayzm33 yes, I saw. Thank you, by the way.
> 
> But it's a bug and it would be great if the project was updated. Changing the source of third party software is not a good idea, but I'll do it until there is an update

i know that thats why i added a patch it 

"and as we cant change the library directly so we added patch so that changes can persist themselves whenever we ran composer install or update."

**Comment by PowerKiKi** [comment]
See the comments in #718 to create a PR that could be merged to fix this

**Comment by gdianov** [comment]
I had the same problem, but the error itself appeared in the Excel file itself, the format of the cell in which the text was located was like Number and this is not correct. Redid the cell format on Text and it worked. **Check cell format.**

**Comment by AlexeyKosov** [comment]
If this repository is abandoned and there's no maintainers who can solve such critical issues, please let users know about that (so that the package is highlighted with yellow in composer) rather than just keeping bug reports closed.

**Comment by astronati** [comment]
@PowerKiKi https://github.com/PHPOffice/PhpSpreadsheet/pull/1326 is the PR but none is reviewing it. Could you help us please?
