### ISSUE TITLE
COUNTIFS : developped ?

### ISSUE THREAD

**Issue by poitierjohan** [PHPOffice/PhpSpreadsheet#688]
Hi,

I would need the function COUNTIFS.
I see in de code that this function isn't implemented.

Could you add this function in the functions library ?

Thank you for your following...

**Comment by PowerKiKi** [comment]
Consider contributing the missing feature you need.

**Comment by poitierjohan** [comment]
Hi,
It is possible to have any documentation for devellop this formula ?
Because it has multple arguments.
Thanks
