### ISSUE TITLE
XIRR returns Non Numeric value Encountered

### ISSUE THREAD

**Issue by Naveen95** [PHPOffice/PhpSpreadsheet#689]
XIRR returning Non Numeric Value Encountered thought the inputs passed are correct. Below is the input passed. 

array:2 [▼
  0 => -1000000.706
  1 => 947003.58
]
array:2 [▼
  0 => "2018-09-05"
  1 => "2018-09-26"
]

The Expected XIRR Return should be **-0.6118824173**

**Comment by TJ909** [comment]
+1

Has anyone encountered a different method for XIRR in PHP? This method for XIRR has difficulty with some negative returns. It's very good at most calculations but is not always the same as Excel with negative returns. 

I found another package in PHP, but it looks like the same formula. Found something in C# as well, but unfortunately refactoring that code is outside my skill set.

Other PHP package, same method: https://www.phpclasses.org/package/892-PHP-Financial-functions-with-the-Excel-function-names-.html

C#: https://stackoverflow.com/questions/5179866/xirr-calculation

**Comment by DilipsinhChudasama** [comment]
The same issue is still there for the following data
```php
[ "2022-12-12"=> -20972.36000000 , "2022-12-16"=> 20350.54500000]
```

**Comment by oleibman** [comment]
Reopening issue. PR #2487 fixed a lot of similar issues with XIRR. However, I agree that it fixes neither the original problem mentioned in this ticket nor the new one just added.

**Comment by oleibman** [comment]
The python package xirr tries the Newton-Raphson method and, if that doesn't converge, tries Brent's method (both these methods come from the scipy package). I have confirmed that these failing examples give the expected result in Python, but they wind up using Brent's method. The PhpSpreadsheet code currently uses only Newton-Raphson. I will have to research if it is possible to come up with Php code for Brent. It could take a while.

**Comment by oleibman** [comment]
Looking again, only the new issue goes through Brent's method in Python. The original does not, so it's a different problem (which may nevertheless be solved via Brent).
