### ISSUE TITLE
Different first page footer image bug fixed

### ISSUE THREAD

**Issue by wenkz027** [PHPOffice/PhpSpreadsheet#698]
Hello,
I just want to share my solution on how to display different first page footer image.
Please take not that the position of the image is only center. I haven't explore the first page footer left position or first page right position. To get the other position please try the tip on how reveal the code for header and footer. Just follow the steps on this [link](https://phpspreadsheet.readthedocs.io/en/develop/topics/recipes/#setting-the-print-header-and-footer-of-a-worksheet).

Sample Code:
$sheet->getHeaderFooter()->setDifferentFirst(true);
$drawing = new \PhpOffice\PhpSpreadsheet\Worksheet\HeaderFooterDrawing();
$drawing->setName('test footer');
$drawing->setPath(dirname(Yii::app()->basePath).'/images/footers/footer.png');
$drawing->setHeight(43);

// The CFFIRST is the location of the image footer extracted from Excel 2016 xlsx file
$sheet->getHeaderFooter()->addImage($drawing, 'CFFIRST');
$sheet->getHeaderFooter()->setFirstFooter("&C&G\nPage &P of &N");
$sheet->getHeaderFooter()->setOddFooter("&CPage &P of &N");

Fix:
Edit  HeaderFooter Class
- Add new const IMAGE_FIRST_FOOTER_CENTER = 'CFFIRST';
- update the getImages() function to get the CFFIRST image details
  - example
     if (isset($this->headerFooterImages[self::IMAGE_FIRST_FOOTER_CENTER])) {
            $images[self::IMAGE_FIRST_FOOTER_CENTER] = $this-> headerFooterImages[self::IMAGE_FIRST_FOOTER_CENTER];
        }

Im using the current latest version 1.4.1 

devteam - Please include this fixed and also add all the locations of the header and footer for first page.

Thank you.

**Comment by PowerKiKi** [comment]
Please consider opening a PR, covered by unit tests, for the changes you suggest.
