### ISSUE TITLE
Switch Date Handling Routines to use DateTime internally

### ISSUE THREAD

**Issue by MarkBaker** [PHPOffice/PhpSpreadsheet#7]
Switch Date Handling Routines to use DateTime internally (to avoid use of unix Timestamp and ensure full range of Excel DateTimes on  32-bit systems), and use DateTimeInterface for typehinting so that DateTime or DateTime immutable can both be used

**Comment by PowerKiKi** [comment]
Is anybody working on that ? I would be willing to do it if the work has not already started and also fix date related unit tests at the same time. What do you say ?

**Comment by MarkBaker** [comment]
I've been working on the DateTime class, switching it to work with DateTime objects rather than unix timestamps, and using DateTimeInterface where appropriate

**Comment by PowerKiKi** [comment]
ok, then I won't do anything about that. I'll have a look at fixing other unit tests.

In the meantime could you please enable Travis CI for this repository ? The badges are shown in the README, but Travis has nod builds to show...

**Comment by PowerKiKi** [comment]
Is it correct that this is now finished ?

**Comment by PowerKiKi** [comment]
Assuming this done
