### ISSUE TITLE
Failed to parse date/time format

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PhpSpreadsheet#70]
I get the following exception when trying to parse a ODS file:
````
Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (1900-01-08T00:57:35.9999999999) at position 0 (1): The timezone could not be found in the database in /bla/foo/third-party/phpspreadsheet/src/PhpSpreadsheet/Reader/Ods.php:533
````
The file contains personal data so I cannot attach it.

**Comment by PowerKiKi** [comment]
The `9999999999` is extremely suspicious to me. Did you have a look a the raw file manually to see what was the exact original content ? 

I'd bet it is an invalid odd file.

**Comment by PowerKiKi** [comment]
Closing for lack of feedback.
