### ISSUE TITLE
Cell->setValue() always uses value binder rather than checking data type

### ISSUE THREAD

**Issue by elazar** [PHPOffice/PhpSpreadsheet#715]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

`Cell->setValue()` should check if a data type has been explicitly set for the cell, whether via its constructor or a call to `setDataType()`, before deferring to the value binder.

Ideally, it should be possible for data set via `Worksheet->fromArray()` to be interpreted with a data type set like so.

```php
$sheet->getCell($coordinate)->setDataType(DataType::TYPE_STRING);
$sheet->fromArray($row);
```

### What is the current behavior?

`Cell->setValue()` always defers to the value binder, ignoring any data type that was previously set.

`Cell->setValueExplicit()` requires that the value and data type be specified at the same time. In cases where a sheet may have a varying number of columns, and row data is contained in enumerated arrays that are normally passed to `Worksheet->fromArray()`, it becomes rather awkward to set data types for individual cells where the intended data type differs from what the value binder would select.

```php
$sheet->fromArray($row);
$cell = $sheet->getCell($coordinate);
$cell->setValueExplicit($cell->getValue(), DataType::TYPE_STRING);
```

### What are the steps to reproduce?

```php
$cell->setDataType(DataType::TYPE_STRING);

// This value is interpreted as a formula instead of a string and causes an error
$cell->setValue('=)');
```

```
PhpOffice\PhpSpreadsheet\Calculation\Exception [ 0 ]: SHEET!N3 -> Formula Error: Unexpected ')' ~ /src/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php [ 274 ]
#0 /src/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1070): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue()
#1 /src/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1020): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeCell(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), 'N3', Array)
#2 /src/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(76): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeSheetData(Object(PhpOffice\PhpSpreadsheet\Shared\XMLWriter), Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), Array)
#3 /src/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(281): PhpOffice\PhpSpreadsheet\Writer\Xlsx\Worksheet->writeWorksheet(Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet), Array, false)
```

### Which versions of PhpSpreadsheet and PHP are affected?

I suspect all versions have this issue. In my particular case, I'm using 1.3.1. However, [changes between that version and 1.4.1](https://github.com/PHPOffice/PhpSpreadsheet/compare/1.3.1...1.4.1) don't appear to include any to the `Cell` class.

**Comment by MarkBaker** [comment]
You misunderstand the purpose of `setDataType()`. The datatype is set by the binder, or by using `setCellValueExplicit()`; it is not intended to use a pre-set datatye from within userland code, but we can't prevent it unfortunately... if PHP supported internal methods, then `setDataType()` would be internal only.

**Comment by NikitaKharkov** [comment]
I add my 50 cents: I used numbers with dots, like 0.1, 0.5 etc. And the problem was (I don't know actually why) with repeating one value to other columns, but exactly with dots. Example

Input: $a = [0.1, 0.5, 0.7, 5, 25];
Output (on a sheet): [0.1, 0.1, 0.1, 5, 25];

In a code we used next strings:

```
foreach ($col->getCellIterator() as $cell) {
       $cell->setDataType(DataType::TYPE_STRING);
}
```

So it's forcibly changed to strings. This worked, but not for my case with float numbers.

It was fixed with next solution:

```
foreach ($col->getCellIterator() as $cell) {
       $cell->setValueExplicit($cell->getValue(), DataType::TYPE_STRING);
}
```

So, now it works like a charm.

Hopeful, that it will be useful for somebody ;)

Version of PHPOffice: **1.17.1**

**Comment by oleibman** [comment]
Request was addressed by @MarkBaker just after the issue went stale. Removing stale label, leaving closed. I will note that the problem with an unparsable formula was dealt with some time ago; these should now be treated as strings not formulas.

Although I would not recommend it, it is fairly easy to extend DefaultValueBinder so that the extended class behaves as the requester wishes:
```php
class UseExistingDataTypeBinder extends DefaultValueBinder
{
    public function bindValue(Cell $cell, mixed $value): bool
    {
        $dataType = $cell->getDataType();
        if ($dataType === DataType::TYPE_NULL) {
            return parent::bindValue($cell, $value);
        }
        $cell->setValueExplicit($value, $dataType);

        return true;
    }
}
```
It probably needs some error-handling, but will basically work as desired.
