### ISSUE TITLE
PHP5.6 is not compatible with Coercive mode

### ISSUE THREAD

**Issue by blueberry-media** [PHPOffice/PhpSpreadsheet#719]
Not working in PHP5.6 (http://php.net/manual/en/migration70.new-features.php)
calculate.php has `private static function mkMatrix(...$args)` this is not working in php 5.6

https://github.com/PHPOffice/PhpSpreadsheet/blob/a1e8c843b79c6bc916cd2a5a725fc26948daba66/src/PhpSpreadsheet/Calculation/Calculation.php#L3235

**Comment by PowerKiKi** [comment]
On the line you link, there is no coercion at all. You probably meant variadic function, and they are supported by PHP 5.6: http://php.net/manual/en/migration56.new-features.php#migration56.new-features.variadics
