### ISSUE TITLE
E_WARNING: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? 

### ISSUE THREAD

**Issue by dp-ifacesoft** [PHPOffice/PhpSpreadsheet#721]
This is: 
vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/OLE.php:323

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by PowerKiKi** [comment]
Fixed in 9022c39dd8cd18b49bd6410edb971636f5c1c72b
