### ISSUE TITLE
Warning: date() expects parameter 2 to be integer, float given in src\PhpSpreadsheet\Shared\OLE.php

### ISSUE THREAD

**Issue by ntamil** [PHPOffice/PhpSpreadsheet#722]
Getting below warning in **PHP Version 7.23**

`Warning: date() expects parameter 2 to be integer, float given in phpoffice\phpspreadsheet\src\PhpSpreadsheet\Shared\OLE.php`

No problem in **PHP Version 5.6.30**

No idea whether it is a problem due to PHP version or any other issue.

**Comment by oleibman** [comment]
Insufficient information to duplicate problem. However, it is very likely that it would have been resolved by PR #2113. Leaving issue closed, removing stale label.
