### ISSUE TITLE
Corrupt file since migrating to 1.3.0 for complex doc when using removeSheet

### ISSUE THREAD

**Issue by immobilia** [PHPOffice/PhpSpreadsheet#723]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Open the result .xlsx with Excel without warning (after the document was saved with PhpSpreadsheet)

[Classeur_Empty.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2488240/Classeur_Empty.xlsx)
[Classeur_Empty.xlsxOUT.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2488241/Classeur_Empty.xlsxOUT.xlsx)

### What is the current behavior?
Open the result .xlsx with Excel ask a confirm notice to open :

Ask :
> Microsoft Excel: Sorry ... We found a problem in the contents of "Class_Box - Copy.xlsxOUT.xlsx"
> Microsoft Excel : Désolé... Nous avons trouvé un problème dans le contenu de "Classeur_Model - Copie.xlsxOUT.xlsx"

After confirm :
> Excel has completed file level validation and repair. Some parts of the workbook may have been repaired or abandoned.
> Deleted Part: Print Options.
> Deleted part: Drawing form.
> Excel a terminé la validation et la réparation de niveau fichier. Certaines parties du classeur peuvent avoir été réparées ou abandonnées.
> Partie supprimée: Options d'impression.
> Partie supprimée: Forme de dessin.

[Classeur_Model.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2488242/Classeur_Model.xlsx)
[Classeur_Model.xlsxOUT.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2488239/Classeur_Model.xlsxOUT.xlsx)

### What are the steps to reproduce?

  - Updating phpoffice/phpspreadsheet (1.0.0 => 1.2.1)
OK : no problem

  - Updating phpoffice/phpspreadsheet (1.2.1 => 1.3.0)
KO : the problem appears

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// $model = __DIR__ . DIRECTORY_SEPARATOR . 'Classeur_Empty.xlsx';
$model = __DIR__ . DIRECTORY_SEPARATOR . 'Classeur_Model.xlsx';

$fileOut = $model . 'OUT.xlsx';

$spreadsheet = IOFactory::load($model);

$worksheet = $spreadsheet->setActiveSheetIndex(2);
$worksheet->setTitle('Mesures Avant');

$worksheet = $spreadsheet->setActiveSheetIndexByName('Mesures Avant');
$sheetIndex = $spreadsheet->getIndex($spreadsheet->getSheetByName('Mesures Avant'));
$spreadsheet->removeSheetByIndex($sheetIndex);	// without this removing, the output document is clean

$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save($fileOut);

// now try to open "Classeur_Model - Copie.xlsxOUT.xlsx" with Excel
```

### Which versions of PhpSpreadsheet and PHP are affected?
All PhpSpreadsheet versions since 1.3.0 are affected.
(Used PHP Version 7.1.22)

**Comment by oleibman** [comment]
Resolved by PR #1462 in May 2020. Leaving issue closed, removing stale label.
