### ISSUE TITLE
Excel getting deleted if saved twice after adding an image

### ISSUE THREAD

**Issue by wbelhomsi** [PHPOffice/PhpSpreadsheet#724]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Add the image again or do nothing

### What is the current behavior?

Saying file does not exist and then deleting the excel file

### What are the steps to reproduce?
So i have an excel sheet called hello.xlsx and im trying to add rows, text and images on it (image is called icon.png and is placed in the same directory as the excel)
if i call editExcelTest once everything works and the image is added.. if i call it again it will show the following:
![image](https://user-images.githubusercontent.com/40052755/47157416-f1c57100-d2f1-11e8-9b0f-52dc8e8c366f.png)

and then the file(excel) will be deleted.. please provide any assist you can 

Please note that if i comment the drawing part and run it multiple times it works like a charm.. but whenever i add an image, the next save will mess it up and delete the excel sheet 

My code:
```
<?php

namespace App\Services;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as writeXlsx;
use PhpOffice\PhpSpreadsheet\Reader\Xlsx as readXlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;

use Symfony\Component\DependencyInjection\ContainerInterface;

class EditExcelService {

   public function editExcelTest() {

    $reader  = new readXlsx();
    $spreadsheet = $reader->load('hello.xlsx');
    $spreadsheet->getActiveSheet()->setCellValue('A4', 'PhpSpreadsheet');

    //Add 2 rows on top
    $spreadsheet->getActiveSheet()->insertNewRowBefore(1, 2);

    // Adding an image
    $drawing = new Drawing();
    $drawing->setName('PhpSpreadsheet logo2');
    $drawing->setDescription('Logo2');
    $drawing->setPath('icon.png');
    $drawing->setHeight(36);
    $drawing->setCoordinates('A2');
    $drawing->setWorksheet($spreadsheet->getActiveSheet());

     $writer = new writeXlsx($spreadsheet);
     $writer->save('hello.xlsx');


    return "reply from edit";
  }

}
```

### Which versions of PhpSpreadsheet and PHP are affected?
 "phpoffice/phpspreadsheet": "^1.4"
PHP: 7.1.9
**Note:** i am using symfony 4.1.. but i don't think the problem comes from there

**Comment by oleibman** [comment]
Supplied code works correctly now. Calling it twice results in a spreadsheet (not deleted) with two identical images, as it should. Whatever the problem was, it seems fixed now. Leaving issue closed, removing stale label.
