### ISSUE TITLE
Autofilter in Xlsx with $A:$F throws "Invalid cell coordinate A"

### ISSUE THREAD

**Issue by CybotTM** [PHPOffice/PhpSpreadsheet#727]
This is:

```
- [X] a bug report
```

### What is the expected behavior?

Having a Xlsx with autofilters on areas defined by $A:$F are loaded without errors

### What is the current behavior?

Exception "Invalid cell coordinate A"

### What are the steps to reproduce?

Create an Xlsx with autofilter over area $Table1.$A:$F

1. new Xlsx
2. Enter some column labels in first row
3. mark whole sheet and hit "Autofilter"
4. save under /var/www/html/web/template.xlsx

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load('/var/www/html/web/template.xlsx');
// throws "Invalid cell coordinate A"
```

### Which versions of PhpSpreadsheet and PHP are affected?

- phpoffice/phpspreadsheet v1.4.1
- PHP 7.2.11

**Comment by CybotTM** [comment]
:-(

**Comment by oleibman** [comment]
Unable to duplicate. Issue must have been solved some time over the past 8 years. Leaving issue closed, removing stale label.
