### ISSUE TITLE
Could anyone tell me the availability of the following 3 files under the /Classes/PHPExcel/Chart directory

### ISSUE THREAD

**Issue by SpencerAshford** [PHPOffice/PhpSpreadsheet#728]
Hi All,

Recently I am developing an internal project that is related to phpexcel(It will not become a commericial product and we are not going to make money with it). I just found that the Axis.php, GridLines.php and Properties.php with in the 
https://github.com/PHPOffice/PHPExcel/tree/1.8/Classes/PHPExcel/Chart directory might be useful for it. 

However, I did not see any copyright notifications or claim within those 3 files like all the other ones. Therefore I would like to know if I could fork/copy and source those 3 php libraries for my project. Thank you!

**Comment by PowerKiKi** [comment]
You are in the wrong project, but the license of that project can be found there: https://github.com/PHPOffice/PHPExcel/blob/1.8/license.md
