### ISSUE TITLE
Spreadsheet getNamedRange returns null (1.5.0)

### ISSUE THREAD

**Issue by shashane** [PHPOffice/PhpSpreadsheet#739]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Retriveing named ranges from xlsx file.

### What is the current behavior?

namedRanges array in Spreadsheet object is empty

Works fine in 1.4.1. 
Breaking change on 1.5.0.

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object

$spreadsheet = IOFactory::load('My File.xlsx');
$range = $spreadsheet->getNamedRange('Range Name');
// 'My File.xlsx' contains a named range 'Range Name'
// $range is null
 
```

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet v1.5
Php  5.6.33

**Comment by guillaume-ro-fr** [comment]
I have exactly the same problem. Can you check if your worksheet title contains the `'` character in your `xlsx` file for the defined named range ?

In debug mode, I found that `extractSheetTitle` don't works as expected : 

Expected [in the documentation](https://github.com/PHPOffice/PhpSpreadsheet/blob/90bb4df777fdaab17310333e87e306b9a1fed97d/src/PhpSpreadsheet/Worksheet/Worksheet.php#L2722) : 
```php
extractSheetTitle("'testSheet 1'!A1", true) === ["testSheet 1", "A1"];
```

Actual : 
```php
extractSheetTitle("'testSheet 1'!A1", true) === ["'testSheet 1'",  "A1"];
```

The name in [`$pRange`](https://github.com/PHPOffice/PhpSpreadsheet/blob/90bb4df777fdaab17310333e87e306b9a1fed97d/src/PhpSpreadsheet/Worksheet/Worksheet.php#L2729) is for example `'Analyse du 1 Janvier 2018'` and [`getTitle()`](https://github.com/PHPOffice/PhpSpreadsheet/blob/90bb4df777fdaab17310333e87e306b9a1fed97d/src/PhpSpreadsheet/Spreadsheet.php#L724) return `Analyse du 1 Janvier 2018`.

**Comment by eigan** [comment]
Stacktrace:
![2019-01-10_748x63](https://user-images.githubusercontent.com/41789/50963583-6f51e500-14cd-11e9-8192-cbdf335b77ec.png)

src/PhpSpreadsheet/Reader/Xlsx.php
![2019-01-10_423x92](https://user-images.githubusercontent.com/41789/50963632-87296900-14cd-11e9-8323-077232f8e192.png)

**Comment by oleibman** [comment]
Appears to have been fixed in https://github.com/PHPOffice/PhpSpreadsheet/commit/09ab584a230de5ab05c787a8c5056990ce4e987a in August 2019.
