### ISSUE TITLE
InvalidArgument to load file

### ISSUE THREAD

**Issue by Saripark** [PHPOffice/PhpSpreadsheet#756]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [X] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I just need load for writting my excel.xls
My code works if i load with a local path(C:\.....)

### What is the current behavior?
I have an error Uncaught exception 'InvalidArgumentException' with message 'File "\\srvname\aaa\bb\Excel.xls"

### What are the steps to reproduce?

$spreadsheet = $reader->load("\\namesrv\test espace\bureau de l\'internet\Excel.xls");

i volontarily put spaces and apostrophes in my path because its my entreprise configuration

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.5 and php 7.2.11

**Comment by oleibman** [comment]
Code now throws Reader Exception rather than Invalid Argument Exception. However, the problem here appears to be that the backslashes need to be doubled in the file name in the code as supplied. Leaving issue closed, removing stale label.
