### ISSUE TITLE
When writing to xlsx, garbargeCollector fails with undefined offset

### ISSUE THREAD

**Issue by fholbrook** [PHPOffice/PhpSpreadsheet#758]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Write the spreadsheet to file.

### What is the current behavior?
Line 1218 of Spreadsheet.php throws an undefined offset: 4.

### What are the steps to reproduce?
Create spreadsheet 1 (new Spreadsheet())
Create spreadsheet 2 (new Spreadsheet())
Create worksheet in spreadsheet 1 
Cut worksheet from spreadsheet 1  
Paste worksheet into spreadsheet 2 
Remove default worksheet from spreadsheet 2
attempt to save to file
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet1 = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$spreadsheet2 = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$spreadsheet1->createSheet()->setTitle('myWorksheet');
//add some data and styles to 'myWorksheet'
$myWorksheet = $spreadsheet1->getSheetByName('myWorksheet');
$spreadsheet2->addSheet($myWorksheet);
//remove default worksheet
$spreadsheet2->removeSheetByIndex(
  $spreadsheet2->getIndex(
     $spreadsheet2->getSheetByName('Worksheet')
  )
);

$writer = IOFactory::createWriter($spreadsheet2, 'Xlsx');
$writer->save('/tmp/file');

```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.2.8
PHPSpreadsheet 1.5.0

**Comment by fholbrook** [comment]
Solved. No issue.

After a thorough review of the source code I found the function `addExternalSheet`. Using this function instead of `addSheet` fixed the problem.

**Comment by oleibman** [comment]
Problem was resolved. Removing stale label.
