### ISSUE TITLE
Setting password does not work

### ISSUE THREAD

**Issue by huguoliang** [PHPOffice/PhpSpreadsheet#761]
```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();

// Setting password does not work
$spreadsheet->getSecurity()->setLockStructure(true)->setWorkbookPassword("123456");

$worksheet = $spreadsheet->getActiveSheet();
$spreadsheet->setActiveSheetIndex(0);

// Here is the business logic code ... ...

$writer = new Xlsx($spreadsheet);
$Path = 'test.xlsx';
$writer->save($Path);
// add code that show the issue here...
```
The generated file can be opened and modified at will.

**Comment by makbul-khan** [comment]
`<?php

require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();

$spreadsheet->getActiveSheet()->getProtection()->setPassword('PhpSpreadsheet');
$spreadsheet->getActiveSheet()->getProtection()->setSheet(true);
$spreadsheet->getActiveSheet()->getProtection()->setSort(true);
$spreadsheet->getActiveSheet()->getProtection()->setInsertRows(true);
$spreadsheet->getActiveSheet()->getProtection()->setFormatCells(true);

$spreadsheet->getSecurity()->setLockWindows(true);
$spreadsheet->getSecurity()->setLockStructure(true);
$spreadsheet->getSecurity()->setWorkbookPassword("PhpSpreadsheet");

$writer = new Xlsx($spreadsheet);
$writer->save('helloworld.xlsx');`

I have this code and its generate helloworld.xlsx file but its not password protected.

**Comment by jamespavett** [comment]
Hello,

I am having the same issue. Anyone have any ideas?

**Comment by benshawuk** [comment]
Also having the same issue.. is this functionality broken?

**Comment by PaulMcRoar** [comment]
This should be reopened. Looks like this functionality hasn't worked in a long time, in the least the recipe should be taken out of the documentation.

**Comment by oleibman** [comment]
The sample code seems to work correctly with the latest release (18.0) and master. Are you seeing a different result?
![image](https://user-images.githubusercontent.com/10341515/121376488-6eb81580-c8f6-11eb-9435-b913070c5944.png)

**Comment by jamespavett** [comment]
@oleibman I believe he means setting password for entire workbook  with setWorkbookPassword not just a singular sheet.

Sheets seem to work fine. Workbook does not.

**Comment by oleibman** [comment]
Thank you for the explanation. At the workbook level, PhpSpreadsheet offers the ability to lock windows (this prevents users from moving, resizing, or closing the workbook window, or hide/unhide windows), and to lock structure (this prevents users from adding, moving, deleting, hiding, and renaming worksheets). Both of those seem to be correctly in effect for the generated workbook. Do you think otherwise?

It sounds like possibly you were expecting to be unable to even view the workbook without supplying a password. The documentation does not claim to be able to do that. I am not sure if that is possible, or what would be required if it is. I'll investigate.

**Comment by oleibman** [comment]
Adding a password to open the workbook involves encrypting and changing the structure of the entire document. It does not seem practical to add such a capability.

As a workaround, you could create one empty sheet which is visible, and hide the remaining sheets. Nobody would be able to unhide them without the workbook password.

Although the documentation is accurate as-is, I will try to change it to make explicit that adding a password to view the workbook is not available.

**Comment by oleibman** [comment]
Actually, it looks like the documentation is actually clear about this - `If you need to completely prevent reading a file by any tool, including PhpSpreadsheet, then you are looking for "encryption", not "protection".` If you nevertheless think it would be valuable to document the clumsy workaround I suggested above, I can consider doing that.

**Comment by jamespavett** [comment]
Probably being ignorant but is this really that difficult functionality to add? To me an option to set the workbook password sounds like it would protect the whole document.

Excel itself offers this functionality out of the box, in a couple of clicks you can apply a password to a workbook to protect the whole document.

Currently I use the following JavaScript tool which allows a password to easily be applied to XLS documents: https://github.com/ankane/secure-spreadsheet

**Comment by oleibman** [comment]
To me, it seems really difficult to add. However, thank you for mentioning secure-spreadsheet, which is, in fact, dependent on xlsx-populate to perform the encryption. I may study how xlsx-populate does it and see if it might be applicable here, but it's definitely not a short-term project.
