### ISSUE TITLE
background color to alternate rows or columns in PhpSpreadsheet (PhpOffice)

### ISSUE THREAD

**Issue by duongp131994** [PHPOffice/PhpSpreadsheet#762]
I have an excel sheet, it has color to alternate rows or columns (in excel: Home> Format as Table.).
I do not know how to get it in PhpSpreadsheet.
`PhpOffice\PhpSpreadsheet\Style\Fill`

**Comment by oleibman** [comment]
"Format as Table" just creates a new table. Table support in PhpSpreadsheet probably wasn't available when this ticket was opened, but it is now. Removing stale label, leaving issue closed.
