### ISSUE TITLE
Time Calculation is 00:00 until i double click the cells

### ISSUE THREAD

**Issue by Falseee** [PHPOffice/PhpSpreadsheet#765]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Calculation of cells which contains times
Example:

A1 => 03:00:00
A2 => 02:30:00

A3 =SUM(A1:A2) => 05:30:00

### What is the current behavior?
Currently the Sum Cell (A3) is empty.
If i double clicke the other Cells the Sum will calculate the couble clicked cell.

So if i have
A1 => 03:00:00
A2 => 02:30:00

And i double click A1 the sum cell shows 03:00:00, if i also double click A2 it show 05:30:00

### What are the steps to reproduce?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$data = [
 ['03:00:00'],
 ['02:30:00'],
 ['=SUM(A1:A2)']
];

$writer = new Xls($spreadsheet);
$writer->save('php://output');
```
I also tried to set the FormatCode or to use the setPreCalculateFormulas function.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet: ^1.5
PHP 7.2.11

**Comment by MarkBaker** [comment]
You're storing strings containing the values `'03:00:00'` and `'02:30:00'`, not timestamps.... if you want to sum these values, then you'll need to store them as actual MS Excel timestamps
