### ISSUE TITLE
Image offset width cannot be more that a cell width

### ISSUE THREAD

**Issue by jbtsp** [PHPOffice/PhpSpreadsheet#770]
This is:

```
- [x ] a bug report
- [x ] a feature request
```

### What is the expected behavior?

offset an image anywhere relative to a cell, even outside of the cell border

### What is the current behavior?

Image offset width cannot be more that a cell width.
This may also affect offset height.

### What are the steps to reproduce?

Sometimes I create a spreadsheet that is intentionally designed to be printed.

In Firefox when I open/download a PHPSpreadsheet generated xls file from our website it opens in Alibre Calc, I click the 'Edit Document' button in the upper right, then click the print preview one time, then again to hide print preview, and a vertical line appears which shows me what I think is the printer margin. 

I try to place an image in the center. The offset cannot be more than the cell width, so sometimes I have to change the starting cell. I print the page and then use a ruler and adjust the positioning.

Sometimes I change the spreadsheet columns widths dynamically, and this wrecks the centering of an image. If I could always start at cell A1 and have the offset be more than the cell width, then the centering would not be affected by dynamic cell width adjustments.

```php
<?php

// add code that show the issue here...
$objDrawing->setOffsetX($x) ;
```

### Which versions of PhpSpreadsheet and PHP are affected?
All.

**Comment by jbtsp** [comment]
I believe should be possible because Alibre Calc allows me to drag the PHPSpreadsheet image anywhere on the spreadsheet. Perhaps reviewing the code from Alibre Calc could aid in finding an adjustment for this issue.

**Comment by jesusantguerrero** [comment]
Why this one was marked as closed if it is not solved yet?

there's no way to center an image in a dynamic row
