### ISSUE TITLE
Rounding issue with calculated values using ROUNDUP function.

### ISSUE THREAD

**Issue by deterset** [PHPOffice/PhpSpreadsheet#774]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Value displayed in Excel Spread sheet is 280 I expected the same value to be returned by PhpSpreadsheet but what was being returned was a 281.

### What is the current behavior?
Value Returned was 281. Value Printed before ROUNDUP () ( using error_log('$number = '.$number); ) was 280. After the ROUNDUP($number,0); The returned value was 281.
A comparison of $number == int($number) determined they were not equal.
Here is a test Spread sheet showing the problem. Sheet1, Cell B3

[test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2580929/test.xlsx)

I therefore had to assume 280 was actually 280.000000000001. Some thing like that. I can't see any fraction when printed.

### What I did to fix this 

I modified the function ROUNDUP() in:  vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Calculation\MathTrig.php

After the 2 statements using Functions::flattenSingleValue I added this statement.

$number = round($number,$digits + 1);

This truncated the decimal values I could not see and that were causing the error. If There is a better way to fix this that would be great but this is working for me right now.

### What are the steps to reproduce?

    <?php
    require 'vendor/autoload.php';

        $inputFileName = 'test.xlsx';
        $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($inputFileName);
        $worksheet = $spreadsheet->getSheetByName('Sheet1');
        $value = $worksheet->getCell('B3')->getFormattedValue();

    ?><!DOCTYPE html>
    <html>
        <head>
            <title>Test</title>
        </head>
        <body>
            <div id="content">
                <h1>Test</h1>
                Value in (B3) = 820<br/>
                Value retrieved = <?=$value?><br/>
            </div>
        </body>
    </html>

### Which versions of PhpSpreadsheet and PHP are affected?

I downloaded a new copy of PhpSpreadsheet on 11/14/2018
Using PHP Version 7.1.9 , happens in other versions as well.

**Comment by oleibman** [comment]
For the sample spreadsheet, Excel shows a value of 820 (not 280) in Sheet2!D3. Current release of PhpSpreadsheet does the same (there have been recent changes to code for ROUNDUP and some other functions). Removing stale label, leaving issue closed.
