### ISSUE TITLE
Do i need composer to run phpspreadsheets ?

### ISSUE THREAD

**Issue by jessicastorm1986** [PHPOffice/PhpSpreadsheet#775]
This is a query, i want to know can i use this on a simple linux shared hosting cpanel or i need atleast a VPS.

I have run the samples in my local windows but when i copied the entire vendor folder inside xampp/htdocs they dont run, so i am bit confused i always need to open cmd and keep it in running state on the server or i have misunderstood something , please guide

**Comment by wast** [comment]
Do you require autoloader? What error do you get?
