### ISSUE TITLE
Formula Error: An unexpected error

### ISSUE THREAD

**Issue by fprina** [PHPOffice/PhpSpreadsheet#781]
This is:

```
- [X ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
calculate the formula as in Excel: 

Open a xlsm
Add data to some cells
Calculate a cell value 

### What is the current behavior?
A simple setCellValue and getCalculatedValue script return the following error:

```
Fatal error: Uncaught PhpOffice\PhpSpreadsheet\Calculation\Exception: Inputs!E22 -> Gross!C22 -> Gross!C77 -> Gross!C79 -> Gross!C37 -> Gross!C39 -> Gross!C40 -> Cost!M25 -> Cost!L25 -> Cost!F25 -> Selected Sum!B18 -> Formula Error: An unexpected error occured in /var/www/vhosts/testxmlx.local/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php:274 
Stack trace: 
#0 /var/www/vhosts/testxmlx.local/html/test/exp/rate/fp.php(22): PhpOffice\PhpSpreadsheet\Cell\Cell->getCalculatedValue() 
#1 {main} thrown in /var/www/vhosts/testxmlx.local/html/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Cell.php on line 274
```

As in the error message the Cells directly involved in the calculation are:
```
Inputs!E22 -> 	=IF(bMoreInputsRequired,"",ROUNDUP('Gross'!C22,2))

Gross!C22 ->	=C77
Gross!C77 ->	=IFERROR(C79+C81+C86+C92+C94,"No Scale Presented")
Gross!C79 ->	=C37*(1+PA_IPT)
Gross!C37 ->	=C17-SUM(C39,C44,C50,C52)
Gross!C39 ->	=SUM(C40:C42)
Gross!C40 ->	=('Cost'!$M$25*0.95/(1-In_Tolerance))/C15

Cost!M25 -> 	=IFERROR(B25*C25*L25*($M$5="No")+($M$5="Yes")*($M$54*TLR-(1+Financial_IPT)*$M$40-(1+Assistance_IPT)*$M$34)/(1+PA_IPT),0)
Cost!L25 -> 	=IFERROR(IF(F25<C25,F25/(C25*INDEX($AC$51:$AG$75,MATCH(A25,$AB$51:$AB$75,0),3)),((INDEX($AC$51:$AG$75,MATCH(A25,$AB$51:$AB$75,0),5)-1)/(INDEX($AC$51:$AG$75,MATCH(A25,$AB$51:$AB$75,0),1)-C25*INDEX($AC$51:$AG$75,MATCH(A25,$AB$51:$AB$75,0),3)))*(MIN(F25,$AC$79)-C25*INDEX($AC$51:$AG$75,MATCH(A25,$AB$51:$AB$75,0),3))+1)*IF(K25="No",1,1-IFERROR(INDEX(Assumptions!$E197:$AO197,MATCH(Product_Combination,Assumptions!$E$186:$AO$186,0)),0))*($M$5="No")+($M$5="Yes"),"-")
Cost!F25 -> 	=INDEX('Selected Sum'!$B18:$J18,MATCH("Yes",'Selected Sum'!$B$3:$J$3,0))

Selected Sum!B18 ->	=SUMIFS(Inputs!$X:$X,Inputs!$T:$T,$A18)
```
### What are the steps to reproduce?

Unfortunately I can't provide the xlsm, so you can't really reproduce the error.
Anyway this is our test code: 

```php
<?php
require(dirname(__FILE__) . "/../../../vendor/autoload.php");

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load(dirname(__FILE__) . "/data/test.xlsm");

$sheetData = $spreadsheet->getActiveSheet();

$spreadsheet->getActiveSheet()->setCellValue('B4','test');
$spreadsheet->getActiveSheet()->setCellValue('B5','12345');
$spreadsheet->getActiveSheet()->setCellValue('B9','1');
$spreadsheet->getActiveSheet()->setCellValue('B10','Public');
$spreadsheet->getActiveSheet()->setCellValue('B19','3');

$spreadsheet->getActiveSheet()->setCellValue('E4','XYZ_2018');
$spreadsheet->getActiveSheet()->setCellValue('E9','20');
$spreadsheet->getActiveSheet()->setCellValue('E10','10');
$spreadsheet->getActiveSheet()->setCellValue('E11','5');
$spreadsheet->getActiveSheet()->setCellValue('E13','10%');

echo $spreadsheet->getActiveSheet()->getCell('E22')->getCalculatedValue();
?>
```

We also have a similar error with just a reader / writer  script 
```php
<?php
require(dirname(__FILE__) . "/../../../vendor/autoload.php");

$reader = new \PhpOffice\PhpSpreadsheet\Reader\Xlsx();
$spreadsheet = $reader->load(dirname(__FILE__) . "/data/test.xlsm");


$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save(dirname(__FILE__) . "/data/save.xlsx");

?>
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet : 1.5.0 & dvelop
PHP: 7.2

Maybe it's relate to close issues #182

**Comment by i-telligence-af** [comment]
I'm having the same problem.

**Comment by xrm** [comment]
Since this still pops up in search results when looking for that error message:
the issue seems to be the unlimited range:
`Inputs!$X:$X` (same for `$T`).

As a workaround, try to replace it with a large range. For example:
`Inputs!$X1:$X100000`

**Comment by kashifumar** [comment]
My Code has been working fine for almost 2 years and suddenly I have started getting the same error

        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "phpoffice/phpexcel": "^1.8"

**Comment by kashifumar** [comment]
ok, found the issue, this happens when the formula in some cell is invalid, that would in normal excel case give an error or in some case excel auto-corrects it so you cant re-produce teh issue in excel in some case. in my case, some cells contained values like
=CONCATENATE("+", "2.")
which evaluates to +2. and there cant be a decimal at the end of the value in the cell

So debug your data

**Comment by akbarali1** [comment]
I have the same problem

My code

 ```
$formula = '=ЕСЛИОШИБКА(ВПР(B'.$i.';product!B2:C'.$product_count.';2;0);0)'; 
            $sheet->setCellValue('C'.$i, $formula);
```
Result 
=ЕСЛИОШИБКА(ВПР(B2;product!B2:C1761;2;0);0)

How can I fix it?

**Comment by MarkBaker** [comment]
> I have the same problem
> 
> My code
> 
> ```
> $formula = '=ЕСЛИОШИБКА(ВПР(B'.$i.';product!B2:C'.$product_count.';2;0);0)'; 
> $sheet->setCellValue('C'.$i, $formula);
> ```
> 
> Result =ЕСЛИОШИБКА(ВПР(B2;product!B2:C1761;2;0);0)
> 
> How can I fix it?

From the [documentation](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#write-a-formula-into-a-cell): When working with formulae 
 - Decimal separator is . (period)
 - Function argument separator is , (comma)
 - Matrix row separator is ; (semicolon)
 - English function names must be used

If you want to use formula in another language, then you need to use the [built-in translation helpers](https://phpspreadsheet.readthedocs.io/en/latest/topics/recipes/#locale-settings-for-formulae) to convert `$formula` to `en_us` locale rules before setting it as the cell value
