### ISSUE TITLE
Updated libs

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PhpSpreadsheet#79]
Some libs have been updated and so this project should follow to always have stable and up-to-date code:

- [ ] https://github.com/PhenX/php-svg-lib.git 0.1 -> 0.2
- [ ] https://github.com/tecnickcom/TCPDF.git 6.2.12 -> 6.2.13

**Comment by PowerKiKi** [comment]
DomPDF is up to date, and I don't think a patch release in TCPDF would change much (or it would break semver). Please next time submit a PR for the changes you would like to see.
