### ISSUE TITLE
Wrong Ids relations when sheet clone

### ISSUE THREAD

**Issue by cia1** [PHPOffice/PhpSpreadsheet#795]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Correct saved xlsx file.

### What is the current behavior?
File is broken.

### What are the steps to reproduce?
- I have xlsx document, contains one empty page with only one image (example file attached);
- load xlsx;
- clone first sheet and add to spreadsheet;
- save to a file.

```php
<?php
$template = IOFactory::load('some-src.xlsx');
$sheet = $template->getSheet(0)->copy();
$sheet->setTitle('Some sheet 2');
$template->addSheet($sheet);
$writer = new Xlsx($template);
$writer->save('some-dst.xlsx');
```

So... I unzip some-dst.xlsx and see file "xl/worksheets/_rels/sheet2.xml.rels":
<Relationship Id="rId1" Type=".../drawing" Target="../drawings/drawing2.xml"/>
<Relationship Id="rId1" Type=".../printerSettings" Target="../printerSettings/printerSettings1.bin"/>

There two relations have some Id (rId1).
Please, looks at the PhpOffice\PhpSpreadsheet\Writer\Xlsx\Rels::writeWorksheetRelationships(). I think that array $drawingOriginalIds have to contains items for new clonned page. I think there need to update array $drawingOriginalIds when any sheet will be cloned.

To fix this a use this way, but there is a very bad solution...
```php
<?php
$template = IOFactory::load('some-src.xlsx');
$sheet = $template->getSheet(0)->copy();
$sheet->setTitle('Some sheet 2');
$template->addSheet($sheet);

$raw = $template->getUnparsedLoadedData();
$drawingOriginalIds = $raw['sheets'][$sheet->getCodeName()]['drawingOriginalIds'];
$cnt = count($drawingOriginalIds);
$key = '../drawings/drawing' . $cnt . '.xml';
$drawingOriginalIds['../drawings/drawing' . ($cnt + 1) . '.xml'] = $drawingOriginalIds[$key];
$raw['sheets'][$sheet->getCodeName()]['drawingOriginalIds'] = $drawingOriginalIds;
$template->setUnparsedLoadedData($raw);

$writer = new Xlsx($template);
$writer->save('some-dst.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.1
Spreadsheet 1.5.2

**Comment by oleibman** [comment]
Resolved by PR #4162 in May 2020. Leaving issue closed, removing stale label.
