### ISSUE TITLE
hello everyOne are U meet this question on windows?

### ISSUE THREAD

**Issue by pigsney** [PHPOffice/PhpSpreadsheet#799]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

![Uploading image.png…]()

**Comment by pigsney** [comment]
![image](https://user-images.githubusercontent.com/34547102/49374348-0348c800-f73c-11e8-9119-801c4607db02.png)

**Comment by PowerKiKi** [comment]
Cannot reproduce with following code:

```php
<?php

use PhpOffice\PhpSpreadsheet\Shared\StringHelper;

require 'vendor/autoload.php';

var_dump(StringHelper::convertEncoding('abc', 'UTF-16LE', 'UTF-8'));
```

This is not directly related with PhpSpreadsheet. You should look for help into how to configure iconv properly on Windows.
