### ISSUE TITLE
ReadTheDocs documentation

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PhpSpreadsheet#8]
- [x] Documentation/markdown/ (using as base)
- [x] Documentation/PHPExcel AutoFilter Reference developer documentation.doc
- [x] Documentation/PHPExcel Function Reference developer documentation.doc
- [x] Documentation/PHPExcel User Documentation - Reading Spreadsheet Files.doc
- [x] Documentation/PHPExcel developer documentation.doc
- [x] Documentation/Functionality Cross-Reference.xls

**Comment by PowerKiKi** [comment]
@Progi1984, I didn't see much progress on this in the past weeks. But it seems all markdown files were created, even though doc files still exists... Is it done, or are you still working on it ?
