### ISSUE TITLE
[Calculation] Invalid locales loading

### ISSUE THREAD

**Issue by guillaume-ro-fr** [PHPOffice/PhpSpreadsheet#800]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

The locales should be properly loaded.

### What is the current behavior?

The locale names are truncated.

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
Settings::setLocale($locale);
```

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.1
Linux (Docker for Mac + PHP-FPM)
PhpSpreadsheet 1.5.2

### How to fix this
https://github.com/PHPOffice/PhpSpreadsheet/blob/501f5722be780cd60a43e7c041af40b3602324f0/src/PhpSpreadsheet/Calculation/Calculation.php#L2207-L2216
On `loadLocales` function, the `$localeFileDirectory` variable have an ending `/`, and the `substr` function starts on `+ 1`.
The `+1` or the `/` must be removed.

Debug : 
```php
// Before `substr`
$filename = '/var/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/locale/bg';
$localeFileDirectory = '/var/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Calculation/locale/';
// After `substr`
$filename = 'g';
```

**Comment by MarkBaker** [comment]
[PR-875](https://github.com/PHPOffice/PhpSpreadsheet/pull/875)
