### ISSUE TITLE
Hello World sample gives Error 500

### ISSUE THREAD

**Issue by guillefixx** [PHPOffice/PhpSpreadsheet#805]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
XLS file should be generated.

### What is the current behavior?
Server crashes at this line **$writer->save('hello world.xlsx')** : 

> This page isn’t working myserveraddress.abc is currently unable to handle this request.
> HTTP ERROR 500

I am under a Wordpress project. Could this cause any trouble?

### What are the steps to reproduce?

I did exactly what it is said on the docs. Requirements are all ok and I installed PhpSpreadsheet into my project using composer.

```php
<?php

require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'Hello World !');

$writer = new Xlsx($spreadsheet);

// This line makes server crash
$writer->save('hello world.xlsx');
?>
```

### Which versions of PhpSpreadsheet and PHP are affected?
I am using PHP 5.6.38 and PhpSpreadsheet 1.5.2

**Comment by frantzmiccoli** [comment]
You should enable error reporting, you would be able to see which precise line is causing the problem and probably solve it.

**Comment by guillefixx** [comment]
Thank you @frantzmiccoli 

It was a permissions issue:

> Warning: ZipArchive::close(): Failure to create temporary file: Permission denied in /var/www/project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php on line 398
> 
> Fatal error: Uncaught exception 'PhpOffice\PhpSpreadsheet\Writer\Exception' with message 'Could not close zip file hello world.xlsx.' in /var/www/project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php:399 Stack trace: #0 /var/www/project/test2.php(16): PhpOffice\PhpSpreadsheet\Writer\Xlsx->save('hello world.xls...') #1 {main} thrown in /var/www/project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php on line 399

**Comment by badz227** [comment]
how did you fix this bro?

**Comment by frantzmiccoli** [comment]
@badz227  Likely something like `chown -R www-data:www-data yourTargetDirectory` followed by `chmod -R 770 yourTargetDirectory`. The first command is giving the ownership of the directory in which you want to write to `www-data` which is likely to be your webserver user, and the second is allowing the user and group to read, write and execute in that same directory.
