### ISSUE TITLE
can't read a cell‘s content has different style by toArray() 

### ISSUE THREAD

**Issue by zarte** [PHPOffice/PhpSpreadsheet#808]
This is:

```
- [ *] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
get a cell‘s’ content

### What is the current behavior?

just get a part of cell’s  content

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...

  $spreadsheet = IOFactory::load($execlfile);  
  $sheetData = $spreadsheet->getActiveSheet()->toArray(null, true, true);  
```

```xml
----------------------------  
the xls content ：  
sheet1.xml：  
-<c r="P2" t="s" s="8">  
<v>14</v>  
</c>  
  
sharedStrings.xml：  
-<si>  
-<r>  
<t>I</t>  
</r>  
-<r>  
-<rPr>  
<sz val="11"/>  
<color theme="1"/>  
<rFont val="宋体"/>  
<family val="3"/>  
<charset val="134"/>
<scheme val="minor"/>
</rPr>
<t>OS</t>
</r>
<phoneticPr type="noConversion" fontId="2"/>
</si>
```  
  
### Which versions of PhpSpreadsheet and PHP are affected?
^1.2  
php5.6

**Comment by oleibman** [comment]
This appears to be a problem with phonetic guide data. Issue #1204 proposes a solution for that, but isn't quite complete. Removing stale label from this issue, leaving it closed.
