### ISSUE TITLE
Avoid using slow in_array() when no need for NULL values

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PhpSpreadsheet#81]
The PHP function `in_array()` is slow in performance compared to `isset()`. This has the fundamental reason that `in_array()` loops through the whole array an compares each key. `isset()` in contrast is only checking if the given key is set but it doesn't find `NULL` values because it cannot do this (see documentation of each functions).

I would go and rewrite PhpSpreadsheet so it uses isset() as I see no use for checking NULL values e.g. with `$filterTypes` in `src/PhpSpreadsheet/Worksheet/AutoFilter/Column.php`. Also e.g. `src/PhpSpreadsheet/Writer/Xls/Worksheet.php` uses it but you can do it otherwise:

````
if (!isset($lockingArray[$someLock])) {
    // Do some stuff
    // Stuff is done
    $lockingArray[$someLock] = TRUE;
}
````

**Comment by MarkBaker** [comment]
[in_array()](http://www.php.net/manual/en/function.in-array.php) doesn't check keys at all, it checks values in the array; so it performs a totally different function to [isset()](http://www.php.net/manual/en/function.isset.php)

**Comment by Quix0r** [comment]
Yes, sorry. That is what i mean. :-) I will make a PR where `in_array()` can be easily replace by isset() without breaking anything.

**Comment by PowerKiKi** [comment]
Closing after #82
