### ISSUE TITLE
mime_content_type for CSV can be return 'text/html'

### ISSUE THREAD

**Issue by nevigen** [PHPOffice/PhpSpreadsheet#811]
This is:

```
- [x] a bug report
```

When CSV file contains fields with some html tags (for example "&lt;a href=""...""&gt;link&lt;/a&gt;"), mime_content_type return 'text/html', not 'text/plain'. It need to add 'text/html' to array $supportedTypes in \PhpOffice\PhpSpreadsheet\Reader\Csv.php

```
        $type = mime_content_type($pFilename);
        $supportedTypes = [
            'text/html',
            'text/csv',
            'text/plain',
            'inode/x-empty',
        ];

        return in_array($type, $supportedTypes, true);
```

### Which versions of PhpSpreadsheet and PHP are affected?
php 7 and last PhpSpreadsheet

**Comment by PowerKiKi** [comment]
Seems to duplicate #564.

If your file has a `csv` extension it will be read, otherwise we try our best to guess, but it's only that a guess. If you know it's a CSV, then create the reader yourself, instead of relying on `IOFactory` guesswork.

**Comment by dmitrystas** [comment]
File has CSV extension, but mime_content_type return 'text/html'
