### ISSUE TITLE
Undefined Index reading hyperlinks in XLSX

### ISSUE THREAD

**Issue by billynoah** [PHPOffice/PhpSpreadsheet#817]
Recently I got an undefined index error reading every row of an XLSX due to [this line](https://github.com/PHPOffice/PhpSpreadsheet/blob/f0e69408caf87600fa4e9323b3d9ca1822740e78/src/PhpSpreadsheet/Reader/Xlsx.php#L1345).  The interpreter spit out something like this something like this:
```
PHP Notice:  Undefined index: rId707 in /root/scrape/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 1343
PHP Notice:  Undefined index: rId708 in /root/scrape/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 1343
PHP Notice:  Undefined index: rId709 in /root/scrape/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php on line 1343
```
It would be easy enough to check that the index isset and do something like:
```
if (isset($linkRel['id']) && isset($hyperlinks[(string) $linkRel['id']]) {
    $hyperlinkUrl = $hyperlinks[(string) $linkRel['id']]
```
But I figure someone smarter than myself could actually ascertain *why* the `$hyperlinks` array might be missing said index.

**Comment by billynoah** [comment]
Can someone please reopen this?

**Comment by oleibman** [comment]
Impossible to debug without a file that demonstrates the problem. Feel free to open a new issue if you have a file that still exhibits this problem. Leaving issue closed, removing stale label.
