### ISSUE TITLE
StringHelper sanitizeUTF8 iconv bug

### ISSUE THREAD

**Issue by TheWotan** [PHPOffice/PhpSpreadsheet#821]
/**
     * Try to sanitize UTF8, stripping invalid byte sequences. Not perfect. Does not surrogate characters.
     *
     * @param string $value
     *
     * @return string
     */
https://github.com/PHPOffice/PhpSpreadsheet/blob/00003fbe6853e95133c68abb47cafba3e95bb303/src/PhpSpreadsheet/Shared/StringHelper.php#L346

Please add //IGNORE to iconv because it NOT stripping invalid byte sequences but "remove" value, because iconv without ignore return false

**Comment by oleibman** [comment]
Fixed by PR #2910.
