### ISSUE TITLE
Custom Format not reading properly

### ISSUE THREAD

**Issue by johnlanz** [PHPOffice/PhpSpreadsheet#827]
If you have a custom format on excel like this: mm:ss.00
sample value: 12:26.34
$s = \PhpOffice\PhpSpreadsheet\IOFactory::load($file);
$data = $s->getActiveSheet()->toArray();
The reader outputs: 12:26.00
its always .00 regardless of what number you input

**Comment by oleibman** [comment]
Unable to duplicate. Problem must have been fixed in last 6+years. Removing stale label, leaving closed.
