### ISSUE TITLE
Internal table | Multiple tables

### ISSUE THREAD

**Issue by filipemansano** [PHPOffice/PhpSpreadsheet#83]
Hi, it's possible use multiples table in the same sheet?
each table using the your autofilter different... 

e.g. in table 

![image](https://cloud.githubusercontent.com/assets/6247393/22493133/300cce96-e815-11e6-8809-5a8fde1dd7cc.png)

The left table order your content in asc and the right table in desc... OR other possibility the right table in the first column filter by number equals XXXX and the left table by YYYY Understood?

this tool it's at top menu Insert > Table

![image](https://cloud.githubusercontent.com/assets/6247393/22493270/3c310664-e816-11e6-9a07-1dc70d658d86.png)

how to make this in PhpSpreadsheet??

**Comment by PowerKiKi** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/phpspreadsheet), or [Gitter](https://gitter.im/PHPOffice/PhpSpreadsheet).

Thank you!
