### ISSUE TITLE
can not read Chinese char csv file

### ISSUE THREAD

**Issue by langziyang** [PHPOffice/PhpSpreadsheet#834]
if my csv file has Chinese  char,when i  use load();i can not open the page;
`$reader = new \PhpOffice\PhpSpreadsheet\Reader\Csv();
//$reader->setInputEncoding('UTF-8');
$data=$reader->load('2.csv');
print_r($data);`

**Comment by MarkBaker** [comment]
If the charset isn't UTF-8, then you need to tell the Csv what charset it is

**Comment by weianguo** [comment]
Xlsx file,sheet name has Chinese char,Also can not open the page.

**Comment by oleibman** [comment]
No reason to think that Mark's answer is incorrect. Removing stale label. Leaving issue closed.
