### ISSUE TITLE
Not working in online server

### ISSUE THREAD

**Issue by deylann** [PHPOffice/PhpSpreadsheet#837]
$spreadsheet = new Spreadsheet(); this object
it's working in local but when going to live it's not working
please help how to solve this problem.

**Comment by UlrichEckhardt** [comment]
I hate to bring you that news, but "it's not working" is really not a suitable error description. As a first step, check the logs and reduce the code to a minimal but still complete example. Also, "local" and "live" are not sufficient descriptions for environments. You need to describe them and find out their differences. Chances are you will find the problem yourself on the way.

**Comment by oleibman** [comment]
As noted above, "not working" just isn't a good enough description. Leaving issue closed, removing stale label.
