### ISSUE TITLE
Support for Auto tables request

### ISSUE THREAD

**Issue by seyfer** [PHPOffice/PhpSpreadsheet#840]
This is:

```
- [ ] a bug report
- [*] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Possibility to create so-called `add ins` or Auto tables (Ctrl+D in Excel) tables. It is a table inside the sheet. An example
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-tables

### What is the current behavior?
Not supported.

### What are the steps to reproduce?
Trying tp achieve the same with Autofilter and changing background leads to different results in Excel. There is no way to create internally table inside the sheet as it is done here - https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-tables

### Which versions of PhpSpreadsheet and PHP are affected?
Latest php 7.3+ and latest PhpSpreadsheet version.

Connected issue: #358

**Comment by oleibman** [comment]
PhpSpreadsheet has supported tables for some time now. Leaving issue closed, removing stale label.
