### ISSUE TITLE
=NUMBERSTRING error

### ISSUE THREAD

**Issue by icy2003** [PHPOffice/PhpSpreadsheet#843]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I have a value shows like this,
![image](https://user-images.githubusercontent.com/12480850/50766872-cb422100-12b5-11e9-9b16-f999bcf07c6e.png)

### What is the current behavior?

php throws an error like that
![image](https://user-images.githubusercontent.com/12480850/50766937-ff1d4680-12b5-11e9-9e9d-aba103527f19.png)

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

use PhpOffice\PhpSpreadsheet\IOFactory;

include 'vendor/autoload.php';

$excel = __DIR__ . '/1.xlsx';
$spreadSheet = IOFactory::load($excel);
$data = $spreadSheet->getSheet(0)->rangeToArray('A23:X23');
var_dump($data);
```

### Which versions of PhpSpreadsheet and PHP are affected?
I installed phpspreadsheet by composer, the require option shows like 
```
"phpoffice/phpspreadsheet": "^1.5"
```

**Comment by oleibman** [comment]
Excel has not supported NUMBERSTRING for some time. PhpSpreadsheet never did. Removing stale label, leaving issue closed.
