### ISSUE TITLE
How i can change font size on chart title?

### ISSUE THREAD

**Issue by padrecedano** [PHPOffice/PhpSpreadsheet#847]
This is:

- [x] **not** explained function in the documentation
- [x] a feature request (perhaps)

Reading the documentation, is not explained how i can change font size for a chart title.

### What is the expected behavior?

Have different font size in title of chart.

### What is the current behavior?

The size are not changing.

### What are the steps to reproduce?

```php


<?php
$title= new \PhpOffice\PhpSpreadsheet\Chart\Title("titulo", null);
$title->getFont()->setSize(10); /*here: how i can set font size to 10pt?*/

$chart = new \PhpOffice\PhpSpreadsheet\Chart(
    'chart1',   // name
    $title,       // title
    $legend,       // legend
    $plotArea,  // plotArea
    true,       // plotVisibleOnly
    0,          // displayBlanksAs
    $xAxisLabel,       // xAxisLabel
    $yAxisLabel        // yAxisLabel
);

```

### Which versions of PhpSpreadsheet and PHP are affected?
Latest

### Question at Stackoverflow

[See here](https://es.stackoverflow.com/q/226761/29967) the question with this issue .

If i try this way, is not working:

```php
$spreadsheet->getActiveSheet()->getStyle('A1')->getFont()->setSize(10);
```
[See here](https://es.stackoverflow.com/a/228325/29967) the entire response at Stackoverflow.

**Comment by oleibman** [comment]
It looks like font size is written out only for a text run, not plain text. So, it's an ugly answer, but ...
```
$rt = new \PhpOffice\PhpSpreadsheet\RichText\RichText();
$tr = $rt->createTextRun('titulo');
$tr->setFont(new \PhpOffice\PhpSpreadsheet\Style\Font());
$tr->getFont()->setSize(10);
$title = new Title($rt);
```
