### ISSUE TITLE
Ods reader skips subsequent spaces

### ISSUE THREAD

**Issue by agopaul** [PHPOffice/PhpSpreadsheet#85]
Basically the reader class ignores the `<text:s>` tag, which is used when you have 2 or more consecutive spaces.

[See  the OpenDocument specs](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#element-text_s)

This is something that it's not implemented in the PHPExcel library either.

I worked on a [quick fix](https://github.com/redokun/PHPExcel/commit/a588c611bc5c51ab2dfa0019d124671ca3bc592e) (sorry for the code style change) which I'm still testing, but it is more of a dirty patch ATM, since the original implementation uses SimpleXML which to my understanding is insufficient for the purpose because of a missing option to traverse the XML tree down to the Node level. You can't access to mixed contexts where you have both Node and Element, and text nodes are not counted as children by SimpleXML.

This means that the whole class should be rewritten to use another XML parsing lib, like DOMDocument.

If the maintainers are willing to consider this change, I can work on a PR which would include: writing at least a few basic unit tests for the Ods reader class, migrating to DOMDocument and finally implementing a parser that takes `<text:s>` tags into account.

Edit: grammar

**Comment by PowerKiKi** [comment]
Your offer to help us much appreciated. Do you have argument in favor or against a migration to DOMDocument  in mind ? I am not particularly familiar with their differences and their availability/popularity...

**Comment by agopaul** [comment]
I looked at the class more carefully and I realized that a complete rewrite is not necessary. The only part affected by the refactoring would be a part of the `loadIntoExisting` method.

DOMDocument and SimpleXML share the same underlying C library (libxml2) and it seems that [they have similar performance](http://stackoverflow.com/questions/9367069/simplexml-vs-domdocument-performance). Having the same dependency (libxml2), they are both bundled with PHP when complied with the libxml option (no PECL necessary).

The main point against SimpleXML is that it's insufficient for reading the XML tree because it ignores the text nodes and therefore it cannot be used to parse XML parts with mixed text nodes and Elements.

See the comparison below:

**SimpleXMLElement**

    <?php  
    $xml = '<?xml version="1.0" encoding="UTF-8"?>
    <test>There are <s/>multiple spaces here <s/></test>';
    
    $s = new SimpleXMLElement($xml);
    
    foreach ($s as $item) {
    	/** @var $item \SimpleXMLElement */
    	var_dump($item->getName());
    }

    /*
     * Output:
     *
     * 's' (length=1)
     * 's' (length=1)
     */


**DOMDocument**

    <?php  
    $d = new \DOMDocument('1.0');
    $d->loadXML($xml);
    
    foreach ($d->firstChild->childNodes as $childNode) {
    	/** @var $childNode \DOMNode */
    	var_dump($childNode->nodeName);
    }
    
    /*
     * Output:
     *
     * '#text' (length=5)
     * 's' (length=1)
     * '#text' (length=5)
     * 's' (length=1)
     */

Notice how SimpleXML doesn’t allow to work with text nodes directly whereas DOMDocument does.
This is crucial when parsing strings like the one in the example as we need to concatenate each element and convert the `<text:s>` tags to one or more spaces.

**Comment by PowerKiKi** [comment]
I've read a few things, most notably [this](http://stackoverflow.com/questions/4803063/whats-the-difference-between-phps-dom-and-simplexml-extensions), and I fully agree that a move to DOMDocument would be welcomed.

If you can do the necessary work and cover it by unit tests, that would be very much appreciated. Again thank you for offering your help.

**Comment by PowerKiKi** [comment]
Closed via #98
