### ISSUE TITLE
Broken cell cache / cell data interference

### ISSUE THREAD

**Issue by AlexPravdin** [PHPOffice/PhpSpreadsheet#851]
This is:

```
- [X] a bug report
```

### Test script

```php
<?php
include 'vendor/autoload.php';
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$cell = $sheet->getCellByColumnAndRow(1, 1);
echo is_null($cell->getParent()) ? 'true' : 'false', "\n";
$sheet->getCellByColumnAndRow(1, 2);
echo is_null($cell->getParent()) ? 'true' : 'false', "\n";
```

### What is the expected behavior?
Test script outputs:
```
false
false

```
### What is the current behavior?
Test script outputs:
```
false
true

```

The script checks the same cell parent property. But by some unknown reason after fetching the second cell its parent property become null. How its possible?

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.3.1
PhpSpreadsheet 1.6.0

**Comment by AlexPravdin** [comment]
As I discrovered only the one cell at a time can be handled correctly. Is it mentioned somewhere in docs?

**Comment by oleibman** [comment]
A common problem, documented as best we can. See https://phpspreadsheet.readthedocs.io/en/latest/topics/accessing-cells/#beware-cells-and-styles-assigned-to-variables-as-a-detached-reference.

Removing stale label, leaving issue closed.
