### ISSUE TITLE
Access Array Out of range

### ISSUE THREAD

**Issue by xtayfhvk** [PHPOffice/PhpSpreadsheet#859]
This is:

### What is the expected behavior?
The program no longer continues

### What is the current behavior?
The program access array to  -1;

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
            $filename = '/home/test.csv';     // this file is  empty;   
            $reader = new \PhpOffice\PhpSpreadsheet\Reader\Csv();
            $reader->setInputEncoding('utf-8');
             $spreadsheet = $reader->load($filename);
            // get file total rows
            $total_line = $reader->listWorksheetInfo($filename)[0]['totalRows'];

nginx error stderr :
[error] 991#991: *82411 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: -1 in /usr/bastion/share/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Csv.php on line 194
### Which versions of PhpSpreadsheet and PHP are affected?
current version: 1.5.0

**Comment by peterdevpl** [comment]
Why don't you upgrade PhpSpreadsheet to the latest version? This bug has been fixed in https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.5.1
