### ISSUE TITLE
Read Excel Files With Macros

### ISSUE THREAD

**Issue by filipemansano** [PHPOffice/PhpSpreadsheet#86]
Is it possible to read excel (XLSM) files without removing the VBA macros contained in it?

**Comment by filipemansano** [comment]
a solução foi gerar um arquivo em excel em branco (xlsm), e armazenar as macros em vba e depois utilizar o metodo LOAD para carregar a template com a macro, e salvar a extensão como xlsm

**Comment by emeraldjava** [comment]
@filipemansano might there be an example of some php code which does the steps you've outlined above. I've a similar requirement with a xslm sheet but am unsure of the VBA template aspect of the solution.

**Comment by russeljo** [comment]
> LOAD

Is this method from phpspreadsheet?
