### ISSUE TITLE
Break xlsx file if you set image and print rule multiple sheet.

### ISSUE THREAD

**Issue by hirossyi73** [PHPOffice/PhpSpreadsheet#861]
This is:

```
- [*] a bug report
```

### What is the expected behavior?
File saved normally.

### What is the current behavior?
If you save a file using a template that has multiple sheets and each sheet has a print setting and some images on some sheets, the file is broken. 

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

1. Create a new template xlsx file.
2. Create multiple sheets in xlsx. (ex. create 4 sheets.)
3. Insert an image on each sheet. However, one sheet is set in the middle of the sheet, and a sheet with no image is set. (Do not save images on 3rd sheet)
4. On each sheet, set printer setting.Select "File" → "Print", and set printer (ex.Adobe PDF).
5. Save the above file in xlsx format.
6. Read the xlsx file you created and execute the following code with PhpSpreadSheet.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$path = "C:\\work\\Documents\\phpspreadsheet\\document.xlsx"; // the template file you created.
$reader = IOFactory::createReader('Xlsx');
$spreadsheet = $reader->load($path);

$writer = new Xlsx($spreadsheet);

$path_write = "C:\\work\\Documents\\phpspreadsheet\\output.xlsx"; // output file. this file is broken.
$writer->save($path_write);

```
If open output.xlsx, this is broken.
And recover this, the image of the next sheet of the sheet for which no image was set is lost.

You say "without relying on an external Excel file", but I found this bug only creating xlsx template file. So please create using this step.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.6.0
PHP 7.2.4

**Comment by hirossyi73** [comment]
I converted the output.xlsx file that I output to zip format and confirmed the configuration.
Then, \xl\worksheets\_rels\sheet4.xml.rels (the sheet where the image is gone) was output as follows.

~~~ xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing4.xml" />
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/printerSettings" Target="../printerSettings/printerSettings4.bin" />
</Relationships>
~~~

The same 'Id="rId1"' was output.
I think that this caused the link to be broken.

**Comment by garethellis36** [comment]
I've come across this bug as well. For me, "broken" means I get an error when opening the spreadsheet in Excel, which is repairable, but nonetheless annoying. In my case the issue is specific to the printer settings. If I change my template to a zip file and delete the printersettings.bin file, then save it back as an xlsx and let Excel repair it, the error goes away. But every time ti edit my template, the printer settings get restored.
