### ISSUE TITLE
Fatal error when loading xlsx-File containing a diagram sheet

### ISSUE THREAD

**Issue by mattbue** [PHPOffice/PhpSpreadsheet#862]
Hi,

i'm new to PhpSpreadsheet and want to use it to read Excel files for uploading the contained data into database after reading them.

Basically this is working. But when the Excel file contains a diagram sheet (created by right click on the sheet name a the bottom -> Insert ->Diagram) the following error is shown:

### Error message
```
Notice: Undefined index: rId2 in C:\...\php_spreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php on line 754

Fatal error: Uncaught TypeError: Argument 1 passed to PhpOffice\PhpSpreadsheet\Reader\Xlsx::readColumnsAndRowsAttributes() must be an instance of SimpleXMLElement, boolean given, called in
C:\...\php_spreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php on line 894 and defined in
C:\...\php_spreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php:2521 Stack trace: 
#0 C:\...\php_spreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php(894): PhpOffice\PhpSpreadsheet\Reader\Xlsx->readColumnsAndRowsAttributes(false, Object(PhpOffice\PhpSpreadsheet\Worksheet\Worksheet))
#1 C:\...\php_spreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\IOFactory.php(95): PhpOffice\PhpSpreadsheet\Reader\Xlsx->load('Test.xlsx')
#2 C:\...\php_spreadsheet\PhpSpreadsheetManager.php(23): PhpOffice\PhpSpreadsheet\IOFactory::load('Test.xlsx')
#3 C:\...\php_s in
C:\...\php_spreadsheet\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xlsx.php on line 2521
```

### What are the steps to reproduce?
For testing i'm using an Excel file named "Test.xlsx". The file is created with Microsoft Excel 2016 MSO (16.0.9126.2336) 32-Bit.

In the first sheet "Tabelle1" are the following values:

Value in cell A1: "Cell A1"
Value in cell B2: "Cell B2"

The diagram sheet is named "Diagramm2". It is just an empty diagram.

```php
<?php

    require_once("php_spreadsheet/vendor/autoload.php");
    use PhpOffice\PhpSpreadsheet\IOFactory;

    $file = IOFactory::load("Test.xlsx");
?>
```
When i delete the diagram sheet in the Excel file everything works fine.

### Which versions of PhpSpreadsheet and PHP are affected?
I've the following versions in use:
PHP Version: 7.2.0
PhpSpreadsheet Version: 1.6.0

Maybe i'm just doing something wrong... But cannot find what.

Thanks a lot for your help.

**Comment by thijs32748932** [comment]
Beste lezer,

In verband met vakantie ben ik niet bereikbaar.

Voor support vragen kunt u mailen naar support@testersuite.nl. 
Voor administratieve vragen kunt u mailen naar administratie@testersuite.nl.

Vanaf 30 april ben ik weer bereikbaar.

Met vriendelijke groet,
Thijs Schalk
Testersuite

**Comment by chartz** [comment]
I have the same error.
It occurs when the excel file contains a diagram sheet.

**Comment by sylvaincherrier** [comment]
I have the same error ?? And there is a diagram sheet also in the document.

**Comment by oleibman** [comment]
I do not know what a "diagram sheet" is. We did add support for "chart sheets" long after this issue went stale. On the assumption that "chart sheets" was meant, I am leaving this issue closed, but removing the stale label.
