### ISSUE TITLE
Support Databars and Color Scales

### ISSUE THREAD

**Issue by godsgood33** [PHPOffice/PhpSpreadsheet#864]
This is:

```
- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Support databar and color scale conditional formatting

### What is the current behavior?
No support

**Comment by dschwanke** [comment]
Very good to have DataBar formatting rule included.
Any plans for Color Scales? (cfRule type="colorScale")

**Comment by oleibman** [comment]
Databar support added by PR #1754. Colorscale support added by PR #3738.
