### ISSUE TITLE
OLE2LocalDate() bugged signature, bad accuracy and overflow detection

### ISSUE THREAD

**Issue by USalsi** [PHPOffice/PhpSpreadsheet#869]
The OLE2LocalDate() function gives invalid values while converting from OLE timestamps (units of 100 ns since 1601-01-01) to Unix timestamp (seconds since 1970-01-01), fails to detect int overflow on 32-bits systems and yields a bad precision due to the float 53-bits accuracy limit.

Proposed alternative implementation which works on both 32 and 64-bits systems:

	/**
	 * Decodes OLE timestamp into Unix timestamp.
	 * @param string $ole_ts A binary string with the encoded date in units of 100 ns
	 * elapsed since 1601-01-01, 8 bytes little endian.
	 * @return int The Unix timestamp corresponding to the string as number of
	 * seconds elapsed since 1970-01-01. The value could be negative for dates
	 * before 1970. On 32-bits systems, if the result overflows the int range,
	 * the closest min or max int value is returned.
	 */
	public static function OLE2LocalDate2($ole_ts) {
		if (strlen($ole_ts) != 8)
			throw new \InvalidArgumentException("Expecting 8 byte string");
		
		// convert to units of 100 ns since 1601:
		$a = unpack('v4', $ole_ts);
		$ts_hi = (float)$a[4] * 65536 + (float)$a[3];
		$ts_lo = (float)$a[2] * 65536 + (float)$a[1];
		
		// translate to seconds since 1601:
		$ts_hi /= 10000000;
		$ts_lo /= 10000000;

		// days from 1601 to 1970:
		$days = 134774;

		// translate to seconds since 1970:
		$ts = floor(65536.0*65536.0*$ts_hi + $ts_lo - $days * 24 * 3600 + 0.5);
		
		// check overflow on 32-bits systems:
		if( (int) $ts == $ts )
			return (int) $ts;
		else 
			return $ts >= 0.0? PHP_INT_MAX : PHP_INT_MIN;
	}

For example, the OLE timestamp for 1970-01-01T00:00:00+00:00 is

134774 days * 86400 s * 10000000 ns/s
= 0x019D B1DE D53E 8000 (units of 100 ns since 1601)
= pack("H16", "00803ed5deb19d01")

The current implementation translates this value into -430 seconds timestamp rather than to the expected 0. The proposed code gives the right result, detects int overflow that could occur on 32-bits systems, and has the correct signature.

**Comment by frantzmiccoli** [comment]
Hi,

I think that ideally you should produce a pull request for this:

1. Fork the project
2. Create a unit test that fails (there is no test on this function as far as I have looked)
3. Modify the function
4. Check that your test now pass 
5. Ensure that you are compliant with this guide https://github.com/PHPOffice/PhpSpreadsheet/blob/master/CONTRIBUTING.md
6. Submit your pull request ;)

**Comment by MarkBaker** [comment]
Implemented and Resolved
