### ISSUE TITLE
Incorred relation Id for existing drawings

### ISSUE THREAD

**Issue by oldurecu** [PHPOffice/PhpSpreadsheet#876]
This is:

```
- [X] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Open a file with a drawing in the 3rd sheet. Save it. Open it to view the content

### What is the current behavior?
Open it with excel raises a file corrupted error message
Open it with PHPSpreadsheet raises an error "Undefined index rId2"

### What are the steps to reproduce?
Here is the analysis
In the original file, the drawing is described by drawing1.xml and has "rId2" has relationship ID
Those data are stored in the $parent->unparsedLoadedData table

When saving, drawing1.xml is renamed drawing3.xml in the ZIP archive, but $unparsedLoadedData is not updated

So when the writer writes the drawing relations (Writer/Xlsx/Rels.php line 214), it looks in $unparsedLoadedData for drawing3.xml, does not find it and uses rId1 as relation ID instead of rId2 that is the original and actual one

I could submit a pull request to fix this, but I don't know the philosophy about handling both unparsedData and data that could be created/added with the library. If I simply update $unparsedLoadedData, I fear to create conflicts between unparsed content and managed content

Let me know how it should work

### Which versions of PhpSpreadsheet and PHP are affected?
1.6.0

**Comment by xklid101** [comment]
I can confirm that issue and I found out, that it is caused by adding worksheet before existing worksheet that contains those drawings.

So my temp solution would be to update `PhpOffice\PhpSpreadsheet\Spreadsheet::$unparsedLoadedData` during adding sheet if needed

According to writer - `/xl/drawings/drawing[N].xml` files are created by worksheet index in all spreadsheet - so `[N]` is replaced by current position of particular worksheet - and some other code in writers classes is not compatible with it (as mentioned in comment above) 

So the easiest solution I've found is this:
I added this code into method `PhpOffice\PhpSpreadsheet\Spreadsheet::addSheet` after sheet insertion
```php
// Adjust unparsedLoadedData
if($unparsedLoadedData = $this->getUnparsedLoadedData()) {
    $unparsedLoadedDataDoUpdate = false;
    $i = 1;
    foreach ($this->workSheetCollection as $sheet) {
        if(
            $i > $iSheetIndex && 
            isset($unparsedLoadedData['sheets'][$sheet->getCodeName()]['drawingOriginalIds']['../drawings/drawing' . ($i - 1) . '.xml'])
        ) {
            $unparsedLoadedData['sheets'][$sheet->getCodeName()]['drawingOriginalIds']['../drawings/drawing' . ($i) . '.xml'] =
                $unparsedLoadedData['sheets'][$sheet->getCodeName()]['drawingOriginalIds']['../drawings/drawing' . ($i - 1) . '.xml'];
            unset($unparsedLoadedData['sheets'][$sheet->getCodeName()]['drawingOriginalIds']['../drawings/drawing' . ($i - 1) . '.xml']);
            $unparsedLoadedDataDoUpdate = true;
        }
        $i++;
    }
    if($unparsedLoadedDataDoUpdate)
        $this->setUnparsedLoadedData($unparsedLoadedData);
}
```

and that works for me. I believe, that there is much better solution, but for "hotfix" i needed it is good enough ;)

So there is the whole method body i have with working drawings:
```php
public function addSheet(Worksheet $pSheet, $iSheetIndex = null)
{
    if ($this->sheetNameExists($pSheet->getTitle())) {
        throw new Exception(
            "Workbook already contains a worksheet named '{$pSheet->getTitle()}'. Rename this worksheet first."
        );
    }

    if ($iSheetIndex === null) {
        if ($this->activeSheetIndex < 0) {
            $this->activeSheetIndex = 0;
        }
        $this->workSheetCollection[] = $pSheet;
    } else {
        // Insert the sheet at the requested index
        array_splice(
            $this->workSheetCollection,
            $iSheetIndex,
            0,
            [$pSheet]
        );

        // Adjust active sheet index if necessary
        if ($this->activeSheetIndex >= $iSheetIndex) {
            ++$this->activeSheetIndex;
        }

        // Adjust unparsedLoadedData
        if($unparsedLoadedData = $this->getUnparsedLoadedData()) {
            $unparsedLoadedDataDoUpdate = false;
            $i = 1;
            foreach ($this->workSheetCollection as $sheet) {
                if(
                    $i > $iSheetIndex && 
                    isset($unparsedLoadedData['sheets'][$sheet->getCodeName()]['drawingOriginalIds']['../drawings/drawing' . ($i - 1) . '.xml'])
                ) {
                    $unparsedLoadedData['sheets'][$sheet->getCodeName()]['drawingOriginalIds']['../drawings/drawing' . ($i) . '.xml'] =
                        $unparsedLoadedData['sheets'][$sheet->getCodeName()]['drawingOriginalIds']['../drawings/drawing' . ($i - 1) . '.xml'];
                    unset($unparsedLoadedData['sheets'][$sheet->getCodeName()]['drawingOriginalIds']['../drawings/drawing' . ($i - 1) . '.xml']);
                    $unparsedLoadedDataDoUpdate = true;
                }
                $i++;
            }
            if($unparsedLoadedDataDoUpdate)
                $this->setUnparsedLoadedData($unparsedLoadedData);
        }
    }

    if ($pSheet->getParent() === null) {
        $pSheet->rebindParent($this);
    }

    return $pSheet;
}
```
I just tested it only for xlsx reader/writer - so no guarantees for other readers/writers (nor for other complex code in all writers)

**Comment by mth0mas** [comment]
I can confirm both the problem and the proposed solution. Thank you!
Should be re-opened and included in the next release

**Comment by oleibman** [comment]
Problem seems to have been resolved in 2020. Removing stale label, leaving closed.
