### ISSUE TITLE
Feature: set page order Over then down 

### ISSUE THREAD

**Issue by ntpnhan** [PHPOffice/PhpSpreadsheet#887]
Is there a feature "setting page order"
![2019-02-15_10-13-22](https://user-images.githubusercontent.com/16861888/52832367-d6853980-310a-11e9-88e8-3db03cf97c60.png)

```
- [ ] a bug report
- [x ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

**Comment by oleibman** [comment]
Support added with PR #1559 in July 2020.
