### ISSUE TITLE
First free cell - find cell empty

### ISSUE THREAD

**Issue by dimaregabriele** [PHPOffice/PhpSpreadsheet#895]
How can I understand which is the first free cell of a given column? Example I want to know which is the first free cell in column B

**Comment by MarkBaker** [comment]
What do you mean by free? A cell may contain a null, or an empty string, or a string of spaces, or a formula that evaluates to any of those, which all look "free"/"empty" in the Excel GUI, but contain valid values.... if you mean containing absolutely nothing, then the worksheet's `getHighestDataRow()` method will tell you if you pass it an argument of the column's address

**Comment by dimaregabriele** [comment]
for free I mean that nothing is written. in practice in column B will be written progressive numbers .. 1-2-3 .. I want to understand what is the first cell not written .. basically I want to understand where to write the next progressive number

**Comment by MarkBaker** [comment]
Then you should probably try using `getHighestDataRow()` first

**Comment by dimaregabriele** [comment]
could you post me some of the code?

**Comment by MarkBaker** [comment]
`$lastRowInColumnA = $myWorksheet->getHighestDataRow('A');`
