### ISSUE TITLE
feature request: resize comment box

### ISSUE THREAD

**Issue by jeandelcapitaine** [PHPOffice/PhpSpreadsheet#897]
This is:

```
- [ ] a bug report
- [ x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Be able to set the size of the comment boxes per cell

### What is the current behavior?
default size, no possibility to resize the box

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

### Which versions of PhpSpreadsheet and PHP are affected?
all

**Comment by denitsa-cm** [comment]
I would like to be able to do this as well.

**Comment by oleibman** [comment]
`setWidth`and `setHeight` have been available for this purpose for a very long time.
