### ISSUE TITLE
getCalculatedValue unexpectedly retains first calculated value, does not recompute value on subsequent calls

### ISSUE THREAD

**Issue by dennis-fedco** [PHPOffice/PhpSpreadsheet#898]
This is:

```
- [x] a bug report
```

### What is the expected behavior?

* `getCell($pCoordinate)->getCalculatedValue()` to provide a freshly-calculated value every time

### What is the current behavior?
* `getCell($pCoordinate)->getCalculatedValue()` is calculated once and it retains the first calculated value, no matter how many times it is called after the first time.

### What are the steps to reproduce?

```php
<?php
require __DIR__ . '/vendor/autoload.php';
// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$worksheet = $spreadsheet->createSheet(1);

$worksheet->setCellValue('B4', '=SQRT(SUMSQ(B2:B3))');

$worksheet->setCellValue('B2', 1);
$worksheet->setCellValue('B3', 1);
assert($worksheet->getCell('B4')->getCalculatedValue() === sqrt(1 * 1 + 1 * 1));

$worksheet->setCellValue('B2', 2);
$worksheet->setCellValue('B3', 2);
//the following assertion triggers a PHP Warning, when it is expected to pass without issue.
assert($worksheet->getCell('B4')->getCalculatedValue() === sqrt(2 * 2 + 2 * 2));
```

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.6.0
PHP 7.3.2 on Windows

**Comment by dennis-fedco** [comment]
I found that adding one of these lines fixes my issue:
```php
use \PhpOffice\PhpSpreadsheet\Calculation\Calculation;
Calculation::getInstance($spreadsheet)->disableCalculationCache();
Calculation::getInstance()->setCalculationCacheEnabled(FALSE);
```
I believe that such information needs to be a bit more clearly presented in the documentation, maybe next to the first mention of `getCalculatedValue` in here: https://phpspreadsheet.readthedocs.io/en/develop/topics/calculation-engine/

**Comment by MarkBaker** [comment]
You're right, this should probably be documented more clearly at the beginning of the [Calculation Engine](https://phpspreadsheet.readthedocs.io/en/develop/topics/calculation-engine/) documentation.

Execution of the calculation engine is costly in terms of performance, and it isn't uncommon to find that a group/column of cells all reference a cell or cells that have been previously calculated; so the default behaviour is that result caching is enabled

I shall update the documentation over the weekend... that is, if I haven't been hanged first

**Comment by dennis-fedco** [comment]
Thanks, it is quite beneficial I think for a sheet where you know that you can set values once, and then compute remaining values from there.  I was trying to run performance stress tests where I could set different values on the same sheet and ran into this behavior.
Why would you be hanged!?
