### ISSUE TITLE
How  reading csv file with field name based data rows ?

### ISSUE THREAD

**Issue by sergeynilov** [PHPOffice/PhpSpreadsheet#900]
Hi,
Using in my laravel 5.7 (php 7.2 )app I installed "phpoffice/phpspreadsheet": "^1.6" and reading csv file with method
```
        $filename = public_path('/upload/csv/clients.csv');
        $reader = new \PhpOffice\PhpSpreadsheet\Reader\Csv();
        $spreadsheet = $reader->load($filename);
```

I got integer indexes files in result set and I have to skip 1st row with fields names listing
If there is a way to get first row names as indexes of all data rows? If yes, please example...

Thanks!

**Comment by sergeynilov** [comment]
Also, looks like any row is splitted by backspace, not by comma as usually valid separator for csv.
So I got invalid results. How to set separator for csv file lines ?

**Comment by MarkBaker** [comment]
The Csv Reader tries to infer the separator unless you specify one to use; you can specify a separator explicitly if necessary:
```
$filename = public_path('/upload/csv/clients.csv');
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Csv();
$reader->setDelimiter(",");
$spreadsheet = $reader->load($filename);
```
Although it should never split on a backspace unless you explicitly set it to do so: the list used for inferring the separator is `[',', ';', "\t", '|', ':', ' '];`
