### ISSUE TITLE
Error opening xlsx in Excel 21013

### ISSUE THREAD

**Issue by simply-phil-1** [PHPOffice/PhpSpreadsheet#905]
This is:

```
- [x] a bug report
```

### What is the expected behavior?
Open spreadsheet without errors

### What is the current behavior?
"We found a problem with some content in '...' Do you want us to try to recover as much as we can

### What are the steps to reproduce?

Error is because of this line:
```$this->writeDefaultContentType($objWriter, 'vml', 'application/vnd.openxmlformats-officedocument.vmlDrawing');```
If the line is removed, the spreadsheet loads without error.  Can you make this line optional, or provide an interface allowing us to customize this file?

### Which versions of PhpSpreadsheet and PHP are affected?

Bug is in the latest

**Comment by parthkharecha** [comment]
@simply-phil-1  Found any solution?
