### ISSUE TITLE
Crash if search cell range doesn't contain row numbers

### ISSUE THREAD

**Issue by DanielMalmgren** [PHPOffice/PhpSpreadsheet#911]
A cell range in Excel can omit the row numbers, ie instead of using "C1:C100" I can put the range in as "C:C", meaning the whole column. This mostly works, but when the first argument (the search range) of the SUMIF formula contains a range without row numbers, I get a crash with the following error:

Data!J1 -> Undefined offset: 1

(J1 in this case is the cell where I've got the formula)

This is in an xlsx file that I first import (IOFactory::load()) and then save again (normally after inserting some values, but I've also tried without doing anything more in between). The crash occurs when I call save().

Using phpspreadsheet 1.6.0 on PHP 7.2.

Relevant part of stacktrace follows:

```
#0 /home/vagrant/Code/Lab/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1068): PhpOffice\\PhpSpreadsheet\\Cell\\Cell->getCalculatedValue()
#1 /home/vagrant/Code/Lab/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(1018): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx\\Worksheet->writeCell(Object(PhpOffice\\PhpSpreadsheet\\Shared\\XMLWriter), Object(PhpOffice\\PhpSpreadsheet\\Worksheet\\Worksheet), 'J1', Array)
#2 /home/vagrant/Code/Lab/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/Worksheet.php(76): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx\\Worksheet->writeSheetData(Object(PhpOffice\\PhpSpreadsheet\\Shared\\XMLWriter), Object(PhpOffice\\PhpSpreadsheet\\Worksheet\\Worksheet), Array)
#3 /home/vagrant/Code/Lab/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx.php(281): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx\\Worksheet->writeWorksheet(Object(PhpOffice\\PhpSpreadsheet\\Worksheet\\Worksheet), Array, false)
#4 /home/vagrant/Code/Lab/app/Http/Controllers/TimeSummaryController.php(45): PhpOffice\\PhpSpreadsheet\\Writer\\Xlsx->save('/tmp/phpxltmpTH...')
```

**Comment by MarkBaker** [comment]
PHPSpreadsheet supports cell references (e.g `A1`) and cell range references (e.g. `A1:B2`), but doesn't fully support row ranges (e.g. `1:1`) or column ranges (e.g. `A;A`)

**Comment by DanielMalmgren** [comment]
Ok. I guess that means this issue can be reclassified as a feature request :-)

Not important for me longer though, now that I've found the culprit I can just change my incoming Excel file to "C1:C1000" (or whatever) instead of "C:C".

**Comment by oleibman** [comment]
Following code returns correct result:
```php
        $data = [
            ['Name', 'Value', '=SUMIF(A:A,"Dave",B:B)'],
            ['Dave', 1],
            ['Susan', 2],
            ['Dave', 3],
            ['Susan', 4],
            ['Dave', 5],
        ];
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->fromArray($data);
        var_dump($sheet->getCell('C1')->getCalculatedValue());
```
Output is `9`, as it should be. Problem seems to have been solved in the intervening seven years. Leaving issue closed, removing stale label.
