### ISSUE TITLE
How to insert image in cell using foreach

### ISSUE THREAD

**Issue by kpramesh07** [PHPOffice/PhpSpreadsheet#913]
$drawing = new \PhpOffice\PhpSpreadsheet\Worksheet\Drawing();
    $drawing->setPath($idata['image']);
    $drawing->setCoordinates('A1');
    $drawing->setWorksheet($spreadsheet->getActiveSheet());
this not inserting image

**Comment by CamiloDiza** [comment]
Could you solve the problem?

**Comment by oleibman** [comment]
Will be solved by PR #4677. Removing stale label.
