### ISSUE TITLE
Formulas are not recalculated after the first call of cell::getCalculatedValue()

### ISSUE THREAD

**Issue by AlexPravdin** [PHPOffice/PhpSpreadsheet#914]
This is:

```
- [x] a bug report
```
### Test code

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$workbook = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$workbook->getActiveSheet()->setCellValue('A3', '=A1+A2');
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($workbook);
$writer->save('/var/f1.xlsx');
$workbook->getActiveSheet()->getCell('A2')->setValue(30);
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($workbook);
$writer->save('/var/f2.xlsx');
```

### What is the expected behavior?
When the `f2.xlsx` file is opened in Excel the `A3` cell contain value `30`.

### What is the current behavior?
When the `f2.xlsx` file is opened in Excel the `A3` cell contain value `0`.

### Code to proof issue

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$workbook = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$workbook->getActiveSheet()->setCellValue('A3', '=A1+A2');
$workbook->getActiveSheet()->getCell('A2')->setValue(30);
$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($workbook);
$writer->save('/var/f2.xlsx');
```

This code produces the correct `f2.xlsx` file with the `A3` cell value equal to `30` on file open. The issue only happen when workbook was saved before the `A2` cell value update.

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet 1.6.0

**Comment by AlexPravdin** [comment]
The issue is in the fact that formula calculation cache is not cleared when source cell value is changed:

```php
$workbook = new Spreadsheet();
$sheet = $workbook->getActiveSheet()
$sheet->setCellValue('A3', '=A2');
$sheet->getCell('A2')->setValue(30);
echo "A3 = " . $sheet->getCell('A3')->getCalculatedValue() . "\n";
$sheet->getCell('A2')->setValue(60);
 echo "A3 = " . $sheet->getCell('A3')->getCalculatedValue() . "\n";
```

This code will output 

>A3 = 30
>A3 = 30

But the expected result should be 

>A3 = 30
>A3 = 60

**Comment by MarkBaker** [comment]
This is something I recently added to the docs: [calculation cache](https://phpspreadsheet.readthedocs.io/en/latest/topics/calculation-engine/#calculation-cache)

Unless you explicitly disable it, saving a file executes the calculations in the spreadsheet, and the results are cached as for any formula calculations. Subsequent calls to `getCalculatedValue()` will return the cached result unless the cache is flushed, even if the underlying data has changed.

We can't afford to map calculation dependencies in the same way MS Excel itself does, and clear values from cache when an underlying value has changed; it's too big a memory overhead.

Recommendation is that you clear the cache manually after a save
