### ISSUE TITLE
MAXIFS PHP Fatal Error

### ISSUE THREAD

**Issue by Jam1eP** [PHPOffice/PhpSpreadsheet#915]
This is:

```
- [x] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

MAXIF is listed as supported function but the current Excel function is MAXIFS so either a bug or new feature request

### What is the current behavior?
MAXIFS throws Formula Error: Unexpected operator ':' if used with a normal range or
 Formula Error: Wrong number of aguments for IF() function if used with a named range

### Which versions of PhpSpreadsheet and PHP are affected?
PhpSpreadsheet v1.5.2 PHP 7.3

**Comment by oleibman** [comment]
Fixed by PR #1056.
