### ISSUE TITLE
Date::isDateTime returns true for string: abr01.html

### ISSUE THREAD

**Issue by jatubio** [PHPOffice/PhpSpreadsheet#916]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
\PhpOffice\PhpSpreadsheet\Shared\Date::isDateTime() returns false for a cell with the string `abr01.html`

### What is the current behavior?
\PhpOffice\PhpSpreadsheet\Shared\Date::isDateTime() returns true for a cell with the string `abr01.html`

### What are the steps to reproduce?
Create a new excel file with a cell with the string `abr01.html` and call to `\PhpOffice\PhpSpreadsheet\Shared\Date::isDateTime($cell)`

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.5.2

**Comment by MarkBaker** [comment]
```
$spreadSheet = new Spreadsheet();
$workSheet = $spreadSheet->getActiveSheet();

// Set details for the formula that we want to evaluate, together with any data on which it depends
$workSheet->setCellValue('A1', "abr01.html");

$cell = $workSheet->getCell('A1');

try {
    $result = \PhpOffice\PhpSpreadsheet\Shared\Date::isDateTime($cell);
    echo 'Result is ', $cell, PHP_EOL;
    var_dump($result);
} catch (Exception $e) {
    echo 'WTF: ', $e->getMessage(), PHP_EOL;
}
```
gives me output of
```
Result is abr01.html
bool(false)
```
So `isDateTime()` correctly returns false

**Comment by MarkBaker** [comment]
Perhaps this was a bug that has been changed since 1.5.2, though I'm not aware of any changes to that part of the code; but the latest code certainly doesn't demonstrate this bug

**Comment by MarkBaker** [comment]
But note that `isDateTime()` reads the **_format mask_** for the cell, not the value that it contains; and it is certainly possible that the format mask has been set to a date mask. This will have absolutely no effect on a non-numeric value.
