### ISSUE TITLE
ROUNDDOWN result is wrong, not the same as in Office Excel

### ISSUE THREAD

**Issue by UniFreak** [PHPOffice/PhpSpreadsheet#920]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

calculated formula `=ROUNDDOWN(30000.0, 0.0042, 3)` should return 378

### What is the current behavior?

calculated formula `=ROUNDDOWN(30000.0, 0.0042, 3)` returned 377

### What are the steps to reproduce?

```php

require __DIR__ . '/vendor/autoload.php';

$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$worksheet = $spreadsheet->getActiveSheet();

$worksheet->setCellValue('A1','30000');
$worksheet->setCellValue('A2','0.0042');
$worksheet->setCellValue('A3','3');
$worksheet->setCellValue('A4','=ROUNDDOWN(A1*A2*A3,0)');

echo $worksheet->getCell('A4')->getCalculatedValue(); // return 377, should be 378
```

### Which versions of PhpSpreadsheet and PHP are affected?

I'm using PHP5.6 and PHP7 with newest phpspreadsheet, but I guess this affects all version of PHP.

I'm guessing it's because phpspreadsheet use floor() to do rounddown() function, and because of the lose of precision in floating point calculation, 377 becomes 378. Using bc functions might solve the problem? I don't know.

**Comment by oleibman** [comment]
Working as desired now.
