### ISSUE TITLE
Doc comment typo for Worksheet::getHighestDataRow

### ISSUE THREAD

**Issue by sbarex** [PHPOffice/PhpSpreadsheet#921]
This is:

```
- [X] a bug report
```

### What is the current behavior?
The Doc comment of ```Worksheet::getHighestDataRow``` has `string` as return type. But the function return `int` (internally it call ```getHighestRow``` that return `int`).

### Which versions of PhpSpreadsheet and PHP are affected?
1.6.0

**Comment by oleibman** [comment]
Fixed by PR #880 in April 2019.
