### ISSUE TITLE
Undefined offset [XLS]

### ISSUE THREAD

**Issue by kieransudbury** [PHPOffice/PhpSpreadsheet#923]
### Errors occuring
```Errors
Notice: Undefined offset: 0 in C:\inetpub\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xls.php on line 3631
Notice: Undefined offset: 0 in C:\inetpub\vendor\phpoffice\phpspreadsheet\src\PhpSpreadsheet\Reader\Xls.php on line 4203
```

### My Code

```php
<?php
    require_once ("../vendor/autoload.php");
    $path = "sample.xls";
    $spreadsheet = PhpOffice\PhpSpreadsheet\IOFactory::load($path);
    print_r( $spreadsheet->getActiveSheet()->toArray(null, true, true, true) );
```

### Which versions of PhpSpreadsheet and PHP are affected?
I'm using the latest version of PhpSpreadhseet and PHP 7.0

### Additional Information
Errors repeat multiple times during execution

### See photo below
https://imgur.com/KMKMapF

**Comment by MAKS-dev** [comment]
You should disable Notice in your error-reporting.
http://www.php.net/manual/en/function.error-reporting.php
Something like:
`
// Report all errors except E_NOTICE
// This is the default value set in php.ini
error_reporting(E_ALL & ~E_NOTICE);
`

**Comment by oleibman** [comment]
Unable to diagnose without an affected file. Feel free to open a new issue if you think this is still an issue. Leaving issue closed, removing stale label.
