### ISSUE TITLE
Incomplete documentation and issue reading 2nd chunk.

### ISSUE THREAD

**Issue by MGParisi** [PHPOffice/PhpSpreadsheet#924]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Read the chunk appropriately

### What is the current behavior?
The second chunk returns  Nulls.
I've tried setting 				

				$chunkFilter->setRows($startRow, $chunkSize);
				$sheet = $reader->load($filepath);

crashes.

Adding 
$sheet = $spreadsheet->getSheet($sheetNumber);

works, but returns NULL on the second chunk for all the values.

### What are the steps to reproduce?

Not really sure, the code Im using is very complicated.  I had this working.  Now its not.  None of the chunk Documentation contains the sheet or how to use the data.  It only shows the load...

**Comment by MGParisi** [comment]
Hey Everyone, is the ChunkFilter documentation wrong? 

I tried it the way in the sample and I had many issues.  I then removed the load($filepath) from within the loop and only ran setRows inside the loop.  This seemed to be the only option that worked and did not run out of memory.

**Comment by oleibman** [comment]
Probably related to issue #1039. I investigated that issue yesterday, and found that ChunkReadFilter seems to now work correctly. Based on that, I am leaving this issue closed, but removing the stale label.
