### ISSUE TITLE
Read richtext cell value and convert it to html

### ISSUE THREAD

**Issue by santoshbadal1111** [PHPOffice/PhpSpreadsheet#925]
I am working on bulk import functionality using phpspreadsheet library. I want RichText datatype cell from excel to save as html so that i could use that styled html to user on web. 
following is my current code of reading excel file. 
inside $fileData array i want to get converted value of richtext cell in html format. 
any advice and suggestions will be greatly appreciated .

try{
    $spreadsheet = IOFactory::load('./uploads/import/'.$file);
    $sheet = $spreadsheet->getActiveSheet();
    $highestRow = $sheet->getHighestDataRow();
    $highestColumn = $sheet->getHighestDataColumn();
    $fileData=array();
    for($row = 1; $row <= $highestRow; $row++){
        $rowData = $sheet->rangeToArray('A' . $row . ':' . 
        $highestColumn . $row,NULL,TRUE,TRUE);
        if($this->isEmptyRow(reset($rowData))) { 
            continue; 
        }
        $fileData[]=$rowData[0];
    }
}catch(){

}

function isEmptyRow($row) {
        foreach($row as $cell){
            if (null !== $cell) return false;
        }
        return true;
    }

**Comment by santoshbadal1111** [comment]
Hey can you please have a look at request and suggest a way to achieve it plase.

**Comment by hyquoccuong** [comment]
I face same issue

**Comment by oleibman** [comment]
Html Writer does handle RichText. Perhaps I am not understanding what is the problem being reported here. But, for now, I am leaving the issue closed, and removing the stale label.
