### ISSUE TITLE
insert image

### ISSUE THREAD

**Issue by dimaregabriele** [PHPOffice/PhpSpreadsheet#927]
How do I insert an image into the xls file? the image is present on the server. format png.

**Comment by AndreyNazarchuk** [comment]
`
    $sheeti = new \PhpOffice\PhpSpreadsheet\Worksheet\Drawing();
    $sheeti->setName('name');
    $sheeti->setDescription('description');
    $sheeti->setPath('/filename.png');
    $sheeti->setHeight(90);
    $sheeti->setCoordinates("G14");
    $sheeti->setOffsetX(20);
    $sheeti->setOffsetY(5);
    $sheeti->setWorksheet($sheet);`

**Comment by leadstar116** [comment]
I can insert image into xls format file.
But when I write it into pdf using MPDF library, image is broken.
How can I fix this?

**Comment by danielpolifabro** [comment]
leadstar116, Its happing with me too.
I can save a totally formatted xlsx file (including images in header and footer)
but when I use Mpdf library to convert to PDF these resources dont apper.

**Comment by leadstar116** [comment]
Hi, Daniel

Did you try to set absolute path for image?
It works for me.
Give full path of image.
It will appear on pdf but with broken style, I guess.

**Comment by dimaregabriele** [comment]
I found that if I open the excel file, I insert the image, and save the file with another name there are no problems, otherwise it goes wrong.

**Comment by githubjeka** [comment]
Probably cause is https://github.com/PHPOffice/PhpSpreadsheet/issues/877#issuecomment-515455684

**Comment by oleibman** [comment]
Code from @AndreyNazarchuk is correct. We have samples and tests which write images to Pdf (e.g. 27_Images_Html_Pdf) without problem. Removing stale label, leaving issue closed.
