### ISSUE TITLE
Named ranges on worksheets with a space in their name are lost when saving

### ISSUE THREAD

**Issue by azine** [PHPOffice/PhpSpreadsheet#928]
This is:

```
- [ x] a bug report
- [ ] a feature request
- [ x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Ranges should work for xlsx spreadsheets with spaces in their sheet name.

### What is the current behavior?
When a spreadsheet contains a space or "!" in its name, any defined range will be lost when reading the workbook with the xlsx reader.

### What are the steps to reproduce?
1) With Excel (or OpenOffice), create a workbook with two spreadsheets ("Work Sheet1" & "WorkSheet2")
2) Define a named range for cell A1 on "Work Sheet1"
3) Reference that named range in a formula on "WorkSheet2"
4) Save the file with Excel (or OpenOffice) as `SampleFile.xlsx` file
5) Run the php code below 
6) Open the new `ModifiedFile.xlsx` in Excel & press "Ctrl-Shift-F9" to recalculate
7) Check the existence of the named range you defined in step 2.

```php
<?php

require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\IOFactory;


$reader = IOFactory::createReader('Xlsx');
$spreadsheet = $reader->load("SampleFile.xlsx");

$sheet = $spreadsheet->getSheetByName('WorkSheet3');
$sheet->setCellValue("A1", "Mofidied Cell Value");

$writer = new Xlsx($spreadsheet);
$writer->save('ModifiedFile.xlsx');
```

### Which versions of PhpSpreadsheet and PHP are affected?
Anything after https://github.com/PHPOffice/PhpSpreadsheet/pull/662
Named ranges work before commit 50a9bc8 and don't work after that.

**Comment by azine** [comment]
Here is a SampleFile.xlsx to run with the above code:
[SampleFile.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2958902/SampleFile.xlsx)

And the resulting ModifiedFile.xlsx with the missing "named ranges":
[ModifiedFile.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/2958903/ModifiedFile.xlsx)

**Comment by azine** [comment]
From a fist look, the following patch would fix the reading. 

```
diff --git a/src/PhpSpreadsheet/Reader/Xlsx.php b/src/PhpSpreadsheet/Reader/Xlsx.php
index eb52747..1ea5e14 100644
--- a/src/PhpSpreadsheet/Reader/Xlsx.php
+++ b/src/PhpSpreadsheet/Reader/Xlsx.php
@@ -1906,7 +1906,7 @@ class Xlsx extends BaseReader
                                         $extractedSheetName = $extractedSheetName[0];
 
                                         // Locate sheet
-                                        $locatedSheet = $excel->getSheetByName($extractedSheetName);
+                                        $locatedSheet = $excel->getSheetByName(trim($extractedSheetName,"'"));
 
                                         // Modify range
                                         list($worksheetName, $extractedRange) = Worksheet::extractSheetTitle($extractedRange, true);
```

But I don't know what other impact this would have AND if this would not better be fixed inside the function `\PhpOffice\PhpSpreadsheet\Spreadsheet::getSheetByName`.

As I see it, the problem is that the titles of ranges containing spaces or "!" and probably other characters too in the title are quoted with single-quotes in the workSheetCollection.

=> "Work Sheet1!A1" becomes "'Work Sheet1'!A1"

Because of these single-quotes, the correct sheet cannot be found when calling `getSheetByName`, so maybe fixing it here would be better?!

```
--- a/src/PhpSpreadsheet/Spreadsheet.php
+++ b/src/PhpSpreadsheet/Spreadsheet.php
@@ -721,7 +721,7 @@ class Spreadsheet
     {
         $worksheetCount = count($this->workSheetCollection);
         for ($i = 0; $i < $worksheetCount; ++$i) {
-            if ($this->workSheetCollection[$i]->getTitle() === $pName) {
+            if ($this->workSheetCollection[$i]->getTitle() === trim($pName, "'")) {
                 return $this->workSheetCollection[$i];
             }
         }
```

Opinions please?!

**Comment by azine** [comment]
Anyone?!

**Comment by azine** [comment]
Anyone?!

**Comment by mdryan** [comment]
Can confirm this bug and that your PR works for me.

**Comment by rkyoku** [comment]
Bug confirmed: still having a bug when sheet name contains a space character. My sheet is named "Vue dEnsemble" and I get the error `"undefined name  'Vue'"` when trying to put a chart in this sheet (the data series is `"Vue dEnsemble!$E$9:$E$18"`).

It fails in `processTokenStack()` method.
