### ISSUE TITLE
cannot read right background rgb when it is white color 

### ISSUE THREAD

**Issue by icy2003** [PHPOffice/PhpSpreadsheet#929]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

getRGB method seems wrong ?????see these pictures and I want some explainations
### What is the current behavior?
![aa](https://user-images.githubusercontent.com/12480850/54270733-0f55e880-45bb-11e9-9f78-c503aee07764.png)
![bbb](https://user-images.githubusercontent.com/12480850/54270754-17ae2380-45bb-11e9-9c91-601597178bf0.png)
![ccc](https://user-images.githubusercontent.com/12480850/54270761-1da40480-45bb-11e9-8230-24bb16ece387.png)
![ddddd](https://user-images.githubusercontent.com/12480850/54270772-21d02200-45bb-11e9-92ac-1b23054c665d.png)
 wtf the "isSupervisor" is???

if the background color is not white, I can get right rgb value.......

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
$a = $cell->getStyle()->getFill()->getStartColor();
$b = $cell->getStyle()->getFill()->getStartColor()->getARGB();

**Comment by oleibman** [comment]
Unable to duplicate. This seems to have been fixed in the intervening years. Leaving issue closed, removing stale label.
