### ISSUE TITLE
getEndColor()->getArgb() seems to return false values

### ISSUE THREAD

**Issue by alexmilde** [PHPOffice/PhpSpreadsheet#93]
Hi
i try to read the bgcolor of an xlsx file.
when i print_r "endColor" it shows the right color.
when i access the color it returns white.
![bildschirmfoto 2017-02-13 um 18 50 42](https://cloud.githubusercontent.com/assets/2182118/22895608/651a7bbc-f21d-11e6-8308-e7a93c410dba.png)

`$res = $cellStyle->getFill()->getEndColor(); // [argb:protected] => FF000000`
`$res = $cellStyle->getFill()->getEndColor()->getArgb(); // => FFFFFFFF`

Does anybody have a solution for this?

Thanks in advance
Alex

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. That way there will be more chance for the issue to be solved.

**Comment by alexmilde** [comment]
Thanks for your reply.
I attached the php and xlsx file.



```
require __DIR__ . '/Header.php';

$inputFileName = 'Excel-Test.xlsx';

$spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($inputFileName);
$cellStyle = $spreadsheet->getActiveSheet()->getStyle('A1');
$res = $cellStyle->getFill()->getEndColor(); // [argb:protected] => FF000000
$res = $cellStyle->getFill()->getEndColor()->getArgb(); // => FFFFFFFF

print_r($res);
[bgcolor-issue.php.zip](https://github.com/PHPOffice/PhpSpreadsheet/files/773791/bgcolor-issue.php.zip)

```


[Excel-Test.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/773781/Excel-Test.xlsx)

**Comment by PowerKiKi** [comment]
I know this won't be easy, but could you try to reproduce it without the .xlsx file ? by building the `$spreadsheet` only by code ?

**Comment by alexmilde** [comment]
no problem, i will try and update you.
but imho this wouldn't fix the issue with loading existing files and parsing the bg color.

**Comment by alexmilde** [comment]
You've led me into the right direction, thanks.
`getStartColor(`) holds the correct values and Works as expected.
IMO the issue can be closed.

**Comment by adrianbj** [comment]
I actually have the same problem with `getStartColor()`

![image](https://user-images.githubusercontent.com/871211/34829916-1ba79f94-f697-11e7-8bda-02ddb697cdf9.png)

Do you want a new is opened? It seems like it's really the same problem to me, so thought here might be best.

**Comment by PowerKiKi** [comment]
Can you reproduce only by code, without reading a file ?

**Comment by adrianbj** [comment]
@PowerKiKi - honestly, I haven't tried yet. I have created lots of xls files from code with the old PHPExcel library, but my current use need reading and I ended up going with the automatic HTML writer (straight to table).
