### ISSUE TITLE
If the file extension is "xlsx" and only the named cell is set, the program will not print it even if it is output to it.

### ISSUE THREAD

**Issue by yobee** [PHPOffice/PhpSpreadsheet#933]
This is:

```
- [ *] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What are the steps to reproduce?
Only named cells were set in the file with extension "xlsx". However, even if the program outputs to a named cell, it is not printed.

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
 // Apache POI fixes
        $contents = $archive->getFromName($fileName, 0, ZipArchive::FL_NOCASE);
        if ($contents === false) {
            $contents = $archive->getFromName(substr($fileName, 1), 0, ZipArchive::FL_NOCASE);
        }
```

Even if getFromName is executed, the data was not obtained named cell information. Is it normal operation?

### Which versions of PhpSpreadsheet and PHP are affected?
PHP version 7.1
phpspreadshee ver 1.4.0

**Comment by oleibman** [comment]
I am sorry, I do not understand this issue at all. Direct reading of the zip file seems like your own code, not PhpSpreadsheet's. Feel free to open a new issue if you feel it still applies. For now, leaving this issue closed, removing stale label.
