### ISSUE TITLE
disconnectWorksheets() not called on __destroy()

### ISSUE THREAD

**Issue by razvanphp** [PHPOffice/PhpSpreadsheet#941]
This is:

- [x] a bug report

### What is the expected behavior?

no memory-leak, unset/__destroy/disconnectWorksheets automatically called or at least `disconnectWorksheets()` called on unset.

### What is the current behavior?

OOM when not manually calling `disconnectWorksheets()`

### What are the steps to reproduce?

For ~150 xls files of 50 KB each, this script:

```php
<?php

require './vendor/autoload.php';

use \PhpOffice\PhpSpreadsheet\IOFactory;

$xls_files = glob("./import/*.xls");
$i = 0;

foreach ($xls_files as $xls_file) {
    $spreadsheet = IOFactory::load($xls_file);

    echo "\nMemory used: " . round(memory_get_usage() / (1024*1024)) . " MB for " . $i++ . ' files';

    // uncomment this and it will work
    // $spreadsheet->disconnectWorksheets();
    unset($spreadsheet);
}
```
returns:
```
....
Memory used: 124 MB for 166 files
Memory used: 124 MB for 167 files
Memory used: 125 MB for 168 filesPHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 36864 bytes) in /Volumes/Code/import-codificare/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Cells.php on line 400
```

### Which versions of PhpSpreadsheet and PHP are affected?

1.4 - 1.6

**Comment by kazitanvirahsan** [comment]
As you said, you have to manually call  $spreadsheet->disconnectWorksheets(); every time before loop ending every time. This will automatically call unset function as well. When your script complete execution, __destruct() function should be called by itself.

Hope this will clarify the matter.

**Comment by Jcs1994** [comment]
that's wierd though, why destruct is not called on unset()
![Deepin Capture-écran_zone de sélection _20190617165247](https://user-images.githubusercontent.com/29231226/59614105-5b677a80-9120-11e9-9b97-281566c4b359.png)

**Comment by oleibman** [comment]
`__destruct` isn't called because there are still live references to the spreadsheet (from each of its worksheets). Calling `disconnectWorksheets` will eliminate the circular references.

Leaving issue closed, removing stale label.
