### ISSUE TITLE
Support for PHPUnit 7 or later

### ISSUE THREAD

**Issue by broberts-mrmc** [PHPOffice/PhpSpreadsheet#946]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Would like to utilize PhpSpreadsheet and PHPUnit 7 or later.

### What is the current behavior?
As of the latest release (1.6), PhpSpreadsheet has PHPUnit locked at ^4.8.35|^5.4.0.

(https://github.com/PHPOffice/PhpSpreadsheet/blob/bf00f0cc5f55c354018f9a9ef15e6e3e1a229051/composer.lock#L32)

### What are the steps to reproduce?
composer require --dev phpunit/phpunit ^7

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```
composer require --dev phpunit/phpunit ^7

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: sebastian/object-enumerator[3.0.3, 2.0.1].
    - Can only install one of: sebastian/object-enumerator[3.0.3, 2.0.1].
    - Can only install one of: sebastian/object-enumerator[3.0.3, 2.0.1].
    - phpunit/phpunit 7.0.0 requires sebastian/object-enumerator ^3.0.3 -> satisfiable by sebastian/object-enumerator[3.0.3].
    - Installation request for phpunit/phpunit 7 -> satisfiable by phpunit/phpunit[7.0.0].
    - Installation request for sebastian/object-enumerator (locked at 2.0.1) -> satisfiable by sebastian/object-enumerator[2.0.1].


Installation failed, reverting ./composer.json to its original content.
```

### Which versions of PhpSpreadsheet and PHP are affected?
1.6

**Comment by oleibman** [comment]
Currently on PHPUnit 10.
