### ISSUE TITLE
Writer\Html->generateSheetData() outputs CSS when it shouldn't

### ISSUE THREAD

**Issue by tomas-eklund** [PHPOffice/PhpSpreadsheet#948]
This is:

```
- [x] a bug report (kind of)
- [x] a feature request (maybe - depends who you ask)
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

I would expect the `generateSheetData()` method of `Writer\Html` to only return the actual `<table>` with content/data and no styling - especially not global styling that affects the entire HTML page in which the table is displayed.

### What is the current behavior?

The `generateSheetData()` method (with the help of the private `setMargins()` method) returns a HTML string with starts with something similar to this:

```html
<style>
@page { margin-left: 0.7in; margin-right: 0.7in; margin-top: 0.75in; margin-bottom: 0.75in; }
body { margin-left: 0.7in; margin-right: 0.7in; margin-top: 0.75in; margin-bottom: 0.75in; }
</style>
    <table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0">
```

I consider this a violation of the separation of concerns principle. There should be one method to get the table (HTML markup and content) and another to get the styling (CSS). 

The current situation will seriously mess up the layout of any page on which you display the HTML table. One should not assume that the tables generated from this plugin all will be displayed individually, in their own HTML documents. Rather one should expect the tables to be embedded on various Internet pages along with other content, sometimes many tables on a single page.

I would expect the methods `generateStyles()` and `generateHTMLHeader()` to be the only methods to return CSS styles in this context.

### What are the steps to reproduce?

```php
<?php
require_once 'vendor/autoload.php';
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$html_writer = new \PhpOffice\PhpSpreadsheet\Writer\Html( $spreadsheet );
$html = $html_writer->generateSheetData();
$html = htmlentities( $html );
echo '<html><head><title></title></head><body>';
echo "<pre>$html</pre>";
echo '</body></html>';
```

Will output:

```html
<style>
@page { margin-left: 0.7in; margin-right: 0.7in; margin-top: 0.75in; margin-bottom: 0.75in; }
body { margin-left: 0.7in; margin-right: 0.7in; margin-top: 0.75in; margin-bottom: 0.75in; }
</style>
    <table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0 gridlines">
        <col class="col0">
        <tbody>
          <tr class="row0">
            <td class="column0">&nbsp;</td>
          </tr>
        </tbody>
    </table>
```

Whereas the expected output is:

```html
    <table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0 gridlines">
        <col class="col0">
        <tbody>
          <tr class="row0">
            <td class="column0">&nbsp;</td>
          </tr>
        </tbody>
    </table>
```

### Which versions of PhpSpreadsheet and PHP are affected?

The current as of today: 1.6.0

### How to fix

Easy: Remove line 1105 of .../Writer/Html.php

```php
$html .= $this->setMargins($pSheet);
```

**Comment by tomas-eklund** [comment]
Bumping to keep the issue active until resolved. It really can't be more thoroughly researched and the proposed fix is stated above.

**Comment by tomas-eklund** [comment]
It's not the issue that's stale, it's the project.

**Comment by PierrickMartos** [comment]
Same issue, @tomas-eklund proposition is great!

**Comment by PowerKiKi** [comment]
If you have a solution, you should create a PR for it, and keep in mind that it shouldn't break the most common use cases of outputting an entire HTML page

**Comment by r-ant-2468** [comment]
For my project I was only using this function for one page which had no margin anyway so I added the following css:

`body {
    margin: 0 !important;
}`

@tomas-eklund thanks for raising this issue.

**Comment by Suraxius** [comment]
I added a pull request to fix this (#1228). I hope this gets pulled soon so i don't have to keep patching my app after each update :/

**Comment by MarkBaker** [comment]
Thank you Suraxius.
To use, just call `setUseEmbeddedCSS(false)` before saving

**Comment by tomas-eklund** [comment]
> If you have a solution, you should create a PR for it, and keep in mind that it shouldn't break the most common use cases of outputting an entire HTML page

I would like to argue that removing arbitarily set margins on a html document is not _breaking_ any sensible use cases. The fix made by @Suraxius is great because at least it provides a workaround, but it is the original implementation that was "broken". 

Thanks guys for fixing this!
