### ISSUE TITLE
XLSX Reader associated irrelevant quote prefixed style

### ISSUE THREAD

**Issue by frantzmiccoli** [PHPOffice/PhpSpreadsheet#950]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?

Formula are correctly executed.

### What is the current behavior?

Style is identified has being prefixed by a quote. `$style->quotePrefix == true`

### What are the steps to reproduce?

I am not able to understand what is causing this, nor to produce a minimal reproduciable example.

### Which versions of PhpSpreadsheet and PHP are affected?

My code has been breaking since https://github.com/PHPOffice/PhpSpreadsheet/commit/033ed16db59a590905fdf9e7adec8ccf9bfa11de "Dde call safe handling" but I do not think that the problems comes from it as the styles are explicitly mentioning `quotePrefix`. I have unsuccessfully tried to understand what might be wrong here.

I am opening this ticket so people can report encounterx with similar problems.

**Comment by frantzmiccoli** [comment]
Not stale.

**Comment by melkamar** [comment]
Not stale.

**Comment by oleibman** [comment]
Might you be able to supply a code sample and/or spreadsheet that demonstrates your problem? I certainly can't figure out what the problem is from the information currently available in the ticket.

**Comment by endrsmar** [comment]
This problem is somehow linked to cell formatting, we've received two separate excel files from a customer that demonstrate this problem, unfortunately I can't of course provide those directly. I'm trying to produce an example sheet but so far I couldn't find the correct combination of formula/formatting that leads to this issue. Removing formatting from cells fixes this problem.

**Comment by oleibman** [comment]
Without a sample file, it's hard to say, but I believe that PR #3497, merged in 2023, is likely to solve this problem. Leaving issue closed, removing stale label.
