### ISSUE TITLE
Column->getColumnIndex() is confusingly named

### ISSUE THREAD

**Issue by tomas-eklund** [PHPOffice/PhpSpreadsheet#951]
This is:

```
- [x] a documentation bug report
```

### What is the problem?

The documentation is too vague on the behavior of the Column->getColumnIndex() method, especially considering the unfortunate naming choice. Intuitively one would expect the following code to work:

```php
foreach ( $worksheet->getColumnIterator() as $column ) {
    if ( $someCondition ) {
        $worksheet->removeColumnByIndex($column->getColumnIndex());
    }
}
```

But the above code doesn't work - because `getColumnIndex()` does not return a column **index** (`integer`) as expected by `removeColumnByIndex()`, it returns a column **address** (`string`). 

I realize of course that it is too late to change the name of the method, but the documentation should be more explicit in stating that `index` can mean different things in different situations, reflecting the inconsistent naming.

### What is the current behavior?

https://phpoffice.github.io/PhpSpreadsheet/master/PhpOffice/PhpSpreadsheet/Worksheet/Column.html#method_getColumnIndex

Currently the documentation states:

> string getColumnIndex()
> Get column index.

Granted, if you look closely you see that the method returns a `string`. But that is easy to overlook. To avoid confusion I would prefer that the documentation was more explicit. Something along the lines of:

> string getColumnIndex()
> Get column address, eg. 'A'.

**Comment by tomas-eklund** [comment]
Bumping to keep the issue active until resolved. It's easy enough to fix.

**Comment by tomas-eklund** [comment]
Bump.

**Comment by PowerKiKi** [comment]
Please suggest a PR to improve docs

**Comment by tomas-eklund** [comment]
I'm afraid I don't know how to do that. I'll try, but if you'd be so kind as to give me a pointer it would be greatly appreciated.
