### ISSUE TITLE
pivot table

### ISSUE THREAD

**Issue by ocin35** [PHPOffice/PhpSpreadsheet#952]
Hi,
please, ask yourself to create the few lines of code in the code below to create a PivotTable in the second sheet in integrand cells B1 to C6
I can not find examples and I am not competent enough
thank you

`<?php
//call the autoload
require 'PhpSpreadSheet/vendor/autoload.php';
//load phpspreadsheet class using namespaces
use PhpOffice\PhpSpreadsheet\Spreadsheet;
//call xlsx writer class to make an xlsx file
use PhpOffice\PhpSpreadsheet\IOFactory;

//make a new spreadsheet object
$spreadsheet = new Spreadsheet();
//get current active sheet (first sheet)
$sheet = $spreadsheet->getActiveSheet();

    //insert value
    $sheet->setCellValue('B1', 'A'); $sheet->setCellValue('C1', '1');
    $sheet->setCellValue('B2', 'A'); $sheet->setCellValue('C2', '2');
    $sheet->setCellValue('B3', 'A'); $sheet->setCellValue('C3', '3');
    $sheet->setCellValue('B4', 'B'); $sheet->setCellValue('C4', '1');
    $sheet->setCellValue('B5', 'B'); $sheet->setCellValue('C5', '2');
    $sheet->setCellValue('B6', 'B'); $sheet->setCellValue('C6', '3');

    // creat, rename and select second worksheets
    $spreadsheet->createSheet()->setTitle('Analyse');
    $spreadsheet->setActiveSheetIndex(1);

// Create pivot table???
    ????
    ????
    ????

    //set the header first, so the result will be treated as an xlsx file
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
//make it an attachment so we can define filename
$filnam = 'ExtractGePi_'.date('ymdhis').'.xlsx';
header('Content-Disposition: attachment;filename='.$filnam);
//header('Content-Disposition: attachment;filename="Result.xlsx"');
//create IOFactory object
$writer=IOFactory::createWriter($spreadsheet, 'Xlsx');
//save into php output
$writer->save('php://output');

?>`

**Comment by oleibman** [comment]
Implemented with PR #4942. Removing stale label, leaving issue closed.
