### ISSUE TITLE
Strip color information with specify colors

### ISSUE THREAD

**Issue by koutja** [PHPOffice/PhpSpreadsheet#955]
This is:

```
- [x] a bug report
```
Excel has [specify words](https://support.office.com/en-us/article/review-guidelines-for-customizing-a-number-format-c0a1d1fa-d3f4-4018-96b7-9c9354dd99f5?ui=en-US&rs=en-US&ad=US) for cell color information: 

* [Black]
* [Green]
* [White]
* [Blue]
* [Magenta]
* [Yellow]
* [Cyan]
* [Red]

Or can be set with [Color1], [Color2], etc. [Full list](http://dmcritchie.mvps.org/excel/colors.htm)

Bug due to move "strip color information" after match duration information in [this commit](https://github.com/PHPOffice/PhpSpreadsheet/commit/699da091760d39ddc9f0656b507b7c26b9dc4f4b), because this regual expression `'/(\[\$[A-Z]*-[0-9A-F]*\])*[hmsdy](?=(?:[^"]|"[^"]*")*$)/miu'` match with some specify colors

[example](https://regex101.com/r/17DLdv/3)
![image](https://user-images.githubusercontent.com/26272443/55670409-769a4c00-588c-11e9-82a1-a2be65cd5e48.png)

### What is the expected behavior?
```php
NumberFormat::toFormattedString(-12345, '[Cyan]0;[Red]0');
Expected :'-12345'
```
### What is the current behavior?
```php
NumberFormat::toFormattedString(-12345, '[Cyan]0;[Red]0');
Actual   :'[Wed, 18 Oct 1933 00:00:00 +0000193318]0'
```

### What are the steps to reproduce?

Add using specify color words who can match with duration cell formatting in [NumberFormatDates](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/tests/data/Style/NumberFormatDates.php) dataset for [NumberFormatTest](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/tests/PhpSpreadsheetTests/Style/NumberFormatTest.php) unit test

```php
[
        '-12345',
        -12345,
        '[Cyan]0;[Red]0',
],
[
        '12345',
        12345,
        '[Cyan]0;[Red]0',
],
```

Or u can run this code

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Style\NumberFormat;

NumberFormat::toFormattedString(-12345, '[Cyan]0;[Red]0');

```

### PhpSpreadsheet versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet
* 1.6 
* master

**Comment by koutja** [comment]
Alarm

**Comment by oleibman** [comment]
Interestingly, when that format is applied in Excel, the cell shows `12345` (in red), not `-12345`. PhpSpreadsheet does likewise. Leaving issue closed, removing stale label.
