### ISSUE TITLE
Format in cells reset, if they contain a value

### ISSUE THREAD

**Issue by FeBe95** [PHPOffice/PhpSpreadsheet#959]
This is:

```
- [x] a bug report
- [ ] a feature request
```

### What is the expected behavior?
Every cell in the targeted column/row is styled/formatted equally when using a "whole column" or "whole row" range.

### What is the current behavior?
Cells containing any value are not formatted at all, if the range is a whole column or row.

### What are the steps to reproduce?
```php
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$spreadsheet->setActiveSheetIndex(0);
$sheet = $spreadsheet->getActiveSheet();

$sheet->getCell("A1")->setValue("foobar");
$sheet->getStyle("1:1")->getAlignment()->setHorizontal("right");
// $sheet->getStyle("A:A")->getNumberFormat()->setFormatCode("@");
// $sheet->getStyle("A1:A1048576")->getNumberFormat()->setFormatCode("@");

header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="Example.xlsx"');
header('Cache-Control: max-age=0');

$writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
$writer->save('php://output');
```

### Additional information
I provided two additional example styles, each as a single-line comment, with the same result.
Changing the last row of the range to something smaller than 1048576 fixes it but is extremely slow (as each cells is formatted individually). If the value "foobar" is not set, its cell gets formatted correctly.

### Which versions of PhpSpreadsheet and PHP are affected?
- PHP: 7.1.14 (64bit Windows)
- PHPSpreadsheet: 1.6.0

**Comment by FeBe95** [comment]
for anyone having the same problem: I fixed it by setting up all styles first before inserting the data, eg.:

## Breaks formatting:
```php
$arrayData = [[1], [2], [3]];
$spreadsheet->getActiveSheet() ->fromArray($arrayData, NULL, 'A2');

$spreadsheet->getActiveSheet()->getStyle("A")->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$spreadsheet->getActiveSheet()->getStyle("A")->getFill()->getStartColor()->setARGB('FFFF0000');
```

## Works as expected:
```php
$arrayData = [[1], [2], [3]];

$spreadsheet->getActiveSheet()->getStyle("A")->getFill()->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID);
$spreadsheet->getActiveSheet()->getStyle("A")->getFill()->getStartColor()->setARGB('FFFF0000');

$spreadsheet->getActiveSheet() ->fromArray($arrayData, NULL, 'A2');
```

**Comment by oleibman** [comment]
Solution from @FeBe95 works. So does applying column/row styles using `applyFromArray`, as recommended in documentation. Leaving issue closed, removing stale label.
