### ISSUE TITLE
PHP 7.1 compatibility

### ISSUE THREAD

**Issue by PowerKiKi** [PHPOffice/PhpSpreadsheet#96]
There are currently [5 failing tests](https://travis-ci.org/PHPOffice/PhpSpreadsheet/jobs/202110926#L277) that prevent us to declare PHP 7.1 compatibility. Any help to solve those would be very much appreciated.

**Comment by ankitm123** [comment]
I see no one is assigned yet, I would like to jump on it, and see if I can help.

**Comment by PowerKiKi** [comment]
Any help with this is welcome, thank you for offering your help. You could submit separate PR for each tests or all at once, up to you.

**Comment by ankitm123** [comment]
3 issues were fixed, but the remaining 2 issues are due to the dompdf package. I changed composer.json file to require 0.8.0v for Dompdf, it still gives the same issue. I will look into it a bit more.
Check this link: https://github.com/dompdf/dompdf/releases/tag/v0.8.0

**Comment by ankitm123** [comment]
Updating to v0.8.0 for dompdf does fix the remaining issues. Take a look at the [passing tests](https://travis-ci.org/ankitm123/PhpSpreadsheet/jobs/204905445) for php 7.1.Now that the build completed for php 7.1, Do we need to keep php 7.1 in the allowed failure list? Guess not.
