### ISSUE TITLE
Incorrect type hint for Worksheet::insertNewColumnBefore()

### ISSUE THREAD

**Issue by aplum** [PHPOffice/PhpSpreadsheet#967]
This is:

```
- [x] a documentation bug report
```

### What is the problem?

The type hint for Worksheet::insertNewColumnBefore() seems to be wrong. `$pBefore` is documented as `int`, but I believe it should be `string`. The example value given in the description for the parameter is `'A'`, and the method throws an Exception if `is_numeric($pBefore)` return true.

https://github.com/PHPOffice/PhpSpreadsheet/blob/170671c616bfb31cf1684e95583e2749d3823cee/src/PhpSpreadsheet/Worksheet/Worksheet.php#L2067

**Comment by oleibman** [comment]
Fixed by PR #1031 on the same day that stalebot closed this.
