### ISSUE TITLE
Footer problem whit Mpdf

### ISSUE THREAD

**Issue by nerminnp** [PHPOffice/PhpSpreadsheet#968]
I'm experiencing a problem while trying to export excel file to PDF by using Mpdf library in Laravel. It doesn't exports excel footer (page numbers). I tried to create footers after creating by using the SetHTMLFooter() method, but getting error that this method doesn't exist. I wonder is there any solution for exporting page numbers, not just a contents from cells

**Comment by gmmaraccini** [comment]
This page is about the PhpSpreadsheet, to view the MPDF, click bottom
https://github.com/mpdf/mpdf

**Comment by oleibman** [comment]
There is a complicated way to get at least some of the functionality you want. See issue https://github.com/PHPOffice/PhpSpreadsheet/issues/2236. Removing stale label, leaving issue closed.
