### ISSUE TITLE
Tables, lists and names get lost in the process

### ISSUE THREAD

**Issue by seabasss** [PHPOffice/PhpSpreadsheet#972]
This is:

```
- [x ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
To load an excel file and the same file comes out with tables, dropdown lists and defined names

### What is the current behavior?
PhpSpreadsheet strips tables, dropdown lists and defined names and can't reach ranges from other sheets

### What are the steps to reproduce?
```
require 'vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader('Xlsx');
$spreadsheet = $reader->load("template.xlsx");

header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="result.xlsx"');
header('Cache-Control: max-age=0');

$writer = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save('php://output');
exit;
```
You need to load my Excel file and run it through for a complete example, which I can provide if needed. Here are two screenshots of before and after PhpSpreadsheet though:

![Screenshot 1](https://i.stack.imgur.com/xQ1LT.png)
![Screenshot 2](https://i.stack.imgur.com/wxbYA.png)

### Which versions of PhpSpreadsheet and PHP are affected?

PhpSpreadsheet: v1.6.0
PHP: v7.1.23

**Comment by seabasss** [comment]
Bump. Thank you!

**Comment by landall** [comment]
Will the feature be supported in the future?

**Comment by seabasss** [comment]
Wondering too. Thanks!

**Comment by udacityanna** [comment]
If your company needs to meet accessibility standards, this problem is important.

**Comment by cbepxpa3ym** [comment]
This issue is still active. Any plans to fix it?

**Comment by carloslabrador** [comment]
Do you know anything about this?

**Comment by seabasss** [comment]
Any news on this? Thanks!

**Comment by nmorell** [comment]
Any chances to re-open this issue?

**Comment by oleibman** [comment]
Can you upload a file which demonstrates the problem?

**Comment by oleibman** [comment]
No update in 2.5 years, and tables, list, and names are all supported. Removing stale label, leaving closed.
