### ISSUE TITLE
How do I store the xlsx to storage/public???

### ISSUE THREAD

**Issue by Niroj11** [PHPOffice/PhpSpreadsheet#973]
I tried to create an XLSX file and It works to store and all.

But as I use storage/ folder to store all the files that I use for the project. How can I directly save to the storage/public/spreadsheets folder using the writer???

**Comment by naitsirch** [comment]
This is a usage question, please ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet.
