### ISSUE TITLE
Setting 3.00 as decimal value from DB it changes to 3 int in excel sheet

### ISSUE THREAD

**Issue by deepakjoshii** [PHPOffice/PhpSpreadsheet#975]
This is:

```
- [ ] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
3.00

### What is the current behavior?
3

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
```
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

$data = [
  "name" => "Prod 1"
  "category" => "Category 7"
  "sku" => "SKU-PROD-1"
  "price" => 19
  "discount_price" => 0
  "stock" => 78
  "description" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu nulla lectus. Pellentesque lectus odio, ultrices in aliquet dignissim, aliquet in dolor. Mauris efficitur magna sapien, eget auctor lacus aliquam et. Proin ac blandit leo. Donec facilisis mauris eu turpis eleifend, et tincidunt nisl interdum. Curabitur massa diam, mollis et commodo ut, vehicula eu tortor."
  "group_sku" => "GROUP-SKU-1"
  "secondary_category" => "Category 1"
  "images" => ""
 		  "attribute1" => "3.00",
		  "attribute2" => "2.75",
		  "attribute3" => "",
		  "attribute4" => "",
		  "attribute5" => "0.00",
		  "extra1" => "Extra 7",
		  "extra2" => "",
		  "extra3" => "Extra 8",
		  "extra4" => "Extra 2",
		  "extra5" => "Extra 4",
];

 $spreadsheet->getActiveSheet()->fromArray($data);
 $writer = new Xlsx($spreadsheet);
 $writer->save(public_path($this->file));

**Comment by MarkBaker** [comment]
It's a numeric, so it's converted to a number in the spreadsheet by the default value binder; if you want to format it with decimals, then use an Excel number format mask; if you want to retain it as a string, then use a custom binder; or write the values individually with `setCellValueExplicit()` to retain its datatype as a string
