### ISSUE TITLE
undefined index $ error when excel has an autofilter

### ISSUE THREAD

**Issue by juanmacias** [PHPOffice/PhpSpreadsheet#976]
This is:
- [x ] a bug report

### What is the expected behavior?
Importing an Excel with autofilter should work.

### What is the current behavior?
undefined index $ error is generated.

### What are the steps to reproduce?
Take one Excel file, add autofilter to first row. And try to load.

### Which versions of PhpSpreadsheet and PHP are affected?
1.6.0

**Comment by lxShaDoWxl** [comment]
This problem actual in version 1.9.0
If added filter in google spreadsheets and download file
https://docs.google.com/spreadsheets/d/1qQhpDrSh9VGqNqrl22nDE7UQBaOL2NrIucq7vUkto_c/edit?usp=sharing
to error
`PHP Notice:  Undefined index: $ in vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/Coordinate.php on line 282`

example code

```<?php

use PhpOffice\PhpSpreadsheet\IOFactory;

require __DIR__.'/vendor/autoload.php';

$path = __DIR__.'/test2.xlsx';
/** @var \PhpOffice\PhpSpreadsheet\Reader\Xlsx $reader */
$reader = IOFactory::createReaderForFile($path);
$phpSpreadsheet = $reader->load($path);
$sheet = $phpSpreadsheet->getSheet(1);```

**Comment by astronati** [comment]
IMHO It should be fixed by https://github.com/PHPOffice/PhpSpreadsheet/pull/1326
