### ISSUE TITLE
数据格式异常

### ISSUE THREAD

**Issue by wvfeng** [PHPOffice/PhpSpreadsheet#977]
本地（windows环境）测试中，把一列单元格设置成文本格式，并填充数据（数字字符串）发现没有问题，代码同步到线上（Linux环境）发现数据格式不正确，单元格格式显示是文本，但是值却显示为科学计数法形式，且精度已经丢失。

**Comment by wvfeng** [comment]
问题来源于`PhpOffice\PhpSpreadsheet\Cell\DefaultValueBinder::dataTypeForValue($pValue)`,第66行处PHP_INT_MAX常量在32位版本中的值为：2147483647，而在某些64位的版本中值为：9223372036854775807，导致对于同一个数据本地和线上试别产生了差异

**Comment by oleibman** [comment]
I believe this problem would be resolved by PR #4527. Removing stale label, leaving issue closed.
