### ISSUE TITLE
PHPSpreadsheet generates an error “Wrong number of arguments for INDEX() function: 5 given, between 1 and 4 expected”

### ISSUE THREAD

**Issue by Noctis17** [PHPOffice/PhpSpreadsheet#979]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
I tried a certain code in my excel sheet, "=INDEX($E$4:$E$38, AGGREGATE(15,6,ROW($1:$38) / ($J$4:$J$38=M5), COUNTIF($M$4:M5, M5)))" and works perfectly fine

### What is the current behavior?
But when I code it in my PHP application (using CodeIgniter framwork) it displays an error “Wrong number of arguments for INDEX() function: 5 given, between 1 and 4 expected”, which is kinda off

### What are the steps to reproduce?
I saw a Stackoverflow post but with is using a different function -> https://stackoverflow.com/questions/18934750/countif-phpexcel-wrong-number-of-arguments, tried to duplicate the said fix but does not work for the "INDEX()" function

I also created a StackOverflow post for further reference -> https://stackoverflow.com/questions/56018814/phpspreadsheet-generates-an-error-wrong-number-of-arguments-for-index-functio

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$ews= new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...

//The variables $occurance and $top_cell here have values that dynamically targets the right cell 
//address, please assume that its working fine -- which is, it really is fine

// The "code" variable is a string which contains my formula
$code = "=INDEX(\$E\$4:\$E\$$occurance, AGGREGATE(15,6,ROW(\$1:\$$occurance) / (\$J\$4:\$J\$$occurance=M$top_cell), COUNTIF(\$M\$4:M$top_cell, M$top_cell)))";
$ews->setCellValue("L$top_cell", $code);

//The "ews" variable is the spreadsheet variable
$ews->setCellValue("L$top_cell", $code);

### Which versions of PhpSpreadsheet and PHP are affected?
- PhpSpreadsheet v 1.6
- Php v5.2

**Comment by oleibman** [comment]
I'm not really sure how to populate the worksheet so that the formula above returns a 'real' answer. However, leaving the worksheet empty, and evaluating the formula with `getCalculatedValue`, the result is `#VALUE!`, not the error message mentioned in the title. Removing the stale label, leaving the issue closed.
