### ISSUE TITLE
CSV export Chinese plus bom, editing and garbled

### ISSUE THREAD

**Issue by it-hjm007** [PHPOffice/PhpSpreadsheet#982]
### What is the expected behavior?

I want to export utf-8 Chinese using CSV, so I add bom. 

### What is the current behavior?

Check no problem, after editing will be garbled

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$data = [['id','name'],[1,'我的名字']];
$file = 'test.csv';
header("Content-type:text/csv");
header("Content-Disposition:attachment;filename=\"" . $file . "\"");
header('Cache-Control:must-revalidate,post-check=0,pre-check=0');
header('Expires:0');
header('Pragma:public');
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->fromArray($data,null,'A1',true);

$writer = new PhpOffice\PhpSpreadsheet\Writer\Csv($spreadsheet);
$writer->setUseBOM(true);
$writer->save('php://output');

```

### Which versions of PhpSpreadsheet and PHP are affected?
Latest version and php7.1

Export Chinese, is there a better choice under big data?

**Comment by zhaofeng-shu33** [comment]
I also find a problem related with BOM. Since my php code contains Chinese characters, I save it in utf-8 encoding with BOM. However, it will produce corrupted xlsx files when downloading xlsx from http://.../get_xlsx.php. Removing the BOM from php code fixes the problem.

**Comment by oleibman** [comment]
Supplied code seems to execute okay now.
