### ISSUE TITLE
Incorrect page Breaks while export to Xlsx format

### ISSUE THREAD

**Issue by aircokol** [PHPOffice/PhpSpreadsheet#987]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
![image](https://user-images.githubusercontent.com/18220789/57764572-620f6600-770c-11e9-99eb-7516646c3256.png)
That's how it looks in the Excel itself and it works correctly while exporting to `xls` format.

### What is the current behavior?
![image](https://user-images.githubusercontent.com/18220789/57764486-3e4c2000-770c-11e9-964c-49c05a094b96.png)
Looks like in Xlsx format the end of the page break not at the end of last data column which causes a printing issue (wrong pages edges).

### What are the steps to reproduce?
1. Load data from Xlsx file format.
2. Add page break somewhere.
3. Save the file to Xlsx format 

### Which versions of PhpSpreadsheet and PHP are affected?
```
PHP 7.2.16
```
```json
"name": "phpoffice/phpspreadsheet",
            "version": "1.6.0",
```

**Comment by aircokol** [comment]
>If this is still an issue for you, please try to help by debugging it further and sharing your results.
Thank you for your contributions.

I'm not sure anyone tried to reproduce it. I don't see any reaction from the team. Why the issue was closed I don't understand.

**Comment by oleibman** [comment]
Unable to duplicate problem, even running Php7.3 with PhpSpreadsheet 1.6.0. Leaving issue closed, removing stale label. If you have a spreadsheet which still demonstrates this issue, please upload it here or open a new issue.
