### ISSUE TITLE
NamedRanges still don't work

### ISSUE THREAD

**Issue by JasonNaughton** [PHPOffice/PhpSpreadsheet#989]
I have a spreadsheet that I can load without any issues with phpspreadsheet.  I can access cells throughout the spreadsheet without any issues if I directly reference the cell (ie E1, D5).  I've embedded named ranges such as:

BA1c
DataSheet!E12

When I attempt to:

$ranges = $excel->getNamedRanges()

$ranges is empty and should contain an array of named ranges within the given worksheet.

I even attempted to fetch the namedrange as:

$namedRange = $excel->getNamedRange('BA1c',$excel->getActiveSheet());

$namedRange is empty but should contain DataSheet!E12 or simply E12.

I'm using php 7.2 and phpspreadsheet 1.6.0

Cheers

**Comment by epoxa** [comment]
I confirm the issue. I got empty array from getNamedRanges() in case of ods file. When loading the same workbook from xlsx name ranges are present though

**Comment by oleibman** [comment]
For the following spreadsheet:

[issue.989.ods](https://github.com/user-attachments/files/28650234/issue.989.ods)

The following code seems to be working properly now:
```php
use PhpOffice\PhpSpreadsheet\Reader\Ods as OdsReader;

class issue989
{
    public static function issue(): void
    {
        $reader = new OdsReader();
        $spreadsheet = $reader->load('issue.989.ods');
        var_dump($spreadsheet->getNamedRanges());
        $sheet = $spreadsheet->getActiveSheet();
        var_dump($sheet->getCell('A1')->getValue());
        var_dump($sheet->getCell('A1')->getCalculatedValue());
    }
}

issue989::issue();
```

Leaving issue closed, removing stale label.
