### ISSUE TITLE
Form Controls

### ISSUE THREAD

**Issue by connorhu** [PHPOffice/PhpSpreadsheet#990]
This is:

```
- [ x ] a feature request
```

Is there any plan for implement Form Controls?
I started to refactoring the PHPWord component and I have plan for create the Form Controls as a 3rd party component library which should be usable in PhpSpreadsheet and PhpDocument library too. So I can help implement Form Controls of the ODF specification (readers and writers).

**Comment by MarkBaker** [comment]
I've never looked that closely at form controls in Excel, but happy to accept a PR; although support for VBA macros attached to form controls seems pretty difficult

**Comment by oleibman** [comment]
Limited support for form controls was added at the end of 2022 by PR #3130. Leaving issue closed, removing stale label.
