### ISSUE TITLE
Calculation INDEX function fails with arrayValue range of cells, rowNum 0

### ISSUE THREAD

**Issue by bonfire-dev** [PHPOffice/PhpSpreadsheet#992]
This is:

```
- [x] a bug report
- [ ] a feature request
- [x] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```

### What is the expected behavior?
Calculation engine INDEX function returns array of cells when given nested arrayValues (range of cells), rowNum 0, and valid columnNum (>0, within range of column keys)

### What is the current behavior?
INDEX function issues warning error of the form "Undefined index: A" (depending on columnNum) and returns NULL

### What are the steps to reproduce?

Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of code that exhibits the issue without relying on an external Excel file or a web server:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

// Create new Spreadsheet object
$spreadsheet = new \PhpOffice\PhpSpreadsheet\Spreadsheet();

// add code that show the issue here...
$spreadsheet->getActiveSheet()->setCellValue('A1', '1');
$spreadsheet->getActiveSheet()->setCellValue('B1', '2');
$spreadsheet->getActiveSheet()->setCellValue('C3', '=SUM(INDEX(A1:B2, 0, 2))');
$spreadsheet->getActiveSheet()->getCell('C3')->getCalculatedValue();
```

When I encountered this, I was in a rather complicated case, but I think this is sufficient to reproduce. INDEX in Calculation/LookupRef.php gets an arrayValues keyed by rowKeys (1, 2, etc), which have values of arrays that are keyed by columns (A, B, etc). However, on line 624 (in 1.6.0, might be slightly different now. Case is when rowNum = 0 and colNum is valid), there is an attempt made to access $arrayValues[$columnNum] (after columnNum has been transformed into a letter), which fails, because $arrayValues keys are row numbers. You'd need to transform $arrayValues to be grouped by column keys, indexed by row number, before you can do an access like that.

### Which versions of PhpSpreadsheet and PHP are affected?
PHP 7.0 (sorry, working on upgrading to 7.3, so we have to port from PHPExcel, but I suspect this can be reproduced in higher versions), PhpSpreadsheet 1.6.0

**Comment by MagicStino** [comment]
example works flawless in latest version
