### ISSUE TITLE
 49/5000 problem with 'y' axis when there are negative values

### ISSUE THREAD

**Issue by eduardosegoviamartin** [PHPOffice/PhpSpreadsheet#995]
I have an issue that seems to be a bug.
When you create a chart with some negative values, the 'y' axis olverlaps over the chart and it does not keep on the left.
I found a workaround that fix this problem and may be help you in order to fix it in next releases.

Go to the PhpOffice/PhpSpreadsheet/Writer/Xlsx/Chart.php
Find next code:
     if ($id1 > 0) {
            $objWriter->startElement('c:crossAx');
            $objWriter->writeAttribute('val', $id2);
            $objWriter->endElement();
Replace with:
     if ($id1 > 0) {
            $objWriter->startElement('c:crossAx');
            $objWriter->writeAttribute('val', $id1);   
            $objWriter->endElement();

**Comment by luispalace** [comment]
Still not corrected on last version, I have to update it manually... thanks notariomayordelreino

**Comment by oleibman** [comment]
No file to test with. However ... both places in the current code base where `crossAx` is set are now consistent between the variable being tested and the variable being written to the chart, which was the suggested solution. Further, I altered 32readwritelineChart2.xlsx to give it a negative value on the y-axis, and ran the sample which processes it; the resulting output chart looks just as it should. So, leaving this issue closed, but removing the stale label.
